/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Legomena
 * Ontology-first companion API over Diogenes Laertius. A committed Turtle dataset (assertion ontology, annotation layer, bilingual passage texts) is loaded into an in-memory triple store at startup, and every endpoint is answered exclusively by querying that store: the knowledge graph is reconstructed from reified assertions, the reader renders stored text literals with the stored stand-off annotation layer, and Ask retrieves passages indexed from the dataset's own text literals, answering with cited assertions.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { AnnotationSpanLang } from './annotationSpanLang';

export interface AnnotationSpan {
  annotationUri: string;
  /** UTF-16 offset into the stored greekText (grc) or englishText (en) */
  start: number;
  end: number;
  lang: AnnotationSpanLang;
  /** The oa:exact quote stored in the TextQuoteSelector */
  exact: string;
  entityUri: string;
  entityLabel?: string;
  entityKind?: string;
  /** otv:ProperName body, when the annotation realizes a name */
  nameUri?: string;
  /** otv:Concept bodies a term annotation denotes */
  conceptUris?: string[];
}
