/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Legomena
 * Ontology-first companion API over Diogenes Laertius. A committed Turtle dataset (assertion ontology, annotation layer, bilingual passage texts) is loaded into an in-memory triple store at startup, and every endpoint is answered exclusively by querying that store: the knowledge graph is reconstructed from reified assertions, the reader renders stored text literals with the stored stand-off annotation layer, and Ask retrieves passages indexed from the dataset's own text literals, answering with cited assertions.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { AssertionKind } from './assertionKind';
import type { ChainLink } from './chainLink';
import type { ConflictRef } from './conflictRef';
import type { LinkOut } from './linkOut';

export interface Assertion {
  /** Claim URI, or a synthetic statement identifier for reified relations */
  uri: string;
  kind: AssertionKind;
  subjectUri: string;
  subjectLabel: string;
  predicateUri: string;
  /** rdfs:label of the predicate from the ontology TBox in the store */
  predicateLabel: string;
  objectUri?: string;
  objectLabel?: string;
  /** Literal object value, when the assertion's object is a literal */
  objectValue?: string;
  objectLang?: string;
  /** asserted, reported, disputed or conjectured (from lo:certainty) */
  certainty: string;
  /** Authorities D.L. names for the assertion */
  accordingTo?: LinkOut[];
  assertedInWork?: LinkOut;
  /** Transmission chain, outermost authority first */
  chain?: ChainLink[];
  conflictsWith?: ConflictRef[];
  citation: string;
  ref: string;
  sectionId?: string;
  /** Verbatim Greek excerpt carried by the claim, when curated */
  grc?: string;
  note?: string;
}
