/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Legomena
 * Ontology-first companion API over Diogenes Laertius. A committed Turtle dataset (assertion ontology, annotation layer, bilingual passage texts) is loaded into an in-memory triple store at startup, and every endpoint is answered exclusively by querying that store: the knowledge graph is reconstructed from reified assertions, the reader renders stored text literals with the stored stand-off annotation layer, and Ask retrieves passages indexed from the dataset's own text literals, answering with cited assertions.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { AnnotatedSectionRef } from './annotatedSectionRef';
import type { Assertion } from './assertion';
import type { LinkOut } from './linkOut';
import type { OntologyGraphEdge } from './ontologyGraphEdge';
import type { ProperName } from './properName';

export interface EntityDetail {
  uri: string;
  label: string;
  /** All ontology classes of the entity, qnames */
  kinds: string[];
  grcName?: string;
  book?: number;
  chapter?: string;
  schoolUri?: string;
  schoolLabel?: string;
  founderOf?: string;
  roles?: string[];
  properNames: ProperName[];
  sameAs: LinkOut[];
  seeAlso: LinkOut[];
  /** Principal doctrines, for school entities */
  doctrines?: LinkOut[];
  /** Assertions whose subject is this entity */
  assertions: Assertion[];
  /** Assertions whose object is this entity */
  mentions: Assertion[];
  /** Derived relation edges touching this entity */
  relations: OntologyGraphEdge[];
  annotatedSections: AnnotatedSectionRef[];
}
