/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Legomena
 * Ontology-first companion API over Diogenes Laertius. A committed Turtle dataset (assertion ontology, annotation layer, bilingual passage texts) is loaded into an in-memory triple store at startup, and every endpoint is answered exclusively by querying that store: the knowledge graph is reconstructed from reified assertions, the reader renders stored text literals with the stored stand-off annotation layer, and Ask retrieves passages indexed from the dataset's own text literals, answering with cited assertions.
 *
 * OpenAPI spec version: 0.1.0
 */

export * from './annotatedSectionRef';
export * from './annotationSpan';
export * from './annotationSpanLang';
export * from './answerLine';
export * from './askInput';
export * from './assertion';
export * from './assertionKind';
export * from './assertionStats';
export * from './chainLink';
export * from './conflictRef';
export * from './datasetFile';
export * from './datasetStats';
export * from './entityDetail';
export * from './entityList';
export * from './entitySummary';
export * from './errorMessage';
export * from './getEntityParams';
export * from './graphDerivation';
export * from './healthStatus';
export * from './linkOut';
export * from './listEntitiesParams';
export * from './listPassagesParams';
export * from './namedCount';
export * from './ontologyAnswer';
export * from './ontologyAnswerMode';
export * from './ontologyGraph';
export * from './ontologyGraphEdge';
export * from './ontologyGraphEdgeType';
export * from './ontologyGraphNode';
export * from './passageDetail';
export * from './passageList';
export * from './passageStats';
export * from './passageSummary';
export * from './properName';
export * from './retrievedPassage';
export * from './retrievedPassageSnippetLang';
export * from './sparqlCell';
export * from './sparqlCellTermType';
export * from './sparqlExample';
export * from './sparqlExampleList';
export * from './sparqlInput';
export * from './sparqlResult';
export * from './sparqlResultForm';
export * from './sparqlRow';
