/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Legomena
 * Ontology-first companion API over Diogenes Laertius. A committed Turtle dataset (assertion ontology, annotation layer, bilingual passage texts) is loaded into an in-memory triple store at startup, and every endpoint is answered exclusively by querying that store: the knowledge graph is reconstructed from reified assertions, the reader renders stored text literals with the stored stand-off annotation layer, and Ask retrieves passages indexed from the dataset's own text literals, answering with cited assertions.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { OntologyGraphEdgeType } from './ontologyGraphEdgeType';

export interface OntologyGraphEdge {
  /** Label of the subject philosopher */
  from: string;
  to: string;
  fromUri: string;
  toUri: string;
  type: OntologyGraphEdgeType;
  predicateUri: string;
  /** D.L. reference (book.section, Hicks numbering) */
  ref: string;
  /** Full bibliographic citation literal from the statement */
  citation: string;
  /** "asserted" when the store also holds the direct triple the statement reifies; "reported" when the relation exists only as a reification */
  certainty: string;
  /** Named authorities (lo:accordingTo) when the dataset records them, otherwise Diogenes Laertius himself */
  attribution: string;
  /** Corpus section id the citation resolves to, when unambiguous */
  sectionId?: string;
}
