/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Legomena
 * Ontology-first companion API over Diogenes Laertius. A committed Turtle dataset (assertion ontology, annotation layer, bilingual passage texts) is loaded into an in-memory triple store at startup, and every endpoint is answered exclusively by querying that store: the knowledge graph is reconstructed from reified assertions, the reader renders stored text literals with the stored stand-off annotation layer, and Ask retrieves passages indexed from the dataset's own text literals, answering with cited assertions.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface OntologyGraphNode {
  uri: string;
  name: string;
  /** Greek proper name form recorded for the entity, when unique */
  grcName?: string;
  /** School slug derived from the lo:memberOf URI */
  school: string;
  schoolUri: string;
  schoolLabel: string;
  book: number;
  chapter: string;
  /** Claims in the store whose rdf:subject is this node */
  claimCount: number;
  /** True when the node is classed lo:Sage (Book 1) */
  sage?: boolean;
}
