/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Legomena
 * Ontology-first companion API over Diogenes Laertius. A committed Turtle dataset (assertion ontology, annotation layer, bilingual passage texts) is loaded into an in-memory triple store at startup, and every endpoint is answered exclusively by querying that store: the knowledge graph is reconstructed from reified assertions, the reader renders stored text literals with the stored stand-off annotation layer, and Ask retrieves passages indexed from the dataset's own text literals, answering with cited assertions.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { RetrievedPassageSnippetLang } from './retrievedPassageSnippetLang';

export interface RetrievedPassage {
  sectionId: string;
  citation: string;
  rank: number;
  /** Fused retrieval score (reciprocal rank fusion) */
  score: number;
  lifeOf?: string;
  /** Short excerpt of the stored English (or Greek) text */
  snippet: string;
  snippetLang?: RetrievedPassageSnippetLang;
  annotationCount: number;
}
