/**
 * Curated claims from Book 3 of Diogenes Laertius' Lives, cited to
 * Hicks section ids (book.section). See kg-claims.ts for the model and
 * curation rules. Source-internal: every claim cites a D.L. passage.
 */
import type { KgClaim } from "../kg-claims";

export const BOOK3_CLAIMS: KgClaim[] = [
  // ----------------------------------------------------------------- Plato
  {
    id: "plato-birthplace-athens",
    subject: "Plato",
    property: "birthPlace",
    value: "Athens",
    valueType: "place",
    ref: "3.3",
    grc: "Πλάτων δὲ ἐπὶ Ἀμεινίου γέγονεν",
    certainty: "reported",
    conflictsWith: ["plato-birthplace-aegina"],
  },
  {
    id: "plato-deme-collytus",
    subject: "Plato",
    property: "deme",
    value: "Collytus",
    valueType: "literal",
    ref: "3.3",
    grc: "ἦν δὲ τῶν δήμων Κολλυτεύς",
    certainty: "reported",
    accordingTo: "Antileon",
    sourceWork: "On Dates",
    note: "Antileon states this in the second book of his On Dates.",
  },
  {
    id: "plato-birthplace-aegina",
    subject: "Plato",
    property: "birthPlace",
    value: "Aegina",
    valueType: "place",
    ref: "3.3",
    grc: "ἐγεννήθη κατά τινας ἐν Αἰγίνῃ",
    certainty: "reported",
    accordingTo: "Favorinus",
    note: "In the house of Phidiades, son of Thales; his father had been sent to settle there.",
    conflictsWith: ["plato-birthplace-athens"],
  },
  {
    id: "plato-birth-ol88",
    subject: "Plato",
    property: "birthDate",
    value: "Born in the 88th Olympiad, on the 7th of Thargelion (428/427 BCE)",
    valueType: "literal",
    ref: "3.2",
    grc: "Καὶ γίνεται Πλάτων, ὥς φησιν Ἀπολλόδωρος ἐν Χρονικοῖς, ὀγδόῃ καὶ ὀγδοηκοστῇ Ὀλυμπιάδι, Θαργηλιῶνος ἑβδόμῃ, καθʼ ἣν Δήλιοι τὸν Ἀπόλλωνα γενέσθαι φασί. τελευτᾷ δὲ—ὥς φησιν Ἕρμιππος, ἔν γάμοις δειπνῶν—τῷ πρώτῳ ἔτει τῆς ὀγδόης καὶ ἑκατοστῆς Ὀλυμπιάδος, βιοὺς ἔτος ἓν πρὸς τοῖς ὀγδοήκοντα.",
    certainty: "reported",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
  },
  {
    id: "plato-death-age-81",
    subject: "Plato",
    property: "deathDate",
    value:
      "Died in the first year of the 108th Olympiad, aged 81 (348/347 BCE)",
    valueType: "literal",
    ref: "3.2",
    grc: "Καὶ γίνεται Πλάτων, ὥς φησιν Ἀπολλόδωρος ἐν Χρονικοῖς, ὀγδόῃ καὶ ὀγδοηκοστῇ Ὀλυμπιάδι, Θαργηλιῶνος ἑβδόμῃ, καθʼ ἣν Δήλιοι τὸν Ἀπόλλωνα γενέσθαι φασί. τελευτᾷ δὲ—ὥς φησιν Ἕρμιππος, ἔν γάμοις δειπνῶν—τῷ πρώτῳ ἔτει τῆς ὀγδόης καὶ ἑκατοστῆς Ὀλυμπιάδος, βιοὺς ἔτος ἓν πρὸς τοῖς ὀγδοήκοντα.",
    certainty: "reported",
    conflictsWith: ["plato-death-age-84"],
  },
  {
    id: "plato-death-age-84",
    subject: "Plato",
    property: "deathDate",
    value: "Died at the age of 84",
    valueType: "literal",
    ref: "3.3",
    grc: "Νεάνθης δέ φησιν αὐτὸν τεττάρων καὶ ὀγδοήκοντα τελευτῆσαι ἐτῶν",
    certainty: "reported",
    accordingTo: "Neanthes",
    conflictsWith: ["plato-death-age-81"],
  },
  {
    id: "plato-death-manner",
    subject: "Plato",
    property: "mannerOfDeath",
    value: "Died at a wedding feast",
    valueType: "literal",
    ref: "3.2",
    grc: "τελευτᾷ δὲ—ὥς φησιν Ἕρμιππος, ἔν γάμοις δειπνῶν—τῷ πρώτῳ ἔτει τῆς ὀγδόης καὶ ἑκατοστῆς Ὀλυμπιάδος, βιοὺς ἔτος ἓν πρὸς τοῖς ὀγδοήκοντα.",
    certainty: "reported",
    accordingTo: "Hermippus",
  },
  {
    id: "plato-travel-cyrene",
    subject: "Plato",
    property: "traveledTo",
    value: "Cyrene",
    valueType: "place",
    ref: "3.6",
    grc: "ἔπειτα εἰς Κυρήνην ἀπῆλθε πρὸς Θεόδωρον τὸν μαθηματικόν",
    certainty: "asserted",
    note: "To Theodorus the mathematician.",
  },
  {
    id: "plato-travel-italy",
    subject: "Plato",
    property: "traveledTo",
    value: "Italy",
    valueType: "place",
    ref: "3.6",
    grc: "ἔπειτα εἰς Κυρήνην ἀπῆλθε πρὸς Θεόδωρον τὸν μαθηματικόν",
    certainty: "asserted",
    note: "To the Pythagoreans Philolaus and Eurytus.",
  },
  {
    id: "plato-travel-egypt",
    subject: "Plato",
    property: "traveledTo",
    value: "Egypt",
    valueType: "place",
    ref: "3.6",
    grc: "ἔπειτα εἰς Κυρήνην ἀπῆλθε πρὸς Θεόδωρον τὸν μαθηματικόν",
    certainty: "asserted",
    note: "To the prophets.",
  },
  {
    id: "plato-wrote-republic",
    subject: "Plato",
    property: "wrote",
    value: "Republic",
    valueType: "work",
    ref: "3.57",
    grc: "Πολιτείας εἰς δέκα διαιρουμένης — ἣν καὶ εὑρίσκεσθαι σχεδὸν ὅλην παρὰ Πρωταγόρᾳ ἐν τοῖς Ἀντιλογικοῖς φησι Φαβωρῖνος ἐν Π",
    certainty: "asserted",
    note: "Aristoxenus says nearly the whole of it is found in the Controversies of Protagoras (3.37).",
  },
  {
    id: "plato-wrote-alcyon",
    subject: "Plato",
    property: "wrote",
    value: "Alcyon",
    valueType: "work",
    ref: "3.62",
    grc: "ὧν ἡ Ἀλκυὼν Λέοντός τινος εἶναι δοκεῖ,",
    certainty: "disputed",
    accordingTo: "Favorinus",
    note: "Thought to be the work of a certain Leon.",
  },
  {
    id: "plato-parentage",
    subject: "Plato",
    property: "parentage",
    value:
      "Son of Ariston, a citizen of Athens; his mother Perictione (or Potone) traced her descent to Solon",
    valueType: "literal",
    ref: "3.1",
    grc: "Πλάτων, Ἀρίστωνος καὶ Περικτιόνης — ἢ Πωτώνης,— Ἀθηναῖος, ἥτις τὸ γένος ἀνέφερεν εἰς Σόλωνα",
    certainty: "asserted",
    note: "Plato was in the sixth generation from Solon; his father was said to be in the direct line from Codrus.",
  },
  {
    id: "plato-name-story",
    subject: "Plato",
    property: "education",
    value:
      "Originally named Aristocles after his grandfather; received the name Plato from his robust figure (or the breadth of his style or forehead)",
    valueType: "literal",
    ref: "3.4",
    grc: "Καὶ ἐπαιδεύθη μὲν γράμματα παρὰ Διονυσίῳ, οὗ καὶ μνημονεύει ἐν τοῖς Ἀντερασταῖς",
    certainty: "reported",
    accordingTo: "Alexander",
    sourceWork: "Successions of Philosophers",
    note: "The name from robust figure per Alexander in his Successions; from breadth of style/forehead per Neanthes.",
  },
  {
    id: "plato-education-letters",
    subject: "Plato",
    property: "education",
    value: "Taught letters in the school of Dionysius and gymnastics under Ariston the Argive wrestler",
    valueType: "literal",
    ref: "3.4",
    grc: "Καὶ ἐπαιδεύθη μὲν γράμματα παρὰ Διονυσίῳ, οὗ καὶ μνημονεύει ἐν τοῖς Ἀντερασταῖς",
    certainty: "asserted",
  },
  {
    id: "plato-studied-socrates",
    subject: "Plato",
    property: "studiedUnder",
    value: "Socrates",
    valueType: "philosopher",
    ref: "3.6",
    grc: "τοὐντεῦθεν δὴ γεγονώς, φασίν, εἴκοσιν ἔτη διήκουσε Σωκράτους",
    certainty: "asserted",
    note: "From his twentieth year he was the pupil of Socrates.",
  },
  {
    id: "plato-studied-cratylus",
    subject: "Plato",
    property: "studiedUnder",
    value: "Cratylus the Heraclitean",
    valueType: "person",
    ref: "3.6",
    grc: "τοὐντεῦθεν δὴ γεγονώς, φασίν, εἴκοσιν ἔτη διήκουσε Σωκράτους",
    certainty: "asserted",
    note: "After Socrates' death; also to Hermogenes who professed the philosophy of Parmenides.",
  },
  {
    id: "plato-studied-euclides",
    subject: "Plato",
    property: "studiedUnder",
    value: "Euclides",
    valueType: "philosopher",
    ref: "3.6",
    grc: "τοὐντεῦθεν δὴ γεγονώς, φασίν, εἴκοσιν ἔτη διήκουσε Σωκράτους",
    certainty: "reported",
    accordingTo: "Hermodorus",
    note: "At age twenty-eight he withdrew to Megara to Euclides with other disciples of Socrates.",
  },
  {
    id: "plato-affiliation-academy",
    subject: "Plato",
    property: "affiliatedWith",
    value: "Academy (Plato)",
    valueType: "school",
    ref: "3.41",
    grc: "ὅθεν καὶ Ἀκαδημαϊκὴ προσηγορεύθη ἡ ἀπʼ αὐτοῦ αἵρεσις",
    certainty: "asserted",
    note: "He was buried in the Academy, where the school he founded was called the Academic school.",
  },
  {
    id: "plato-lived-academy",
    subject: "Plato",
    property: "livedIn",
    value: "Academy",
    valueType: "place",
    ref: "3.7",
    grc: "ἐπανελθὼν δὲ εἰς Ἀθήνας διέτριβεν ἐν Ἀκαδημείᾳ",
    certainty: "asserted",
    note: "A gymnasium outside the walls, in a grove named after the hero Hecademus.",
  },
  {
    id: "plato-travel-megara",
    subject: "Plato",
    property: "traveledTo",
    value: "Megara",
    valueType: "place",
    ref: "3.6",
    grc: "ἔπειτα εἰς Κυρήνην ἀπῆλθε πρὸς Θεόδωρον τὸν μαθηματικόν",
    certainty: "asserted",
    note: "To Euclides, with other disciples of Socrates.",
  },
  {
    id: "plato-travel-sicily",
    subject: "Plato",
    property: "traveledTo",
    value: "Sicily",
    valueType: "place",
    ref: "3.18",
    grc: "Δοκεῖ δὲ Πλάτων καὶ τὰ Σώφρονος τοῦ μιμογράφου βιβλία ἠμελημένα πρῶτος εἰς Ἀθήνας διακομίσαι καὶ ἠθοποιῆσαι πρὸς αὐτόν",
    certainty: "asserted",
    note: "He made three voyages to Sicily; first to see the island and Etna, later to the courts of the two Dionysii.",
  },
  {
    id: "plato-death-lice",
    subject: "Plato",
    property: "mannerOfDeath",
    value: "Died of a disease of lice (phthiriasis)",
    valueType: "literal",
    ref: "3.40",
    grc: "Μυρωνιανὸς δʼ ἐν Ὁμοίοις φησὶ Φίλωνα παροιμίας μνημονεύειν περὶ τῶν Πλάτωνος φθειρῶν, ὡς οὕτως αὐτοῦ τελευτήσαντος.",
    certainty: "reported",
    accordingTo: "Myronianus",
    note: "Philo mentions proverbs about Plato's lice, implying this was the mode of his death.",
    conflictsWith: ["plato-death-manner"],
  },
  // -- Doctrines
  {
    id: "plato-doctrine-soul-immortal",
    subject: "Plato",
    property: "heldDoctrine",
    value:
      "The soul is immortal and, by transmigration, puts on many bodies",
    valueType: "doctrine",
    ref: "3.67",
    grc: "ἀθάνατον ἔλεγε τὴν ψυχὴν καὶ πολλὰ μεταμφιεννυμένην σώματα",
    certainty: "asserted",
  },
  {
    id: "plato-doctrine-soul-tripartite",
    subject: "Plato",
    property: "heldDoctrine",
    value:
      "The soul is tripartite: rational in the head, passionate about the heart, appetitive about the navel and liver",
    valueType: "doctrine",
    ref: "3.67",
    grc: "αὐτοκίνητόν τε εἶναι καὶ τριμερῆ· τὸ μὲν γὰρ αὐτῆς λογιστικὸν μέρος περὶ τῇ κεφαλῇ καθιδρῦσθαι, τὸ δὲ θυμοειδὲς περὶ τῇ καρδίᾳ, τὸ δὲ ἐπιθυμητικὸν περὶ τὸν ὀμφαλὸν καὶ τὸ ἧπαρ συνίστασθαι.",
    certainty: "asserted",
  },
  {
    id: "plato-doctrine-two-principles",
    subject: "Plato",
    property: "heldDoctrine",
    value:
      "There are two universal principles, God and matter; God is mind and cause, matter is formless and unlimited",
    valueType: "doctrine",
    ref: "3.69",
    grc: "δύο δὲ τῶν πάντων ἀπέφηνεν ἀρχάς, θεὸν καὶ ὕλην, ὃν καὶ νοῦν προσαγορεύει καὶ αἴτιον. εἶναι δὲ τὴν ὕλην ἀσχημάτιστον καὶ ἄπειρον, ἐξ ἧς γίνεσθαι τὰ συγκρίματα.",
    certainty: "asserted",
  },
  {
    id: "plato-doctrine-ideas",
    subject: "Plato",
    property: "heldDoctrine",
    value:
      "The Ideas are causes and principles whereby the world of natural objects is what it is; things resemble the Ideas as copies of archetypes",
    valueType: "doctrine",
    ref: "3.77",
    grc: "τὰς δὲ ἰδέας ὑφίσταται, καθὰ καὶ προείρηται, αἰτίας τινὰς καὶ ἀρχὰς τοῦ τοιαῦτʼ εἶναι τὰ φύσει συνεστῶτα, οἷάπερ ἐστὶν αὐτά.",
    certainty: "asserted",
    greek: "ἰδέα",
  },
  {
    id: "plato-doctrine-assimilation-god",
    subject: "Plato",
    property: "heldDoctrine",
    value: "The end to aim at is assimilation to God",
    valueType: "doctrine",
    ref: "3.78",
    grc: "τέλος μὲν εἶναι τὴν ἐξομοίωσιν τῷ θεῷ.",
    certainty: "asserted",
    greek: "ὁμοίωσις θεῷ",
  },
  {
    id: "plato-doctrine-virtue-sufficient",
    subject: "Plato",
    property: "heldDoctrine",
    value:
      "Virtue is in itself sufficient for happiness, though it needs bodily and external advantages as instruments",
    valueType: "doctrine",
    ref: "3.78",
    grc: "τὴν δʼ ἀρετὴν αὐτάρκη μὲν εἶναι πρὸς εὐδαιμονίαν. ὀργάνων δὲ προσδεῖσθαι τῶν περὶ σῶμα πλεονεκτημάτων, ἰσχύος, ὑγιείας, εὐαισθησίας, τῶν ὁμοίων·",
    certainty: "asserted",
    greek: "εὐδαιμονία",
  },
  {
    id: "plato-doctrine-created-cosmos",
    subject: "Plato",
    property: "heldDoctrine",
    value:
      "There is one created, animate universe, made by God, spherical and imperishable",
    valueType: "doctrine",
    ref: "3.71",
    grc: "Κόσμον τε εἶναι ἕνα γεννητόν, ἐπειδὴ καὶ αἰσθητός ἐστιν ὑπὸ θεοῦ κατεσκευασμένος· ἔμψυχόν τε εἶναι διὰ τὸ κρεῖττον εἶναι τοῦ ἀψύχου τὸ ἔμψυχον",
    certainty: "asserted",
  },
  // -- Works: the tetralogies as Thrasylus organized them (3.57-3.60)
  {
    id: "plato-wrote-euthyphro",
    subject: "Plato",
    property: "wrote",
    value: "Euthyphro, or On Holiness",
    valueType: "work",
    ref: "3.58",
    grc: "ἡγεῖται Εὐθύφρων ἢ περὶ ὁσίου",
    certainty: "asserted",
    note: "First tetralogy; a tentative dialogue.",
  },
  {
    id: "plato-wrote-apology",
    subject: "Plato",
    property: "wrote",
    value: "Apology of Socrates",
    valueType: "work",
    ref: "3.58",
    grc: "δεύτερος Ἀπολογία Σωκράτους,",
    certainty: "asserted",
    note: "First tetralogy; an ethical dialogue.",
  },
  {
    id: "plato-wrote-crito",
    subject: "Plato",
    property: "wrote",
    value: "Crito, or On what is to be done",
    valueType: "work",
    ref: "3.58",
    grc: "τρίτος Κρίτων ἢ περὶ πρακτέου,",
    certainty: "asserted",
    note: "First tetralogy; ethical.",
  },
  {
    id: "plato-wrote-phaedo",
    subject: "Plato",
    property: "wrote",
    value: "Phaedo, or On the Soul",
    valueType: "work",
    ref: "3.58",
    grc: "τέταρτος Φαίδων ἢ περὶ ψυχῆς,",
    certainty: "asserted",
    note: "First tetralogy; ethical.",
  },
  {
    id: "plato-wrote-cratylus",
    subject: "Plato",
    property: "wrote",
    value: "Cratylus, or On Correctness of Names",
    valueType: "work",
    ref: "3.58",
    grc: "ἧς ἡγεῖται Κρατύλος ἢ περὶ ὀρθότητος ὀνομάτων,",
    certainty: "asserted",
    note: "Second tetralogy; a logical dialogue.",
  },
  {
    id: "plato-wrote-theaetetus",
    subject: "Plato",
    property: "wrote",
    value: "Theaetetus, or On Knowledge",
    valueType: "work",
    ref: "3.58",
    grc: "Θεαίτητος ἢ περὶ ἐπιστήμης, πειραστικός",
    certainty: "asserted",
    note: "Second tetralogy; tentative.",
  },
  {
    id: "plato-wrote-sophist",
    subject: "Plato",
    property: "wrote",
    value: "Sophist, or On Being",
    valueType: "work",
    ref: "3.58",
    grc: "Σοφιστὴς ἢ περὶ τοῦ ὄντος, λογικός",
    certainty: "asserted",
    note: "Second tetralogy; a logical dialogue.",
  },
  {
    id: "plato-wrote-statesman",
    subject: "Plato",
    property: "wrote",
    value: "Statesman, or On Monarchy",
    valueType: "work",
    ref: "3.58",
    grc: "Πολιτικὸς ἢ περὶ βασιλείας, λογικός",
    certainty: "asserted",
    note: "Second tetralogy; logical.",
  },
  {
    id: "plato-wrote-parmenides",
    subject: "Plato",
    property: "wrote",
    value: "Parmenides, or On Ideas",
    valueType: "work",
    ref: "3.58",
    grc: "τῆς τρίτης ἡγεῖται Παρμενίδης ἢ περὶ ἰδεῶν,",
    certainty: "asserted",
    note: "Third tetralogy; logical.",
  },
  {
    id: "plato-wrote-philebus",
    subject: "Plato",
    property: "wrote",
    value: "Philebus, or On Pleasure",
    valueType: "work",
    ref: "3.58",
    grc: "Φίληβος ἢ περὶ ἡδονῆς, ἠθικός",
    certainty: "asserted",
    note: "Third tetralogy; ethical.",
  },
  {
    id: "plato-wrote-symposium",
    subject: "Plato",
    property: "wrote",
    value: "The Banquet, or On the Good",
    valueType: "work",
    ref: "3.58",
    grc: "Συμπόσιον ἢ περὶ ἀγαθοῦ, ἠθικός",
    certainty: "asserted",
    note: "Third tetralogy; ethical (the Symposium).",
  },
  {
    id: "plato-wrote-phaedrus",
    subject: "Plato",
    property: "wrote",
    value: "Phaedrus, or On Love",
    valueType: "work",
    ref: "3.58",
    grc: "Φαῖδρος ἢ περὶ ἔρωτος, ἠθικός.",
    certainty: "asserted",
    note: "Third tetralogy; ethical. A story says the Phaedrus was his first dialogue (3.38).",
  },
  {
    id: "plato-wrote-alcibiades-1",
    subject: "Plato",
    property: "wrote",
    value: "Alcibiades, or On the Nature of Man",
    valueType: "work",
    ref: "3.59",
    grc: "Τῆς τετάρτης ἡγεῖται Ἀλκιβιάδης ἢ περὶ ἀνθρώπου φύσεως, μαιευτικός",
    certainty: "asserted",
    note: "Fourth tetralogy; an obstetric dialogue.",
  },
  {
    id: "plato-wrote-alcibiades-2",
    subject: "Plato",
    property: "wrote",
    value: "Second Alcibiades, or On Prayer",
    valueType: "work",
    ref: "3.59",
    grc: "Ἀλκιβιάδης δεύτερος ἢ περὶ εὐχῆς, μαιευτικός",
    certainty: "asserted",
    note: "Fourth tetralogy; obstetric.",
  },
  {
    id: "plato-wrote-hipparchus",
    subject: "Plato",
    property: "wrote",
    value: "Hipparchus, or The Lover of Gain",
    valueType: "work",
    ref: "3.59",
    grc: "Ἵππαρχος ἢ φιλοκερδής, ἠθικός",
    certainty: "asserted",
    note: "Fourth tetralogy; ethical.",
  },
  {
    id: "plato-wrote-rivals",
    subject: "Plato",
    property: "wrote",
    value: "The Rivals, or On Philosophy",
    valueType: "work",
    ref: "3.59",
    grc: "Ἀντερασταὶ ἢ περὶ φιλοσοφίας, ἠθικός",
    certainty: "asserted",
    note: "Fourth tetralogy; ethical.",
  },
  {
    id: "plato-wrote-theages",
    subject: "Plato",
    property: "wrote",
    value: "Theages, or On Philosophy",
    valueType: "work",
    ref: "3.59",
    grc: "τῆς πέμπτης ἡγεῖται Θεάγης ἢ περὶ φιλοσοφίας, μαιευτικός",
    certainty: "asserted",
    note: "Fifth tetralogy; an obstetric dialogue.",
  },
  {
    id: "plato-wrote-charmides",
    subject: "Plato",
    property: "wrote",
    value: "Charmides, or On Temperance",
    valueType: "work",
    ref: "3.59",
    grc: "Χαρμίδης ἢ περὶ σωφροσύνης, πειραστικός",
    certainty: "asserted",
    note: "Fifth tetralogy; tentative.",
  },
  {
    id: "plato-wrote-laches",
    subject: "Plato",
    property: "wrote",
    value: "Laches, or On Courage",
    valueType: "work",
    ref: "3.59",
    grc: "Λάχης ἢ περὶ ἀνδρείας, μαιευτικός",
    certainty: "asserted",
    note: "Fifth tetralogy; obstetric.",
  },
  {
    id: "plato-wrote-lysis",
    subject: "Plato",
    property: "wrote",
    value: "Lysis, or On Friendship",
    valueType: "work",
    ref: "3.59",
    grc: "Λύσις ἢ περὶ φιλίας, μαιευτικός",
    certainty: "asserted",
    note: "Fifth tetralogy; obstetric. Socrates on hearing it read exclaimed how many lies this young man tells about me (3.35).",
  },
  {
    id: "plato-wrote-euthydemus",
    subject: "Plato",
    property: "wrote",
    value: "Euthydemus, or The Eristic",
    valueType: "work",
    ref: "3.59",
    grc: "τῆς ἕκτης ἡγεῖται Εὐθύδημος ἢ ἐριστικός, ἀνατρεπτικός",
    certainty: "asserted",
    note: "Sixth tetralogy; a refutative dialogue.",
  },
  {
    id: "plato-wrote-protagoras",
    subject: "Plato",
    property: "wrote",
    value: "Protagoras, or Sophists",
    valueType: "work",
    ref: "3.59",
    grc: "Πρωταγόρας ἢ σοφισταί, ἐνδεικτικός",
    certainty: "asserted",
    note: "Sixth tetralogy; critical.",
  },
  {
    id: "plato-wrote-gorgias",
    subject: "Plato",
    property: "wrote",
    value: "Gorgias, or On Rhetoric",
    valueType: "work",
    ref: "3.59",
    grc: "Γοργίας ἢ περὶ ῥητορικῆς, ἀνατρεπτικός",
    certainty: "asserted",
    note: "Sixth tetralogy; refutative.",
  },
  {
    id: "plato-wrote-meno",
    subject: "Plato",
    property: "wrote",
    value: "Meno, or On Virtue",
    valueType: "work",
    ref: "3.59",
    grc: "Μένων ἢ περὶ ἀρετῆς, πειραστικός.",
    certainty: "asserted",
    note: "Sixth tetralogy; tentative.",
  },
  {
    id: "plato-wrote-hippias-major",
    subject: "Plato",
    property: "wrote",
    value: "Hippias (major), or On Beauty",
    valueType: "work",
    ref: "3.60",
    grc: "Ἱππίαι δύο — α′ ἢ περὶ τοῦ καλοῦ",
    certainty: "asserted",
    note: "Seventh tetralogy; refutative.",
  },
  {
    id: "plato-wrote-hippias-minor",
    subject: "Plato",
    property: "wrote",
    value: "Hippias (minor), or On Falsehood",
    valueType: "work",
    ref: "3.60",
    grc: "β′ ἢ περὶ τοῦ ψεύδους",
    certainty: "asserted",
    note: "Seventh tetralogy; refutative.",
  },
  {
    id: "plato-wrote-ion",
    subject: "Plato",
    property: "wrote",
    value: "Ion, or On the Iliad",
    valueType: "work",
    ref: "3.60",
    grc: "Ἴων ἢ περὶ Ἰλιάδος, πειραστικός",
    certainty: "asserted",
    note: "Seventh tetralogy; tentative.",
  },
  {
    id: "plato-wrote-menexenus",
    subject: "Plato",
    property: "wrote",
    value: "Menexenus, or The Funeral Oration",
    valueType: "work",
    ref: "3.60",
    grc: "Μενέξενος ἢ ἐπιτάφιος, ἠθικός",
    certainty: "asserted",
    note: "Seventh tetralogy; ethical.",
  },
  {
    id: "plato-wrote-clitophon",
    subject: "Plato",
    property: "wrote",
    value: "Clitophon, or Introduction",
    valueType: "work",
    ref: "3.60",
    grc: "τῆς ὀγδόης ἡγεῖται Κλειτοφῶν ἢ προτρεπτικός, ἠθικός",
    certainty: "asserted",
    note: "Eighth tetralogy; ethical.",
  },
  {
    id: "plato-wrote-timaeus",
    subject: "Plato",
    property: "wrote",
    value: "Timaeus, or On Nature",
    valueType: "work",
    ref: "3.60",
    grc: "Τίμαιος ἢ περὶ φύσεως, φυσικός",
    certainty: "asserted",
    note: "Eighth tetralogy; a physical treatise. Physics is represented by the Timaeus (3.50).",
  },
  {
    id: "plato-wrote-critias",
    subject: "Plato",
    property: "wrote",
    value: "Critias, or Story of Atlantis",
    valueType: "work",
    ref: "3.60",
    grc: "Κριτίας ἢ Ἀτλαντικός, ἠθικός",
    certainty: "asserted",
    note: "Eighth tetralogy; ethical.",
  },
  {
    id: "plato-wrote-minos",
    subject: "Plato",
    property: "wrote",
    value: "Minos, or On Law",
    valueType: "work",
    ref: "3.60",
    grc: "τῆς ἐνάτης ἡγεῖται Μίνως ἢ περὶ νόμου, πολιτικός",
    certainty: "asserted",
    note: "Ninth tetralogy; a political dialogue.",
  },
  {
    id: "plato-wrote-laws",
    subject: "Plato",
    property: "wrote",
    value: "Laws, or On Legislation",
    valueType: "work",
    ref: "3.60",
    grc: "Νόμοι ἢ περὶ νομοθεσίας, πολιτικός",
    certainty: "asserted",
    note: "Ninth tetralogy; political. Reckoned as twelve books (3.57).",
  },
  {
    id: "plato-wrote-epinomis",
    subject: "Plato",
    property: "wrote",
    value: "Epinomis, or Nocturnal Council",
    valueType: "work",
    ref: "3.60",
    grc: "Ἐπινομὶς ἢ νυκτερινὸς σύλλογος ἢ φιλόσοφος, πολιτικός",
    certainty: "asserted",
    note: "Ninth tetralogy; political. Said to have been added by Philippus of Opus (3.37).",
  },
  {
    id: "plato-wrote-epistles",
    subject: "Plato",
    property: "wrote",
    value: "Epistles (thirteen in number)",
    valueType: "work",
    ref: "3.61",
    grc: "ἐν αἷς ἔγραφεν εὖ πράττειν, Ἐπίκουρος δὲ εὖ διάγειν, Κλέων χαίρειν — πρὸς Ἀριστόδημον μία, πρὸς Ἀρχύταν δύο, πρὸς Διονύσιον τέτταρες, πρὸς Ἑρμίαν καὶ Ἔραστον καὶ Κορίσκον μία, πρὸς Λεωδάμαντα μία, πρὸς Δίωνα μία, πρὸς Περδίκκαν μία, πρὸς τοὺς Δίωνος οἰκείους δύο",
    certainty: "asserted",
    note: "Ninth tetralogy; ethical; heading was 'Welfare'.",
  },
  // -- Works acknowledged spurious (3.62)
  {
    id: "plato-wrote-midon",
    subject: "Plato",
    property: "wrote",
    value: "Midon, or Horse-breeder",
    valueType: "work",
    ref: "3.62",
    grc: "νοθεύονται δὲ τῶν διαλόγων ὁμολογουμένως Μίδων ἢ Ἱπποτρόφος,",
    certainty: "disputed",
    note: "Acknowledged to be spurious.",
  },
  {
    id: "plato-wrote-eryxias",
    subject: "Plato",
    property: "wrote",
    value: "Eryxias, or Erasistratus",
    valueType: "work",
    ref: "3.62",
    grc: "Ἐρυξίας ἢ Ἐρασίστρατος,",
    certainty: "disputed",
    note: "Acknowledged to be spurious.",
  },
  {
    id: "plato-wrote-acephali",
    subject: "Plato",
    property: "wrote",
    value: "Acephali, or Sisyphus",
    valueType: "work",
    ref: "3.62",
    grc: "Ἀκέφαλοι ἢ Σίσυφος,",
    certainty: "disputed",
    note: "Acknowledged to be spurious.",
  },
  {
    id: "plato-wrote-axiochus",
    subject: "Plato",
    property: "wrote",
    value: "Axiochus",
    valueType: "work",
    ref: "3.62",
    grc: "Ἀξίοχος,",
    certainty: "disputed",
    note: "Acknowledged to be spurious.",
  },
  {
    id: "plato-wrote-phaeacians",
    subject: "Plato",
    property: "wrote",
    value: "The Phaeacians",
    valueType: "work",
    ref: "3.62",
    grc: "Φαίακες,",
    certainty: "disputed",
    note: "Acknowledged to be spurious.",
  },
  {
    id: "plato-wrote-demodocus",
    subject: "Plato",
    property: "wrote",
    value: "Demodocus",
    valueType: "work",
    ref: "3.62",
    grc: "Δημόδοκος,",
    certainty: "disputed",
    note: "Acknowledged to be spurious.",
  },
  {
    id: "plato-wrote-chelidon",
    subject: "Plato",
    property: "wrote",
    value: "Chelidon",
    valueType: "work",
    ref: "3.62",
    grc: "Χελιδών,",
    certainty: "disputed",
    note: "Acknowledged to be spurious.",
  },
  {
    id: "plato-wrote-seventh-day",
    subject: "Plato",
    property: "wrote",
    value: "The Seventh Day",
    valueType: "work",
    ref: "3.62",
    grc: "Ἑβδόμη,",
    certainty: "disputed",
    note: "Acknowledged to be spurious.",
  },
  {
    id: "plato-wrote-epimenides",
    subject: "Plato",
    property: "wrote",
    value: "Epimenides",
    valueType: "work",
    ref: "3.62",
    grc: "Ἐπιμενίδης",
    certainty: "disputed",
    note: "Acknowledged to be spurious.",
  },
];
