/**
 * Curated claims from Book 4 of Diogenes Laertius' Lives, cited to
 * Hicks section ids (book.section). See kg-claims.ts for the model and
 * curation rules. Source-internal: every claim cites a D.L. passage.
 */
import type { KgClaim } from "../kg-claims";

export const BOOK4_CLAIMS: KgClaim[] = [
  // ------------------------------------------------------------ Speusippus
  {
    id: "speusippus-parentage",
    subject: "Speusippus",
    property: "parentage",
    value:
      "An Athenian, son of Eurymedon of the deme Myrrhinus and of Potone, Plato's sister",
    valueType: "literal",
    ref: "4.1",
    grc: "διεδέξατο δʼ αὐτὸν Σπεύσιππος Εὐρυμέδοντος Ἀθηναῖος, τῶν μὲν δήμων Μυρρινούσιος, υἱὸς δὲ τῆς ἀδελφῆς αὐτοῦ Πωτώνης",
    certainty: "asserted",
  },
  {
    id: "speusippus-birthplace-athens",
    subject: "Speusippus",
    property: "birthPlace",
    value: "Athens",
    valueType: "place",
    ref: "4.1",
    grc: "διεδέξατο δʼ αὐτὸν Σπεύσιππος Εὐρυμέδοντος Ἀθηναῖος, τῶν μὲν δήμων Μυρρινούσιος, υἱὸς δὲ τῆς ἀδελφῆς αὐτοῦ Πωτώνης",
    certainty: "asserted",
  },
  {
    id: "speusippus-studied-plato",
    subject: "Speusippus",
    property: "studiedUnder",
    value: "Plato",
    valueType: "philosopher",
    ref: "4.1",
    grc: "τὰ μὲν περὶ Πλάτωνος τοσαῦτα ἦν ἐς τὸ δυνατὸν ἡμῖν συναγαγεῖν, φιλοπόνως διειλήσασι τὰ λεγόμενα περὶ τἀνδρός",
    certainty: "asserted",
    note: "He adhered faithfully to Plato's doctrines, whom he succeeded.",
  },
  {
    id: "speusippus-affiliation-academy",
    subject: "Speusippus",
    property: "affiliatedWith",
    value: "Academy",
    valueType: "school",
    ref: "4.1",
    grc: "καὶ ἐσχολάρχησεν ἔτη ὀκτώ, ἀρξάμενος ἀπὸ τῆς ὀγδόης καὶ ἑκατοστῆς Ὀλυμπιάδος",
    certainty: "asserted",
    note: "Head of the school for eight years, beginning in the 108th Olympiad.",
  },
  {
    id: "speusippus-death-manner",
    subject: "Speusippus",
    property: "mannerOfDeath",
    value:
      "In old age, despondent and crippled by paralysis, he put an end to his life",
    valueType: "literal",
    ref: "4.3",
    grc: "καὶ τέλος ὑπὸ ἀθυμίας ἑκὼν τὸν βίον μετήλλαξε γηραιὸς ὤν.",
    certainty: "asserted",
    conflictsWith: ["speusippus-death-lice"],
  },
  {
    id: "speusippus-death-lice",
    subject: "Speusippus",
    property: "mannerOfDeath",
    value: "His malady was morbus pedicularis (a disease of lice)",
    valueType: "literal",
    ref: "4.4",
    grc: "Πλούταρχος δέ φησιν ἐν τῷ Λυσάνδρου βίῳ καὶ Σύλλα φθειρσὶν ἐκζέσαι αὐτόν.",
    certainty: "reported",
    accordingTo: "Plutarch",
    sourceWork: "Life of Lysander and Sulla",
    note: "That his body wasted away is affirmed by Timotheus in his book On Lives.",
    conflictsWith: ["speusippus-death-manner"],
  },
  {
    id: "speusippus-headship-ol108",
    subject: "Speusippus",
    property: "birthDate",
    value:
      "Was head of the school for eight years beginning in the 108th Olympiad (348/345 BCE)",
    valueType: "literal",
    ref: "4.1",
    grc: "καὶ ἐσχολάρχησεν ἔτη ὀκτώ, ἀρξάμενος ἀπὸ τῆς ὀγδόης καὶ ἑκατοστῆς Ὀλυμπιάδος",
    certainty: "asserted",
  },
  {
    id: "speusippus-wrote-on-wealth",
    subject: "Speusippus",
    property: "wrote",
    value: "On Wealth (1 book)",
    valueType: "work",
    ref: "4.4",
    grc: "Περὶ πλούτου α′",
    certainty: "asserted",
  },
  {
    id: "speusippus-wrote-on-pleasure",
    subject: "Speusippus",
    property: "wrote",
    value: "On Pleasure (1 book)",
    valueType: "work",
    ref: "4.4",
    grc: "Περὶ ἡδονῆς α′",
    certainty: "asserted",
  },
  {
    id: "speusippus-wrote-on-justice",
    subject: "Speusippus",
    property: "wrote",
    value: "On Justice",
    valueType: "work",
    ref: "4.4",
    grc: "Περὶ δικαιοσύνης α′",
    certainty: "asserted",
  },
  {
    id: "speusippus-wrote-on-philosophy",
    subject: "Speusippus",
    property: "wrote",
    value: "On Philosophy",
    valueType: "work",
    ref: "4.4",
    grc: "Περὶ φιλοσοφίας α′",
    certainty: "asserted",
  },
  {
    id: "speusippus-wrote-on-friendship",
    subject: "Speusippus",
    property: "wrote",
    value: "On Friendship",
    valueType: "work",
    ref: "4.4",
    grc: "Περὶ φιλίας α′",
    certainty: "asserted",
  },
  {
    id: "speusippus-wrote-on-the-gods",
    subject: "Speusippus",
    property: "wrote",
    value: "On the Gods",
    valueType: "work",
    ref: "4.4",
    grc: "Περὶ θεῶν α′",
    certainty: "asserted",
  },
  {
    id: "speusippus-wrote-the-philosopher",
    subject: "Speusippus",
    property: "wrote",
    value: "The Philosopher",
    valueType: "work",
    ref: "4.4",
    grc: "Φιλόσοφος α′",
    certainty: "asserted",
  },
  {
    id: "speusippus-wrote-eulogy-of-plato",
    subject: "Speusippus",
    property: "wrote",
    value: "Eulogy of Plato",
    valueType: "work",
    ref: "4.5",
    grc: "Πλάτωνος ἐγκώμιον",
    certainty: "asserted",
  },
  {
    id: "speusippus-wrote-on-legislation",
    subject: "Speusippus",
    property: "wrote",
    value: "On Legislation",
    valueType: "work",
    ref: "4.5",
    grc: "Περὶ γενῶν καὶ εἰδῶν παραδειγμάτων",
    certainty: "asserted",
  },
  {
    id: "speusippus-wrote-definitions",
    subject: "Speusippus",
    property: "wrote",
    value: "Definitions",
    valueType: "work",
    ref: "4.5",
    grc: "Ὅροι",
    certainty: "asserted",
  },
  {
    id: "speusippus-writings-lines",
    subject: "Speusippus",
    property: "writings",
    value:
      "Left a vast store of memoirs and numerous dialogues comprising in all 43,475 lines",
    valueType: "literal",
    ref: "4.5",
    grc: "Ἀρίστιππος α′",
    certainty: "asserted",
    note: "Favorinus relates that Aristotle purchased his works for three talents.",
  },

  // ------------------------------------------------------------ Xenocrates
  {
    id: "xenocrates-parentage",
    subject: "Xenocrates",
    property: "parentage",
    value: "Son of Agathenor",
    valueType: "literal",
    ref: "4.6",
    grc: "Ξενοκράτης Ἀγαθήνορος Χαλκηδόνιος",
    certainty: "asserted",
  },
  {
    id: "xenocrates-birthplace-chalcedon",
    subject: "Xenocrates",
    property: "birthPlace",
    value: "Chalcedon",
    valueType: "place",
    ref: "4.6",
    grc: "Ξενοκράτης Ἀγαθήνορος Χαλκηδόνιος",
    certainty: "asserted",
  },
  {
    id: "xenocrates-studied-plato",
    subject: "Xenocrates",
    property: "studiedUnder",
    value: "Plato",
    valueType: "philosopher",
    ref: "4.6",
    grc: "οὗτος ἐκ νέου Πλάτωνος ἤκουσεν, ἀλλὰ καὶ εἰς Σικελίαν αὐτῷ συναπεδήμησεν",
    certainty: "asserted",
    note: "A pupil of Plato from his earliest youth; he accompanied him to Sicily.",
  },
  {
    id: "xenocrates-affiliation-academy",
    subject: "Xenocrates",
    property: "affiliatedWith",
    value: "Academy",
    valueType: "school",
    ref: "4.14",
    grc: "διεδέξατο δὲ Σπεύσιππον καὶ ἀφηγήσατο τῆς σχολῆς πέντε καὶ εἴκοσιν ἔτη ἐπὶ Λυσιμαχίδου ἀρξάμενος κατὰ τὸ δεύτερον ἔτος τῆς δεκάτης καὶ ἑκατοστῆς Ὀλυμπιάδος",
    certainty: "asserted",
    note: "He succeeded Speusippus and was head of the school for twenty-five years, from the 110th Olympiad.",
  },
  {
    id: "xenocrates-death-fall",
    subject: "Xenocrates",
    property: "mannerOfDeath",
    value:
      "Died in his 82nd year from the effects of a fall over a bronze vessel in the night",
    valueType: "literal",
    ref: "4.14",
    grc: "ἐτελεύτα δὲ νυκτὸς λεκάνῃ προσπταίσας, ἔτος ἤδη γεγονὼς δεύτερον καὶ ὀγδοηκοστόν.",
    certainty: "asserted",
  },
  {
    id: "xenocrates-headship-ol110",
    subject: "Xenocrates",
    property: "birthDate",
    value:
      "Succeeded Speusippus and was head of the school for twenty-five years from the archonship of Lysimachides, beginning in the second year of the 110th Olympiad (339/338 BCE)",
    valueType: "literal",
    ref: "4.14",
    grc: "διεδέξατο δὲ Σπεύσιππον καὶ ἀφηγήσατο τῆς σχολῆς πέντε καὶ εἴκοσιν ἔτη ἐπὶ Λυσιμαχίδου ἀρξάμενος κατὰ τὸ δεύτερον ἔτος τῆς δεκάτης καὶ ἑκατοστῆς Ὀλυμπιάδος",
    certainty: "asserted",
  },
  {
    id: "xenocrates-wrote-on-nature",
    subject: "Xenocrates",
    property: "wrote",
    value: "On Nature (6 books)",
    valueType: "work",
    ref: "4.11",
    grc: "Περὶ φύσεως α′ β′ γ′ δ′ ε′ ς′",
    certainty: "asserted",
  },
  {
    id: "xenocrates-wrote-on-wisdom",
    subject: "Xenocrates",
    property: "wrote",
    value: "On Wisdom (6 books)",
    valueType: "work",
    ref: "4.11",
    grc: "Περὶ σοφίας ς′",
    certainty: "asserted",
  },
  {
    id: "xenocrates-wrote-on-the-good",
    subject: "Xenocrates",
    property: "wrote",
    value: "On the Good",
    valueType: "work",
    ref: "4.13",
    grc: "Περὶ τἀγαθοῦ α′",
    certainty: "asserted",
  },
  {
    id: "xenocrates-wrote-on-ideas",
    subject: "Xenocrates",
    property: "wrote",
    value: "On Ideas",
    valueType: "work",
    ref: "4.12",
    grc: "Περὶ ἰδεῶν α′.",
    certainty: "asserted",
  },
  {
    id: "xenocrates-wrote-on-the-soul",
    subject: "Xenocrates",
    property: "wrote",
    value: "On the Soul (2 books)",
    valueType: "work",
    ref: "4.13",
    grc: "Περὶ ψυχῆς α′ β′",
    certainty: "asserted",
  },
  {
    id: "xenocrates-wrote-on-philosophy",
    subject: "Xenocrates",
    property: "wrote",
    value: "On Philosophy",
    valueType: "work",
    ref: "4.13",
    grc: "Περὶ φιλοσοφίας α′",
    certainty: "asserted",
  },
  {
    id: "xenocrates-wrote-on-the-gods",
    subject: "Xenocrates",
    property: "wrote",
    value: "On the Gods (2 books)",
    valueType: "work",
    ref: "4.13",
    grc: "Περὶ θεῶν α′ β′",
    certainty: "asserted",
  },
  {
    id: "xenocrates-wrote-on-the-writings-of-parmenides",
    subject: "Xenocrates",
    property: "wrote",
    value: "On the Writings of Parmenides",
    valueType: "work",
    ref: "4.13",
    grc: "Περὶ τῶν Παρμενίδου α′",
    certainty: "asserted",
  },
  {
    id: "xenocrates-wrote-solution-of-logical-problems",
    subject: "Xenocrates",
    property: "wrote",
    value: "Solution of Logical Problems (10 books)",
    valueType: "work",
    ref: "4.13",
    grc: "Λύσις τῶν περὶ τοὺς λόγους ι′",
    certainty: "asserted",
  },
  {
    id: "xenocrates-wrote-elementary-principles-monarchy",
    subject: "Xenocrates",
    property: "wrote",
    value:
      "Elementary Principles of Monarchy (4 books, dedicated to Alexander)",
    valueType: "work",
    ref: "4.14",
    grc: "Στοιχεῖα πρὸς Ἀλέξανδρον περὶ βασιλείας δ",
    certainty: "asserted",
  },
  {
    id: "xenocrates-writings-lines",
    subject: "Xenocrates",
    property: "writings",
    value:
      "Left a very large number of treatises, poems and addresses comprising in all 224,239 lines",
    valueType: "literal",
    ref: "4.14",
    grc: "Στοιχεῖα πρὸς Ἀλέξανδρον περὶ βασιλείας δ",
    certainty: "asserted",
  },

  // ---------------------------------------------------------------- Polemo
  {
    id: "polemo-parentage",
    subject: "Polemo",
    property: "parentage",
    value: "Son of Philostratus, an Athenian of the deme of Oea",
    valueType: "literal",
    ref: "4.16",
    grc: "Πολέμων Φιλοστράτου μὲν ἦν υἱός, Ἀθηναῖος τῶν δήμων Οἴηθεν",
    certainty: "asserted",
  },
  {
    id: "polemo-birthplace-athens",
    subject: "Polemo",
    property: "birthPlace",
    value: "Athens",
    valueType: "place",
    ref: "4.16",
    grc: "Πολέμων Φιλοστράτου μὲν ἦν υἱός, Ἀθηναῖος τῶν δήμων Οἴηθεν",
    certainty: "asserted",
  },
  {
    id: "polemo-studied-xenocrates",
    subject: "Polemo",
    property: "studiedUnder",
    value: "Xenocrates",
    valueType: "philosopher",
    ref: "4.16",
    grc: "Πολέμων Φιλοστράτου μὲν ἦν υἱός, Ἀθηναῖος τῶν δήμων Οἴηθεν",
    certainty: "asserted",
    note: "Converted from a profligate life by Xenocrates' discourse on temperance; became head of the school in the 116th Olympiad.",
  },
  {
    id: "polemo-affiliation-academy",
    subject: "Polemo",
    property: "affiliatedWith",
    value: "Academy",
    valueType: "school",
    ref: "4.16",
    grc: "εἰς τὴν Ξενοκράτους ᾖξε σχολήν",
    certainty: "asserted",
  },
  {
    id: "polemo-doctrine-facts-not-logic",
    subject: "Polemo",
    property: "heldDoctrine",
    value:
      "We should exercise ourselves with facts and not with mere logical speculations",
    valueType: "doctrine",
    ref: "4.18",
    grc: "ἔφασκε δὲ ὁ Πολέμων δεῖν ἐν τοῖς πράγμασι γυμνάζεσθαι καὶ μὴ ἐν τοῖς διαλεκτικοῖς θεωρήμασι",
    certainty: "asserted",
  },
  {
    id: "polemo-death-decay",
    subject: "Polemo",
    property: "mannerOfDeath",
    value: "Died at an advanced age of gradual decay",
    valueType: "literal",
    ref: "4.20",
    grc: "Ἐτελεύτησε δὲ γηραιὸς ἤδη ὑπὸ φθίσεως, ἱκανὰ συγγράμματα καταλιπών.",
    certainty: "asserted",
  },
  {
    id: "polemo-headship-ol116",
    subject: "Polemo",
    property: "birthDate",
    value: "Rose to be head of the school in the 116th Olympiad (316/313 BCE)",
    valueType: "literal",
    ref: "4.16",
    grc: "ἀκοῦον δὴ τὸ μειράκιον κατʼ ὀλίγον ἐθηράθη καὶ οὕτως ἐγένετο φιλόπονος ὡς ὑπερβάλλεσθαι τοὺς ἅλλους καὶ αὐτὸς διαδέξασθαι τὴν σχολήν, ἀρξάμενος ἀπὸ τῆς ἕκτης καὶ δεκάτης καὶ ἑκατοστῆς Ὀλυμπιάδος.",
    certainty: "asserted",
  },

  // --------------------------------------------------------- Crates of Athens
  {
    id: "crates-athens-parentage",
    subject: "Crates of Athens",
    property: "parentage",
    value: "Son of Antigenes, an Athenian of the deme of Thria",
    valueType: "literal",
    ref: "4.21",
    grc: "Κράτης πατρὸς μὲν ἦν Ἀντιγένους 〈Ἀθηναῖοσ〉, Θριάσιος δὲ τῶν δήμων, ἀκροατὴς ἅμα καὶ ἐρώμενος Πολέμωνος",
    certainty: "asserted",
  },
  {
    id: "crates-athens-birthplace-athens",
    subject: "Crates of Athens",
    property: "birthPlace",
    value: "Athens",
    valueType: "place",
    ref: "4.21",
    grc: "Κράτης πατρὸς μὲν ἦν Ἀντιγένους 〈Ἀθηναῖοσ〉, Θριάσιος δὲ τῶν δήμων, ἀκροατὴς ἅμα καὶ ἐρώμενος Πολέμωνος",
    certainty: "asserted",
  },
  {
    id: "crates-athens-studied-polemo",
    subject: "Crates of Athens",
    property: "studiedUnder",
    value: "Polemo",
    valueType: "philosopher",
    ref: "4.21",
    grc: "Κράτης πατρὸς μὲν ἦν Ἀντιγένους 〈Ἀθηναῖοσ〉, Θριάσιος δὲ τῶν δήμων, ἀκροατὴς ἅμα καὶ ἐρώμενος Πολέμωνος",
    certainty: "asserted",
    note: "A pupil and favourite of Polemo, whom he succeeded in the headship; they shared the same tomb.",
  },
  {
    id: "crates-athens-affiliation-academy",
    subject: "Crates of Athens",
    property: "affiliatedWith",
    value: "Academy",
    valueType: "school",
    ref: "4.21",
    grc: "ἀλλὰ καὶ διεδέξατο τὴν σχολὴν αὐτοῦ",
    certainty: "asserted",
  },
  {
    id: "crates-athens-wrote-philosophical",
    subject: "Crates of Athens",
    property: "writings",
    value:
      "Left works of a philosophical kind, others on comedy, and speeches delivered in the assembly or on embassy",
    valueType: "literal",
    ref: "4.23",
    grc: "Τελευτῶν δὲ ὁ Κράτης, καθά φησιν Ἀπολλόδωρος ἐν τρίτῳ τῶν Χρονικῶν, ἀπέλιπε βιβλία τὰ μὲν φιλοσοφούμενα, τὰ δὲ περὶ κωμῳδίας, τὰ δὲ λόγους δημηγορικοὺς καὶ πρεσβευτικούς",
    certainty: "reported",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
  },

  // --------------------------------------------------------------- Crantor
  {
    id: "crantor-birthplace-soli",
    subject: "Crantor",
    property: "birthPlace",
    value: "Soli",
    valueType: "place",
    ref: "4.24",
    grc: "Κράντωρ Σολεὺς θαυμαζόμενος ἐν τῇ ἑαυτοῦ πατρίδι ἀπῆρεν εἰς Ἀθήνας καὶ Ξενοκράτους διήκουσε Πολέμωνι συσχολάζων",
    certainty: "asserted",
  },
  {
    id: "crantor-travel-athens",
    subject: "Crantor",
    property: "traveledTo",
    value: "Athens",
    valueType: "place",
    ref: "4.24",
    grc: "Κράντωρ Σολεὺς θαυμαζόμενος ἐν τῇ ἑαυτοῦ πατρίδι ἀπῆρεν εἰς Ἀθήνας καὶ Ξενοκράτους διήκουσε Πολέμωνι συσχολάζων",
    certainty: "asserted",
    note: "Left Soli for Athens to attend the lectures of Xenocrates.",
  },
  {
    id: "crantor-studied-xenocrates",
    subject: "Crantor",
    property: "studiedUnder",
    value: "Xenocrates",
    valueType: "philosopher",
    ref: "4.24",
    grc: "Κράντωρ Σολεὺς θαυμαζόμενος ἐν τῇ ἑαυτοῦ πατρίδι ἀπῆρεν εἰς Ἀθήνας καὶ Ξενοκράτους διήκουσε Πολέμωνι συσχολάζων",
    certainty: "asserted",
    note: "Attended the lectures of Xenocrates at the same time as Polemo; later a follower of Polemo.",
  },
  {
    id: "crantor-affiliation-academy",
    subject: "Crantor",
    property: "affiliatedWith",
    value: "Academy",
    valueType: "school",
    ref: "4.24",
    grc: "Κράντωρ Σολεὺς θαυμαζόμενος ἐν τῇ ἑαυτοῦ πατρίδι ἀπῆρεν εἰς Ἀθήνας καὶ Ξενοκράτους διήκουσε Πολέμωνι συσχολάζων",
    certainty: "asserted",
  },
  {
    id: "crantor-wrote-on-grief",
    subject: "Crantor",
    property: "wrote",
    value: "On Grief",
    valueType: "work",
    ref: "4.27",
    grc: "θαυμάζεται δὲ αὐτοῦ βιβλίον μάλιστα τὸ Περὶ πένθους",
    certainty: "asserted",
    note: "His most highly esteemed work.",
  },
  {
    id: "crantor-writings-lines",
    subject: "Crantor",
    property: "writings",
    value:
      "Left memoirs extending to 30,000 lines, some of them attributed by critics to Arcesilaus",
    valueType: "literal",
    ref: "4.24",
    grc: "Κράντωρ Σολεὺς θαυμαζόμενος ἐν τῇ ἑαυτοῦ πατρίδι ἀπῆρεν εἰς Ἀθήνας καὶ Ξενοκράτους διήκουσε Πολέμωνι συσχολάζων",
    certainty: "asserted",
  },
  {
    id: "crantor-death-dropsy",
    subject: "Crantor",
    property: "mannerOfDeath",
    value: "Died before Polemo and Crates, his end hastened by dropsy",
    valueType: "literal",
    ref: "4.27",
    grc: "καὶ κατέστρεψε πρὸ Πολέμωνος καὶ Κράτητος, ὑδρωπικῇ διαθέσει νοσήσας.",
    certainty: "asserted",
  },

  // ------------------------------------------------------------- Arcesilaus
  {
    id: "arcesilaus-parentage",
    subject: "Arcesilaus",
    property: "parentage",
    value: "Son of Seuthes, the youngest of four brothers",
    valueType: "literal",
    ref: "4.28",
    grc: "Ἀρκεσίλαος Σεύθου",
    certainty: "asserted",
  },
  {
    id: "arcesilaus-birthplace-pitane",
    subject: "Arcesilaus",
    property: "birthPlace",
    value: "Pitane",
    valueType: "place",
    ref: "4.28",
    grc: "Ἀρκεσίλαος Σεύθου 〈[ἢ Σκύθου], ὡς Ἀπολλόδωρος ἐν τρίτῳ Χρονικῶν〉, Πιτάνης τῆς Αἰολίδος",
    certainty: "reported",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
    note: "In Aeolis.",
  },
  {
    id: "arcesilaus-studied-crantor",
    subject: "Arcesilaus",
    property: "studiedUnder",
    value: "Crantor",
    valueType: "philosopher",
    ref: "4.29",
    grc: "ἤκουσε δὲ κατʼ ἀρχὰς μὲν Αὐτολύκου τοῦ μαθηματικοῦ πολίτου τυγχάνοντος, πρὶν ἀπαίρειν εἰς Ἀθήνας, μεθʼ οὗ καὶ εἰς Σάρδεις ἀπεδήμησεν",
    certainty: "asserted",
    note: "Crossed over to the Academy and joined Crantor, who was enamoured of him.",
  },
  {
    id: "arcesilaus-studied-theophrastus",
    subject: "Arcesilaus",
    property: "studiedUnder",
    value: "Theophrastus",
    valueType: "philosopher",
    ref: "4.29",
    grc: "ἤκουσε δὲ κατʼ ἀρχὰς μὲν Αὐτολύκου τοῦ μαθηματικοῦ πολίτου τυγχάνοντος, πρὶν ἀπαίρειν εἰς Ἀθήνας, μεθʼ οὗ καὶ εἰς Σάρδεις ἀπεδήμησεν",
    certainty: "asserted",
    note: "A pupil of Theophrastus before he went over to the Academy.",
  },
  {
    id: "arcesilaus-affiliation-academy",
    subject: "Arcesilaus",
    property: "affiliatedWith",
    value: "Academy",
    valueType: "school",
    ref: "4.28",
    grc: "Ἀρκεσίλαος Σεύθου 〈[ἢ Σκύθου], ὡς Ἀπολλόδωρος ἐν τρίτῳ Χρονικῶν〉, Πιτάνης τῆς Αἰολίδος",
    certainty: "asserted",
    note: "With him begins the Middle Academy.",
  },
  {
    id: "arcesilaus-doctrine-suspension",
    subject: "Arcesilaus",
    property: "heldDoctrine",
    value:
      "He was the first to suspend judgement owing to the contradictions of opposing arguments, arguing on both sides of a question",
    valueType: "doctrine",
    ref: "4.28",
    grc: "οὗτός ἐστιν ὁ τῆς μέσης Ἀκαδημείας κατάρξας, πρῶτος ἐπισχὼν τὰς ἀποφάσεις διὰ τὰς ἐναντιότητας τῶν λόγων. πρῶτος δὲ καὶ εἰς ἑκάτερον ἐπεχείρησε",
    certainty: "asserted",
    greek: "ἐποχή",
  },
  {
    id: "arcesilaus-writings-none",
    subject: "Arcesilaus",
    property: "writings",
    value:
      "One result of his suspending judgement was that he never so much as wrote a book",
    valueType: "literal",
    ref: "4.32",
    grc: "διὰ δὲ τὸ περὶ πάντων ἐπέχειν οὐδὲ βιβλίον, φασί τινες, συνέγραψεν",
    certainty: "reported",
    note: "According to some; others say he was caught revising works of Crantor.",
  },
  {
    id: "arcesilaus-death-wine",
    subject: "Arcesilaus",
    property: "mannerOfDeath",
    value:
      "Died through drinking too freely of unmixed wine, which affected his reason, aged seventy-five",
    valueType: "literal",
    ref: "4.44",
    grc: "Ἐτελεύτησε δέ, ὥς φησιν Ἕρμιππος, ἄκρατον ἐμφορηθεὶς πολὺν καὶ παρακόφας, ἤδη γεγονὼς ἔτος πέμπτον καὶ ἑβδομηκοστόν",
    certainty: "reported",
    accordingTo: "Hermippus",
  },
  {
    id: "arcesilaus-floruit-ol120",
    subject: "Arcesilaus",
    property: "birthDate",
    value: "Flourished about the 120th Olympiad (300/297 BCE)",
    valueType: "literal",
    ref: "4.45",
    grc: "Ὁ δὲ προειρημένος φιλόσοφος, καθά φησιν Ἀπολλόδωρος ἐν Χρονικοῖς, ἤκμαζε περὶ τὴν εἰκοστὴν καὶ ἑκατοστὴν Ὀλυμπιάδα.",
    certainty: "reported",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
  },

  // -------------------------------------------------------------------- Bion
  {
    id: "bion-birthplace-borysthenes",
    subject: "Bion",
    property: "birthPlace",
    value: "Borysthenes",
    valueType: "place",
    ref: "4.46",
    grc: "Βίων τὸ μὲν γένος ἦν Βορυσθενίτης, ὧντινων δὲ γονέων καὶ ἀφʼ οἵων πραγμάτων ἧξεν ἐπὶ φιλοσοφίαν, αὐτὸς Ἀντιγόνῳ διασαφεῖ",
    certainty: "asserted",
    note: "His father a freedman and dealer in salt fish; his mother from a brothel; sold with his family, then bought by a rhetorician.",
  },
  {
    id: "bion-parentage",
    subject: "Bion",
    property: "parentage",
    value:
      "Son of a freedman salt-fish dealer and a mother from a brothel; the family was sold into slavery",
    valueType: "literal",
    ref: "4.46",
    grc: "Βίων τὸ μὲν γένος ἦν Βορυσθενίτης, ὧντινων δὲ γονέων καὶ ἀφʼ οἵων πραγμάτων ἧξεν ἐπὶ φιλοσοφίαν, αὐτὸς Ἀντιγόνῳ διασαφεῖ",
    certainty: "asserted",
    note: "Bion told this himself to Antigonus.",
  },
  {
    id: "bion-studied-crates",
    subject: "Bion",
    property: "studiedUnder",
    value: "Crates of Athens",
    valueType: "philosopher",
    ref: "4.51",
    grc: "τοσοῦτον διαφέρειν τὴν φρόνησιν τῶν ἄλλων ἀρετῶν, ὅσον τὴν ὅρασιν τῶν ἄλλων αἰσθήσεων",
    certainty: "asserted",
    note: "At the outset he deprecated Academic doctrines while a pupil of Crates.",
  },
  {
    id: "bion-studied-theophrastus",
    subject: "Bion",
    property: "studiedUnder",
    value: "Theophrastus",
    valueType: "philosopher",
    ref: "4.52",
    grc: "καὶ τί γὰρ ἄλλο μετεσκεύασεν αὐτὸν πρὸς ἀπάθειαν; ἔπειτα ἐπὶ τὰ Θεοδώρεια μετῆλθε διακούσας Θεοδώρου τοῦ ἀθέου κατὰ πᾶν εἶδος λόγου σοφιστεύοντος",
    certainty: "asserted",
    note: "Attended the lectures of Theophrastus the Peripatetic; earlier adopted the Cynic discipline and Theodorean views.",
  },
  {
    id: "bion-affiliation-academy",
    subject: "Bion",
    property: "affiliatedWith",
    value: "Academy",
    valueType: "school",
    ref: "4.51",
    grc: "τοσοῦτον διαφέρειν τὴν φρόνησιν τῶν ἄλλων ἀρετῶν, ὅσον τὴν ὅρασιν τῶν ἄλλων αἰσθήσεων",
    certainty: "asserted",
    note: "Corpus classifies him under the Academy; he passed through Cynic, Theodorean and Peripatetic phases.",
  },
  {
    id: "bion-doctrine-atheism",
    subject: "Bion",
    property: "heldDoctrine",
    value: "He would vehemently assail belief in the gods",
    valueType: "doctrine",
    ref: "4.54",
    grc: "πολλὰ δὲ καὶ ἀθεώτερον προεφέρετο τοῖς ὁμιλοῦσι, τοῦτο Θεοδώρειον ἀπολαύσας.",
    certainty: "asserted",
    note: "A taste derived from Theodorus; on his deathbed he was said to repent of his offences against religion.",
  },
  {
    id: "bion-criticized-socrates",
    subject: "Bion",
    property: "criticized",
    value: "Socrates",
    valueType: "philosopher",
    ref: "4.49",
    grc: "διέβαλε δὲ καὶ τὸν Σωκράτην, λέγων ὡς εἰ μὲν εἶχεν Ἀλκιβιάδου χρείαν καὶ ἀπείχετο, μάταιος ἦν· εἰ δὲ μὴ εἶχεν, οὐδὲν ἐποίει παράδοξον.",
    certainty: "asserted",
    note: "Abused Socrates over his conduct towards Alcibiades.",
  },
  {
    id: "bion-death-chalcis",
    subject: "Bion",
    property: "deathPlace",
    value: "Chalcis",
    valueType: "place",
    ref: "4.54",
    grc: "καὶ ὕστερόν ποτε ἐμπεσὼν εἰς νόσον, ὡς ἔφασκον οἱ ἐν Χαλκίδι—αὐτόθι γὰρ καὶ κατέστρεψε—",
    certainty: "asserted",
    note: "Where he died after a lingering disease.",
  },

  // ------------------------------------------------------------------ Lacydes
  {
    id: "lacydes-parentage",
    subject: "Lacydes",
    property: "parentage",
    value: "Son of Alexander",
    valueType: "literal",
    ref: "4.59",
    grc: "Λακύδης Ἀλεξάνδρου Κυρηναῖος",
    certainty: "asserted",
  },
  {
    id: "lacydes-birthplace-cyrene",
    subject: "Lacydes",
    property: "birthPlace",
    value: "Cyrene",
    valueType: "place",
    ref: "4.59",
    grc: "Λακύδης Ἀλεξάνδρου Κυρηναῖος",
    certainty: "asserted",
  },
  {
    id: "lacydes-studied-arcesilaus",
    subject: "Lacydes",
    property: "studiedUnder",
    value: "Arcesilaus",
    valueType: "philosopher",
    ref: "4.59",
    grc: "οὗτός ἐστιν ὁ τῆς νέας Ἀκαδημείας κατάρξας καὶ Ἀρκεσίλαον διαδεξάμενος, ἀνὴρ σεμνότατος καὶ οὐκ ὀλίγους ἐσχηκὼς ζηλωτάς",
    certainty: "asserted",
    note: "The successor of Arcesilaus and founder of the New Academy.",
  },
  {
    id: "lacydes-affiliation-academy",
    subject: "Lacydes",
    property: "affiliatedWith",
    value: "Academy",
    valueType: "school",
    ref: "4.59",
    grc: "Λακύδης Ἀλεξάνδρου Κυρηναῖος",
    certainty: "asserted",
    note: "Founder of the New Academy; assumed the headship in the 134th Olympiad and led for twenty-six years.",
  },
  {
    id: "lacydes-death-palsy",
    subject: "Lacydes",
    property: "mannerOfDeath",
    value: "Died of a palsy brought on by drinking too freely",
    valueType: "literal",
    ref: "4.61",
    grc: "ἡ τελευτὴ δὲ αὐτῷ παράλυσις ἐκ πολυποσίας.",
    certainty: "asserted",
  },
  {
    id: "lacydes-headship-ol134",
    subject: "Lacydes",
    property: "birthDate",
    value:
      "Assumed the headship of the school in the fourth year of the 134th Olympiad (241/240 BCE), and at his death had been head for twenty-six years",
    valueType: "literal",
    ref: "4.61",
    grc: "Ἐτελεύτησε δὲ σχολαρχεῖν ἀρξάμενος τῷ τετάρτῳ ἔτει τῆς τετάρτης καὶ τριακοστῆς καὶ ἑκατοστῆς Ὀλυμπιάδος, τῆς σχολῆς ἀφηγησάμενος ἓξ πρὸς τοῖς εἴικοσιν ἔτη",
    certainty: "asserted",
  },

  // ---------------------------------------------------------------- Carneades
  {
    id: "carneades-parentage",
    subject: "Carneades",
    property: "parentage",
    value: "Son of Epicomus (or, according to Alexander, of Philocomus)",
    valueType: "literal",
    ref: "4.62",
    grc: "Καρνεάδης Ἐπικώμου ἢ Φιλοκώμου, ὡς Ἀλέξανδρος ἐν Διαδοχαῖς, Κυρηναῖος",
    certainty: "reported",
    accordingTo: "Alexander",
  },
  {
    id: "carneades-birthplace-cyrene",
    subject: "Carneades",
    property: "birthPlace",
    value: "Cyrene",
    valueType: "place",
    ref: "4.62",
    grc: "φιλόπονος δʼ ἄνθρωπος γέγονεν εἰ καί τις ἄλλος, ἐν μὲν τοῖς φυσικοῖς ἧττον φερόμενος, ἐν δὲ τοῖς ἠθικοῖς μᾶλλον",
    certainty: "asserted",
  },
  {
    id: "carneades-studied-hegesinus",
    subject: "Carneades",
    property: "studiedUnder",
    value: "Hegesinus of Pergamum",
    valueType: "person",
    ref: "4.60",
    grc: "Ὁ γοῦν Λακύδης ἐσχόλαζεν ἐν Ἀκαδημείᾳ ἐν τῷ κατασκευασθέντι κήπῳ ὑπὸ Ἀττάλου τοῦ βασιλέως, καὶ Λακύδειον ἀπʼ αὐτοῦ προσηγορεύετο",
    certainty: "asserted",
    note: "Carneades succeeded Hegesinus in the line from Lacydes.",
  },
  {
    id: "carneades-affiliation-academy",
    subject: "Carneades",
    property: "affiliatedWith",
    value: "Academy",
    valueType: "school",
    ref: "4.62",
    grc: "ὅθεν καὶ ἐκόμα καὶ ἔτρεφεν ὄνυχας ἀσχολίᾳ τῇ περὶ τοὺς λόγους. τοσοῦτον δʼ ἴσχυσεν ἐν φιλοσοφίᾳ, ὥστε καὶ τοὺς ῥήτορας ἀπολύσαντας ἐκ τῶν σχολῶν παρʼ αὐτὸν ἰέναι καὶ αὐτοῦ ἀκούειν.",
    certainty: "asserted",
  },
  {
    id: "carneades-criticized-chrysippus",
    subject: "Carneades",
    property: "criticized",
    value: "Chrysippus",
    valueType: "philosopher",
    ref: "4.62",
    grc: "οὗτος τὰ τῶν Στωικῶν βιβλία ἀναγνοὺς ἐπιμελῶς 〈καὶ μάλιστα〉 τὰ Χρυσίππου, ἐπιεικῶς αὐτοῖς ἀντέλεγε καὶ εὐημέρει τοσοῦτον, ὥστε ἐκεῖνο ἐπιλέγειν· εἰ μὴ γὰρ ἦν Χρύσιππος, οὐκ ἂν ἦν ἐγώ.",
    certainty: "asserted",
    note: "Studied the Stoics, especially Chrysippus, and became famous by combating them: 'Without Chrysippus where should I have been?'",
  },
  {
    id: "carneades-writings-none",
    subject: "Carneades",
    property: "writings",
    value:
      "He himself left nothing in writing; everything was compiled by his pupils",
    valueType: "literal",
    ref: "4.65",
    grc: "τὰ δὲ λοιπὰ αὐτοῦ οἱ μαθηταὶ συνέγραψαν",
    certainty: "asserted",
  },
  {
    id: "carneades-death-age-85",
    subject: "Carneades",
    property: "deathDate",
    value:
      "Departed this life in the fourth year of the 162nd Olympiad at the age of eighty-five (129/128 BCE)",
    valueType: "literal",
    ref: "4.65",
    grc: "Φησὶ δὲ Ἀπολλόδωρος ἐν Χρονικοῖς ἀπελθεῖν αὐτὸν ἐξ ἀνθρώπων ἔτει τετάρτῳ τῆς δευτέρας καὶ ἑξηκοστῆς καὶ ἑκατοστῆς Ὀλυμπιάδος, βιώσαντα ἔτη πέντε πρὸς τοῖς ὀγδοήκοντα",
    certainty: "reported",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
  },

  // --------------------------------------------------------------- Clitomachus
  {
    id: "clitomachus-birthplace-carthage",
    subject: "Clitomachus",
    property: "birthPlace",
    value: "Carthage",
    valueType: "place",
    ref: "4.67",
    grc: "Κλειτόμαχος Καρχηδόνιος",
    certainty: "asserted",
    note: "His real name was Hasdrubal; he taught philosophy at Carthage in his native tongue before going to Athens.",
  },
  {
    id: "clitomachus-travel-athens",
    subject: "Clitomachus",
    property: "traveledTo",
    value: "Athens",
    valueType: "place",
    ref: "4.67",
    grc: "Κλειτόμαχος Καρχηδόνιος",
    certainty: "asserted",
    note: "Went to Athens at forty and became a pupil of Carneades.",
  },
  {
    id: "clitomachus-studied-carneades",
    subject: "Clitomachus",
    property: "studiedUnder",
    value: "Carneades",
    valueType: "philosopher",
    ref: "4.67",
    grc: "ἐλθὼν δʼ εἰς Ἀθήνας ἤδη τετταράκοντʼ ἔτη γεγονὼς ἤκουσε Καρνεάδου",
    certainty: "asserted",
    note: "Succeeded Carneades in the headship and by his writings elucidated his opinions.",
  },
  {
    id: "clitomachus-affiliation-academy",
    subject: "Clitomachus",
    property: "affiliatedWith",
    value: "Academy",
    valueType: "school",
    ref: "4.67",
    grc: "Κλειτόμαχος Καρχηδόνιος",
    certainty: "asserted",
  },
  {
    id: "clitomachus-writings-treatises",
    subject: "Clitomachus",
    property: "writings",
    value: "Composed more than four hundred treatises",
    valueType: "literal",
    ref: "4.67",
    grc: "ὁ δὲ εἰς τοσοῦτον ἤλασεν ἐπιμελείας, ὥστε ὑπὲρ τὰ τετρακόσια βιβλία συνέγραψε",
    certainty: "asserted",
    note: "Well acquainted with the three sects: the Academy, the Peripatetics, and the Stoics.",
  },
];
