/**
 * Curated claims from Book 7 of Diogenes Laertius' Lives, cited to
 * Hicks section ids (book.section). See kg-claims.ts for the model and
 * curation rules. Source-internal: every claim cites a D.L. passage.
 */
import type { KgClaim } from "../kg-claims";

export const BOOK7_CLAIMS: KgClaim[] = [
  // ------------------------------------------------------- Zeno of Citium
  {
    id: "zeno-birthplace-citium",
    subject: "Zeno of Citium",
    property: "birthPlace",
    value: "Citium",
    valueType: "place",
    ref: "7.1",
    grc: "Τὸν τράχηλον ἐπὶ θάτερα νενευκὼς ἦν, ὥς φησι Τιμόθεος ὁ Ἀθηναῖος ἐν τῷ Περὶ βίων",
    certainty: "asserted",
    note: "A Greek city in Cyprus which had received Phoenician settlers.",
  },
  {
    id: "zeno-parentage-mnaseas",
    subject: "Zeno of Citium",
    property: "parentage",
    value: "Son of Mnaseas",
    valueType: "literal",
    ref: "7.1",
    grc: "Ζήνων Μνασέου ἢ Δημέου Κιτιεὺς ἀπὸ Κύπρου, πολίσματος Ἑλληνικοῦ, Φοίνικας ἐποίκους ἐσχηκότος",
    certainty: "reported",
    conflictsWith: ["zeno-parentage-demeas"],
  },
  {
    id: "zeno-parentage-demeas",
    subject: "Zeno of Citium",
    property: "parentage",
    value: "Son of Demeas",
    valueType: "literal",
    ref: "7.1",
    grc: "Ζήνων Μνασέου ἢ Δημέου Κιτιεὺς ἀπὸ Κύπρου, πολίσματος Ἑλληνικοῦ, Φοίνικας ἐποίκους ἐσχηκότος",
    certainty: "reported",
    conflictsWith: ["zeno-parentage-mnaseas"],
  },
  {
    id: "zeno-affiliated-stoa",
    subject: "Zeno of Citium",
    property: "affiliatedWith",
    value: "Stoa",
    valueType: "school",
    ref: "7.5",
    grc: "ἄλλοι δὲ διατρίβοντα ἐν ταῖς Ἀθήναις ἀκοῦσαι τὴν ναυαγίαν καὶ εἰπεῖν, εὖ γε ποιεῖ ἡ τύχη προσελαύνουσα ἡμᾶς φιλοσοφίᾳ",
    certainty: "asserted",
    note: "His followers were called men of the Stoa, or Stoics, from the painted colonnade (Stoa Poikile) where he taught; he was the founder of the School.",
  },
  {
    id: "zeno-teacher-crates",
    subject: "Zeno of Citium",
    property: "studiedUnder",
    value: "Crates of Thebes",
    valueType: "philosopher",
    ref: "7.2",
    grc: "Διήκουσε δέ, καθὰ προείρηται, Κράτητος",
    certainty: "asserted",
  },
  {
    id: "zeno-teacher-stilpo",
    subject: "Zeno of Citium",
    property: "studiedUnder",
    value: "Stilpo",
    valueType: "philosopher",
    ref: "7.2",
    grc: "Διήκουσε δέ, καθὰ προείρηται, Κράτητος",
    certainty: "reported",
    accordingTo: "Timocrates",
  },
  {
    id: "zeno-teacher-xenocrates",
    subject: "Zeno of Citium",
    property: "studiedUnder",
    value: "Xenocrates",
    valueType: "philosopher",
    ref: "7.2",
    grc: "Διήκουσε δέ, καθὰ προείρηται, Κράτητος",
    certainty: "reported",
    accordingTo: "Timocrates",
    note: "For ten years, per Timocrates in his Dion.",
  },
  {
    id: "zeno-teacher-polemo",
    subject: "Zeno of Citium",
    property: "studiedUnder",
    value: "Polemo",
    valueType: "philosopher",
    ref: "7.25",
    grc: "Συνδιέτριψε δὲ καὶ Διοδώρῳ, καθά φησιν Ἱππόβοτος",
    certainty: "reported",
  },
  {
    id: "zeno-lived-athens",
    subject: "Zeno of Citium",
    property: "livedIn",
    value: "Athens",
    valueType: "place",
    ref: "7.2",
    grc: "Διήκουσε δέ, καθὰ προείρηται, Κράτητος",
    certainty: "asserted",
    note: "Came to Athens at about the age of thirty after being shipwrecked on a voyage from Phoenicia to Peiraeus.",
  },
  {
    id: "zeno-wrote-republic",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Republic (Politeia)",
    valueType: "work",
    ref: "7.4",
    grc: "τὴν Πολιτείαν",
    certainty: "asserted",
    note: "Its authorship by Zeno is attested by Chrysippus in his De Republica (7.34).",
  },
  {
    id: "zeno-wrote-life-nature",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Of Life according to Nature",
    valueType: "work",
    ref: "7.4",
    grc: "Περὶ τοῦ κατὰ φύσιν βίου",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-impulse",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Of Impulse, or Human Nature",
    valueType: "work",
    ref: "7.4",
    grc: "Περὶ ὁρμῆς ἢ περὶ ἀνθρώπου φύσεως",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-emotions",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Of Emotions",
    valueType: "work",
    ref: "7.4",
    grc: "Περὶ παθῶν",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-duty",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Of Duty",
    valueType: "work",
    ref: "7.4",
    grc: "Περὶ τοῦ καθήκοντος",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-law",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Of Law",
    valueType: "work",
    ref: "7.4",
    grc: "Περὶ νόμου",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-greek-education",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Of Greek Education",
    valueType: "work",
    ref: "7.4",
    grc: "Περὶ τῆς Ἑλληνικῆς παιδείας",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-vision",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Of Vision",
    valueType: "work",
    ref: "7.4",
    grc: "Περὶ ὄψεως",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-whole-world",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Of the Whole World",
    valueType: "work",
    ref: "7.4",
    grc: "Περὶ τοῦ ὅλου",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-signs",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Of Signs",
    valueType: "work",
    ref: "7.4",
    grc: "Περὶ σημείων",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-pythagorean-questions",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Pythagorean Questions",
    valueType: "work",
    ref: "7.4",
    grc: "Πυθαγορικά",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-universals",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Universals",
    valueType: "work",
    ref: "7.4",
    grc: "Καθολικά",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-varieties-style",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Of Varieties of Style",
    valueType: "work",
    ref: "7.4",
    grc: "Περὶ λέξεων",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-homeric-problems",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Homeric Problems (5 books)",
    valueType: "work",
    ref: "7.4",
    grc: "Προβλημάτων Ὁμηρικῶν πέντε",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-reading-poetry",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Of the Reading of Poetry",
    valueType: "work",
    ref: "7.4",
    grc: "Περὶ ποιητικῆς ἀκροάσεως",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-handbook-rhetoric",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "A Handbook of Rhetoric",
    valueType: "work",
    ref: "7.4",
    grc: "Απομνημονεύματα Κράτητος",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-solutions",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Solutions",
    valueType: "work",
    ref: "7.4",
    grc: "Ἔστι δʼ αὐτοῦ καὶ Τέχνη καὶ Λύσεις καὶ Ἔλεγχοι δύο",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-refutations",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Refutations (2 books)",
    valueType: "work",
    ref: "7.4",
    grc: "Καὶ τάδε μὲν τὰ βιβλία",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-recollections-crates",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Recollections of Crates",
    valueType: "work",
    ref: "7.4",
    grc: "Απομνημονεύματα Κράτητος",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-ethics",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Ethics",
    valueType: "work",
    ref: "7.4",
    grc: "Ἠθικά",
    certainty: "asserted",
  },
  {
    id: "zeno-wrote-nature-of-man",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "On the Nature of Man",
    valueType: "work",
    ref: "7.87",
    grc: "Διόπερ πρῶτος ὁ Ζήνων ἐν τῷ Περὶ ἀνθρώπου φύσεως τέλος εἶπε τὸ ὁμολογουμένως τῇ φύσει ζῆν, ὅπερ ἐστὶ κατʼ ἀρετὴν ζῆν",
    certainty: "asserted",
    note: "The treatise in which he first designated the end as life in agreement with nature.",
  },
  {
    id: "zeno-wrote-exposition-doctrine",
    subject: "Zeno of Citium",
    property: "wrote",
    value: "Exposition of Doctrine",
    valueType: "work",
    ref: "7.39",
    grc: "Ταῦτα δὲ τὰ μέρη ὁ μὲν Ἀπολλόδωρος τόπους καλεῖ, ὁ δὲ Χρύσιππος καὶ Εὔδρομος εἴδη, ἄλλοι γένη.",
    certainty: "asserted",
    note: "The treatise in which he first divided philosophic doctrine into physical, ethical, and logical parts.",
  },
  {
    id: "zeno-death-age-98",
    subject: "Zeno of Citium",
    property: "deathDate",
    value: "Died at the age of 98",
    valueType: "literal",
    ref: "7.28",
    grc: "ὀκτὼ γὰρ πρὸς τοῖς ἐνενήκοντα βιοὺς ἔτη κατέστρεψεν",
    certainty: "reported",
    conflictsWith: ["zeno-death-age-72"],
  },
  {
    id: "zeno-death-age-72",
    subject: "Zeno of Citium",
    property: "deathDate",
    value: "Died at the age of 72",
    valueType: "literal",
    ref: "7.28",
    grc: "δύο καὶ ἑβδομήκοντα ἐτῶν τελευτῆσαι αὐτόν",
    certainty: "reported",
    accordingTo: "Persaeus",
    conflictsWith: ["zeno-death-age-98"],
  },
  {
    id: "zeno-old-man-ol130",
    subject: "Zeno of Citium",
    property: "birthDate",
    value:
      "Was already an old man in the 130th Olympiad (260/257 BCE), when his friend Persaeus flourished",
    valueType: "literal",
    ref: "7.6",
    grc: "ὁ δὲ τοῦτο μὲν παρῃτήσατο, Περσαῖον δʼ ἕνα τῶν γνωρίμων ἀπέστειλεν, ὃς ἦν Δημητρίου μὲν υἱός, Κιτιεὺς δὲ τὸ γένος, καὶ ἤκμαζε κατὰ τὴν τριακοστὴν καὶ ἑκατοστὴν Ὀλυμπιάδα, ἤδη γέροντος ὄντος Ζήνωνος",
    certainty: "asserted",
  },
  {
    id: "zeno-death-manner",
    subject: "Zeno of Citium",
    property: "mannerOfDeath",
    value:
      "Tripped and broke a toe leaving the school; struck the ground, quoted the Niobe, and died on the spot by holding his breath",
    valueType: "literal",
    ref: "7.28",
    grc: "ἐτελεύτα δὴ οὕτως· ἐκ τῆς σχολῆς ἀπιὼν προσέπταισε καὶ τὸν δάκτυλον περιέρρηξε· παίσας δὲ τὴν γῆν τῇ χειρί, φησὶ τὸ ἐκ τῆς Νιόβης, ἔρχομαι· τί μʼ αὔεις; καὶ παραχρῆμα ἐτελεύτησεν, ἀποπνίξας ἑαυτόν.",
    certainty: "asserted",
    conflictsWith: ["zeno-death-starvation"],
  },
  {
    id: "zeno-death-starvation",
    subject: "Zeno of Citium",
    property: "mannerOfDeath",
    value: "Died by ceasing to take food",
    valueType: "literal",
    ref: "7.31",
    grc: "τὸν Κιτιᾶ Ζήνωνα θανεῖν λόγος ὡς ὑπὸ γήρως πολλὰ καμὼν ἐλύθη μένων ἄσιτος",
    certainty: "reported",
    note: "One of the versions D.L. records in his Pammetros.",
    conflictsWith: ["zeno-death-manner"],
  },
  {
    id: "zeno-death-place-athens",
    subject: "Zeno of Citium",
    property: "deathPlace",
    value: "Athens",
    valueType: "place",
    ref: "7.29",
    grc: "Ἀθηναῖοι δʼ ἔθαψαν αὐτὸν ἐν τῷ Κεραμεικῷ καὶ ψηφίσμασι τοῖς προειρημένοις ἐτίμησαν, τὴν ἀρετὴν αὐτῷ προσμαρτυροῦντες.",
    certainty: "asserted",
    note: "The Athenians buried him in the Ceramicus at the public cost.",
  },
  // Zeno - principal Stoic doctrines (7.38-160 doxography)
  {
    id: "zeno-doctrine-division-philosophy",
    subject: "Zeno of Citium",
    property: "heldDoctrine",
    value:
      "Philosophic doctrine falls into three parts: physical, ethical, and logical",
    valueType: "doctrine",
    ref: "7.39",
    grc: "Τριμερῆ φασὶν εἶναι τὸν κατὰ φιλοσοφίαν λόγον· εἶναι γὰρ αὐτοῦ τὸ μέν τι φυσικόν, τὸ δὲ ἠθικόν, τὸ δὲ λογικόν. οὕτω δὲ πρῶτος διεῖλε Ζήνων ὁ Κιτιεὺς ἐν τῷ Περὶ λόγου",
    certainty: "asserted",
    note: "Zeno was the first to make this division, in his Exposition of Doctrine.",
  },
  {
    id: "zeno-doctrine-oikeiosis",
    subject: "Zeno of Citium",
    property: "heldDoctrine",
    value:
      "An animal's first impulse is to self-preservation, nature endearing it to itself from the outset",
    valueType: "doctrine",
    greek: "οἰκείωσις",
    ref: "7.85",
    grc: "Τὴν δὲ πρώτην ὁρμήν φασι τὸ ζῷον ἴσχειν ἐπὶ τὸ τηρεῖν ἑαυτό, οἰκειούσης αὑτῷ τῆς φύσεως ἀπʼ ἀρχῆς",
    certainty: "asserted",
  },
  {
    id: "zeno-doctrine-telos",
    subject: "Zeno of Citium",
    property: "heldDoctrine",
    value: "The end (telos) is life in agreement with nature",
    valueType: "doctrine",
    greek: "τέλος",
    ref: "7.87",
    grc: "Διόπερ πρῶτος ὁ Ζήνων ἐν τῷ Περὶ ἀνθρώπου φύσεως τέλος εἶπε τὸ ὁμολογουμένως τῇ φύσει ζῆν, ὅπερ ἐστὶ κατʼ ἀρετὴν ζῆν· ἄγει γὰρ πρὸς ταύτην ἡμᾶς ἡ φύσις.",
    certainty: "asserted",
    note: "First so designated in his treatise On the Nature of Man; the same as a virtuous life.",
  },
  {
    id: "zeno-doctrine-katalept-phantasia",
    subject: "Zeno of Citium",
    property: "heldDoctrine",
    value:
      "The standard of truth is the apprehending presentation, that which proceeds from a real object and is stamped seal-fashion on the mind",
    valueType: "doctrine",
    greek: "φαντασία καταληπτική",
    ref: "7.54",
    grc: "Κριτήριον δὲ τῆς ἀληθείας φασὶ τυγχάνειν τὴν καταληπτικὴν φαντασίαν, τουτέστι τὴν ἀπὸ ὑπάρχοντος, καθά φησι Χρύσιππος ἐν τῇ δυωδεκάτῃ τῶν Φυσικῶν καὶ Ἀντίπατρος καὶ Ἀπολλόδωρος.",
    certainty: "asserted",
  },
  {
    id: "zeno-doctrine-kathekon",
    subject: "Zeno of Citium",
    property: "heldDoctrine",
    value:
      "Duty (kathekon) is an action adapted to nature's arrangements, for which a reasonable defence can be adduced",
    valueType: "doctrine",
    greek: "καθῆκον",
    ref: "7.108",
    grc: "Κατωνομάσθαι δʼ οὕτως ὑπὸ πρώτου Ζήνωνος τὸ καθῆκον, ἀπὸ τοῦ κατά τινας ἥκειν τῆς προσονομασίας εἰλημμένης. ἐνέργημα δʼ αὐτὸ εἶναι ταῖς κατὰ φύσιν κατασκευαῖς οἰκεῖον.",
    certainty: "asserted",
    note: "Zeno was the first to use the term kathekon of conduct.",
  },
  {
    id: "zeno-doctrine-pathos",
    subject: "Zeno of Citium",
    property: "heldDoctrine",
    value:
      "Passion is an irrational and unnatural movement in the soul, or impulse in excess",
    valueType: "doctrine",
    greek: "πάθος",
    ref: "7.110",
    grc: "ἔστι δὲ αὐτὸ τὸ πάθος κατὰ Ζήνωνα ἡ ἄλογος καὶ παρὰ φύσιν ψυχῆς κίνησις ἢ ὁρμὴ πλεονάζουσα.",
    certainty: "asserted",
    note: "Zeno's definition; the four great classes are grief, fear, desire, pleasure.",
  },
  {
    id: "zeno-doctrine-apatheia",
    subject: "Zeno of Citium",
    property: "heldDoctrine",
    value: "The wise man is passionless, not prone to fall into infirmity",
    valueType: "doctrine",
    greek: "ἀπάθεια",
    ref: "7.117",
    grc: "Φασὶ δὲ καὶ ἀπαθῆ εἶναι τὸν σοφόν, διὰ τὸ ἀνέμπτωτον εἶναι·",
    certainty: "asserted",
  },
  {
    id: "zeno-doctrine-eupatheiai",
    subject: "Zeno of Citium",
    property: "heldDoctrine",
    value:
      "There are three good emotional states: joy, caution, and wishing (rational counterparts of the passions)",
    valueType: "doctrine",
    greek: "εὐπάθειαι",
    ref: "7.116",
    grc: "Εἶναι δὲ καὶ εὐπαθείας φασὶ τρεῖς, χαράν, εὐλάβειαν, βούλησιν.",
    certainty: "asserted",
  },
  {
    id: "zeno-doctrine-virtue-sufficient",
    subject: "Zeno of Citium",
    property: "heldDoctrine",
    value: "Virtue is in itself sufficient to ensure well-being",
    valueType: "doctrine",
    ref: "7.127",
    grc: "αὐτάρκη τʼ εἶναι αὐτὴν πρὸς εὐδαιμονίαν, καθά φησι Ζήνων καὶ Χρύσιππος ἐν τῷ πρώτῳ Περὶ ἀρετῶν καὶ Ἑκάτων ἐν τῷ δευτέρῳ Περὶ ἀγαθῶν.",
    certainty: "asserted",
    greek: "εὐδαιμονία",
    note: "So Zeno, and Chrysippus in the first book On Virtues, and Hecato.",
  },
  {
    id: "zeno-doctrine-sins-equal",
    subject: "Zeno of Citium",
    property: "heldDoctrine",
    value: "All sins are equal",
    valueType: "doctrine",
    ref: "7.120",
    grc: "ἀρέσκει τʼ αὐτοῖς ἴσα ἡγεῖσθαι τὰ ἁμαρτήματα, καθά φησι Χρύσιππος ἐν τῷ τετάρτῳ τῶν Ἠθικῶν ζητημάτων καὶ Περσαῖος καὶ Ζήνων.",
    certainty: "asserted",
    note: "So Chrysippus in book four of his Ethical Questions, as well as Persaeus and Zeno.",
  },
  {
    id: "zeno-doctrine-two-principles",
    subject: "Zeno of Citium",
    property: "heldDoctrine",
    value:
      "There are two principles in the universe: the active (reason, i.e. God) and the passive (substance without quality, i.e. matter)",
    valueType: "doctrine",
    ref: "7.134",
    grc: "Δοκεῖ δʼ αὐτοῖς ἀρχὰς εἶναι τῶν ὅλων δύο, τὸ ποιοῦν καὶ τὸ πάσχον. τὸ μὲν οὖν πάσχον εἶναι τὴν ἄποιον οὐσίαν τὴν ὕλην, τὸ δὲ ποιοῦν τὸν ἐν αὐτῇ λόγον τὸν θεόν·",
    certainty: "asserted",
    note: "Laid down by Zeno in his treatise On Existence.",
  },
  {
    id: "zeno-doctrine-god",
    subject: "Zeno of Citium",
    property: "heldDoctrine",
    value:
      "God is one and the same with Reason, Fate, and Zeus, the everlasting artificer of all things",
    valueType: "doctrine",
    ref: "7.135",
    grc: "Ἕν τʼ εἶναι θεὸν καὶ νοῦν καὶ εἱμαρμένην καὶ Δία· πολλάς τʼ ἑτέρας ὀνομασίας προσονομάζεσθαι.",
    certainty: "asserted",
  },
  {
    id: "zeno-doctrine-fate",
    subject: "Zeno of Citium",
    property: "heldDoctrine",
    value:
      "All things happen by fate or destiny, an endless chain of causation",
    valueType: "doctrine",
    greek: "εἱμαρμένη",
    ref: "7.149",
    grc: "καθʼ εἱμαρμένην δέ φασι τὰ πάντα γίγνεσθαι Χρύσιππος ἐν τοῖς Περὶ εἱμαρμένης καὶ Ποσειδώνιος ἐν δευτέρῳ Περὶ εἱμαρμένης καὶ Ζήνων, Βόηθος δʼ ἐν τῷ πρώτῳ Περὶ εἱμαρμένης. ἔστι δʼ εἱμαρμένη αἰτία τῶν ὄντων εἰρομένη ἢ λόγος καθʼ ὃν ὁ κόσμος διεξάγεται.",
    certainty: "asserted",
  },
  {
    id: "zeno-doctrine-soul-breath",
    subject: "Zeno of Citium",
    property: "heldDoctrine",
    value: "The soul is a warm breath, by which we become animate and can move",
    valueType: "doctrine",
    greek: "πνεῦμα",
    ref: "7.157",
    grc: "Ζήνων δʼ ὁ Κιτιεὺς καὶ Ἀντίπατρος ἐν τοῖς Περὶ ψυχῆς καὶ Ποσειδώνιος πνεῦμα ἔνθερμον εἶναι τὴν ψυχήν· τούτῳ γὰρ ἡμᾶς εἶναι ἔμπνους καὶ ὑπὸ τούτου κινεῖσθαι.",
    certainty: "asserted",
    note: "So Zeno of Citium and Antipater in their treatises De anima, and Posidonius.",
  },
  {
    id: "zeno-doctrine-conflagration",
    subject: "Zeno of Citium",
    property: "heldDoctrine",
    value:
      "The world had a beginning and is destructible, resolved into fire at the general conflagration",
    valueType: "doctrine",
    greek: "ἐκπύρωσις",
    ref: "7.142",
    grc: "περὶ δὴ οὖν τῆς γενέσεως καὶ τῆς φθορᾶς τοῦ κόσμου φησὶ Ζήνων μὲν ἐν τῷ Περὶ ὅλου, Χρύσιππος δʼ ἐν τῷ πρώτῳ τῶν Φυσικῶν καὶ Ποσειδώνιος ἐν πρώτῳ Περὶ κόσμου καὶ Κλεάνθης καὶ Ἀντίπατρος ἐν τῷ δεκάτῳ Περὶ κόσμου.",
    certainty: "asserted",
    note: "The generation and destruction of the world are discussed by Zeno in his treatise On the Whole.",
  },

  // ------------------------------------------------------- Ariston of Chios
  {
    id: "ariston-birthplace-chios",
    subject: "Ariston of Chios",
    property: "birthPlace",
    value: "Chios",
    valueType: "place",
    ref: "7.37",
    grc: "Ἀρίστων Μιλτιάδου Χῖος, ὁ τὴν ἀδιαφορίαν εἰσηγησάμενος",
    certainty: "asserted",
  },
  {
    id: "ariston-parentage-miltiades",
    subject: "Ariston of Chios",
    property: "parentage",
    value: "Son of Miltiades",
    valueType: "literal",
    ref: "7.37",
    grc: "Ἀρίστων Μιλτιάδου Χῖος, ὁ τὴν ἀδιαφορίαν εἰσηγησάμενος",
    certainty: "asserted",
  },
  {
    id: "ariston-affiliated-stoa",
    subject: "Ariston of Chios",
    property: "affiliatedWith",
    value: "Stoa",
    valueType: "school",
    ref: "7.37",
    grc: "Κλεάνθης Φανίου Ἄσσιος, ὁ διαδεξάμενος τὴν σχολήν",
    certainty: "asserted",
    note: "Ranked by D.L. at 7.167 among those who swerved from Zeno's main doctrine and are counted as a sect apart (heterodox Stoic).",
  },
  {
    id: "ariston-teacher-zeno",
    subject: "Ariston of Chios",
    property: "studiedUnder",
    value: "Zeno of Citium",
    valueType: "philosopher",
    ref: "7.37",
    grc: "Ἀρίστων Μιλτιάδου Χῖος, ὁ τὴν ἀδιαφορίαν εἰσηγησάμενος",
    certainty: "asserted",
    note: "A disciple of Zeno; he introduced the doctrine of things morally indifferent.",
  },
  {
    id: "ariston-doctrine-indifference",
    subject: "Ariston of Chios",
    property: "heldDoctrine",
    value:
      "The end of action is a life of perfect indifference to everything which is neither virtue nor vice",
    valueType: "doctrine",
    greek: "ἀδιαφορία",
    ref: "7.160",
    grc: "τέλος ἔφησεν εἶναι τὸ ἀδιαφόρως ἔχοντα ζῆν πρὸς τὰ μεταξὺ ἀρετῆς καὶ κακίας μηδʼ ἡντινοῦν ἐν αὐτοῖς παραλλαγὴν ἀπολείποντα",
    certainty: "asserted",
    note: "He recognized no distinction whatever among things indifferent.",
  },
  {
    id: "ariston-doctrine-only-ethics",
    subject: "Ariston of Chios",
    property: "heldDoctrine",
    value:
      "Logic and Physics should be discarded: Physics is beyond our reach and Logic does not concern us; only Ethics concerns us",
    valueType: "doctrine",
    ref: "7.160",
    grc: "τόν τε φυσικὸν τόπον καὶ τὸν λογικὸν ἀνῄρει, λέγων τὸν μὲν εἶναι ὑπὲρ ἡμᾶς, τὸν δʼ οὐδὲν πρὸς ἡμᾶς, μόνον δὲ τὸν ἠθικὸν εἶναι πρὸς ἡμᾶς",
    certainty: "asserted",
  },
  {
    id: "ariston-death-sunstroke",
    subject: "Ariston of Chios",
    property: "mannerOfDeath",
    value: "Being bald, he had a sunstroke and so came to his end",
    valueType: "literal",
    ref: "7.164",
    grc: "Τοῦτον λόγος φαλακρὸν ὄντα ἐγκαυθῆναι ὑπὸ ἡλίου καὶ ὧδε τελευτῆσαι.",
    certainty: "reported",
  },
  {
    id: "ariston-wrote-exhortations",
    subject: "Ariston of Chios",
    property: "wrote",
    value: "Exhortations (2 books)",
    valueType: "work",
    ref: "7.163",
    grc: "Προτρεπτικῶν β′.",
    certainty: "disputed",
    note: "Panaetius and Sosicrates hold only the Letters to Cleanthes genuine, attributing the rest to Ariston the Peripatetic.",
  },
  {
    id: "ariston-wrote-zeno-doctrines",
    subject: "Ariston of Chios",
    property: "wrote",
    value: "Of Zeno's Doctrines",
    valueType: "work",
    ref: "7.163",
    grc: "Περὶ τῶν Ζήνωνος δογμάτων",
    certainty: "disputed",
  },
  {
    id: "ariston-wrote-dissertations-philosophy",
    subject: "Ariston of Chios",
    property: "wrote",
    value: "Dissertations on Philosophy (7 books)",
    valueType: "work",
    ref: "7.163",
    grc: "Σχολῶν ς′",
    certainty: "disputed",
  },
  {
    id: "ariston-wrote-letters-cleanthes",
    subject: "Ariston of Chios",
    property: "wrote",
    value: "Letters to Cleanthes (4 books)",
    valueType: "work",
    ref: "7.163",
    grc: "Παναίτιος δὲ καὶ Σωσικράτης μόνας αὐτοῦ τὰς ἐπιστολάς φασι, τὰ δʼ ἄλλα τοῦ περιπατητικοῦ Ἀρίστωνος.",
    certainty: "reported",
    note: "Panaetius and Sosicrates consider the Letters alone genuine.",
  },

  // ------------------------------------------------------- Herillus
  {
    id: "herillus-birthplace-carthage",
    subject: "Herillus",
    property: "birthPlace",
    value: "Carthage",
    valueType: "place",
    ref: "7.37",
    grc: "Ἀρίστων Μιλτιάδου Χῖος, ὁ τὴν ἀδιαφορίαν εἰσηγησάμενος",
    certainty: "asserted",
  },
  {
    id: "herillus-affiliated-stoa",
    subject: "Herillus",
    property: "affiliatedWith",
    value: "Stoa",
    valueType: "school",
    ref: "7.37",
    grc: "Κλεάνθης Φανίου Ἄσσιος, ὁ διαδεξάμενος τὴν σχολήν",
    certainty: "asserted",
    note: "Ranked by D.L. at 7.167 among those who swerved from Zeno's main doctrine and are counted as a sect apart (heterodox Stoic).",
  },
  {
    id: "herillus-teacher-zeno",
    subject: "Herillus",
    property: "studiedUnder",
    value: "Zeno of Citium",
    valueType: "philosopher",
    ref: "7.166",
    grc: "Λέγεται δʼ ὅτι παιδὸς ὄντος αὐτοῦ ἠράσθησαν ἱκανοί, οὓς ἀποτρέψαι βουλόμενος ὁ Ζήνων ἠνάγκασε ξυρᾶσθαι Ἥριλλον, οἱ δʼ ἀπετράποντο",
    certainty: "asserted",
  },
  {
    id: "herillus-doctrine-knowledge-end",
    subject: "Herillus",
    property: "heldDoctrine",
    value:
      "The end of action is Knowledge: to live always so as to make the scientific life the standard in all things",
    valueType: "doctrine",
    greek: "ἐπιστήμη",
    ref: "7.165",
    grc: "Ἥριλλος δʼ ὁ Καρχηδόνιος τέλος εἶπε τὴν ἐπιστήμην, ὅπερ ἐστὶ ζῆν ἀεὶ πάντʼ ἀναφέροντα πρὸς τὸ μετʼ ἐπιστήμης ζῆν καὶ μὴ τῇ ἀγνοίᾳ διαβεβλημένον.",
    certainty: "asserted",
    note: "He distinguished an end-in-chief from a subordinate end.",
  },
  {
    id: "herillus-wrote-training",
    subject: "Herillus",
    property: "wrote",
    value: "Of Training",
    valueType: "work",
    ref: "7.166",
    grc: "Περὶ ἀσκήσεως",
    certainty: "asserted",
  },
  {
    id: "herillus-wrote-passions",
    subject: "Herillus",
    property: "wrote",
    value: "Of the Passions",
    valueType: "work",
    ref: "7.166",
    grc: "Περὶ παθῶν",
    certainty: "asserted",
  },
  {
    id: "herillus-wrote-legislator",
    subject: "Herillus",
    property: "wrote",
    value: "The Legislator",
    valueType: "work",
    ref: "7.166",
    grc: "Νομοθέτης",
    certainty: "asserted",
  },

  // ------------------------------------------------ Dionysius the Renegade
  {
    id: "dionysius-birthplace-heraclea",
    subject: "Dionysius the Renegade",
    property: "birthPlace",
    value: "Heraclea",
    valueType: "place",
    ref: "7.166",
    grc: "Ἦν δὲ παῖς μὲν Θεοφάντου, πόλεως δʼ Ἡρακλείας",
    certainty: "asserted",
  },
  {
    id: "dionysius-parentage-theophantus",
    subject: "Dionysius the Renegade",
    property: "parentage",
    value: "Son of Theophantus",
    valueType: "literal",
    ref: "7.166",
    grc: "Ἦν δὲ παῖς μὲν Θεοφάντου, πόλεως δʼ Ἡρακλείας",
    certainty: "asserted",
  },
  {
    id: "dionysius-affiliated-stoa",
    subject: "Dionysius the Renegade",
    property: "affiliatedWith",
    value: "Stoa",
    valueType: "school",
    ref: "7.37",
    grc: "Κλεάνθης Φανίου Ἄσσιος, ὁ διαδεξάμενος τὴν σχολήν",
    certainty: "asserted",
    note: "Ranked by D.L. at 7.167 among those who swerved from Zeno's main doctrine and are counted as a sect apart (heterodox Stoic); later went over to the Cyrenaics (7.166-167).",
  },
  {
    id: "dionysius-affiliated-cyrenaic",
    subject: "Dionysius the Renegade",
    property: "affiliatedWith",
    value: "Cyrenaic",
    valueType: "school",
    ref: "7.167",
    grc: "Καὶ κατʼ ἀρχὰς μὲν φιλογράμματος ὢν παντοδαποῖς ἐπεχείρει ποιήμασιν, ἔπειτα δὲ καὶ Ἄρατον ἀπεδέχετο, ζηλῶν αὐτόν",
    certainty: "asserted",
    note: "Went over to the Cyrenaic school after recanting the Stoic view on pain, no longer able to call pain a thing indifferent following a violent attack of ophthalmia (7.166-167).",
  },
  {
    id: "dionysius-teacher-heraclides",
    subject: "Dionysius the Renegade",
    property: "studiedUnder",
    value: "Heraclides of Heraclea",
    valueType: "person",
    ref: "7.166",
    grc: "ἤκουσε δέ, καθά φησι Διοκλῆς, πρῶτον μὲν Ἡρακλείδου τοῦ πολίτου",
    certainty: "reported",
    accordingTo: "Diocles",
    note: "First a pupil of his fellow-townsman Heraclides, next of Alexinus and Menedemus, lastly of Zeno.",
  },
  {
    id: "dionysius-teacher-zeno",
    subject: "Dionysius the Renegade",
    property: "studiedUnder",
    value: "Zeno of Citium",
    valueType: "philosopher",
    ref: "7.166",
    grc: "τελευταῖον δὲ Ζήνωνος",
    certainty: "asserted",
  },
  {
    id: "dionysius-doctrine-pleasure",
    subject: "Dionysius the Renegade",
    property: "heldDoctrine",
    value: "Pleasure is the end of action",
    valueType: "doctrine",
    greek: "ἡδονή",
    ref: "7.166",
    grc: "Διονύσιος δʼ ὁ Μεταθέμενος τέλος εἶπε τὴν ἡδονὴν διὰ περίστασιν ὀφθαλμίας",
    certainty: "asserted",
    note: "He recanted the Stoic view under a violent attack of ophthalmia, no longer able to call pain a thing indifferent.",
  },
  {
    id: "dionysius-death-starvation",
    subject: "Dionysius the Renegade",
    property: "mannerOfDeath",
    value:
      "After living till nearly eighty, committed suicide by starving himself",
    valueType: "literal",
    ref: "7.167",
    grc: "βιοὺς δὲ πρὸς τὰ ὀγδοήκοντʼ ἀσιτίᾳ κατέστρεψε.",
    certainty: "asserted",
  },
  {
    id: "dionysius-wrote-apathy",
    subject: "Dionysius the Renegade",
    property: "wrote",
    value: "Of Apathy (2 books)",
    valueType: "work",
    ref: "7.167",
    grc: "Περὶ ἀπαθείας β′",
    certainty: "asserted",
  },
  {
    id: "dionysius-wrote-pleasure",
    subject: "Dionysius the Renegade",
    property: "wrote",
    value: "Of Pleasure (4 books)",
    valueType: "work",
    ref: "7.167",
    grc: "Περὶ ἡδονῆς δ′",
    certainty: "asserted",
  },

  // ------------------------------------------------------- Cleanthes
  {
    id: "cleanthes-birthplace-assos",
    subject: "Cleanthes",
    property: "birthPlace",
    value: "Assos",
    valueType: "place",
    ref: "7.168",
    grc: "Κεφ",
    certainty: "asserted",
  },
  {
    id: "cleanthes-parentage-phanias",
    subject: "Cleanthes",
    property: "parentage",
    value: "Son of Phanias",
    valueType: "literal",
    ref: "7.168",
    grc: "Κεφ",
    certainty: "asserted",
  },
  {
    id: "cleanthes-affiliated-stoa",
    subject: "Cleanthes",
    property: "affiliatedWith",
    value: "Stoa",
    valueType: "school",
    ref: "7.168",
    grc: "Κεφ",
    certainty: "asserted",
    note: "The legitimate successor to Zeno in the headship of the school.",
  },
  {
    id: "cleanthes-teacher-zeno",
    subject: "Cleanthes",
    property: "studiedUnder",
    value: "Zeno of Citium",
    valueType: "philosopher",
    ref: "7.168",
    grc: "Κεφ",
    certainty: "asserted",
    note: "Adhered to the same doctrines throughout; spent nineteen years as Zeno's pupil.",
  },
  {
    id: "cleanthes-education-pugilist",
    subject: "Cleanthes",
    property: "education",
    value:
      "Was at first a pugilist; driven by extreme poverty, drew water in gardens by night and studied by day (nicknamed Phreantles, Well-lifter)",
    valueType: "literal",
    ref: "7.168",
    grc: "Κεφ",
    certainty: "reported",
    accordingTo: "Antisthenes",
  },
  {
    id: "cleanthes-doctrine-nature-universe",
    subject: "Cleanthes",
    property: "heldDoctrine",
    value:
      "The nature to be followed as the end is the nature of the universe alone, not the nature of the individual",
    valueType: "doctrine",
    ref: "7.89",
    grc: "ὁ δὲ Κλεάνθης τὴν κοινὴν μόνην ἐκδέχεται φύσιν, ᾗ ἀκολουθεῖν δεῖ, οὐκέτι δὲ καὶ τὴν ἐπὶ μέρους.",
    certainty: "asserted",
    note: "As against Chrysippus, who understood both universal and individual nature.",
  },
  {
    id: "cleanthes-doctrine-virtue-not-lost",
    subject: "Cleanthes",
    property: "heldDoctrine",
    value:
      "Virtue cannot be lost, owing to the certainty of our mental apprehension",
    valueType: "doctrine",
    ref: "7.127",
    grc: "καὶ μὴν τὴν ἀρετὴν Χρύσιππος μὲν ἀποβλητήν, Κλεάνθης δὲ ἀναπόβλητον· ὁ μὲν ἀποβλητὴν διὰ μέθην καὶ μελαγχολίαν, ὁ δʼ ἀναπόβλητον διὰ βεβαίους καταλήψεις·",
    certainty: "asserted",
    note: "As against Chrysippus, who held virtue can be lost through drunkenness or melancholy.",
    conflictsWith: ["chrysippus-doctrine-virtue-lost"],
  },
  {
    id: "cleanthes-doctrine-sun-ruling",
    subject: "Cleanthes",
    property: "heldDoctrine",
    value: "The sun is the ruling power of the world",
    valueType: "doctrine",
    ref: "7.139",
    grc: "Χρύσιππος δʼ ἐν τῷ πρώτῳ Περὶ προνοίας καὶ Ποσειδώνιος ἐν τῷ Περὶ θεῶν τὸν οὐρανόν φασι τὸ ἡγεμονικὸν τοῦ κόσμου, Κλεάνθης δὲ τὸν ἥλιον.",
    certainty: "asserted",
    note: "As against Chrysippus and Posidonius, who said the heaven is the ruling power.",
  },
  {
    id: "cleanthes-doctrine-souls-survive",
    subject: "Cleanthes",
    property: "heldDoctrine",
    value: "All souls continue to exist until the general conflagration",
    valueType: "doctrine",
    ref: "7.157",
    grc: "Κλεάνθης μὲν οὖν πάσας ἐπιδιαμένειν μέχρι τῆς ἐκπυρώσεως, Χρύσιππος δὲ τὰς τῶν σοφῶν μόνον.",
    certainty: "asserted",
    note: "As against Chrysippus, who held that only the souls of the wise survive.",
    conflictsWith: ["chrysippus-doctrine-souls-wise"],
  },
  {
    id: "cleanthes-doctrine-six-parts",
    subject: "Cleanthes",
    property: "heldDoctrine",
    value:
      "Philosophy has six parts: Dialectic, Rhetoric, Ethics, Politics, Physics, Theology",
    valueType: "doctrine",
    ref: "7.41",
    grc: "ὁ δὲ Κλεάνθης ἓξ μέρη φησί, διαλεκτικόν, ῥητορικόν, ἠθικόν, πολιτικόν, φυσικόν, θεολογικόν.",
    certainty: "asserted",
  },
  {
    id: "cleanthes-death-starvation",
    subject: "Cleanthes",
    property: "mannerOfDeath",
    value:
      "Having abstained from food on doctors' advice for an inflammation of the gums, he refused to resume eating and fasted to his death",
    valueType: "literal",
    ref: "7.176",
    grc: "διῴδησεν αὐτῷ τὸ οὖλον· ἀπαγορευσάντων δὲ τῶν ἰατρῶν, δύο ἡμέρας ἀπέσχετο τροφῆς. καί πως ἔσχε καλῶς ὥστε τοὺς ἰατροὺς αὐτῷ πάντα τὰ συνήθη συγχωρεῖν· τὸν δὲ μὴ ἀνασχέσθαι, ἀλλʼ εἰπόντα ἤδη αὐτῷ προωδοιπορῆσθαι καὶ τὰς λοιπὰς ἀποσχόμενον τελευτῆσαι",
    certainty: "asserted",
  },
  {
    id: "cleanthes-wrote-time",
    subject: "Cleanthes",
    property: "wrote",
    value: "Of Time",
    valueType: "work",
    ref: "7.174",
    grc: "Περὶ χρόνου",
    certainty: "asserted",
  },
  {
    id: "cleanthes-wrote-zeno-natural-philosophy",
    subject: "Cleanthes",
    property: "wrote",
    value: "Of Zeno's Natural Philosophy (2 books)",
    valueType: "work",
    ref: "7.174",
    grc: "Περὶ τῆς [τοῦ] Ζήνωνος φυσιολογίας δύο",
    certainty: "asserted",
  },
  {
    id: "cleanthes-wrote-interpretations-heraclitus",
    subject: "Cleanthes",
    property: "wrote",
    value: "Interpretations of Heraclitus (4 books)",
    valueType: "work",
    ref: "7.174",
    grc: "Βιβλία δὲ κάλλιστα καταλέλοιπεν, ἅ ἐστι τάδε",
    certainty: "asserted",
  },
  {
    id: "cleanthes-wrote-of-impulse",
    subject: "Cleanthes",
    property: "wrote",
    value: "Of Impulse (2 books)",
    valueType: "work",
    ref: "7.174",
    grc: "Περὶ αἰσθήσεως",
    certainty: "asserted",
  },
  {
    id: "cleanthes-wrote-of-the-gods",
    subject: "Cleanthes",
    property: "wrote",
    value: "Of the Gods",
    valueType: "work",
    ref: "7.175",
    grc: "Περὶ θεῶν",
    certainty: "asserted",
  },
  {
    id: "cleanthes-wrote-of-duty",
    subject: "Cleanthes",
    property: "wrote",
    value: "Of Duty (3 books)",
    valueType: "work",
    ref: "7.175",
    grc: "Περὶ γιγάντων",
    certainty: "asserted",
  },
  {
    id: "cleanthes-wrote-of-the-end",
    subject: "Cleanthes",
    property: "wrote",
    value: "Of the End",
    valueType: "work",
    ref: "7.175",
    grc: "Περὶ ὑμεναίου",
    certainty: "asserted",
  },

  // ------------------------------------------------------- Sphaerus
  {
    id: "sphaerus-birthplace-bosporus",
    subject: "Sphaerus",
    property: "birthPlace",
    value: "Bosporus",
    valueType: "place",
    ref: "7.37",
    grc: "Ἀρίστων Μιλτιάδου Χῖος, ὁ τὴν ἀδιαφορίαν εἰσηγησάμενος",
    certainty: "asserted",
  },
  {
    id: "sphaerus-affiliated-stoa",
    subject: "Sphaerus",
    property: "affiliatedWith",
    value: "Stoa",
    valueType: "school",
    ref: "7.177",
    grc: "Τούτου, καθάπερ προειρήκαμεν, ἤκουσε μετὰ Ζήνωνα καὶ Σφαῖρος ὁ Βοσποριανός, ὃς προκοπὴν ἱκανὴν περιποιησάμενος λόγων εἰς Ἀλεξάνδρειαν ἀπῄει πρὸς Πτολεμαῖον τὸν Φιλοπάτορα",
    certainty: "asserted",
  },
  {
    id: "sphaerus-teacher-zeno",
    subject: "Sphaerus",
    property: "studiedUnder",
    value: "Zeno of Citium",
    valueType: "philosopher",
    ref: "7.177",
    grc: "Τούτου, καθάπερ προειρήκαμεν, ἤκουσε μετὰ Ζήνωνα καὶ Σφαῖρος ὁ Βοσποριανός, ὃς προκοπὴν ἱκανὴν περιποιησάμενος λόγων εἰς Ἀλεξάνδρειαν ἀπῄει πρὸς Πτολεμαῖον τὸν Φιλοπάτορα",
    certainty: "asserted",
  },
  {
    id: "sphaerus-teacher-cleanthes",
    subject: "Sphaerus",
    property: "studiedUnder",
    value: "Cleanthes",
    valueType: "philosopher",
    ref: "7.177",
    grc: "Τούτου, καθάπερ προειρήκαμεν, ἤκουσε μετὰ Ζήνωνα καὶ Σφαῖρος ὁ Βοσποριανός, ὃς προκοπὴν ἱκανὴν περιποιησάμενος λόγων εἰς Ἀλεξάνδρειαν ἀπῄει πρὸς Πτολεμαῖον τὸν Φιλοπάτορα",
    certainty: "asserted",
    note: "Became a pupil of Cleanthes after Zeno's death.",
  },
  {
    id: "sphaerus-lived-alexandria",
    subject: "Sphaerus",
    property: "traveledTo",
    value: "Alexandria",
    valueType: "place",
    ref: "7.177",
    grc: "Τούτου, καθάπερ προειρήκαμεν, ἤκουσε μετὰ Ζήνωνα καὶ Σφαῖρος ὁ Βοσποριανός, ὃς προκοπὴν ἱκανὴν περιποιησάμενος λόγων εἰς Ἀλεξάνδρειαν ἀπῄει πρὸς Πτολεμαῖον τὸν Φιλοπάτορα",
    certainty: "asserted",
    note: "Went to the court of King Ptolemy Philopator.",
  },
  {
    id: "sphaerus-wrote-cosmos",
    subject: "Sphaerus",
    property: "wrote",
    value: "Of the Cosmos (2 books)",
    valueType: "work",
    ref: "7.178",
    grc: "Περὶ κόσμου δύο",
    certainty: "asserted",
  },
  {
    id: "sphaerus-wrote-lycurgus-socrates",
    subject: "Sphaerus",
    property: "wrote",
    value: "Of Lycurgus and Socrates (3 books)",
    valueType: "work",
    ref: "7.178",
    grc: "Περὶ Λυκούργου καὶ Σωκράτους τρίς",
    certainty: "asserted",
  },
  {
    id: "sphaerus-wrote-spartan-constitution",
    subject: "Sphaerus",
    property: "wrote",
    value: "Of the Spartan Constitution",
    valueType: "work",
    ref: "7.178",
    grc: "Περὶ Λακωνικῆς πολιτείας",
    certainty: "asserted",
  },
  {
    id: "sphaerus-wrote-handbook-dialectic",
    subject: "Sphaerus",
    property: "wrote",
    value: "Handbook of Dialectic (2 books)",
    valueType: "work",
    ref: "7.178",
    grc: "Τέχνης διαλεκτικῆς δύο",
    certainty: "asserted",
  },

  // ------------------------------------------------------- Chrysippus
  {
    id: "chrysippus-birthplace-soli",
    subject: "Chrysippus",
    property: "birthPlace",
    value: "Soli",
    valueType: "place",
    ref: "7.179",
    grc: "Χρύσιππος Ἀπολλωνίου Σολεὺς ἢ Ταρσεύς, ὡς Ἀλέξανδρος ἐν Διαδοχαῖς, μαθητὴς Κλεάνθους",
    certainty: "reported",
    accordingTo: "Alexander",
    conflictsWith: ["chrysippus-birthplace-tarsus"],
  },
  {
    id: "chrysippus-birthplace-tarsus",
    subject: "Chrysippus",
    property: "birthPlace",
    value: "Tarsus",
    valueType: "place",
    ref: "7.179",
    grc: "Χρύσιππος Ἀπολλωνίου Σολεὺς ἢ Ταρσεύς, ὡς Ἀλέξανδρος ἐν Διαδοχαῖς, μαθητὴς Κλεάνθους",
    certainty: "reported",
    conflictsWith: ["chrysippus-birthplace-soli"],
  },
  {
    id: "chrysippus-parentage-apollonius",
    subject: "Chrysippus",
    property: "parentage",
    value: "Son of Apollonius",
    valueType: "literal",
    ref: "7.179",
    grc: "Χρύσιππος Ἀπολλωνίου Σολεὺς ἢ Ταρσεύς, ὡς Ἀλέξανδρος ἐν Διαδοχαῖς, μαθητὴς Κλεάνθους",
    certainty: "asserted",
  },
  {
    id: "chrysippus-affiliated-stoa",
    subject: "Chrysippus",
    property: "affiliatedWith",
    value: "Stoa",
    valueType: "school",
    ref: "7.183",
    grc: "Ἐν μέντοι ταῖς οἰνώσεσιν ἡσύχαζε παραφε",
    certainty: "asserted",
    note: "\"But for Chrysippus, there had been no Porch.\"",
  },
  {
    id: "chrysippus-teacher-cleanthes",
    subject: "Chrysippus",
    property: "studiedUnder",
    value: "Cleanthes",
    valueType: "philosopher",
    ref: "7.179",
    grc: "Χρύσιππος Ἀπολλωνίου Σολεὺς ἢ Ταρσεύς, ὡς Ἀλέξανδρος ἐν Διαδοχαῖς, μαθητὴς Κλεάνθους",
    certainty: "asserted",
    note: "He often differed from Cleanthes and from Zeno on most points.",
  },
  {
    id: "chrysippus-teacher-zeno",
    subject: "Chrysippus",
    property: "studiedUnder",
    value: "Zeno of Citium",
    valueType: "philosopher",
    ref: "7.179",
    grc: "Χρύσιππος Ἀπολλωνίου Σολεὺς ἢ Ταρσεύς, ὡς Ἀλέξανδρος ἐν Διαδοχαῖς, μαθητὴς Κλεάνθους",
    certainty: "reported",
    accordingTo: "Diocles",
    note: "Diocles says Chrysippus was at first a pupil of Zeno of Citium (7.179). The prevailing account has Cleanthes as his teacher; Diocles' alternative is that he later came under Cleanthes. The reified succession link in LOD (succession-links.ts) records this without a direct lo:teacherOf triple.",
  },
  {
    id: "chrysippus-teacher-arcesilaus",
    subject: "Chrysippus",
    property: "studiedUnder",
    value: "Arcesilaus",
    valueType: "philosopher",
    ref: "7.183",
    grc: "Τέλος δʼ Ἀρκεσιλάῳ καὶ Λακύδῃ, καθά φησι Σωτίων ἐν τῷ ὀγδόῳ, παραγενόμενος ἐν Ἀκαδημείᾳ συνεφιλοσόφησε·",
    certainty: "reported",
    accordingTo: "Sotion",
    note: "Said to have joined Arcesilaus and Lacydes and studied in the Academy.",
  },
  {
    id: "chrysippus-education-runner",
    subject: "Chrysippus",
    property: "education",
    value: "Before philosophy he used to practise as a long-distance runner",
    valueType: "literal",
    ref: "7.179",
    grc: "οὗτος πρότερον μὲν δόλιχον ἤσκει, ἔπειτʼ ἀκούσας Ζήνωνος ἢ Κλεάνθους, ὡς Διοκλῆς καὶ οἱ πλείους, ἔτι τε ζῶντος ἀπέστη αὐτοῦ καὶ οὐχ ὁ τυχὼν ἐγένετο κατὰ φιλοσοφίαν",
    certainty: "asserted",
  },
  {
    id: "chrysippus-death-age-73",
    subject: "Chrysippus",
    property: "deathDate",
    value:
      "Died at the age of 73, in the 143rd Olympiad (208-204 BCE)",
    valueType: "literal",
    ref: "7.184",
    grc: "ἔνθα προσενεγκάμενον γλυκὺν ἄκρατον καὶ ἰλιγγιάσαντα πεμπταῖον ἀπελθεῖν ἐξ ἀνθρώπων, τρία καὶ ἑβδομήκοντα βιώσαντʼ ἔτη, κατὰ τὴν τρίτην καὶ τετταρακοστὴν καὶ ἑκατοστὴν Ὀλυμπιάδα, καθά φησιν Ἀπολλόδωρος ἐν Χρονικοῖς",
    certainty: "reported",
    accordingTo: "Apollodorus",
  },
  {
    id: "chrysippus-death-wine",
    subject: "Chrysippus",
    property: "mannerOfDeath",
    value:
      "Seized with dizziness after drinking a draught of sweet unmixed wine at a sacrificial feast, he died five days afterwards",
    valueType: "literal",
    ref: "7.184",
    grc: "ἔνθα προσενεγκάμενον γλυκὺν ἄκρατον καὶ ἰλιγγιάσαντα πεμπταῖον ἀπελθεῖν ἐξ ἀνθρώπων, τρία καὶ ἑβδομήκοντα βιώσαντʼ ἔτη",
    certainty: "reported",
    accordingTo: "Hermippus",
    conflictsWith: ["chrysippus-death-laughter"],
  },
  {
    id: "chrysippus-death-laughter",
    subject: "Chrysippus",
    property: "mannerOfDeath",
    value:
      "Died of a violent fit of laughter, after an ass ate his figs and he called for the ass to be given wine to wash them down",
    valueType: "literal",
    ref: "7.185",
    grc: "Ἔνιοι δέ φασι γέλωτι συσχεθέντα αὐτὸν τελευτῆσαι· ὄνου γὰρ τὰ σῦκα αὐτῷ φαγόντος, εἰπόντα τῇ γραῒ διδόναι ἄκρατον ἐπιρροφῆσαι τῷ ὄνῳ, ὑπερκαγχάσαντα τελευτῆσαι.",
    certainty: "reported",
    conflictsWith: ["chrysippus-death-wine"],
  },
  {
    id: "chrysippus-doctrine-nature-both",
    subject: "Chrysippus",
    property: "heldDoctrine",
    value:
      "The nature with which life should accord is both universal nature and the nature of man",
    valueType: "doctrine",
    ref: "7.89",
    grc: "Φύσιν δὲ Χρύσιππος μὲν ἐξακούει, ᾗ ἀκολούθως δεῖ ζῆν, τήν τε κοινὴν καὶ ἰδίως τὴν ἀνθρωπίνην·",
    certainty: "asserted",
    note: "As against Cleanthes, who took the nature of the universe alone.",
  },
  {
    id: "chrysippus-doctrine-standard",
    subject: "Chrysippus",
    property: "heldDoctrine",
    value: "Sensation and preconception are the only standards of truth",
    valueType: "doctrine",
    greek: "πρόληψις",
    ref: "7.54",
    grc: "ὁ δὲ Χρύσιππος διαφερόμενος πρὸς αὑτὸν ἐν τῷ πρώτῳ Περὶ λόγου κριτήριά φησιν εἶναι αἴσθησιν καὶ πρόληψιν· ἔστι δʼ ἡ πρόληψις ἔννοια φυσικὴ τῶν καθόλου.",
    certainty: "asserted",
    note: "Preconception being a general notion which comes by the gift of nature.",
  },
  {
    id: "chrysippus-doctrine-virtue-lost",
    subject: "Chrysippus",
    property: "heldDoctrine",
    value: "Virtue can be lost, in consequence of drunkenness or melancholy",
    valueType: "doctrine",
    ref: "7.127",
    grc: "καὶ μὴν τὴν ἀρετὴν Χρύσιππος μὲν ἀποβλητήν, Κλεάνθης δὲ ἀναπόβλητον· ὁ μὲν ἀποβλητὴν διὰ μέθην καὶ μελαγχολίαν, ὁ δʼ ἀναπόβλητον διὰ βεβαίους καταλήψεις·",
    certainty: "asserted",
    conflictsWith: ["cleanthes-doctrine-virtue-not-lost"],
  },
  {
    id: "chrysippus-doctrine-souls-wise",
    subject: "Chrysippus",
    property: "heldDoctrine",
    value: "Only the souls of the wise survive until the general conflagration",
    valueType: "doctrine",
    ref: "7.157",
    grc: "Κλεάνθης μὲν οὖν πάσας ἐπιδιαμένειν μέχρι τῆς ἐκπυρώσεως, Χρύσιππος δὲ τὰς τῶν σοφῶν μόνον.",
    certainty: "asserted",
    conflictsWith: ["cleanthes-doctrine-souls-survive"],
  },
  {
    id: "chrysippus-doctrine-passions-judgements",
    subject: "Chrysippus",
    property: "heldDoctrine",
    value: "The emotions are judgements",
    valueType: "doctrine",
    ref: "7.111",
    grc: "δοκεῖ δʼ αὐτοῖς τὰ πάθη κρίσεις εἶναι, καθά φησι Χρύσιππος ἐν τῷ Περὶ παθῶν·",
    certainty: "asserted",
    note: "So Chrysippus in his treatise On the Passions; e.g. avarice is a supposition that money is a good.",
  },
  {
    id: "chrysippus-doctrine-fate",
    subject: "Chrysippus",
    property: "heldDoctrine",
    value: "All things happen by fate or destiny",
    valueType: "doctrine",
    greek: "εἱμαρμένη",
    ref: "7.149",
    grc: "καθʼ εἱμαρμένην δέ φασι τὰ πάντα γίγνεσθαι Χρύσιππος ἐν τοῖς Περὶ εἱμαρμένης καὶ Ποσειδώνιος ἐν δευτέρῳ Περὶ εἱμαρμένης καὶ Ζήνων, Βόηθος δʼ ἐν τῷ πρώτῳ Περὶ εἱμαρμένης.",
    certainty: "asserted",
    note: "Maintained in his treatise De fato.",
  },
  {
    id: "chrysippus-doctrine-providence",
    subject: "Chrysippus",
    property: "heldDoctrine",
    value: "The world is ordered by reason and providence",
    valueType: "doctrine",
    greek: "πρόνοια",
    ref: "7.138",
    grc: "Τὸν δὴ κόσμον διοικεῖσθαι κατὰ νοῦν καὶ πρόνοιαν, καθά φησι Χρύσιππός τʼ ἐν τῷ πέμπτῳ Περὶ προνοίας καὶ Ποσειδώνιος ἐν τῷ τρίτῳ Περὶ θεῶν",
    certainty: "asserted",
    note: "So Chrysippus in the fifth book of his treatise On Providence.",
  },
  // Chrysippus - catalogue (7.189-202)
  {
    id: "chrysippus-wrote-logical-theses",
    subject: "Chrysippus",
    property: "wrote",
    value: "Logical Theses",
    valueType: "work",
    ref: "7.189",
    grc: "Θέσεις λογικαί",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-philosophers-inquiries",
    subject: "Chrysippus",
    property: "wrote",
    value: "The Philosopher's Inquiries",
    valueType: "work",
    ref: "7.189",
    grc: "καταγέλαστοι δὲ καὶ οἱ τρόποι τοῦ πορισμοῦ, οἷον οἱ ἀπὸ βασιλέως· εἴκειν γὰρ αὐτῷ δεήσει",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-dialectical-definitions",
    subject: "Chrysippus",
    property: "wrote",
    value: "Dialectical Definitions addressed to Metrodorus (6 books)",
    valueType: "work",
    ref: "7.189",
    grc: "Ὅρων διαλεκτικῶν πρὸς Μητρόδωρον ς′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-terms-dialectic",
    subject: "Chrysippus",
    property: "wrote",
    value: "On the Terms used in Dialectic, addressed to Zeno",
    valueType: "work",
    ref: "7.189",
    grc: "Περὶ τῶν κατὰ τὴν διαλεκτικὴν ὀνομάτων πρὸς Ζήνωνα α′.",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-art-dialectic",
    subject: "Chrysippus",
    property: "wrote",
    value: "Art of Dialectic, addressed to Aristagoras",
    valueType: "work",
    ref: "7.190",
    grc: "Τέχνη διαλεκτικὴ πρὸς Ἀρισταγόραν α′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-probable-hypothetical",
    subject: "Chrysippus",
    property: "wrote",
    value:
      "Probable Hypothetical Judgements, addressed to Dioscurides (4 books)",
    valueType: "work",
    ref: "7.190",
    grc: "Συνημμένων πιθανῶν πρὸς Διοσκουρίδην δ′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-of-judgements",
    subject: "Chrysippus",
    property: "wrote",
    value: "Of Judgements",
    valueType: "work",
    ref: "7.190",
    grc: "Περὶ ἀξιωμάτων α′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-complex-judgement",
    subject: "Chrysippus",
    property: "wrote",
    value: "Of the Complex Judgement, addressed to Athenades (2 books)",
    valueType: "work",
    ref: "7.190",
    grc: "Περὶ τῶν οὐχ ἁπλῶν ἀξιωμάτων α′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-negative-judgements",
    subject: "Chrysippus",
    property: "wrote",
    value: "Of Negative Judgements, addressed to Aristagoras (3 books)",
    valueType: "work",
    ref: "7.190",
    grc: "Περὶ τοῦ συμπεπλεγμένου πρὸς Ἀθηνάδην α′ β′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-true-disjunctive",
    subject: "Chrysippus",
    property: "wrote",
    value: "Of a True Disjunctive Judgement, addressed to Gorgippides",
    valueType: "work",
    ref: "7.190",
    grc: "Περὶ ἀποφατικῶν πρὸς Ἀρισταγόραν γ′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-true-hypothetical",
    subject: "Chrysippus",
    property: "wrote",
    value:
      "Of a True Hypothetical Judgement, addressed to Gorgippides (4 books)",
    valueType: "work",
    ref: "7.190",
    grc: "Περὶ τῶν καταγορευτικῶν πρὸς Ἀθηνόδωρον α′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-judgements-possibility",
    subject: "Chrysippus",
    property: "wrote",
    value: "On Judgements of Possibility, addressed to Clitus (4 books)",
    valueType: "work",
    ref: "7.191",
    grc: "Περὶ τοῦ διὰ τριῶν πάλιν πρὸς Γοργιππίδην α′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-of-predicates",
    subject: "Chrysippus",
    property: "wrote",
    value: "Of Predicates, addressed to Metrodorus (10 books)",
    valueType: "work",
    ref: "7.192",
    grc: "Περὶ τῶν κατηγορημάτων πρὸς Μητρόδωρον ι′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-singular-plural",
    subject: "Chrysippus",
    property: "wrote",
    value: "Of Singular and Plural Expressions (6 books)",
    valueType: "work",
    ref: "7.192",
    grc: "Περὶ τῶν συναμμάτων πρὸς Ἀπολλωνίδην α′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-solecisms",
    subject: "Chrysippus",
    property: "wrote",
    value: "On Solecisms",
    valueType: "work",
    ref: "7.192",
    grc: "Περὶ σολοικισμῶν",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-ambiguous-speech",
    subject: "Chrysippus",
    property: "wrote",
    value: "On Ambiguous Forms of Speech, addressed to Apollas (4 books)",
    valueType: "work",
    ref: "7.193",
    grc: "Περὶ τῆς συντάξεως καὶ στοιχείων τῶν λεγομενων πρὸς Φίλιππον γ′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-handbook-arguments-moods",
    subject: "Chrysippus",
    property: "wrote",
    value: "Handbook of Arguments and Moods, addressed to Dioscurides (5 books)",
    valueType: "work",
    ref: "7.193",
    grc: "Τέχνη λόγων καὶ τρόπων πρὸς Διοσκουρίδην ε′.",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-of-syllogisms",
    subject: "Chrysippus",
    property: "wrote",
    value: "Of Syllogisms (3 books)",
    valueType: "work",
    ref: "7.194",
    grc: "Περὶ τῶν λόγων γ′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-primary-indemonstrable",
    subject: "Chrysippus",
    property: "wrote",
    value: "On the Primary Indemonstrable Syllogisms, addressed to Zeno",
    valueType: "work",
    ref: "7.195",
    grc: "Περὶ τῶν περαινόντων λόγων πρὸς Ζήνωνα α′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-mentiens",
    subject: "Chrysippus",
    property: "wrote",
    value: "Of the Mentiens Argument, addressed to Aristocreon (6 books)",
    valueType: "work",
    ref: "7.196",
    grc: "Περὶ ὑποθέσεων πρὸς Μελέαγρον γ′",
    certainty: "asserted",
    note: "On the Liar paradox.",
  },
  {
    id: "chrysippus-wrote-nobody-puzzle",
    subject: "Chrysippus",
    property: "wrote",
    value: "Of the Nobody Puzzle, addressed to Menecrates (8 books)",
    valueType: "work",
    ref: "7.198",
    grc: "Περὶ τοῦ ἐγκεκαλυμμένου πρὸς Ἀριστόβουλον β′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-attack-common-sense",
    subject: "Chrysippus",
    property: "wrote",
    value: "Attack upon Common Sense, addressed to Metrodorus (6 books)",
    valueType: "work",
    ref: "7.198",
    grc: "Κατὰ τῆς συνηθείας πρὸς Μητρόδωρον ς′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-defence-common-sense",
    subject: "Chrysippus",
    property: "wrote",
    value: "Defence of Common Sense, addressed to Gorgippides (7 books)",
    valueType: "work",
    ref: "7.198",
    grc: "Σύνταξις ὀγδόη· Περὶ τοῦ οὔτιδος πρὸς Μενεκράτην η′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-outline-ethical",
    subject: "Chrysippus",
    property: "wrote",
    value: "Outline of Ethical Theory, addressed to Theoporos",
    valueType: "work",
    ref: "7.199",
    grc: "Ὑπογραφὴ τοῦ 〈ἠθικοῦ〉 λόγου πρὸς Θεόπορον α′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-definitions-good",
    subject: "Chrysippus",
    property: "wrote",
    value: "Definitions of the Good or Virtuous, addressed to Metrodorus (2 books)",
    valueType: "work",
    ref: "7.199",
    grc: "Ὅρων τῶν τοῦ ἀστείου πρὸς Μητρόδωρον β′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-of-poems",
    subject: "Chrysippus",
    property: "wrote",
    value: "Of Poems, addressed to Philomathes",
    valueType: "work",
    ref: "7.200",
    grc: "Περὶ εἰδῶν καὶ γενῶν πρὸς Γοργιππίδην β′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-of-rhetoric",
    subject: "Chrysippus",
    property: "wrote",
    value: "Of Rhetoric, addressed to Dioscurides (4 books)",
    valueType: "work",
    ref: "7.202",
    grc: "Περὶ τῆς ῥητορικῆς πρὸς Διοσκουρίδην δ′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-good-pleasure",
    subject: "Chrysippus",
    property: "wrote",
    value:
      "Of the Good or Morally Beautiful and Pleasure, addressed to Aristocreon (10 books)",
    valueType: "work",
    ref: "7.202",
    grc: "Ἀποδείξεις πρὸς τὸ μὴ εἶναι τὴν ἡδονὴν ἀγαθὸν δ′",
    certainty: "asserted",
  },
  {
    id: "chrysippus-wrote-de-republica",
    subject: "Chrysippus",
    property: "wrote",
    value: "De Republica",
    valueType: "work",
    ref: "7.34",
    grc: "ὅτι δʼ αὐτοῦ ἐστιν ἡ Πολιτεία καὶ Χρύσιππος ἐν τῷ Περὶ πολιτείας φησί",
    certainty: "asserted",
    note: "In it he attests that the Republic is the work of Zeno.",
  },
];
