/**
 * Curated claims from Book 9 of Diogenes Laertius' Lives, cited to
 * Hicks section ids (book.section). See kg-claims.ts for the model and
 * curation rules. Source-internal: every claim cites a D.L. passage.
 */
import type { KgClaim } from "../kg-claims";

export const BOOK9_CLAIMS: KgClaim[] = [
  // ---------------------------------------------------------------- Heraclitus
  {
    id: "heraclitus-parentage-bloson",
    subject: "Heraclitus",
    property: "parentage",
    value: "Son of Bloson, or, according to some, of Heracon",
    valueType: "literal",
    ref: "9.1",
    grc: "Ἡράκλειτος Βλόσωνος ἤ, ὥς τινες, Ἡράκωντος Ἐφέσιος",
    certainty: "reported",
  },
  {
    id: "heraclitus-birthplace-ephesus",
    subject: "Heraclitus",
    property: "birthPlace",
    value: "Ephesus",
    valueType: "place",
    ref: "9.1",
    grc: "μεγαλόφρ ων δὲ γέγονε παρʼ ὁντιναοῦ καὶ ὑπερόπτης, ὡς καὶ ἐκ τοῦ συγγράμματος αὐτοῦ δῆλον, ἐν ᾧ φησι, πολυμαθίη νόον οὐ διδάσκει",
    certainty: "asserted",
  },
  {
    id: "heraclitus-floruit",
    subject: "Heraclitus",
    property: "birthDate",
    value: "Flourished in the 69th Olympiad (504/501 BCE)",
    valueType: "literal",
    ref: "9.1",
    grc: "οὗτος ἤκμαζε μὲν κατὰ τὴν ἐνάτην καὶ ἑξηκοστὴν Ὀλυμπιάδα. μεγαλόφρ ων δὲ γέγονε παρʼ ὁντιναοῦ καὶ ὑπερόπτης, ὡς καὶ ἐκ τοῦ συγγράμματος αὐτοῦ δῆλον, ἐν ᾧ φησι, πολυμαθίη νόον οὐ διδάσκει",
    certainty: "asserted",
  },
  {
    id: "heraclitus-education-self-taught",
    subject: "Heraclitus",
    property: "education",
    value: "Nobody's pupil; he inquired of himself and learned everything from himself",
    valueType: "literal",
    ref: "9.5",
    grc: "ἤκουσέ τʼ οὐδενός, ἀλλʼ αὑτὸν ἔφη διζήσασθαι καὶ μαθεῖν πάντα παρʼ ἑαυτοῦ",
    certainty: "asserted",
    conflictsWith: ["heraclitus-studied-xenophanes"],
  },
  {
    id: "heraclitus-studied-xenophanes",
    subject: "Heraclitus",
    property: "studiedUnder",
    value: "Xenophanes",
    valueType: "philosopher",
    ref: "9.5",
    grc: "ἤκουσέ τʼ οὐδενός, ἀλλʼ αὑτὸν ἔφη διζήσασθαι καὶ μαθεῖν πάντα παρʼ ἑαυτοῦ",
    certainty: "reported",
    accordingTo: "Sotion",
    conflictsWith: ["heraclitus-education-self-taught"],
  },
  {
    id: "heraclitus-wrote-nature",
    subject: "Heraclitus",
    property: "wrote",
    value: "On Nature (a continuous treatise in three discourses: on the universe, on politics, on theology)",
    valueType: "work",
    ref: "9.5",
    grc: "Τὸ δὲ φερόμενον αὐτοῦ βιβλίον ἐστὶ μὲν ἀπὸ τοῦ συνέχοντος Περὶ φύσεως, διῄρηται δʼ εἰς τρεῖς λόγους, εἴς τε τὸν περὶ τοῦ παντὸς καὶ πολιτικὸν καὶ θεολογικόν.",
    certainty: "asserted",
    note: "Deposited in the temple of Artemis; deliberately obscure, some say.",
  },
  {
    id: "heraclitus-death-dung",
    subject: "Heraclitus",
    property: "mannerOfDeath",
    value: "Fell ill of dropsy, buried himself in cow-dung hoping the warmth would draw off the moisture, and died at sixty",
    valueType: "literal",
    ref: "9.3",
    grc: "καὶ μέντοι καὶ διὰ τοῦτο περιτραπεὶς εἰς ὕδερον κατῆλθεν εἰς ἄστυ καὶ τῶν ἰατρῶν αἰνιγματωδῶς ἐπυνθάνετο εἰ δύναιντʼ ἐξ ἐπομβρίας αὐχμὸν ποιῆσαι· τῶν δὲ μὴ συνιέντων, αὑτὸν εἰς βουστάσιον κατορύξας τῇ τῶν βολίτων ἀλέᾳ ἤλπισεν ἐξατμισθήσεσθαι. οὐδὲν δʼ ἀνύων οὐδʼ οὕτως, ἐτελεύτα βιοὺς ἔτη ἑξήκοντα.",
    certainty: "asserted",
    conflictsWith: ["heraclitus-death-dogs", "heraclitus-death-other-disease"],
  },
  {
    id: "heraclitus-death-dogs",
    subject: "Heraclitus",
    property: "mannerOfDeath",
    value: "Unable to tear off the dung, he remained as he was and, being unrecognizable, was devoured by dogs",
    valueType: "literal",
    ref: "9.4",
    grc: "Νεάνθης δʼ ὁ Κυζικηνός φησι μὴ δυνηθέντʼ αὐτὸν ἀποσπάσαι τὰ βόλιτα μεῖναι καὶ διὰ τὴν μεταβολὴν ἀγνοηθέντα κυνόβρωτον γενέσθαι.",
    certainty: "reported",
    accordingTo: "Neanthes",
    conflictsWith: ["heraclitus-death-dung", "heraclitus-death-other-disease"],
  },
  {
    id: "heraclitus-death-other-disease",
    subject: "Heraclitus",
    property: "mannerOfDeath",
    value: "Was cured of the dropsy and died of another disease",
    valueType: "literal",
    ref: "9.5",
    grc: "λέγειν τε Ἀρίστωνα ἐν τῷ Περὶ Ἡρακλείτου καὶ τὸν ὕδερον αὐτὸν θεραπευθῆναι, ἀποθανεῖν δʼ ἄλλῃ νόσῳ.",
    certainty: "reported",
    // 9.5: "as we learn from Sotion, who also tells us that Ariston in his
    // book On Heraclitus says that he was cured of the dropsy and died of
    // another disease" - D.L.'s nearest source is Sotion, transmitting
    // Ariston's account, so the work moves into the chain link.
    accordingTo: "Sotion",
    chain: [{ authority: "Ariston", work: "On Heraclitus" }],
    conflictsWith: ["heraclitus-death-dung", "heraclitus-death-dogs"],
  },
  {
    id: "heraclitus-doctrine-fire",
    subject: "Heraclitus",
    property: "heldDoctrine",
    value: "All things are composed of fire and into fire are again resolved",
    valueType: "doctrine",
    ref: "9.8",
    grc: "πῦρ εἶναι στοιχεῖον καὶ πυρὸς ἀμοιβὴν τὰ πάντα, ἀραιώσει καὶ πυκνώσει γινόμενα.",
    certainty: "asserted",
    greek: "πῦρ",
  },
  {
    id: "heraclitus-doctrine-destiny",
    subject: "Heraclitus",
    property: "heldDoctrine",
    value: "All things come about by destiny",
    valueType: "doctrine",
    ref: "9.7",
    grc: "πάντα δὲ γίνεσθαι καθʼ εἱμαρμένην καὶ διὰ τῆς ἐναντιοδρομίας ἡρμόσθαι τὰ ὄντα·",
    certainty: "asserted",
    greek: "εἱμαρμένη",
  },
  {
    id: "heraclitus-doctrine-flux",
    subject: "Heraclitus",
    property: "heldDoctrine",
    value: "All that is flows like a stream and comes into being by conflict of opposites",
    valueType: "doctrine",
    ref: "9.8",
    grc: "γίνεσθαί τε πάντα κατʼ ἐναντιότητα καὶ ῥεῖν τὰ ὅλα ποταμοῦ δίκην, πεπεράνθαι τε τὸ πᾶν καὶ ἕνα εἶναι κόσμον·",
    certainty: "asserted",
  },
  {
    id: "heraclitus-criticized-pythagoras",
    subject: "Heraclitus",
    property: "criticized",
    value: "Pythagoras",
    valueType: "philosopher",
    ref: "9.1",
    grc: "πολυμαθίη νόον οὐ διδάσκει· Ἡσίοδον γὰρ ἂν ἐδίδαξε καὶ Πυθαγόρην, αὖτίς τε Ξενοφάνεά τε καὶ Ἑκαταῖον.",
    certainty: "asserted",
    note: "Much learning does not teach understanding; else would it have taught Pythagoras.",
  },
  {
    id: "heraclitus-criticized-xenophanes",
    subject: "Heraclitus",
    property: "criticized",
    value: "Xenophanes",
    valueType: "philosopher",
    ref: "9.1",
    grc: "πολυμαθίη νόον οὐ διδάσκει· Ἡσίοδον γὰρ ἂν ἐδίδαξε καὶ Πυθαγόρην, αὖτίς τε Ξενοφάνεά τε καὶ Ἑκαταῖον.",
    certainty: "asserted",
  },
  {
    id: "heraclitus-criticized-homer",
    subject: "Heraclitus",
    property: "criticized",
    value: "Homer",
    valueType: "person",
    ref: "9.1",
    grc: "τόν τε Ὅμηρον ἔφασκεν ἄξιον ἐκ τῶν ἀγώνων ἐκβάλλεσθαι καὶ ῥαπίζεσθαι, καὶ Ἀρχίλοχον ὁμοίως.",
    certainty: "asserted",
    note: "Said Homer deserved to be chased out of the lists and beaten with rods.",
  },

  // ---------------------------------------------------------------- Xenophanes
  {
    id: "xenophanes-parentage-dexius",
    subject: "Xenophanes",
    property: "parentage",
    value: "Son of Dexius, or, according to Apollodorus, of Orthomenes",
    valueType: "literal",
    ref: "9.18",
    grc: "οὗτος ἐκπεσὼν τῆς πατρίδος ἐν Ζάγκλῃ τῆς Σικελίας * * * διέτριβε δὲ καὶ ἐν Κατάνῃ",
    certainty: "reported",
    accordingTo: "Apollodorus",
  },
  {
    id: "xenophanes-birthplace-colophon",
    subject: "Xenophanes",
    property: "birthPlace",
    value: "Colophon",
    valueType: "place",
    ref: "9.18",
    grc: "μακροβιώτατός τε γέγονεν, ὥς που καὶ αὐτός φησιν·",
    certainty: "asserted",
  },
  {
    id: "xenophanes-lived-elea",
    subject: "Xenophanes",
    property: "livedIn",
    value: "Elea",
    valueType: "place",
    ref: "9.18",
    grc: "οὗτος ἐκπεσὼν τῆς πατρίδος ἐν Ζάγκλῃ τῆς Σικελίας * * * διέτριβε δὲ καὶ ἐν Κατάνῃ",
    certainty: "reported",
    note: "Banished from Colophon, lived at Zancle and Catana in Sicily, and taught at the colony of Elea.",
  },
  {
    id: "xenophanes-affiliated-eleatic",
    subject: "Xenophanes",
    property: "affiliatedWith",
    value: "Eleatics, Atomists, Sceptics",
    valueType: "school",
    ref: "9.18",
    grc: "Ξενοφάνης Δεξίου ἤ, ὡς Ἀπολλόδωρος, Ὀρθομένους Κολοφώνιος ἐπαινεῖται πρὸς τοῦ Τίμωνος",
    certainty: "asserted",
  },
  {
    id: "xenophanes-education-self-taught",
    subject: "Xenophanes",
    property: "education",
    value: "According to some, no man's pupil",
    valueType: "literal",
    ref: "9.18",
    grc: "Ξενοφάνης Δεξίου ἤ, ὡς Ἀπολλόδωρος, Ὀρθομένους Κολοφώνιος ἐπαινεῖται πρὸς τοῦ Τίμωνος",
    certainty: "reported",
    conflictsWith: [
      "xenophanes-studied-archelaus",
      "xenophanes-succession-italian",
    ],
  },
  {
    id: "xenophanes-studied-archelaus",
    subject: "Xenophanes",
    property: "studiedUnder",
    value: "Archelaus",
    valueType: "philosopher",
    ref: "9.18",
    grc: "Ξενοφάνης Δεξίου ἤ, ὡς Ἀπολλόδωρος, Ὀρθομένους Κολοφώνιος ἐπαινεῖται πρὸς τοῦ Τίμωνος",
    certainty: "reported",
    note: "Others say a pupil of Boton of Athens, or of Archelaus.",
    conflictsWith: ["xenophanes-education-self-taught"],
  },
  {
    id: "xenophanes-floruit",
    subject: "Xenophanes",
    property: "birthDate",
    value: "Flourished about the 60th Olympiad (540/537 BCE)",
    valueType: "literal",
    ref: "9.20",
    grc: "ἤκμαζε κατὰ τὴν ἑξηκοστὴν Ὀλυμπιάδα",
    certainty: "asserted",
  },
  {
    id: "xenophanes-wrote-colophon",
    subject: "Xenophanes",
    property: "wrote",
    value: "The Founding of Colophon",
    valueType: "work",
    ref: "9.20",
    grc: "Ἐποίησε δὲ καὶ Κολοφῶνος κτίσιν καὶ τὸν εἰς Ἐλέαν τῆς Ἰταλίας ἀποικισμὸν ἔπη δισχίλια",
    certainty: "asserted",
  },
  {
    id: "xenophanes-wrote-elea",
    subject: "Xenophanes",
    property: "wrote",
    value: "The Settlement of a Colony at Elea in Italy",
    valueType: "work",
    ref: "9.20",
    grc: "Ἔφη δὲ καὶ τὰ πολλὰ ἥσσω νοῦ εἶναι",
    certainty: "asserted",
    note: "The two poems making 2000 lines in all.",
  },
  {
    id: "xenophanes-doctrine-god-one",
    subject: "Xenophanes",
    property: "heldDoctrine",
    value: "The substance of God is spherical, in no way resembling man; all eye and all ear, eternal",
    valueType: "doctrine",
    ref: "9.19",
    grc: "οὐσίαν θεοῦ σφαιροειδῆ, μηδὲν ὅμοιον ἔχουσαν ἀνθρώπῳ· ὅλον δὲ ὁρᾶν καὶ ὅλον ἀκούειν, μὴ μέντοι ἀναπνεῖν· σύμπαντά τε εἶναι νοῦν καὶ φρόνησιν καὶ ἀΐδιον.",
    certainty: "asserted",
  },
  {
    id: "xenophanes-doctrine-perishing",
    subject: "Xenophanes",
    property: "heldDoctrine",
    value: "Everything which comes into being is doomed to perish, and the soul is breath",
    valueType: "doctrine",
    ref: "9.19",
    grc: "πρῶτός τε ἀπεφήνατο ὅτι πᾶν τὸ γινόμενον φθαρτόν ἐστι καὶ ἡ ψυχὴ πνεῦμα.",
    certainty: "asserted",
  },
  {
    id: "xenophanes-criticized-thales",
    subject: "Xenophanes",
    property: "criticized",
    value: "Thales",
    valueType: "philosopher",
    ref: "9.18",
    grc: "ἀντιδοξάσαι τε λέγεται Θαλῇ καὶ Πυθαγόρᾳ, καθάψασθαι δὲ καὶ Ἐπιμενίδου.",
    certainty: "asserted",
    note: "He opposed the views of Thales and Pythagoras, and attacked Epimenides.",
  },
  {
    id: "xenophanes-criticized-pythagoras",
    subject: "Xenophanes",
    property: "criticized",
    value: "Pythagoras",
    valueType: "philosopher",
    ref: "9.18",
    grc: "ἀντιδοξάσαι τε λέγεται Θαλῇ καὶ Πυθαγόρᾳ, καθάψασθαι δὲ καὶ Ἐπιμενίδου.",
    certainty: "asserted",
  },
  {
    id: "xenophanes-criticized-homer",
    subject: "Xenophanes",
    property: "criticized",
    value: "Homer",
    valueType: "person",
    ref: "9.18",
    grc: "γέγραφε δὲ καὶ ἐν ἔπεσι καὶ ἐλεγείας καὶ ἰάμβους καθʼ Ἡσιόδου καὶ Ὁμήρου, ἐπικόπτων αὐτῶν τὰ περὶ θεῶν εἰρημένα.",
    certainty: "asserted",
    note: "Denounced what Hesiod and Homer said about the gods.",
  },

  // ---------------------------------------------------------------- Parmenides
  {
    id: "parmenides-parentage-pyres",
    subject: "Parmenides",
    property: "parentage",
    value: "Son of Pyres, of illustrious birth and great wealth",
    valueType: "literal",
    ref: "9.21",
    grc: "Ξενοφάνους δὲ διήκουσε Παρμενίδης Πύρητος Ἐλεάτης (τοῦτον Θεόφραστος ἐν τῇ Ἐπιτομῇ Ἀναξιμάνδρου φησὶν ἀκοῦσαι)",
    certainty: "asserted",
  },
  {
    id: "parmenides-birthplace-elea",
    subject: "Parmenides",
    property: "birthPlace",
    value: "Elea",
    valueType: "place",
    ref: "9.21",
    grc: "Ξενοφάνους δὲ διήκουσε Παρμενίδης Πύρητος Ἐλεάτης (τοῦτον Θεόφραστος ἐν τῇ Ἐπιτομῇ Ἀναξιμάνδρου φησὶν ἀκοῦσαι)",
    certainty: "asserted",
  },
  {
    id: "parmenides-studied-xenophanes",
    subject: "Parmenides",
    property: "studiedUnder",
    value: "Xenophanes",
    valueType: "philosopher",
    ref: "9.21",
    grc: "Ξενοφάνους δὲ διήκουσε Παρμενίδης Πύρητος Ἐλεάτης (τοῦτον Θεόφραστος ἐν τῇ Ἐπιτομῇ Ἀναξιμάνδρου φησὶν ἀκοῦσαι)",
    certainty: "asserted",
    note: "Instructed by Xenophanes, but no follower of his.",
    conflictsWith: ["parmenides-studied-anaximander"],
  },
  {
    id: "parmenides-studied-anaximander",
    subject: "Parmenides",
    property: "studiedUnder",
    value: "Anaximander",
    valueType: "philosopher",
    ref: "9.21",
    grc: "Ξενοφάνους δὲ διήκουσε Παρμενίδης Πύρητος Ἐλεάτης (τοῦτον Θεόφραστος ἐν τῇ Ἐπιτομῇ Ἀναξιμάνδρου φησὶν ἀκοῦσαι)",
    certainty: "reported",
    accordingTo: "Theophrastus",
    conflictsWith: ["parmenides-studied-xenophanes"],
  },
  {
    id: "parmenides-studied-ameinias",
    subject: "Parmenides",
    property: "studiedUnder",
    value: "Ameinias",
    valueType: "person",
    ref: "9.21",
    grc: "Ξενοφάνους δὲ διήκουσε Παρμενίδης Πύρητος Ἐλεάτης (τοῦτον Θεόφραστος ἐν τῇ Ἐπιτομῇ Ἀναξιμάνδρου φησὶν ἀκοῦσαι)",
    certainty: "reported",
    accordingTo: "Sotion",
    note: "Ameinias the Pythagorean led him to adopt the peaceful life of a student.",
  },
  {
    id: "parmenides-floruit",
    subject: "Parmenides",
    property: "birthDate",
    value: "Flourished in the 69th Olympiad (504/501 BCE)",
    valueType: "literal",
    ref: "9.23",
    grc: "Ἤκμαζε δὲ κατὰ τὴν ἐνάτην καὶ ἑξηκοστὴν Ὀλυμπιάδα",
    certainty: "asserted",
  },
  {
    id: "parmenides-doctrine-earth-spherical",
    subject: "Parmenides",
    property: "heldDoctrine",
    value: "The earth is spherical and situated in the centre of the universe",
    valueType: "doctrine",
    ref: "9.21",
    grc: "Πρῶτος δʼ οὗτος τὴν γῆν ἀπέφαινε σφαιροειδῆ καὶ ἐν μέσῳ κεῖσθαι.",
    certainty: "asserted",
    note: "First to declare it.",
  },
  {
    id: "parmenides-doctrine-truth-opinion",
    subject: "Parmenides",
    property: "heldDoctrine",
    value: "Philosophy is divided into two parts, dealing the one with truth, the other with opinion",
    valueType: "doctrine",
    ref: "9.22",
    grc: "δισσήν τε ἔφη τὴν φιλοσοφίαν, τὴν μὲν κατʼ ἀλήθειαν, τὴν δὲ κατὰ δόξαν.",
    certainty: "asserted",
    greek: "ἀλήθεια καὶ δόξα",
  },
  {
    id: "parmenides-doctrine-reason-standard",
    subject: "Parmenides",
    property: "heldDoctrine",
    value: "Reason is the standard; sensations are inexact",
    valueType: "doctrine",
    ref: "9.22",
    grc: "κριτήριον δὲ τὸν λόγον εἶπε· τάς τε αἰσθήσεις μὴ ἀκριβεῖς ὑπάρχειν.",
    certainty: "asserted",
  },

  // ---------------------------------------------------------------- Melissus
  {
    id: "melissus-parentage-ithaegenes",
    subject: "Melissus",
    property: "parentage",
    value: "Son of Ithaegenes",
    valueType: "literal",
    ref: "9.24",
    grc: "Μέλισσος Ἰθαιγένους Σάμιος",
    certainty: "asserted",
  },
  {
    id: "melissus-birthplace-samos",
    subject: "Melissus",
    property: "birthPlace",
    value: "Samos",
    valueType: "place",
    ref: "9.24",
    grc: "γέγονε δὲ καὶ πολιτικὸς ἀνὴρ καὶ ἀποδοχῆς παρὰ τοῖς πολίταις ἠξιωμένος",
    certainty: "asserted",
  },
  {
    id: "melissus-studied-parmenides",
    subject: "Melissus",
    property: "studiedUnder",
    value: "Parmenides",
    valueType: "philosopher",
    ref: "9.24",
    grc: "οὗτος ἤκουσε Παρμενίδου",
    certainty: "asserted",
  },
  {
    id: "melissus-floruit",
    subject: "Melissus",
    property: "birthDate",
    value: "Flourished in the 84th Olympiad (444/441 BCE)",
    valueType: "literal",
    ref: "9.24",
    grc: "ἠκμακέναι αὐτὸν κατὰ τὴν τετάρτην καὶ ὀγδοηκοστὴν Ὀλυμπιάδα",
    certainty: "reported",
    accordingTo: "Apollodorus",
  },
  {
    id: "melissus-doctrine-universe",
    subject: "Melissus",
    property: "heldDoctrine",
    value: "The universe is unlimited, unchangeable, immovable, one, uniform and full of matter; motion is only apparent",
    valueType: "doctrine",
    ref: "9.24",
    grc: "Ἐδόκει δʼ αὐτῷ τὸ πᾶν ἄπειρον εἶναι καὶ ἀναλλοίωτον καὶ ἀκίνητον καὶ ἓν ὅμοιον ἑαυτῷ καὶ πλῆρες· κίνησίν τε μὴ εἶναι, δοκεῖν δʼ εἶναι.",
    certainty: "asserted",
  },
  {
    id: "melissus-doctrine-gods",
    subject: "Melissus",
    property: "heldDoctrine",
    value: "We ought not to make any statements about the gods, for it is impossible to have knowledge of them",
    valueType: "doctrine",
    ref: "9.24",
    grc: "ἀλλὰ καὶ περὶ θεῶν ἔλεγε μὴ δεῖν ἀποφαίνεσθαι· μὴ γὰρ εἶναι γνῶσιν αὐτῶν.",
    certainty: "asserted",
  },

  // ---------------------------------------------------------------- Zeno of Elea
  {
    id: "zeno-elea-parentage-teleutagoras",
    subject: "Zeno of Elea",
    property: "parentage",
    value: "Son of Teleutagoras by birth, but of Parmenides by adoption",
    valueType: "literal",
    ref: "9.25",
    grc: "Ζήνων Ἐλεάτης",
    certainty: "reported",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
  },
  {
    id: "zeno-elea-birthplace-elea",
    subject: "Zeno of Elea",
    property: "birthPlace",
    value: "Elea",
    valueType: "place",
    ref: "9.25",
    grc: "Ὁ δὴ Ζήνων διακήκοε Παρμενίδου καὶ γέγονεν αὐτοῦ παιδικά",
    certainty: "asserted",
  },
  {
    id: "zeno-elea-studied-parmenides",
    subject: "Zeno of Elea",
    property: "studiedUnder",
    value: "Parmenides",
    valueType: "philosopher",
    ref: "9.25",
    grc: "Ζήνων Ἐλεάτης",
    certainty: "asserted",
    note: "All through a pupil of Parmenides and his bosom friend.",
  },
  {
    id: "zeno-elea-floruit",
    subject: "Zeno of Elea",
    property: "birthDate",
    value: "Flourished in the 79th Olympiad (464/461 BCE)",
    valueType: "literal",
    ref: "9.29",
    grc: "ἤκμαζε δʼ οὗτος κατὰ τὴν ἐνάτην",
    certainty: "asserted",
  },
  {
    id: "zeno-elea-doctrine-dialectic",
    subject: "Zeno of Elea",
    property: "heldDoctrine",
    value: "Inventor of dialectic",
    valueType: "doctrine",
    ref: "9.25",
    grc: "φησὶ δʼ Ἀριστοτέλης εὑρετὴν αὐτὸν γενέσθαι διαλεκτικῆς, ὥσπερ Ἐμπεδοκλέα ῥητορικῆς.",
    certainty: "reported",
    accordingTo: "Aristotle",
  },
  {
    id: "zeno-elea-doctrine-achilles",
    subject: "Zeno of Elea",
    property: "heldDoctrine",
    value: "First to propound the argument of the Achilles",
    valueType: "doctrine",
    ref: "9.29",
    grc: "Οὗτος καὶ τὸν Ἀχιλλέα πρῶτος λόγον ἠρώτησε [Φαβωρῖνος δέ φησι Παρμενίδην] καὶ ἄλλους συχνούς.",
    certainty: "asserted",
    note: "Favorinus attributes it to Parmenides.",
  },
  {
    id: "zeno-elea-doctrine-void",
    subject: "Zeno of Elea",
    property: "heldDoctrine",
    value: "There are worlds, but there is no empty space",
    valueType: "doctrine",
    ref: "9.29",
    grc: "ἀρέσκει δʼ αὐτῷ τάδε· κόσμους εἶναι κενόν τε μὴ εἶναι·",
    certainty: "asserted",
  },
  {
    id: "zeno-elea-death-ear",
    subject: "Zeno of Elea",
    property: "mannerOfDeath",
    value: "Arrested for plotting against the tyrant; bit off the tyrant's ear and held on until stabbed to death",
    valueType: "literal",
    ref: "9.26",
    grc: "εἶτα περί τινων εἰπεῖν ἔχειν τινα 〈ἔφη〉 αὐτῷ πρὸς τὸ οὖς καὶ δακὼν οὐκ ἀνῆκεν ἕως ἀπεκεντήθη, ταὐτὸν Ἀριστογείτονι τῷ τυραννοκτόνῳ παθών.",
    certainty: "reported",
    // 9.26: "so Heraclides in his epitome of Satyrus" - Heraclides Lembus
    // transmits Satyrus' account (the epitome's title is not named here).
    accordingTo: "Heraclides",
    chain: [{ authority: "Satyrus" }],
    conflictsWith: ["zeno-elea-death-nose", "zeno-elea-death-mortar"],
  },
  {
    id: "zeno-elea-death-nose",
    subject: "Zeno of Elea",
    property: "mannerOfDeath",
    value: "Bit off the tyrant's nose, not his ear; at last bit off his own tongue and spat it at him, and was stoned",
    valueType: "literal",
    ref: "9.27",
    grc: "Δημήτριος δέ φησιν ἐν τοῖς Ὁμωνύμοις τὸν μυκτῆρα αὐτὸν ἀποτραγεῖν.",
    certainty: "reported",
    accordingTo: "Demetrius",
    sourceWork: "Homonyms",
    conflictsWith: ["zeno-elea-death-ear", "zeno-elea-death-mortar"],
  },
  {
    id: "zeno-elea-death-mortar",
    subject: "Zeno of Elea",
    property: "mannerOfDeath",
    value: "Cast into a mortar and beaten to death",
    valueType: "literal",
    ref: "9.27",
    grc: "Ἕρμιππος δέ φησιν εἰς ὅλμον αὐτὸν βληθῆναι καὶ κατακοπῆναι.",
    certainty: "reported",
    accordingTo: "Hermippus",
    conflictsWith: ["zeno-elea-death-ear", "zeno-elea-death-nose"],
  },

  // ---------------------------------------------------------------- Leucippus
  {
    id: "leucippus-birthplace-elea",
    subject: "Leucippus",
    property: "birthPlace",
    value: "Elea, but some say Abdera and others Miletus",
    valueType: "place",
    ref: "9.30",
    grc: "Λεύκιππος Ἐλεάτης, ὡς δέ τινες, Ἀβδηρίτης, κατʼ ἐνίους δὲ Μιλήσιος",
    certainty: "reported",
  },
  {
    id: "leucippus-studied-zeno",
    subject: "Leucippus",
    property: "studiedUnder",
    value: "Zeno of Elea",
    valueType: "philosopher",
    ref: "9.30",
    grc: "οὗτος ἤκουσε Ζήνωνος",
    certainty: "asserted",
  },
  {
    id: "leucippus-affiliated-atomist",
    subject: "Leucippus",
    property: "affiliatedWith",
    value: "Eleatics, Atomists, Sceptics",
    valueType: "school",
    ref: "9.30",
    grc: "Λεύκιππος Ἐλεάτης, ὡς δέ τινες, Ἀβδηρίτης, κατʼ ἐνίους δὲ Μιλήσιος",
    certainty: "asserted",
    note: "First to set up atoms as first principles.",
  },
  {
    id: "leucippus-doctrine-atoms",
    subject: "Leucippus",
    property: "heldDoctrine",
    value: "Atoms and the void are first principles; the worlds are formed when atoms fall into the void and entangle in a vortex",
    valueType: "doctrine",
    ref: "9.31",
    grc: "τούτου δὲ τὸ μὲν πλῆρες εἶναι, τὸ δὲ κενόν, 〈ἃ〉 καὶ στοιχεῖά φησι. κόσμους τε ἐκ τούτων ἀπείρους εἶναι καὶ διαλύεσθαι εἰς ταῦτα.",
    certainty: "asserted",
    greek: "ἄτομα καὶ κενόν",
  },

  // ---------------------------------------------------------------- Democritus
  {
    id: "democritus-parentage-hegesistratus",
    subject: "Democritus",
    property: "parentage",
    value: "Son of Hegesistratus, though some say of Athenocritus, and others of Damasippus",
    valueType: "literal",
    ref: "9.34",
    grc: "οὗτος μάγων τινῶν διήκουσε καὶ Χαλδαίων, Ξέρξου τοῦ βασιλέως τῷ πατρὶ αὐτοῦ ἐπιστάτας καταλιπόντος, ἡνίκα ἐξενίσθη παρʼ αὐτῷ, καθά φησι καὶ Ἡρόδοτος",
    certainty: "reported",
  },
  {
    id: "democritus-birthplace-abdera",
    subject: "Democritus",
    property: "birthPlace",
    value: "Abdera, or, according to some, Miletus",
    valueType: "place",
    ref: "9.34",
    grc: "Δημόκριτος Ἡγησιστράτου, οἱ δὲ Ἀθηνοκρίτου, τινὲς Δαμασίππου Ἀβδηρίτης ἤ, ὡς ἔνιοι, Μιλήσιος",
    certainty: "reported",
  },
  {
    id: "democritus-studied-leucippus",
    subject: "Democritus",
    property: "studiedUnder",
    value: "Leucippus",
    valueType: "philosopher",
    ref: "9.34",
    grc: "Δημόκριτος Ἡγησιστράτου, οἱ δὲ Ἀθηνοκρίτου, τινὲς Δαμασίππου Ἀβδηρίτης ἤ, ὡς ἔνιοι, Μιλήσιος",
    certainty: "asserted",
    conflictsWith: ["democritus-studied-anaxagoras"],
  },
  {
    id: "democritus-studied-anaxagoras",
    subject: "Democritus",
    property: "studiedUnder",
    value: "Anaxagoras",
    valueType: "philosopher",
    ref: "9.34",
    grc: "Δημόκριτος Ἡγησιστράτου, οἱ δὲ Ἀθηνοκρίτου, τινὲς Δαμασίππου Ἀβδηρίτης ἤ, ὡς ἔνιοι, Μιλήσιος",
    certainty: "disputed",
    note: "Some suggest it, but D.L. doubts it, as Democritus pulled Anaxagoras's views to pieces.",
    conflictsWith: ["democritus-studied-leucippus"],
  },
  {
    id: "democritus-studied-magi",
    subject: "Democritus",
    property: "studiedUnder",
    value: "Magians and Chaldaeans",
    valueType: "person",
    ref: "9.34",
    grc: "Δημόκριτος Ἡγησιστράτου, οἱ δὲ Ἀθηνοκρίτου, τινὲς Δαμασίππου Ἀβδηρίτης ἤ, ὡς ἔνιοι, Μιλήσιος",
    certainty: "asserted",
    note: "Left by Xerxes with Democritus's father; taught him theology and astronomy.",
  },
  {
    id: "democritus-traveled-egypt",
    subject: "Democritus",
    property: "traveledTo",
    value: "Egypt",
    valueType: "place",
    ref: "9.35",
    grc: "διασύρειν τε αὐτοῦ τὰ περὶ τῆς διακοσμήσεως καὶ τοῦ νοῦ, ἐχθρῶς ἔχοντα πρὸς αὐτὸν ὅτι δὴ μὴ προσήκατο αὐτόν",
    certainty: "reported",
    note: "Also Persia, the Red Sea, and, some say, India and Aethiopia.",
  },
  {
    id: "democritus-birth-ol80",
    subject: "Democritus",
    property: "birthDate",
    value: "Born in the 80th Olympiad (460/457 BCE)",
    valueType: "literal",
    ref: "9.41",
    grc: "ὡς μὲν Ἀπολλόδωρος ἐν Χρονικοῖς, κατὰ τὴν ὀγδοηκοστὴν Ὀλυμπιάδα",
    certainty: "reported",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
    conflictsWith: ["democritus-birth-ol77"],
  },
  {
    id: "democritus-birth-ol77",
    subject: "Democritus",
    property: "birthDate",
    value: "Born in the third year of the 77th Olympiad (470 BCE), one year older than Socrates",
    valueType: "literal",
    ref: "9.41",
    grc: "κατὰ τὸ τρίτον ἔτος τῆς ἑβδόμης καὶ ἑβδομηκοστῆς Ὀλυμπιάδος",
    certainty: "reported",
    accordingTo: "Thrasylus",
    conflictsWith: ["democritus-birth-ol80"],
  },
  {
    id: "democritus-death-age-109",
    subject: "Democritus",
    property: "deathDate",
    value: "Died at the age of one hundred and nine",
    valueType: "literal",
    ref: "9.43",
    grc: "Τελευτῆσαι δὲ τὸν Δημόκριτόν φησιν Ἕρμιππος τοῦτον τὸν τρόπον",
    certainty: "reported",
    accordingTo: "Hipparchus",
  },
  {
    id: "democritus-death-loaves",
    subject: "Democritus",
    property: "mannerOfDeath",
    value: "Prolonged his life through the Thesmophoria by inhaling the steam of hot loaves, then let his life go without pain",
    valueType: "literal",
    ref: "9.43",
    grc: "κελεῦσαι αὑτῷ προσφέρειν ἄρτους θερμοὺς ὁσημέραι. τούτους δὴ ταῖς ῥισὶ προσφέρων διεκράτησεν αὑτὸν τὴν ἑορτήν· ἐπειδὴ δὲ παρῆλθον αἱ ἡμέραι, τρεῖς δʼ ἦσαν, ἀλυπότατα τὸν βίον προήκατο",
    certainty: "reported",
    accordingTo: "Hermippus",
  },
  {
    id: "democritus-doctrine-atoms",
    subject: "Democritus",
    property: "heldDoctrine",
    value: "The first principles of the universe are atoms and empty space; everything else is merely thought to exist",
    valueType: "doctrine",
    ref: "9.44",
    grc: "ἀρχὰς εἶναι τῶν ὅλων ἀτόμους καὶ κενόν, τὰ δʼ ἄλλα πάντα νενομίσθαι·",
    certainty: "asserted",
    greek: "ἄτομα καὶ κενόν",
  },
  {
    id: "democritus-doctrine-tranquillity",
    subject: "Democritus",
    property: "heldDoctrine",
    value: "The end of action is tranquillity, a state in which the soul continues calm and strong, undisturbed by fear or superstition",
    valueType: "doctrine",
    ref: "9.45",
    grc: "τέλος δʼ εἶναι τὴν εὐθυμίαν, οὐ τὴν αὐτὴν οὖσαν τῇ ἡδονῇ, ὡς ἔνιοι παρακούσαντες ἐξεδέξαντο, ἀλλὰ καθʼ ἣν γαληνῶς καὶ εὐσταθῶς ἡ ψυχὴ διάγει, ὑπὸ μηδενὸς ταραττομένη φόβου ἢ δεισιδαιμονίας ἢ ἄλλου τινὸς πάθους.",
    certainty: "asserted",
    greek: "εὐθυμία",
  },
  {
    id: "democritus-doctrine-necessity",
    subject: "Democritus",
    property: "heldDoctrine",
    value: "All things happen by virtue of necessity, the vortex being the cause of the creation of all things",
    valueType: "doctrine",
    ref: "9.45",
    grc: "Πάντα τε κατʼ ἀνάγκην γίνεσθαι, τῆς δίνης αἰτίας οὔσης τῆς γενέσεως πάντων, ἣν ἀνάγκην λέγει.",
    certainty: "asserted",
  },
  {
    id: "democritus-doctrine-convention",
    subject: "Democritus",
    property: "heldDoctrine",
    value: "The qualities of things exist merely by convention; in nature there is nothing but atoms and void",
    valueType: "doctrine",
    ref: "9.45",
    grc: "ποιότητας δὲ νόμῳ εἶναι, φύσει δʼ ἄτομα καὶ κενόν.",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-pythagoras",
    subject: "Democritus",
    property: "wrote",
    value: "Pythagoras",
    valueType: "work",
    ref: "9.46",
    grc: "Πυθαγόρης",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-disposition-wise",
    subject: "Democritus",
    property: "wrote",
    value: "Of the Disposition of the Wise Man",
    valueType: "work",
    ref: "9.46",
    grc: "Περὶ τῆς τοῦ σοφοῦ διαθέσεως",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-those-in-hades",
    subject: "Democritus",
    property: "wrote",
    value: "Of those in Hades",
    valueType: "work",
    ref: "9.46",
    grc: "Περὶ τῶν ἐν Ἅιδου",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-tritogeneia",
    subject: "Democritus",
    property: "wrote",
    value: "Tritogeneia",
    valueType: "work",
    ref: "9.46",
    grc: "Τριτογένεια ʽτοῦτο δέ ἐστιν, ὅτι τρία γίνεται ἐξ αὐτῆς, ἃ πάντα ἀνθρώπινα συνέχεἰ",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-manly-excellence",
    subject: "Democritus",
    property: "wrote",
    value: "Of Manly Excellence, or Of Virtue",
    valueType: "work",
    ref: "9.46",
    grc: "Περὶ ἀνδραγαθίας ἢ περὶ ἀρετῆς",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-amaltheas-horn",
    subject: "Democritus",
    property: "wrote",
    value: "Amaltheas's Horn (the Horn of Plenty)",
    valueType: "work",
    ref: "9.46",
    grc: "Ἔστι δε ἤθικα μὲν τάδε",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-tranquillity",
    subject: "Democritus",
    property: "wrote",
    value: "Of Tranquillity",
    valueType: "work",
    ref: "9.46",
    grc: "Περὶ εὐθυμίης",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-great-diacosmos",
    subject: "Democritus",
    property: "wrote",
    value: "The Great Diacosmos",
    valueType: "work",
    ref: "9.46",
    grc: "Μέγας διάκοσμος (ὃν οἱ περὶ Θεόφραστον Λευκίππου φασὶν εἶναι)",
    certainty: "asserted",
    note: "The school of Theophrastus attribute it to Leucippus.",
  },
  {
    id: "democritus-wrote-lesser-diacosmos",
    subject: "Democritus",
    property: "wrote",
    value: "The Lesser Diacosmos",
    valueType: "work",
    ref: "9.46",
    grc: "Μικρὸς διάκοσμος",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-description-world",
    subject: "Democritus",
    property: "wrote",
    value: "Description of the World",
    valueType: "work",
    ref: "9.46",
    grc: "Τριτογένεια ʽτοῦτο δέ ἐστιν",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-planets",
    subject: "Democritus",
    property: "wrote",
    value: "On the Planets",
    valueType: "work",
    ref: "9.46",
    grc: "Περὶ τῶν πλανήτων",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-nature",
    subject: "Democritus",
    property: "wrote",
    value: "Of Nature (one book)",
    valueType: "work",
    ref: "9.46",
    grc: "Περὶ φύσεως πρῶτον",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-nature-of-man",
    subject: "Democritus",
    property: "wrote",
    value: "Of the Nature of Man, or Of Flesh",
    valueType: "work",
    ref: "9.46",
    grc: "Περὶ ἀνθρώπου φύσιος (ἢ Περὶ σαρκό̓ς), δεύτερον",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-reason",
    subject: "Democritus",
    property: "wrote",
    value: "Of Reason",
    valueType: "work",
    ref: "9.46",
    grc: "Περὶ ἀνθρώπου φύσιος (ἢ Περὶ σαρκό̓ς)",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-senses",
    subject: "Democritus",
    property: "wrote",
    value: "Of the Senses",
    valueType: "work",
    ref: "9.46",
    grc: "Περὶ νοῦ",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-flavours",
    subject: "Democritus",
    property: "wrote",
    value: "Of Flavours",
    valueType: "work",
    ref: "9.46",
    grc: "Περὶ αἰσθησίων (ταῦτά τινες ὅμου γράφοντες Περὶ ψυχῆς ἐπιγράφουσι)",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-colours",
    subject: "Democritus",
    property: "wrote",
    value: "Of Colours",
    valueType: "work",
    ref: "9.46",
    grc: "Περὶ χυμῶν",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-shapes",
    subject: "Democritus",
    property: "wrote",
    value: "Of the Different Shapes (of Atoms)",
    valueType: "work",
    ref: "9.47",
    grc: "Περὶ τῶν διαφερόντων ῥυσμῶν",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-changes-shape",
    subject: "Democritus",
    property: "wrote",
    value: "Of Changes of Shape",
    valueType: "work",
    ref: "9.47",
    grc: "Περὶ ἀμειψιρυσμιῶν",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-confirmations",
    subject: "Democritus",
    property: "wrote",
    value: "Confirmations",
    valueType: "work",
    ref: "9.47",
    grc: "Κρατυντήρια (ὅπερ ἐστὶν ἐπικριτικὰ τῶν προειρημένων)",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-images",
    subject: "Democritus",
    property: "wrote",
    value: "On Images, or On Foreknowledge of the Future",
    valueType: "work",
    ref: "9.47",
    grc: "Περὶ εἰδώλων ἢ περὶ προνοίας",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-logic",
    subject: "Democritus",
    property: "wrote",
    value: "On Logic, or Criterion of Thought (three books)",
    valueType: "work",
    ref: "9.47",
    grc: "Περὶ λογικῶν ἢ κανὼν α′ β′ γʼ",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-geometry",
    subject: "Democritus",
    property: "wrote",
    value: "On Geometry",
    valueType: "work",
    ref: "9.47",
    grc: "Περὶ γεωμετρίης",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-numbers",
    subject: "Democritus",
    property: "wrote",
    value: "Numbers",
    valueType: "work",
    ref: "9.47",
    grc: "Ἀριθμοί",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-irrational-lines",
    subject: "Democritus",
    property: "wrote",
    value: "On Irrational Lines and Solids (two books)",
    valueType: "work",
    ref: "9.47",
    grc: "Αἰτίαι περὶ ζῴων α′ β′ γʼ",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-great-year",
    subject: "Democritus",
    property: "wrote",
    value: "The Great Year, or Astronomy, Calendar",
    valueType: "work",
    ref: "9.48",
    grc: "Μέγας ἐνιαυτὸς ἢ Ἀστρονομίη, παράπηγμα",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-geography",
    subject: "Democritus",
    property: "wrote",
    value: "Geography",
    valueType: "work",
    ref: "9.48",
    grc: "Μέγας ἐνιαυτὸς ἢ Ἀστρονομίη",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-rhythms-harmony",
    subject: "Democritus",
    property: "wrote",
    value: "On Rhythms and Harmony",
    valueType: "work",
    ref: "9.48",
    grc: "Περὶ ῥυθμῶν καὶ ἁρμονίης",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-poetry",
    subject: "Democritus",
    property: "wrote",
    value: "On Poetry",
    valueType: "work",
    ref: "9.48",
    grc: "Περὶ ποιήσιος",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-homer",
    subject: "Democritus",
    property: "wrote",
    value: "Concerning Homer, or On Correct Epic Diction, and On Glosses",
    valueType: "work",
    ref: "9.48",
    grc: "Ἅμιλλα κλεψύδρας 〈καὶ οὐρανοῦ〉",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-diet",
    subject: "Democritus",
    property: "wrote",
    value: "Of Diet, or Diaetetics",
    valueType: "work",
    ref: "9.48",
    grc: "Περὶ καλλοσύνης ἐπέων",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-agriculture",
    subject: "Democritus",
    property: "wrote",
    value: "Of Agriculture, or Concerning Land Measurements",
    valueType: "work",
    ref: "9.48",
    grc: "Περὶ εὐφώνων καὶ δυσφ〈·〉νων γραμμάτων",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-painting",
    subject: "Democritus",
    property: "wrote",
    value: "Of Painting",
    valueType: "work",
    ref: "9.48",
    grc: "Περὶ Ὁμήρου ἢ ὀρθοεπείης καὶ γλωσσέων",
    certainty: "asserted",
  },
  {
    id: "democritus-wrote-tactics",
    subject: "Democritus",
    property: "wrote",
    value: "Treatise on Tactics, and On Fighting in Armour",
    valueType: "work",
    ref: "9.48",
    grc: "Οὐρανογραφίη",
    certainty: "asserted",
  },

  // ---------------------------------------------------------------- Protagoras
  {
    id: "protagoras-parentage-artemon",
    subject: "Protagoras",
    property: "parentage",
    value: "Son of Artemon, or, according to Apollodorus and Dinon, of Maeandrius",
    valueType: "literal",
    ref: "9.50",
    grc: "Πρωταγόρας Ἀρτέμωνος ἤ, ὡς Ἀπολλόδωρος καὶ Δείνων ἐν Περσικῷ εʼ, Μαιανδρίου Ἀβδηρίτης, καθά φησιν Ἡρακλείδης ὁ Ποντικὸς ἐν τοῖς Περὶ νόμων, ὃς καὶ Θουρίοις νόμους γράψαι φησὶν αὐτόν",
    certainty: "reported",
    accordingTo: "Apollodorus",
  },
  {
    id: "protagoras-birthplace-abdera",
    subject: "Protagoras",
    property: "birthPlace",
    value: "Abdera",
    valueType: "place",
    ref: "9.50",
    grc: "Πρωταγόρας Ἀρτέμωνος ἤ, ὡς Ἀπολλόδωρος καὶ Δείνων ἐν Περσικῷ εʼ, Μαιανδρίου Ἀβδηρίτης, καθά φησιν Ἡρακλείδης ὁ Ποντικὸς ἐν τοῖς Περὶ νόμων, ὃς καὶ Θουρίοις νόμους γράψαι φησὶν αὐτόν",
    certainty: "reported",
    accordingTo: "Heraclides",
    conflictsWith: ["protagoras-birthplace-teos"],
  },
  {
    id: "protagoras-birthplace-teos",
    subject: "Protagoras",
    property: "birthPlace",
    value: "Teos",
    valueType: "place",
    ref: "9.50",
    grc: "Πρωταγόρας Ἀρτέμωνος ἤ, ὡς Ἀπολλόδωρος καὶ Δείνων ἐν Περσικῷ εʼ, Μαιανδρίου Ἀβδηρίτης, καθά φησιν Ἡρακλείδης ὁ Ποντικὸς ἐν τοῖς Περὶ νόμων, ὃς καὶ Θουρίοις νόμους γράψαι φησὶν αὐτόν",
    certainty: "reported",
    note: "So Eupolis in his Flatterers.",
    conflictsWith: ["protagoras-birthplace-abdera"],
  },
  {
    id: "protagoras-studied-democritus",
    subject: "Protagoras",
    property: "studiedUnder",
    value: "Democritus",
    valueType: "philosopher",
    ref: "9.50",
    grc: "Πρωταγόρας Ἀρτέμωνος ἤ, ὡς Ἀπολλόδωρος καὶ Δείνων ἐν Περσικῷ εʼ, Μαιανδρίου Ἀβδηρίτης, καθά φησιν Ἡρακλείδης ὁ Ποντικὸς ἐν τοῖς Περὶ νόμων, ὃς καὶ Θουρίοις νόμους γράψαι φησὶν αὐτόν",
    certainty: "asserted",
  },
  {
    id: "protagoras-affiliated-sophist",
    subject: "Protagoras",
    property: "affiliatedWith",
    value: "Eleatics, Atomists, Sceptics",
    valueType: "school",
    ref: "9.50",
    grc: "Πρωταγόρας Ἀρτέμωνος ἤ, ὡς Ἀπολλόδωρος καὶ Δείνων ἐν Περσικῷ εʼ, Μαιανδρίου Ἀβδηρίτης, καθά φησιν Ἡρακλείδης ὁ Ποντικὸς ἐν τοῖς Περὶ νόμων, ὃς καὶ Θουρίοις νόμους γράψαι φησὶν αὐτόν",
    certainty: "asserted",
  },
  {
    id: "protagoras-doctrine-measure",
    subject: "Protagoras",
    property: "heldDoctrine",
    value: "Man is the measure of all things, of things that are that they are, and of things that are not that they are not",
    valueType: "doctrine",
    ref: "9.51",
    grc: "πάντων χρημάτων μέτρον ἄνθρωπος, τῶν μὲν ὄντων ὡς ἔστιν, τῶν δὲ οὐκ ὄντων ὡς οὐκ ἔστιν.",
    certainty: "asserted",
    greek: "πάντων χρημάτων μέτρον ἄνθρωπος",
  },
  {
    id: "protagoras-doctrine-two-sides",
    subject: "Protagoras",
    property: "heldDoctrine",
    value: "There are two sides to every question, opposed to each other",
    valueType: "doctrine",
    ref: "9.51",
    grc: "Καὶ πρῶτος ἔφη δύο λόγους εἶναι περὶ παντὸς πράγματος ἀντικειμένους ἀλλήλοις·",
    certainty: "asserted",
  },
  {
    id: "protagoras-doctrine-gods",
    subject: "Protagoras",
    property: "heldDoctrine",
    value: "As to the gods, I have no means of knowing either that they exist or that they do not exist",
    valueType: "doctrine",
    ref: "9.51",
    grc: "περὶ μὲν θεῶν οὐκ ἔχω εἰδέναι οὔθʼ ὡς εἰσίν, οὔθʼ ὡς οὐκ εἰσίν·",
    certainty: "asserted",
  },
  {
    id: "protagoras-death-shipwreck",
    subject: "Protagoras",
    property: "mannerOfDeath",
    value: "On a voyage to Sicily his ship went down",
    valueType: "literal",
    ref: "9.55",
    grc: "Φησὶ δὲ Φιλόχορος, πλέοντος αὐτοῦ ἐς Σικελίαν, τὴν ναῦν καταποντωθῆναι",
    certainty: "reported",
    accordingTo: "Philochorus",
    conflictsWith: ["protagoras-death-journey"],
  },
  {
    id: "protagoras-death-journey",
    subject: "Protagoras",
    property: "mannerOfDeath",
    value: "Died on a journey at nearly ninety years of age",
    valueType: "literal",
    ref: "9.56",
    grc: "καὶ σεῦ, Πρωταγόρη, φάτιν ἔκλυον, ὡς ἄρʼ Ἀθηνέων ἔκ ποτʼ ἰὼν καθʼ ὁδὸν πρέσβυς ἐὼν ἔθανες",
    certainty: "reported",
    conflictsWith: ["protagoras-death-shipwreck"],
  },
  {
    id: "protagoras-death-age",
    subject: "Protagoras",
    property: "deathDate",
    value: "Died at seventy, with a career of forty years as a sophist; floruit in the 84th Olympiad (444/441 BCE)",
    valueType: "literal",
    ref: "9.56",
    grc: "Ἀπολλόδωρος δέ φησιν ἑβδομήκοντα, σοφιστεῦσαι δὲ τεσσαράκοντα καὶ ἀκμάζειν κατὰ τὴν τετάρτην καὶ ὀγδοηκοστὴν Ὀλυμπιάδα",
    certainty: "reported",
    accordingTo: "Apollodorus",
  },
  {
    id: "protagoras-wrote-gods",
    subject: "Protagoras",
    property: "wrote",
    value: "On the Gods",
    valueType: "work",
    ref: "9.54",
    grc: "Πρῶτον δὲ τῶν λόγων ἑαυτοῦ ἀνέγνω τὸν Περὶ θεῶν, οὗ τὴν ἀρχὴν ἄνω παρεθέμεθα",
    certainty: "asserted",
    note: "The book for which the Athenians expelled him and burnt his works.",
  },
  {
    id: "protagoras-wrote-controversy",
    subject: "Protagoras",
    property: "wrote",
    value: "The Art of Controversy",
    valueType: "work",
    ref: "9.55",
    grc: "Ἔστι δὲ τὰ σωζόμενα αὐτοῦ βιβλία τάδε",
    certainty: "asserted",
  },
  {
    id: "protagoras-wrote-state",
    subject: "Protagoras",
    property: "wrote",
    value: "Of the State",
    valueType: "work",
    ref: "9.55",
    grc: "Περὶ πάλης",
    certainty: "asserted",
  },
  {
    id: "protagoras-wrote-virtues",
    subject: "Protagoras",
    property: "wrote",
    value: "Of Virtues",
    valueType: "work",
    ref: "9.55",
    grc: "Περὶ ἀρετῶν",
    certainty: "asserted",
  },
  {
    id: "protagoras-wrote-hades",
    subject: "Protagoras",
    property: "wrote",
    value: "On the Dwellers in Hades",
    valueType: "work",
    ref: "9.55",
    grc: "Περὶ τῶν μαθημάτων",
    certainty: "asserted",
  },
  {
    id: "protagoras-wrote-forensic",
    subject: "Protagoras",
    property: "wrote",
    value: "Of Forensic Speech for a Fee",
    valueType: "work",
    ref: "9.55",
    grc: "Περὶ πολιτείας",
    certainty: "asserted",
  },

  // ---------------------------------------------------- Diogenes of Apollonia
  {
    id: "diogenes-apollonia-parentage-apollothemis",
    subject: "Diogenes of Apollonia",
    property: "parentage",
    value: "Son of Apollothemis",
    valueType: "literal",
    ref: "9.57",
    grc: "Διογένης Ἀπολλοθέμιδος Ἀπολλωνιάτης, ἀνὴρ φυσικὸς καὶ ἄγαν ἐλλόγιμος",
    certainty: "asserted",
  },
  {
    id: "diogenes-apollonia-studied-anaximenes",
    subject: "Diogenes of Apollonia",
    property: "studiedUnder",
    value: "Anaximenes",
    valueType: "philosopher",
    ref: "9.57",
    grc: "ἤκουσε δέ, φησὶν Ἀντισθένης, Ἀναξιμένους",
    certainty: "reported",
    accordingTo: "Antisthenes",
  },
  {
    id: "diogenes-apollonia-lived-athens",
    subject: "Diogenes of Apollonia",
    property: "livedIn",
    value: "Athens",
    valueType: "place",
    ref: "9.57",
    grc: "Διογένης Ἀπολλοθέμιδος Ἀπολλωνιάτης, ἀνὴρ φυσικὸς καὶ ἄγαν ἐλλόγιμος",
    certainty: "asserted",
    note: "So great was his unpopularity there that he almost lost his life.",
  },
  {
    id: "diogenes-apollonia-doctrine-air",
    subject: "Diogenes of Apollonia",
    property: "heldDoctrine",
    value: "Air is the universal element; by condensation and rarefaction it generates the worlds",
    valueType: "doctrine",
    ref: "9.57",
    grc: "στοιχεῖον εἶναι τὸν ἀέρα, κόσμους ἀπείρους καὶ κενὸν ἄπειρον· τόν τε ἀέρα πυκνούμενον καὶ ἀραιούμενον γεννητικὸν εἶναι τῶν κόσμων·",
    certainty: "asserted",
    greek: "ἀήρ",
  },
  {
    id: "diogenes-apollonia-doctrine-worlds",
    subject: "Diogenes of Apollonia",
    property: "heldDoctrine",
    value: "There are worlds unlimited in number and unlimited empty space; nothing comes into being from what is not",
    valueType: "doctrine",
    ref: "9.57",
    grc: "κόσμους ἀπείρους καὶ κενὸν ἄπειρον· τόν τε ἀέρα πυκνούμενον καὶ ἀραιούμενον γεννητικὸν εἶναι τῶν κόσμων· οὐδὲν ἐκ τοῦ μὴ ὄντος γίνεσθαι οὐδʼ εἰς τὸ μὴ ὂν φθείρεσθαι·",
    certainty: "asserted",
  },

  // ---------------------------------------------------------------- Anaxarchus
  {
    id: "anaxarchus-birthplace-abdera",
    subject: "Anaxarchus",
    property: "birthPlace",
    value: "Abdera",
    valueType: "place",
    ref: "9.58",
    grc: "Ἀνάξαρχος Ἀβδηρίτης",
    certainty: "asserted",
  },
  {
    id: "anaxarchus-studied-diogenes-smyrna",
    subject: "Anaxarchus",
    property: "studiedUnder",
    value: "Diogenes of Smyrna",
    valueType: "person",
    ref: "9.58",
    grc: "οὗτος ἤκουσε Διογένους τοῦ Σμυρναίου",
    certainty: "asserted",
  },
  {
    id: "anaxarchus-affiliated-atomist",
    subject: "Anaxarchus",
    property: "affiliatedWith",
    value: "Eleatics, Atomists, Sceptics",
    valueType: "school",
    ref: "9.58",
    grc: "Ἀνάξαρχος Ἀβδηρίτης",
    certainty: "asserted",
  },
  {
    id: "anaxarchus-floruit",
    subject: "Anaxarchus",
    property: "birthDate",
    value: "Flourished in the 110th Olympiad (340/337 BCE)",
    valueType: "literal",
    ref: "9.58",
    grc: "ὁ δʼ οὖν Ἀνάξαρχος καὶ Ἀλεξάνδρῳ συνῆν καὶ ἤκμαζε κατὰ τὴν δεκάτην καὶ ἑκατοστὴν Ὀλυμπιάδα καὶ εἶχεν ἐχθρὸν Νικοκρέοντα τὸν Κύπρου τύραννον",
    certainty: "asserted",
    note: "Accompanied Alexander.",
  },
  {
    id: "anaxarchus-death-mortar",
    subject: "Anaxarchus",
    property: "mannerOfDeath",
    value: "Seized by Nicocreon of Cyprus, put in a mortar and pounded to death with iron pestles; bit off his tongue and spat it at the tyrant",
    valueType: "literal",
    ref: "9.59",
    grc: "συλλαβὼν αὐτὸν καὶ εἰς ὅλμον βαλὼν ἐκέλευσε τύπτεσθαι σιδηροῖς ὑπέροις.",
    certainty: "asserted",
  },
  {
    id: "anaxarchus-doctrine-contentment",
    subject: "Anaxarchus",
    property: "heldDoctrine",
    value: "Fortitude and contentment in life, for which he was called the Happy Man",
    valueType: "doctrine",
    ref: "9.60",
    grc: "Οὗτος διὰ τὴν ἀπάθειαν καὶ εὐκολίαν τοῦ βίου Εὐδαιμονικὸς ἐκαλεῖτο· καὶ ἦν ἐκ τοῦ ῥᾴστου δυνατὸς σωφρονίζειν.",
    certainty: "asserted",
    greek: "εὐδαιμονικός",
  },

  // ---------------------------------------------------------------- Pyrrho
  {
    id: "pyrrho-parentage-pleistarchus",
    subject: "Pyrrho",
    property: "parentage",
    value: "Son of Pleistarchus",
    valueType: "literal",
    ref: "9.61",
    grc: "Πύρρων Ἠλεῖος Πλειστάρχου μὲν ἦν υἱός, καθὰ καὶ Διοκλῆς ἱστορεῖ",
    certainty: "reported",
    accordingTo: "Diocles",
  },
  {
    id: "pyrrho-birthplace-elis",
    subject: "Pyrrho",
    property: "birthPlace",
    value: "Elis",
    valueType: "place",
    ref: "9.61",
    grc: "Πύρρων Ἠλεῖος Πλειστάρχου μὲν ἦν υἱός, καθὰ καὶ Διοκλῆς ἱστορεῖ",
    certainty: "asserted",
  },
  {
    id: "pyrrho-education-painter",
    subject: "Pyrrho",
    property: "education",
    value: "First a painter",
    valueType: "literal",
    ref: "9.61",
    grc: "ὥς φησι δʼ Ἀπολλόδωρος ἐν Χρονικοῖς, πρότερον ἦν ζωγράφος, καὶ ἤκουσε Βρύσωνος τοῦ Στίλπωνος, ὡς Ἀλέξανδρος ἐν Διαδοχαῖς, εἶτʼ Ἀναξάρχου, ξυνακολουθῶν πανταχοῦ, ὡς καὶ τοῖς Γυμνοσοφισταῖς ἐν Ἰνδίᾳ συμμίξαι καὶ τοῖς Μάγοις. ὅθεν γενναιότατα δοκεῖ φιλοσοφῆσαι, τὸ τῆς ἀκαταληψίας καὶ ἐποχῆς εἶδος εἰσαγαγών, ὡς Ἀσκάνιος ὁ Ἀβδηρίτης φησίν",
    certainty: "reported",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
  },
  {
    id: "pyrrho-studied-bryson",
    subject: "Pyrrho",
    property: "studiedUnder",
    value: "Bryson",
    valueType: "person",
    ref: "9.61",
    grc: "ὥς φησι δʼ Ἀπολλόδωρος ἐν Χρονικοῖς, πρότερον ἦν ζωγράφος, καὶ ἤκουσε Βρύσωνος τοῦ Στίλπωνος, ὡς Ἀλέξανδρος ἐν Διαδοχαῖς, εἶτʼ Ἀναξάρχου, ξυνακολουθῶν πανταχοῦ, ὡς καὶ τοῖς Γυμνοσοφισταῖς ἐν Ἰνδίᾳ συμμίξαι καὶ τοῖς Μάγοις",
    certainty: "reported",
    accordingTo: "Alexander",
    note: "Bryson, son of Stilpo.",
  },
  {
    id: "pyrrho-studied-anaxarchus",
    subject: "Pyrrho",
    property: "studiedUnder",
    value: "Anaxarchus",
    valueType: "philosopher",
    ref: "9.61",
    grc: "ὥς φησι δʼ Ἀπολλόδωρος ἐν Χρονικοῖς, πρότερον ἦν ζωγράφος, καὶ ἤκουσε Βρύσωνος τοῦ Στίλπωνος, ὡς Ἀλέξανδρος ἐν Διαδοχαῖς, εἶτʼ Ἀναξάρχου, ξυνακολουθῶν πανταχοῦ, ὡς καὶ τοῖς Γυμνοσοφισταῖς ἐν Ἰνδίᾳ συμμίξαι καὶ τοῖς Μάγοις",
    certainty: "asserted",
    note: "Whom he accompanied everywhere, even to the Indian Gymnosophists and the Magi.",
  },
  {
    id: "pyrrho-affiliated-sceptic",
    subject: "Pyrrho",
    property: "affiliatedWith",
    value: "Eleatics, Atomists, Sceptics",
    valueType: "school",
    ref: "9.61",
    grc: "Πύρρων Ἠλεῖος Πλειστάρχου μὲν ἦν υἱός, καθὰ καὶ Διοκλῆς ἱστορεῖ",
    certainty: "asserted",
    note: "Founder of the school; his followers called Pyrrhoneans, Sceptics, Ephectics, Zetetics.",
  },
  {
    id: "pyrrho-writings-none",
    subject: "Pyrrho",
    property: "writings",
    value: "Left no writings",
    valueType: "literal",
    ref: "9.102",
    grc: "Ἔστι δὲ καὶ τὸν ὅλον τῆς συναγωγῆς αὐτῶν τρόπον συνιδεῖν ἐκ τῶν ἀπολειφθεισῶν συντάξεων",
    certainty: "asserted",
    note: "His associates Timon, Aenesidemus, Numenius and Nausiphanes did write.",
  },
  {
    id: "pyrrho-death-age",
    subject: "Pyrrho",
    property: "deathDate",
    value: "Lived to be nearly ninety",
    valueType: "literal",
    ref: "9.62",
    grc: "Ἀκόλουθος δʼ ἦν καὶ τῷ βίῳ, μηδὲν ἐκτρεπόμενος μηδὲ φυλαττόμενος, ἅπαντα ὑφιστάμενος, ἁμάξας, εἰ τύχοι, καὶ κρημνοὺς καὶ κύνας καὶ ὅλως μηδὲν ταῖς αἰσθήσεσιν ἐπιτρέπων",
    certainty: "asserted",
  },
  {
    id: "pyrrho-doctrine-epoche",
    subject: "Pyrrho",
    property: "heldDoctrine",
    value: "Agnosticism and suspension of judgement; nothing is honourable or base, just or unjust by nature",
    valueType: "doctrine",
    ref: "9.61",
    grc: "ὅθεν γενναιότατα δοκεῖ φιλοσοφῆσαι, τὸ τῆς ἀκαταληψίας καὶ ἐποχῆς εἶδος εἰσαγαγών, ὡς Ἀσκάνιος ὁ Ἀβδηρίτης φησίν· οὐδὲν γὰρ ἔφασκεν οὔτε καλὸν οὔτʼ αἰσχρὸν οὔτε δίκαιον οὔτʼ ἄδικον·",
    certainty: "asserted",
    greek: "ἐποχή",
  },
  {
    id: "pyrrho-doctrine-ou-mallon",
    subject: "Pyrrho",
    property: "heldDoctrine",
    value: "No single thing is in itself any more this than that",
    valueType: "doctrine",
    ref: "9.61",
    grc: "οὐ γὰρ μᾶλλον τόδε ἢ τόδε εἶναι ἕκαστον.",
    certainty: "asserted",
    greek: "οὐ μᾶλλον",
  },
  {
    id: "pyrrho-doctrine-ataraxia",
    subject: "Pyrrho",
    property: "heldDoctrine",
    value: "The end to be realized is suspension of judgement, which brings tranquillity in its train",
    valueType: "doctrine",
    ref: "9.107",
    grc: "τέλος δὲ οἱ σκεπτικοί φασι τὴν ἐποχήν, ᾗ σκιᾶς τρόπον ἐπακολουθεῖ ἡ ἀταραξία, ὥς φασιν οἵ τε περὶ τὸν Τίμωνα καὶ Αἰνεσίδημον·",
    certainty: "asserted",
    greek: "ἀταραξία",
  },
  {
    id: "pyrrho-doctrine-modes",
    subject: "Pyrrho",
    property: "heldDoctrine",
    value: "The ten modes (tropes) of perplexity, by which the equal validity of opposing appearances leads to suspension of judgement",
    valueType: "doctrine",
    ref: "9.79",
    grc: "Αἱ δʼ ἀπορίαι κατὰ τὰς συμφωνίας τῶν φαινομένων ἢ νοουμένων, ἃς ἀπεδίδοσαν, ἦσαν κατὰ δέκα τρόπους, καθʼ οὓς τὰ ὑποκείμενα παραλλάττοντα ἐφαίνετο.",
    certainty: "asserted",
  },
  {
    id: "pyrrho-praised-democritus",
    subject: "Pyrrho",
    property: "praised",
    value: "Democritus",
    valueType: "philosopher",
    ref: "9.67",
    grc: "ἀλλὰ καὶ Φίλων ὁ Ἀθηναῖος, γνώριμος αὐτοῦ γεγονώς, ἔλεγεν ὡς ἐμέμνητο μάλιστα μὲν Δημοκρίτου, εἶτα δὲ καὶ Ὁμήρου, θαυμάζων αὐτὸν καὶ συνεχὲς λέγων",
    certainty: "reported",
    accordingTo: "Philo of Athens",
    note: "He was most fond of Democritus, and then of Homer.",
  },

  // ---------------------------------------------------------------- Timon
  {
    id: "timon-parentage-timarchus",
    subject: "Timon",
    property: "parentage",
    value: "Son of Timarchus",
    valueType: "literal",
    ref: "9.109",
    grc: "Ἀπολλωνίδης ὁ Νικαεὺς ὁ παρʼ ἡμῶν ἐν τῷ πρώτῳ τῶν Εἰς τοὺς Σίλλους ὑπομνήματι, ἃ προσφωνεῖ Τιβερίῳ Καίσαρι, φησὶ τὸν Τίμωνα εἶναι πατρὸς μὲν Τιμάρχου, Φλιάσιον δὲ τὸ γένος",
    certainty: "reported",
    accordingTo: "Apollonides",
  },
  {
    id: "timon-birthplace-phlius",
    subject: "Timon",
    property: "birthPlace",
    value: "Phlius",
    valueType: "place",
    ref: "9.109",
    grc: "Ἀπολλωνίδης ὁ Νικαεὺς ὁ παρʼ ἡμῶν ἐν τῷ πρώτῳ τῶν Εἰς τοὺς Σίλλους ὑπομνήματι, ἃ προσφωνεῖ Τιβερίῳ Καίσαρι, φησὶ τὸν Τίμωνα εἶναι πατρὸς μὲν Τιμάρχου, Φλιάσιον δὲ τὸ γένος",
    certainty: "asserted",
  },
  {
    id: "timon-education-dancer",
    subject: "Timon",
    property: "education",
    value: "First a stage-dancer, but later took a dislike to that pursuit",
    valueType: "literal",
    ref: "9.109",
    grc: "Ἀπολλωνίδης ὁ Νικαεὺς ὁ παρʼ ἡμῶν ἐν τῷ πρώτῳ τῶν Εἰς τοὺς Σίλλους ὑπομνήματι, ἃ προσφωνεῖ Τιβερίῳ Καίσαρι, φησὶ τὸν Τίμωνα εἶναι πατρὸς μὲν Τιμάρχου, Φλιάσιον δὲ τὸ γένος",
    certainty: "asserted",
  },
  {
    id: "timon-studied-stilpo",
    subject: "Timon",
    property: "studiedUnder",
    value: "Stilpo",
    valueType: "philosopher",
    ref: "9.109",
    grc: "Ἀπολλωνίδης ὁ Νικαεὺς ὁ παρʼ ἡμῶν ἐν τῷ πρώτῳ τῶν Εἰς τοὺς Σίλλους ὑπομνήματι, ἃ προσφωνεῖ Τιβερίῳ Καίσαρι, φησὶ τὸν Τίμωνα εἶναι πατρὸς μὲν Τιμάρχου, Φλιάσιον δὲ τὸ γένος",
    certainty: "asserted",
    note: "Went to Megara to stay with Stilpo.",
  },
  {
    id: "timon-studied-pyrrho",
    subject: "Timon",
    property: "studiedUnder",
    value: "Pyrrho",
    valueType: "philosopher",
    ref: "9.109",
    grc: "Ἀπολλωνίδης ὁ Νικαεὺς ὁ παρʼ ἡμῶν ἐν τῷ πρώτῳ τῶν Εἰς τοὺς Σίλλους ὑπομνήματι, ἃ προσφωνεῖ Τιβερίῳ Καίσαρι, φησὶ τὸν Τίμωνα εἶναι πατρὸς μὲν Τιμάρχου, Φλιάσιον δὲ τὸ γένος",
    certainty: "asserted",
  },
  {
    id: "timon-affiliated-sceptic",
    subject: "Timon",
    property: "affiliatedWith",
    value: "Eleatics, Atomists, Sceptics",
    valueType: "school",
    ref: "9.109",
    grc: "Ἀπολλωνίδης ὁ Νικαεὺς ὁ παρʼ ἡμῶν ἐν τῷ πρώτῳ τῶν Εἰς τοὺς Σίλλους ὑπομνήματι, ἃ προσφωνεῖ Τιβερίῳ Καίσαρι, φησὶ τὸν Τίμωνα εἶναι πατρὸς μὲν Τιμάρχου, Φλιάσιον δὲ τὸ γένος",
    certainty: "asserted",
  },
  {
    id: "timon-lived-athens",
    subject: "Timon",
    property: "livedIn",
    value: "Athens",
    valueType: "place",
    ref: "9.110",
    grc: "ἐντεῦθέν τε πορισάμενος ἀπῆρεν εἰς Ἀθήνας, κἀκεῖ διέτριβε μέχρι καὶ τελευτῆς, ὀλίγον χρόνον εἰς Θήβας διαδραμών",
    certainty: "asserted",
    note: "Lived there until his death, except a short period at Thebes.",
  },
  {
    id: "timon-death-age",
    subject: "Timon",
    property: "deathDate",
    value: "Died at the age of nearly ninety",
    valueType: "literal",
    ref: "9.112",
    grc: "τὸ δὲ πρῶτον ταὐτὰ περιέχει πράγματα, πλὴν ὅτι μονοπρόσωπός ἐστιν ἡ ποίησις",
    certainty: "reported",
    accordingTo: "Antigonus",
  },
  {
    id: "timon-wrote-silli",
    subject: "Timon",
    property: "wrote",
    value: "Silli (lampoons, in three books)",
    valueType: "work",
    ref: "9.111",
    grc: "τῶν δὲ σίλλων τρία ἐστίν,",
    certainty: "asserted",
    note: "Parodies in which Xenophanes answers his questions about each philosopher.",
  },
  {
    id: "timon-wrote-pytho",
    subject: "Timon",
    property: "wrote",
    value: "Pytho",
    valueType: "work",
    ref: "9.76",
    grc: "καθά φησι καὶ Τίμων ἐν τῷ Πύθωνι,",
    certainty: "asserted",
  },
  {
    id: "timon-wrote-conceits",
    subject: "Timon",
    property: "wrote",
    value: "The Conceits",
    valueType: "work",
    ref: "9.105",
    grc: "καὶ ὅτι κινεῖταί τις βλέπομεν, καὶ ὅτι φθείρεται πῶς δὲ ταῦτα γίνεται οὐκ ἴσμεν",
    certainty: "asserted",
  },
  {
    id: "timon-wrote-senses",
    subject: "Timon",
    property: "wrote",
    value: "On the Senses",
    valueType: "work",
    ref: "9.105",
    grc: "καὶ ἐν τοῖς Περὶ αἰσθήσεών φησι,",
    certainty: "asserted",
  },
  {
    id: "timon-wrote-funeral-banquet",
    subject: "Timon",
    property: "wrote",
    value: "Funeral Banquet of Arcesilaus",
    valueType: "work",
    ref: "9.115",
    grc: "ἐρωτηθεὶς δέ ποθʼ ὑπὸ τοῦ Ἀρκεσιλάου διὰ τί παρείη ἐκ Θηβῶν, ἔφη, ἵνʼ ὑμᾶς ἀναπεπταμένους ὁρῶν γελῶ",
    certainty: "asserted",
  },
  {
    id: "timon-doctrine-apparent",
    subject: "Timon",
    property: "heldDoctrine",
    value: "The apparent is omnipotent wherever it goes; I do not lay it down that honey is sweet, but I admit that it appears so",
    valueType: "doctrine",
    ref: "9.105",
    grc: "ἀλλὰ τὸ φαινόμενον πάντη σθένει οὗπερ ἂν ἔλθῃ. καὶ ἐν τοῖς Περὶ αἰσθήσεών φησι, τὸ μέλι ὅτι ἐστὶ γλυκὺ οὐ τίθημι, τὸ δʼ ὅτι φαίνεται ὁμολογῶ.",
    certainty: "asserted",
  },
  // The disputed succession of Timon (9.115). D.L. sets Menodotus'
  // no-successor report against the pupil list of Hippobotus and
  // Sotion ("however"). One claim per named authority - a combined
  // "Hippobotus and Sotion" string would mint a bogus conflated
  // source node. The Menodotus here is the empiric of Nicomedia who
  // closes the same succession at 9.116 - the standard identification
  // (an insider writing the school's history in the very passage
  // where he himself appears), not a guessed homonym: D.L. names no
  // other Menodotus. The pupils themselves get hedged teacher links
  // in succession-links.ts.
  {
    id: "timon-no-successor",
    subject: "Timon",
    property: "succession",
    value:
      "Left no successor; his school lapsed until Ptolemy of Cyrene re-established it",
    valueType: "literal",
    ref: "9.115",
    grc: "ἐρωτηθεὶς δέ ποθʼ ὑπὸ τοῦ Ἀρκεσιλάου διὰ τί παρείη ἐκ Θηβῶν, ἔφη, ἵνʼ ὑμᾶς ἀναπεπταμένους ὁρῶν γελῶ",
    certainty: "reported",
    accordingTo: "Menodotus of Nicomedia",
    conflictsWith: ["timon-pupils-hippobotus", "timon-pupils-sotion"],
  },
  {
    id: "timon-pupils-hippobotus",
    subject: "Timon",
    property: "succession",
    value:
      "Had as pupils Dioscurides of Cyprus, Nicolochus of Rhodes, Euphranor of Seleucia, and Praÿlus of the Troad",
    valueType: "literal",
    ref: "9.115",
    grc: "ἐρωτηθεὶς δέ ποθʼ ὑπὸ τοῦ Ἀρκεσιλάου διὰ τί παρείη ἐκ Θηβῶν, ἔφη, ἵνʼ ὑμᾶς ἀναπεπταμένους ὁρῶν γελῶ",
    certainty: "reported",
    accordingTo: "Hippobotus",
    conflictsWith: ["timon-no-successor"],
  },
  {
    id: "timon-pupils-sotion",
    subject: "Timon",
    property: "succession",
    value:
      "Had as pupils Dioscurides of Cyprus, Nicolochus of Rhodes, Euphranor of Seleucia, and Praÿlus of the Troad",
    valueType: "literal",
    ref: "9.115",
    grc: "ἐρωτηθεὶς δέ ποθʼ ὑπὸ τοῦ Ἀρκεσιλάου διὰ τί παρείη ἐκ Θηβῶν, ἔφη, ἵνʼ ὑμᾶς ἀναπεπταμένους ὁρῶν γελῶ",
    certainty: "reported",
    accordingTo: "Sotion",
    conflictsWith: ["timon-no-successor"],
  },
];
