/**
 * Curated claims from Book 2 of Diogenes Laertius' Lives, cited to
 * Hicks section ids (book.section). See kg-claims.ts for the model and
 * curation rules. Source-internal: every claim cites a D.L. passage.
 */
import type { KgClaim } from "../kg-claims";

export const BOOK2_CLAIMS: KgClaim[] = [
  // ------------------------------------------------------------ Anaximander
  {
    id: "anaximander-parentage",
    subject: "Anaximander",
    property: "parentage",
    value: "Son of Praxiades",
    valueType: "literal",
    ref: "2.1",
    grc: "Ἀναξίμανδρος Πραξιάδου Μιλήσιος",
    certainty: "asserted",
  },
  {
    id: "anaximander-birthplace-miletus",
    subject: "Anaximander",
    property: "birthPlace",
    value: "Miletus",
    valueType: "place",
    ref: "2.1",
    grc: "Ἀναξίμανδρος Πραξιάδου Μιλήσιος",
    certainty: "asserted",
  },
  {
    id: "anaximander-doctrine-apeiron",
    subject: "Anaximander",
    property: "heldDoctrine",
    value: "The first principle and element is the unlimited, not defined as air or water or anything else",
    valueType: "doctrine",
    greek: "ἄπειρον",
    ref: "2.1",
    grc: "οὗτος ἔφασκεν ἀρχὴν καὶ στοιχεῖον τὸ ἄπειρον, οὐ διορίζων ἀέρα ἢ ὕδωρ ἢ ἄλλο τι.",
    certainty: "asserted",
  },
  {
    id: "anaximander-doctrine-earth-centre",
    subject: "Anaximander",
    property: "heldDoctrine",
    value: "The earth is spherical and lies in the midst, occupying the place of a centre",
    valueType: "doctrine",
    ref: "2.1",
    grc: "μέσην τε τὴν γῆν κεῖσθαι, κέντρου τάξιν ἐπέχουσαν οὖσαν σφαιροειδῆ·",
    certainty: "asserted",
  },
  {
    id: "anaximander-flourished",
    subject: "Anaximander",
    property: "birthDate",
    value: "Was sixty-four in the second year of the 58th Olympiad (547/546 BCE), and died not long afterwards",
    valueType: "literal",
    ref: "2.2",
    grc: "ὃς καί φησιν αὐτὸν ἐν τοῖς Χρονικοῖς τῷ δευτέρῳ ἔτει τῆς πεντηκοστῆς ὀγδόης Ὀλυμπιάδος ἐτῶν εἶναι ἑξήκοντα τεττάρων καὶ μετʼ ὀλίγον τελευτῆσαι, ἀκμάσαντά πη μάλιστα κατὰ Πολυκράτην τὸν Σάμου τύραννον",
    certainty: "reported",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
  },
  // ------------------------------------------------------------ Anaximenes
  {
    id: "anaximenes-parentage",
    subject: "Anaximenes",
    property: "parentage",
    value: "Son of Eurystratus, a native of Miletus",
    valueType: "literal",
    ref: "2.3",
    grc: "Γεγόνασι δὲ καὶ ἄλλοι δύο Λαμψακηνοί, ῥήτωρ καὶ ἱστορικός, ὃς ἀδελφῆς υἱὸς ἦν τοῦ ῥήτορος τοῦ τὰς Ἀλεξάνδρου πράξεις γεγραφότος",
    certainty: "asserted",
  },
  {
    id: "anaximenes-birthplace-miletus",
    subject: "Anaximenes",
    property: "birthPlace",
    value: "Miletus",
    valueType: "place",
    ref: "2.3",
    grc: "Ἀναξιμένης Εὐρυστράτου Μιλήσιος ἤκουσεν Ἀναξιμάνδρου",
    certainty: "asserted",
  },
  {
    id: "anaximenes-teacher-anaximander",
    subject: "Anaximenes",
    property: "studiedUnder",
    value: "Anaximander",
    valueType: "philosopher",
    ref: "2.3",
    grc: "Ἀναξιμένης Εὐρυστράτου Μιλήσιος ἤκουσεν Ἀναξιμάνδρου",
    certainty: "asserted",
    conflictsWith: ["anaximenes-teacher-parmenides"],
  },
  {
    id: "anaximenes-teacher-parmenides",
    subject: "Anaximenes",
    property: "studiedUnder",
    value: "Parmenides",
    valueType: "philosopher",
    ref: "2.3",
    grc: "Ἀναξιμένης Εὐρυστράτου Μιλήσιος ἤκουσεν Ἀναξιμάνδρου",
    certainty: "reported",
    note: "According to some, he was also a pupil of Parmenides.",
    conflictsWith: ["anaximenes-teacher-anaximander"],
  },
  {
    id: "anaximenes-doctrine-air",
    subject: "Anaximenes",
    property: "heldDoctrine",
    value: "His first principle is air, or that which is unlimited",
    valueType: "doctrine",
    greek: "ἀήρ",
    ref: "2.3",
    grc: "οὗτος ἀρχὴν ἀέρα εἶπε καὶ τὸ ἄπειρον.",
    certainty: "asserted",
  },
  {
    id: "anaximenes-death-ol63",
    subject: "Anaximenes",
    property: "deathDate",
    value: "Died in the 63rd Olympiad (528/525 BCE), about the taking of Sardis",
    valueType: "literal",
    ref: "2.3",
    grc: "Καὶ γεγένηται μέν, καθά φησιν Ἀπολλόδωρος, περὶ τὴν Σάρδεων ἅλωσιν, ἐτελεύτησε δὲ τῇ ἑξηκοστῇ τρίτῃ Ὀλυμπιάδι",
    certainty: "reported",
    accordingTo: "Apollodorus",
  },
  // ------------------------------------------------------------ Anaxagoras
  {
    id: "anaxagoras-parentage",
    subject: "Anaxagoras",
    property: "parentage",
    value: "Son of Hegesibulus or Eubulus, a native of Clazomenae",
    valueType: "literal",
    ref: "2.6",
    grc: "Οὗτος εὐγενείᾳ καὶ πλούτῳ διαφέρων ἦν, ἀλλὰ καὶ μεγαλοφροσύνῃ, ὅς γε τὰ πατρῷα παρεχώρησε τοῖς οἰκείοις.",
    certainty: "asserted",
  },
  {
    id: "anaxagoras-birthplace-clazomenae",
    subject: "Anaxagoras",
    property: "birthPlace",
    value: "Clazomenae",
    valueType: "place",
    ref: "2.6",
    grc: "Ἀναξαγόρας Ἡγησιβούλου ἢ Εὐβούλου Κλαζομένιος",
    certainty: "asserted",
  },
  {
    id: "anaxagoras-teacher-anaximenes",
    subject: "Anaxagoras",
    property: "studiedUnder",
    value: "Anaximenes",
    valueType: "philosopher",
    ref: "2.6",
    grc: "οὗτος ἤκουσεν Ἀναξιμένους, καὶ πρῶτος τῇ ὕλῃ νοῦν ἐπέστησεν, ἀρξάμενος οὕτω τοῦ συγγράμματος, ὅ ἐστιν ἡδέως καὶ μεγαλοφρόνως ἡρμηνευμένον",
    certainty: "asserted",
  },
  {
    id: "anaxagoras-doctrine-nous",
    subject: "Anaxagoras",
    property: "heldDoctrine",
    value: "All things were together; then came Mind and set them in order",
    valueType: "doctrine",
    greek: "νοῦς",
    ref: "2.6",
    grc: "πάντα χρήματα ἦν ὁμοῦ· εἶτα νοῦς ἐλθὼν αὐτὰ διεκόσμησε.",
    certainty: "asserted",
    note: "The first who set mind above matter; hence his nickname Nous.",
  },
  {
    id: "anaxagoras-doctrine-homoeomeries",
    subject: "Anaxagoras",
    property: "heldDoctrine",
    value: "The universe is compounded of minute homogeneous molecules (homoeomeries)",
    valueType: "doctrine",
    ref: "2.8",
    grc: "ἀρχὰς δὲ τὰς ὁμοιομερείας· καθάπερ γὰρ ἐκ τῶν ψηγμάτων λεγομένων τὸν χρυσὸν συνεστάναι, οὕτως ἐκ τῶν ὁμοιομερῶν μικρῶν σωμάτων τὸ πᾶν συγκεκρίσθαι.",
    certainty: "asserted",
  },
  {
    id: "anaxagoras-doctrine-sun-metal",
    subject: "Anaxagoras",
    property: "heldDoctrine",
    value: "The sun is a mass of red-hot metal, larger than the Peloponnesus",
    valueType: "doctrine",
    ref: "2.8",
    grc: "Οὗτος ἔλεγε τὸν ἥλιον μύδρον εἶναι διάπυρον καὶ μείζω τῆς Πελοποννήσου·",
    certainty: "asserted",
    note: "For this he was indicted on a charge of impiety (2.12).",
  },
  {
    id: "anaxagoras-birth-ol70",
    subject: "Anaxagoras",
    property: "birthDate",
    value: "Born in the 70th Olympiad (500/497 BCE)",
    valueType: "literal",
    ref: "2.7",
    grc: "φησὶ δʼ Ἀπολλόδωρος ἐν τοῖς Χρονικοῖς γεγενῆσθαι αὐτὸν τῇ ἑβδομηκοστῇ Ὀλυμπιάδι, τεθνηκέναι δὲ τῷ πρώτῳ ἔτει τῆς ὀγδοηκοστῆς ὀγδόης",
    certainty: "reported",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
  },
  {
    id: "anaxagoras-death-ol88",
    subject: "Anaxagoras",
    property: "deathDate",
    value: "Died in the first year of the 88th Olympiad (428/427 BCE)",
    valueType: "literal",
    ref: "2.7",
    grc: "φησὶ δʼ Ἀπολλόδωρος ἐν τοῖς Χρονικοῖς γεγενῆσθαι αὐτὸν τῇ ἑβδομηκοστῇ Ὀλυμπιάδι, τεθνηκέναι δὲ τῷ πρώτῳ ἔτει τῆς ὀγδοηκοστῆς ὀγδόης",
    certainty: "reported",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
  },
  {
    id: "anaxagoras-death-lampsacus",
    subject: "Anaxagoras",
    property: "deathPlace",
    value: "Lampsacus",
    valueType: "place",
    ref: "2.14",
    grc: "καὶ τέλος ἀποχωρήσας εἰς Λάμψακον αὐτόθι κατέστρεψεν.",
    certainty: "asserted",
  },
  {
    id: "anaxagoras-death-natural",
    subject: "Anaxagoras",
    property: "mannerOfDeath",
    value: "Retired to Lampsacus and there died; honourably buried by the people",
    valueType: "literal",
    ref: "2.14",
    grc: "καὶ τέλος ἀποχωρήσας εἰς Λάμψακον αὐτόθι κατέστρεψεν. ὅτε καὶ τῶν ἀρχόντων τῆς πόλεως ἀξιούντων τί βούλεται αὐτῷ γενέσθαι, φάναι, τοὺς παῖδας ἐν ᾧ ἂν ἀποθάνῃ μηνὶ κατʼ ἔτος παίζειν συγχωρεῖν.",
    certainty: "asserted",
    conflictsWith: ["anaxagoras-death-suicide"],
  },
  {
    id: "anaxagoras-death-suicide",
    subject: "Anaxagoras",
    property: "mannerOfDeath",
    value: "Could not brook the indignity he had suffered and committed suicide",
    valueType: "literal",
    ref: "2.13",
    grc: "οὐκ ἐνεγκὼν δὲ τὴν ὕβριν ἑαυτὸν ἐξήγαγεν.",
    certainty: "reported",
    accordingTo: "Hermippus",
    conflictsWith: ["anaxagoras-death-natural"],
  },
  // ------------------------------------------------------------ Archelaus
  {
    id: "archelaus-parentage",
    subject: "Archelaus",
    property: "parentage",
    value: "Son of Apollodorus, or as some say of Midon",
    valueType: "literal",
    ref: "2.16",
    grc: "Ἀρχέλαος Ἀθηναῖος ἢ Μιλήσιος, πατρὸς Ἀπολλοδώρου, ὡς δέ τινες, Μίδωνος, μαθητὴς Ἀναξαγόρου, διδάσκαλος Σωκράτους",
    certainty: "asserted",
  },
  {
    id: "archelaus-birthplace-athens",
    subject: "Archelaus",
    property: "birthPlace",
    value: "Athens",
    valueType: "place",
    ref: "2.16",
    grc: "Ἀρχέλαος Ἀθηναῖος ἢ Μιλήσιος, πατρὸς Ἀπολλοδώρου, ὡς δέ τινες, Μίδωνος, μαθητὴς Ἀναξαγόρου, διδάσκαλος Σωκράτους",
    certainty: "reported",
    note: "A citizen of Athens or of Miletus.",
    conflictsWith: ["archelaus-birthplace-miletus"],
  },
  {
    id: "archelaus-birthplace-miletus",
    subject: "Archelaus",
    property: "birthPlace",
    value: "Miletus",
    valueType: "place",
    ref: "2.16",
    grc: "Ἀρχέλαος Ἀθηναῖος ἢ Μιλήσιος, πατρὸς Ἀπολλοδώρου, ὡς δέ τινες, Μίδωνος, μαθητὴς Ἀναξαγόρου, διδάσκαλος Σωκράτους",
    certainty: "reported",
    conflictsWith: ["archelaus-birthplace-athens"],
  },
  {
    id: "archelaus-teacher-anaxagoras",
    subject: "Archelaus",
    property: "studiedUnder",
    value: "Anaxagoras",
    valueType: "philosopher",
    ref: "2.16",
    grc: "Ἀρχέλαος Ἀθηναῖος ἢ Μιλήσιος, πατρὸς Ἀπολλοδώρου, ὡς δέ τινες, Μίδωνος, μαθητὴς Ἀναξαγόρου, διδάσκαλος Σωκράτους",
    certainty: "asserted",
  },
  {
    id: "archelaus-doctrine-convention",
    subject: "Archelaus",
    property: "heldDoctrine",
    value: "What is just and what is base depends not upon nature but upon convention",
    valueType: "doctrine",
    ref: "2.16",
    grc: "καὶ τὸ δίκαιον εἶναι καὶ τὸ αἰσχρὸν οὐ φύσει, ἀλλὰ νόμῳ.",
    certainty: "asserted",
  },
  {
    id: "archelaus-doctrine-heat-cold",
    subject: "Archelaus",
    property: "heldDoctrine",
    value: "Heat and cold are the two causes of becoming; living things were produced from slime",
    valueType: "doctrine",
    ref: "2.16",
    grc: "ἔλεγε δὲ δύο αἰτίας εἶναι γενέσεως, θερμὸν καὶ ψυχρόν. καὶ τὰ ζῷα ἀπὸ τῆς ἰλύος γεννηθῆναι·",
    certainty: "asserted",
  },
  // -------------------------------------------------------------- Socrates
  {
    id: "socrates-birthplace-athens",
    subject: "Socrates",
    property: "birthPlace",
    value: "Athens",
    valueType: "place",
    ref: "2.18",
    grc: "Σωκράτης Σωφρονίσκου μὲν ἦν υἱὸς λιθουργοῦ καὶ Φαιναρέτης μαίας, ὡς καὶ Πλάτων ἐν Θεαιτήτῳ φησίν, Ἀθηναῖος, τῶν δήμων Ἀλωπεκῆθεν",
    certainty: "asserted",
  },
  {
    id: "socrates-parentage",
    subject: "Socrates",
    property: "parentage",
    value: "Son of Sophroniscus, a sculptor, and of Phaenarete, a midwife",
    valueType: "literal",
    ref: "2.18",
    grc: "Σωκράτης Σωφρονίσκου μὲν ἦν υἱὸς λιθουργοῦ καὶ Φαιναρέτης μαίας, ὡς καὶ Πλάτων ἐν Θεαιτήτῳ φησίν, Ἀθηναῖος, τῶν δήμων Ἀλωπεκῆθεν",
    certainty: "asserted",
  },
  {
    id: "socrates-teacher-anaxagoras",
    subject: "Socrates",
    property: "studiedUnder",
    value: "Anaxagoras",
    valueType: "philosopher",
    ref: "2.19",
    grc: "εἶναί τε αὐτοῦ καὶ τὰς ἐν ἀκροπόλει Χάριτας ἔνιοί φασιν, ἐνδεδυμένας οὔσας",
    certainty: "reported",
    note: "According to some authors.",
    conflictsWith: ["socrates-teacher-damon"],
  },
  {
    id: "socrates-teacher-damon",
    subject: "Socrates",
    property: "studiedUnder",
    value: "Damon",
    valueType: "person",
    ref: "2.19",
    grc: "εἶναί τε αὐτοῦ καὶ τὰς ἐν ἀκροπόλει Χάριτας ἔνιοί φασιν, ἐνδεδυμένας οὔσας",
    certainty: "reported",
    accordingTo: "Alexander",
    conflictsWith: ["socrates-teacher-anaxagoras"],
  },
  {
    id: "socrates-teacher-archelaus",
    subject: "Socrates",
    property: "studiedUnder",
    value: "Archelaus",
    valueType: "philosopher",
    ref: "2.19",
    grc: "εἶναί τε αὐτοῦ καὶ τὰς ἐν ἀκροπόλει Χάριτας ἔνιοί φασιν, ἐνδεδυμένας οὔσας",
    certainty: "asserted",
    note: "After the condemnation of Anaxagoras.",
  },
  {
    id: "socrates-birth-ol77",
    subject: "Socrates",
    property: "birthDate",
    value:
      "Born in the fourth year of the 77th Olympiad, on the 6th of Thargelion (469 BCE)",
    valueType: "literal",
    ref: "2.44",
    grc: "Ἐγεννήθη δέ, καθά φησιν Ἀπολλόδωρος ἐν τοῖς Χρονικοῖς, ἐπὶ Ἀψεφίωνος ἐν τῷ τετάρτῳ ἔτει τῆς ἑβδομηκοστῆς ἑβδόμης Ὀλυμπιάδος, Θαργηλιῶνος ἕκτῃ, ὅτε καθαίρουσιν Ἀθηναῖοι τὴν πόλιν καὶ τὴν Ἄρτεμιν Δήλιοι γενέσθαι φασίν. ἐτελεύτησε δὲ τῷ πρώτῳ ἔτει τῆς ἐνενηκοστῆς πέμπτης Ὀλυμπιάδος, γεγονὼς ἐτῶν ἑβδομήκοντα",
    certainty: "reported",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
  },
  {
    id: "socrates-death-ol95",
    subject: "Socrates",
    property: "deathDate",
    value:
      "Died in the first year of the 95th Olympiad, aged 70 (399 BCE)",
    valueType: "literal",
    ref: "2.44",
    grc: "Φιλόχορος δέ φησι προτελευτῆσαι τὸν Εὐριπίδην τοῦ Σωκράτους. Ἐγεννήθη δέ, καθά φησιν Ἀπολλόδωρος ἐν τοῖς Χρονικοῖς, ἐπὶ Ἀψεφίωνος ἐν τῷ τετάρτῳ ἔτει τῆς ἑβδομηκοστῆς ἑβδόμης Ὀλυμπιάδος, Θαργηλιῶνος ἕκτῃ, ὅτε καθαίρουσιν Ἀθηναῖοι τὴν πόλιν καὶ τὴν Ἄρτεμιν Δήλιοι γενέσθαι φασίν",
    certainty: "reported",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
  },
  {
    id: "socrates-death-manner",
    subject: "Socrates",
    property: "mannerOfDeath",
    value: "Condemned by the Athenians; drank the hemlock in prison",
    valueType: "literal",
    ref: "2.42",
    grc: "Καὶ οἳ θάνατον αὐτοῦ κατέγνωσαν, προσθέντες ἄλλας ψήφους ὀγδοήκοντα. καὶ δεθεὶς μετʼ οὐ πολλὰς ἡμέρας ἔπιε τὸ κώνειον, πολλὰ καλὰ κἀγαθὰ διαλεχθείς, ἃ Πλάτων ἐν τῷ Φαίδωνί φησιν.",
    certainty: "asserted",
  },
  {
    id: "socrates-wrote-paean",
    subject: "Socrates",
    property: "wrote",
    value: "Paean (composed in prison)",
    valueType: "work",
    ref: "2.42",
    grc: "Διονυσόδωρος δέ φησι μὴ εἶναι αὐτοῦ τὸν παιᾶνα",
    certainty: "disputed",
    note: "According to some; Dionysodorus denies that he wrote the paean.",
  },
  {
    id: "socrates-doctrine-knowledge-good",
    subject: "Socrates",
    property: "heldDoctrine",
    value: "There is only one good, knowledge, and only one evil, ignorance",
    valueType: "doctrine",
    ref: "2.31",
    grc: "ἔλεγε δὲ καὶ ἓν μόνον ἀγαθὸν εἶναι, τὴν ἐπιστήμην, καὶ ἓν μόνον κακόν, τὴν ἀμαθίαν·",
    certainty: "asserted",
  },
  {
    id: "socrates-doctrine-daimonion",
    subject: "Socrates",
    property: "heldDoctrine",
    value: "A supernatural sign (the daimonion) warned him beforehand of the future",
    valueType: "doctrine",
    greek: "δαιμόνιον",
    ref: "2.32",
    grc: "ἔλεγε δὲ καὶ προσημαίνειν τὸ δαιμόνιον τὰ μέλλοντα αὐτῷ·",
    certainty: "asserted",
  },
  {
    id: "socrates-doctrine-ignorance",
    subject: "Socrates",
    property: "heldDoctrine",
    value: "He knew nothing except just the fact of his own ignorance",
    valueType: "doctrine",
    ref: "2.32",
    grc: "καὶ εἰδέναι μὲν μηδὲν πλὴν αὐτὸ τοῦτο [εἰδέναι].",
    certainty: "asserted",
  },
  {
    id: "socrates-doctrine-nothing-excess",
    subject: "Socrates",
    property: "heldDoctrine",
    value: "The virtue of a young man consists in doing nothing to excess",
    valueType: "doctrine",
    ref: "2.32",
    grc: "καί ποτε ἐρωτηθείς, τίς ἀρετὴ νέου, τὸ μηδὲν ἄγαν, εἶπεν.",
    certainty: "asserted",
  },
  {
    id: "socrates-doctrine-eat-to-live",
    subject: "Socrates",
    property: "heldDoctrine",
    value: "He ate to live, while the rest of the world lived to eat",
    valueType: "doctrine",
    ref: "2.34",
    grc: "ἔλεγέ τε τοὺς μὲν ἄλλους ἀνθρώπους ζῆν ἵνʼ ἐσθίοιεν· αὐτὸς δὲ ἐσθίειν ἵνα ζῴη.",
    certainty: "asserted",
  },
  // -------------------------------------------------------------- Xenophon
  {
    id: "xenophon-parentage",
    subject: "Xenophon",
    property: "parentage",
    value: "Son of Gryllus, of the deme Erchia at Athens",
    valueType: "literal",
    ref: "2.48",
    grc: "Ξενοφῶν Γρύλλου μὲν ἦν υἱός, Ἀθηναῖος, τῶν δήμων Ἐρχιεύς",
    certainty: "asserted",
  },
  {
    id: "xenophon-birthplace-athens",
    subject: "Xenophon",
    property: "birthPlace",
    value: "Athens",
    valueType: "place",
    ref: "2.48",
    grc: "Ξενοφῶν Γρύλλου μὲν ἦν υἱός, Ἀθηναῖος, τῶν δήμων Ἐρχιεύς",
    certainty: "asserted",
  },
  {
    id: "xenophon-teacher-socrates",
    subject: "Xenophon",
    property: "studiedUnder",
    value: "Socrates",
    valueType: "philosopher",
    ref: "2.48",
    grc: "καὶ τοὐντεῦθεν ἀκροατὴς Σωκράτους ἦν",
    certainty: "asserted",
    note: "Socrates barred his way with a stick and made him his pupil.",
  },
  {
    id: "xenophon-lived-scillus",
    subject: "Xenophon",
    property: "livedIn",
    value: "Scillus",
    valueType: "place",
    ref: "2.52",
    grc: "Ἐντεῦθεν ἐάσας τὸν Ἀγησίλαον ἧκεν εἰς Σκιλλοῦντα, χωρίον τῆς Ἠλείας ὀλίγον τῆς πόλεως ἀπέχον",
    certainty: "asserted",
    note: "A place in the territory of Elis, where he hunted and wrote his histories.",
  },
  {
    id: "xenophon-flourished-ol94",
    subject: "Xenophon",
    property: "birthDate",
    value: "Flourished in the fourth year of the 94th Olympiad (401/400 BCE)",
    valueType: "literal",
    ref: "2.55",
    grc: "ἤκμαζε δὲ κατὰ τὸ τέταρτον ἔτος τῆς τετάρτης καὶ ἐνενηκοστῆς Ὀλυμπιάδος",
    certainty: "asserted",
    note: "Took part in the expedition of Cyrus in the year before the death of Socrates.",
  },
  {
    id: "xenophon-death-ol105",
    subject: "Xenophon",
    property: "deathDate",
    value: "Died in the first year of the 105th Olympiad (360 BCE)",
    valueType: "literal",
    ref: "2.56",
    grc: "Κατέστρεψε δέ, καθα ´ φησι Κτησικλείδης ὁ Ἀθηναῖος ἐν τῇ τῶν ἀρχόντων καὶ Ὀλυμπιονικῶν ἀναγραφῇ, ἔτει πρώτῳ τῆς πέμπτης καὶ ἑκατοστῆς Ὀλυμπιάδος, ἐπὶ ἄρχοντος Καλλιδημίδου, ἐφʼ οὗ καὶ Φίλιππος ὁ Ἀμύντου Μακεδόνων ἦρξε",
    certainty: "reported",
    accordingTo: "Ctesiclides",
  },
  {
    id: "xenophon-death-corinth",
    subject: "Xenophon",
    property: "deathPlace",
    value: "Corinth",
    valueType: "place",
    ref: "2.56",
    grc: "τέθνηκε δʼ ἐν Κορίνθῳ, ὥς φησι Δημήτριος ὁ Μάγνης, ἤδη δηλαδὴ γηραιὸς ἱκανῶς",
    certainty: "reported",
    accordingTo: "Demetrius of Magnesia",
  },
  {
    id: "xenophon-wrote-anabasis",
    subject: "Xenophon",
    property: "wrote",
    value: "Anabasis",
    valueType: "work",
    ref: "2.57",
    grc: "Τήν τʼ Ἀνάβασιν, ἧς κατὰ βιβλίον μὲν ἐποίησε προοίμιον, ὅλης δὲ οὔ",
    certainty: "asserted",
  },
  {
    id: "xenophon-wrote-cyropaedia",
    subject: "Xenophon",
    property: "wrote",
    value: "Cyropaedia",
    valueType: "work",
    ref: "2.57",
    grc: "Κύρου Παιδείαν",
    certainty: "asserted",
  },
  {
    id: "xenophon-wrote-hellenica",
    subject: "Xenophon",
    property: "wrote",
    value: "Hellenica",
    valueType: "work",
    ref: "2.57",
    grc: "Ἑλληνικὰ",
    certainty: "asserted",
  },
  {
    id: "xenophon-wrote-memorabilia",
    subject: "Xenophon",
    property: "wrote",
    value: "Memorabilia",
    valueType: "work",
    ref: "2.57",
    grc: "Ἀπομνημονεύματα",
    certainty: "asserted",
  },
  {
    id: "xenophon-wrote-symposium",
    subject: "Xenophon",
    property: "wrote",
    value: "Symposium",
    valueType: "work",
    ref: "2.57",
    grc: "Συμπόσιόν",
    certainty: "asserted",
  },
  {
    id: "xenophon-wrote-oeconomicus",
    subject: "Xenophon",
    property: "wrote",
    value: "Oeconomicus",
    valueType: "work",
    ref: "2.57",
    grc: "Οἰκονομικὸν",
    certainty: "asserted",
  },
  {
    id: "xenophon-wrote-on-horsemanship",
    subject: "Xenophon",
    property: "wrote",
    value: "On Horsemanship",
    valueType: "work",
    ref: "2.57",
    grc: "Περὶ ἱππικῆς",
    certainty: "asserted",
  },
  {
    id: "xenophon-wrote-on-hunting",
    subject: "Xenophon",
    property: "wrote",
    value: "On Hunting",
    valueType: "work",
    ref: "2.57",
    grc: "Κυνηγετικὸν",
    certainty: "asserted",
  },
  {
    id: "xenophon-wrote-cavalry-general",
    subject: "Xenophon",
    property: "wrote",
    value: "On the Duty of a Cavalry General",
    valueType: "work",
    ref: "2.57",
    grc: "Ἱππαρχικόν",
    certainty: "asserted",
  },
  {
    id: "xenophon-wrote-defence-socrates",
    subject: "Xenophon",
    property: "wrote",
    value: "A Defence of Socrates",
    valueType: "work",
    ref: "2.57",
    grc: "Ἀπολογίαν τε Σωκράτους",
    certainty: "asserted",
  },
  {
    id: "xenophon-wrote-on-revenues",
    subject: "Xenophon",
    property: "wrote",
    value: "On Revenues",
    valueType: "work",
    ref: "2.57",
    grc: "Περὶ πόρων",
    certainty: "asserted",
  },
  {
    id: "xenophon-wrote-hieron",
    subject: "Xenophon",
    property: "wrote",
    value: "Hieron, or Of Tyranny",
    valueType: "work",
    ref: "2.57",
    grc: "Ἱέρωνα ἢ Τυραννικόν",
    certainty: "asserted",
  },
  {
    id: "xenophon-wrote-agesilaus",
    subject: "Xenophon",
    property: "wrote",
    value: "Agesilaus",
    valueType: "work",
    ref: "2.57",
    grc: "Ἀγησίλαόν",
    certainty: "asserted",
  },
  {
    id: "xenophon-wrote-constitutions",
    subject: "Xenophon",
    property: "wrote",
    value: "The Constitutions of Athens and Sparta",
    valueType: "work",
    ref: "2.57",
    grc: "Ἀθηναίων καὶ Λακεδαιμονίων Πολιτείαν, ἥν φησιν οὐκ εἶναι Ξενοφῶντος ὁ Μάγνης Δημήτριος",
    certainty: "disputed",
    note: "Demetrius of Magnesia denies that the last of these works is by Xenophon.",
  },
  // -------------------------------------------------------------- Aeschines
  {
    id: "aeschines-parentage",
    subject: "Aeschines",
    property: "parentage",
    value: "Son of Charinus the sausage-maker, though others make his father's name Lysanias",
    valueType: "literal",
    ref: "2.60",
    grc: "Αἰσχίνης Χαρίνου τοῦ ἀλλαντοποιοῦ, οἱ δὲ Λυσανίου, Ἀθηναῖος, ἐκ νέου φιλόπονος",
    certainty: "asserted",
  },
  {
    id: "aeschines-birthplace-athens",
    subject: "Aeschines",
    property: "birthPlace",
    value: "Athens",
    valueType: "place",
    ref: "2.60",
    grc: "Αἰσχίνης Χαρίνου τοῦ ἀλλαντοποιοῦ, οἱ δὲ Λυσανίου, Ἀθηναῖος, ἐκ νέου φιλόπονος",
    certainty: "asserted",
  },
  {
    id: "aeschines-teacher-socrates",
    subject: "Aeschines",
    property: "studiedUnder",
    value: "Socrates",
    valueType: "philosopher",
    ref: "2.60",
    grc: "Αἰσχίνης Χαρίνου τοῦ ἀλλαντοποιοῦ, οἱ δὲ Λυσανίου, Ἀθηναῖος, ἐκ νέου φιλόπονος",
    certainty: "asserted",
    note: "He never quitted Socrates: 'Only the sausage-maker's son knows how to honour me.'",
  },
  {
    id: "aeschines-wrote-miltiades",
    subject: "Aeschines",
    property: "wrote",
    value: "Miltiades",
    valueType: "work",
    ref: "2.61",
    grc: "πρῶτος Μιλτιάδης, διὸ καὶ ἀσθενέστερόν πως ἔχει",
    certainty: "asserted",
    note: "One of the seven dialogues stamped with a Socratic character; some doubted his authorship of the dialogues (2.60).",
  },
  {
    id: "aeschines-wrote-callias",
    subject: "Aeschines",
    property: "wrote",
    value: "Callias",
    valueType: "work",
    ref: "2.61",
    grc: "Καλλίας",
    certainty: "asserted",
  },
  {
    id: "aeschines-wrote-axiochus",
    subject: "Aeschines",
    property: "wrote",
    value: "Axiochus",
    valueType: "work",
    ref: "2.61",
    grc: "Ἀξίοχος",
    certainty: "asserted",
  },
  {
    id: "aeschines-wrote-aspasia",
    subject: "Aeschines",
    property: "wrote",
    value: "Aspasia",
    valueType: "work",
    ref: "2.61",
    grc: "Ἀσπασία",
    certainty: "asserted",
  },
  {
    id: "aeschines-wrote-alcibiades",
    subject: "Aeschines",
    property: "wrote",
    value: "Alcibiades",
    valueType: "work",
    ref: "2.61",
    grc: "Ἀλκιβιάδης",
    certainty: "asserted",
  },
  {
    id: "aeschines-wrote-telauges",
    subject: "Aeschines",
    property: "wrote",
    value: "Telauges",
    valueType: "work",
    ref: "2.61",
    grc: "Τηλαύγης",
    certainty: "asserted",
  },
  {
    id: "aeschines-wrote-rhinon",
    subject: "Aeschines",
    property: "wrote",
    value: "Rhinon",
    valueType: "work",
    ref: "2.61",
    grc: "Ῥίνων",
    certainty: "asserted",
  },
  // -------------------------------------------------------------- Aristippus
  {
    id: "aristippus-birthplace-cyrene",
    subject: "Aristippus",
    property: "birthPlace",
    value: "Cyrene",
    valueType: "place",
    ref: "2.65",
    grc: "Ἀρίστιππος τὸ μὲν γένος ἦν Κυρηναῖος, ἀφιγμένος δʼ Ἀθήναζε, καθά φησιν Αἰσχίνης, κατὰ κλέος Σωκράτους",
    certainty: "asserted",
  },
  {
    id: "aristippus-teacher-socrates",
    subject: "Aristippus",
    property: "studiedUnder",
    value: "Socrates",
    valueType: "philosopher",
    ref: "2.65",
    grc: "Ἀρίστιππος τὸ μὲν γένος ἦν Κυρηναῖος, ἀφιγμένος δʼ Ἀθήναζε, καθά φησιν Αἰσχίνης, κατὰ κλέος Σωκράτους",
    certainty: "asserted",
    note: "Drawn to Athens by the fame of Socrates; the first of the followers of Socrates to charge fees.",
  },
  {
    id: "aristippus-affiliation-cyrenaic",
    subject: "Aristippus",
    property: "affiliatedWith",
    value: "Cyrenaic",
    valueType: "school",
    ref: "2.85",
    grc: "Κατὰ δὲ Σωτίωνα ἐν δευτέρῳ καὶ Παναίτιον ἔστιν αὐτῷ συγγράμματα τάδε",
    certainty: "asserted",
    note: "Founder of the Cyrenaic school which sprang from him.",
  },
  {
    id: "aristippus-doctrine-end-pleasure",
    subject: "Aristippus",
    property: "heldDoctrine",
    value: "The end is the smooth motion resulting in sensation (pleasure)",
    valueType: "doctrine",
    greek: "ἡδονή",
    ref: "2.85",
    grc: "Τέλος δʼ ἀπέφαινε τὴν λείαν κίνησιν εἰς αἴσθησιν ἀναδιδομένην.",
    certainty: "asserted",
  },
  {
    id: "aristippus-doctrine-present",
    subject: "Aristippus",
    property: "heldDoctrine",
    value: "He derived pleasure from what was present, and did not toil to procure the enjoyment of what was absent",
    valueType: "doctrine",
    ref: "2.66",
    grc: "ἀπέλαυε μὲν γὰρ ἡδονῆς τῶν παρόντων, οὐκ ἐθήρα δὲ πόνῳ τὴν ἀπόλαυσιν τῶν οὐ παρόντων·",
    certainty: "asserted",
  },
  {
    id: "aristippus-wrote-libya",
    subject: "Aristippus",
    property: "wrote",
    value: "A History of Libya (in three books, sent to Dionysius)",
    valueType: "work",
    ref: "2.83",
    grc: "Τοῦ δὲ Κυρηναϊκοῦ φιλοσόφου φέρεται βιβλία τρία μὲν ἱστορίας τῶν κατὰ Λιβύην, ἀπεσταλμένα Διονυσίῳ",
    certainty: "asserted",
    conflictsWith: ["aristippus-writings-none"],
  },
  {
    id: "aristippus-wrote-artabazus",
    subject: "Aristippus",
    property: "wrote",
    value: "Artabazus",
    valueType: "work",
    ref: "2.84",
    grc: "Ἀρτάβαζος",
    certainty: "asserted",
  },
  {
    id: "aristippus-wrote-to-shipwrecked",
    subject: "Aristippus",
    property: "wrote",
    value: "To the Shipwrecked",
    valueType: "work",
    ref: "2.84",
    grc: "Πρὸς τοὺς ναυαγούς",
    certainty: "asserted",
  },
  {
    id: "aristippus-wrote-to-exiles",
    subject: "Aristippus",
    property: "wrote",
    value: "To the Exiles",
    valueType: "work",
    ref: "2.84",
    grc: "Πρὸς τοὺς φυγάδας",
    certainty: "asserted",
  },
  {
    id: "aristippus-wrote-to-lais",
    subject: "Aristippus",
    property: "wrote",
    value: "To Laïs",
    valueType: "work",
    ref: "2.84",
    grc: "Πρὸς Λαΐδα",
    certainty: "asserted",
  },
  {
    id: "aristippus-wrote-to-lais-mirror",
    subject: "Aristippus",
    property: "wrote",
    value: "To Laïs, On the Mirror",
    valueType: "work",
    ref: "2.84",
    grc: "Πρὸς Λαΐδα περὶ τοῦ κατόπτρου",
    certainty: "asserted",
  },
  {
    id: "aristippus-wrote-on-education",
    subject: "Aristippus",
    property: "wrote",
    value: "On Education",
    valueType: "work",
    ref: "2.85",
    grc: "Περὶ παιδείας",
    certainty: "asserted",
    note: "Per Sotion and Panaetius.",
  },
  {
    id: "aristippus-wrote-on-virtue",
    subject: "Aristippus",
    property: "wrote",
    value: "On Virtue",
    valueType: "work",
    ref: "2.85",
    grc: "Περὶ ἀρετῆς",
    certainty: "asserted",
  },
  {
    id: "aristippus-wrote-introduction-philosophy",
    subject: "Aristippus",
    property: "wrote",
    value: "Introduction to Philosophy",
    valueType: "work",
    ref: "2.85",
    grc: "Κατὰ δὲ Σωτίωνα ἐν δευτέρῳ καὶ Παναίτιον ἔστιν αὐτῷ συγγράμματα τάδε",
    certainty: "asserted",
  },
  {
    id: "aristippus-wrote-on-fortune",
    subject: "Aristippus",
    property: "wrote",
    value: "On Fortune",
    valueType: "work",
    ref: "2.85",
    grc: "Περὶ τύχης",
    certainty: "asserted",
  },
  {
    id: "aristippus-writings-none",
    subject: "Aristippus",
    property: "writings",
    value: "Wrote nothing at all",
    valueType: "literal",
    ref: "2.84",
    grc: "Ἀρτάβαζος",
    certainty: "disputed",
    accordingTo: "Sosicrates",
    note: "Sosicrates of Rhodes holds he wrote nothing; others credit him with the dialogues and essays.",
    conflictsWith: ["aristippus-wrote-libya"],
  },
  // -------------------------------------------------------------- Phaedo
  {
    id: "phaedo-birthplace-elis",
    subject: "Phaedo",
    property: "birthPlace",
    value: "Elis",
    valueType: "place",
    ref: "2.105",
    grc: "Φαίδων Ἠλεῖος, τῶν εὐπατριδῶν, συνεάλω τῇ πατρίδι καὶ ἠναγκάσθη στῆναι ἐπʼ οἰκήματος",
    certainty: "asserted",
    note: "Of noble family; taken captive on the fall of the city, ransomed at Socrates' instance.",
  },
  {
    id: "phaedo-teacher-socrates",
    subject: "Phaedo",
    property: "studiedUnder",
    value: "Socrates",
    valueType: "philosopher",
    ref: "2.105",
    grc: "Φαίδων Ἠλεῖος, τῶν εὐπατριδῶν, συνεάλω τῇ πατρίδι καὶ ἠναγκάσθη στῆναι ἐπʼ οἰκήματος",
    certainty: "asserted",
    note: "Joined Socrates' circle and afterwards studied philosophy as a free man.",
  },
  {
    id: "phaedo-affiliation-elian",
    subject: "Phaedo",
    property: "affiliatedWith",
    value: "Elian (later Eretrian) school",
    valueType: "school",
    ref: "2.105",
    grc: "Φαίδων Ἠλεῖος, τῶν εὐπατριδῶν, συνεάλω τῇ πατρίδι καὶ ἠναγκάσθη στῆναι ἐπʼ οἰκήματος",
    certainty: "asserted",
    note: "The school was known as that of Elis until Menedemus, when it was called Eretrian.",
  },
  {
    id: "phaedo-wrote-zopyrus",
    subject: "Phaedo",
    property: "wrote",
    value: "Zopyrus",
    valueType: "work",
    ref: "2.105",
    grc: "διαλόγους δὲ συνέγραψε γνησίους μὲν Ζώπυρον,",
    certainty: "asserted",
    note: "Genuine, together with Simon.",
  },
  {
    id: "phaedo-wrote-simon",
    subject: "Phaedo",
    property: "wrote",
    value: "Simon",
    valueType: "work",
    ref: "2.105",
    grc: "Σίμωνα,",
    certainty: "asserted",
  },
  {
    id: "phaedo-wrote-nicias",
    subject: "Phaedo",
    property: "wrote",
    value: "Nicias",
    valueType: "work",
    ref: "2.105",
    grc: "καὶ δισταζόμενον Νικίαν,",
    certainty: "disputed",
    note: "The Nicias is doubtful; the Medius and the Cobblers' Tales are by some ascribed to Aeschines.",
  },
  // -------------------------------------------------------------- Euclides
  {
    id: "euclides-birthplace-megara",
    subject: "Euclides",
    property: "birthPlace",
    value: "Megara",
    valueType: "place",
    ref: "2.106",
    grc: "Εὐκλείδης ἀπὸ Μεγάρων τῶν πρὸς Ἰσθμῷ, ἢ Γελῶος κατʼ ἐνίους, ὥς φησιν Ἀλέξανδρος ἐν Διαδοχαῖς",
    certainty: "asserted",
    conflictsWith: ["euclides-birthplace-gela"],
  },
  {
    id: "euclides-birthplace-gela",
    subject: "Euclides",
    property: "birthPlace",
    value: "Gela",
    valueType: "place",
    ref: "2.106",
    grc: "Εὐκλείδης ἀπὸ Μεγάρων τῶν πρὸς Ἰσθμῷ, ἢ Γελῶος κατʼ ἐνίους, ὥς φησιν Ἀλέξανδρος ἐν Διαδοχαῖς",
    certainty: "reported",
    accordingTo: "Alexander",
    conflictsWith: ["euclides-birthplace-megara"],
  },
  {
    id: "euclides-affiliation-megarian",
    subject: "Euclides",
    property: "affiliatedWith",
    value: "Megarian",
    valueType: "school",
    ref: "2.106",
    grc: "Εὐκλείδης ἀπὸ Μεγάρων τῶν πρὸς Ἰσθμῷ, ἢ Γελῶος κατʼ ἐνίους, ὥς φησιν Ἀλέξανδρος ἐν Διαδοχαῖς",
    certainty: "asserted",
    note: "His followers were called Megarians, then Eristics, and later Dialecticians.",
  },
  {
    id: "euclides-doctrine-good-one",
    subject: "Euclides",
    property: "heldDoctrine",
    value: "The supreme good is one, though called by many names - wisdom, God, Mind and so forth",
    valueType: "doctrine",
    ref: "2.106",
    grc: "οὗτος ἓν τὸ ἀγαθὸν ἀπεφαίνετο πολλοῖς ὀνόμασι καλούμενον· ὁτὲ μὲν γὰρ φρόνησιν, ὁτὲ δὲ θεόν, καὶ ἄλλοτε νοῦν καὶ τὰ λοιπά.",
    certainty: "asserted",
  },
  {
    id: "euclides-wrote-lamprias",
    subject: "Euclides",
    property: "wrote",
    value: "Lamprias",
    valueType: "work",
    ref: "2.108",
    grc: "Διαλόγους δὲ συνέγραψεν ἕξ, Λαμπρίαν, Αἰσχίνην, Φοίνικα, Κρίτωνα, Ἀλκιβιάδην, Ἐρωτικόν",
    certainty: "asserted",
  },
  {
    id: "euclides-wrote-aeschines",
    subject: "Euclides",
    property: "wrote",
    value: "Aeschines",
    valueType: "work",
    ref: "2.108",
    grc: "Αἰσχίνην",
    certainty: "asserted",
  },
  {
    id: "euclides-wrote-phoenix",
    subject: "Euclides",
    property: "wrote",
    value: "Phoenix",
    valueType: "work",
    ref: "2.108",
    grc: "Φοίνικα",
    certainty: "asserted",
  },
  {
    id: "euclides-wrote-crito",
    subject: "Euclides",
    property: "wrote",
    value: "Crito",
    valueType: "work",
    ref: "2.108",
    grc: "Κρίτωνα",
    certainty: "asserted",
  },
  {
    id: "euclides-wrote-alcibiades",
    subject: "Euclides",
    property: "wrote",
    value: "Alcibiades",
    valueType: "work",
    ref: "2.108",
    grc: "Ἀλκιβιάδην",
    certainty: "asserted",
  },
  {
    id: "euclides-wrote-on-love",
    subject: "Euclides",
    property: "wrote",
    value: "A Discourse on Love",
    valueType: "work",
    ref: "2.108",
    grc: "Ἐρωτικόν",
    certainty: "asserted",
  },
  // -------------------------------------------------------------- Stilpo
  {
    id: "stilpo-birthplace-megara",
    subject: "Stilpo",
    property: "birthPlace",
    value: "Megara",
    valueType: "place",
    ref: "2.113",
    grc: "Στίλπων Μεγαρεὺς τῆς Ἑλλάδος διήκουσε μὲν τῶν ἀπʼ Εὐκλείδου τινῶν",
    certainty: "asserted",
  },
  {
    id: "stilpo-affiliation-megarian",
    subject: "Stilpo",
    property: "affiliatedWith",
    value: "Megarian",
    valueType: "school",
    ref: "2.113",
    grc: "Στίλπων Μεγαρεὺς τῆς Ἑλλάδος διήκουσε μὲν τῶν ἀπʼ Εὐκλείδου τινῶν",
    certainty: "asserted",
    note: "Nearly the whole of Greece was attracted to him and joined the school of Megara.",
  },
  {
    id: "stilpo-teacher-euclides",
    subject: "Stilpo",
    property: "studiedUnder",
    value: "Euclides",
    valueType: "philosopher",
    ref: "2.113",
    grc: "ἀπὸ δὲ τῶν διαλεκτικῶν Παιώνειον μὲν ἀπʼ Ἀριστείδου, Δίφιλον δὲ τὸν Βοσποριανὸν Εὐφάντου καὶ Μύρμηκα τὸν Ἐξαινέτου παραγενομένους ὡς ἐλέγξοντας ἀμφοτέρους ζηλωτὰς ἔσχε.",
    certainty: "reported",
    note: "A pupil of some of the followers of Euclides, although others make him a pupil of Euclides himself.",
  },
  {
    id: "stilpo-doctrine-nominalism",
    subject: "Stilpo",
    property: "heldDoctrine",
    value: "He who asserts the existence of Man means no individual; therefore he means no one at all",
    valueType: "doctrine",
    ref: "2.119",
    grc: "καὶ ἔλεγε τὸν λέγοντα ἄνθρωπον εἶναι μηδένα· οὔτε γὰρ τόνδε εἶναι οὔτε τόνδε· τί γὰρ μᾶλλον τόνδε ἢ τόνδε; οὐδʼ ἄρα τόνδε.",
    certainty: "asserted",
    note: "A consummate master of controversy, he used to demolish even the Ideas.",
  },
  {
    id: "stilpo-wrote-moschus",
    subject: "Stilpo",
    property: "wrote",
    value: "Moschus",
    valueType: "work",
    ref: "2.120",
    grc: "Μόσχος, Ἀρίστιππος ἢ Καλλίας, Πτολεμαῖος, Χαιρεκράτης, Μητροκλῆς, Ἀναξιμένης, Ἐπιγένης, Πρὸς τὴν ἑαυτοῦ θυγατέρα, Ἀριστοτέλης",
    certainty: "asserted",
  },
  {
    id: "stilpo-wrote-aristippus",
    subject: "Stilpo",
    property: "wrote",
    value: "Aristippus, or Callias",
    valueType: "work",
    ref: "2.120",
    grc: "Ἀρίστιππος ἢ Καλλίας",
    certainty: "asserted",
  },
  {
    id: "stilpo-wrote-ptolemy",
    subject: "Stilpo",
    property: "wrote",
    value: "Ptolemy",
    valueType: "work",
    ref: "2.120",
    grc: "Πτολεμαῖος",
    certainty: "asserted",
  },
  {
    id: "stilpo-wrote-chaerecrates",
    subject: "Stilpo",
    property: "wrote",
    value: "Chaerecrates",
    valueType: "work",
    ref: "2.120",
    grc: "Χαιρεκράτης",
    certainty: "asserted",
  },
  {
    id: "stilpo-wrote-metrocles",
    subject: "Stilpo",
    property: "wrote",
    value: "Metrocles",
    valueType: "work",
    ref: "2.120",
    grc: "Μητροκλῆς",
    certainty: "asserted",
  },
  {
    id: "stilpo-wrote-anaximenes",
    subject: "Stilpo",
    property: "wrote",
    value: "Anaximenes",
    valueType: "work",
    ref: "2.120",
    grc: "Ἀναξιμένης",
    certainty: "asserted",
  },
  {
    id: "stilpo-wrote-epigenes",
    subject: "Stilpo",
    property: "wrote",
    value: "Epigenes",
    valueType: "work",
    ref: "2.120",
    grc: "Ἐπιγένης",
    certainty: "asserted",
  },
  {
    id: "stilpo-wrote-to-daughter",
    subject: "Stilpo",
    property: "wrote",
    value: "To his Daughter",
    valueType: "work",
    ref: "2.120",
    grc: "Πρὸς τὴν ἑαυτοῦ θυγατέρα",
    certainty: "asserted",
  },
  {
    id: "stilpo-wrote-aristotle",
    subject: "Stilpo",
    property: "wrote",
    value: "Aristotle",
    valueType: "work",
    ref: "2.120",
    grc: "Ἀριστοτέλης",
    certainty: "asserted",
  },
  {
    id: "stilpo-death-manner",
    subject: "Stilpo",
    property: "mannerOfDeath",
    value: "Died at a great age after taking wine to hasten his end",
    valueType: "literal",
    ref: "2.120",
    grc: "γηραιὸν δὲ τελευτῆσαί φησιν Ἕρμιππος, οἶνον προσενεγκάμενον ὅπως θᾶττον ἀποθάνοι.",
    certainty: "reported",
    accordingTo: "Hermippus",
  },
  // -------------------------------------------------------------- Crito
  {
    id: "crito-birthplace-athens",
    subject: "Crito",
    property: "birthPlace",
    value: "Athens",
    valueType: "place",
    ref: "2.121",
    grc: "Κρίτων Ἀθηναῖος",
    certainty: "asserted",
    note: "Most affectionate towards Socrates; his four sons were also pupils of Socrates.",
  },
  {
    id: "crito-wrote-not-good-by-instruction",
    subject: "Crito",
    property: "wrote",
    value: "That men are not made good by instruction",
    valueType: "work",
    ref: "2.121",
    grc: "Κρίτων Ἀθηναῖος",
    certainty: "asserted",
    note: "One of seventeen dialogues extant in a single volume.",
  },
  {
    id: "crito-wrote-superfluity",
    subject: "Crito",
    property: "wrote",
    value: "Concerning superfluity",
    valueType: "work",
    ref: "2.121",
    grc: "Περὶ εὐθημοσύνης",
    certainty: "asserted",
  },
  {
    id: "crito-wrote-what-is-expedient",
    subject: "Crito",
    property: "wrote",
    value: "What is expedient, or The Statesman",
    valueType: "work",
    ref: "2.121",
    grc: "Τί τὸ ἐπιτήδειον ἢ Πολιτικός",
    certainty: "asserted",
  },
  {
    id: "crito-wrote-of-beauty",
    subject: "Crito",
    property: "wrote",
    value: "Of Beauty",
    valueType: "work",
    ref: "2.121",
    grc: "Περὶ τοῦ καλοῦ",
    certainty: "asserted",
  },
  {
    id: "crito-wrote-on-law",
    subject: "Crito",
    property: "wrote",
    value: "On Law",
    valueType: "work",
    ref: "2.121",
    grc: "Περὶ τοῦ πλέον ἔχειν",
    certainty: "asserted",
  },
  {
    id: "crito-wrote-of-wisdom",
    subject: "Crito",
    property: "wrote",
    value: "Of Wisdom",
    valueType: "work",
    ref: "2.121",
    grc: "Περὶ τοῦ κακουργεῖν",
    certainty: "asserted",
  },
  {
    id: "crito-wrote-what-is-knowledge",
    subject: "Crito",
    property: "wrote",
    value: "What is Knowledge",
    valueType: "work",
    ref: "2.121",
    grc: "Περὶ τοῦ γνῶναι ἢ Περὶ ἐπιστήμης",
    certainty: "asserted",
  },
  // -------------------------------------------------------------- Simon
  {
    id: "simon-birthplace-athens",
    subject: "Simon",
    property: "birthPlace",
    value: "Athens",
    valueType: "place",
    ref: "2.122",
    grc: "Σίμων Ἀθηναῖος, σκυτοτόμος",
    certainty: "asserted",
    note: "A cobbler who noted down Socrates' conversations; the first to record Socratic dialogues.",
  },
  {
    id: "simon-wrote-of-the-gods",
    subject: "Simon",
    property: "wrote",
    value: "Of the Gods",
    valueType: "work",
    ref: "2.122",
    grc: "Περὶ θεῶν",
    certainty: "asserted",
    note: "One of thirty-three 'leathern' dialogues extant in a single volume.",
  },
  {
    id: "simon-wrote-of-the-good",
    subject: "Simon",
    property: "wrote",
    value: "Of the Good",
    valueType: "work",
    ref: "2.122",
    grc: "Περὶ τοῦ ἀγαθοῦ",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-on-the-beautiful",
    subject: "Simon",
    property: "wrote",
    value: "On the Beautiful",
    valueType: "work",
    ref: "2.122",
    grc: "Περὶ τοῦ καλοῦ",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-of-virtue",
    subject: "Simon",
    property: "wrote",
    value: "Of Virtue, that it cannot be taught",
    valueType: "work",
    ref: "2.122",
    grc: "Περὶ ἀρετῆς ὅτι οὐ διδακτόν",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-on-love",
    subject: "Simon",
    property: "wrote",
    value: "On Love",
    valueType: "work",
    ref: "2.122",
    grc: "Περὶ ἔρωτος",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-on-philosophy",
    subject: "Simon",
    property: "wrote",
    value: "On Philosophy",
    valueType: "work",
    ref: "2.122",
    grc: "Περὶ φιλοσοφίας Περὶ ἐπιστήμης",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-what-is-the-beautiful",
    subject: "Simon",
    property: "wrote",
    value: "What is the Beautiful",
    valueType: "work",
    ref: "2.122",
    grc: "Τί τὸ καλόν",
    certainty: "asserted",
    note: "Listed twice in the catalogue (Τί τὸ καλόν); the repeat opens the Greek text of 2.123.",
  },
  {
    id: "simon-wrote-on-the-just",
    subject: "Simon",
    property: "wrote",
    value: "On the Just",
    valueType: "work",
    ref: "2.122",
    grc: "Περὶ δικαίου πρῶτον, δεύτερον",
    certainty: "asserted",
    note: "Two dialogues (Περὶ δικαίου πρῶτον, δεύτερον).",
  },
  {
    id: "simon-wrote-of-courage",
    subject: "Simon",
    property: "wrote",
    value: "Of Courage",
    valueType: "work",
    ref: "2.122",
    grc: "Περὶ ἀνδρείας πρῶτον, δεύτερον, τρίτον",
    certainty: "asserted",
    note: "Three dialogues (Περὶ ἀνδρείας πρῶτον, δεύτερον, τρίτον).",
  },
  {
    id: "simon-wrote-on-law",
    subject: "Simon",
    property: "wrote",
    value: "On Law",
    valueType: "work",
    ref: "2.122",
    grc: "Περὶ δικαίου πρῶτον",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-on-guiding-the-people",
    subject: "Simon",
    property: "wrote",
    value: "On Guiding the People",
    valueType: "work",
    ref: "2.122",
    grc: "Περὶ ἀνδρείας πρῶτον",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-of-honour",
    subject: "Simon",
    property: "wrote",
    value: "Of Honour",
    valueType: "work",
    ref: "2.122",
    grc: "Περὶ νόμου",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-of-poetry",
    subject: "Simon",
    property: "wrote",
    value: "Of Poetry",
    valueType: "work",
    ref: "2.122",
    grc: "Περὶ δημαγωγίας",
    certainty: "asserted",
    note: "Hicks renders the catalogue's first Περὶ ποιήσεως as 'Of Poetry' and its repeat as 'On Poetry'.",
  },
  {
    id: "simon-wrote-on-good-eating",
    subject: "Simon",
    property: "wrote",
    value: "On Good Eating",
    valueType: "work",
    ref: "2.122",
    grc: "Περὶ τιμῆς",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-on-knowledge",
    subject: "Simon",
    property: "wrote",
    value: "On Knowledge",
    valueType: "work",
    ref: "2.122",
    grc: "Περὶ ποιήσεως",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-on-music",
    subject: "Simon",
    property: "wrote",
    value: "On Music",
    valueType: "work",
    ref: "2.122",
    grc: "Περὶ μουσικῆς",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-on-poetry",
    subject: "Simon",
    property: "wrote",
    value: "On Poetry",
    valueType: "work",
    ref: "2.122",
    grc: "Περὶ εὐπαθείας",
    certainty: "asserted",
    note: "The catalogue's second Περὶ ποιήσεως in Hicks' rendering.",
  },
  {
    id: "simon-wrote-on-teaching",
    subject: "Simon",
    property: "wrote",
    value: "On Teaching",
    valueType: "work",
    ref: "2.123",
    grc: "Περὶ διδασκαλίας",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-on-the-art-of-conversation",
    subject: "Simon",
    property: "wrote",
    value: "On the Art of Conversation",
    valueType: "work",
    ref: "2.123",
    grc: "Περὶ τοῦ διαλέγεσθαι",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-of-judging",
    subject: "Simon",
    property: "wrote",
    value: "Of Judging",
    valueType: "work",
    ref: "2.123",
    grc: "Περὶ κρίσεως",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-of-being",
    subject: "Simon",
    property: "wrote",
    value: "Of Being",
    valueType: "work",
    ref: "2.123",
    grc: "Περὶ τοῦ ὄντος",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-of-number",
    subject: "Simon",
    property: "wrote",
    value: "Of Number",
    valueType: "work",
    ref: "2.123",
    grc: "Περὶ ἀριθμοῦ",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-on-diligence",
    subject: "Simon",
    property: "wrote",
    value: "On Diligence",
    valueType: "work",
    ref: "2.123",
    grc: "Περὶ ἐπιμελείας",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-on-efficiency",
    subject: "Simon",
    property: "wrote",
    value: "On Efficiency",
    valueType: "work",
    ref: "2.123",
    grc: "Περὶ τοῦ ἐργάζεσθαι",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-on-greed",
    subject: "Simon",
    property: "wrote",
    value: "On Greed",
    valueType: "work",
    ref: "2.123",
    grc: "Περὶ φιλοκερδοῦς",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-on-pretentiousness",
    subject: "Simon",
    property: "wrote",
    value: "On Pretentiousness",
    valueType: "work",
    ref: "2.123",
    grc: "Περὶ ἀλαζονείας",
    certainty: "asserted",
  },
  {
    id: "simon-wrote-on-deliberation",
    subject: "Simon",
    property: "wrote",
    value: "On Deliberation",
    valueType: "work",
    ref: "2.123",
    grc: "Περὶ τοῦ καλοῦ",
    certainty: "reported",
    note: "One of three dialogues introduced by 'Others are' (οἱ δέ) - attributed by some.",
  },
  {
    id: "simon-wrote-on-reason-or-on-expediency",
    subject: "Simon",
    property: "wrote",
    value: "On Reason, or On Expediency",
    valueType: "work",
    ref: "2.123",
    grc: "Περὶ λόγου ἢ περὶ ἐπιτηδειότητος",
    certainty: "reported",
    note: "One of three dialogues introduced by 'Others are' (οἱ δέ) - attributed by some.",
  },
  {
    id: "simon-wrote-on-doing-ill",
    subject: "Simon",
    property: "wrote",
    value: "On Doing Ill",
    valueType: "work",
    ref: "2.123",
    grc: "Περὶ κακουργίας",
    certainty: "reported",
    note: "One of three dialogues introduced by 'Others are' (οἱ δέ) - attributed by some.",
  },
  // -------------------------------------------------------------- Glaucon
  {
    id: "glaucon-birthplace-athens",
    subject: "Glaucon",
    property: "birthPlace",
    value: "Athens",
    valueType: "place",
    ref: "2.124",
    grc: "Γλαύκων Ἀθηναῖος",
    certainty: "asserted",
  },
  {
    id: "glaucon-wrote-phidylus",
    subject: "Glaucon",
    property: "wrote",
    value: "Phidylus",
    valueType: "work",
    ref: "2.124",
    grc: "Φειδύλος",
    certainty: "asserted",
    note: "One of nine dialogues extant in a single volume; thirty-two others are considered spurious.",
  },
  {
    id: "glaucon-wrote-euripides",
    subject: "Glaucon",
    property: "wrote",
    value: "Euripides",
    valueType: "work",
    ref: "2.124",
    grc: "Εὐριπίδης",
    certainty: "asserted",
  },
  {
    id: "glaucon-wrote-amyntichus",
    subject: "Glaucon",
    property: "wrote",
    value: "Amyntichus",
    valueType: "work",
    ref: "2.124",
    grc: "Ἀμύντιχος",
    certainty: "asserted",
  },
  {
    id: "glaucon-wrote-euthias",
    subject: "Glaucon",
    property: "wrote",
    value: "Euthias",
    valueType: "work",
    ref: "2.124",
    grc: "Εὐθίας",
    certainty: "asserted",
  },
  {
    id: "glaucon-wrote-cephalus",
    subject: "Glaucon",
    property: "wrote",
    value: "Cephalus",
    valueType: "work",
    ref: "2.124",
    grc: "Κέφαλος",
    certainty: "asserted",
  },
  {
    id: "glaucon-wrote-menexenus",
    subject: "Glaucon",
    property: "wrote",
    value: "Menexenus",
    valueType: "work",
    ref: "2.124",
    grc: "Μενέξενος",
    certainty: "asserted",
  },
  // -------------------------------------------------------------- Simmias
  {
    id: "simmias-birthplace-thebes",
    subject: "Simmias",
    property: "birthPlace",
    value: "Thebes",
    valueType: "place",
    ref: "2.124",
    grc: "Σιμμίας Θηβαῖος",
    certainty: "asserted",
  },
  {
    id: "simmias-wrote-on-wisdom",
    subject: "Simmias",
    property: "wrote",
    value: "On Wisdom",
    valueType: "work",
    ref: "2.124",
    grc: "Περὶ σοφίας",
    certainty: "asserted",
    note: "One of twenty-three dialogues extant in a single volume.",
  },
  {
    id: "simmias-wrote-on-philosophy",
    subject: "Simmias",
    property: "wrote",
    value: "On Philosophy",
    valueType: "work",
    ref: "2.124",
    grc: "Περὶ φιλοσοφίας",
    certainty: "asserted",
  },
  {
    id: "simmias-wrote-of-the-soul",
    subject: "Simmias",
    property: "wrote",
    value: "Of the Soul",
    valueType: "work",
    ref: "2.124",
    grc: "Περὶ ψυχῆς",
    certainty: "asserted",
  },
  {
    id: "simmias-wrote-on-friendship",
    subject: "Simmias",
    property: "wrote",
    value: "On Friendship",
    valueType: "work",
    ref: "2.124",
    grc: "Περὶ φίλου",
    certainty: "asserted",
  },
  {
    id: "simmias-wrote-on-music",
    subject: "Simmias",
    property: "wrote",
    value: "On Music",
    valueType: "work",
    ref: "2.124",
    grc: "Περὶ μουσικῆς",
    certainty: "asserted",
  },
  {
    id: "simmias-wrote-of-truth",
    subject: "Simmias",
    property: "wrote",
    value: "Of Truth",
    valueType: "work",
    ref: "2.124",
    grc: "Περὶ ἀληθείας",
    certainty: "asserted",
  },
  // -------------------------------------------------------------- Cebes
  {
    id: "cebes-birthplace-thebes",
    subject: "Cebes",
    property: "birthPlace",
    value: "Thebes",
    valueType: "place",
    ref: "2.125",
    grc: "Κέβης ὁ Θηβαῖος",
    certainty: "asserted",
  },
  {
    id: "cebes-wrote-tablet",
    subject: "Cebes",
    property: "wrote",
    value: "The Tablet",
    valueType: "work",
    ref: "2.125",
    grc: "Πίναξ",
    certainty: "asserted",
  },
  {
    id: "cebes-wrote-seventh-day",
    subject: "Cebes",
    property: "wrote",
    value: "The Seventh Day",
    valueType: "work",
    ref: "2.125",
    grc: "Ἑβδόμη",
    certainty: "asserted",
  },
  {
    id: "cebes-wrote-phrynichus",
    subject: "Cebes",
    property: "wrote",
    value: "Phrynichus",
    valueType: "work",
    ref: "2.125",
    grc: "Φρύνιχος.",
    certainty: "asserted",
  },
  // ---------------------------------------------------- Menedemus of Eretria
  {
    id: "menedemus-parentage",
    subject: "Menedemus of Eretria",
    property: "parentage",
    value: "Son of Clisthenes, of the clan called the Theopropidae, of good family though a poor builder",
    valueType: "literal",
    ref: "2.125",
    grc: "Κλεισθένους τοῦ τῶν Θεοπροπιδῶν καλουμένων υἱός, ἀνδρὸς εὐγενοῦς μέν, ἀρχιτέκτονος δὲ καὶ πένητος",
    certainty: "asserted",
  },
  {
    id: "menedemus-birthplace-eretria",
    subject: "Menedemus of Eretria",
    property: "birthPlace",
    value: "Eretria",
    valueType: "place",
    ref: "2.126",
    grc: "Ἀσκληπιάδου δὲ τοῦ Φλιασίου περισπάσαντος αὐτὸν ἐγένετο ἐν Μεγάροις παρὰ Στίλπωνι, οὗπερ ἀμφότεροι διήκουσαν",
    certainty: "asserted",
  },
  {
    id: "menedemus-teacher-stilpo",
    subject: "Menedemus of Eretria",
    property: "studiedUnder",
    value: "Stilpo",
    valueType: "philosopher",
    ref: "2.126",
    grc: "Ἀσκληπιάδου δὲ τοῦ Φλιασίου περισπάσαντος αὐτὸν ἐγένετο ἐν Μεγάροις παρὰ Στίλπωνι, οὗπερ ἀμφότεροι διήκουσαν",
    certainty: "asserted",
    note: "He lived at Megara with Stilpo, whose lectures he attended.",
  },
  {
    id: "menedemus-affiliation-eretrian",
    subject: "Menedemus of Eretria",
    property: "affiliatedWith",
    value: "Eretrian",
    valueType: "school",
    ref: "2.126",
    grc: "Ἀσκληπιάδου δὲ τοῦ Φλιασίου περισπάσαντος αὐτὸν ἐγένετο ἐν Μεγάροις παρὰ Στίλπωνι, οὗπερ ἀμφότεροι διήκουσαν",
    certainty: "asserted",
    note: "The Elian school was renamed Eretrian from the city to which he belonged.",
  },
  {
    id: "menedemus-doctrine-propositions",
    subject: "Menedemus of Eretria",
    property: "heldDoctrine",
    value: "He admitted only simple affirmative propositions, converting negatives into affirmatives and rejecting hypothetical and complex propositions",
    valueType: "doctrine",
    ref: "2.135",
    grc: "Ἀνῄρει δέ, φασί, καὶ τὰ ἀποφατικὰ τῶν ἀξιωμάτων, καταφατικὰ τιθείς· καὶ τούτων τὰ ἁπλᾶ προσδεχόμενος τὰ οὐχ ἁπλᾶ ἀνῄρει, λέγω δὲ συνημμένα καὶ συμπεπλεγμένα.",
    certainty: "asserted",
    note: "Heraclides says that in doctrine he was a Platonist, yet he made sport of dialectic.",
  },
  {
    id: "menedemus-writings-none",
    subject: "Menedemus of Eretria",
    property: "writings",
    value: "Never wrote or composed anything, and so never held firmly by any doctrine",
    valueType: "literal",
    ref: "2.136",
    grc: "Καί ποτέ τινος ἀκούσας ὡς μέγιστον ἀγαθὸν εἴη τὸ πάντων ἐπιτυγχάνειν ὧν τις ἐπιθυμεῖ, εἶπε, πολὺ δὲ μεῖζον τὸ ἐπιθυμεῖν ὧν δεῖ",
    certainty: "reported",
    accordingTo: "Antigonus of Carystus",
  },
  {
    id: "menedemus-death-starvation",
    subject: "Menedemus of Eretria",
    property: "mannerOfDeath",
    value: "In despair put an end to his life by abstaining from food for seven days",
    valueType: "literal",
    ref: "2.143",
    grc: "τοῦ δὲ μὴ εἴκοντος ὑπʼ ἀθυμίας ἀσιτήσαντα ἑπτὰ ἡμέρας τὸν βίον μεταλλάξαι.",
    certainty: "reported",
    accordingTo: "Heraclides",
    conflictsWith: ["menedemus-death-broken-heart"],
  },
  {
    id: "menedemus-death-broken-heart",
    subject: "Menedemus of Eretria",
    property: "mannerOfDeath",
    value: "Withdrew to the court of Antigonus, where he died of a broken heart",
    valueType: "literal",
    ref: "2.142",
    grc: "τήν τε γυναῖκα καὶ τὰς θυγατέρας παραλαβὼν πρὸς Ἀντίγονον ἐλθὼν ἀθυμίᾳ τὸν βίον κατέστρεψε.",
    certainty: "reported",
    accordingTo: "Hermippus",
    conflictsWith: ["menedemus-death-starvation"],
  },
];
