/**
 * Curated claims from Book 8 of Diogenes Laertius' Lives, cited to
 * Hicks section ids (book.section). See kg-claims.ts for the model and
 * curation rules. Source-internal: every claim cites a D.L. passage.
 */
import type { KgClaim } from "../kg-claims";

export const BOOK8_CLAIMS: KgClaim[] = [
  // ---------------------------------------------------------------- Pythagoras
  {
    id: "pythagoras-parentage-mnesarchus",
    subject: "Pythagoras",
    property: "parentage",
    value: "Son of Mnesarchus the gem-engraver",
    valueType: "literal",
    ref: "8.1",
    grc: "ἔνιοι δʼ υἱὸν μὲν εἶναι Μαρμάκου τοῦ Ἱππάσου τοῦ Εὐθύφρονος τοῦ Κλεωνύμου φυγάδος ἐκ Φλιοῦντος, οἰκεῖν δʼ ἐν Σάμῳ τὸν Μάρμακον, ὅθεν Σάμιον τὸν Πυθαγόραν λέγεσθαι·",
    certainty: "asserted",
  },
  {
    id: "pythagoras-origin-samian",
    subject: "Pythagoras",
    property: "parentage",
    value: "A Samian by descent",
    valueType: "literal",
    ref: "8.1",
    grc: "ἔνιοι δʼ υἱὸν μὲν εἶναι Μαρμάκου τοῦ Ἱππάσου τοῦ Εὐθύφρονος τοῦ Κλεωνύμου φυγάδος ἐκ Φλιοῦντος, οἰκεῖν δʼ ἐν Σάμῳ τὸν Μάρμακον, ὅθεν Σάμιον τὸν Πυθαγόραν λέγεσθαι·",
    certainty: "reported",
    accordingTo: "Hermippus",
    conflictsWith: ["pythagoras-origin-tyrrhenian"],
  },
  {
    id: "pythagoras-origin-tyrrhenian",
    subject: "Pythagoras",
    property: "parentage",
    value: "A Tyrrhenian, from one of the islands the Athenians cleared of Tyrrhenians",
    valueType: "literal",
    ref: "8.1",
    grc: "ἔνιοι δʼ υἱὸν μὲν εἶναι Μαρμάκου τοῦ Ἱππάσου τοῦ Εὐθύφρονος τοῦ Κλεωνύμου φυγάδος ἐκ Φλιοῦντος, οἰκεῖν δʼ ἐν Σάμῳ τὸν Μάρμακον, ὅθεν Σάμιον τὸν Πυθαγόραν λέγεσθαι·",
    certainty: "reported",
    accordingTo: "Aristoxenus",
    conflictsWith: ["pythagoras-origin-samian"],
  },
  {
    id: "pythagoras-birthplace-samos",
    subject: "Pythagoras",
    property: "birthPlace",
    value: "Samos",
    valueType: "place",
    ref: "8.1",
    grc: "Ἐπειδὴ δὲ τὴν Ἰωνικὴν φιλοσοφίαν τὴν ἀπὸ Θαλοῦ καὶ τοὺς ἐν ταύτῃ διαγενομένους ἄνδρας ἀξιολόγους διεληλύθαμεν, φέρε καὶ περὶ τῆς Ἰταλικῆς διαλάβωμεν, ἧς ἦρξε Πυθαγόρας Μνησάρχου δακτυλιογλύφου, ὥς φησιν Ἕρμιππος, Σάμιος ἤ, ὡς Ἀριστόξενος, Τυρρηνὸς ἀπὸ μιᾶς τῶν νήσων ἃς ἔσχον Ἀθηναῖοι Τυρρηνοὺς ἐκβαλόντες",
    certainty: "reported",
  },
  {
    id: "pythagoras-studied-pherecydes",
    subject: "Pythagoras",
    property: "studiedUnder",
    value: "Pherecydes",
    valueType: "philosopher",
    ref: "8.2",
    grc: "ἤκουσε μέν, καθὰ προείρηται, Φερεκύδου τοῦ Συρίου",
    certainty: "asserted",
    note: "Pherecydes of Syros.",
  },
  {
    id: "pythagoras-studied-hermodamas",
    subject: "Pythagoras",
    property: "studiedUnder",
    value: "Hermodamas",
    valueType: "person",
    ref: "8.2",
    grc: "ἤκουσεν Ἑρμοδάμαντος τοῦ ἀπογόνου Κρεωφύλου",
    certainty: "asserted",
    note: "Creophylus's descendant, at Samos.",
  },
  {
    id: "pythagoras-studied-themistoclea",
    subject: "Pythagoras",
    property: "studiedUnder",
    value: "Themistoclea",
    valueType: "person",
    ref: "8.8",
    grc: "φησὶ δὲ καὶ Ἀριστόξενος τὰ πλεῖστα τῶν ἠθικῶν δογμάτων λαβεῖν τὸν Πυθαγόραν παρὰ Θεμιστοκλείας τῆς ἐν Δελφοῖς",
    certainty: "reported",
    accordingTo: "Aristoxenus",
    note: "The Delphic priestess, from whom he got most of his moral doctrines.",
  },
  {
    id: "pythagoras-traveled-egypt",
    subject: "Pythagoras",
    property: "traveledTo",
    value: "Egypt",
    valueType: "place",
    ref: "8.3",
    grc: "ἐγένετʼ οὖν ἐν Αἰγύπτῳ, ὁπηνίκα καὶ Πολυκράτης αὐτὸν Ἀμάσιδι συνέστησε διʼ ἐπιστολῆς",
    certainty: "asserted",
    note: "Also journeyed among the Chaldaeans and Magi, and to Crete.",
  },
  {
    id: "pythagoras-lived-croton",
    subject: "Pythagoras",
    property: "livedIn",
    value: "Croton",
    valueType: "place",
    ref: "8.3",
    grc: "ἐγένετʼ οὖν ἐν Αἰγύπτῳ, ὁπηνίκα καὶ Πολυκράτης αὐτὸν Ἀμάσιδι συνέστησε διʼ ἐπιστολῆς",
    certainty: "asserted",
    note: "In Italy, where he laid down a constitution for the Italian Greeks.",
  },
  {
    id: "pythagoras-writings-none",
    subject: "Pythagoras",
    property: "writings",
    value: "Some insist, absurdly, that he left no writings whatever",
    valueType: "literal",
    ref: "8.6",
    grc: "γέγραπται δὲ τῷ Πυθαγόρᾳ συγγράμματα τρία, Παιδευτικόν, Πολιτικόν, Φυσικόν·",
    certainty: "reported",
    conflictsWith: [
      "pythagoras-wrote-education",
      "pythagoras-wrote-statesmanship",
      "pythagoras-wrote-nature",
    ],
  },
  {
    id: "pythagoras-wrote-education",
    subject: "Pythagoras",
    property: "wrote",
    value: "On Education",
    valueType: "work",
    ref: "8.6",
    grc: "Παιδευτικόν,",
    certainty: "asserted",
    note: "One of the three books D.L. says Pythagoras in fact wrote.",
    conflictsWith: ["pythagoras-writings-none"],
  },
  {
    id: "pythagoras-wrote-statesmanship",
    subject: "Pythagoras",
    property: "wrote",
    value: "On Statesmanship",
    valueType: "work",
    ref: "8.6",
    grc: "Πολιτικόν,",
    certainty: "asserted",
    conflictsWith: ["pythagoras-writings-none"],
  },
  {
    id: "pythagoras-wrote-nature",
    subject: "Pythagoras",
    property: "wrote",
    value: "On Nature",
    valueType: "work",
    ref: "8.6",
    grc: "οὕτω δʼ εἶπεν, ἐπειδήπερ ἐναρχόμενος ὁ Πυθαγόρας τοῦ Φυσικοῦ συγγράμματος λέγει ὧδε· οὐ μὰ τὸν ἀέρα, τὸν ἀναπνέω, οὐ μὰ τὸ ὕδωρ, τὸ πίνω, οὔ κοτʼ οἴσω ψόγον περὶ τοῦ λόγου τοῦδε",
    certainty: "asserted",
    conflictsWith: ["pythagoras-writings-none"],
  },
  {
    id: "pythagoras-doctrine-transmigration",
    subject: "Pythagoras",
    property: "heldDoctrine",
    value: "The soul is immortal and passes at death into other living creatures",
    valueType: "doctrine",
    ref: "8.14",
    grc: "Πρῶτόν τέ φασι τοῦτον ἀποφῆναι τὴν ψυχὴν κύκολον ἀνάγκης ἀμείβουσαν ἄλλοτʼ ἄλλοις ἐνδεῖσθαι ζῴοις·",
    certainty: "asserted",
    greek: "μετεμψύχωσις",
    note: "He was the first to declare that the soul goes on a round ordained of necessity.",
  },
  {
    id: "pythagoras-doctrine-friends-common",
    subject: "Pythagoras",
    property: "heldDoctrine",
    value: "Friends have all things in common",
    valueType: "doctrine",
    ref: "8.10",
    grc: "εἶπέ τε πρῶτος, ὥς φησι Τίμαιος, κοινὰ τὰ φίλων εἶναι καὶ φιλίαν ἰσότητα. καὶ αὐτοῦ οἱ μαθηταὶ κατετίθεντο τὰς οὐσίας εἰς ἕν [ποιούμενοι].",
    certainty: "reported",
    accordingTo: "Timaeus",
  },
  {
    id: "pythagoras-doctrine-friendship-equality",
    subject: "Pythagoras",
    property: "heldDoctrine",
    value: "Friendship is equality",
    valueType: "doctrine",
    ref: "8.10",
    grc: "εἶπέ τε πρῶτος, ὥς φησι Τίμαιος, κοινὰ τὰ φίλων εἶναι καὶ φιλίαν ἰσότητα.",
    certainty: "reported",
    accordingTo: "Timaeus",
  },
  {
    id: "pythagoras-doctrine-beans",
    subject: "Pythagoras",
    property: "heldDoctrine",
    value: "Abstinence from beans",
    valueType: "doctrine",
    ref: "8.19",
    grc: "Παντὸς δὲ μᾶλλον ἀπηγόρευε μήτʼ ἐρυθῖνον ἐσθίειν μήτε μελάνουρον, καρδίας τʼ ἀπέχεσθαι καὶ κυάμων·",
    certainty: "asserted",
  },
  {
    id: "pythagoras-doctrine-abstinence-animals",
    subject: "Pythagoras",
    property: "heldDoctrine",
    value: "Not to kill or eat animals that share with us the privilege of having a soul",
    valueType: "doctrine",
    ref: "8.13",
    grc: "τοῦτον γὰρ καὶ τὸ φονεύειν ἀπαγορεύειν, μὴ ὅτι γεύεσθαι τῶν ζῴων κοινὸν δίκαιον ἡμῖν ἐχόντων ψυχῆς.",
    certainty: "asserted",
  },
  {
    id: "pythagoras-doctrine-monad",
    subject: "Pythagoras",
    property: "heldDoctrine",
    value: "The principle of all things is the monad; from it spring numbers, points, lines, figures and bodies",
    valueType: "doctrine",
    ref: "8.25",
    grc: "ἀρχὴν μὲν ἁπάντων μονάδα· ἐκ δὲ τῆς μονάδος ἀόριστον δυάδα ὡς ἂν ὕλην τῇ μονάδι αἰτίῳ ὄντι ὑποστῆναι· ἐκ δὲ τῆς μονάδος καὶ τῆς ἀορίστου δυάδος τοὺς ἀριθμούς· ἐκ δὲ τῶν ἀριθμῶν τὰ σημεῖα· ἐκ δὲ τούτων τὰς γραμμάς, ἐξ ὧν τὰ ἐπίπεδα σχήματα·",
    certainty: "reported",
    accordingTo: "Alexander",
    sourceWork: "Successions of Philosophers",
    greek: "μονάς",
    note: "From the Pythagorean memoirs, per Alexander in his Successions.",
  },
  {
    id: "pythagoras-doctrine-virtue-harmony",
    subject: "Pythagoras",
    property: "heldDoctrine",
    value: "Virtue is harmony, and so are health and all good and God himself",
    valueType: "doctrine",
    ref: "8.33",
    grc: "τήν τʼ ἀρετὴν ἁρμονίαν εἶναι καὶ τὴν ὑγίειαν καὶ τὸ ἀγαθὸν ἅπαν καὶ τὸν θεόν· διὸ καὶ καθʼ ἁρμονίαν συνεστάναι τὰ ὅλα.",
    certainty: "reported",
    greek: "ἁρμονία",
    note: "From the Pythagorean memoirs.",
  },
  {
    id: "pythagoras-floruit",
    subject: "Pythagoras",
    property: "birthDate",
    value: "Flourished in the 60th Olympiad (540/537 BCE)",
    valueType: "literal",
    ref: "8.45",
    grc: "Ἤκμαζε δὲ καὶ κατὰ τὴν ἑξηκοστὴν Ὀλυμπιάδα, καὶ αὐτοῦ τὸ σύστημα διέμενε μέχρι γενεῶν ἐννέα ἢ καὶ δέκα·",
    certainty: "asserted",
  },
  {
    id: "pythagoras-death-age-eighty",
    subject: "Pythagoras",
    property: "deathDate",
    value: "Died at the age of eighty",
    valueType: "literal",
    ref: "8.44",
    grc: "Ὁ δʼ οὖν Πυθαγόρας, ὡς μὲν Ἡρακλείδης φησὶν ὁ τοῦ Σαραπίωνος, ὀγδοηκοντούτης ἐτελεύτα, κατὰ τὴν ἰδίαν ὑπογραφὴν τῶν ἡλικιῶν",
    certainty: "reported",
    accordingTo: "Heraclides",
    note: "Heraclides the son of Serapion; agrees with Pythagoras's own account of the life of man.",
    conflictsWith: ["pythagoras-death-age-ninety"],
  },
  {
    id: "pythagoras-death-age-ninety",
    subject: "Pythagoras",
    property: "deathDate",
    value: "Died at the age of ninety",
    valueType: "literal",
    ref: "8.44",
    grc: "Ὁ δʼ οὖν Πυθαγόρας, ὡς μὲν Ἡρακλείδης φησὶν ὁ τοῦ Σαραπίωνος, ὀγδοηκοντούτης ἐτελεύτα, κατὰ τὴν ἰδίαν ὑπογραφὴν τῶν ἡλικιῶν",
    certainty: "reported",
    note: "So most authorities.",
    conflictsWith: ["pythagoras-death-age-eighty"],
  },
  {
    id: "pythagoras-death-manner",
    subject: "Pythagoras",
    property: "mannerOfDeath",
    value:
      "Caught fleeing when the house of Milo was set ablaze; halted at a field of beans he would not cross, and his pursuers cut his throat",
    valueType: "literal",
    ref: "8.39",
    grc: "τὸν δὴ Πυθαγόραν καταληφθῆναι διεξιόντα· καὶ πρός τινι χωρίῳ γενόμενος πλήρει κυάμων, ἵνα [αὐτόθι] ἔστη, εἰπὼν ἁλῶναι ἂν μᾶλλον ἢ πατῆσαι [ἀναιρεθῆναι δὲ κρεῖττον ἢ λαλῆσαι]· καὶ ὧδε πρὸς τῶν διωκόντων ἀποσφαγῆναι.",
    certainty: "asserted",
    note: "Some say the fire was set out of jealousy, others by the Crotonians fearing a tyranny.",
  },

  // ---------------------------------------------------------------- Empedocles
  {
    id: "empedocles-parentage-meton",
    subject: "Empedocles",
    property: "parentage",
    value: "Son of Meton and grandson of Empedocles, of an illustrious family",
    valueType: "literal",
    ref: "8.51",
    grc: "Ἐμπεδοκλῆς, ὥς φησιν Ἱππόβοτος, Μέτωνος ἦν υἱὸς τοῦ Ἐμπεδοκλέους, Ἀκραγαντῖνος",
    certainty: "reported",
    accordingTo: "Hippobotus",
    conflictsWith: ["empedocles-parentage-exaenetus", "empedocles-parentage-archinomus"],
  },
  {
    id: "empedocles-parentage-exaenetus",
    subject: "Empedocles",
    property: "parentage",
    value: "Son of Exaenetus, and himself left a son named Exaenetus",
    valueType: "literal",
    ref: "8.53",
    grc: "Ἐμπεδοκλῆς υἱὸς μὲν ἦν Ἐξαινέτου, κατέλιπε δὲ καὶ αὐτὸς υἱὸν Ἐξαίνετον",
    certainty: "reported",
    accordingTo: "Satyrus",
    conflictsWith: ["empedocles-parentage-meton", "empedocles-parentage-archinomus"],
  },
  {
    id: "empedocles-parentage-archinomus",
    subject: "Empedocles",
    property: "parentage",
    value: "Son of Archinomus",
    valueType: "literal",
    ref: "8.53",
    grc: "τὸν Ἐμπεδοκλέα Ἀρχινόμου εἶναι υἱόν",
    certainty: "reported",
    accordingTo: "Telauges",
    conflictsWith: ["empedocles-parentage-meton", "empedocles-parentage-exaenetus"],
  },
  {
    id: "empedocles-birthplace-agrigentum",
    subject: "Empedocles",
    property: "birthPlace",
    value: "Agrigentum (Acragas)",
    valueType: "place",
    ref: "8.51",
    grc: "Ἐμπεδοκλῆς, ὥς φησιν Ἱππόβοτος, Μέτωνος ἦν υἱὸς τοῦ Ἐμπεδοκλέους, Ἀκραγαντῖνος",
    certainty: "asserted",
    note: "He testifies to this himself at the beginning of his Purifications.",
  },
  {
    id: "empedocles-studied-pythagoras",
    subject: "Empedocles",
    property: "studiedUnder",
    value: "Pythagoras",
    valueType: "philosopher",
    ref: "8.54",
    grc: "Ὅτι δʼ ἦν Ἀκραγαντῖνος ἐκ Σικελίας, αὐτὸς ἐναρχόμενος τῶν Καθαρμῶν φησιν",
    certainty: "reported",
    accordingTo: "Timaeus",
    conflictsWith: [
      "empedocles-studied-parmenides",
      "empedocles-studied-xenophanes",
      "empedocles-studied-anaxagoras",
    ],
  },
  {
    id: "empedocles-studied-parmenides",
    subject: "Empedocles",
    property: "studiedUnder",
    value: "Parmenides",
    valueType: "philosopher",
    ref: "8.55",
    grc: "Θεόφραστος Παρμενίδου φησὶ ζηλωτὴν αὐτὸν γενέσθαι",
    certainty: "reported",
    accordingTo: "Theophrastus",
    note: "An admirer of Parmenides, imitating him in verse.",
    conflictsWith: [
      "empedocles-studied-pythagoras",
      "empedocles-studied-xenophanes",
      "empedocles-studied-anaxagoras",
    ],
  },
  {
    id: "empedocles-studied-xenophanes",
    subject: "Empedocles",
    property: "studiedUnder",
    value: "Xenophanes",
    valueType: "philosopher",
    ref: "8.56",
    grc: "Ξενοφάνους δὲ γεγονέναι ζηλωτήν, ᾧ καὶ συνδιατρῖψαι",
    certainty: "reported",
    accordingTo: "Hermippus",
    conflictsWith: [
      "empedocles-studied-pythagoras",
      "empedocles-studied-parmenides",
      "empedocles-studied-anaxagoras",
    ],
  },
  {
    id: "empedocles-studied-anaxagoras",
    subject: "Empedocles",
    property: "studiedUnder",
    value: "Anaxagoras",
    valueType: "philosopher",
    ref: "8.56",
    grc: "τὸν δὲ Ἀναξαγόρου διακοῦσαι",
    certainty: "reported",
    accordingTo: "Alcidamas",
    note: "Alcidamas makes him pupil of Parmenides, then of Anaxagoras and Pythagoras.",
    conflictsWith: [
      "empedocles-studied-pythagoras",
      "empedocles-studied-parmenides",
      "empedocles-studied-xenophanes",
    ],
  },
  {
    id: "empedocles-deathplace-peloponnesus",
    subject: "Empedocles",
    property: "deathPlace",
    value: "Peloponnesus",
    valueType: "place",
    ref: "8.71",
    grc: "τετελεύτηκεν οὖν ἐν Πελοποννήσῳ.",
    certainty: "reported",
    accordingTo: "Timaeus",
    note: "Timaeus says he left Sicily for Peloponnesus and never returned.",
  },
  {
    id: "empedocles-death-etna",
    subject: "Empedocles",
    property: "mannerOfDeath",
    value: "Leapt into the fiery craters of Etna to confirm the report that he had become a god",
    valueType: "literal",
    ref: "8.69",
    grc: "Ἱππόβοτος δέ φησιν ἐξαναστάντα αὐτὸν ὡδευκέναι ὡς ἐπὶ τὴν Αἴτνην, εἶτα παραγενόμενον ἐπὶ τοὺς κρατῆρας τοῦ πυρὸς ἐναλέσθαι καὶ ἀφανισθῆναι, βουλόμενον τὴν περὶ αὑτοῦ φήμην βεβαιῶσαι ὅτι γεγόνοι θεός",
    certainty: "reported",
    accordingTo: "Hippobotus",
    note: "The truth known because a bronze slipper of his was cast up in the flames.",
    conflictsWith: [
      "empedocles-death-ascension",
      "empedocles-death-carriage",
      "empedocles-death-hanged",
      "empedocles-death-drowned",
      "empedocles-death-peloponnesus",
    ],
  },
  {
    id: "empedocles-death-ascension",
    subject: "Empedocles",
    property: "mannerOfDeath",
    value: "Vanished after a loud voice called him in the night and a light appeared in the heavens; taken up as a god",
    valueType: "literal",
    ref: "8.68",
    grc: "εἷς τις ἔφη μέσων νυκτῶν φωνῆς ὑπερμεγέθους ἀκοῦσαι προσκαλουμένης Ἐμπεδοκλέα, εἶτʼ ἐξαναστὰς ἑωρακέναι φῶς οὐράνιον καὶ λαμπάδων φέγγος, ἄλλο δὲ μηδέν",
    certainty: "reported",
    accordingTo: "Heraclides",
    conflictsWith: [
      "empedocles-death-etna",
      "empedocles-death-carriage",
      "empedocles-death-hanged",
      "empedocles-death-drowned",
      "empedocles-death-peloponnesus",
    ],
  },
  {
    id: "empedocles-death-carriage",
    subject: "Empedocles",
    property: "mannerOfDeath",
    value: "Fell from a carriage on the way to Messene, broke his thigh, and died of the ensuing illness at seventy-seven",
    valueType: "literal",
    ref: "8.73",
    grc: "ὕστερον δὲ διά τινα πανήγυριν πορευόμενον ἐπʼ ἀμάξης ὡς εἰς Μεσσήνην πεσεῖν καὶ τὸν μηρὸν κλάσαι· νοσήσαντα δʼ ἐκ τούτου τελευτῆσαι ἐτῶν ἑπτὰ καὶ ἑβδομήκοντα.",
    certainty: "reported",
    accordingTo: "Favorinus",
    conflictsWith: [
      "empedocles-death-etna",
      "empedocles-death-ascension",
      "empedocles-death-hanged",
      "empedocles-death-drowned",
      "empedocles-death-peloponnesus",
    ],
  },
  {
    id: "empedocles-death-hanged",
    subject: "Empedocles",
    property: "mannerOfDeath",
    value: "Hanged himself from a tall cornel-tree",
    valueType: "literal",
    ref: "8.74",
    grc: "Δημήτριος δʼ ὁ Τροιζήνιος ἐν τῷ Κατὰ σοφιστῶν βιβλίῳ φησὶν αὐτὸν καθʼ Ὅμηρον ἁψάμενον βρόχον αἰπὺν ἀφʼ ὑψηλοῖο κρανείης αὐχένʼ ἀποκρεμάσαι, ψυχὴν δʼ Ἄϊδόσδε κατελθεῖν.",
    certainty: "reported",
    accordingTo: "Demetrius of Troezen",
    sourceWork: "Against the Sophists",
    conflictsWith: [
      "empedocles-death-etna",
      "empedocles-death-ascension",
      "empedocles-death-carriage",
      "empedocles-death-drowned",
      "empedocles-death-peloponnesus",
    ],
  },
  {
    id: "empedocles-death-drowned",
    subject: "Empedocles",
    property: "mannerOfDeath",
    value: "By reason of his age slipped into the sea and was drowned",
    valueType: "literal",
    ref: "8.74",
    grc: "λέγεται αὐτὸν εἰς θάλατταν ὑπὸ γήρως ὀλισθόντα τελευτῆσαι.",
    certainty: "reported",
    accordingTo: "Telauges",
    conflictsWith: [
      "empedocles-death-etna",
      "empedocles-death-ascension",
      "empedocles-death-carriage",
      "empedocles-death-hanged",
      "empedocles-death-peloponnesus",
    ],
  },
  {
    id: "empedocles-death-peloponnesus",
    subject: "Empedocles",
    property: "mannerOfDeath",
    value: "Died in Peloponnesus; the manner of his death is unknown",
    valueType: "literal",
    ref: "8.71",
    grc: "ἐξεχώρησεν εἰς Πελοπόννησον καὶ τὸ σύνολον οὐκ ἐπανῆλθεν· ὅθεν αὐτοῦ καὶ τὴν τελευτὴν ἄδηλον εἶναι.",
    certainty: "reported",
    accordingTo: "Timaeus",
    conflictsWith: [
      "empedocles-death-etna",
      "empedocles-death-ascension",
      "empedocles-death-carriage",
      "empedocles-death-hanged",
      "empedocles-death-drowned",
    ],
  },
  {
    id: "empedocles-death-age-sixty",
    subject: "Empedocles",
    property: "deathDate",
    value: "Died at the age of sixty",
    valueType: "literal",
    ref: "8.74",
    grc: "φησὶ γὰρ ἐκεῖνος ἑξήκοντʼ ἐτῶν αὐτὸν τελευτῆσαι",
    certainty: "reported",
    accordingTo: "Aristotle",
    conflictsWith: ["empedocles-death-age-109"],
  },
  {
    id: "empedocles-death-age-109",
    subject: "Empedocles",
    property: "deathDate",
    value: "Died at the age of one hundred and nine",
    valueType: "literal",
    ref: "8.74",
    grc: "οἱ δὲ ἐννέα καὶ ἑκατόν",
    certainty: "reported",
    conflictsWith: ["empedocles-death-age-sixty"],
  },
  {
    id: "empedocles-floruit",
    subject: "Empedocles",
    property: "birthDate",
    value: "Flourished in the 84th Olympiad (444/441 BCE)",
    valueType: "literal",
    ref: "8.74",
    grc: "ἤκμαζε δὲ κατὰ τὴν τετάρτην καὶ ὀγδοηκοστὴν Ὀλυμπιάδα",
    certainty: "asserted",
  },
  {
    id: "empedocles-wrote-nature",
    subject: "Empedocles",
    property: "wrote",
    value: "On Nature",
    valueType: "work",
    ref: "8.77",
    grc: "Τὰ μὲν οὖν Περὶ φύσεως αὐτῷ καὶ οἱ Καθαρμοὶ εἰς ἔπη τείνουσι πεντακισχίλια, ὁ δὲ Ἰατρικὸς λόγος εἰς ἔπη ἑξακόσια",
    certainty: "asserted",
    note: "On Nature and Purifications together run to 5000 lines.",
  },
  {
    id: "empedocles-wrote-purifications",
    subject: "Empedocles",
    property: "wrote",
    value: "Purifications",
    valueType: "work",
    ref: "8.54",
    grc: "Ὅτι δʼ ἦν Ἀκραγαντῖνος ἐκ Σικελίας, αὐτὸς ἐναρχόμενος τῶν Καθαρμῶν φησιν",
    certainty: "asserted",
  },
  {
    id: "empedocles-wrote-medicine",
    subject: "Empedocles",
    property: "wrote",
    value: "Discourse on Medicine (600 lines)",
    valueType: "work",
    ref: "8.77",
    grc: "ὁ δὲ Ἰατρικὸς λόγος εἰς ἔπη ἑξακόσια",
    certainty: "asserted",
  },
  {
    id: "empedocles-wrote-xerxes",
    subject: "Empedocles",
    property: "wrote",
    value: "Poem on the invasion of Xerxes",
    valueType: "work",
    ref: "8.57",
    grc: "καὶ διότι γράψαντος αὐτοῦ καὶ ἄλλα ποιήματα τήν τε τοῦ Ξέρξου διάβασιν καὶ προοίμιον εἰς Ἀπόλλωνα,",
    certainty: "reported",
    accordingTo: "Aristotle",
    note: "Deliberately burnt, being unfinished.",
  },
  {
    id: "empedocles-wrote-apollo-hymn",
    subject: "Empedocles",
    property: "wrote",
    value: "Hymn to Apollo",
    valueType: "work",
    ref: "8.57",
    grc: "ἐν δὲ τῷ Περὶ ποιητῶν φησιν ὅτι καὶ Ὁμηρικὸς ὁ Ἐμπεδοκλῆς καὶ δεινὸς περὶ τὴν φράσιν γέγονεν, μεταφορητικός τε ὢν καὶ τοῖς ἄλλοις τοῖς περὶ ποιητικὴν ἐπιτεύγμασι χρώμενος· καὶ διότι γράψαντος αὐτοῦ καὶ ἄλλα ποιήματα τήν τε τοῦ Ξέρξου διάβασιν καὶ προοίμιον εἰς Ἀπόλλωνα, ταῦθʼ ὔστερον κατέκαυσεν ἀδελφή τις αὐτοῦ (ἢ θυγάτηρ, ὥς φησιν Ἱερώνυμος), τὸ μὲν προοίμιον ἄκουσα, τὰ δὲ Περσικὰ βουληθεῖσα διὰ τὸ ἀτελείωτα εἶναι.",
    certainty: "reported",
    accordingTo: "Aristotle",
    note: "Burnt unintentionally by a sister of his (or, according to Hieronymus, his daughter).",
  },
  {
    id: "empedocles-doctrine-elements",
    subject: "Empedocles",
    property: "heldDoctrine",
    value: "There are four elements - fire, water, earth and air - united by Love and separated by Strife",
    valueType: "doctrine",
    ref: "8.76",
    grc: "στοιχεῖα μὲν εἶναι τέτταρα, πῦρ, ὕδωρ, γῆν, ἀέρα· Φιλίαν θʼ ᾗ συγκρίνεται καὶ Νεῖκος ᾧ διακρίνεται.",
    certainty: "asserted",
    greek: "φιλότης καὶ νεῖκος",
  },
  {
    id: "empedocles-doctrine-transmigration",
    subject: "Empedocles",
    property: "heldDoctrine",
    value: "The soul assumes all the various forms of animals and plants",
    valueType: "doctrine",
    ref: "8.77",
    grc: "καὶ τὴν ψυχὴν παντοῖα εἴδη ζῴων καὶ φυτῶν ἐνδύεσθαι· φησὶ γοῦν· ἤδη γάρ ποτʼ ἐγὼ γενόμην κοῦρός τε κόρη τε θάμνος τʼ οἰωνός τε καὶ ἔξαλος ἔμπυρος ἰχθύς.",
    certainty: "asserted",
  },

  // ---------------------------------------------------------------- Epicharmus
  {
    id: "epicharmus-parentage-helothales",
    subject: "Epicharmus",
    property: "parentage",
    value: "Son of Helothales, of Cos",
    valueType: "literal",
    ref: "8.78",
    grc: "εἴ τι παραλλάσσει φαέθων μέγας ἅλιος ἄστρων καὶ πόντος ποταμῶν μείζονʼ ἔχει δύναμιν, φαμὶ τοσοῦτον ἐγὼ σοφίᾳ προέχειν Ἐπίχαρμον, ὃν πατρὶς ἐστεφάνωσʼ ἅδε Συρακοσίων",
    certainty: "asserted",
  },
  {
    id: "epicharmus-studied-pythagoras",
    subject: "Epicharmus",
    property: "studiedUnder",
    value: "Pythagoras",
    valueType: "philosopher",
    ref: "8.78",
    grc: "καὶ οὗτος ἤκουσε Πυθαγόρου",
    certainty: "asserted",
  },
  {
    id: "epicharmus-lived-syracuse",
    subject: "Epicharmus",
    property: "livedIn",
    value: "Syracuse",
    valueType: "place",
    ref: "8.78",
    grc: "Ἐπίχαρμος Ἡλοθαλοῦς Κῷος",
    certainty: "asserted",
    note: "Sent as an infant to Megara in Sicily and thence to Syracuse.",
  },
  {
    id: "epicharmus-wrote-memoirs",
    subject: "Epicharmus",
    property: "wrote",
    value: "Memoirs containing physical, ethical and medical doctrines",
    valueType: "work",
    ref: "8.78",
    grc: "οὗτος ὑπομνήματα καταλέλοιπεν ἐν οἷς φυσιολογεῖ,",
    certainty: "asserted",
  },
  {
    id: "epicharmus-death-age-ninety",
    subject: "Epicharmus",
    property: "deathDate",
    value: "Died at the age of ninety",
    valueType: "literal",
    ref: "8.78",
    grc: "Ἐπίχαρμος Ἡλοθαλοῦς Κῷος",
    certainty: "asserted",
  },

  // ---------------------------------------------------------------- Archytas
  {
    id: "archytas-parentage-mnesagoras",
    subject: "Archytas",
    property: "parentage",
    value: "Son of Mnesagoras, or, per Aristoxenus, of Hestiaeus",
    valueType: "literal",
    ref: "8.79",
    grc: "Ἀρχύτας Μνησαγόρου Ταραντῖνος, ὡς δὲ Ἀριστόξενος, Ἑστιαίου, Πυθαγορικὸς καὶ αὐτός",
    certainty: "reported",
    accordingTo: "Aristoxenus",
  },
  {
    id: "archytas-birthplace-tarentum",
    subject: "Archytas",
    property: "birthPlace",
    value: "Tarentum",
    valueType: "place",
    ref: "8.79",
    grc: "Ἀρχύτας Μνησαγόρου Ταραντῖνος, ὡς δὲ Ἀριστόξενος, Ἑστιαίου, Πυθαγορικὸς καὶ αὐτός",
    certainty: "asserted",
  },
  {
    id: "archytas-affiliated-pythagorean",
    subject: "Archytas",
    property: "affiliatedWith",
    value: "Italian / Pythagorean",
    valueType: "school",
    ref: "8.79",
    grc: "Ἀρχύτας Μνησαγόρου Ταραντῖνος, ὡς δὲ Ἀριστόξενος, Ἑστιαίου, Πυθαγορικὸς καὶ αὐτός",
    certainty: "asserted",
    note: "Another of the Pythagoreans.",
  },
  {
    id: "archytas-doctrine-mechanics",
    subject: "Archytas",
    property: "heldDoctrine",
    value: "First to bring mechanics to a system by applying mathematical principles, and to employ mechanical motion in geometry",
    valueType: "doctrine",
    ref: "8.83",
    grc: "Οὗτος πρῶτος τὰ μηχανικὰ ταῖς μαθηματικαῖς προσχρησάμενος ἀρχαῖς μεθώδευσε καὶ πρῶτος κίνησιν ὀργανικὴν διαγράμματι γεωμετρικῷ προσήγαγε",
    certainty: "asserted",
  },

  // ---------------------------------------------------------------- Alcmaeon
  {
    id: "alcmaeon-parentage-pirithous",
    subject: "Alcmaeon",
    property: "parentage",
    value: "Son of Pirithous",
    valueType: "literal",
    ref: "8.83",
    grc: "Ἦν δὲ Πειρίθου υἱός, ὡς αὐτὸς ἐναρχόμενος τοῦ συγγράμματός φησιν",
    certainty: "asserted",
    note: "As he tells us at the beginning of his treatise.",
  },
  {
    id: "alcmaeon-birthplace-croton",
    subject: "Alcmaeon",
    property: "birthPlace",
    value: "Croton",
    valueType: "place",
    ref: "8.83",
    grc: "Ἀλκμαίων Κροτωνιάτης",
    certainty: "asserted",
  },
  {
    id: "alcmaeon-studied-pythagoras",
    subject: "Alcmaeon",
    property: "studiedUnder",
    value: "Pythagoras",
    valueType: "philosopher",
    ref: "8.83",
    grc: "καὶ οὗτος Πυθαγόρου διήκουσε",
    certainty: "asserted",
    note: "Another disciple of Pythagoras.",
  },
  {
    id: "alcmaeon-wrote-medicine",
    subject: "Alcmaeon",
    property: "wrote",
    value: "A physical treatise (chiefly on medicine)",
    valueType: "work",
    ref: "8.83",
    grc: "δοκεῖ δὲ πρῶτος φυσικὸν λόγον συγγεγραφέναι, καθά φησι Φαβωρῖνος ἐν Παντοδαπῇ ἱστορίᾳ",
    certainty: "reported",
    accordingTo: "Favorinus",
    note: "Thought to be the first to compile a physical treatise.",
  },
  {
    id: "alcmaeon-doctrine-soul-immortal",
    subject: "Alcmaeon",
    property: "heldDoctrine",
    value: "The soul is immortal and continuously in motion like the sun",
    valueType: "doctrine",
    ref: "8.83",
    grc: "ἔφη δὲ καὶ τὴν ψυχὴν ἀθάνατον, καὶ κινεῖσθαι αὐτὴν συνεχὲς ὡς τὸν ἥλιον",
    certainty: "asserted",
  },

  // ---------------------------------------------------------------- Hippasus
  {
    id: "hippasus-birthplace-metapontum",
    subject: "Hippasus",
    property: "birthPlace",
    value: "Metapontum",
    valueType: "place",
    ref: "8.84",
    grc: "Ἵππασος Μεταποντῖνος καὶ αὐτὸς Πυθαγορικός",
    certainty: "asserted",
  },
  {
    id: "hippasus-affiliated-pythagorean",
    subject: "Hippasus",
    property: "affiliatedWith",
    value: "Italian / Pythagorean",
    valueType: "school",
    ref: "8.84",
    grc: "Ἵππασος Μεταποντῖνος καὶ αὐτὸς Πυθαγορικός",
    certainty: "asserted",
    note: "Another Pythagorean.",
  },
  {
    id: "hippasus-writings-none",
    subject: "Hippasus",
    property: "writings",
    value: "Left nothing in writing",
    valueType: "literal",
    ref: "8.84",
    grc: "Ἵππασος Μεταποντῖνος καὶ αὐτὸς Πυθαγορικός",
    certainty: "reported",
    accordingTo: "Demetrius",
  },
  {
    id: "hippasus-doctrine-universe",
    subject: "Hippasus",
    property: "heldDoctrine",
    value: "The All is limited and ever in motion, changing within a definite time",
    valueType: "doctrine",
    ref: "8.84",
    grc: "ἔφη δὲ χρόνον ὡρισμένον εἶναι τῆς τοῦ κόσμου μεταβολῆς καὶ πεπερασμένον εἶναι τὸ πᾶν καὶ ἀεικίνητον.",
    certainty: "asserted",
  },

  // ---------------------------------------------------------------- Philolaus
  {
    id: "philolaus-birthplace-croton",
    subject: "Philolaus",
    property: "birthPlace",
    value: "Croton",
    valueType: "place",
    ref: "8.84",
    grc: "Φιλόλαος Κροτωνιάτης",
    certainty: "asserted",
  },
  {
    id: "philolaus-affiliated-pythagorean",
    subject: "Philolaus",
    property: "affiliatedWith",
    value: "Italian / Pythagorean",
    valueType: "school",
    ref: "8.84",
    grc: "Φιλόλαος Κροτωνιάτης Πυθαγορικός",
    certainty: "asserted",
  },
  {
    id: "philolaus-wrote-nature",
    subject: "Philolaus",
    property: "wrote",
    value: "On Nature (one book)",
    valueType: "work",
    ref: "8.85",
    grc: "Τοῦτόν φησι Δημήτριος ἐν Ὁμωνύμοις πρῶτον ἐκδοῦναι τῶν Πυθαγορικῶν 〈βιβλία καὶ ἐπιγράψαι〉〉 Περὶ φύσεως, ὧν ἀρχὴ ἥδε",
    certainty: "asserted",
    note: "The first to publish the Pythagorean treatises, per Demetrius; Plato bought it.",
  },
  {
    id: "philolaus-doctrine-necessity",
    subject: "Philolaus",
    property: "heldDoctrine",
    value: "All things are brought about by necessity and in harmonious inter-relation",
    valueType: "doctrine",
    ref: "8.85",
    grc: "Δοκεῖ δʼ αὐτῷ πάντα ἀνάγκῃ καὶ ἁρμονίᾳ γίνεσθαι.",
    certainty: "asserted",
  },
  {
    id: "philolaus-doctrine-earth-moves",
    subject: "Philolaus",
    property: "heldDoctrine",
    value: "The earth moves in a circle",
    valueType: "doctrine",
    ref: "8.85",
    grc: "καὶ τὴν γῆν κινεῖσθαι κατὰ κύκλον πρῶτον εἰπεῖν· οἱ δʼ Ἱκέταν 〈τὸν〉 Συρακόσιόν φασιν.",
    certainty: "asserted",
    note: "First to declare it, though some ascribe it to Hicetas of Syracuse.",
  },
  {
    id: "philolaus-death-tyranny",
    subject: "Philolaus",
    property: "mannerOfDeath",
    value: "Put to death by Croton on suspicion of aiming at a tyranny",
    valueType: "literal",
    ref: "8.84",
    grc: "ἐτελεύτα δὲ νομισθεὶς ἐπιτίθεσθαι τυραννίδι",
    certainty: "conjectured",
    note: "Inferred from D.L.'s epigram; the prose account is ambiguous.",
  },

  // ---------------------------------------------------------------- Eudoxus
  {
    id: "eudoxus-parentage-aeschines",
    subject: "Eudoxus",
    property: "parentage",
    value: "Son of Aeschines",
    valueType: "literal",
    ref: "8.86",
    grc: "Εὔδοξος Αἰσχίνου Κνίδιος, ἀστρολόγος, γεωμέτρης, ἰατρός, νομοθέτης",
    certainty: "asserted",
  },
  {
    id: "eudoxus-birthplace-cnidos",
    subject: "Eudoxus",
    property: "birthPlace",
    value: "Cnidos",
    valueType: "place",
    ref: "8.86",
    grc: "Εὔδοξος Αἰσχίνου Κνίδιος, ἀστρολόγος, γεωμέτρης, ἰατρός, νομοθέτης",
    certainty: "asserted",
  },
  {
    id: "eudoxus-studied-archytas",
    subject: "Eudoxus",
    property: "studiedUnder",
    value: "Archytas",
    valueType: "philosopher",
    ref: "8.86",
    grc: "Εὔδοξος Αἰσχίνου Κνίδιος, ἀστρολόγος, γεωμέτρης, ἰατρός, νομοθέτης",
    certainty: "asserted",
    note: "Learned geometry from Archytas.",
  },
  {
    id: "eudoxus-studied-philistion",
    subject: "Eudoxus",
    property: "studiedUnder",
    value: "Philistion the Sicilian",
    valueType: "person",
    ref: "8.86",
    grc: "Εὔδοξος Αἰσχίνου Κνίδιος, ἀστρολόγος, γεωμέτρης, ἰατρός, νομοθέτης",
    certainty: "asserted",
    note: "Learned medicine from him.",
  },
  {
    id: "eudoxus-studied-plato",
    subject: "Eudoxus",
    property: "studiedUnder",
    value: "Plato",
    valueType: "philosopher",
    ref: "8.86",
    grc: "Εὔδοξος Αἰσχίνου Κνίδιος, ἀστρολόγος, γεωμέτρης, ἰατρός, νομοθέτης",
    certainty: "reported",
    accordingTo: "Sotion",
  },
  // Curator note: the whole 8.86-87 travel narrative is indirect discourse
  // hanging off Sotion's Successions (8.86). The two travel claims below are
  // curated as asserted for consistency; if ever downgraded to
  // reported/accordingTo Sotion, change both together, never one alone.
  {
    id: "eudoxus-traveled-egypt",
    subject: "Eudoxus",
    property: "traveledTo",
    value: "Egypt",
    valueType: "place",
    ref: "8.87",
    grc: "δύο δὴ μῆνας διατρίψαντα οἴκαδʼ ἐπανελθεῖν καὶ πρὸς τῶν φίλων ἐρανισθέντα εἰς Αἴγυπτον ἀπᾶραι μετὰ Χρυσίππου τοῦ ἰατροῦ, συστατικὰς φέροντα παρʼ Ἀγησιλάου πρὸς Νεκτάναβιν",
    certainty: "asserted",
    note: "Remained a year and four months with the priests.",
  },
  {
    id: "eudoxus-traveled-cyzicus",
    subject: "Eudoxus",
    property: "traveledTo",
    value: "Cyzicus",
    valueType: "place",
    ref: "8.87",
    grc: "ἐντεῦθέν τε γενέσθαι ἐν Κυζίκῳ καὶ τῇ Προποντίδι σοφιστεύοντα·",
    certainty: "asserted",
    note: "From Egypt he went to Cyzicus and the Propontis, giving lectures; afterwards he came to the court of Mausolus.",
  },
  {
    id: "eudoxus-doctrine-pleasure",
    subject: "Eudoxus",
    property: "heldDoctrine",
    value: "Pleasure is the good",
    valueType: "doctrine",
    ref: "8.88",
    grc: "φησὶ δʼ αὐτὸν Νικόμαχος ὁ Ἀριστοτέλους τὴν ἡδονὴν λέγειν τὸ ἀγαθόν.",
    certainty: "reported",
    accordingTo: "Nicomachus",
    greek: "ἡδονή",
  },
  {
    id: "eudoxus-wrote-octaeteris",
    subject: "Eudoxus",
    property: "wrote",
    value: "Octaëteris",
    valueType: "work",
    ref: "8.87",
    grc: "δύο δὴ μῆνας διατρίψαντα οἴκαδʼ ἐπανελθεῖν καὶ πρὸς τῶν φίλων ἐρανισθέντα εἰς Αἴγυπτον ἀπᾶραι μετὰ Χρυσίππου τοῦ ἰατροῦ, συστατικὰς φέροντα παρʼ Ἀγησιλάου πρὸς Νεκτάναβιν· τὸν δὲ τοῖς ἱερεῦσιν αὐτὸν συστῆσαι",
    certainty: "reported",
  },
  {
    id: "eudoxus-wrote-dogs",
    subject: "Eudoxus",
    property: "wrote",
    value: "Dialogues of Dogs",
    valueType: "work",
    ref: "8.89",
    grc: "φησὶ δʼ αὐτὸν Ἐρατοσθένης ἐν τοῖς Πρὸς Βάτωνα καὶ Κυνῶν διαλόγους συνθεῖναι",
    certainty: "reported",
    accordingTo: "Eratosthenes",
    note: "Others say written by Egyptians and translated by him.",
  },
  {
    id: "eudoxus-wrote-geography",
    subject: "Eudoxus",
    property: "wrote",
    value: "Geography",
    valueType: "work",
    ref: "8.90",
    grc: "Γεγόνασι δʼ Εὔδοξοι τρεῖς· αὐτὸς οὗτος, ἕτερος Ῥόδιος ἱστορίας γεγραφώς, τρίτος Σικελιώτης παῖς Ἀγαθοκλέους, ποιητὴς κωμωδίας, νικας ἑλὼν ἀστικὰς μὲν τρεῖς, Ληναϊκὰς δὲ πέντε, καθά φησιν Ἀπολλόδωρος ἐν Χρονικοῖς",
    certainty: "asserted",
  },
  {
    id: "eudoxus-floruit",
    subject: "Eudoxus",
    property: "birthDate",
    value: "Flourished about the 103rd Olympiad (368/365 BCE)",
    valueType: "literal",
    ref: "8.90",
    grc: "Ὁ δʼ αὐτός φησι τὸν Κνίδιον Εὔδοξον ἀκμάσαι κατὰ τὴν τρίτην καὶ ἑκατοστὴν Ὀλυμπιάδα, εὑρεῖν τε τὰ περὶ τὰς καμπύλας γραμμάς",
    certainty: "reported",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
  },
  {
    id: "eudoxus-death-age-53",
    subject: "Eudoxus",
    property: "deathDate",
    value: "Died in his fifty-third year",
    valueType: "literal",
    ref: "8.90",
    grc: "Ὁ δʼ αὐτός φησι τὸν Κνίδιον Εὔδοξον ἀκμάσαι κατὰ τὴν τρίτην καὶ ἑκατοστὴν Ὀλυμπιάδα, εὑρεῖν τε τὰ περὶ τὰς καμπύλας γραμμάς. ἐτελεύτησε δὲ τρίτον ἄγων καὶ πεντηκοστὸν ἔτος",
    certainty: "asserted",
  },
  {
    id: "eudoxus-affiliated-pythagorean",
    subject: "Eudoxus",
    property: "affiliatedWith",
    value: "Italian / Pythagorean",
    valueType: "school",
    ref: "8.91",
    grc: "Ἔστι δὲ καὶ ἡμῶν εἰς αὐτὸν οὕτως ἔχον",
    certainty: "asserted",
    note: "Counted among the famous Pythagoreans in D.L.'s closing of Book 8: 'Having now dealt with the famous Pythagoreans, let us next discuss the so-called sporadic philosophers.'",
  },
];
