/**
 * Curated claims from Book 6 (the Cynics) of Diogenes Laertius' Lives,
 * cited to Hicks section ids (book.section). See kg-claims.ts for the model
 * and curation rules. Source-internal: every claim cites a D.L. passage.
 */
import type { KgClaim } from "../kg-claims";

export const BOOK6_CLAIMS: KgClaim[] = [
  // ---------------------------------------------------------------- Antisthenes
  {
    id: "antisthenes-parentage",
    subject: "Antisthenes",
    property: "parentage",
    value: "Son of Antisthenes, an Athenian; his mother said to have been a Thracian",
    valueType: "literal",
    ref: "6.1",
    grc: "Ἀντισθένης Ἀντισθένους Ἀθηναῖος",
    certainty: "asserted",
  },
  {
    id: "antisthenes-birthplace-athens",
    subject: "Antisthenes",
    property: "birthPlace",
    value: "Athens",
    valueType: "place",
    ref: "6.1",
    grc: "Ἀντισθένης Ἀντισθένους Ἀθηναῖος",
    certainty: "asserted",
  },
  {
    id: "antisthenes-studied-gorgias",
    subject: "Antisthenes",
    property: "studiedUnder",
    value: "Gorgias",
    valueType: "person",
    ref: "6.1",
    grc: "Οὗτος κατʼ ἀρχὰς μὲν ἤκουσε Γοργίου τοῦ ῥήτορος",
    certainty: "asserted",
    note: "First a pupil of Gorgias the rhetorician, hence his rhetorical style.",
  },
  {
    id: "antisthenes-studied-socrates",
    subject: "Antisthenes",
    property: "studiedUnder",
    value: "Socrates",
    valueType: "philosopher",
    ref: "6.2",
    grc: "Ὕστερον δὲ παρέβαλε Σωκράτει, καὶ τοσοῦτον ὤνατο αὐτοῦ, ὥστε παρῄνει τοῖς μαθηταῖς γενέσθαι αὐτῷ πρὸς Σωκράτην συμμαθητάς. οἰκῶν τʼ ἐν Πειραιεῖ καθʼ ἑκάστην ἡμέραν τοὺς τετταράκοντα σταδίους ἀνιὼν ἤκουε Σωκράτους, παρʼ οὗ καὶ τὸ καρτερικὸν λαβὼν καὶ τὸ ἀπαθὲς ζηλώσας κατῆρξε πρῶτος τοῦ κυνισμοῦ",
    certainty: "asserted",
    note: "From Socrates he learned his hardihood, and thus inaugurated the Cynic way of life.",
  },
  {
    id: "antisthenes-affiliated-cynic",
    subject: "Antisthenes",
    property: "affiliatedWith",
    value: "Cynic",
    valueType: "school",
    ref: "6.2",
    grc: "φησὶ δʼ Ἕρμιππος ὅτι προείλετο ἐν τῇ τῶν Ἰσθμίων πανηγύρει ψέξαι τε καὶ ἐπαινέσαι Ἀθηναίους, Θηβαίους, Λακεδαιμονίους",
    certainty: "asserted",
    note: "Regarded as founder of the Cynic way of life; the school named perhaps from the gymnasium Cynosarges (6.13).",
  },
  {
    id: "antisthenes-education-cloak",
    subject: "Antisthenes",
    property: "education",
    value: "The first to double his cloak, be content with that one garment, and take up a staff and a wallet",
    valueType: "literal",
    ref: "6.13",
    grc: "Τεῖχος ἀσφαλέστατον φρόνησιν",
    certainty: "reported",
    accordingTo: "Diocles",
    conflictsWith: ["antisthenes-education-diodorus"],
  },
  {
    id: "antisthenes-education-diodorus",
    subject: "Antisthenes",
    property: "education",
    value: "The doubled cloak, staff and wallet were first adopted by Diodorus of Aspendus",
    valueType: "literal",
    ref: "6.13",
    grc: "Τεῖχος ἀσφαλέστατον φρόνησιν",
    certainty: "reported",
    accordingTo: "Sosicrates",
    conflictsWith: ["antisthenes-education-cloak"],
  },
  {
    id: "antisthenes-doctrine-virtue-taught",
    subject: "Antisthenes",
    property: "heldDoctrine",
    value: "Virtue can be taught",
    valueType: "doctrine",
    ref: "6.10",
    grc: "Ἤρεσκεν αὐτῷ καὶ τάδε. διδακτὴν ἀπεδείκνυε τὴν ἀρετήν.",
    certainty: "asserted",
  },
  {
    id: "antisthenes-doctrine-virtue-sufficient",
    subject: "Antisthenes",
    property: "heldDoctrine",
    value: "Virtue is sufficient in itself to ensure happiness",
    valueType: "doctrine",
    ref: "6.11",
    grc: "αὐτάρκη δὲ τὴν ἀρετὴν πρὸς εὐδαιμονίαν, μηδενὸς προσδεομένην ὅτι μὴ Σωκρατικῆς ἰσχύος.",
    certainty: "asserted",
    greek: "εὐδαιμονία",
  },
  {
    id: "antisthenes-doctrine-virtue-deeds",
    subject: "Antisthenes",
    property: "heldDoctrine",
    value: "Virtue is an affair of deeds and needs no store of words or learning",
    valueType: "doctrine",
    ref: "6.11",
    grc: "τήν τʼ ἀρετὴν τῶν ἔργων εἶναι, μήτε λόγων πλείστων δεομένην μήτε μαθημάτων.",
    certainty: "asserted",
  },
  {
    id: "antisthenes-doctrine-wise-selfsufficing",
    subject: "Antisthenes",
    property: "heldDoctrine",
    value: "The wise man is self-sufficing, for all the goods of others are his",
    valueType: "doctrine",
    ref: "6.11",
    grc: "αὐτάρκη τʼ εἶναι τὸν σοφόν· πάντα γὰρ αὐτοῦ εἶναι τὰ τῶν ἄλλων.",
    certainty: "asserted",
    greek: "αὐτάρκεια",
  },
  {
    id: "antisthenes-doctrine-end-virtue",
    subject: "Antisthenes",
    property: "heldDoctrine",
    value: "Life according to Virtue is the End to be sought",
    valueType: "doctrine",
    ref: "6.104",
    grc: "Ἀρέσκει δʼ αὐτοῖς καὶ τέλος εἶναι τὸ κατʼ ἀρετὴν ζῆν, ὡς Ἀντισθένης φησὶν ἐν τῷ Ἡρακλεῖ, ὁμοίως τοῖς στωικοῖς·",
    certainty: "asserted",
    greek: "τέλος",
    note: "As Antisthenes says in his Heracles; exactly like the Stoics.",
  },
  {
    id: "antisthenes-death-disease",
    subject: "Antisthenes",
    property: "mannerOfDeath",
    value: "Died of disease (consumption)",
    valueType: "literal",
    ref: "6.18",
    grc: "ἐτελεύτησε δὲ ἀρρωστίᾳ",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-a-treatise-on-expression-or-styles-of-speaking",
    subject: "Antisthenes",
    property: "wrote",
    value: "A Treatise on Expression, or Styles of Speaking",
    valueType: "work",
    ref: "6.15",
    grc: "Οὗτος ἡγήσατο καὶ τῆς Διογένους ἀπαθείας καὶ τῆς Κράτητος ἐγκρατείας καὶ τῆς Ζήνωνος καρτερίας, αὐτὸς ὑποθέμενος τῇ πολιτείᾳ τὰ θεμέλια",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-ajax-or-the-speech-of-ajax",
    subject: "Antisthenes",
    property: "wrote",
    value: "Ajax, or The Speech of Ajax",
    valueType: "work",
    ref: "6.15",
    grc: "Αἴας ἢ Αἴαντος λόγος",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-odysseus-or-concerning-odysseus",
    subject: "Antisthenes",
    property: "wrote",
    value: "Odysseus, or Concerning Odysseus",
    valueType: "work",
    ref: "6.15",
    grc: "Ὀδυσσεὺς ἢ περὶ Ὀδυσσέως",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-a-defence-of-orestes-or-concerning-forensic-writers",
    subject: "Antisthenes",
    property: "wrote",
    value: "A Defence of Orestes, or Concerning Forensic Writers",
    valueType: "work",
    ref: "6.15",
    grc: "πρῶτος ἐν ᾧ Περὶ λέξεως ἢ περὶ χαρακτήρων",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-isography-similar-writing-or-lysias-and-isocrates",
    subject: "Antisthenes",
    property: "wrote",
    value: "Isography (similar writing), or Lysias and Isocrates",
    valueType: "work",
    ref: "6.15",
    grc: "Ἰσογραφὴ ἢ Λυσίας καὶ Ἰσοκράτης",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-concerning-theognis-making-a-fourth-and-a-fifth-book",
    subject: "Antisthenes",
    property: "wrote",
    value: "Concerning Theognis, making a fourth and a fifth book",
    valueType: "work",
    ref: "6.16",
    grc: "Περὶ νόμου ἢ περὶ πολιτείας",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-the-good",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of the Good",
    valueType: "work",
    ref: "6.16",
    grc: "Τόμος τρίτος ἐν ᾧ Περὶ ἀγαθοῦ",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-courage",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of Courage",
    valueType: "work",
    ref: "6.16",
    grc: "Περὶ δικαιοσύνης καὶ ἀνδρείας προτρεπτικὸς πρῶτος, δεύτερος, τρίτος",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-law-or-of-a-commonwealth",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of Law, or Of a Commonwealth",
    valueType: "work",
    ref: "6.16",
    grc: "Περὶ ζῴων φύσεως",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-law-or-of-goodness-and-justice",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of Law, or Of Goodness and Justice",
    valueType: "work",
    ref: "6.16",
    grc: "Περὶ παιδοποιίας ἢ περὶ γάμου ἐρωτικός",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-freedom-and-slavery",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of Freedom and Slavery",
    valueType: "work",
    ref: "6.16",
    grc: "Περὶ ἐλευθερίας καὶ δουλείας",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-belief",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of Belief",
    valueType: "work",
    ref: "6.16",
    grc: "Περὶ τῶν σοφιστῶν φυσιογνωμονικός",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-the-guardian-or-on-obedience",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of the Guardian, or On Obedience",
    valueType: "work",
    ref: "6.16",
    grc: "Περὶ Θεόγνιδος δʼ εʼ",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-cyrus",
    subject: "Antisthenes",
    property: "wrote",
    value: "Cyrus",
    valueType: "work",
    ref: "6.16",
    grc: "Περὶ νόμου ἢ περὶ καλοῦ καὶ δικαίου",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-the-greater-heracles-or-of-strength",
    subject: "Antisthenes",
    property: "wrote",
    value: "The Greater Heracles, or Of Strength",
    valueType: "work",
    ref: "6.16",
    grc: "Ἡρακλῆς ὁ μείζων ἢ περὶ ἰσχύος",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-cyrus-or-of-sovereignty",
    subject: "Antisthenes",
    property: "wrote",
    value: "Cyrus, or Of Sovereignty",
    valueType: "work",
    ref: "6.16",
    grc: "Περὶ πίστεως",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-aspasia",
    subject: "Antisthenes",
    property: "wrote",
    value: "Aspasia",
    valueType: "work",
    ref: "6.16",
    grc: "Περὶ ἐπιτρόπου ἢ περὶ τοῦ πείθεσθαι",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-truth",
    subject: "Antisthenes",
    property: "wrote",
    value: "Truth",
    valueType: "work",
    ref: "6.16",
    grc: "Περὶ νίκης οἰκονομικός",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-satho-or-of-contradiction-in-three-books",
    subject: "Antisthenes",
    property: "wrote",
    value: "Satho, or Of Contradiction, in three books",
    valueType: "work",
    ref: "6.16",
    grc: "Τόμος τέταρτος ἐν ᾧ Κῦρος",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-on-talk",
    subject: "Antisthenes",
    property: "wrote",
    value: "On Talk",
    valueType: "work",
    ref: "6.16",
    grc: "Περὶ ἀνδρείας",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-on-education-or-on-names-in-five-books",
    subject: "Antisthenes",
    property: "wrote",
    value: "On Education, or On Names, in five books",
    valueType: "work",
    ref: "6.17",
    grc: "Τόμος ἕβδομος ἐν ᾧ Περὶ παιδείας ἢ ὀνομάτων α′ β′ γ′ δ′ ε′",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-questioning-and-answering",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of Questioning and Answering",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ ὀνομάτων χρήσεως ἐριστικός",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-opinion-and-knowledge-in-four-books",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of Opinion and Knowledge, in four books",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ δόξης καὶ ἐπιστήμης α′ β′ γ′ δ′",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-dying",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of Dying",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ ἐρωτήσεως καὶ ἀποκρίσεως",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-life-and-death",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of Life and Death",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ ζωῆς καὶ θανάτου",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-those-in-the-underworld",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of Those in the Underworld",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ τοῦ ἀποθανεῖν",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-nature-in-two-books",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of Nature, in two books",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ φύσεως α′ β′",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-a-problem-concerning-nature",
    subject: "Antisthenes",
    property: "wrote",
    value: "A Problem concerning Nature (two books)",
    valueType: "work",
    ref: "6.17",
    grc: "Ἐρώτημα περὶ φύσεως β′",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-opinions-or-the-controversialist",
    subject: "Antisthenes",
    property: "wrote",
    value: "Opinions, or The Controversialist",
    valueType: "work",
    ref: "6.17",
    grc: "Δόξαι ἢ ἐριστικός",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-problems-about-learning",
    subject: "Antisthenes",
    property: "wrote",
    value: "Problems about Learning",
    valueType: "work",
    ref: "6.17",
    grc: "Αθηνᾶ ἢ περὶ Τηλεμάχου",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-on-music",
    subject: "Antisthenes",
    property: "wrote",
    value: "On Music",
    valueType: "work",
    ref: "6.17",
    grc: "Τόμος ὄγδοος ἐν ᾧ Περὶ μουσικῆς",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-on-commentators",
    subject: "Antisthenes",
    property: "wrote",
    value: "On Commentators",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ τῶν ἐν ᾅδου",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-on-homer",
    subject: "Antisthenes",
    property: "wrote",
    value: "On Homer",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ τοῦ μανθάνειν προβλήματα",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-on-wickedness-and-impiety",
    subject: "Antisthenes",
    property: "wrote",
    value: "On Wickedness and Impiety",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ ἐξηγητῶν",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-on-calchas",
    subject: "Antisthenes",
    property: "wrote",
    value: "On Calchas",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ Ὁμήρου",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-on-the-scout",
    subject: "Antisthenes",
    property: "wrote",
    value: "On the Scout",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ ἀδικίας καὶ ἀσεβείας",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-on-pleasure",
    subject: "Antisthenes",
    property: "wrote",
    value: "On Pleasure",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ ἡδονῆς",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-the-odyssey",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of the Odyssey",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ Κάλχαντος",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-the-minstrels-staff",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of the Minstrel’s Staff",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ κατασκόπου",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-athena-or-of-telemachus",
    subject: "Antisthenes",
    property: "wrote",
    value: "Athena, or Of Telemachus",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ Πρωτέως",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-helen-and-penelope",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of Helen and Penelope",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ τῆς ῥάβδου",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-of-proteus",
    subject: "Antisthenes",
    property: "wrote",
    value: "Of Proteus",
    valueType: "work",
    ref: "6.17",
    grc: "Περὶ Ἑλένης καὶ Πηνελόπης",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-cyclops-or-of-odysseus",
    subject: "Antisthenes",
    property: "wrote",
    value: "Cyclops, or Of Odysseus",
    valueType: "work",
    ref: "6.17",
    grc: "Τόμος ἔνατος ἐν ᾧ Περὶ Ὀδυσσείας",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-heracles-or-midas",
    subject: "Antisthenes",
    property: "wrote",
    value: "Heracles, or Midas",
    valueType: "work",
    ref: "6.18",
    grc: "Τόμος δέκατος ἐν ᾧ Ἡρακλῆς ἢ Μίδας",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-heracles-or-of-wisdom-or-strength",
    subject: "Antisthenes",
    property: "wrote",
    value: "Heracles, or Of Wisdom or Strength",
    valueType: "work",
    ref: "6.18",
    grc: "Ἡρακλῆς ἢ περὶ φρονήσεως ἢ ἰσχύος",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-cyrus-or-the-beloved",
    subject: "Antisthenes",
    property: "wrote",
    value: "Cyrus, or The Beloved",
    valueType: "work",
    ref: "6.18",
    grc: "Κῦρος ἢ ἐρώμενος",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-cyrus-or-the-scouts",
    subject: "Antisthenes",
    property: "wrote",
    value: "Cyrus, or The Scouts",
    valueType: "work",
    ref: "6.18",
    grc: "Περὶ τοῦ Ὀδυσσέως καὶ Πηνελόπης καὶ περὶ τοῦ κυνός",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-menexenus-or-on-ruling",
    subject: "Antisthenes",
    property: "wrote",
    value: "Menexenus, or On Ruling",
    valueType: "work",
    ref: "6.18",
    grc: "Μενέξενος ἢ περὶ τοῦ ἄρχειν",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-alcibiades",
    subject: "Antisthenes",
    property: "wrote",
    value: "Alcibiades",
    valueType: "work",
    ref: "6.18",
    grc: "Ἀλκιβιάδης",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrote-archelaus-or-of-kingship",
    subject: "Antisthenes",
    property: "wrote",
    value: "Archelaus, or Of Kingship",
    valueType: "work",
    ref: "6.18",
    grc: "Ἀρχέλαος ἢ περὶ βασιλείας",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Diogenes of Sinope
  {
    id: "diogenes-parentage",
    subject: "Diogenes of Sinope",
    property: "parentage",
    value: "Son of Hicesius, a banker",
    valueType: "literal",
    ref: "6.20",
    grc: "φησὶ δὲ Διοκλῆς, δημοσίαν αὐτοῦ τὴν τράπεζαν ἔχοντος τοῦ πατρὸς καὶ παραχαράξαντος τὸ νόμισμα, φυγεῖν. Εὐβουλίδης δʼ ἐν τῷ Περὶ Διογένους αὐτόν φησι Διογένην τοῦτο πρᾶξαι καὶ συναλᾶσθαι τῷ πατρί",
    certainty: "asserted",
  },
  {
    id: "diogenes-birthplace-sinope",
    subject: "Diogenes of Sinope",
    property: "birthPlace",
    value: "Sinope",
    valueType: "place",
    ref: "6.20",
    grc: "Διογένης Ἱκεσίου τραπεζίτου Σινωπεύς",
    certainty: "asserted",
    note: "Went into exile over the adulteration of the coinage.",
  },
  {
    id: "diogenes-studied-antisthenes",
    subject: "Diogenes of Sinope",
    property: "studiedUnder",
    value: "Antisthenes",
    valueType: "philosopher",
    ref: "6.21",
    grc: "ἔνιοι δέ φασι παρὰ τοῦ πατρὸς αὐτὸν λαβόντα τὸ νόμισμα διαφθεῖραι",
    certainty: "asserted",
    note: "By sheer persistence he wore down Antisthenes, who never welcomed pupils.",
  },
  {
    id: "diogenes-affiliated-cynic",
    subject: "Diogenes of Sinope",
    property: "affiliatedWith",
    value: "Cynic",
    valueType: "school",
    ref: "6.60",
    grc: "Ἐπανῄει ἀπʼ Ὀλυμπίων",
    certainty: "asserted",
    note: "\"I am Diogenes the Cynic.\"",
  },
  {
    id: "diogenes-doctrine-cosmopolitan",
    subject: "Diogenes of Sinope",
    property: "heldDoctrine",
    value: "I am a citizen of the world",
    valueType: "doctrine",
    ref: "6.63",
    grc: "ἐρωτηθεὶς πόθεν εἴη, κοσμοπολίτης, ἔφη.",
    certainty: "asserted",
    greek: "κοσμοπολίτης",
  },
  {
    id: "diogenes-doctrine-all-belong-wise",
    subject: "Diogenes of Sinope",
    property: "heldDoctrine",
    value: "All things belong to the gods; the gods are friends to the wise; friends share all in common; therefore all things belong to the wise",
    valueType: "doctrine",
    ref: "6.72",
    grc: "πάντα τῶν θεῶν ἐστι· φίλοι δὲ τοῖς σοφοῖς οἱ θεοί· κοινὰ δὲ τὰ τῶν φίλων. πάντα ἄρα τῶν σοφῶν.",
    certainty: "asserted",
  },
  {
    id: "diogenes-doctrine-nature-over-convention",
    subject: "Diogenes of Sinope",
    property: "heldDoctrine",
    value: "Natural right is to be preferred to convention; he lived like Heracles, preferring liberty to everything",
    valueType: "doctrine",
    ref: "6.71",
    grc: "μηδὲν οὕτω τοῖς κατὰ νόμον ὡς τοῖς κατὰ φύσιν διδούς· τὸν αὐτὸν χαρακτῆρα τοῦ βίου λέγων διεξάγειν ὅνπερ καὶ Ἡρακλῆς, μηδὲν ἐλευθερίας προκρίνων.",
    certainty: "asserted",
  },
  {
    id: "diogenes-doctrine-cosmic-commonwealth",
    subject: "Diogenes of Sinope",
    property: "heldDoctrine",
    value: "The only true commonwealth is that which is as wide as the universe",
    valueType: "doctrine",
    ref: "6.72",
    grc: "μόνην τε ὀρθὴν πολιτείαν εἶναι τὴν ἐν κόσμῳ.",
    certainty: "asserted",
  },
  {
    id: "diogenes-doctrine-community-wives",
    subject: "Diogenes of Sinope",
    property: "heldDoctrine",
    value: "Advocated community of wives, recognizing no marriage but the union of persuasion and consent",
    valueType: "doctrine",
    ref: "6.72",
    grc: "ἔλεγε δὲ καὶ κοινὰς εἶναι δεῖν τὰς γυναῖκας, γάμον μηδένα νομίζων, ἀλλὰ τὸν πείσαντα τῇ πεισθείσῃ συνεῖναι·",
    certainty: "asserted",
  },
  {
    id: "diogenes-doctrine-selfsufficiency",
    subject: "Diogenes of Sinope",
    property: "heldDoctrine",
    value: "Self-sufficingness and the easiest path of life",
    valueType: "doctrine",
    ref: "6.78",
    grc: "μοῦνος ἐπεὶ βιοτᾶς αὐτάρκεα δόξαν ἔδειξας θνατοῖς καὶ ζωᾶς οἶμον ἐλαφροτάταν.",
    certainty: "asserted",
    greek: "αὐτάρκεια",
  },
  {
    id: "diogenes-birthdate-ol113",
    subject: "Diogenes of Sinope",
    property: "birthDate",
    value: "Was an old man in the 113th Olympiad (328/325 BCE)",
    valueType: "literal",
    ref: "6.79",
    grc: "ἦν δὲ γέρων κατὰ τὴν τρίτην καὶ δεκάτην καὶ ἑκατοστὴν Ὀλυμπιάδα.",
    certainty: "asserted",
  },
  {
    id: "diogenes-deathdate-90",
    subject: "Diogenes of Sinope",
    property: "deathDate",
    value: "Said to have been nearly ninety years old when he died",
    valueType: "literal",
    ref: "6.76",
    grc: "Λέγεται δὲ πρὸς τὰ ἐνενήκοντα ἔτη βιοὺς τελευτῆσαι",
    certainty: "reported",
  },
  {
    id: "diogenes-deathplace-corinth",
    subject: "Diogenes of Sinope",
    property: "deathPlace",
    value: "Corinth",
    valueType: "place",
    ref: "6.79",
    grc: "Δημήτριος δʼ ἐν τοῖς Ὁμωνύμοις φησὶ τῆς αὐτῆς ἡμέρας Ἀλέξανδρον μὲν ἐν Βαβυλῶνι, Διογένην δʼ ἐν Κορίνθῳ τελευτῆσαι.",
    certainty: "reported",
    accordingTo: "Demetrius",
    sourceWork: "Homonyms",
    note: "Demetrius says he died at Corinth on the same day Alexander died at Babylon.",
  },
  {
    id: "diogenes-death-octopus",
    subject: "Diogenes of Sinope",
    property: "mannerOfDeath",
    value: "Seized with colic after eating a raw octopus",
    valueType: "literal",
    ref: "6.76",
    grc: "οἱ μὲν γὰρ πολύποδα φαγόντα ὠμὸν χολερικῇ ληφθῆναι καὶ ὧδε τελευτῆσαι",
    certainty: "reported",
    conflictsWith: ["diogenes-death-breath", "diogenes-death-dogbite"],
  },
  {
    id: "diogenes-death-breath",
    subject: "Diogenes of Sinope",
    property: "mannerOfDeath",
    value: "Died voluntarily by holding his breath",
    valueType: "literal",
    ref: "6.77",
    grc: "οἱ μέντοι γνώριμοι αὐτοῦ, καθά φησιν Ἀντισθένης ἐν Διαδοχαῖς, εἴκαζον τὴν τοῦ πνεύματος συγκράτησιν.",
    certainty: "reported",
    accordingTo: "Antisthenes",
    sourceWork: "Successions",
    conflictsWith: ["diogenes-death-octopus", "diogenes-death-dogbite"],
  },
  {
    id: "diogenes-death-dogbite",
    subject: "Diogenes of Sinope",
    property: "mannerOfDeath",
    value: "Bitten on the sinew of the foot by dogs while dividing an octopus among them",
    valueType: "literal",
    ref: "6.77",
    grc: "Ἄλλοι φασὶ πολύπουν κυσὶ συμμερίσασθαι βουλόμενον οὕτω δηχθῆναι τοῦ ποδὸς τὸν τένοντα καὶ καταστρέψαι.",
    certainty: "reported",
    conflictsWith: ["diogenes-death-octopus", "diogenes-death-breath"],
  },
  {
    id: "diogenes-writings-none",
    subject: "Diogenes of Sinope",
    property: "writings",
    value: "Left nothing in writing",
    valueType: "literal",
    ref: "6.80",
    grc: "Φέρεται δʼ αὐτοῦ βιβλία τάδε",
    certainty: "reported",
    accordingTo: "Sosicrates",
    note: "Sosicrates and Satyrus allege he left nothing; the tragedies ascribed to his friend Philiscus.",
  },
  {
    id: "diogenes-wrote-cephalion",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Cephalion",
    valueType: "work",
    ref: "6.80",
    grc: "Κεφαλίων",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-ichthyas",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Ichthyas",
    valueType: "work",
    ref: "6.80",
    grc: "Ἰχθύας",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-jackdaw",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Jackdaw",
    valueType: "work",
    ref: "6.80",
    grc: "Κολοιός",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-pordalus",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Pordalus",
    valueType: "work",
    ref: "6.80",
    grc: "Πόρδαλος",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-the-athenian-demos",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "The Athenian Demos",
    valueType: "work",
    ref: "6.80",
    grc: "Δῆμος Ἀθηναίων",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-republic",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Republic",
    valueType: "work",
    ref: "6.80",
    grc: "Πολιτεία",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-art-of-ethics",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Art of Ethics",
    valueType: "work",
    ref: "6.80",
    grc: "Τέχνη ἠθική",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-on-wealth",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "On Wealth",
    valueType: "work",
    ref: "6.80",
    grc: "Περὶ πλούτου",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-on-love",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "On Love",
    valueType: "work",
    ref: "6.80",
    grc: "Ἐρωτικός",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-theodorus",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Theodorus",
    valueType: "work",
    ref: "6.80",
    grc: "Θεόδωρος",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-hypsias",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Hypsias",
    valueType: "work",
    ref: "6.80",
    grc: "Ὑψίας",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-aristarchus",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Aristarchus",
    valueType: "work",
    ref: "6.80",
    grc: "Ἀρίσταρχος",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-on-death",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "On Death",
    valueType: "work",
    ref: "6.80",
    grc: "Περὶ θανάτου",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-letters",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Letters",
    valueType: "work",
    ref: "6.80",
    grc: "Ἐπιστολαί",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-helen",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Helen",
    valueType: "work",
    ref: "6.80",
    grc: "Ἑλένη",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-thyestes",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Thyestes",
    valueType: "work",
    ref: "6.80",
    grc: "Θυέστης",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-heracles",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Heracles",
    valueType: "work",
    ref: "6.80",
    grc: "Ἡρακλῆς",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-achilles",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Achilles",
    valueType: "work",
    ref: "6.80",
    grc: "Ἀχιλλεύς",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-medea",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Medea",
    valueType: "work",
    ref: "6.80",
    grc: "Μήδεια",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-chrysippus",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Chrysippus",
    valueType: "work",
    ref: "6.80",
    grc: "Χρύσιππος",
    certainty: "asserted",
  },
  {
    id: "diogenes-wrote-oedipus",
    subject: "Diogenes of Sinope",
    property: "wrote",
    value: "Oedipus",
    valueType: "work",
    ref: "6.80",
    grc: "Οἰδίπους",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Monimus
  {
    id: "monimus-birthplace-syracuse",
    subject: "Monimus",
    property: "birthPlace",
    value: "Syracuse",
    valueType: "place",
    ref: "6.82",
    grc: "Μόνιμος Συρακόσιος μαθητὴς μὲν Διογένους, οἰκέτης δέ τινος τραπεζίτου Κορινθίου, καθά φησι Σωσικράτης",
    certainty: "asserted",
  },
  {
    id: "monimus-studied-diogenes",
    subject: "Monimus",
    property: "studiedUnder",
    value: "Diogenes of Sinope",
    valueType: "philosopher",
    ref: "6.82",
    grc: "Μόνιμος Συρακόσιος μαθητὴς μὲν Διογένους, οἰκέτης δέ τινος τραπεζίτου Κορινθίου, καθά φησι Σωσικράτης",
    certainty: "asserted",
    note: "Feigned madness to be dismissed by his master, then devoted himself to Diogenes.",
  },
  {
    id: "monimus-studied-crates",
    subject: "Monimus",
    property: "studiedUnder",
    value: "Crates of Thebes",
    valueType: "philosopher",
    ref: "6.82",
    grc: "Μόνιμος Συρακόσιος μαθητὴς μὲν Διογένους, οἰκέτης δέ τινος τραπεζίτου Κορινθίου, καθά φησι Σωσικράτης",
    certainty: "asserted",
    note: "Often followed Crates the Cynic as well.",
  },
  {
    id: "monimus-affiliated-cynic",
    subject: "Monimus",
    property: "affiliatedWith",
    value: "Cynic",
    valueType: "school",
    ref: "6.83",
    grc: "Ἐγένετο δʼ ἀνὴρ ἐλλόγιμος, ὡς καὶ Μένανδρον αὐτοῦ τὸν κωμικὸν μεμνῆσθαι",
    certainty: "asserted",
  },
  {
    id: "monimus-wrote-impulses",
    subject: "Monimus",
    property: "wrote",
    value: "On Impulses",
    valueType: "work",
    ref: "6.83",
    grc: "Ἐγένετο δʼ ἀνὴρ ἐλλόγιμος, ὡς καὶ Μένανδρον αὐτοῦ τὸν κωμικὸν μεμνῆσθαι",
    certainty: "asserted",
  },
  {
    id: "monimus-wrote-exhortation",
    subject: "Monimus",
    property: "wrote",
    value: "An Exhortation to Philosophy",
    valueType: "work",
    ref: "6.83",
    grc: "Γέγραφε δὲ παίγνια σπουδῇ λεληθυίᾳ μεμιγμένα καὶ Περὶ ὁρμῶν δύο καὶ Προτρεπτικόν.",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Onesicritus
  {
    id: "onesicritus-birthplace-aegina",
    subject: "Onesicritus",
    property: "birthPlace",
    value: "Aegina",
    valueType: "place",
    ref: "6.84",
    grc: "Ὀνησίκριτος",
    certainty: "reported",
    conflictsWith: ["onesicritus-birthplace-astypalaea"],
  },
  {
    id: "onesicritus-birthplace-astypalaea",
    subject: "Onesicritus",
    property: "birthPlace",
    value: "Astypalaea",
    valueType: "place",
    ref: "6.84",
    grc: "Ὀνησίκριτος",
    certainty: "reported",
    accordingTo: "Demetrius of Magnesia",
    conflictsWith: ["onesicritus-birthplace-aegina"],
  },
  {
    id: "onesicritus-studied-diogenes",
    subject: "Onesicritus",
    property: "studiedUnder",
    value: "Diogenes of Sinope",
    valueType: "philosopher",
    ref: "6.84",
    grc: "καὶ οὗτος τῶν ἐλλογίμων Διογένους μαθητῶν",
    certainty: "asserted",
    note: "One of the distinguished pupils of Diogenes; wrote of how Alexander was educated.",
  },
  {
    id: "onesicritus-affiliated-cynic",
    subject: "Onesicritus",
    property: "affiliatedWith",
    value: "Cynic",
    valueType: "school",
    ref: "6.84",
    grc: "Ὀνησίκριτος",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Crates of Thebes
  {
    id: "crates-parentage",
    subject: "Crates of Thebes",
    property: "parentage",
    value: "Son of Ascondas, a Theban",
    valueType: "literal",
    ref: "6.85",
    grc: "Κράτης Ἀσκώνδου Θηβαῖος",
    certainty: "asserted",
  },
  {
    id: "crates-birthplace-thebes",
    subject: "Crates of Thebes",
    property: "birthPlace",
    value: "Thebes",
    valueType: "place",
    ref: "6.85",
    grc: "Κράτης Ἀσκώνδου Θηβαῖος",
    certainty: "asserted",
  },
  {
    id: "crates-studied-diogenes",
    subject: "Crates of Thebes",
    property: "studiedUnder",
    value: "Diogenes of Sinope",
    valueType: "philosopher",
    ref: "6.85",
    grc: "καὶ οὗτος τῶν ἐλλογίμων τοῦ κυνὸς μαθητῶν. Ἱππόβοτος δέ φησιν οὐ Διογένους αὐτὸν μαθητὴν γεγονέναι, ἀλλὰ Βρύσωνος τοῦ Ἀχαιοῦ",
    certainty: "asserted",
    conflictsWith: ["crates-studied-bryson"],
  },
  {
    id: "crates-studied-bryson",
    subject: "Crates of Thebes",
    property: "studiedUnder",
    value: "Bryson the Achaean",
    valueType: "person",
    ref: "6.85",
    grc: "καὶ οὗτος τῶν ἐλλογίμων τοῦ κυνὸς μαθητῶν. Ἱππόβοτος δέ φησιν οὐ Διογένους αὐτὸν μαθητὴν γεγονέναι, ἀλλὰ Βρύσωνος τοῦ Ἀχαιοῦ",
    certainty: "reported",
    accordingTo: "Hippobotus",
    conflictsWith: ["crates-studied-diogenes"],
  },
  {
    id: "crates-affiliated-cynic",
    subject: "Crates of Thebes",
    property: "affiliatedWith",
    value: "Cynic",
    valueType: "school",
    ref: "6.85",
    grc: "Κράτης Ἀσκώνδου Θηβαῖος",
    certainty: "asserted",
  },
  {
    id: "crates-flourished-ol113",
    subject: "Crates of Thebes",
    property: "birthDate",
    value: "Flourished in the 113th Olympiad (328/325 BCE)",
    valueType: "literal",
    ref: "6.87",
    grc: "Ἤκμαζε δὲ κατὰ τὴν τρίτην καὶ δεκάτην καὶ ἑκατοστὴν Ὀλυμπιάδα",
    certainty: "asserted",
  },
  {
    id: "crates-writings-distributed",
    subject: "Crates of Thebes",
    property: "writings",
    value: "Turned his property (about 200 talents) into money and distributed it among his fellow-citizens",
    valueType: "literal",
    ref: "6.87",
    grc: "Ἤκμαζε δὲ κατὰ τὴν τρίτην καὶ δεκάτην καὶ ἑκατοστὴν Ὀλυμπιάδα",
    certainty: "reported",
    accordingTo: "Antisthenes",
  },
  {
    id: "crates-doctrine-country",
    subject: "Crates of Thebes",
    property: "heldDoctrine",
    value: "Ignominy and Poverty are my country, which Fortune can never take captive",
    valueType: "doctrine",
    ref: "6.93",
    grc: "ἔχειν δὲ πατρίδα ἀδοξίαν καὶ πενίαν ἀνάλωτα τῇ τύχῃ καὶ Διογένους εἶναι πολίτης ἀνεπιβουλεύτου φθόνῳ.",
    certainty: "asserted",
  },
  {
    id: "crates-wrote-epistles",
    subject: "Crates of Thebes",
    property: "wrote",
    value: "Epistles",
    valueType: "work",
    ref: "6.98",
    grc: "Φέρεται δὲ τοῦ Κράτητος βιβλίον Ἐπιστολαί,",
    certainty: "asserted",
    note: "Excellent philosophy in a style sometimes resembling Plato.",
  },
  {
    id: "crates-wrote-tragedies",
    subject: "Crates of Thebes",
    property: "wrote",
    value: "Tragedies",
    valueType: "work",
    ref: "6.98",
    grc: "γέγραφε καὶ τραγῳδίας ὑψηλότατον ἐχούσας φιλοσοφίας χαρακτῆρα,",
    certainty: "asserted",
    note: "Stamped with a very lofty kind of philosophy.",
  },
  {
    id: "crates-death-oldage",
    subject: "Crates of Thebes",
    property: "mannerOfDeath",
    value: "Died in old age and was buried in Boeotia",
    valueType: "literal",
    ref: "6.98",
    grc: "Ἐτελεύτησε δὲ γηραιὸς καὶ ἐτάφη ἐν Βοιωτίᾳ.",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Metrocles
  {
    id: "metrocles-birthplace-maroneia",
    subject: "Metrocles",
    property: "birthPlace",
    value: "Maroneia",
    valueType: "place",
    ref: "6.94",
    grc: "Μητροκλῆς ὁ Μαρωνείτης, ἀδελφὸς Ἱππαρχίας, ὃς πρότερον ἀκούων Θεοφράστου τοῦ περιπατητικοῦ τοσοῦτον διέφθαρτο, ὥστε ποτὲ μελετῶν καὶ μεταξύ πως ἀποπαρδὼν ὑπʼ ἀθυμίας οἴκοι κατάκλειστος ἦν, ἀποκαρτερεῖν βουλόμενος",
    certainty: "asserted",
  },
  {
    id: "metrocles-studied-theophrastus",
    subject: "Metrocles",
    property: "studiedUnder",
    value: "Theophrastus",
    valueType: "philosopher",
    ref: "6.94",
    grc: "Μητροκλῆς ὁ Μαρωνείτης, ἀδελφὸς Ἱππαρχίας, ὃς πρότερον ἀκούων Θεοφράστου τοῦ περιπατητικοῦ τοσοῦτον διέφθαρτο, ὥστε ποτὲ μελετῶν καὶ μεταξύ πως ἀποπαρδὼν ὑπʼ ἀθυμίας οἴκοι κατάκλειστος ἦν, ἀποκαρτερεῖν βουλόμενος",
    certainty: "asserted",
    note: "Formerly a pupil of Theophrastus the Peripatetic.",
  },
  {
    id: "metrocles-studied-crates",
    subject: "Metrocles",
    property: "studiedUnder",
    value: "Crates of Thebes",
    valueType: "philosopher",
    ref: "6.94",
    grc: "Μητροκλῆς ὁ Μαρωνείτης, ἀδελφὸς Ἱππαρχίας, ὃς πρότερον ἀκούων Θεοφράστου τοῦ περιπατητικοῦ τοσοῦτον διέφθαρτο, ὥστε ποτὲ μελετῶν καὶ μεταξύ πως ἀποπαρδὼν ὑπʼ ἀθυμίας οἴκοι κατάκλειστος ἦν, ἀποκαρτερεῖν βουλόμενος",
    certainty: "asserted",
    note: "Crates lifted him from dejection and he became his pupil.",
  },
  {
    id: "metrocles-affiliated-cynic",
    subject: "Metrocles",
    property: "affiliatedWith",
    value: "Cynic",
    valueType: "school",
    ref: "6.95",
    grc: "Οὗτος τὰ ἑαυτοῦ συγγράμματα κατακαίων, ὥς φησιν Ἑκάτων ἐν πρώτῳ Χρειῶν, ἐπέλεγε",
    certainty: "asserted",
  },
  {
    id: "metrocles-writings-burned",
    subject: "Metrocles",
    property: "writings",
    value: "Burned his own compositions (his notes of Theophrastus’s lectures)",
    valueType: "literal",
    ref: "6.95",
    grc: "Οὗτος τὰ ἑαυτοῦ συγγράμματα κατακαίων, ὥς φησιν Ἑκάτων ἐν πρώτῳ Χρειῶν, ἐπέλεγε",
    certainty: "reported",
    accordingTo: "Hecato",
  },
  {
    id: "metrocles-death-choked",
    subject: "Metrocles",
    property: "mannerOfDeath",
    value: "Died of old age, having choked himself",
    valueType: "literal",
    ref: "6.95",
    grc: "Ἐτελεύτα δὲ ὑπὸ γήρως ἑαυτὸν πνίξας.",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Hipparchia
  {
    id: "hipparchia-birthplace-maroneia",
    subject: "Hipparchia",
    property: "birthPlace",
    value: "Maroneia",
    valueType: "place",
    ref: "6.96",
    grc: "Ἐθηράθη δὲ τοῖς λόγοις καὶ ἡ ἀδελφὴ τοῦ Μητροκλέους Ἱππαρχία",
    certainty: "asserted",
    note: "Sister of Metrocles.",
  },
  {
    id: "hipparchia-studied-crates",
    subject: "Hipparchia",
    property: "studiedUnder",
    value: "Crates of Thebes",
    valueType: "philosopher",
    ref: "6.96",
    grc: "Ἐθηράθη δὲ τοῖς λόγοις καὶ ἡ ἀδελφὴ τοῦ Μητροκλέους Ἱππαρχία",
    certainty: "asserted",
    note: "Fell in love with the discourses and life of Crates; adopted the same dress and shared his pursuits.",
  },
  {
    id: "hipparchia-affiliated-cynic",
    subject: "Hipparchia",
    property: "affiliatedWith",
    value: "Cynic",
    valueType: "school",
    ref: "6.97",
    grc: "Εἵλετο ἡ παῖς καὶ ταὐτὸν ἀναλαβοῦσα σχῆμα συμπεριῄει τἀνδρὶ καὶ ἐν τῷ φανερῷ συνεγίνετο καὶ ἐπὶ τὰ δεῖπνα ἀπῄει",
    certainty: "asserted",
  },
  {
    id: "hipparchia-criticized-theodorus",
    subject: "Hipparchia",
    property: "criticized",
    value: "Theodorus",
    valueType: "person",
    ref: "6.97",
    grc: "ἔνθα Θεόδωρον τὸν ἐπίκλην Ἄθεον ἐπήλεγξε, σόφισμα προτείνασα τοιοῦτον·",
    certainty: "asserted",
    note: "At Lysimachus’s banquet she put down Theodorus the atheist by a sophism.",
  },
  // ---------------------------------------------------------------- Menippus
  {
    id: "menippus-parentage",
    subject: "Menippus",
    property: "parentage",
    value: "A Phoenician by descent, a slave",
    valueType: "literal",
    ref: "6.99",
    grc: "Μένιππος, καὶ οὗτος κυνικός, τὸ ἀνέκαθεν ἦν Φοῖνιξ, δοῦλος, ὥς φησιν Ἀχαϊκὸς ἐν Ἠθικοῖς.",
    certainty: "reported",
    accordingTo: "Achaïcus",
  },
  {
    id: "menippus-affiliated-cynic",
    subject: "Menippus",
    property: "affiliatedWith",
    value: "Cynic",
    valueType: "school",
    ref: "6.99",
    grc: "Μένιππος, καὶ οὗτος κυνικός, τὸ ἀνέκαθεν ἦν Φοῖνιξ, δοῦλος, ὥς φησιν Ἀχαϊκὸς ἐν Ἠθικοῖς",
    certainty: "asserted",
  },
  {
    id: "menippus-death-hanged",
    subject: "Menippus",
    property: "mannerOfDeath",
    value: "Fell victim to a plot, was robbed of all, and in despair hanged himself",
    valueType: "literal",
    ref: "6.100",
    grc: "τέλος δʼ ἐπιβουλευθέντα πάντων στερηθῆναι καὶ ὑπʼ ἀθυμίας βρόχῳ τὸν βίον μεταλλάξαι.",
    certainty: "asserted",
  },
  {
    id: "menippus-writings-disputed",
    subject: "Menippus",
    property: "writings",
    value: "The books attributed to him are questioned, some alleging they are by Dionysius and Zopyrus of Colophon",
    valueType: "literal",
    ref: "6.100",
    grc: "τέλος δʼ ἐπιβουλευθέντα πάντων στερηθῆναι καὶ ὑπʼ ἀθυμίας βρόχῳ τὸν βίον μεταλλάξαι",
    certainty: "disputed",
  },
  {
    id: "menippus-wrote-necromancy",
    subject: "Menippus",
    property: "wrote",
    value: "Necromancy",
    valueType: "work",
    ref: "6.101",
    grc: "Τὰ δʼ οὖν τοῦ κυνικοῦ βιβλία ἐστὶ δεκατρία, Νέκυια",
    certainty: "asserted",
  },
  {
    id: "menippus-wrote-wills",
    subject: "Menippus",
    property: "wrote",
    value: "Wills",
    valueType: "work",
    ref: "6.101",
    grc: "Διαθῆκαι",
    certainty: "asserted",
  },
  {
    id: "menippus-wrote-epistles-artificially-composed-as-if-by-the-gods",
    subject: "Menippus",
    property: "wrote",
    value: "Epistles artificially composed as if by the gods",
    valueType: "work",
    ref: "6.101",
    grc: "Ἐπιστολαὶ κεκομψευμέναι ἀπὸ τοῦ τῶν θεῶν προσώπου",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Menedemus the Cynic
  {
    id: "menedemus-cyn-studied-colotes",
    subject: "Menedemus the Cynic",
    property: "studiedUnder",
    value: "Colotes of Lampsacus",
    valueType: "person",
    ref: "6.102",
    grc: "Μενέδημος Κωλώτου τοῦ Λαμψακηνοῦ μαθητής",
    certainty: "asserted",
  },
  {
    id: "menedemus-cyn-affiliated-cynic",
    subject: "Menedemus the Cynic",
    property: "affiliatedWith",
    value: "Cynic",
    valueType: "school",
    ref: "6.102",
    grc: "Μενέδημος Κωλώτου τοῦ Λαμψακηνοῦ μαθητής",
    certainty: "asserted",
    note: "Reported to have gone about in the guise of a Fury, claiming to have come from Hades.",
  },
];
