/**
 * Curated claims from Book 1 of Diogenes Laertius' Lives, cited to
 * Hicks section ids (book.section). See kg-claims.ts for the model and
 * curation rules. Source-internal: every claim cites a D.L. passage.
 */
import type { KgClaim } from "../kg-claims";

export const BOOK1_CLAIMS: KgClaim[] = [
  // ------------------------------------------------------------ Xenophanes
  // Prologue placement: the Italian succession of 1.15 makes Xenophanes
  // the pupil of Telauges (and teacher of Parmenides), while 9.18
  // reports that according to some he was no man's pupil. Both textual
  // presentations are recorded and linked as competing reports.
  {
    id: "xenophanes-succession-italian",
    subject: "Xenophanes",
    property: "education",
    value: "Pupil of Telauges in the Italian succession of the Prologue",
    valueType: "literal",
    ref: "1.15",
    grc: "Ἡ δὲ Ἰταλικὴ οὕτω· Φερεκύδους Πυθαγόρας, οὗ Τηλαύγης ὁ υἱός, οὗ Ξενοφάνης, οὗ Παρμενίδης",
    certainty: "asserted",
    note: "The Prologue's Italian succession places Xenophanes between Telauges and Parmenides; his Life reports, according to some, that he was no man's pupil (9.18).",
    conflictsWith: ["xenophanes-education-self-taught"],
  },
  // ---------------------------------------------------------------- Thales
  {
    id: "thales-descent-milesian",
    subject: "Thales",
    property: "parentage",
    value: "A genuine Milesian of distinguished family",
    valueType: "literal",
    ref: "1.22",
    grc: "Ἦν τοίνυν ὁ Θαλῆς, ὡς μὲν Ἡρόδοτος καὶ Δοῦρις καὶ Δημόκριτός φασι, πατρὸς μὲν Ἐξαμύου, μητρὸς δὲ Κλεοβουλίνης, ἐκ τῶν Θηλιδῶν, οἵ εἰσι Φοίνικες, εὐγενέστατοι τῶν ἀπὸ Κάδμου καὶ Ἀγήνορος",
    certainty: "reported",
    note: "So most writers, per D.L.",
    conflictsWith: ["thales-descent-phoenician"],
  },
  {
    id: "thales-descent-phoenician",
    subject: "Thales",
    property: "parentage",
    value:
      "Son of Examyas and Cleobulina, of the Thelidae family, Phoenicians by descent",
    valueType: "literal",
    ref: "1.22",
    grc: "Ἦν τοίνυν ὁ Θαλῆς, ὡς μὲν Ἡρόδοτος καὶ Δοῦρις καὶ Δημόκριτός φασι, πατρὸς μὲν Ἐξαμύου, μητρὸς δὲ Κλεοβουλίνης, ἐκ τῶν Θηλιδῶν, οἵ εἰσι Φοίνικες, εὐγενέστατοι τῶν ἀπὸ Κάδμου καὶ Ἀγήνορος",
    certainty: "reported",
    accordingTo: "Herodotus",
    note: "Also per Duris and Democritus.",
    conflictsWith: ["thales-descent-milesian"],
  },
  {
    id: "thales-lived-miletus",
    subject: "Thales",
    property: "livedIn",
    value: "Miletus",
    valueType: "place",
    ref: "1.22",
    grc: "Ἦν τοίνυν ὁ Θαλῆς, ὡς μὲν Ἡρόδοτος καὶ Δοῦρις καὶ Δημόκριτός φασι, πατρὸς μὲν Ἐξαμύου, μητρὸς δὲ Κλεοβουλίνης, ἐκ τῶν Θηλιδῶν, οἵ εἰσι Φοίνικες, εὐγενέστατοι τῶν ἀπὸ Κάδμου καὶ Ἀγήνορος",
    certainty: "asserted",
  },
  {
    id: "thales-wrote-nothing",
    subject: "Thales",
    property: "writings",
    value: "Left nothing in writing",
    valueType: "literal",
    ref: "1.23",
    grc: "κατά τινας δὲ μόνα δύο συνέγραψε, Περὶ τροπῆς καὶ Ἰσημερίας, τὰ ἄλλʼ ἀκατάληπτα εἶναι δοκιμάσας",
    certainty: "reported",
    conflictsWith: [
      "thales-wrote-solstice",
      "thales-wrote-equinox",
      "thales-wrote-nautical-astronomy",
    ],
  },
  {
    id: "thales-wrote-solstice",
    subject: "Thales",
    property: "wrote",
    value: "On the Solstice",
    valueType: "work",
    ref: "1.23",
    grc: "Μετὰ δὲ τὰ πολιτικὰ τῆς φυσικῆς ἐγένετο θεωρίας",
    certainty: "reported",
    note: "Per those who say he wrote nothing but two treatises.",
    conflictsWith: ["thales-wrote-nothing"],
  },
  {
    id: "thales-wrote-equinox",
    subject: "Thales",
    property: "wrote",
    value: "On the Equinox",
    valueType: "work",
    ref: "1.23",
    grc: "Καλλίμαχος δʼ αὐτὸν οἶδεν εὑρετὴν τῆς ἄρκτου τῆς μικρᾶς, λέγων ἐν τοῖς Ἰάμβοις οὕτως",
    certainty: "reported",
    conflictsWith: ["thales-wrote-nothing"],
  },
  {
    id: "thales-wrote-nautical-astronomy",
    subject: "Thales",
    property: "wrote",
    value: "Nautical Astronomy",
    valueType: "work",
    ref: "1.23",
    grc: "ὥς φησιν Εὔδημος ἐν τῇ περὶ τῶν Ἀστρολογουμένων ἱστορίᾳ",
    certainty: "disputed",
    note: "Attributed to Thales but said to be by Phocus of Samos.",
    conflictsWith: ["thales-wrote-nothing"],
  },
  {
    id: "thales-birth-ol35",
    subject: "Thales",
    property: "birthDate",
    value: "Born in the first year of the 35th Olympiad (640/639 BCE)",
    valueType: "literal",
    ref: "1.37",
    grc: "Φησὶ δʼ Ἀπολλόδωρος ἐν τοῖς Χρονικοῖς γεγενῆσθαι αὐτὸν κατὰ τὸ πρῶτον ἔτος τῆς τριακοστῆς πέμπτης [ἐνάτης ?] Ὀλυμπιάδος.",
    certainty: "reported",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
  },
  {
    id: "thales-death-age-78",
    subject: "Thales",
    property: "deathDate",
    value: "Died in the 58th Olympiad (548-545 BCE) at the age of 78",
    valueType: "literal",
    ref: "1.38",
    grc: "ἐτελεύτησε δʼ ἐτῶν ἑβδομήκοντα ὀκτώ",
    certainty: "reported",
    conflictsWith: ["thales-death-age-90"],
  },
  {
    id: "thales-death-age-90",
    subject: "Thales",
    property: "deathDate",
    value: "Died at the age of 90",
    valueType: "literal",
    ref: "1.38",
    grc: "ὡς Σωσικράτης φησίν, ἐνενήκοντα",
    certainty: "reported",
    accordingTo: "Sosicrates",
    conflictsWith: ["thales-death-age-78"],
  },
  {
    id: "thales-death-manner",
    subject: "Thales",
    property: "mannerOfDeath",
    value:
      "Died of heat, thirst and weakness while watching an athletic contest, in old age",
    valueType: "literal",
    ref: "1.39",
    grc: "Ὁ δʼ οὖν σοφὸς ἐτελεύτησεν ἀγῶνα θεώμενος γυμνικὸν ὑπό τε καύματος καὶ δίψους καὶ ἀσθενείας, ἤδη γηραιός.",
    certainty: "asserted",
  },
  {
    id: "xenophanes-praised-thales",
    subject: "Xenophanes",
    property: "praised",
    value: "Thales",
    valueType: "philosopher",
    ref: "1.23",
    grc: "ὅθεν αὐτὸν καὶ Ξενοφάνης καὶ Ἡρόδοτος θαυμάζει.",
    certainty: "asserted",
    note: "His astronomy gained him the admiration of Xenophanes and Herodotus.",
  },
  // ---------------------------------------------------------------- Solon
  {
    id: "solon-parentage",
    subject: "Solon",
    property: "parentage",
    value: "Son of Execestides",
    valueType: "literal",
    ref: "1.45",
    grc: "ἑπτὰ δὴ ταλάντων ὀφειλομένων αὐτῷ πατρῴων συνεχώρησε πρῶτος καὶ τοὺς λοιποὺς τὸ ὅμοιον προὔτρεψε πρᾶξαι",
    certainty: "asserted",
  },
  {
    id: "solon-birthplace-salamis",
    subject: "Solon",
    property: "birthPlace",
    value: "Salamis",
    valueType: "place",
    ref: "1.45",
    grc: "Σόλων Ἐξηκεστίδου Σαλαμίνιος πρῶτον μὲν τὴν σεισάχθειαν εἰσηγήσατο Ἀθηναίοις",
    certainty: "asserted",
  },
  {
    id: "solon-traveled-egypt",
    subject: "Solon",
    property: "traveledTo",
    value: "Egypt",
    valueType: "place",
    ref: "1.50",
    grc: "τὰ δὲ περὶ τῆς τοῦ Πεισιστράτου τυραννίδος ἐλεγεῖα προλέγοντος αὐτοῦ ταῦτα ἦν",
    certainty: "asserted",
  },
  {
    id: "solon-traveled-cyprus",
    subject: "Solon",
    property: "traveledTo",
    value: "Cyprus",
    valueType: "place",
    ref: "1.50",
    grc: "τὰ δὲ περὶ τῆς τοῦ Πεισιστράτου τυραννίδος ἐλεγεῖα προλέγοντος αὐτοῦ ταῦτα ἦν",
    certainty: "asserted",
  },
  {
    id: "solon-lived-cilicia",
    subject: "Solon",
    property: "livedIn",
    value: "Cilicia",
    valueType: "place",
    ref: "1.51",
    grc: "Φασὶ δέ τινες ὅτι κοσμήσας ἑαυτὸν ὁ Κροῖσος παντοδαπῶς καὶ καθίσας εἰς τὸν θρόνον ἤρετο αὐτὸν εἴ τι θέαμα κάλλιον τεθέαται",
    certainty: "asserted",
    note: "Founded there a city which he called Soli after his own name.",
  },
  {
    id: "solon-wrote-laws",
    subject: "Solon",
    property: "wrote",
    value: "Laws (the laws which bear his name)",
    valueType: "work",
    ref: "1.61",
    grc: "τοὺς νόμους",
    certainty: "asserted",
  },
  {
    id: "solon-wrote-salamis",
    subject: "Solon",
    property: "wrote",
    value: "On Salamis (elegiac poem)",
    valueType: "work",
    ref: "1.61",
    grc: "Τῶν δὲ ᾀδομένων αὐτοῦ ἐστι τάδε",
    certainty: "asserted",
  },
  {
    id: "solon-wrote-constitution",
    subject: "Solon",
    property: "wrote",
    value: "On the Athenian Constitution (elegiac poem)",
    valueType: "work",
    ref: "1.61",
    grc: "τῆς Ἀθηναίων πολιτείας",
    certainty: "asserted",
    note: "Elegiac poems, five thousand lines in all, besides iambics and epodes.",
  },
  {
    id: "solon-flourished-ol46",
    subject: "Solon",
    property: "birthDate",
    value: "Flourished about the 46th Olympiad (596/593 BCE), being archon at Athens in its third year",
    valueType: "literal",
    ref: "1.62",
    grc: "Ἤκμαζε μὲν οὖν περὶ τὴν τεσσαρακοστὴν ἕκτην Ὀλυμπιάδα, ἧς τῷ τρίτῳ ἔτει ἦρξεν Ἀθήνησι, καθά φησι Σωσικράτης",
    certainty: "reported",
    accordingTo: "Sosicrates",
  },
  {
    id: "solon-death-cyprus",
    subject: "Solon",
    property: "deathPlace",
    value: "Cyprus",
    valueType: "place",
    ref: "1.62",
    grc: "ἐτελεύτησε δʼ ἐν Κύπρῳ βιοὺς ἔτη ὀγδοήκοντα",
    certainty: "asserted",
  },
  {
    id: "solon-death-age80",
    subject: "Solon",
    property: "deathDate",
    value: "Died in Cyprus at the age of eighty",
    valueType: "literal",
    ref: "1.62",
    grc: "ἐτελεύτησε δʼ ἐν Κύπρῳ βιοὺς ἔτη ὀγδοήκοντα",
    certainty: "asserted",
  },
  {
    id: "solon-doctrine-nothing-too-much",
    subject: "Solon",
    property: "heldDoctrine",
    value: "Nothing too much",
    valueType: "doctrine",
    greek: "μηδὲν ἄγαν",
    ref: "1.63",
    grc: "Ἀπεφθέγξατο δέ, φασί, Μηδὲν ἄγαν.",
    certainty: "reported",
    note: "It is said that he was the author of this apophthegm.",
  },
  // ---------------------------------------------------------------- Chilon
  {
    id: "chilon-parentage",
    subject: "Chilon",
    property: "parentage",
    value: "Son of Damagetas, a Lacedaemonian",
    valueType: "literal",
    ref: "1.68",
    grc: "Χίλων Δαμαγήτου Λακεδαιμόνοις",
    certainty: "asserted",
  },
  {
    id: "chilon-birthplace-sparta",
    subject: "Chilon",
    property: "birthPlace",
    value: "Lacedaemon",
    valueType: "place",
    ref: "1.68",
    grc: "γέγονε δὲ ἔφορος κατὰ τὴν πεντηκοστὴν πέμπτην Ὀλυμπιάδα",
    certainty: "asserted",
  },
  {
    id: "chilon-wrote-elegy",
    subject: "Chilon",
    property: "wrote",
    value: "Elegiac poem (some 200 lines)",
    valueType: "work",
    ref: "1.68",
    grc: "οὗτος ἐποίησεν ἐλεγεῖα εἰς ἔπη διακόσια,",
    certainty: "asserted",
  },
  {
    id: "chilon-flourished-ol52",
    subject: "Chilon",
    property: "birthDate",
    value: "Was an old man about the 52nd Olympiad (572/569 BCE), when Aesop the fabulist was flourishing",
    valueType: "literal",
    ref: "1.72",
    grc: "ἦν δὲ γέρων περὶ τὴν πεντηκοστὴν δευτέραν Ὀλυμπιάδα, ὅτε Αἴσωπος ὁ λογοποιὸς ἤκμαζεν. ἐτελεύτησε δʼ, ὥς φησιν Ἕρμιππος, ἐν Πίσῃ, τὸν υἱὸν Ὀλυμπιονίκην ἀσπασάμενος πυγμῆς",
    certainty: "asserted",
  },
  {
    id: "chilon-death-place-pisa",
    subject: "Chilon",
    property: "deathPlace",
    value: "Pisa",
    valueType: "place",
    ref: "1.72",
    grc: "ἐτελεύτησε δʼ, ὥς φησιν Ἕρμιππος, ἐν Πίσῃ, τὸν υἱὸν Ὀλυμπιονίκην ἀσπασάμενος πυγμῆς.",
    certainty: "reported",
    accordingTo: "Hermippus",
  },
  {
    id: "chilon-death-manner",
    subject: "Chilon",
    property: "mannerOfDeath",
    value: "Died of excess of joy at Pisa, just after congratulating his son on an Olympic boxing victory",
    valueType: "literal",
    ref: "1.72",
    grc: "ἐτελεύτησε δʼ, ὥς φησιν Ἕρμιππος, ἐν Πίσῃ, τὸν υἱὸν Ὀλυμπιονίκην ἀσπασάμενος πυγμῆς. ἔπαθε δὲ τοῦτο ὑπερβολῇ τε χαρᾶς καὶ ἀσθενείᾳ πολυετίας.",
    certainty: "reported",
    accordingTo: "Hermippus",
  },
  {
    id: "chilon-doctrine-pledge",
    subject: "Chilon",
    property: "heldDoctrine",
    value: "Give a pledge, and suffer for it",
    valueType: "doctrine",
    ref: "1.73",
    grc: "ἀπεφθέγξατο, ἐγγύα, πάρα δʼ ἄτα.",
    certainty: "asserted",
    note: "His apophthegm.",
  },
  // ---------------------------------------------------------------- Pittacus
  {
    id: "pittacus-parentage-mitylene",
    subject: "Pittacus",
    property: "parentage",
    value: "Son of Hyrrhadius, a native of Mitylene",
    valueType: "literal",
    ref: "1.74",
    grc: "Πιττακὸς Ὑρραδίου Μυτιληναῖος",
    certainty: "asserted",
    conflictsWith: ["pittacus-father-thracian"],
  },
  {
    id: "pittacus-father-thracian",
    subject: "Pittacus",
    property: "parentage",
    value: "His father was a Thracian",
    valueType: "literal",
    ref: "1.74",
    grc: "Πιττακὸς Ὑρραδίου Μυτιληναῖος",
    certainty: "reported",
    accordingTo: "Duris",
    conflictsWith: ["pittacus-parentage-mitylene"],
  },
  {
    id: "pittacus-birthplace-mitylene",
    subject: "Pittacus",
    property: "birthPlace",
    value: "Mitylene",
    valueType: "place",
    ref: "1.74",
    grc: "Πιττακὸς Ὑρραδίου Μυτιληναῖος",
    certainty: "asserted",
  },
  {
    id: "pittacus-wrote-elegy",
    subject: "Pittacus",
    property: "wrote",
    value: "Elegiac poems (some 600 lines)",
    valueType: "work",
    ref: "1.79",
    grc: "ἐποίησε δὲ καὶ ἐλεγεῖα ἔπη ἑξακόσια,",
    certainty: "asserted",
  },
  {
    id: "pittacus-wrote-on-laws",
    subject: "Pittacus",
    property: "wrote",
    value: "On Laws (prose work for the citizens)",
    valueType: "work",
    ref: "1.79",
    grc: "καὶ ὑπὲρ νόμων καταλογάδην τοῖς πολίταις",
    certainty: "asserted",
  },
  {
    id: "pittacus-flourished-ol42",
    subject: "Pittacus",
    property: "birthDate",
    value: "Flourishing about the 42nd Olympiad (612/609 BCE)",
    valueType: "literal",
    ref: "1.79",
    grc: "Ἤκμαζε μὲν οὖν περὶ τὴν τεσσαρακοστὴν δευτέραν Ὀλυμπιάδα",
    certainty: "asserted",
  },
  {
    id: "pittacus-death-ol52",
    subject: "Pittacus",
    property: "deathDate",
    value: "Died in the archonship of Aristomenes, in the third year of the 52nd Olympiad (570/569 BCE), aged more than seventy",
    valueType: "literal",
    ref: "1.79",
    grc: "ἐτελεύτησε δʼ ἐπὶ Ἀριστομένους τῷ τρίτῳ ἔτει τῆς πεντηκοστῆς δευτέρας Ὀλυμπιάδος",
    certainty: "asserted",
  },
  {
    id: "pittacus-doctrine-hard-good",
    subject: "Pittacus",
    property: "heldDoctrine",
    value: "It is hard to be good",
    valueType: "doctrine",
    ref: "1.76",
    grc: "εἶπέ τε χαλεπὸν ἐσθλὸν ἔμμεναι· οὗ καὶ Σιμωνίδης μέμνηται λέγων· ἄνδρʼ ἀγαθὸν ἀλαθέως γενέσθαι χαλεπόν, τὸ Πιττάκειον.",
    certainty: "asserted",
    note: "Cited by Simonides; alluded to by Plato in the Protagoras.",
  },
  {
    id: "pittacus-doctrine-opportunity",
    subject: "Pittacus",
    property: "heldDoctrine",
    value: "Know thine opportunity",
    valueType: "doctrine",
    ref: "1.79",
    grc: "ἀπόφθεγμα αὐτοῦ· καιρὸν γνῶθι.",
    certainty: "asserted",
    note: "His apophthegm.",
  },
  // ---------------------------------------------------------------- Bias
  {
    id: "bias-parentage",
    subject: "Bias",
    property: "parentage",
    value: "Son of Teutames",
    valueType: "literal",
    ref: "1.82",
    grc: "Φανόδικος δὲ κόρας αἰχμαλώτους λυτρωσάμενον Μεσσηνίας θρέψαι τε ὡς θυγατέρας καὶ προῖκας ἐπιδοῦναι καὶ εἰς τὴν Μεσσήνην ἀποστεῖλαι τοῖς πατράσιν αὐτῶν",
    certainty: "asserted",
  },
  {
    id: "bias-birthplace-priene",
    subject: "Bias",
    property: "birthPlace",
    value: "Priene",
    valueType: "place",
    ref: "1.82",
    grc: "Βίας Τευτάμου Πριηνεύς, προκεκριμένος τῶν ἑπτὰ ὑπὸ Σατύρου",
    certainty: "asserted",
  },
  {
    id: "bias-wrote-ionia",
    subject: "Bias",
    property: "wrote",
    value: "Poem on Ionia and how it may best be made prosperous (2000 lines)",
    valueType: "work",
    ref: "1.85",
    grc: "Ἐποίησε δὲ περὶ Ἰωνίας, τίνα μάλιστα ἂν τρόπον εὐδαιμονοίη, εἰς ἔπη δισχίλια",
    certainty: "asserted",
  },
  {
    id: "bias-death-manner",
    subject: "Bias",
    property: "mannerOfDeath",
    value: "Died of old age while pleading a case, resting his head on his grandson's bosom",
    valueType: "literal",
    ref: "1.84",
    grc: "δίκην γὰρ ὑπέρ τινος λέξας ἤδη ὑπέργηρως ὑπάρχων, μετὰ τὸ καταπαῦσαι τὸν λόγον ἀπέκλινε τὴν κεφαλὴν εἰς τοὺς τοῦ τῆς θυγατρὸς υἱοῦ κόλπους",
    certainty: "asserted",
  },
  {
    id: "bias-doctrine-most-men-bad",
    subject: "Bias",
    property: "heldDoctrine",
    value: "Most men are bad",
    valueType: "doctrine",
    ref: "1.88",
    grc: "ἀπεφθέγξατο· οἱ πλεῖστοι κακοί.",
    certainty: "asserted",
    note: "His apophthegm.",
  },
  {
    id: "heraclitus-praised-bias",
    subject: "Heraclitus",
    property: "praised",
    value: "Bias",
    valueType: "philosopher",
    ref: "1.88",
    grc: "ὁ δυσάρεστος Ἡράκλειτος μάλιστα αὐτὸν ἐπῄνεσε γράψας· ἐν Πριήνῃ Βίας ἐγένετο ὁ Τευτάμεω, οὗ πλέων λόγος ἢ τῶν ἄλλων.",
    certainty: "asserted",
    note: "Heraclitus, who is hard to please, praises him: 'In Priene lived Bias, son of Teutames, a man of more consideration than any.'",
  },
  // ---------------------------------------------------------------- Cleobulus
  {
    id: "cleobulus-parentage-lindus",
    subject: "Cleobulus",
    property: "parentage",
    value: "Son of Euagoras, born at Lindus",
    valueType: "literal",
    ref: "1.89",
    grc: "Κλεόβουλος Εὐαγόρου Λίνδιος, ὡς δὲ Δοῦρις, Κάρ",
    certainty: "asserted",
    conflictsWith: ["cleobulus-descent-carian"],
  },
  {
    id: "cleobulus-descent-carian",
    subject: "Cleobulus",
    property: "parentage",
    value: "A Carian by descent",
    valueType: "literal",
    ref: "1.89",
    grc: "Κλεόβουλος Εὐαγόρου Λίνδιος, ὡς δὲ Δοῦρις, Κάρ",
    certainty: "reported",
    accordingTo: "Duris",
    conflictsWith: ["cleobulus-parentage-lindus"],
  },
  {
    id: "cleobulus-birthplace-lindus",
    subject: "Cleobulus",
    property: "birthPlace",
    value: "Lindus",
    valueType: "place",
    ref: "1.89",
    grc: "Κλεόβουλος Εὐαγόρου Λίνδιος, ὡς δὲ Δοῦρις, Κάρ",
    certainty: "asserted",
  },
  {
    id: "cleobulus-wrote-songs-riddles",
    subject: "Cleobulus",
    property: "wrote",
    value: "Songs and riddles (some 3000 lines)",
    valueType: "work",
    ref: "1.89",
    grc: "Κλεόβουλος Εὐαγόρου Λίνδιος, ὡς δὲ Δοῦρις, Κάρ· ἔνιοι δὲ εἰς Ἡρακλέα ἀναφέρειν τὸ γένος αὐτόν· ῥώμῃ δὲ καὶ κάλλει διαφέρειν, μετασχεῖν τε τῆς ἐν Αἰγύπτῳ φιλοσοφίας",
    certainty: "asserted",
  },
  {
    id: "cleobulus-death-age70",
    subject: "Cleobulus",
    property: "deathDate",
    value: "Died at the age of seventy",
    valueType: "literal",
    ref: "1.93",
    grc: "δεσπότας κτήσῃ τοὺς συγγενέας",
    certainty: "asserted",
  },
  {
    id: "cleobulus-doctrine-moderation",
    subject: "Cleobulus",
    property: "heldDoctrine",
    value: "Moderation is best",
    valueType: "doctrine",
    ref: "1.93",
    grc: "Ἀπεφθέγξατο· μέτρον ἄριστον.",
    certainty: "asserted",
    note: "His apophthegm.",
  },
  // ---------------------------------------------------------------- Periander
  {
    id: "periander-parentage",
    subject: "Periander",
    property: "parentage",
    value: "Son of Cypselus, of the family of the Heraclidae",
    valueType: "literal",
    ref: "1.94",
    grc: "Τόν τε παῖδα ἀπεκήρυξεν εἰς Κέρκυραν, λυπούμενον ἐπὶ τῇ μητρί, ᾧ ὄνομα Λυκόφρων",
    certainty: "asserted",
  },
  {
    id: "periander-birthplace-corinth",
    subject: "Periander",
    property: "birthPlace",
    value: "Corinth",
    valueType: "place",
    ref: "1.94",
    grc: "Περίανδρος Κυψέλου Κορίνθιος ἀπὸ τοῦ τῶν Ἡρακλειδῶν γένους",
    certainty: "asserted",
  },
  {
    id: "periander-wrote-didactic",
    subject: "Periander",
    property: "wrote",
    value: "Didactic poem (2000 lines)",
    valueType: "work",
    ref: "1.97",
    grc: "ἐποίησε δὲ καὶ ὑποθήκας εἰς ἔπη δισχίλια",
    certainty: "asserted",
  },
  {
    id: "periander-death-age80",
    subject: "Periander",
    property: "deathDate",
    value: "Died at the age of eighty, forty-one years before Croesus, just before the 49th Olympiad (585 BCE)",
    valueType: "literal",
    ref: "1.95",
    grc: "Καὶ ὃς ἀθυμήσας ἐτελεύτησεν, ἤδη γεγονὼς ἔτη ὀγδοήκοντα. Σωσικράτης δέ φησι πρότερον Κροίσου τελευτῆσαι αὐτὸν ἔτεσι τεσσαράκοντα καὶ ἑνί, πρὸ τῆς τεσσαρακοστῆς ἐνάτης Ὀλυμπιάδος",
    certainty: "reported",
    accordingTo: "Sosicrates",
  },
  {
    id: "periander-flourished-ol38",
    subject: "Periander",
    property: "birthDate",
    value: "Flourished about the 38th Olympiad (628/625 BCE) and was tyrant for forty years",
    valueType: "literal",
    ref: "1.98",
    grc: "καὶ οὐκ εἴα ἐν ἄστει ζῆν τοὺς βουλομένους, καθά φησιν Ἔφορος καὶ Ἀριστοτέλης, ἤκμαζε δὲ περὶ τὴν τριακοστὴν ὀγδόην Ὀλυμπιάδα, καὶ ἐτυράννησεν ἔτη τετταράκοντα",
    certainty: "asserted",
  },
  {
    id: "periander-doctrine-practice",
    subject: "Periander",
    property: "heldDoctrine",
    value: "Practice makes perfect",
    valueType: "doctrine",
    ref: "1.99",
    grc: "Τούτου ἐστί· Μελέτη τὸ πᾶν.",
    certainty: "asserted",
    note: "His apophthegm.",
  },
  {
    id: "periander-sage-disputed",
    subject: "Periander",
    property: "affiliatedWith",
    value: "Seven Sages",
    valueType: "school",
    ref: "1.99",
    grc: "τοῦτο καὶ Νεάνθης φησὶν ὁ Κυζικηνός, ἀνεψιούς τε εἶιναι ἀλλήλοις",
    certainty: "disputed",
    accordingTo: "Aristotle",
    note: "Aristotle holds the Corinthian Periander was the Sage; Plato denies it. Sotion, Heraclides and Pamphila distinguish two Perianders, a tyrant and a sage of Ambracia.",
  },
  // ---------------------------------------------------------------- Anacharsis
  {
    id: "anacharsis-parentage",
    subject: "Anacharsis",
    property: "parentage",
    value: "Son of Gnurus and brother of Caduidas, king of Scythia; his mother was a Greek",
    valueType: "literal",
    ref: "1.101",
    grc: "Ἀνάχαρσις ὁ Σκύθης Γνούρου μὲν ἦν υἱός, ἀδελφὸς δὲ Καδουΐδα τοῦ Σκυθῶν βασιλέως, μητρὸς δὲ Ἑλληνίδος",
    certainty: "asserted",
  },
  {
    id: "anacharsis-birthplace-scythia",
    subject: "Anacharsis",
    property: "birthPlace",
    value: "Scythia",
    valueType: "place",
    ref: "1.101",
    grc: "Ἀνάχαρσις ὁ Σκύθης Γνούρου μὲν ἦν υἱός, ἀδελφὸς δὲ Καδουΐδα τοῦ Σκυθῶν βασιλέως, μητρὸς δὲ Ἑλληνίδος",
    certainty: "asserted",
  },
  {
    id: "anacharsis-wrote-institutions",
    subject: "Anacharsis",
    property: "wrote",
    value: "Poem on the institutions of the Greeks and the Scythians (800 lines)",
    valueType: "work",
    ref: "1.101",
    grc: "Ἀνάχαρσις ὁ Σκύθης Γνούρου μὲν ἦν υἱός, ἀδελφὸς δὲ Καδουΐδα τοῦ Σκυθῶν βασιλέως, μητρὸς δὲ Ἑλληνίδος",
    certainty: "asserted",
    note: "On simplicity of life and military matters.",
  },
  {
    id: "anacharsis-traveled-athens",
    subject: "Anacharsis",
    property: "traveledTo",
    value: "Athens",
    valueType: "place",
    ref: "1.101",
    grc: "Ἀνάχαρσις ὁ Σκύθης Γνούρου μὲν ἦν υἱός, ἀδελφὸς δὲ Καδουΐδα τοῦ Σκυθῶν βασιλέως, μητρὸς δὲ Ἑλληνίδος",
    certainty: "reported",
    accordingTo: "Sosicrates",
    note: "Came to Athens about the 47th Olympiad in the archonship of Eucrates.",
  },
  {
    id: "anacharsis-athens-ol47",
    subject: "Anacharsis",
    property: "birthDate",
    value:
      "Came to Athens about the 47th Olympiad (592/589 BCE), in the archonship of Eucrates",
    valueType: "literal",
    ref: "1.101",
    grc: "Λέγει δὲ αὐτὸν Σωσικράτης ἐλθεῖν εἰς Ἀθήνας κατὰ τὴν τεσσαρακοστὴν ἑβδόμην Ὀλυμπιάδα ἐπὶ ἄρχοντος Εὐκράτους",
    certainty: "reported",
    accordingTo: "Sosicrates",
  },
  {
    id: "anacharsis-death-manner",
    subject: "Anacharsis",
    property: "mannerOfDeath",
    value: "Killed by his brother while out hunting, on his return to Scythia, for his enthusiasm for Greek ways",
    valueType: "literal",
    ref: "1.102",
    grc: "Μετὰ χρόνον δὲ παραγενόμενος εἰς τὴν Σκυθίαν καὶ δοκῶν τὰ νόμιμα παραλύειν τῆς πατρίδος πολὺς ὢν ἐν τῷ ἑλληνίζειν, τοξευθεὶς ἐν κυνηγεσίῳ πρὸς τἀδελφοῦ τελευτᾷ",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Myson
  {
    id: "myson-parentage",
    subject: "Myson",
    property: "parentage",
    value: "Son of Strymon, a native of Chen",
    valueType: "literal",
    ref: "1.106",
    grc: "φασὶ δὲ αὐτὸν καὶ τυράννου πατρὸς εἶναι",
    certainty: "reported",
    accordingTo: "Sosicrates",
    chain: [{ authority: "Hermippus" }],
    note: "Sosicrates quotes Hermippus as his authority; his father is said to have been a tyrant.",
  },
  {
    id: "myson-birthplace-chen",
    subject: "Myson",
    property: "birthPlace",
    value: "Chen (a village in the district of Oeta or Laconia)",
    valueType: "place",
    ref: "1.106",
    grc: "Μύσων Στρύμωνος, ὥς φησι Σωσικράτης Ἕρμιππον παρατιθέμενος, τὸ γένος Χηνεύς, ἀπὸ κώμης τινὸς Οἰταϊκῆς ἢ Λακωνικῆς, σὺν τοῖς ἑπτὰ καταριθμεῖται",
    certainty: "asserted",
  },
  {
    id: "myson-death-age97",
    subject: "Myson",
    property: "deathDate",
    value: "Died at the age of ninety-seven",
    valueType: "literal",
    ref: "1.108",
    grc: "ὀφθῆναι γοῦν ἐν Λακεδαίμονι μόνον ἐπʼ ἐρημίας γελῶντα",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Epimenides
  {
    id: "epimenides-parentage-phaestius",
    subject: "Epimenides",
    property: "parentage",
    value: "Son of Phaestius",
    valueType: "literal",
    ref: "1.109",
    grc: "Ἐπιμενίδης, καθά φησι Θεόπομπος καὶ ἄλλοι συχνοί, πατρὸς μὲν ἦν Φαιστίου",
    certainty: "reported",
    accordingTo: "Theopompus",
    conflictsWith: ["epimenides-parentage-dosiadas"],
  },
  {
    id: "epimenides-parentage-dosiadas",
    subject: "Epimenides",
    property: "parentage",
    value: "Son of Dosiadas, or of Agesarchus",
    valueType: "literal",
    ref: "1.109",
    grc: "πατρὸς μὲν ἦν Φαιστίου, οἱ δὲ Δωσιάδα οἱ δὲ Ἀγησάρχου",
    certainty: "reported",
    conflictsWith: ["epimenides-parentage-phaestius"],
  },
  {
    id: "epimenides-birthplace-cnossos",
    subject: "Epimenides",
    property: "birthPlace",
    value: "Cnossos in Crete",
    valueType: "place",
    ref: "1.109",
    grc: "Ἐπιμενίδης, καθά φησι Θεόπομπος καὶ ἄλλοι συχνοί, πατρὸς μὲν ἦν Φαιστίου, οἱ δὲ Δωσιάδα οἱ δὲ Ἀγησάρχου",
    certainty: "asserted",
  },
  {
    id: "epimenides-traveled-athens",
    subject: "Epimenides",
    property: "traveledTo",
    value: "Athens",
    valueType: "place",
    ref: "1.110",
    grc: "γνωσθεὶς δὲ παρὰ τοῖς Ἕλλησι θεοφιλέστατος εἶναι ὑπελήφθη",
    certainty: "asserted",
    note: "Came in the 46th Olympiad, purified the city and stopped the pestilence.",
  },
  {
    id: "epimenides-wrote-theogony",
    subject: "Epimenides",
    property: "wrote",
    value: "On the Birth of the Curetes and Corybantes, and a Theogony (5000 lines)",
    valueType: "work",
    ref: "1.111",
    grc: "Ἐποίησε δὲ Κουρήτων καὶ Κορυβάντων γένεσιν καὶ Θεογονίαν,",
    certainty: "asserted",
  },
  {
    id: "epimenides-wrote-argo",
    subject: "Epimenides",
    property: "wrote",
    value: "On the building of the Argo and Jason's voyage to Colchis (6500 lines)",
    valueType: "work",
    ref: "1.111",
    grc: "Ἐποίησε δὲ Κουρήτων καὶ Κορυβάντων γένεσιν καὶ Θεογονίαν, ἔπη πεντακισχίλια, Ἀργοῦς ναυπηγίαν τε καὶ Ἰάσονος εἰς Κόλχους ἀπόπλουν ἔπη ἑξακισχίλια πεντακόσια.",
    certainty: "asserted",
  },
  {
    id: "epimenides-wrote-prose",
    subject: "Epimenides",
    property: "wrote",
    value: "On Sacrifices and the Cretan Constitution; On Minos and Rhadamanthus (about 4000 lines)",
    valueType: "work",
    ref: "1.112",
    grc: "Φέρεται δʼ αὐτοῦ καὶ ἐπιστολὴ πρὸς Σόλωνα τὸν νομοθέτην, περιέχουσα πολιτείαν ἣν διέταξε Κρησὶ Μίνως",
    certainty: "asserted",
  },
  {
    id: "epimenides-death-157",
    subject: "Epimenides",
    property: "deathDate",
    value: "Lived one hundred and fifty-seven years",
    valueType: "literal",
    ref: "1.111",
    grc: "Ἀθηναῖοι δὲ τάλαντον ἐψηφίσαντο δοῦναι αὐτῷ καὶ ναῦν τὴν ἐς Κρήτην ἀπάξουσαν αὐτόν",
    certainty: "reported",
    accordingTo: "Phlegon",
    conflictsWith: ["epimenides-death-299", "epimenides-death-154"],
  },
  {
    id: "epimenides-death-299",
    subject: "Epimenides",
    property: "deathDate",
    value: "Lived two hundred and ninety-nine years",
    valueType: "literal",
    ref: "1.111",
    grc: "Ἀθηναῖοι δὲ τάλαντον ἐψηφίσαντο δοῦναι αὐτῷ καὶ ναῦν τὴν ἐς Κρήτην ἀπάξουσαν αὐτόν",
    certainty: "reported",
    note: "According to the Cretans.",
    conflictsWith: ["epimenides-death-157", "epimenides-death-154"],
  },
  {
    id: "epimenides-death-154",
    subject: "Epimenides",
    property: "deathDate",
    value: "Lived one hundred and fifty-four years",
    valueType: "literal",
    ref: "1.111",
    grc: "Ἀθηναῖοι δὲ τάλαντον ἐψηφίσαντο δοῦναι αὐτῷ καὶ ναῦν τὴν ἐς Κρήτην ἀπάξουσαν αὐτόν",
    certainty: "reported",
    accordingTo: "Xenophanes",
    note: "Xenophanes of Colophon gives his age as 154, according to hearsay.",
    conflictsWith: ["epimenides-death-157", "epimenides-death-299"],
  },
  {
    id: "epimenides-athens-ol46",
    subject: "Epimenides",
    property: "birthDate",
    value:
      "Came to Athens in the 46th Olympiad (596/593 BCE) and purified the city",
    valueType: "literal",
    ref: "1.110",
    grc: "καὶ ὃς ἐλθὼν Ὀλυμπιάδι τεσσαρακοστῇ ἕκτῇ ἐκάθηρεν αὐτῶν τὴν πόλιν καὶ ἔπαυσε τὸν λοιμὸν τοῦτον τὸν τρόπον",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Pherecydes
  {
    id: "pherecydes-parentage",
    subject: "Pherecydes",
    property: "parentage",
    value: "Son of Babys, a native of Syros",
    valueType: "literal",
    ref: "1.116",
    grc: "Φερεκύδης Βάβυος Σύριος, καθά φησιν Ἀλέξανδρος ἐν Διαδοχαῖς, Πιττακοῦ διακήκοεν",
    certainty: "asserted",
  },
  {
    id: "pherecydes-birthplace-syros",
    subject: "Pherecydes",
    property: "birthPlace",
    value: "Syros",
    valueType: "place",
    ref: "1.116",
    grc: "Φερεκύδης Βάβυος Σύριος, καθά φησιν Ἀλέξανδρος ἐν Διαδοχαῖς, Πιττακοῦ διακήκοεν",
    certainty: "asserted",
  },
  {
    id: "pherecydes-teacher-pittacus",
    subject: "Pherecydes",
    property: "studiedUnder",
    value: "Pittacus",
    valueType: "philosopher",
    ref: "1.116",
    grc: "Φερεκύδης Βάβυος Σύριος, καθά φησιν Ἀλέξανδρος ἐν Διαδοχαῖς, Πιττακοῦ διακήκοεν",
    certainty: "reported",
    accordingTo: "Alexander",
    sourceWork: "Successions of Philosophers",
    note: "A pupil of Pittacus, per Alexander in his Successions of Philosophers.",
  },
  {
    id: "pherecydes-wrote-nature-gods",
    subject: "Pherecydes",
    property: "wrote",
    value: "A work on nature and the gods (beginning 'Zeus and Time and Earth were from all eternity')",
    valueType: "work",
    ref: "1.119",
    grc: "Ἄνδρων δʼ ὁ Ἐφέσιός φησι δύο γεγονέναι Φερεκύδας Συρίους, τὸν μὲν ἀστρολόγον, τὸν δὲ θεολόγον υἱὸν Βάβυος, ᾧ καὶ Πυθαγόραν σχολάσαι",
    certainty: "asserted",
    note: "Theopompus says he was the first who wrote in Greek on nature and the gods (1.116).",
  },
  {
    id: "pherecydes-death-vermin",
    subject: "Pherecydes",
    property: "mannerOfDeath",
    value: "Died of a verminous (lice) disease",
    valueType: "literal",
    ref: "1.118",
    grc: "οἱ δὲ φθειριάσαντα τὸν βίον τελευτῆσαι",
    certainty: "reported",
    conflictsWith: ["pherecydes-death-corycus", "pherecydes-death-natural"],
  },
  {
    id: "pherecydes-death-corycus",
    subject: "Pherecydes",
    property: "mannerOfDeath",
    value: "Came to Delphi and hurled himself down from Mount Corycus",
    valueType: "literal",
    ref: "1.118",
    grc: "ἔνιοι δέ φασιν ἐλθόντα εἰς Δελφοὺς ἀπὸ τοῦ Κωρυκίου ὄρους αὑτὸν δισκῆσαι.",
    certainty: "reported",
    conflictsWith: ["pherecydes-death-vermin", "pherecydes-death-natural"],
  },
  {
    id: "pherecydes-death-natural",
    subject: "Pherecydes",
    property: "mannerOfDeath",
    value: "Died a natural death and was buried by Pythagoras in Delos",
    valueType: "literal",
    ref: "1.118",
    grc: "Ἀριστόξενος δʼ ἐν τῷ Περὶ Πυθαγόρου καὶ τῶν γνωρίμων αὐτοῦ φησι νοσήσαντα αὐτὸν ὑπὸ Πυθαγόρου ταφῆναι ἐν Δήλῳ.",
    certainty: "reported",
    accordingTo: "Aristoxenus",
    sourceWork: "On Pythagoras and his Associates",
    conflictsWith: ["pherecydes-death-vermin", "pherecydes-death-corycus"],
  },
  {
    id: "pherecydes-flourished-ol59",
    subject: "Pherecydes",
    property: "birthDate",
    value: "Lived in the 59th Olympiad (544/541 BCE)",
    valueType: "literal",
    ref: "1.121",
    grc: "Γέγονε δὲ κατὰ τὴν πεντηκοστὴν καὶ ἐνάτην Ὀλυμπιάδα",
    certainty: "asserted",
  },
];
