/**
 * Curated claims from Book 10 of Diogenes Laertius' Lives, cited to
 * Hicks section ids (book.section). See kg-claims.ts for the model and
 * curation rules. Source-internal: every claim cites a D.L. passage.
 */
import type { KgClaim } from "../kg-claims";

export const BOOK10_CLAIMS: KgClaim[] = [
  // -------------------------------------------------------------- Epicurus
  {
    id: "epicurus-parentage",
    subject: "Epicurus",
    property: "parentage",
    value:
      "Son of Neocles and Chaerestrate, a citizen of Athens of the deme Gargettus, of the family of the Philaidae",
    valueType: "literal",
    ref: "10.1",
    grc: "Ἐπίκουρος Νεοκλέους καὶ Χαιρεστράτης, Ἀθηναῖος, τῶν δήμων Γαργήττιος, γένους τοῦ τῶν Φιλαϊδῶν, ὥς φησι Μητρόδωρος ἐν τῷ Περὶ εὐγενείας",
    certainty: "asserted",
    note: "The Philaidae descent per Metrodorus in his On Noble Birth.",
  },
  {
    id: "epicurus-birthplace-athens",
    subject: "Epicurus",
    property: "birthPlace",
    value: "Athens",
    valueType: "place",
    ref: "10.1",
    grc: "Ἐπίκουρος Νεοκλέους καὶ Χαιρεστράτης, Ἀθηναῖος, τῶν δήμων Γαργήττιος, γένους τοῦ τῶν Φιλαϊδῶν, ὥς φησι Μητρόδωρος ἐν τῷ Περὶ εὐγενείας",
    certainty: "asserted",
    note: "A citizen of the deme Gargettus, of the family of the Philaidae, as Metrodorus says.",
  },
  {
    id: "epicurus-raised-samos",
    subject: "Epicurus",
    property: "livedIn",
    value: "Samos",
    valueType: "place",
    ref: "10.1",
    grc: "Ἐπίκουρος Νεοκλέους καὶ Χαιρεστράτης, Ἀθηναῖος, τῶν δήμων Γαργήττιος, γένους τοῦ τῶν Φιλαϊδῶν, ὥς φησι Μητρόδωρος ἐν τῷ Περὶ εὐγενείας",
    certainty: "reported",
    // 10.1: "He is said by Heraclides in his Epitome of Sotion ... to have
    // been brought up at Samos" - Heraclides Lembus transmits Sotion.
    accordingTo: "Heraclides",
    chain: [{ authority: "Sotion" }],
    note: "Brought up at Samos after the Athenians sent settlers there.",
  },
  {
    id: "epicurus-lived-colophon",
    subject: "Epicurus",
    property: "livedIn",
    value: "Colophon",
    valueType: "place",
    ref: "10.1",
    grc: "Ἐπίκουρος Νεοκλέους καὶ Χαιρεστράτης, Ἀθηναῖος, τῶν δήμων Γαργήττιος, γένους τοῦ τῶν Φιλαϊδῶν, ὥς φησι Μητρόδωρος ἐν τῷ Περὶ εὐγενείας",
    certainty: "asserted",
    note: "Left Athens to join his father in Colophon after the settlers were expelled from Samos; gathered disciples there.",
  },
  {
    id: "epicurus-affiliated-garden",
    subject: "Epicurus",
    property: "affiliatedWith",
    value: "Garden (Epicurus)",
    valueType: "school",
    ref: "10.2",
    grc: "καὶ μέχρι μέν τινος κατʼ ἐπιμιξίαν τοῖς ἄλλοις φιλοσοφεῖν, ἔπειτα ἰδίᾳ ἀπο- 〈φαίνεσθαι〉 τὴν ἀπʼ αὐτοῦ κληθεῖσαν αἵρεσιν συστήσαντα",
    certainty: "asserted",
    note: "Founded the school called after him; his friends lived with him in his garden (10.10).",
  },
  {
    id: "epicurus-education-philosophy-at-fourteen",
    subject: "Epicurus",
    property: "education",
    value:
      "Turned to philosophy at fourteen, in contempt of the schoolmasters who could not explain Hesiod's 'chaos'",
    valueType: "literal",
    ref: "10.2",
    grc: "καὶ μέχρι μέν τινος κατʼ ἐπιμιξίαν τοῖς ἄλλοις φιλοσοφεῖν, ἔπειτα ἰδίᾳ ἀπο- 〈φαίνεσθαι〉 τὴν ἀπʼ αὐτοῦ κληθεῖσαν αἵρεσιν συστήσαντα. ἐφάψασθαι δὲ φιλοσοφίας αὐτός φησιν ἔτη γεγονὼς τετταρεσκαίδεκα",
    certainty: "reported",
    accordingTo: "Apollodorus the Epicurean",
    note: "Apollodorus the Epicurean (the Kepotyrannos, 10.25), in the first book of his Life of Epicurus; Epicurus himself said he began philosophy at fourteen (10.2).",
  },
  {
    id: "epicurus-teacher-nausiphanes",
    subject: "Epicurus",
    property: "studiedUnder",
    value: "Nausiphanes",
    valueType: "person",
    ref: "10.13",
    grc: "ἀλλʼ οὐδὲ Λεύκιππόν τινα γεγενῆσθαί φησι φιλόσοφον, οὔτε αὐτὸς οὔτε Ἕρμαρχος, ὃν ἔνιοί φασι καὶ Ἀπολλόδωρος ὁ Ἐπικούρειος διδάσκαλον Δημοκρίτου γεγενῆσθαι",
    certainty: "disputed",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
    note: "Also of Praxiphanes, per Apollodorus in his Chronology.",
    conflictsWith: ["epicurus-self-taught"],
  },
  {
    id: "epicurus-self-taught",
    subject: "Epicurus",
    property: "education",
    value: "Self-taught: studied under no one",
    valueType: "literal",
    ref: "10.13",
    grc: "Τοῦτον Ἀπολλόδωρος ἐν Χρονικοῖς Ναυσιφάνους ἀκοῦσαί φησι καὶ Πραξιφάνους",
    certainty: "disputed",
    accordingTo: "Epicurus (letter to Eurylochus)",
    conflictsWith: ["epicurus-teacher-nausiphanes"],
  },
  {
    id: "epicurus-teacher-xenocrates",
    subject: "Epicurus",
    property: "studiedUnder",
    value: "Xenocrates",
    valueType: "philosopher",
    ref: "10.13",
    grc: "ἀλλʼ οὐδὲ Λεύκιππόν τινα γεγενῆσθαί φησι φιλόσοφον, οὔτε αὐτὸς οὔτε Ἕρμαρχος, ὃν ἔνιοί φασι καὶ Ἀπολλόδωρος ὁ Ἐπικούρειος διδάσκαλον Δημοκρίτου γεγενῆσθαι",
    certainty: "reported",
    accordingTo: "Demetrius the Magnesian",
  },
  {
    id: "epicurus-birth-ol109",
    subject: "Epicurus",
    property: "birthDate",
    value:
      "Born in the third year of the 109th Olympiad, on the 7th of Gamelion (341 BCE)",
    valueType: "literal",
    ref: "10.14",
    grc: "Ἐγεννήθη δέ, φησὶν Ἀπολλόδωρος ἐν Χρονικοῖς, κατὰ τὸ τρίτον ἔτος τῆς ἐνάτης καὶ ἑκατοστῆς Ὀλυμπιάδος ἐπὶ Σωσιγένους ἄρχοντος μηνὸς γαμηλιῶνος ἑβδόμῃ, ἔτεσιν ὕστερον τῆς Πλάτωνος τελευτῆς ἑπτά.",
    certainty: "reported",
    accordingTo: "Apollodorus",
    sourceWork: "Chronology",
    note: "In the archonship of Sosigenes, the seventh year after the death of Plato.",
  },
  {
    id: "epicurus-death-ol127",
    subject: "Epicurus",
    property: "deathDate",
    value:
      "Died in the second year of the 127th Olympiad, in the archonship of Pytharatus, aged 72 (270 BCE)",
    valueType: "literal",
    ref: "10.15",
    grc: "τελευτῆσαι κατὰ τὸ δεύτερον ἔτος τῆς ἑβδόμης καὶ εἰκοστῆς καὶ ἑκατοστῆς Ὀλυμπιάδος",
    certainty: "asserted",
  },
  {
    id: "epicurus-died-athens",
    subject: "Epicurus",
    property: "deathPlace",
    value: "Athens",
    valueType: "place",
    ref: "10.15",
    grc: "ἔπειτα οὕτως εἰς Ἀθήνας μετελθεῖν καὶ τελευτῆσαι κατὰ τὸ δεύτερον ἔτος τῆς ἑβδόμης καὶ εἰκοστῆς καὶ ἑκατοστῆς Ὀλυμπιάδος",
    certainty: "asserted",
    note: "Removed to Athens at thirty-seven and died there.",
  },
  {
    id: "epicurus-death-manner",
    subject: "Epicurus",
    property: "mannerOfDeath",
    value:
      "Died of renal calculus (a stone) after a fortnight's illness; entered a bronze bath of lukewarm water, asked for unmixed wine, and drank it",
    valueType: "literal",
    ref: "10.15",
    grc: "τελευτῆσαι δʼ αὐτὸν λίθῳ τῶν οὔρων ἐπισχεθέντων, ὥς φησι καὶ Ἕρμαρχος ἐν ἐπιστολαῖς, ἡμέρας νοσήσαντα τεσσαρεσκαίδεκα. ὅτε καί φησιν Ἕρμιππος ἐμβάντα αὐτὸν εἰς πύελον χαλκῆν κεκραμένην ὕδατι θερμῷ καὶ αἰτήσαντα ἄκρατον ῥοφῆσαι",
    certainty: "reported",
    accordingTo: "Hermarchus",
    note: "The bath and wine per Hermippus (10.16).",
  },
  // ---- Family, will and school succession
  {
    id: "epicurus-successor-hermarchus",
    subject: "Epicurus",
    property: "praised",
    value: "Hermarchus",
    valueType: "person",
    ref: "10.16",
    grc: "τοῖς τε φίλοις παραγγείλαντα τῶν δογμάτων μεμνῆσθαι, οὕτω τελευτῆσαι",
    certainty: "asserted",
    note: "Hermarchus son of Agemortus, a Mitylenaean, took over the School; Epicurus left him all his books (10.21).",
  },
  {
    id: "epicurus-will-garden",
    subject: "Epicurus",
    property: "writings",
    value:
      "By his will, gave and bequeathed all his property to Amynomachus and Timocrates, placing the garden at the disposal of Hermarchus and the School in perpetuity, and manumitting his slaves Mys, Nicias, Lycon and Phaedrium",
    valueType: "literal",
    ref: "10.16",
    grc: "τοῖς τε φίλοις παραγγείλαντα τῶν δογμάτων μεμνῆσθαι, οὕτω τελευτῆσαι",
    certainty: "asserted",
    note: "The will (10.16-21) endows funeral offerings, birthday and monthly commemorations, and provision for Metrodorus' children.",
  },
  {
    id: "epicurus-praised-metrodorus",
    subject: "Epicurus",
    property: "praised",
    value: "Metrodorus",
    valueType: "person",
    ref: "10.22",
    grc: "Μαθητὰς δὲ ἔσχε πολλοὺς μέν, σφόδρα δὲ ἐλλογίμους Μητρόδωρον Ἀθηναίου ἢ Τιμοκρατους καὶ Σάνδης Λαμψακηνόν· ὃς ἀφʼ οὗ τὸν ἄνδρα ἔγνω, οὐκ ἀπέστη ἀπʼ αὐτοῦ πλὴν ἓξ μηνῶν εἰς τὴν οἰκείαν, ἔπειτʼ ἐπανῆλθε.",
    certainty: "asserted",
    note: "His foremost disciple, of Lampsacus; showed dauntless courage in meeting troubles and death (10.23).",
  },
  // ---- Writings
  {
    id: "epicurus-works-volume",
    subject: "Epicurus",
    property: "writings",
    value: "The most prolific of all philosophers: about three hundred rolls",
    valueType: "literal",
    ref: "10.26",
    grc: "γέγραπται δὲ μαρτύριον ἔξωθεν ἐν αὐτοῖς οὐδέν, ἀλλʼ αὐτοῦ εἰσιν Ἐπικούρου φωναί",
    certainty: "asserted",
    note: "Contain not a single citation from other authors; it is Epicurus himself who speaks throughout.",
  },
  {
    id: "epicurus-wrote-on-nature",
    subject: "Epicurus",
    property: "wrote",
    value: "On Nature (37 books)",
    valueType: "work",
    ref: "10.27",
    grc: "Περὶ φύσεως ἑπτὰ καὶ τριάκοντα",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-atoms-void",
    subject: "Epicurus",
    property: "wrote",
    value: "Of Atoms and Void",
    valueType: "work",
    ref: "10.27",
    grc: "Περὶ ἀτόμων καὶ κενοῦ",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-of-love",
    subject: "Epicurus",
    property: "wrote",
    value: "Of Love",
    valueType: "work",
    ref: "10.27",
    grc: "Περὶ ἔρωτος",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-epitome-physicists",
    subject: "Epicurus",
    property: "wrote",
    value: "Epitome of Objections to the Physicists",
    valueType: "work",
    ref: "10.27",
    grc: "Ἐπιτομὴ τῶν πρὸς τοὺς φυσικούς",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-against-megarians",
    subject: "Epicurus",
    property: "wrote",
    value: "Against the Megarians",
    valueType: "work",
    ref: "10.27",
    grc: "Πρὸς τοὺς Μεγαρικούς",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-problems",
    subject: "Epicurus",
    property: "wrote",
    value: "Problems",
    valueType: "work",
    ref: "10.27",
    grc: "Διαπορίαι",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-sovran-maxims",
    subject: "Epicurus",
    property: "wrote",
    value: "Sovran Maxims (Kyriai Doxai)",
    valueType: "work",
    ref: "10.27",
    grc: "Κύριαι δόξαι",
    certainty: "asserted",
    greek: "Κύριαι Δόξαι",
  },
  {
    id: "epicurus-wrote-choice-avoidance",
    subject: "Epicurus",
    property: "wrote",
    value: "Of Choice and Avoidance",
    valueType: "work",
    ref: "10.27",
    grc: "Περὶ αἱρέσεων καὶ φυγῶν",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-of-the-end",
    subject: "Epicurus",
    property: "wrote",
    value: "Of the End",
    valueType: "work",
    ref: "10.27",
    grc: "Περὶ τέλους",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-canon",
    subject: "Epicurus",
    property: "wrote",
    value: "Of the Standard, a work entitled Canon",
    valueType: "work",
    ref: "10.27",
    grc: "Περὶ κριτηρίου ἢ Κανών",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-chaeredemus",
    subject: "Epicurus",
    property: "wrote",
    value: "Chaeredemus",
    valueType: "work",
    ref: "10.27",
    grc: "Χαιρέδημος",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-of-the-gods",
    subject: "Epicurus",
    property: "wrote",
    value: "Of the Gods",
    valueType: "work",
    ref: "10.27",
    grc: "Περὶ θεῶν",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-of-piety",
    subject: "Epicurus",
    property: "wrote",
    value: "Of Piety",
    valueType: "work",
    ref: "10.27",
    grc: "Περὶ ὁσιότητος.",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-of-human-life",
    subject: "Epicurus",
    property: "wrote",
    value: "Of Human Life (4 books)",
    valueType: "work",
    ref: "10.28",
    grc: "Περὶ βίων δʼ",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-of-just-dealing",
    subject: "Epicurus",
    property: "wrote",
    value: "Of Just Dealing",
    valueType: "work",
    ref: "10.28",
    grc: "Περὶ δικαιοπραγίας",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-symposium",
    subject: "Epicurus",
    property: "wrote",
    value: "Symposium",
    valueType: "work",
    ref: "10.28",
    grc: "Συμπόσιον",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-of-vision",
    subject: "Epicurus",
    property: "wrote",
    value: "Of Vision",
    valueType: "work",
    ref: "10.28",
    grc: "Περὶ τοῦ ὁρᾶν",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-of-fate",
    subject: "Epicurus",
    property: "wrote",
    value: "Of Fate",
    valueType: "work",
    ref: "10.28",
    grc: "Περὶ εἱμαρμένης",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-of-images",
    subject: "Epicurus",
    property: "wrote",
    value: "Of Images",
    valueType: "work",
    ref: "10.28",
    grc: "Περὶ τῆς ἐν τῇ ἀτόμῳ γωνίας",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-of-presentation",
    subject: "Epicurus",
    property: "wrote",
    value: "Of Presentation",
    valueType: "work",
    ref: "10.28",
    grc: "Περὶ ἁφῆς",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-of-music",
    subject: "Epicurus",
    property: "wrote",
    value: "Of Music",
    valueType: "work",
    ref: "10.28",
    grc: "Περὶ μουσικῆς",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-of-justice-virtues",
    subject: "Epicurus",
    property: "wrote",
    value: "Of Justice and the other Virtues",
    valueType: "work",
    ref: "10.28",
    grc: "Περὶ δικαιοσύνης καὶ τῶν ἄλλων ἀρετῶν",
    certainty: "asserted",
  },
  {
    id: "epicurus-wrote-of-kingship",
    subject: "Epicurus",
    property: "wrote",
    value: "Of Kingship",
    valueType: "work",
    ref: "10.28",
    grc: "Περὶ βασιλείας",
    certainty: "asserted",
  },
  // ---- Praise and criticism
  {
    id: "epicurus-criticized-democritus",
    subject: "Epicurus",
    property: "criticized",
    value: "Democritus",
    valueType: "philosopher",
    ref: "10.8",
    grc: "Ἡράκλειτόν τε κυκητὴν καὶ Δημόκριτον Ληρόκριτον καὶ Ἀντίδωρον Σαννίδωρον·",
    certainty: "disputed",
    note: "Said to have called him 'Lerocritus' (nonsense-monger); D.L. holds the hostile witnesses to be mad (10.9).",
  },
  {
    id: "epicurus-criticized-nausiphanes",
    subject: "Epicurus",
    property: "criticized",
    value: "Nausiphanes",
    valueType: "person",
    ref: "10.8",
    grc: "πλεύμονά τε αὐτὸν ἐκάλει καὶ ἀγράμματον καὶ ἀπατεῶνα καὶ πόρνην·",
    certainty: "reported",
    note: "Called him jelly-fish, an illiterate, a fraud, and a trollop; wrote against him in the On Nature (10.7).",
  },
  {
    id: "epicurus-criticized-plato-school",
    subject: "Epicurus",
    property: "criticized",
    value: "Plato",
    valueType: "philosopher",
    ref: "10.8",
    grc: "τούς τε περὶ Πλάτωνα Διονυσοκόλακας καὶ αὐτὸν Πλάτωνα χρυσοῦν",
    certainty: "reported",
    note: "Called Plato's school the toadies of Dionysius, and their master himself 'the golden Plato'.",
  },
  {
    id: "epicurus-favoured-anaxagoras",
    subject: "Epicurus",
    property: "praised",
    value: "Anaxagoras",
    valueType: "philosopher",
    ref: "10.12",
    grc: "Μάλιστα δʼ ἀπεδέχετο, φησὶ Διοκλῆς, τῶν ἀρχαίων Ἀναξαγόραν, καίτοι ἔν τισιν ἀντειρηκὼς αὐτῷ, καὶ Ἀρχέλαον τὸν Σωκράτους διδάσκαλον.",
    certainty: "reported",
    accordingTo: "Diocles",
    note: "Among the early philosophers his favourite, though he occasionally disagreed with him.",
  },
  // ---- Doctrines: division of philosophy and canonic
  {
    id: "epicurus-doctrine-three-parts",
    subject: "Epicurus",
    property: "heldDoctrine",
    value: "Philosophy is divided into three parts: Canonic, Physics, Ethics",
    valueType: "doctrine",
    ref: "10.30",
    grc: "τὸ μὲν οὖν κανονικὸν ἐφόδους ἐπὶ τὴν πραγματείαν ἔχει, καὶ ἔστιν ἐν ἑνὶ τῷ ἐπιγραφομένῳ Κανών· τὸ δὲ φυσικὸν τὴν περὶ φύσεως θεωρίαν πᾶσαν, καὶ ἔστιν ἐν ταῖς Περὶ φύσεως βίβλοις ἑπτὰ καὶ τριάκοντα καὶ ταῖς ἐπιστολαῖς κατὰ στοιχεῖον· τὸ δὲ ἠθικὸν τὰ περὶ αἱρέσεως καὶ φυγῆς·",
    certainty: "asserted",
    note: "Canonic is the introduction and criterion; physics the theory of nature; ethics the facts of choice and aversion.",
  },
  {
    id: "epicurus-doctrine-reject-dialectic",
    subject: "Epicurus",
    property: "heldDoctrine",
    value: "Dialectic is rejected as superfluous",
    valueType: "doctrine",
    ref: "10.31",
    grc: "Τὴν διαλεκτικὴν ὡς παρέλκουσαν ἀποδοκιμάζουσιν· ἀρκεῖν γὰρ τοὺς φυσικοὺς χωρεῖν κατὰ τοὺς τῶν πραγμάτων φθόγγους.",
    certainty: "asserted",
    note: "The physicists should be content to employ the ordinary terms for things.",
  },
  {
    id: "epicurus-doctrine-criteria-truth",
    subject: "Epicurus",
    property: "heldDoctrine",
    value:
      "Sensations, preconceptions and feelings are the standards (criteria) of truth",
    valueType: "doctrine",
    greek: "κριτήρια",
    ref: "10.31",
    grc: "ἐν τοίνυν τῷ Κανόνι λέγων ἐστὶν ὁ Ἐπίκουρος κριτήρια τῆς ἀληθείας εἶναι τὰς αἰσθήσεις καὶ προλήψεις καὶ τὰ πάθη, οἱ δʼ Ἐπικούρειοι καὶ τὰς φανταστικὰς ἐπιβολὰς τῆς διανοίας.",
    certainty: "asserted",
    note: "In The Canon; the Epicureans add mental presentations. Every sensation is devoid of reason and cannot be refuted.",
  },
  {
    id: "epicurus-doctrine-preconception",
    subject: "Epicurus",
    property: "heldDoctrine",
    value:
      "By preconception (prolepsis) is meant a universal idea stored in the mind, a recollection of an oft-presented external object",
    valueType: "doctrine",
    greek: "πρόληψις",
    ref: "10.33",
    grc: "Τὴν δὲ πρόληψιν λέγουσιν οἱονεὶ κατάληψιν ἢ δόξαν ὀρθὴν ἢ ἔννοιαν ἢ καθολικὴν νόησιν ἐναποκειμένην, τουτέστι μνήμην τοῦ πολλάκις ἔξωθεν φανέντος",
    certainty: "asserted",
  },
  // ---- Doctrines: physics
  {
    id: "epicurus-doctrine-nothing-from-nonexistent",
    subject: "Epicurus",
    property: "heldDoctrine",
    value: "Nothing comes into being out of what is non-existent",
    valueType: "doctrine",
    ref: "10.38",
    grc: "πρῶτον μὲν ὅτι οὐδὲν γίνεται ἐκ τοῦ μὴ ὄντος.",
    certainty: "asserted",
    note: "Letter to Herodotus; nor does anything perish into the non-existent.",
  },
  {
    id: "epicurus-doctrine-bodies-void",
    subject: "Epicurus",
    property: "heldDoctrine",
    value: "The whole of being consists of bodies and space (void)",
    valueType: "doctrine",
    greek: "κενόν",
    ref: "10.39",
    grc: "τὸ πᾶν ἐστι σώματα καὶ κενόν· σώματα μὲν γὰρ ὡς ἔστιν, αὐτὴ ἡ αἴσθησις ἐπὶ πάντων μαρτυρεῖ",
    certainty: "asserted",
    note: "Space is called also void, place and intangible nature.",
  },
  {
    id: "epicurus-doctrine-atoms",
    subject: "Epicurus",
    property: "heldDoctrine",
    value:
      "The first beginnings are indivisible, unchangeable corporeal entities (atoms)",
    valueType: "doctrine",
    greek: "ἄτομα",
    ref: "10.41",
    grc: "ταῦτα δέ ἐστιν ἄτομα καὶ ἀμετάβλητα, εἴπερ μὴ μέλλει πάντα εἰς τὸ μὴ ὂν φθαρήσεσθαι, ἀλλʼ ἰσχύοντα ὑπομένειν ἐν ταῖς διαλύσεσι τῶν συγκρίσεων, πλήρη τὴν φύσιν ὄντα, οἷα δὴ οὐκ ἔχοντα ὅπῃ ἢ ὅπως διαλυθήσεται. ὥστε τὰς ἀρχὰς ἀτόμους ἀναγκαῖον εἶναι σωμάτων φύσεις.",
    certainty: "asserted",
    note: "Atoms are in continual motion through all eternity (10.43); they differ only in shape, size and weight (10.44).",
  },
  {
    id: "epicurus-doctrine-infinite-sum",
    subject: "Epicurus",
    property: "heldDoctrine",
    value:
      "The sum of things is infinite, unlimited both by the multitude of atoms and the extent of the void",
    valueType: "doctrine",
    greek: "ἄπειρον",
    ref: "10.41",
    grc: "Καὶ μὴν καὶ τῷ πλήθει τῶν σωμάτων ἄπειρόν ἐστι τὸ πᾶν καὶ τῷ μεγέθει τοῦ κενοῦ.",
    certainty: "asserted",
  },
  {
    id: "epicurus-doctrine-infinite-worlds",
    subject: "Epicurus",
    property: "heldDoctrine",
    value: "There is an infinite number of worlds, some like this world, others unlike it",
    valueType: "doctrine",
    ref: "10.45",
    grc: "Ἀλλὰ μὴν καὶ κόσμοι ἄπειροί εἰσιν, οἵ θʼ ὅμοιοι τούτῳ καὶ ἀνόμοιοι.",
    certainty: "asserted",
  },
  {
    id: "epicurus-doctrine-images",
    subject: "Epicurus",
    property: "heldDoctrine",
    value:
      "Thin films or images (eidola) stream off the surface of bodies and cause perception",
    valueType: "doctrine",
    greek: "εἴδωλα",
    ref: "10.46",
    grc: "τύποι ὁμοιοσχήμονες τοῖς στερεμνίοις εἰσί, λεπτότησιν ἀπέχοντες μακρὰν τῶν φαινομένων.",
    certainty: "asserted",
  },
  // ---- Doctrines: ethics (letter to Menoeceus and Sovran Maxims)
  {
    id: "epicurus-doctrine-gods-blessed",
    subject: "Epicurus",
    property: "heldDoctrine",
    value:
      "The gods are living beings immortal and blessed, exempt from trouble, anger and partiality; they neither trouble themselves nor others",
    valueType: "doctrine",
    ref: "10.123",
    grc: "πρῶτον μὲν τὸν θεὸν ζῷον ἄφθαρτον καὶ μακάριον νομίζων, ὡς ἡ κοινὴ τοῦ θεοῦ νόησις ὑπεγράφη, μηθὲν μήτε τῆς ἀφθαρσίας ἀλλότριον μήτε τῆς μακαριότητος ἀνοίκειον αὐτῷ πρόσαπτε·",
    certainty: "asserted",
    note: "Letter to Menoeceus; restated in Sovran Maxim 1 (10.139).",
  },
  {
    id: "epicurus-doctrine-death-nothing",
    subject: "Epicurus",
    property: "heldDoctrine",
    value:
      "Death is nothing to us, for good and evil imply sentience and death is the privation of all sentience",
    valueType: "doctrine",
    ref: "10.124",
    grc: "Συνέθιζε δὲ ἐν τῷ νομίζειν μηδὲν πρὸς ἡμᾶς εἶναι τὸν θάνατον· ἐπεὶ πᾶν ἀγαθὸν καὶ κακὸν ἐν αἰσθήσει· στέρησις δέ ἐστιν αἰσθήσεως ὁ θάνατος.",
    certainty: "asserted",
    note: "When we are, death is not come; and when death is come, we are not (10.125). Sovran Maxim 2 (10.139).",
  },
  {
    id: "epicurus-doctrine-desires",
    subject: "Epicurus",
    property: "heldDoctrine",
    value:
      "Of desires some are natural and necessary, some natural but not necessary, and some neither natural nor necessary but due to illusory opinion",
    valueType: "doctrine",
    greek: "ἐπιθυμίαι",
    ref: "10.127",
    grc: "Ἀναλογιστέον δὲ ὡς τῶν ἐπιθυμιῶν αἱ μέν εἰσι φυσικαί, αἱ δὲ κεναί. καὶ τῶν φυσικῶν αἱ μὲν ἀναγκαῖαι, αἱ δὲ φυσικαὶ μόνον·",
    certainty: "asserted",
    note: "Restated in Sovran Maxim 29 (10.149).",
  },
  {
    id: "epicurus-doctrine-pleasure",
    subject: "Epicurus",
    property: "heldDoctrine",
    value: "Pleasure is the beginning and end (telos) of the blessed life",
    valueType: "doctrine",
    greek: "τέλος",
    ref: "10.128",
    grc: "καὶ διὰ τοῦτο τὴν ἡδονὴν ἀρχὴν καὶ τέλος λέγομεν εἶναι τοῦ μακαρίως ζῆν·",
    certainty: "asserted",
    note: "Letter to Menoeceus; pleasure the alpha and omega of a blessed life.",
  },
  {
    id: "epicurus-doctrine-ataraxia",
    subject: "Epicurus",
    property: "heldDoctrine",
    value:
      "The end of all our actions is to be free from pain (in the body) and from trouble (in the soul), i.e. tranquillity",
    valueType: "doctrine",
    greek: "ἀταραξία",
    ref: "10.128",
    grc: "τούτου γὰρ χάριν πάντα πράττομεν, ὅπως μήτε ἀλγῶμεν μήτε ταρβῶμεν· ὅταν δʼ ἅπαξ τοῦτο περὶ ἡμᾶς γένηται, λύεται πᾶς ὁ τῆς ψυχῆς χειμών",
    certainty: "asserted",
    note: "By pleasure is meant the absence of pain in the body and of trouble in the soul (10.131).",
  },
  {
    id: "epicurus-doctrine-pleasure-kinetic-katastematic",
    subject: "Epicurus",
    property: "heldDoctrine",
    value:
      "Pleasure is of two kinds: that which is a state of rest (peace of mind, freedom from pain) and that which consists in motion (joy and delight)",
    valueType: "doctrine",
    ref: "10.136",
    grc: "ἡ μὲν γὰρ ἀταραξία καὶ ἀπονία καταστηματικαί εἰσιν ἡδοναί· ἡ δὲ χαρὰ καὶ ἡ εὐφροσύνη κατὰ κίνησιν ἐνεργείᾳ βλέπονται.",
    certainty: "asserted",
    note: "He differs here from the Cyrenaics, who admit only pleasure in motion.",
  },
  {
    id: "epicurus-doctrine-prudence",
    subject: "Epicurus",
    property: "heldDoctrine",
    value:
      "Prudence (phronesis) is the greatest good and the source of all the other virtues, more precious even than philosophy",
    valueType: "doctrine",
    greek: "φρόνησις",
    ref: "10.132",
    grc: "τούτων δὲ πάντων ἀρχὴ καὶ τὸ μέγιστον ἀγαθὸν φρόνησις· διὸ καὶ φιλοσοφίας τιμιώτερον ὑπάρχει φρόνησις, ἐξ ἧς αἱ λοιπαὶ πᾶσαι πεφύκασιν ἀρεταί",
    certainty: "asserted",
    note: "We cannot live pleasantly without living prudently, honourably and justly, nor conversely (Sovran Maxim 5, 10.140).",
  },
  {
    id: "epicurus-doctrine-limit-of-pleasure",
    subject: "Epicurus",
    property: "heldDoctrine",
    value: "The magnitude of pleasure reaches its limit in the removal of all pain",
    valueType: "doctrine",
    ref: "10.139",
    grc: "Ὅρος τοῦ μεγέθους τῶν ἡδονῶν ἡ παντὸς τοῦ ἀλγοῦντος ὑπεξαίρεσις.",
    certainty: "asserted",
    note: "Sovran Maxim 3.",
  },
  {
    id: "epicurus-doctrine-friendship",
    subject: "Epicurus",
    property: "heldDoctrine",
    value:
      "Of all the means to ensure happiness throughout life, by far the most important is the acquisition of friends",
    valueType: "doctrine",
    greek: "φιλία",
    ref: "10.148",
    grc: "Ὧν ἡ σοφία παρασκευάζεται εἰς τὴν τοῦ ὅλου βίου μακαριότητα, πολὺ μέγιστόν ἐστιν ἡ τῆς φιλίας κτῆσις.",
    certainty: "asserted",
    note: "Sovran Maxim 27.",
  },
  {
    id: "epicurus-doctrine-natural-justice",
    subject: "Epicurus",
    property: "heldDoctrine",
    value:
      "Natural justice is a compact of expediency, to prevent one man from harming or being harmed by another; there is no absolute justice",
    valueType: "doctrine",
    greek: "δικαιοσύνη",
    ref: "10.150",
    grc: "Τὸ τῆς φύσεως δίκαιόν ἐστι σύμβολον τοῦ συμφέροντος εἰς τὸ μὴ βλάπτειν ἀλλήλους μηδὲ βλάπτεσθαι.",
    certainty: "asserted",
    note: "Sovran Maxims 31-33.",
  },
];
