import type { WorkFacet } from "./types";

/**
 * Aristotle's catalogue (D.L. 5.22-27).
 *
 * Judgment calls:
 * - Metaphysical/ontological titles (On the Idea, On the Unit, Of Logical
 *   Principle, On Genera and Species) classify under dialectic (see barrel
 *   header); psychology (Of the Soul) under physics, the ancient placement.
 * - Extracts and expositions of other philosophers' works are doxography.
 * - Victor lists and dramatic records are chronology; "Claims advanced"
 *   (the Dikaiomata pleaded for Greek cities) is politics but NOT philosophy.
 * - "A Collection of Arts" and the Handbook collections are the surveys of
 *   earlier rhetorical technai → rhetoric.
 * - "Two books of Routine Instruction" is too opaque for a topic.
 * - Shared nodes curated here: "Concerning Love", "Exhortation to
 *   Philosophy", "Of Wealth", "On Nature (three books)" (all + Theophrastus),
 *   "Of the Good (three books)" (+ Strato).
 * - Survival: extant only where the catalogue entry is standardly
 *   identified with a surviving treatise: Categories, De Interpretatione,
 *   Prior Analytics (the eight books = an older division of the extant
 *   two), Greater Posterior Analytics (two books), Poetics (one book, the
 *   extant single book - NOT the separate two-book "Treatise on the Art of
 *   Poetry"), "On Animals (nine books)" = the Historia Animalium,
 *   Mechanics (extant but spurious - transmission, not authenticity), and
 *   "Five books of Ethics" = the Eudemian Ethics less the books shared
 *   with the Nicomachean. Doubtful matches stay lost - never guess:
 *   "Politics (two books)" vs the extant eight, "Of the Soul (one book)"
 *   vs the extant three, "Two books of the Art of Rhetoric" vs the extant
 *   three, Methodics vs the Topics.
 */
export const ARISTOTLE_WORKS: Record<string, WorkFacet> = {
  "A Collection of Arts [that is, Handbooks (two books)": { form: "prose", topic: "rhetoric" },
  "A Collection or Compendium (two books)": { form: "prose", topic: "miscellany" },
  "A Reply to the Pythagoreans (one book)": { form: "prose", topic: "physics" },
  "A Reply to the Writings of Alcmaeon (one book)": { form: "prose", topic: "physics" },
  "A Reply to the Writings of Gorgias (one book)": { form: "prose", topic: "dialectic" },
  "A Reply to the Writings of Melissus (one book)": { form: "prose", topic: "physics" },
  "A Reply to the Writings of Xenophanes (one book)": { form: "prose", topic: "physics" },
  "A Reply to the Writings of Zeno (one book)": { form: "prose", topic: "dialectic" },
  "A selection of Dissections (one book)": { form: "prose", topic: "physics" },
  "A Treatise on the Art of Poetry (two books)": { form: "prose", topic: "poetics" },
  "Affections or Qualities (one book)": { form: "prose", topic: "physics" },
  "Alexander, or a Plea for Colonies (one book)": { form: "prose", topic: "politics" },
  "Analogies (one book)": { form: "prose", topic: "dialectic" },
  "Another Collection of Handbooks (two books)": { form: "prose", topic: "rhetoric" },
  "Art, a Handbook (one book)": { form: "prose", topic: "rhetoric" },
  "Categories (one book)": { form: "prose", topic: "dialectic", survival: "extant" },
  "Claims advanced (one book)": { form: "prose", topic: "politics", philosophical: false },
  "Compendium of the Art of Theodectes (one book)": { form: "prose", topic: "rhetoric" },
  "Concerning Astronomy (one book)": { form: "prose", topic: "astronomy" },
  "Concerning Delphi (one book)": { form: "prose", topic: "history" },
  "Concerning Division (one book)": { form: "prose", topic: "dialectic" },
  "Concerning Logical Division (one book)": { form: "prose", topic: "dialectic" },
  "Concerning Love (one book)": { form: "prose", topic: "ethics" },
  "Concerning Mathematics (one book)": { form: "prose", topic: "mathematics" },
  "Concerning Memory (one book)": { form: "prose", topic: "physics" },
  "Concerning Method (one book)": { form: "prose", topic: "dialectic" },
  "Concerning Nature (one book)": { form: "prose", topic: "physics" },
  "Concerning Optics (one book)": { form: "prose", topic: "mathematics" },
  "Concerning Physiognomy (one book)": { form: "prose", topic: "physics" },
  "Concerning Syllogism with Definitions (one book)": { form: "prose", topic: "dialectic" },
  "Controversial Propositions (one book)": { form: "prose", topic: "dialectic" },
  "Criticism of the List of Pythian Victors (one book)": { form: "prose", topic: "chronology" },
  "De Interpretatione (one book)": { form: "prose", topic: "dialectic", survival: "extant" },
  "Definitions (thirteen books)": { form: "prose", topic: "dialectic" },
  "Definitions prefixed to the Topics (seven books)": { form: "prose", topic: "dialectic" },
  "Descriptions of Genera (fourteen books)": { form: "prose", topic: "dialectic" },
  "Divisions of Enthymemes (one book)": { form: "prose", topic: "rhetoric" },
  "Dramatic Records (one book)": { form: "prose", topic: "chronology" },
  "Dramatic Victories at the Dionysia (one book)": { form: "prose", topic: "chronology" },
  "Eight books of Dissections": { form: "prose", topic: "physics" },
  "Eight books of Methodics": { form: "prose", topic: "dialectic" },
  "Eight books of Prior Analytics": { form: "prose", topic: "dialectic", survival: "extant" },
  "Exhortation to Philosophy (one book)": { form: "prose", topic: "ethics" },
  "Extracts from Plato’s Laws (three books)": { form: "prose", topic: "doxography" },
  "Extracts from the Republic (two books)": { form: "prose", topic: "doxography" },
  "Extracts from the Timaeus and from the Works of Archytas (one book)": { form: "prose", topic: "doxography" },
  "Five books of Ethics": { form: "prose", topic: "ethics", survival: "extant" },
  "Four books of Laws": { form: "prose", topic: "politics" },
  "In reply to Democritus (one book)": { form: "prose", topic: "physics" },
  "Laws of the Mess-table (one book)": { form: "prose", topic: "miscellany" },
  "Letters of Selymbrians": { form: "prose", topic: "letters" },
  "Letters to Alexander (four books)": { form: "prose", topic: "letters" },
  "Letters to Antipater (nine books)": { form: "prose", topic: "letters" },
  "Letters to Philip": { form: "prose", topic: "letters" },
  "Logical Divisions (seventeen books)": { form: "prose", topic: "dialectic" },
  "Mechanics (one book)": { form: "prose", topic: "mathematics", survival: "extant" },
  "Menexenus (one book)": { form: "prose", topic: "ethics" },
  "Miscellaneous Notes (twelve books)": { form: "prose", topic: "miscellany" },
  "Nerinthus (one book)": { form: "prose", topic: "ethics" },
  "Objections (one book)": { form: "prose", topic: "dialectic" },
  "Of Degree (one book)": { form: "prose", topic: "dialectic" },
  "Of Friendship (one book)": { form: "prose", topic: "ethics" },
  "Of Household Management (one book)": { form: "prose", topic: "ethics" },
  "Of Just Actions (two books)": { form: "prose", topic: "ethics" },
  "Of Justice (four books)": { form: "prose", topic: "ethics" },
  "Of Logical Principle (one book)": { form: "prose", topic: "dialectic" },
  "Of Motion (one book)": { form: "prose", topic: "physics" },
  "Of Passions or of Anger (one book)": { form: "prose", topic: "ethics" },
  "Of Pleasure (one book)": { form: "prose", topic: "ethics" },
  "Of Prayer (one book)": { form: "prose", topic: "ethics" },
  "Of Problems (one book)": { form: "prose", topic: "physics" },
  "Of Science (one book)": { form: "prose", topic: "dialectic" },
  "Of Sciences (one book)": { form: "prose", topic: "dialectic" },
  "Of Taking Counsel (one book)": { form: "prose", topic: "ethics" },
  "Of the Desirable and the Contingent (one book)": { form: "prose", topic: "dialectic" },
  "Of the Good (three books)": { form: "prose", topic: "ethics" },
  "Of the Greater Good (one book)": { form: "prose", topic: "ethics" },
  "Of the Soul (one book)": { form: "prose", topic: "physics" },
  "Of the Statesman (two books)": { form: "prose", topic: "politics" },
  "Of Tragedies (one book)": { form: "prose", topic: "poetics" },
  "Of Wealth (one book)": { form: "prose", topic: "ethics" },
  "On Animals (nine books)": { form: "prose", topic: "physics", survival: "extant" },
  "On being or having been affected (one book)": { form: "prose", topic: "physics" },
  "On Composite Animals (one book)": { form: "prose", topic: "physics" },
  "On Contraries (one book)": { form: "prose", topic: "dialectic" },
  "On Controversial Questions (two books)": { form: "prose", topic: "dialectic" },
  "On Dialectical Questioning and Answering (two books)": { form: "prose", topic: "dialectic" },
  "On Diction (two books)": { form: "prose", topic: "rhetoric" },
  "On Education (one book)": { form: "prose", topic: "ethics" },
  "On Elements (three books)": { form: "prose", topic: "physics" },
  "On Essential Attributes (one book)": { form: "prose", topic: "dialectic" },
  "On Genera and Species (one book)": { form: "prose", topic: "dialectic" },
  "On Kingship (one book)": { form: "prose", topic: "politics" },
  "On Motion (one book)": { form: "prose", topic: "physics" },
  "On Music (one book)": { form: "prose", topic: "music" },
  "On Nature (three books)": { form: "prose", topic: "physics" },
  "On Noble Birth (one book)": { form: "prose", topic: "ethics" },
  "On Philosophy (three books)": { form: "prose", topic: "physics" },
  "On Plants (two books)": { form: "prose", topic: "physics" },
  "On Pleasure (one book)": { form: "prose", topic: "ethics" },
  "On Poets (three books)": { form: "prose", topic: "poetics" },
  "On Rhetoric, or Grylus (one book)": { form: "prose", topic: "rhetoric" },
  "On Sterility (one book)": { form: "prose", topic: "physics" },
  "On the Animals of Fable (one book)": { form: "prose", topic: "physics" },
  "On the Beautiful (one book)": { form: "prose", topic: "ethics" },
  "On the Idea (one book)": { form: "prose", topic: "dialectic" },
  "On the Magnet (one book)": { form: "prose", topic: "physics" },
  "On the Philosophy of Archytas (three books)": { form: "prose", topic: "doxography" },
  "On the Philosophy of Speusippus and Xenocrates (one book)": { form: "prose", topic: "doxography" },
  "On the Pythagoreans (one book)": { form: "prose", topic: "doxography" },
  "On the Unit (one book)": { form: "prose", topic: "dialectic" },
  "On the Various Meanings of Terms or Expressions where a Determinant is added (one book)": { form: "prose", topic: "dialectic" },
  "On the Voluntary (one book)": { form: "prose", topic: "ethics" },
  "Poetics (one book)": { form: "prose", topic: "poetics", survival: "extant" },
  "Politics (two books)": { form: "prose", topic: "politics" },
  "Preface to Commonplaces (one book)": { form: "prose", topic: "dialectic" },
  "Problems taken from the works of Democritus (two books)": { form: "prose", topic: "physics" },
  "Prognostics of Storms (one book)": { form: "prose", topic: "astronomy" },
  "Propositions (one book)": { form: "prose", topic: "dialectic" },
  "Propositions concerning Virtue (two books)": { form: "prose", topic: "ethics" },
  "Proverbs (one book)": { form: "prose", topic: "grammar" },
  "Rhetorical Enthymemes (one book)": { form: "prose", topic: "rhetoric" },
  "Six books of Homeric Problems": { form: "prose", topic: "poetics" },
  "Solutions of Controversial Questions (four books)": { form: "prose", topic: "dialectic" },
  "Sophistical Divisions (four books)": { form: "prose", topic: "dialectic" },
  "Syllogisms (one book)": { form: "prose", topic: "dialectic" },
  "Symposium (one book)": { form: "prose", topic: "ethics" },
  "The Sophist (one book)": { form: "prose", topic: "dialectic" },
  "Theses concerning Friendship (two books)": { form: "prose", topic: "ethics" },
  "Theses concerning Love (four books)": { form: "prose", topic: "ethics" },
  "Theses concerning the Soul (one book)": { form: "prose", topic: "physics" },
  "Theses for Refutation (twenty-five books)": { form: "prose", topic: "dialectic" },
  "To Ariston (one book)": { form: "prose", topic: "letters" },
  "To Hephaestion (one book)": { form: "prose", topic: "letters" },
  "To Mentor (one book)": { form: "prose", topic: "letters" },
  "To Olympias (one book)": { form: "prose", topic: "letters" },
  "To Philoxenus (one book)": { form: "prose", topic: "letters" },
  "To Themistagoras (one book)": { form: "prose", topic: "letters" },
  "Two books concerning Medicine": { form: "prose", topic: "medicine" },
  "Two books of Greater Posterior Analytics": { form: "prose", topic: "dialectic", survival: "extant" },
  "Two books of Refutations": { form: "prose", topic: "dialectic" },
  "Two books of Routine Instruction": { form: "prose", topic: null },
  "Two books of Syllogisms": { form: "prose", topic: "dialectic" },
  "Two books of the Art of Rhetoric": { form: "prose", topic: "rhetoric" },
  "Two books of Topics criticizing the Definitions": { form: "prose", topic: "dialectic" },
  "Victors at Olympia (one book)": { form: "prose", topic: "chronology" },
  "Victors at the Pythian Games (one book)": { form: "prose", topic: "chronology" },
};
