import type { WorkFacet } from "./types";

/**
 * Theophrastus' catalogue (D.L. 5.42-50), the longest in the Lives.
 *
 * Judgment calls:
 * - Several labels are mangled TEI joins of two adjacent catalogue entries
 *   ("Of Calumny, one book.] Of Becoming (one book)"...). Where both halves
 *   share a topic the topic is asserted (metres+diction → grammar); where
 *   they diverge (protreptic+numbers, characters+truth) the topic is null.
 * - Pathology titles (Epilepsy, Pestilences, Suffocation, Melancholy,
 *   Fainting, Sweating Sickness, Vertigo...) are medicine; physiology of
 *   sensation, sleep and plants is physics.
 * - Epitomes and "On the Writings of X" are doxography, including the
 *   Epitomes of Aristotle's work on Animals (consistency over content).
 * - Crimes, punishment, illegalities and riots sit with the political-legal
 *   works → politics; delivery, preludes, examples and the artless proofs
 *   ("On Unscientific Proofs") are rhetoric.
 * - Acicharus (the Ahiqar book), Evias and Megacles are too opaque: topic
 *   null. "Another treatise with the same title" refers to its catalogue
 *   neighbour and cannot stand alone: topic null.
 * - Shared nodes curated elsewhere: "Concerning Love", "Exhortation to
 *   Philosophy", "Of Wealth", "On Nature (three books)" (aristotle.ts);
 *   "Of Happiness (one book)", "Solutions (one book)" (plato-academy.ts);
 *   "Of the Gods (three books)" (peripatos.ts, with Strato).
 * - Survival: the extant botany and opuscula are marked extant - Character
 *   Sketches, Botanical Causes, On Fire, On Precious Stones, Of the Senses,
 *   On Smells, On Vertigo and Dizziness, On Fatigues, On Sweating Sickness
 *   (De sudore), and On Indivisible Lines (transmitted in Aristotle's
 *   corpus). The merged TEI node "A Reply to the Physical Philosophers ...
 *   Of Botanical Researches" pairs a lost polemic with the extant Historia
 *   Plantarum → survival null. Physical Opinions survives in extensive
 *   verbatim quotation (Simplicius and the doxographers) → excerpts. The
 *   two wind titles ("On Winds" / "Of the Winds") are an ambiguous pair
 *   against the extant De ventis → both stay lost (never guess a homonym).
 */
export const THEOPHRASTUS_WORKS: Record<string, WorkFacet> = {
  "A Collection of Problems (five books)": { form: "prose", topic: "physics" },
  "A Compendium of Arguments (one book)": { form: "prose", topic: "dialectic" },
  "A Compendium of the Writings of Xenocrates (one book)": { form: "prose", topic: "doxography" },
  "A Political Treatise dealing with important Crises (four books)": { form: "prose", topic: "politics" },
  "A Reply to Anaxagoras (one book)": { form: "prose", topic: "physics" },
  "A Reply to the Academics (one book)": { form: "prose", topic: "dialectic" },
  "A Reply to the Physical Philosophers, one book Of Botanical Researches (ten books)": { form: "prose", topic: "physics", survival: null },
  "Acicharus (one book)": { form: "prose", topic: null },
  "Afternoon Essays (two books)": { form: "prose", topic: "miscellany" },
  "An Epitome of Physics (two books)": { form: "prose", topic: "physics" },
  "An Exhortation to Philosophy, one book.] On Numbers (one book)": { form: "prose", topic: null },
  "Another tract on the Art of Poetry (one book)": { form: "prose", topic: "poetics" },
  "Another Treatise on Love (one book)": { form: "prose", topic: "ethics" },
  "Another treatise on Pleasure (one book)": { form: "prose", topic: "ethics" },
  "Another treatise with the same title (one book)": { form: "prose", topic: null },
  "Arithmetical Researches on Growth (one book)": { form: "prose", topic: "mathematics" },
  "Astronomical Research (six books)": { form: "prose", topic: "astronomy" },
  "Callisthenes, or On Bereavement (one book)": { form: "prose", topic: "ethics" },
  "Character Sketches (one book)": { form: "prose", topic: "ethics", survival: "extant" },
  "Character Sketches, one book.] On Truth and Falsehood (one book)": { form: "prose", topic: null },
  "Characteristics of Virtues (one book)": { form: "prose", topic: "ethics" },
  "Compendium of the Writings of Diogenes (one book)": { form: "prose", topic: "doxography" },
  "Compendium on the Doctrines of Metrodorus (one book)": { form: "prose", topic: "doxography" },
  "Concerning Conversation (one book)": { form: "prose", topic: "ethics" },
  "Concerning Empedocles (one book)": { form: "prose", topic: "doxography" },
  "Concerning Politics (two books)": { form: "prose", topic: "politics" },
  "Definitions concerning the Diction of Syllogisms (one book)": { form: "prose", topic: "dialectic" },
  "Divisions (two books)": { form: "prose", topic: "dialectic" },
  "Eight books of Physics": { form: "prose", topic: "physics" },
  "Eighteen books of Refutative Arguments": { form: "prose", topic: "dialectic" },
  "Epitome of Analytics (one book)": { form: "prose", topic: "dialectic" },
  "Epitome of Physical Opinions (one book)": { form: "prose", topic: "doxography" },
  "Epitome of Plato’s Republic (two books)": { form: "prose", topic: "doxography" },
  "Epitomes of Aristotle’s work on Animals (six books)": { form: "prose", topic: "doxography" },
  "Evias (one book)": { form: "prose", topic: null },
  "Geometrical Researches (four books)": { form: "prose", topic: "mathematics" },
  "Harmonics (one book)": { form: "prose", topic: "music" },
  "How States can best be governed (one book)": { form: "prose", topic: "politics" },
  "Introduction to Propositions (eighteen books)": { form: "prose", topic: "dialectic" },
  "Lecture Notes of Aristotle or Theophrastus (six books)": { form: "prose", topic: "miscellany" },
  "Lecture-Notes (one book)": { form: "prose", topic: "miscellany" },
  "Lectures on Ethics (one book)": { form: "prose", topic: "ethics" },
  "Materials for Argument, or Contrarieties (one book)": { form: "prose", topic: "dialectic" },
  "Megacles (one book)": { form: "prose", topic: null },
  "Megarian Treatise (one book)": { form: "prose", topic: "dialectic" },
  "Of Ambition (two books)": { form: "prose", topic: "ethics" },
  "Of Animals (seven books)": { form: "prose", topic: "physics" },
  "Of Animals reputed to be spiteful (one book)": { form: "prose", topic: "physics" },
  "Of Animals that burrow (one book)": { form: "prose", topic: "physics" },
  "Of Animals which bite or gore (one book)": { form: "prose", topic: "physics" },
  "Of Botanical Causes (eight books)": { form: "prose", topic: "physics", survival: "extant" },
  "Of Calumny, one book.] Of Becoming (one book)": { form: "prose", topic: null },
  "Of Causes (one book)": { form: "prose", topic: "physics" },
  "Of Comedy (one book)": { form: "prose", topic: "poetics" },
  "Of Discoveries (two books)": { form: "prose", topic: "history" },
  "Of Education or of the Virtues or of Temperance (one book)": { form: "prose", topic: "ethics" },
  "Of Experience (one book)": { form: "prose", topic: "dialectic" },
  "Of False Pleasure (one book)": { form: "prose", topic: "ethics" },
  "Of Flattery (one book)": { form: "prose", topic: "ethics" },
  "Of Friendship (three books)": { form: "prose", topic: "ethics" },
  "Of Good Fortune (one book)": { form: "prose", topic: "ethics" },
  "Of Kingship (one book)": { form: "prose", topic: "politics" },
  "Of Legislators (three books)": { form: "prose", topic: "politics" },
  "Of Mankind (one book)": { form: "prose", topic: "physics" },
  "Of Melancholy (one book)": { form: "prose", topic: "medicine" },
  "Of Mental Derangement (one book)": { form: "prose", topic: "medicine" },
  "Of Metres, one book.] Of Diction (one book)": { form: "prose", topic: "grammar" },
  "Of Old Age (one book)": { form: "prose", topic: "ethics" },
  "Of Paralysis (one book)": { form: "prose", topic: "medicine" },
  "Of Petrifactions (two books)": { form: "prose", topic: "physics" },
  "Of Piety (one book)": { form: "prose", topic: "ethics" },
  "Of Pleasure according to Aristotle (one book)": { form: "prose", topic: "ethics" },
  "Of Politics (six books)": { form: "prose", topic: "politics" },
  "Of Praise (one book)": { form: "prose", topic: "rhetoric" },
  "Of Punishment (two books)": { form: "prose", topic: "politics" },
  "Of Salt, Nitre and Alum (one book)": { form: "prose", topic: "physics" },
  "Of Secretion (one book)": { form: "prose", topic: "physics" },
  "Of Social Customs (four books)": { form: "prose", topic: "ethics" },
  "Of Sudden Appearances (one book)": { form: "prose", topic: "physics" },
  "Of Suffocation (one book)": { form: "prose", topic: "medicine" },
  "Of the Animals which are confined to Dry Land (one book)": { form: "prose", topic: "physics" },
  "Of the Best Constitution (one book)": { form: "prose", topic: "politics" },
  "Of the Education of Kings (one book)": { form: "prose", topic: "politics" },
  "Of the Happiness of the Gods (one book)": { form: "prose", topic: "physics" },
  "Of the Heavens (one book)": { form: "prose", topic: "physics" },
  "Of the Intelligence and Character of Animals (one book)": { form: "prose", topic: "physics" },
  "Of the Ludicrous (one book)": { form: "prose", topic: "poetics" },
  "Of the Order of the World (one book)": { form: "prose", topic: "physics" },
  "Of the Sea (one book)": { form: "prose", topic: "physics" },
  "Of the Senses (one book)": { form: "prose", topic: "physics", survival: "extant" },
  "Of the Voluntary (one book)": { form: "prose", topic: "ethics" },
  "Of the Winds (one book)": { form: "prose", topic: "physics" },
  "Of the Wise (one book)": { form: "prose", topic: "ethics" },
  "Of those which change their Colours (one book)": { form: "prose", topic: "physics" },
  "Of Tyranny (one book)": { form: "prose", topic: "politics" },
  "Of Various Schemes of Life (three books)": { form: "prose", topic: "ethics" },
  "Of Virtue (one book)": { form: "prose", topic: "ethics" },
  "On Acting (one book)": { form: "prose", topic: "rhetoric" },
  "On Affirmation and Negation (one book)": { form: "prose", topic: "dialectic" },
  "On Animals": { form: "prose", topic: "physics" },
  "On Animals produced spontaneously (one book)": { form: "prose", topic: "physics" },
  "On Calumny (one book)": { form: "prose", topic: "ethics" },
  "On Coagulation and Liquefaction (one book)": { form: "prose", topic: "physics" },
  "On Consultation (one book)": { form: "prose", topic: "ethics" },
  "On Crimes (one book)": { form: "prose", topic: "politics" },
  "On Data (one book)": { form: "prose", topic: "dialectic" },
  "On Democritus (one book)": { form: "prose", topic: "doxography" },
  "On Differences (one book)": { form: "prose", topic: "dialectic" },
  "On Enthymemes (one book)": { form: "prose", topic: "rhetoric" },
  "On Epilepsy (one book)": { form: "prose", topic: "medicine" },
  "On Example (one book)": { form: "prose", topic: "rhetoric" },
  "On Fainting (one book)": { form: "prose", topic: "medicine" },
  "On Fatigues (one book)": { form: "prose", topic: "medicine", survival: "extant" },
  "On Festivals (one book)": { form: "prose", topic: "history" },
  "On Fire (two books)": { form: "prose", topic: "physics", survival: "extant" },
  "On Flavours, Colours and Flesh (one book)": { form: "prose", topic: "physics" },
  "On Forensic Speeches (one book)": { form: "prose", topic: "rhetoric" },
  "On Frenzy (one book)": { form: "prose", topic: "medicine" },
  "On Fruits": { form: "prose", topic: "physics" },
  "On Gratitude (one book)": { form: "prose", topic: "ethics" },
  "On Greater and Less (one book)": { form: "prose", topic: "dialectic" },
  "On Hair (one book)": { form: "prose", topic: "physics" },
  "On Honey (one book)": { form: "prose", topic: "physics" },
  "On Hot and Cold (one book)": { form: "prose", topic: "physics" },
  "On Illegalities (one book)": { form: "prose", topic: "politics" },
  "On Indivisible Lines (one book)": { form: "prose", topic: "mathematics", survival: "extant" },
  "On Intoxication (one book)": { form: "prose", topic: "ethics" },
  "On Introduction and Narrative (one book)": { form: "prose", topic: "rhetoric" },
  "On Judgement (one book)": { form: "prose", topic: "dialectic" },
  "On Judging of Syllogisms (one book)": { form: "prose", topic: "dialectic" },
  "On Juices (five books)": { form: "prose", topic: "physics" },
  "On Laws (one book)": { form: "prose", topic: "politics" },
  "On Measures (one book)": { form: "prose", topic: "mathematics" },
  "On Meteorology (one book)": { form: "prose", topic: "physics" },
  "On Mines (two books)": { form: "prose", topic: "physics" },
  "On Motion (three books)": { form: "prose", topic: "physics" },
  "On Music (three books)": { form: "prose", topic: "music" },
  "On Negation (one book)": { form: "prose", topic: "dialectic" },
  "On Pestilences (one book)": { form: "prose", topic: "medicine" },
  "On Physical Problems (one book)": { form: "prose", topic: "physics" },
  "On Physics (eighteen books)": { form: "prose", topic: "physics" },
  "On Precious Stones (one book)": { form: "prose", topic: "physics", survival: "extant" },
  "On Problems in Physics, one book.] What are the methods of attaining Knowledge (one book)": { form: "prose", topic: null },
  "On Proverbs (one book)": { form: "prose", topic: "grammar" },
  "On Relevant Arguments (one book)": { form: "prose", topic: "dialectic" },
  "On Research (one book)": { form: "prose", topic: "dialectic" },
  "On Simple Problems (one book)": { form: "prose", topic: "physics" },
  "On Sleep and Dreams (one book)": { form: "prose", topic: "physics" },
  "On Smells (one book)": { form: "prose", topic: "physics", survival: "extant" },
  "On Solecisms (one book)": { form: "prose", topic: "grammar" },
  "On Species or Forms (two books)": { form: "prose", topic: "dialectic" },
  "On Sweating Sickness (one book)": { form: "prose", topic: "medicine", survival: "extant" },
  "On Symptoms (one book)": { form: "prose", topic: "medicine" },
  "On Taking an Oath (one book)": { form: "prose", topic: "ethics" },
  "On the Analysis of Syllogisms (one book)": { form: "prose", topic: "dialectic" },
  "On the Art of Poetry (one book)": { form: "prose", topic: "poetics" },
  "On the Art of Rhetoric (one book)": { form: "prose", topic: "rhetoric" },
  "On the Astronomy of Democritus (one book)": { form: "prose", topic: "astronomy" },
  "On the Diversity of Sounds uttered by Animals of the same Species (one book)": { form: "prose", topic: "physics" },
  "On the Education of Children (one book)": { form: "prose", topic: "ethics" },
  "On the Eruption in Sicily (one book)": { form: "prose", topic: "physics" },
  "On the Fallacy known as the Liar (three books)": { form: "prose", topic: "dialectic" },
  "On the Musicians (one book)": { form: "prose", topic: "music" },
  "On the Passions (one book)": { form: "prose", topic: "ethics" },
  "On the solution of Syllogisms (one book)": { form: "prose", topic: "dialectic" },
  "On the Writings of Anaxagoras (one book)": { form: "prose", topic: "doxography" },
  "On the Writings of Anaximenes (one book)": { form: "prose", topic: "doxography" },
  "On the Writings of Archelaus (one book)": { form: "prose", topic: "doxography" },
  "On Things generally admitted (one book)": { form: "prose", topic: "dialectic" },
  "On Times of Crisis (two books)": { form: "prose", topic: "politics" },
  "On Tumult or Riot (one book)": { form: "prose", topic: "politics" },
  "On Unscientific Proofs (one book)": { form: "prose", topic: "rhetoric" },
  "On Vertigo and Dizziness (one book)": { form: "prose", topic: "medicine", survival: "extant" },
  "On Vision (four books)": { form: "prose", topic: "physics" },
  "On Visual Images or Emanations (one book)": { form: "prose", topic: "physics" },
  "On Water (three books)": { form: "prose", topic: "physics" },
  "On Winds (one book)": { form: "prose", topic: "physics" },
  "On Wine and Oil": { form: "prose", topic: "physics" },
  "One Dissertation on the Soul": { form: "prose", topic: "physics" },
  "Panegyrics on the Gods (one book)": { form: "prose", topic: "rhetoric" },
  "Polemical discussion on the Theory of Eristic Argument": { form: "prose", topic: "dialectic" },
  "Preludes (one book)": { form: "prose", topic: "rhetoric" },
  "Problems in Politics, Ethics, Physics, and in the Art of Love (one book)": { form: "prose", topic: "miscellany" },
  "Prolegomena to Topics (one book)": { form: "prose", topic: "dialectic" },
  "Relating to Aeschylus (one book)": { form: "prose", topic: "poetics" },
  "Relating to Definitions (two books)": { form: "prose", topic: "dialectic" },
  "Remarks upon Definitions (one book)": { form: "prose", topic: "dialectic" },
  "Rhetorical Precepts (one book)": { form: "prose", topic: "rhetoric" },
  "Seven books of Posterior Analytics": { form: "prose", topic: "dialectic" },
  "Sixteen books of Physical Opinions": { form: "prose", topic: "doxography", survival: "excerpts" },
  "Ten books of an Epitome of Laws": { form: "prose", topic: "politics" },
  "The History of Theological Inquiry (six books)": { form: "prose", topic: "doxography" },
  "The Special Commonplaces of the Treatises on Rhetoric (seventeen books)": { form: "prose", topic: "rhetoric" },
  "Theses (twenty-four books)": { form: "prose", topic: "dialectic" },
  "Three books of Definitions": { form: "prose", topic: "dialectic" },
  "Three books of Letters": { form: "prose", topic: "letters" },
  "Three books of Polemical Objections": { form: "prose", topic: "dialectic" },
  "Three books of Prior Analytics": { form: "prose", topic: "dialectic" },
  "To Casander on Kingship (one book)": { form: "prose", topic: "politics" },
  "Two books of Classified Topics": { form: "prose", topic: "dialectic" },
  "Two books of Lectures": { form: "prose", topic: "miscellany" },
  "Two books of Meteorology": { form: "prose", topic: "physics" },
  "Two books of Refutative Arguments": { form: "prose", topic: "dialectic" },
  "Two books of Sophisms": { form: "prose", topic: "dialectic" },
  "Two books of Topics": { form: "prose", topic: "dialectic" },
};
