/**
 * Pinned answer sets for validate-competency-counts.ts: one sorted list of
 * serialized result rows per competency question (as of July 2026 curation).
 * Each row is the projected variables in order, joined as name=value with
 * " | " separators; the list is sorted so ordering changes never fail.
 * After a deliberate curation change, update the drifted question entry to
 * the live rows printed in the failure output (or regenerate the whole
 * table from the validator failure listing).
 */
/**
 * Pinned Greek forms for every philosopher name appearing in a pinned
 * answer row (as of July 2026 curation). The /competency page's Entities
 * card shows each philosopher answer's Greek form next to the English
 * name; that form comes from the terms assembly in routes/competency.ts
 * (greekNameSpec(name)?.grc for KG-node row values), a payload the
 * answer-set pin above never sees. A drifted or deleted curated Greek
 * form would change the card silently, so validate-competency-counts.ts
 * re-derives each pinned name's Greek form and compares it here.
 * After a deliberate curation change, update the drifted entry to the
 * live form printed in the failure output.
 */
export const EXPECTED_GREEK_FORMS: Record<string, string> = {
  Aeschines: "Αἰσχίνης",
  Anaxarchus: "Ἀνάξαρχος",
  Anaximenes: "Ἀναξιμένης",
  Antisthenes: "Ἀντισθένης",
  Arcesilaus: "Ἀρκεσίλαος",
  Aristippus: "Ἀρίστιππος",
  "Ariston of Chios": "Ἀρίστων",
  Aristotle: "Ἀριστοτέλης",
  Bion: "Βίων",
  Carneades: "Καρνεάδης",
  Cebes: "Κέβης",
  Chrysippus: "Χρύσιππος",
  Cleanthes: "Κλεάνθης",
  Clitomachus: "Κλειτόμαχος",
  Crantor: "Κράντωρ",
  "Crates of Athens": "Κράτης",
  "Crates of Thebes": "Κράτης",
  Crito: "Κρίτων",
  "Demetrius of Phalerum": "Δημήτριος",
  Democritus: "Δημόκριτος",
  "Diogenes of Apollonia": "Διογένης",
  "Diogenes of Sinope": "Διογένης",
  "Dionysius the Renegade": "Διονύσιος",
  Epicurus: "Ἐπίκουρος",
  Epimenides: "Ἐπιμενίδης",
  Euclides: "Εὐκλείδης",
  Glaucon: "Γλαύκων",
  "Heraclides Ponticus": "Ἡρακλείδης",
  Heraclitus: "Ἡράκλειτος",
  Herillus: "Ἥριλλος",
  Hipparchia: "Ἱππαρχία",
  Lacydes: "Λακύδης",
  Leucippus: "Λεύκιππος",
  Lyco: "Λύκων",
  Melissus: "Μέλισσος",
  "Menedemus of Eretria": "Μενέδημος",
  "Menedemus the Cynic": "Μενέδημος",
  Menippus: "Μένιππος",
  Metrocles: "Μητροκλῆς",
  Monimus: "Μόνιμος",
  Onesicritus: "Ὀνησίκριτος",
  Parmenides: "Παρμενίδης",
  Phaedo: "Φαίδων",
  Plato: "Πλάτων",
  Polemo: "Πολέμων",
  Protagoras: "Πρωταγόρας",
  Pyrrho: "Πύρρων",
  Pythagoras: "Πυθαγόρας",
  Simmias: "Σιμμίας",
  Simon: "Σίμων",
  Socrates: "Σωκράτης",
  Speusippus: "Σπεύσιππος",
  Sphaerus: "Σφαῖρος",
  Strato: "Στράτων",
  Thales: "Θαλῆς",
  Theophrastus: "Θεόφραστος",
  Xenocrates: "Ξενοκράτης",
  Xenophanes: "Ξενοφάνης",
  Xenophon: "Ξενοφῶν",
  "Zeno of Citium": "Ζήνων",
  "Zeno of Elea": "Ζήνων",
};


/**
 * Pinned Greek forms for pinned answer-row values that are NOT
 * knowledge-graph nodes but classify as extra person/place/work terms in
 * routes/competency.ts (extraTerms): homonym bearers like "Zeno of
 * Tarsus", places, and work titles. Their Greek forms come from
 * greekNameSpec (person/place) or greekWorkTitleSpec (work), a payload
 * no other pin sees; a drifted or deleted curated form would change the
 * Entities card silently. `grc: null` pins that the term deliberately
 * ships without a Greek form. After a deliberate curation change, update
 * the drifted entry to the live form printed in the failure output.
 */
export const EXPECTED_EXTRA_TERM_GREEK_FORMS: Record<
  string,
  { type: "person" | "place" | "work"; grc: string | null }
> = {
  "A Collection of Arts [that is, Handbooks (two books)": { type: "work", grc: null },
  "A Collection or Compendium (two books)": { type: "work", grc: null },
  "A Reply to the Pythagoreans (one book)": { type: "work", grc: null },
  "A Reply to the Writings of Alcmaeon (one book)": { type: "work", grc: null },
  "A Reply to the Writings of Gorgias (one book)": { type: "work", grc: null },
  "A Reply to the Writings of Melissus (one book)": { type: "work", grc: null },
  "A Reply to the Writings of Xenophanes (one book)": { type: "work", grc: null },
  "A Reply to the Writings of Zeno (one book)": { type: "work", grc: null },
  "A selection of Dissections (one book)": { type: "work", grc: null },
  "A Treatise on the Art of Poetry (two books)": { type: "work", grc: null },
  "Affections or Qualities (one book)": { type: "work", grc: null },
  "Against the Megarians": { type: "work", grc: null },
  "Agrippa": { type: "person", grc: "Ἀγρίππας" },
  "Alcibiades": { type: "work", grc: null },
  "Alcibiades, or On the Nature of Man": { type: "work", grc: null },
  "Alexander": { type: "person", grc: "Ἀλέξανδρος" },
  "Alexander the Great": { type: "person", grc: "Ἀλέξανδρος" },
  "Alexander, or a Plea for Colonies (one book)": { type: "work", grc: null },
  "Analogies (one book)": { type: "work", grc: null },
  "Another Collection of Handbooks (two books)": { type: "work", grc: null },
  "Antigonus": { type: "person", grc: null },
  "Antigonus of Carystus": { type: "person", grc: "Ἀντίγονος" },
  "Apollodorus": { type: "person", grc: "Ἀπολλόδωρος" },
  "Apology of Socrates": { type: "work", grc: null },
  "Ariston": { type: "person", grc: "Ἀρίστων" },
  "Aristophanes": { type: "person", grc: "Ἀριστοφάνης" },
  "Aristophanes the Grammarian": { type: "person", grc: "Ἀριστοφάνης" },
  "Art, a Handbook (one book)": { type: "work", grc: null },
  "Athenodorus": { type: "person", grc: "Ἀθηνόδωρος" },
  "Athenodorus of Soli": { type: "person", grc: "Ἀθηνόδωρος" },
  // born-in-athens projects its ?birthplace label so the People & Places
  // question ships a real grc-carrying place chip (the once-dormant place
  // branch of the classifier). The Greek form is the curated Ἀθῆναι from
  // greek-names.ts.
  "Athens": { type: "place", grc: "Ἀθῆναι" },
  "Bryson": { type: "person", grc: "Βρύσων" },
  "Bryson the Achaean": { type: "person", grc: "Βρύσων" },
  "Callias": { type: "work", grc: null },
  "Categories (one book)": { type: "work", grc: null },
  "Chaeredemus": { type: "work", grc: null },
  "Charmides, or On Temperance": { type: "work", grc: null },
  "Claims advanced (one book)": { type: "work", grc: null },
  "Clitophon, or Introduction": { type: "work", grc: null },
  "Colotes of Lampsacus": { type: "person", grc: "Κωλώτης" },
  "Compendium of the Art of Theodectes (one book)": { type: "work", grc: null },
  "Concerning Astronomy (one book)": { type: "work", grc: null },
  "Concerning Delphi (one book)": { type: "work", grc: null },
  "Concerning Division (one book)": { type: "work", grc: null },
  "Concerning Logical Division (one book)": { type: "work", grc: null },
  "Concerning Love (one book)": { type: "work", grc: null },
  "Concerning Mathematics (one book)": { type: "work", grc: null },
  "Concerning Memory (one book)": { type: "work", grc: null },
  "Concerning Method (one book)": { type: "work", grc: null },
  "Concerning Nature (one book)": { type: "work", grc: null },
  "Concerning Optics (one book)": { type: "work", grc: null },
  "Concerning Physiognomy (one book)": { type: "work", grc: null },
  "Concerning Syllogism with Definitions (one book)": { type: "work", grc: null },
  "Controversial Propositions (one book)": { type: "work", grc: null },
  "Cratinus": { type: "person", grc: "Κρατῖνος" },
  "Cratinus the Younger": { type: "person", grc: "Κρατῖνος" },
  "Cratylus, or On Correctness of Names": { type: "work", grc: null },
  "Critias, or Story of Atlantis": { type: "work", grc: null },
  "Criticism of the List of Pythian Victors (one book)": { type: "work", grc: null },
  "Crito, or On what is to be done": { type: "work", grc: null },
  "Croton": { type: "person", grc: "Κρότων" },
  "Damon": { type: "person", grc: "Δάμων" },
  "Damon of Cyrene": { type: "person", grc: "Δάμων" },
  "De Interpretatione (one book)": { type: "work", grc: null },
  "Definitions (thirteen books)": { type: "work", grc: null },
  "Definitions prefixed to the Topics (seven books)": { type: "work", grc: null },
  "Demetrius": { type: "person", grc: "Δημήτριος" },
  "Demetrius of Magnesia": { type: "person", grc: "Δημήτριος" },
  "Demetrius of Troezen": { type: "person", grc: "Δημήτριος" },
  "Demetrius the epic poet": { type: "person", grc: "Δημήτριος" },
  "Demetrius the Magnesian": { type: "person", grc: "Δημήτριος" },
  "Descriptions of Genera (fourteen books)": { type: "work", grc: null },
  "Diodorus": { type: "person", grc: "Διόδωρος" },
  "Diodorus of Ephesus": { type: "person", grc: "Διόδωρος" },
  "Diogenes": { type: "person", grc: "Διογένης" },
  "Diogenes Laertius": { type: "person", grc: "Διογένης" },
  "Diogenes of Smyrna": { type: "person", grc: "Διογένης" },
  "Dionysius the Elder": { type: "person", grc: "Διονύσιος" },
  "Dionysius the Stoic": { type: "person", grc: "Διονύσιος" },
  "Dionysius the Younger": { type: "person", grc: "Διονύσιος" },
  "Dioscurides": { type: "person", grc: "Διοσκουρίδης" },
  "Dioscurides of Cyprus": { type: "person", grc: "Διοσκουρίδης" },
  "Divisions of Enthymemes (one book)": { type: "work", grc: null },
  "Dramatic Records (one book)": { type: "work", grc: null },
  "Dramatic Victories at the Dionysia (one book)": { type: "work", grc: null },
  "Eight books of Dissections": { type: "work", grc: null },
  "Eight books of Methodics": { type: "work", grc: null },
  "Eight books of Prior Analytics": { type: "work", grc: null },
  "Epinomis, or Nocturnal Council": { type: "work", grc: null },
  "Epistles (thirteen in number)": { type: "work", grc: null },
  "Epitome of Objections to the Physicists": { type: "work", grc: null },
  "Euripides": { type: "work", grc: null },
  "Euthydemus, or The Eristic": { type: "work", grc: null },
  "Euthyphro, or On Holiness": { type: "work", grc: null },
  "Exhortation to Philosophy (one book)": { type: "work", grc: null },
  "Extracts from Plato’s Laws (three books)": { type: "work", grc: null },
  "Extracts from the Republic (two books)": { type: "work", grc: null },
  "Extracts from the Timaeus and from the Works of Archytas (one book)": { type: "work", grc: null },
  "Five books of Ethics": { type: "work", grc: null },
  "Four books of Laws": { type: "work", grc: null },
  "Gorgias, or On Rhetoric": { type: "work", grc: null },
  "Heraclides": { type: "person", grc: "Ἡρακλείδης" },
  "Heraclides of Heraclea": { type: "person", grc: "Ἡρακλείδης" },
  "Heraclides of Tarsus": { type: "person", grc: "Ἡρακλείδης" },
  "Heraclides the Sceptic": { type: "person", grc: "Ἡρακλείδης" },
  "Hermarchus": { type: "person", grc: "Ἕρμαρχος" },
  "Hipparchus, or The Lover of Gain": { type: "work", grc: null },
  "Hippias (major), or On Beauty": { type: "work", grc: null },
  "Hippias (minor), or On Falsehood": { type: "work", grc: null },
  "Idomeneus of Lampsacus": { type: "person", grc: "Ἰδομενεύς" },
  "In reply to Democritus (one book)": { type: "work", grc: null },
  "Ion, or On the Iliad": { type: "work", grc: null },
  "Laches, or On Courage": { type: "work", grc: null },
  "Laws of the Mess-table (one book)": { type: "work", grc: null },
  "Laws, or On Legislation": { type: "work", grc: null },
  "Leonteus": { type: "person", grc: "Λεοντεύς" },
  "Letters of Selymbrians": { type: "work", grc: null },
  "Letters to Alexander (four books)": { type: "work", grc: null },
  "Letters to Antipater (nine books)": { type: "work", grc: null },
  "Letters to Philip": { type: "work", grc: null },
  "Logical Divisions (seventeen books)": { type: "work", grc: null },
  "Lysis, or On Friendship": { type: "work", grc: null },
  "Mechanics (one book)": { type: "work", grc: null },
  "Menexenus (one book)": { type: "work", grc: null },
  "Menexenus, or The Funeral Oration": { type: "work", grc: null },
  "Meno, or On Virtue": { type: "work", grc: null },
  "Minos, or On Law": { type: "work", grc: null },
  "Miscellaneous Notes (twelve books)": { type: "work", grc: null },
  "Nerinthus (one book)": { type: "work", grc: null },
  "Objections (one book)": { type: "work", grc: null },
  "Of Atoms and Void": { type: "work", grc: null },
  "Of Choice and Avoidance": { type: "work", grc: null },
  "Of Degree (one book)": { type: "work", grc: null },
  "Of Fate": { type: "work", grc: null },
  "Of Friendship (one book)": { type: "work", grc: null },
  "Of Household Management (one book)": { type: "work", grc: null },
  "Of Human Life (4 books)": { type: "work", grc: null },
  "Of Images": { type: "work", grc: null },
  "Of Just Actions (two books)": { type: "work", grc: null },
  "Of Just Dealing": { type: "work", grc: null },
  "Of Justice (four books)": { type: "work", grc: null },
  "Of Justice and the other Virtues": { type: "work", grc: null },
  "Of Kingship": { type: "work", grc: null },
  "Of Logical Principle (one book)": { type: "work", grc: null },
  "Of Love": { type: "work", grc: null },
  "Of Motion (one book)": { type: "work", grc: null },
  "Of Music": { type: "work", grc: null },
  "Of Passions or of Anger (one book)": { type: "work", grc: null },
  "Of Piety": { type: "work", grc: null },
  "Of Pleasure (one book)": { type: "work", grc: null },
  "Of Prayer (one book)": { type: "work", grc: null },
  "Of Presentation": { type: "work", grc: null },
  "Of Problems (one book)": { type: "work", grc: null },
  "Of Science (one book)": { type: "work", grc: null },
  "Of Sciences (one book)": { type: "work", grc: null },
  "Of Taking Counsel (one book)": { type: "work", grc: null },
  "Of the Desirable and the Contingent (one book)": { type: "work", grc: null },
  "Of the End": { type: "work", grc: null },
  "Of the Gods": { type: "work", grc: "Περὶ θεῶν" },
  "Of the Good (three books)": { type: "work", grc: null },
  "Of the Greater Good (one book)": { type: "work", grc: null },
  "Of the Soul (one book)": { type: "work", grc: null },
  "Of the Standard, a work entitled Canon": { type: "work", grc: null },
  "Of the Statesman (two books)": { type: "work", grc: null },
  "Of the Wise (one book)": { type: "work", grc: "Περὶ τῶν σοφῶν" },
  "Of Tragedies (one book)": { type: "work", grc: null },
  "Of Vision": { type: "work", grc: null },
  "Of Wealth (one book)": { type: "work", grc: null },
  "On Animals (nine books)": { type: "work", grc: null },
  "On being or having been affected (one book)": { type: "work", grc: null },
  "On Composite Animals (one book)": { type: "work", grc: null },
  "On Contraries (one book)": { type: "work", grc: null },
  "On Controversial Questions (two books)": { type: "work", grc: null },
  "On Dialectical Questioning and Answering (two books)": { type: "work", grc: null },
  "On Diction (two books)": { type: "work", grc: null },
  "On Education (one book)": { type: "work", grc: null },
  "On Elements (three books)": { type: "work", grc: null },
  "On Essential Attributes (one book)": { type: "work", grc: null },
  "On Genera and Species (one book)": { type: "work", grc: null },
  "On Kingship (one book)": { type: "work", grc: null },
  "On Motion (one book)": { type: "work", grc: null },
  "On Music (one book)": { type: "work", grc: null },
  "On Nature (37 books)": { type: "work", grc: null },
  "On Nature (three books)": { type: "work", grc: null },
  "On Noble Birth (one book)": { type: "work", grc: null },
  "On Philosophy (three books)": { type: "work", grc: null },
  "On Plants (two books)": { type: "work", grc: null },
  "On Pleasure (one book)": { type: "work", grc: null },
  "On Poets (three books)": { type: "work", grc: null },
  "On Rhetoric, or Grylus (one book)": { type: "work", grc: null },
  "On Sterility (one book)": { type: "work", grc: null },
  "On the Animals of Fable (one book)": { type: "work", grc: null },
  "On the Beautiful (one book)": { type: "work", grc: null },
  "On the Idea (one book)": { type: "work", grc: null },
  "On the Magnet (one book)": { type: "work", grc: null },
  "On the Philosophy of Archytas (three books)": { type: "work", grc: null },
  "On the Philosophy of Speusippus and Xenocrates (one book)": { type: "work", grc: null },
  "On the Pythagoreans (one book)": { type: "work", grc: null },
  "On the Sages": { type: "work", grc: "Περὶ τῶν σοφῶν" },
  "On the Unit (one book)": { type: "work", grc: null },
  "On the Various Meanings of Terms or Expressions where a Determinant is added (one book)": { type: "work", grc: null },
  "On the Voluntary (one book)": { type: "work", grc: null },
  "Parmenides, or On Ideas": { type: "work", grc: null },
  "Phaedo, or On the Soul": { type: "work", grc: null },
  "Phaedrus, or On Love": { type: "work", grc: null },
  "Philebus, or On Pleasure": { type: "work", grc: null },
  "Phrynichus": { type: "work", grc: null },
  "Poetics (one book)": { type: "work", grc: null },
  "Politics (two books)": { type: "work", grc: null },
  "Polyaenus": { type: "person", grc: "Πολύαινος" },
  "Posidonius": { type: "person", grc: "Ποσειδώνιος" },
  "Posidonius of Alexandria": { type: "person", grc: "Ποσειδώνιος" },
  "Preface to Commonplaces (one book)": { type: "work", grc: null },
  "Problems": { type: "work", grc: null },
  "Problems taken from the works of Democritus (two books)": { type: "work", grc: null },
  "Prognostics of Storms (one book)": { type: "work", grc: null },
  "Propositions (one book)": { type: "work", grc: null },
  "Propositions concerning Virtue (two books)": { type: "work", grc: null },
  "Protagoras, or Sophists": { type: "work", grc: null },
  "Proverbs (one book)": { type: "work", grc: null },
  "Ptolemy of Cyrene": { type: "person", grc: "Πτολεμαῖος" },
  "Ptolemy Soter": { type: "person", grc: "Πτολεμαῖος" },
  "Republic": { type: "work", grc: "Πολιτεία" },
  "Rhetorical Enthymemes (one book)": { type: "work", grc: null },
  "Second Alcibiades, or On Prayer": { type: "work", grc: null },
  "Six books of Homeric Problems": { type: "work", grc: null },
  "Solutions of Controversial Questions (four books)": { type: "work", grc: null },
  "Sophist, or On Being": { type: "work", grc: null },
  "Sophistical Divisions (four books)": { type: "work", grc: null },
  "Sovran Maxims (Kyriai Doxai)": { type: "work", grc: null },
  "Statesman, or On Monarchy": { type: "work", grc: null },
  "Successions": { type: "work", grc: "Διαδοχαί" },
  "Successions of Philosophers": { type: "work", grc: "Διαδοχαί" },
  "Syllogisms (one book)": { type: "work", grc: null },
  "Symposium": { type: "work", grc: "Συμπόσιον" },
  "Symposium (one book)": { type: "work", grc: null },
  "Telauges": { type: "person", grc: "Τηλαύγης" },
  "The Banquet, or On the Good": { type: "work", grc: null },
  "The Rivals, or On Philosophy": { type: "work", grc: null },
  "The Sophist (one book)": { type: "work", grc: null },
  "Theaetetus, or On Knowledge": { type: "work", grc: null },
  "Theages, or On Philosophy": { type: "work", grc: null },
  "Themista": { type: "person", grc: "Θεμίστα" },
  "Theses concerning Friendship (two books)": { type: "work", grc: null },
  "Theses concerning Love (four books)": { type: "work", grc: null },
  "Theses concerning the Soul (one book)": { type: "work", grc: null },
  "Theses for Refutation (twenty-five books)": { type: "work", grc: null },
  "Timaeus, or On Nature": { type: "work", grc: null },
  "To Ariston (one book)": { type: "work", grc: null },
  "To Hephaestion (one book)": { type: "work", grc: null },
  "To Mentor (one book)": { type: "work", grc: null },
  "To Olympias (one book)": { type: "work", grc: null },
  "To Philoxenus (one book)": { type: "work", grc: null },
  "To Themistagoras (one book)": { type: "work", grc: null },
  "Two books concerning Medicine": { type: "work", grc: null },
  "Two books of Greater Posterior Analytics": { type: "work", grc: null },
  "Two books of Refutations": { type: "work", grc: null },
  "Two books of Routine Instruction": { type: "work", grc: null },
  "Two books of Syllogisms": { type: "work", grc: null },
  "Two books of the Art of Rhetoric": { type: "work", grc: null },
  "Two books of Topics criticizing the Definitions": { type: "work", grc: null },
  "Victors at Olympia (one book)": { type: "work", grc: null },
  "Victors at the Pythian Games (one book)": { type: "work", grc: null },
  "Zeno of Sidon": { type: "person", grc: "Ζήνων" },
  "Zeno of Tarsus": { type: "person", grc: "Ζήνων" },
  "Zeuxis": { type: "person", grc: "Ζεῦξις" },
  "Zeuxis Goniopus": { type: "person", grc: "Ζεῦξις" },
};

/**
 * Pinned Greek sect names for every school label reachable from a
 * competency question's Entities card (as of July 2026 curation): the
 * movements of the question's seed subgraph (schoolTerms in
 * routes/competency.ts) and answer-row values classified as movement
 * labels (the extraTerms "school" branch), both of which ship
 * greekSchoolGrc(label) from GREEK_SCHOOL_NAMES (greek-names.ts). No
 * other pin sees that payload, so a drifted or deleted curated entry
 * would change or drop a school chip's Greek sect name silently.
 * `null` pins a school label that deliberately ships English-only
 * (the Unaffiliated bucket is not a sect). After a deliberate curation
 * change, update the drifted entry to the live form printed in the
 * failure output.
 */
export const EXPECTED_SCHOOL_GREEK_FORMS: Record<string, string | null> = {
  Academy: "Ἀκαδημαϊκή",
  Atomist: "Ἀτομική",
  Cynic: "Κυνική",
  Cyrenaic: "Κυρηναϊκή",
  Eleatic: "Ἐλεατική",
  "Elian–Eretrian": "Ἠλιακὴ καὶ Ἐρετρική",
  "Epicurean (Garden)": "Ἐπικούρειος",
  "Ionian / Milesian": "Ἰωνική",
  Megarian: "Μεγαρική",
  Peripatos: "Περιπατητική",
  Pythagorean: "Πυθαγορική",
  Sceptic: "Σκεπτική",
  "Seven Sages": "οἱ ἑπτὰ σοφοί",
  Socratic: "Σωκρατική",
  Sophist: "Σοφιστική",
  Stoa: "Στωϊκή",
  Unaffiliated: null,
};

/**
 * Pinned Greek forms for every dropped-seed anchor of every competency
 * question (as of July 2026 curation): curated anchors without a Life
 * chapter (KNOWN_DROPPED_SEEDS / getDroppedSeeds in lib/competency.ts),
 * which routes/competency.ts ships on the Entities card as
 * { en: name, grc: greekNameSpec(name)?.grc }. Those names have no KG
 * node and no answer row, so no other pin sees that payload: a drifted
 * or deleted GREEK_NAMES entry for a dropped seed would silently change
 * or drop its Greek form while every existing pin stays green. Keyed by
 * question id, then seed name; `null` pins a seed that deliberately
 * ships without a Greek form. After a deliberate curation change,
 * update the drifted entry to the live form printed in the failure
 * output.
 */
export const EXPECTED_DROPPED_SEED_GREEK_FORMS: Record<
  string,
  Record<string, string | null>
> = {
  "homonymy-proper-names": {
    "Zeno of Sidon": "Ζήνων",
    "Diogenes Laertius": "Διογένης",
  },
};

export const EXPECTED_ANSWER_ROWS: Record<string, string[]> = {
  "stoa-members": [
    "name=Ariston of Chios",
    "name=Chrysippus",
    "name=Cleanthes",
    "name=Dionysius the Renegade",
    "name=Herillus",
    "name=Sphaerus",
    "name=Zeno of Citium",
  ],
  "academy-members": [
    "name=Arcesilaus",
    "name=Bion",
    "name=Carneades",
    "name=Clitomachus",
    "name=Crantor",
    "name=Crates of Athens",
    "name=Lacydes",
    "name=Plato",
    "name=Polemo",
    "name=Speusippus",
    "name=Xenocrates",
  ],
  "school-founders": [
    "name=Antisthenes | school=Cynic",
    "name=Aristippus | school=Cyrenaic",
    "name=Aristotle | school=Peripatos",
    "name=Epicurus | school=Epicurean (Garden)",
    "name=Euclides | school=Megarian",
    "name=Leucippus | school=Atomist",
    "name=Phaedo | school=Elian–Eretrian",
    "name=Plato | school=Academy",
    "name=Pyrrho | school=Sceptic",
    "name=Pythagoras | school=Pythagorean",
    "name=Socrates | school=Socratic",
    "name=Thales | school=Ionian / Milesian",
    "name=Xenophanes | school=Eleatic",
    "name=Zeno of Citium | school=Stoa",
  ],
  "cynic-line": [
    "name=Antisthenes",
    "name=Crates of Thebes",
    "name=Diogenes of Sinope",
    "name=Hipparchia",
    "name=Menedemus the Cynic",
    "name=Menippus",
    "name=Metrocles",
    "name=Monimus",
    "name=Onesicritus",
  ],
  "peripatos-members": [
    "name=Aristotle",
    "name=Demetrius of Phalerum",
    "name=Heraclides Ponticus",
    "name=Lyco",
    "name=Strato",
    "name=Theophrastus",
  ],
  "garden-members": [
    "name=Colotes of Lampsacus",
    "name=Epicurus",
    "name=Hermarchus",
    "name=Idomeneus of Lampsacus",
    "name=Leonteus",
    "name=Metrodorus",
    "name=Polyaenus",
    "name=Themista",
  ],
  "socrates-students": [
    "name=Aeschines",
    "name=Antisthenes",
    "name=Aristippus",
    "name=Cebes",
    "name=Crito",
    "name=Euclides",
    "name=Glaucon",
    "name=Phaedo",
    "name=Plato",
    "name=Simmias",
    "name=Simon",
    "name=Xenophon",
  ],
  "aristotle-teachers": [
    "name=Plato",
  ],
  "marriages": [
    "a=Crates of Thebes | b=Hipparchia",
  ],
  "eleatic-atomist-chain": [
    "from=Anaxarchus | to=Pyrrho",
    "from=Democritus | to=Anaxarchus",
    "from=Democritus | to=Epicurus",
    "from=Democritus | to=Protagoras",
    "from=Leucippus | to=Democritus",
    "from=Parmenides | to=Melissus",
    "from=Parmenides | to=Zeno of Elea",
    "from=Xenophanes | to=Parmenides",
    "from=Zeno of Elea | to=Leucippus",
  ],
  "born-in-athens": [
    "name=Aeschines | birthplace=Athens",
    "name=Antisthenes | birthplace=Athens",
    "name=Crates of Athens | birthplace=Athens",
    "name=Crito | birthplace=Athens",
    "name=Epicurus | birthplace=Athens",
    "name=Glaucon | birthplace=Athens",
    "name=Polemo | birthplace=Athens",
    "name=Simon | birthplace=Athens",
    "name=Socrates | birthplace=Athens",
    "name=Speusippus | birthplace=Athens",
    "name=Xenophon | birthplace=Athens",
  ],
  "died-in-athens": [
    "name=Epicurus",
    "name=Zeno of Citium",
  ],
  "plato-works": [
    "title=Alcibiades, or On the Nature of Man",
    "title=Apology of Socrates",
    "title=Charmides, or On Temperance",
    "title=Clitophon, or Introduction",
    "title=Cratylus, or On Correctness of Names",
    "title=Critias, or Story of Atlantis",
    "title=Crito, or On what is to be done",
    "title=Epinomis, or Nocturnal Council",
    "title=Epistles (thirteen in number)",
    "title=Euthydemus, or The Eristic",
    "title=Euthyphro, or On Holiness",
    "title=Gorgias, or On Rhetoric",
    "title=Hipparchus, or The Lover of Gain",
    "title=Hippias (major), or On Beauty",
    "title=Hippias (minor), or On Falsehood",
    "title=Ion, or On the Iliad",
    "title=Laches, or On Courage",
    "title=Laws, or On Legislation",
    "title=Lysis, or On Friendship",
    "title=Menexenus, or The Funeral Oration",
    "title=Meno, or On Virtue",
    "title=Minos, or On Law",
    "title=Parmenides, or On Ideas",
    "title=Phaedo, or On the Soul",
    "title=Phaedrus, or On Love",
    "title=Philebus, or On Pleasure",
    "title=Protagoras, or Sophists",
    "title=Republic",
    "title=Second Alcibiades, or On Prayer",
    "title=Sophist, or On Being",
    "title=Statesman, or On Monarchy",
    "title=The Banquet, or On the Good",
    "title=The Rivals, or On Philosophy",
    "title=Theaetetus, or On Knowledge",
    "title=Theages, or On Philosophy",
    "title=Timaeus, or On Nature",
  ],
  "aristotle-works": [
    "title=A Collection of Arts [that is, Handbooks (two books)",
    "title=A Collection or Compendium (two books)",
    "title=A Reply to the Pythagoreans (one book)",
    "title=A Reply to the Writings of Alcmaeon (one book)",
    "title=A Reply to the Writings of Gorgias (one book)",
    "title=A Reply to the Writings of Melissus (one book)",
    "title=A Reply to the Writings of Xenophanes (one book)",
    "title=A Reply to the Writings of Zeno (one book)",
    "title=A Treatise on the Art of Poetry (two books)",
    "title=A selection of Dissections (one book)",
    "title=Affections or Qualities (one book)",
    "title=Alexander, or a Plea for Colonies (one book)",
    "title=Analogies (one book)",
    "title=Another Collection of Handbooks (two books)",
    "title=Art, a Handbook (one book)",
    "title=Categories (one book)",
    "title=Claims advanced (one book)",
    "title=Compendium of the Art of Theodectes (one book)",
    "title=Concerning Astronomy (one book)",
    "title=Concerning Delphi (one book)",
    "title=Concerning Division (one book)",
    "title=Concerning Logical Division (one book)",
    "title=Concerning Love (one book)",
    "title=Concerning Mathematics (one book)",
    "title=Concerning Memory (one book)",
    "title=Concerning Method (one book)",
    "title=Concerning Nature (one book)",
    "title=Concerning Optics (one book)",
    "title=Concerning Physiognomy (one book)",
    "title=Concerning Syllogism with Definitions (one book)",
    "title=Controversial Propositions (one book)",
    "title=Criticism of the List of Pythian Victors (one book)",
    "title=De Interpretatione (one book)",
    "title=Definitions (thirteen books)",
    "title=Definitions prefixed to the Topics (seven books)",
    "title=Descriptions of Genera (fourteen books)",
    "title=Divisions of Enthymemes (one book)",
    "title=Dramatic Records (one book)",
    "title=Dramatic Victories at the Dionysia (one book)",
    "title=Eight books of Dissections",
    "title=Eight books of Methodics",
    "title=Eight books of Prior Analytics",
    "title=Exhortation to Philosophy (one book)",
    "title=Extracts from Plato’s Laws (three books)",
    "title=Extracts from the Republic (two books)",
    "title=Extracts from the Timaeus and from the Works of Archytas (one book)",
    "title=Five books of Ethics",
    "title=Four books of Laws",
    "title=In reply to Democritus (one book)",
    "title=Laws of the Mess-table (one book)",
    "title=Letters of Selymbrians",
    "title=Letters to Alexander (four books)",
    "title=Letters to Antipater (nine books)",
    "title=Letters to Philip",
    "title=Logical Divisions (seventeen books)",
    "title=Mechanics (one book)",
    "title=Menexenus (one book)",
    "title=Miscellaneous Notes (twelve books)",
    "title=Nerinthus (one book)",
    "title=Objections (one book)",
    "title=Of Degree (one book)",
    "title=Of Friendship (one book)",
    "title=Of Household Management (one book)",
    "title=Of Just Actions (two books)",
    "title=Of Justice (four books)",
    "title=Of Logical Principle (one book)",
    "title=Of Motion (one book)",
    "title=Of Passions or of Anger (one book)",
    "title=Of Pleasure (one book)",
    "title=Of Prayer (one book)",
    "title=Of Problems (one book)",
    "title=Of Science (one book)",
    "title=Of Sciences (one book)",
    "title=Of Taking Counsel (one book)",
    "title=Of Tragedies (one book)",
    "title=Of Wealth (one book)",
    "title=Of the Desirable and the Contingent (one book)",
    "title=Of the Good (three books)",
    "title=Of the Greater Good (one book)",
    "title=Of the Soul (one book)",
    "title=Of the Statesman (two books)",
    "title=On Animals (nine books)",
    "title=On Composite Animals (one book)",
    "title=On Contraries (one book)",
    "title=On Controversial Questions (two books)",
    "title=On Dialectical Questioning and Answering (two books)",
    "title=On Diction (two books)",
    "title=On Education (one book)",
    "title=On Elements (three books)",
    "title=On Essential Attributes (one book)",
    "title=On Genera and Species (one book)",
    "title=On Kingship (one book)",
    "title=On Motion (one book)",
    "title=On Music (one book)",
    "title=On Nature (three books)",
    "title=On Noble Birth (one book)",
    "title=On Philosophy (three books)",
    "title=On Plants (two books)",
    "title=On Pleasure (one book)",
    "title=On Poets (three books)",
    "title=On Rhetoric, or Grylus (one book)",
    "title=On Sterility (one book)",
    "title=On being or having been affected (one book)",
    "title=On the Animals of Fable (one book)",
    "title=On the Beautiful (one book)",
    "title=On the Idea (one book)",
    "title=On the Magnet (one book)",
    "title=On the Philosophy of Archytas (three books)",
    "title=On the Philosophy of Speusippus and Xenocrates (one book)",
    "title=On the Pythagoreans (one book)",
    "title=On the Unit (one book)",
    "title=On the Various Meanings of Terms or Expressions where a Determinant is added (one book)",
    "title=On the Voluntary (one book)",
    "title=Poetics (one book)",
    "title=Politics (two books)",
    "title=Preface to Commonplaces (one book)",
    "title=Problems taken from the works of Democritus (two books)",
    "title=Prognostics of Storms (one book)",
    "title=Propositions (one book)",
    "title=Propositions concerning Virtue (two books)",
    "title=Proverbs (one book)",
    "title=Rhetorical Enthymemes (one book)",
    "title=Six books of Homeric Problems",
    "title=Solutions of Controversial Questions (four books)",
    "title=Sophistical Divisions (four books)",
    "title=Syllogisms (one book)",
    "title=Symposium (one book)",
    "title=The Sophist (one book)",
    "title=Theses concerning Friendship (two books)",
    "title=Theses concerning Love (four books)",
    "title=Theses concerning the Soul (one book)",
    "title=Theses for Refutation (twenty-five books)",
    "title=To Ariston (one book)",
    "title=To Hephaestion (one book)",
    "title=To Mentor (one book)",
    "title=To Olympias (one book)",
    "title=To Philoxenus (one book)",
    "title=To Themistagoras (one book)",
    "title=Two books concerning Medicine",
    "title=Two books of Greater Posterior Analytics",
    "title=Two books of Refutations",
    "title=Two books of Routine Instruction",
    "title=Two books of Syllogisms",
    "title=Two books of Topics criticizing the Definitions",
    "title=Two books of the Art of Rhetoric",
    "title=Victors at Olympia (one book)",
    "title=Victors at the Pythian Games (one book)",
  ],
  "epicurus-works": [
    "title=Against the Megarians",
    "title=Chaeredemus",
    "title=Epitome of Objections to the Physicists",
    "title=Of Atoms and Void",
    "title=Of Choice and Avoidance",
    "title=Of Fate",
    "title=Of Human Life (4 books)",
    "title=Of Images",
    "title=Of Just Dealing",
    "title=Of Justice and the other Virtues",
    "title=Of Kingship",
    "title=Of Love",
    "title=Of Music",
    "title=Of Piety",
    "title=Of Presentation",
    "title=Of Vision",
    "title=Of the End",
    "title=Of the Gods",
    "title=Of the Standard, a work entitled Canon",
    "title=On Nature (37 books)",
    "title=Problems",
    "title=Sovran Maxims (Kyriai Doxai)",
    "title=Symposium",
  ],
  "school-doctrines": [
    "school=Academy | doctrine=The end to aim at is assimilation to God",
    "school=Cynic | doctrine=Life according to virtue is the end",
    "school=Cyrenaic | doctrine=Bodily pleasure is the end",
    "school=Epicurean (Garden) | doctrine=Pleasure is the end and aim",
    "school=Peripatos | doctrine=The one ethical end is the exercise of virtue in a completed life",
    "school=Sceptic | doctrine=The end to be realized is suspension of judgement, which brings tranquillity in its train",
    "school=Stoa | doctrine=Life in agreement with nature is the end",
  ],
  "homonymy-proper-names": [
    "form=Αἰσχίνης | name1=Aeschines | name2=Aeschines",
    "form=Βίων | name1=Bion | name2=Bion",
    "form=Βρύσων | name1=Bryson | name2=Bryson the Achaean",
    "form=Δάμων | name1=Damon | name2=Damon of Cyrene",
    "form=Δημήτριος | name1=Demetrius of Magnesia | name2=Demetrius of Troezen",
    "form=Δημήτριος | name1=Demetrius of Magnesia | name2=Demetrius the Magnesian",
    "form=Δημήτριος | name1=Demetrius of Phalerum | name2=Demetrius",
    "form=Δημήτριος | name1=Demetrius of Phalerum | name2=Demetrius of Magnesia",
    "form=Δημήτριος | name1=Demetrius of Phalerum | name2=Demetrius of Troezen",
    "form=Δημήτριος | name1=Demetrius of Phalerum | name2=Demetrius the Magnesian",
    "form=Δημήτριος | name1=Demetrius of Troezen | name2=Demetrius",
    "form=Δημήτριος | name1=Demetrius of Troezen | name2=Demetrius of Magnesia",
    "form=Δημήτριος | name1=Demetrius of Troezen | name2=Demetrius of Phalerum",
    "form=Δημήτριος | name1=Demetrius of Troezen | name2=Demetrius of Troezen",
    "form=Δημήτριος | name1=Demetrius of Troezen | name2=Demetrius the Magnesian",
    "form=Δημήτριος | name1=Demetrius of Troezen | name2=Demetrius the epic poet",
    "form=Δημήτριος | name1=Demetrius the epic poet | name2=Demetrius",
    "form=Δημήτριος | name1=Demetrius the epic poet | name2=Demetrius of Magnesia",
    "form=Δημήτριος | name1=Demetrius the epic poet | name2=Demetrius of Phalerum",
    "form=Δημήτριος | name1=Demetrius the epic poet | name2=Demetrius of Troezen",
    "form=Δημήτριος | name1=Demetrius the epic poet | name2=Demetrius the Magnesian",
    "form=Δημήτριος | name1=Demetrius | name2=Demetrius of Magnesia",
    "form=Δημήτριος | name1=Demetrius | name2=Demetrius of Troezen",
    "form=Δημήτριος | name1=Demetrius | name2=Demetrius the Magnesian",
    "form=Διαδοχαί | name1=Successions | name2=Successions of Philosophers",
    "form=Διογένης | name1=Diogenes Laertius | name2=Diogenes of Apollonia",
    "form=Διογένης | name1=Diogenes Laertius | name2=Diogenes of Sinope",
    "form=Διογένης | name1=Diogenes Laertius | name2=Diogenes of Smyrna",
    "form=Διογένης | name1=Diogenes of Apollonia | name2=Diogenes of Sinope",
    "form=Διογένης | name1=Diogenes of Smyrna | name2=Diogenes of Apollonia",
    "form=Διογένης | name1=Diogenes of Smyrna | name2=Diogenes of Sinope",
    "form=Διογένης | name1=Diogenes | name2=Diogenes Laertius",
    "form=Διογένης | name1=Diogenes | name2=Diogenes of Apollonia",
    "form=Διογένης | name1=Diogenes | name2=Diogenes of Sinope",
    "form=Διογένης | name1=Diogenes | name2=Diogenes of Smyrna",
    "form=Διονύσιος | name1=Dionysius the Elder | name2=Dionysius the Renegade",
    "form=Διονύσιος | name1=Dionysius the Elder | name2=Dionysius the Stoic",
    "form=Διονύσιος | name1=Dionysius the Elder | name2=Dionysius the Younger",
    "form=Διονύσιος | name1=Dionysius the Renegade | name2=Dionysius the Stoic",
    "form=Διονύσιος | name1=Dionysius the Younger | name2=Dionysius the Renegade",
    "form=Διονύσιος | name1=Dionysius the Younger | name2=Dionysius the Stoic",
    "form=Διοσκουρίδης | name1=Dioscurides of Cyprus | name2=Dioscurides",
    "form=Διόδωρος | name1=Diodorus | name2=Diodorus of Ephesus",
    "form=Εὐριπίδης | name1=Euripides | name2=Euripides",
    "form=Ζήνων | name1=Zeno of Citium | name2=Zeno of Elea",
    "form=Ζήνων | name1=Zeno of Citium | name2=Zeno of Tarsus",
    "form=Ζήνων | name1=Zeno of Elea | name2=Zeno of Tarsus",
    "form=Ζήνων | name1=Zeno of Sidon | name2=Zeno of Citium",
    "form=Ζήνων | name1=Zeno of Sidon | name2=Zeno of Elea",
    "form=Ζήνων | name1=Zeno of Sidon | name2=Zeno of Tarsus",
    "form=Ζεῦξις | name1=Zeuxis Goniopus | name2=Zeuxis",
    "form=Θεόφραστος | name1=Theophrastus | name2=Theophrastus",
    "form=Καλλίας | name1=Callias | name2=Callias",
    "form=Κράτης | name1=Crates of Athens | name2=Crates of Thebes",
    "form=Κρίτων | name1=Crito | name2=Crito",
    "form=Κρατῖνος | name1=Cratinus | name2=Cratinus the Younger",
    "form=Κρότων | name1=Croton | name2=Croton",
    "form=Μένιππος | name1=Menippus | name2=Menippus",
    "form=Μενέδημος | name1=Menedemus of Eretria | name2=Menedemus the Cynic",
    "form=Μητροκλῆς | name1=Metrocles | name2=Metrocles",
    "form=Ξενοφάνης | name1=Xenophanes | name2=Xenophanes",
    "form=Περὶ τῶν σοφῶν | name1=Of the Wise (one book) | name2=On the Sages",
    "form=Ποσειδώνιος | name1=Posidonius of Alexandria | name2=Posidonius",
    "form=Πτολεμαῖος | name1=Ptolemy of Cyrene | name2=Ptolemy Soter",
    "form=Πυθαγόρας | name1=Pythagoras | name2=Pythagoras",
    "form=Σίμων | name1=Simon | name2=Simon",
    "form=Σωκράτης | name1=Socrates | name2=Socrates",
    "form=Τηλαύγης | name1=Telauges | name2=Telauges",
    "form=Φρύνιχος | name1=Phrynichus | name2=Phrynichus",
    "form=Χρύσιππος | name1=Chrysippus | name2=Chrysippus",
    "form=Ἀγρίππας | name1=Agrippa | name2=Agrippa",
    "form=Ἀθηνόδωρος | name1=Athenodorus of Soli | name2=Athenodorus",
    "form=Ἀκαδήμεια | name1=Academy | name2=Academy",
    "form=Ἀλέξανδρος | name1=Alexander the Great | name2=Alexander",
    "form=Ἀλκιβιάδης | name1=Alcibiades | name2=Alcibiades",
    "form=Ἀναξιμένης | name1=Anaximenes | name2=Anaximenes",
    "form=Ἀντίγονος | name1=Antigonus | name2=Antigonus of Carystus",
    "form=Ἀντισθένης | name1=Antisthenes | name2=Antisthenes",
    "form=Ἀπολλόδωρος | name1=Apollodorus | name2=Apollodorus",
    "form=Ἀρίστων | name1=Ariston of Chios | name2=Ariston",
    "form=Ἀριστοτέλης | name1=Aristotle | name2=Aristotle",
    "form=Ἀριστοφάνης | name1=Aristophanes | name2=Aristophanes the Grammarian",
    "form=Ἀρκεσίλαος | name1=Arcesilaus | name2=Arcesilaus",
    "form=Ἐπιμενίδης | name1=Epimenides | name2=Epimenides",
    "form=Ἕρμαρχος | name1=Hermarchus | name2=Hermarchus",
    "form=Ἡράκλειτος | name1=Heraclitus | name2=Heraclitus",
    "form=Ἡρακλείδης | name1=Heraclides Ponticus | name2=Heraclides",
    "form=Ἡρακλείδης | name1=Heraclides Ponticus | name2=Heraclides of Tarsus",
    "form=Ἡρακλείδης | name1=Heraclides of Heraclea | name2=Heraclides",
    "form=Ἡρακλείδης | name1=Heraclides of Heraclea | name2=Heraclides Ponticus",
    "form=Ἡρακλείδης | name1=Heraclides of Heraclea | name2=Heraclides of Tarsus",
    "form=Ἡρακλείδης | name1=Heraclides of Heraclea | name2=Heraclides the Sceptic",
    "form=Ἡρακλείδης | name1=Heraclides the Sceptic | name2=Heraclides",
    "form=Ἡρακλείδης | name1=Heraclides the Sceptic | name2=Heraclides Ponticus",
    "form=Ἡρακλείδης | name1=Heraclides the Sceptic | name2=Heraclides of Tarsus",
    "form=Ἡρακλείδης | name1=Heraclides | name2=Heraclides of Tarsus",
  ],
};

/**
 * Pinned Entities-card term types for every pinned answer-row value that
 * reaches the extra-terms classifier (as of July 2026 curation). The
 * /competency page buckets each non-philosopher row value as a school,
 * place, work, person, or doctrine chip via classifyExtraTerm in
 * routes/competency.ts, consulting several lookup tables (MOVEMENTS,
 * PLACE_TYPES, WORK_FACETS, greekNameSpec, the LOD person ASK). A
 * curation change — a name added to PLACE_TYPES, a person losing its LOD
 * typing — could silently rebucket a chip (say, a person rendered as a
 * doctrine chip) while every count/column/answer pin stays green, so
 * validate-competency-counts.ts re-classifies each pinned answer value
 * and compares against this table. After a deliberate curation change,
 * update the drifted entry to the live type printed in the failure
 * output.
 */
export const EXPECTED_TERM_TYPES: Record<
  string,
  "school" | "place" | "work" | "person" | "doctrine"
> = {
  "The end to aim at is assimilation to God": "doctrine",
  "The one ethical end is the exercise of virtue in a completed life": "doctrine",
  "The end to be realized is suspension of judgement, which brings tranquillity in its train": "doctrine",
  "A Collection of Arts [that is, Handbooks (two books)": "work",
  "A Collection or Compendium (two books)": "work",
  "A Reply to the Pythagoreans (one book)": "work",
  "A Reply to the Writings of Alcmaeon (one book)": "work",
  "A Reply to the Writings of Gorgias (one book)": "work",
  "A Reply to the Writings of Melissus (one book)": "work",
  "A Reply to the Writings of Xenophanes (one book)": "work",
  "A Reply to the Writings of Zeno (one book)": "work",
  "A Treatise on the Art of Poetry (two books)": "work",
  "A selection of Dissections (one book)": "work",
  "Academy": "school",
  "Affections or Qualities (one book)": "work",
  "Against the Megarians": "work",
  "Agrippa": "person",
  "Alcibiades, or On the Nature of Man": "work",
  "Alcibiades": "work",
  "Alexander the Great": "person",
  "Alexander, or a Plea for Colonies (one book)": "work",
  "Alexander": "person",
  "Analogies (one book)": "work",
  "Another Collection of Handbooks (two books)": "work",
  "Antigonus of Carystus": "person",
  "Antigonus": "person",
  "Apollodorus": "person",
  "Apology of Socrates": "work",
  "Ariston": "person",
  "Aristophanes the Grammarian": "person",
  "Aristophanes": "person",
  "Art, a Handbook (one book)": "work",
  "Athenodorus of Soli": "person",
  "Athenodorus": "person",
  "Athens": "place",
  "Atomist": "school",
  "Bodily pleasure is the end": "doctrine",
  "Bryson the Achaean": "person",
  "Bryson": "person",
  "Callias": "work",
  "Categories (one book)": "work",
  "Chaeredemus": "work",
  "Charmides, or On Temperance": "work",
  "Claims advanced (one book)": "work",
  "Clitophon, or Introduction": "work",
  "Colotes of Lampsacus": "person",
  "Compendium of the Art of Theodectes (one book)": "work",
  "Concerning Astronomy (one book)": "work",
  "Concerning Delphi (one book)": "work",
  "Concerning Division (one book)": "work",
  "Concerning Logical Division (one book)": "work",
  "Concerning Love (one book)": "work",
  "Concerning Mathematics (one book)": "work",
  "Concerning Memory (one book)": "work",
  "Concerning Method (one book)": "work",
  "Concerning Nature (one book)": "work",
  "Concerning Optics (one book)": "work",
  "Concerning Physiognomy (one book)": "work",
  "Concerning Syllogism with Definitions (one book)": "work",
  "Controversial Propositions (one book)": "work",
  "Cratinus the Younger": "person",
  "Cratinus": "person",
  "Cratylus, or On Correctness of Names": "work",
  "Critias, or Story of Atlantis": "work",
  "Criticism of the List of Pythian Victors (one book)": "work",
  "Crito, or On what is to be done": "work",
  "Croton": "person",
  "Cynic": "school",
  "Cyrenaic": "school",
  "Damon of Cyrene": "person",
  "Damon": "person",
  "De Interpretatione (one book)": "work",
  "Definitions (thirteen books)": "work",
  "Definitions prefixed to the Topics (seven books)": "work",
  "Demetrius of Magnesia": "person",
  "Demetrius of Troezen": "person",
  "Demetrius the Magnesian": "person",
  "Demetrius the epic poet": "person",
  "Demetrius": "person",
  "Descriptions of Genera (fourteen books)": "work",
  "Diodorus of Ephesus": "person",
  "Diodorus": "person",
  "Diogenes Laertius": "person",
  "Diogenes of Smyrna": "person",
  "Diogenes": "person",
  "Dionysius the Elder": "person",
  "Dionysius the Stoic": "person",
  "Dionysius the Younger": "person",
  "Dioscurides of Cyprus": "person",
  "Dioscurides": "person",
  "Divisions of Enthymemes (one book)": "work",
  "Dramatic Records (one book)": "work",
  "Dramatic Victories at the Dionysia (one book)": "work",
  "Eight books of Dissections": "work",
  "Eight books of Methodics": "work",
  "Eight books of Prior Analytics": "work",
  "Eleatic": "school",
  "Elian–Eretrian": "school",
  "Epicurean (Garden)": "school",
  "Epinomis, or Nocturnal Council": "work",
  "Epistles (thirteen in number)": "work",
  "Epitome of Objections to the Physicists": "work",
  "Euripides": "work",
  "Euthydemus, or The Eristic": "work",
  "Euthyphro, or On Holiness": "work",
  "Exhortation to Philosophy (one book)": "work",
  "Extracts from Plato’s Laws (three books)": "work",
  "Extracts from the Republic (two books)": "work",
  "Extracts from the Timaeus and from the Works of Archytas (one book)": "work",
  "Five books of Ethics": "work",
  "Four books of Laws": "work",
  "Gorgias, or On Rhetoric": "work",
  "Heraclides of Heraclea": "person",
  "Heraclides of Tarsus": "person",
  "Heraclides the Sceptic": "person",
  "Heraclides": "person",
  "Hermarchus": "person",
  "Hipparchus, or The Lover of Gain": "work",
  "Hippias (major), or On Beauty": "work",
  "Hippias (minor), or On Falsehood": "work",
  "Idomeneus of Lampsacus": "person",
  "In reply to Democritus (one book)": "work",
  "Ion, or On the Iliad": "work",
  "Ionian / Milesian": "school",
  "Laches, or On Courage": "work",
  "Laws of the Mess-table (one book)": "work",
  "Laws, or On Legislation": "work",
  "Leonteus": "person",
  "Letters of Selymbrians": "work",
  "Letters to Alexander (four books)": "work",
  "Letters to Antipater (nine books)": "work",
  "Letters to Philip": "work",
  "Life according to virtue is the end": "doctrine",
  "Life in agreement with nature is the end": "doctrine",
  "Logical Divisions (seventeen books)": "work",
  "Lysis, or On Friendship": "work",
  "Mechanics (one book)": "work",
  "Megarian": "school",
  "Menexenus (one book)": "work",
  "Menexenus, or The Funeral Oration": "work",
  "Meno, or On Virtue": "work",
  "Metrodorus": "doctrine",
  "Minos, or On Law": "work",
  "Miscellaneous Notes (twelve books)": "work",
  "Nerinthus (one book)": "work",
  "Objections (one book)": "work",
  "Of Atoms and Void": "work",
  "Of Choice and Avoidance": "work",
  "Of Degree (one book)": "work",
  "Of Fate": "work",
  "Of Friendship (one book)": "work",
  "Of Household Management (one book)": "work",
  "Of Human Life (4 books)": "work",
  "Of Images": "work",
  "Of Just Actions (two books)": "work",
  "Of Just Dealing": "work",
  "Of Justice (four books)": "work",
  "Of Justice and the other Virtues": "work",
  "Of Kingship": "work",
  "Of Logical Principle (one book)": "work",
  "Of Love": "work",
  "Of Motion (one book)": "work",
  "Of Music": "work",
  "Of Passions or of Anger (one book)": "work",
  "Of Piety": "work",
  "Of Pleasure (one book)": "work",
  "Of Prayer (one book)": "work",
  "Of Presentation": "work",
  "Of Problems (one book)": "work",
  "Of Science (one book)": "work",
  "Of Sciences (one book)": "work",
  "Of Taking Counsel (one book)": "work",
  "Of Tragedies (one book)": "work",
  "Of Vision": "work",
  "Of Wealth (one book)": "work",
  "Of the Desirable and the Contingent (one book)": "work",
  "Of the End": "work",
  "Of the Gods": "work",
  "Of the Good (three books)": "work",
  "Of the Greater Good (one book)": "work",
  "Of the Soul (one book)": "work",
  "Of the Standard, a work entitled Canon": "work",
  "Of the Statesman (two books)": "work",
  "Of the Wise (one book)": "work",
  "On Animals (nine books)": "work",
  "On Composite Animals (one book)": "work",
  "On Contraries (one book)": "work",
  "On Controversial Questions (two books)": "work",
  "On Dialectical Questioning and Answering (two books)": "work",
  "On Diction (two books)": "work",
  "On Education (one book)": "work",
  "On Elements (three books)": "work",
  "On Essential Attributes (one book)": "work",
  "On Genera and Species (one book)": "work",
  "On Kingship (one book)": "work",
  "On Motion (one book)": "work",
  "On Music (one book)": "work",
  "On Nature (37 books)": "work",
  "On Nature (three books)": "work",
  "On Noble Birth (one book)": "work",
  "On Philosophy (three books)": "work",
  "On Plants (two books)": "work",
  "On Pleasure (one book)": "work",
  "On Poets (three books)": "work",
  "On Rhetoric, or Grylus (one book)": "work",
  "On Sterility (one book)": "work",
  "On being or having been affected (one book)": "work",
  "On the Animals of Fable (one book)": "work",
  "On the Beautiful (one book)": "work",
  "On the Idea (one book)": "work",
  "On the Magnet (one book)": "work",
  "On the Philosophy of Archytas (three books)": "work",
  "On the Philosophy of Speusippus and Xenocrates (one book)": "work",
  "On the Pythagoreans (one book)": "work",
  "On the Sages": "work",
  "On the Unit (one book)": "work",
  "On the Various Meanings of Terms or Expressions where a Determinant is added (one book)": "work",
  "On the Voluntary (one book)": "work",
  "Parmenides, or On Ideas": "work",
  "Peripatos": "school",
  "Phaedo, or On the Soul": "work",
  "Phaedrus, or On Love": "work",
  "Philebus, or On Pleasure": "work",
  "Phrynichus": "work",
  "Pleasure is the end and aim": "doctrine",
  "Poetics (one book)": "work",
  "Politics (two books)": "work",
  "Polyaenus": "person",
  "Posidonius of Alexandria": "person",
  "Posidonius": "person",
  "Preface to Commonplaces (one book)": "work",
  "Problems taken from the works of Democritus (two books)": "work",
  "Problems": "work",
  "Prognostics of Storms (one book)": "work",
  "Propositions (one book)": "work",
  "Propositions concerning Virtue (two books)": "work",
  "Protagoras, or Sophists": "work",
  "Proverbs (one book)": "work",
  "Ptolemy Soter": "person",
  "Ptolemy of Cyrene": "person",
  "Pythagorean": "school",
  "Republic": "work",
  "Rhetorical Enthymemes (one book)": "work",
  "Sceptic": "school",
  "Second Alcibiades, or On Prayer": "work",
  "Six books of Homeric Problems": "work",
  "Socratic": "school",
  "Solutions of Controversial Questions (four books)": "work",
  "Sophist, or On Being": "work",
  "Sophistical Divisions (four books)": "work",
  "Sovran Maxims (Kyriai Doxai)": "work",
  "Statesman, or On Monarchy": "work",
  "Stoa": "school",
  "Successions of Philosophers": "work",
  "Successions": "work",
  "Syllogisms (one book)": "work",
  "Symposium (one book)": "work",
  "Symposium": "work",
  "Telauges": "person",
  "The Banquet, or On the Good": "work",
  "The Rivals, or On Philosophy": "work",
  "The Sophist (one book)": "work",
  "Theaetetus, or On Knowledge": "work",
  "Theages, or On Philosophy": "work",
  "Themista": "person",
  "Theses concerning Friendship (two books)": "work",
  "Theses concerning Love (four books)": "work",
  "Theses concerning the Soul (one book)": "work",
  "Theses for Refutation (twenty-five books)": "work",
  "Timaeus, or On Nature": "work",
  "To Ariston (one book)": "work",
  "To Hephaestion (one book)": "work",
  "To Mentor (one book)": "work",
  "To Olympias (one book)": "work",
  "To Philoxenus (one book)": "work",
  "To Themistagoras (one book)": "work",
  "Two books concerning Medicine": "work",
  "Two books of Greater Posterior Analytics": "work",
  "Two books of Refutations": "work",
  "Two books of Routine Instruction": "work",
  "Two books of Syllogisms": "work",
  "Two books of Topics criticizing the Definitions": "work",
  "Two books of the Art of Rhetoric": "work",
  "Victors at Olympia (one book)": "work",
  "Victors at the Pythian Games (one book)": "work",
  "Zeno of Sidon": "person",
  "Zeno of Tarsus": "person",
  "Zeuxis Goniopus": "person",
  "Zeuxis": "person",
};
