/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Legomena
 * Ontology-first companion API over Diogenes Laertius. A committed Turtle dataset (assertion ontology, annotation layer, bilingual passage texts) is loaded into an in-memory triple store at startup, and every endpoint is answered exclusively by querying that store: the knowledge graph is reconstructed from reified assertions, the reader renders stored text literals with the stored stand-off annotation layer, and Ask retrieves passages indexed from the dataset's own text literals, answering with cited assertions.
 *
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
  /** Whether the Turtle dataset finished loading into the store */
  storeReady: boolean;
  /** Triples currently in the store */
  tripleCount: number;
  /** Whether the dense embedding index and query embedder are available */
  denseIndexReady: boolean;
  /** True once the local embedding model has warmed up (loaded at startup and produced a first embedding). Deployment checks can poll this to wait until the first search will answer instantly. */
  modelReady: boolean;
}

export interface ErrorMessage {
  error: string;
}

export interface NamedCount {
  name: string;
  count: number;
}

export interface DatasetFile {
  /** File name inside the committed dataset directory */
  name: string;
  /** Content hash recorded by the materializer */
  sha256: string;
  bytes: number;
  /** Triples contributed to the store by this file */
  triples?: number;
}

export interface AssertionStats {
  /** lo:Claim reifications in the store */
  claims: number;
  /** rdf:Statement reifications carrying D.L. citations */
  relationStatements: number;
  byCertainty: NamedCount[];
  /** Claim predicates by frequency, descending */
  byPredicate: NamedCount[];
}

export interface PassageStats {
  /** lo:Passage nodes in the dataset */
  total: number;
  withEnglish: number;
  /** Passages with at least one stored annotation */
  annotated: number;
  /** oa:Annotation nodes in the dataset */
  annotations: number;
}

export interface DatasetStats {
  /** Timestamp recorded in the dataset manifest */
  generatedAt: string;
  files: DatasetFile[];
  totalTriples: number;
  /** Named individuals per core ontology class */
  entityCounts: NamedCount[];
  assertions: AssertionStats;
  passages: PassageStats;
}

export interface GraphDerivation {
  description: string;
  /** The SPARQL query that produced the nodes */
  nodeQuery: string;
  /** The SPARQL query that produced the edges */
  edgeQuery: string;
}

export interface OntologyGraphNode {
  uri: string;
  name: string;
  /** Greek proper name form recorded for the entity, when unique */
  grcName?: string;
  /** School slug derived from the lo:memberOf URI */
  school: string;
  schoolUri: string;
  schoolLabel: string;
  book: number;
  chapter: string;
  /** Claims in the store whose rdf:subject is this node */
  claimCount: number;
  /** True when the node is classed lo:Sage (Book 1) */
  sage?: boolean;
}

export type OntologyGraphEdgeType = typeof OntologyGraphEdgeType[keyof typeof OntologyGraphEdgeType];


export const OntologyGraphEdgeType = {
  teacherOf: 'teacherOf',
  influenced: 'influenced',
  spouseOf: 'spouseOf',
} as const;

export interface OntologyGraphEdge {
  /** Label of the subject philosopher */
  from: string;
  to: string;
  fromUri: string;
  toUri: string;
  type: OntologyGraphEdgeType;
  predicateUri: string;
  /** D.L. reference (book.section, Hicks numbering) */
  ref: string;
  /** Full bibliographic citation literal from the statement */
  citation: string;
  /** "asserted" when the store also holds the direct triple the statement reifies; "reported" when the relation exists only as a reification */
  certainty: string;
  /** Named authorities (lo:accordingTo) when the dataset records them, otherwise Diogenes Laertius himself */
  attribution: string;
  /** Corpus section id the citation resolves to, when unambiguous */
  sectionId?: string;
}

export interface OntologyGraph {
  nodes: OntologyGraphNode[];
  edges: OntologyGraphEdge[];
  derivation: GraphDerivation;
}

export interface EntitySummary {
  uri: string;
  label: string;
  /** Primary ontology class (philosopher, sage, school, place, work, person, source, doctrine) */
  kind: string;
  grcName?: string;
  /** Assertions (claims and relation statements) touching this entity */
  claimCount: number;
  /** Stored stand-off annotations whose body is this entity */
  annotationCount: number;
}

export interface EntityList {
  entities: EntitySummary[];
  /** Matching entities before any truncation */
  total: number;
}

export interface LinkOut {
  uri: string;
  label?: string;
}

export interface ProperName {
  uri: string;
  form: string;
  lang: string;
}

export interface ChainLink {
  authorityUri: string;
  authorityLabel: string;
  /** Position in the transmission chain, 1 = D.L.'s immediate source */
  order: number;
}

export interface ConflictRef {
  uri: string;
  /** Verbalized subject-predicate-object of the conflicting claim */
  summary?: string;
}

export type AssertionKind = typeof AssertionKind[keyof typeof AssertionKind];


export const AssertionKind = {
  claim: 'claim',
  relation: 'relation',
} as const;

export interface Assertion {
  /** Claim URI, or a synthetic statement identifier for reified relations */
  uri: string;
  kind: AssertionKind;
  subjectUri: string;
  subjectLabel: string;
  predicateUri: string;
  /** rdfs:label of the predicate from the ontology TBox in the store */
  predicateLabel: string;
  objectUri?: string;
  objectLabel?: string;
  /** Literal object value, when the assertion's object is a literal */
  objectValue?: string;
  objectLang?: string;
  /** asserted, reported, disputed or conjectured (from lo:certainty) */
  certainty: string;
  /** Authorities D.L. names for the assertion */
  accordingTo?: LinkOut[];
  assertedInWork?: LinkOut;
  /** Transmission chain, outermost authority first */
  chain?: ChainLink[];
  conflictsWith?: ConflictRef[];
  citation: string;
  ref: string;
  sectionId?: string;
  /** Verbatim Greek excerpt carried by the claim, when curated */
  grc?: string;
  note?: string;
}

export interface AnnotatedSectionRef {
  sectionId: string;
  citation: string;
  lifeOf?: string;
  /** Stored annotations of this entity in the section */
  count: number;
}

export interface EntityDetail {
  uri: string;
  label: string;
  /** All ontology classes of the entity, qnames */
  kinds: string[];
  grcName?: string;
  book?: number;
  chapter?: string;
  schoolUri?: string;
  schoolLabel?: string;
  founderOf?: string;
  roles?: string[];
  properNames: ProperName[];
  sameAs: LinkOut[];
  seeAlso: LinkOut[];
  /** Principal doctrines, for school entities */
  doctrines?: LinkOut[];
  /** Assertions whose subject is this entity */
  assertions: Assertion[];
  /** Assertions whose object is this entity */
  mentions: Assertion[];
  /** Derived relation edges touching this entity */
  relations: OntologyGraphEdge[];
  annotatedSections: AnnotatedSectionRef[];
}

export interface PassageSummary {
  id: string;
  citation: string;
  book: number;
  chapter: string;
  section: string;
  lifeOf?: string;
  lifeOfUri?: string;
  hasEnglish: boolean;
  annotationCount: number;
  /** Assertions whose citation resolves to this section */
  assertionCount: number;
}

export interface PassageList {
  sections: PassageSummary[];
}

export type AnnotationSpanLang = typeof AnnotationSpanLang[keyof typeof AnnotationSpanLang];


export const AnnotationSpanLang = {
  grc: 'grc',
  en: 'en',
} as const;

export interface AnnotationSpan {
  annotationUri: string;
  /** UTF-16 offset into the stored greekText (grc) or englishText (en) */
  start: number;
  end: number;
  lang: AnnotationSpanLang;
  /** The oa:exact quote stored in the TextQuoteSelector */
  exact: string;
  entityUri: string;
  entityLabel?: string;
  entityKind?: string;
  /** otv:ProperName body, when the annotation realizes a name */
  nameUri?: string;
  /** otv:Concept bodies a term annotation denotes */
  conceptUris?: string[];
}

export interface PassageDetail {
  id: string;
  citation: string;
  urn: string;
  book: number;
  chapter: string;
  section: string;
  lifeOf?: string;
  lifeOfUri?: string;
  /** The stored lo:greekText literal */
  greekText: string;
  /**
     * The stored lo:englishText literal, when the dataset has one
     * @nullable
     */
  englishText?: string | null;
  annotations: AnnotationSpan[];
  /** Assertions whose D.L. citation resolves to this section */
  assertions: Assertion[];
  prevId?: string;
  nextId?: string;
}

export interface AskInput {
  /** @minLength 1 */
  question: string;
  /**
     * Number of passages to retrieve
     * @minimum 1
     * @maximum 25
     */
  topK?: number;
}

export type RetrievedPassageSnippetLang = typeof RetrievedPassageSnippetLang[keyof typeof RetrievedPassageSnippetLang];


export const RetrievedPassageSnippetLang = {
  grc: 'grc',
  en: 'en',
} as const;

export interface RetrievedPassage {
  sectionId: string;
  citation: string;
  rank: number;
  /** Fused retrieval score (reciprocal rank fusion) */
  score: number;
  lifeOf?: string;
  /** Short excerpt of the stored English (or Greek) text */
  snippet: string;
  snippetLang?: RetrievedPassageSnippetLang;
  annotationCount: number;
}

export interface AnswerLine {
  /** Verbalized assertion, subject - predicate - object */
  text: string;
  assertion: Assertion;
  /** Rank of the retrieved passage that grounded this line */
  passageRank?: number;
}

/**
 * Whether dense retrieval participated
 */
export type OntologyAnswerMode = typeof OntologyAnswerMode[keyof typeof OntologyAnswerMode];


export const OntologyAnswerMode = {
  hybrid: 'hybrid',
  sparse: 'sparse',
} as const;

export interface OntologyAnswer {
  question: string;
  /** Whether dense retrieval participated */
  mode: OntologyAnswerMode;
  lines: AnswerLine[];
  passages: RetrievedPassage[];
  /** Entities named by the retrieved passages' annotations that grounded the lines */
  entities: LinkOut[];
  /** Degradation notice, e.g. dense index unavailable */
  notice?: string;
}

export interface SparqlInput {
  /**
     * @minLength 1
     * @maxLength 20000
     */
  query: string;
}

export type SparqlCellTermType = typeof SparqlCellTermType[keyof typeof SparqlCellTermType];


export const SparqlCellTermType = {
  uri: 'uri',
  literal: 'literal',
  bnode: 'bnode',
} as const;

export interface SparqlCell {
  bound: boolean;
  termType?: SparqlCellTermType;
  value?: string;
  lang?: string;
  datatype?: string;
}

export interface SparqlRow {
  cells: SparqlCell[];
}

export type SparqlResultForm = typeof SparqlResultForm[keyof typeof SparqlResultForm];


export const SparqlResultForm = {
  select: 'select',
  ask: 'ask',
  construct: 'construct',
  describe: 'describe',
} as const;

export interface SparqlResult {
  form: SparqlResultForm;
  columns?: string[];
  rows?: SparqlRow[];
  /** ASK result */
  boolean?: boolean;
  /** CONSTRUCT / DESCRIBE result serialized as Turtle */
  turtle?: string;
  rowCount: number;
  elapsedMs: number;
}

export interface SparqlExample {
  id: string;
  title: string;
  description: string;
  query: string;
}

export interface SparqlExampleList {
  examples: SparqlExample[];
}

export type ListEntitiesParams = {
/**
 * Case-insensitive substring filter on labels and Greek names
 */
q?: string;
/**
 * Entity kind filter (philosopher, sage, school, place, work, person, source, doctrine)
 */
kind?: string;
};

export type GetEntityParams = {
/**
 * Entity URI as it appears in the dataset
 */
uri: string;
};

export type ListPassagesParams = {
book?: number;
};

