/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Legomena
 * Ontology-first companion API over Diogenes Laertius. A committed Turtle dataset (assertion ontology, annotation layer, bilingual passage texts) is loaded into an in-memory triple store at startup, and every endpoint is answered exclusively by querying that store: the knowledge graph is reconstructed from reified assertions, the reader renders stored text literals with the stored stand-off annotation layer, and Ask retrieves passages indexed from the dataset's own text literals, answering with cited assertions.
 *
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AskInput,
  DatasetStats,
  EntityDetail,
  EntityList,
  ErrorMessage,
  GetEntityParams,
  HealthStatus,
  ListEntitiesParams,
  ListPassagesParams,
  OntologyAnswer,
  OntologyGraph,
  PassageDetail,
  PassageList,
  SparqlExampleList,
  SparqlInput,
  SparqlResult
} from './legomena.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getHealthCheckUrl = () => {




  return `/legomena/api/healthz`
}

/**
 * Returns server health and triple-store readiness
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/legomena/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetDatasetStatsUrl = () => {




  return `/legomena/api/dataset/stats`
}

/**
 * Provenance of the committed Turtle files (name, size, content hash) and store-derived counts: entities per class, assertions by kind and certainty, passages and annotations. Every number is computed by SPARQL against the loaded store.
 * @summary Dataset statistics
 */
export const getDatasetStats = async ( options?: RequestInit): Promise<DatasetStats> => {

  return customFetch<DatasetStats>(getGetDatasetStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDatasetStatsQueryKey = () => {
    return [
    `/legomena/api/dataset/stats`
    ] as const;
    }


export const getGetDatasetStatsQueryOptions = <TData = Awaited<ReturnType<typeof getDatasetStats>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDatasetStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDatasetStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDatasetStats>>> = ({ signal }) => getDatasetStats({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDatasetStats>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDatasetStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getDatasetStats>>>
export type GetDatasetStatsQueryError = ErrorType<unknown>


/**
 * @summary Dataset statistics
 */

export function useGetDatasetStats<TData = Awaited<ReturnType<typeof getDatasetStats>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDatasetStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDatasetStatsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetDerivedGraphUrl = () => {




  return `/legomena/api/graph`
}

/**
 * Philosopher nodes and relation edges reconstructed purely from the store: nodes from chapter-subject class assertions, edges from the reified rdf:Statement assertions carrying D.L. citations. Each edge reports the citation, the certainty derived from the presence of a direct triple, and the attribution (named authorities where the dataset records them). The SPARQL queries used for the derivation are included verbatim.
 * @summary Knowledge graph derived from assertions
 */
export const getDerivedGraph = async ( options?: RequestInit): Promise<OntologyGraph> => {

  return customFetch<OntologyGraph>(getGetDerivedGraphUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDerivedGraphQueryKey = () => {
    return [
    `/legomena/api/graph`
    ] as const;
    }


export const getGetDerivedGraphQueryOptions = <TData = Awaited<ReturnType<typeof getDerivedGraph>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDerivedGraph>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDerivedGraphQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDerivedGraph>>> = ({ signal }) => getDerivedGraph({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDerivedGraph>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDerivedGraphQueryResult = NonNullable<Awaited<ReturnType<typeof getDerivedGraph>>>
export type GetDerivedGraphQueryError = ErrorType<unknown>


/**
 * @summary Knowledge graph derived from assertions
 */

export function useGetDerivedGraph<TData = Awaited<ReturnType<typeof getDerivedGraph>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDerivedGraph>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDerivedGraphQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListEntitiesUrl = (params?: ListEntitiesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/legomena/api/entities?${stringifiedParams}` : `/legomena/api/entities`
}

/**
 * Entities of the assertion ontology (philosophers, sages, schools, places, works, persons, sources, doctrines), with per-entity assertion and annotation counts derived from the store. Filterable by kind and by case-insensitive label substring.
 * @summary List entities
 */
export const listEntities = async (params?: ListEntitiesParams, options?: RequestInit): Promise<EntityList> => {

  return customFetch<EntityList>(getListEntitiesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListEntitiesQueryKey = (params?: ListEntitiesParams,) => {
    return [
    `/legomena/api/entities`, ...(params ? [params] : [])
    ] as const;
    }


export const getListEntitiesQueryOptions = <TData = Awaited<ReturnType<typeof listEntities>>, TError = ErrorType<unknown>>(params?: ListEntitiesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listEntities>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEntitiesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEntities>>> = ({ signal }) => listEntities(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEntities>>, TError, TData> & { queryKey: QueryKey }
}

export type ListEntitiesQueryResult = NonNullable<Awaited<ReturnType<typeof listEntities>>>
export type ListEntitiesQueryError = ErrorType<unknown>


/**
 * @summary List entities
 */

export function useListEntities<TData = Awaited<ReturnType<typeof listEntities>>, TError = ErrorType<unknown>>(
 params?: ListEntitiesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listEntities>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListEntitiesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetEntityUrl = (params: GetEntityParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/legomena/api/entity?${stringifiedParams}` : `/legomena/api/entity`
}

/**
 * One entity by URI: labels, classes, Greek proper names, external links, and every assertion about it - claims where it is subject or object, reified relation statements, each with certainty, attribution, transmission chain and D.L. citation.
 * @summary Entity detail with its assertions
 */
export const getEntity = async (params: GetEntityParams, options?: RequestInit): Promise<EntityDetail> => {

  return customFetch<EntityDetail>(getGetEntityUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetEntityQueryKey = (params?: GetEntityParams,) => {
    return [
    `/legomena/api/entity`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetEntityQueryOptions = <TData = Awaited<ReturnType<typeof getEntity>>, TError = ErrorType<ErrorMessage>>(params: GetEntityParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEntity>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEntityQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEntity>>> = ({ signal }) => getEntity(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEntity>>, TError, TData> & { queryKey: QueryKey }
}

export type GetEntityQueryResult = NonNullable<Awaited<ReturnType<typeof getEntity>>>
export type GetEntityQueryError = ErrorType<ErrorMessage>


/**
 * @summary Entity detail with its assertions
 */

export function useGetEntity<TData = Awaited<ReturnType<typeof getEntity>>, TError = ErrorType<ErrorMessage>>(
 params: GetEntityParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEntity>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetEntityQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListPassagesUrl = (params?: ListPassagesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/legomena/api/sections?${stringifiedParams}` : `/legomena/api/sections`
}

/**
 * Every lo:Passage node of the dataset in reading order, with citation, Life attribution, English availability, and stored annotation counts. Filterable by book.
 * @summary List passages
 */
export const listPassages = async (params?: ListPassagesParams, options?: RequestInit): Promise<PassageList> => {

  return customFetch<PassageList>(getListPassagesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPassagesQueryKey = (params?: ListPassagesParams,) => {
    return [
    `/legomena/api/sections`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPassagesQueryOptions = <TData = Awaited<ReturnType<typeof listPassages>>, TError = ErrorType<unknown>>(params?: ListPassagesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPassages>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPassagesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPassages>>> = ({ signal }) => listPassages(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPassages>>, TError, TData> & { queryKey: QueryKey }
}

export type ListPassagesQueryResult = NonNullable<Awaited<ReturnType<typeof listPassages>>>
export type ListPassagesQueryError = ErrorType<unknown>


/**
 * @summary List passages
 */

export function useListPassages<TData = Awaited<ReturnType<typeof listPassages>>, TError = ErrorType<unknown>>(
 params?: ListPassagesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPassages>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListPassagesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetPassageUrl = (id: string,) => {




  return `/legomena/api/sections/${id}`
}

/**
 * One passage by section id: the stored Greek and English text literals, the stand-off annotation layer (exact quote, offsets, language, tagged entity), and the assertions cited to this section. No runtime tagging is involved; highlights come from the dataset.
 * @summary Passage detail with stored annotations
 */
export const getPassage = async (id: string, options?: RequestInit): Promise<PassageDetail> => {

  return customFetch<PassageDetail>(getGetPassageUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPassageQueryKey = (id: string,) => {
    return [
    `/legomena/api/sections/${id}`
    ] as const;
    }


export const getGetPassageQueryOptions = <TData = Awaited<ReturnType<typeof getPassage>>, TError = ErrorType<ErrorMessage>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPassage>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPassageQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPassage>>> = ({ signal }) => getPassage(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPassage>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPassageQueryResult = NonNullable<Awaited<ReturnType<typeof getPassage>>>
export type GetPassageQueryError = ErrorType<ErrorMessage>


/**
 * @summary Passage detail with stored annotations
 */

export function useGetPassage<TData = Awaited<ReturnType<typeof getPassage>>, TError = ErrorType<ErrorMessage>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPassage>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPassageQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getAskOntologyUrl = () => {




  return `/legomena/api/ask`
}

/**
 * Hybrid retrieval (BM25 and dense embeddings, both indexed from the dataset's own text literals) selects passages; the stored annotation layer of those passages names the entities involved; and the answer lines are the assertions about those entities whose citations resolve into the retrieved passages. Every line carries the assertion URI, its certainty and attribution, and the D.L. citation.
 * @summary Ask a question, answered by cited assertions
 */
export const askOntology = async (askInput: AskInput, options?: RequestInit): Promise<OntologyAnswer> => {

  return customFetch<OntologyAnswer>(getAskOntologyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(askInput)
  }
);}





export const getAskOntologyMutationOptions = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof askOntology>>, TError,{data: BodyType<AskInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof askOntology>>, TError,{data: BodyType<AskInput>}, TContext> => {

const mutationKey = ['askOntology'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof askOntology>>, {data: BodyType<AskInput>}> = (props) => {
          const {data} = props ?? {};

          return  askOntology(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AskOntologyMutationResult = NonNullable<Awaited<ReturnType<typeof askOntology>>>
    export type AskOntologyMutationBody = BodyType<AskInput>
    export type AskOntologyMutationError = ErrorType<ErrorMessage>

    /**
 * @summary Ask a question, answered by cited assertions
 */
export const useAskOntology = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof askOntology>>, TError,{data: BodyType<AskInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof askOntology>>,
        TError,
        {data: BodyType<AskInput>},
        TContext
      > => {
      return useMutation(getAskOntologyMutationOptions(options));
    }

export const getRunSparqlUrl = () => {




  return `/legomena/api/sparql`
}

/**
 * Executes a SPARQL 1.1 query against the in-memory store that feeds every other endpoint. SELECT and ASK return bindings; CONSTRUCT and DESCRIBE return Turtle. Updates are rejected.
 * @summary Run a read-only SPARQL query
 */
export const runSparql = async (sparqlInput: SparqlInput, options?: RequestInit): Promise<SparqlResult> => {

  return customFetch<SparqlResult>(getRunSparqlUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sparqlInput)
  }
);}





export const getRunSparqlMutationOptions = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runSparql>>, TError,{data: BodyType<SparqlInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof runSparql>>, TError,{data: BodyType<SparqlInput>}, TContext> => {

const mutationKey = ['runSparql'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof runSparql>>, {data: BodyType<SparqlInput>}> = (props) => {
          const {data} = props ?? {};

          return  runSparql(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RunSparqlMutationResult = NonNullable<Awaited<ReturnType<typeof runSparql>>>
    export type RunSparqlMutationBody = BodyType<SparqlInput>
    export type RunSparqlMutationError = ErrorType<ErrorMessage>

    /**
 * @summary Run a read-only SPARQL query
 */
export const useRunSparql = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runSparql>>, TError,{data: BodyType<SparqlInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof runSparql>>,
        TError,
        {data: BodyType<SparqlInput>},
        TContext
      > => {
      return useMutation(getRunSparqlMutationOptions(options));
    }

export const getListSparqlExamplesUrl = () => {




  return `/legomena/api/sparql/examples`
}

/**
 * Example SPARQL queries demonstrating the assertion ontology - the same queries the server itself uses for its derivations, plus smaller didactic ones.
 * @summary Curated example queries
 */
export const listSparqlExamples = async ( options?: RequestInit): Promise<SparqlExampleList> => {

  return customFetch<SparqlExampleList>(getListSparqlExamplesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListSparqlExamplesQueryKey = () => {
    return [
    `/legomena/api/sparql/examples`
    ] as const;
    }


export const getListSparqlExamplesQueryOptions = <TData = Awaited<ReturnType<typeof listSparqlExamples>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listSparqlExamples>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSparqlExamplesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSparqlExamples>>> = ({ signal }) => listSparqlExamples({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSparqlExamples>>, TError, TData> & { queryKey: QueryKey }
}

export type ListSparqlExamplesQueryResult = NonNullable<Awaited<ReturnType<typeof listSparqlExamples>>>
export type ListSparqlExamplesQueryError = ErrorType<unknown>


/**
 * @summary Curated example queries
 */

export function useListSparqlExamples<TData = Awaited<ReturnType<typeof listSparqlExamples>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listSparqlExamples>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListSparqlExamplesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







