/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Legomena
 * Ontology-first companion API over Diogenes Laertius. A committed Turtle dataset (assertion ontology, annotation layer, bilingual passage texts) is loaded into an in-memory triple store at startup, and every endpoint is answered exclusively by querying that store: the knowledge graph is reconstructed from reified assertions, the reader renders stored text literals with the stored stand-off annotation layer, and Ask retrieves passages indexed from the dataset's own text literals, answering with cited assertions.
 *
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health and triple-store readiness
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string(),
  "storeReady": zod.boolean().describe('Whether the Turtle dataset finished loading into the store'),
  "tripleCount": zod.number().describe('Triples currently in the store'),
  "denseIndexReady": zod.boolean().describe('Whether the dense embedding index and query embedder are available'),
  "modelReady": zod.boolean().describe('True once the local embedding model has warmed up (loaded at startup and produced a first embedding). Deployment checks can poll this to wait until the first search will answer instantly.\n')
})


/**
 * Provenance of the committed Turtle files (name, size, content hash) and store-derived counts: entities per class, assertions by kind and certainty, passages and annotations. Every number is computed by SPARQL against the loaded store.
 * @summary Dataset statistics
 */
export const GetDatasetStatsResponse = zod.object({
  "generatedAt": zod.string().describe('Timestamp recorded in the dataset manifest'),
  "files": zod.array(zod.object({
  "name": zod.string().describe('File name inside the committed dataset directory'),
  "sha256": zod.string().describe('Content hash recorded by the materializer'),
  "bytes": zod.number(),
  "triples": zod.number().optional().describe('Triples contributed to the store by this file')
})),
  "totalTriples": zod.number(),
  "entityCounts": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number()
})).describe('Named individuals per core ontology class'),
  "assertions": zod.object({
  "claims": zod.number().describe('lo:Claim reifications in the store'),
  "relationStatements": zod.number().describe('rdf:Statement reifications carrying D.L. citations'),
  "byCertainty": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number()
})),
  "byPredicate": zod.array(zod.object({
  "name": zod.string(),
  "count": zod.number()
})).describe('Claim predicates by frequency, descending')
}),
  "passages": zod.object({
  "total": zod.number().describe('lo:Passage nodes in the dataset'),
  "withEnglish": zod.number(),
  "annotated": zod.number().describe('Passages with at least one stored annotation'),
  "annotations": zod.number().describe('oa:Annotation nodes in the dataset')
})
})


/**
 * Philosopher nodes and relation edges reconstructed purely from the store: nodes from chapter-subject class assertions, edges from the reified rdf:Statement assertions carrying D.L. citations. Each edge reports the citation, the certainty derived from the presence of a direct triple, and the attribution (named authorities where the dataset records them). The SPARQL queries used for the derivation are included verbatim.
 * @summary Knowledge graph derived from assertions
 */
export const GetDerivedGraphResponse = zod.object({
  "nodes": zod.array(zod.object({
  "uri": zod.string(),
  "name": zod.string(),
  "grcName": zod.string().optional().describe('Greek proper name form recorded for the entity, when unique'),
  "school": zod.string().describe('School slug derived from the lo:memberOf URI'),
  "schoolUri": zod.string(),
  "schoolLabel": zod.string(),
  "book": zod.number(),
  "chapter": zod.string(),
  "claimCount": zod.number().describe('Claims in the store whose rdf:subject is this node'),
  "sage": zod.boolean().optional().describe('True when the node is classed lo:Sage (Book 1)')
})),
  "edges": zod.array(zod.object({
  "from": zod.string().describe('Label of the subject philosopher'),
  "to": zod.string(),
  "fromUri": zod.string(),
  "toUri": zod.string(),
  "type": zod.enum(['teacherOf', 'influenced', 'spouseOf']),
  "predicateUri": zod.string(),
  "ref": zod.string().describe('D.L. reference (book.section, Hicks numbering)'),
  "citation": zod.string().describe('Full bibliographic citation literal from the statement'),
  "certainty": zod.string().describe('\"asserted\" when the store also holds the direct triple the statement reifies; \"reported\" when the relation exists only as a reification'),
  "attribution": zod.string().describe('Named authorities (lo:accordingTo) when the dataset records them, otherwise Diogenes Laertius himself'),
  "sectionId": zod.string().optional().describe('Corpus section id the citation resolves to, when unambiguous')
})),
  "derivation": zod.object({
  "description": zod.string(),
  "nodeQuery": zod.string().describe('The SPARQL query that produced the nodes'),
  "edgeQuery": zod.string().describe('The SPARQL query that produced the edges')
})
})


/**
 * Entities of the assertion ontology (philosophers, sages, schools, places, works, persons, sources, doctrines), with per-entity assertion and annotation counts derived from the store. Filterable by kind and by case-insensitive label substring.
 * @summary List entities
 */
export const ListEntitiesQueryParams = zod.object({
  "q": zod.coerce.string().optional().describe('Case-insensitive substring filter on labels and Greek names'),
  "kind": zod.coerce.string().optional().describe('Entity kind filter (philosopher, sage, school, place, work, person, source, doctrine)')
})

export const ListEntitiesResponse = zod.object({
  "entities": zod.array(zod.object({
  "uri": zod.string(),
  "label": zod.string(),
  "kind": zod.string().describe('Primary ontology class (philosopher, sage, school, place, work, person, source, doctrine)'),
  "grcName": zod.string().optional(),
  "claimCount": zod.number().describe('Assertions (claims and relation statements) touching this entity'),
  "annotationCount": zod.number().describe('Stored stand-off annotations whose body is this entity')
})),
  "total": zod.number().describe('Matching entities before any truncation')
})


/**
 * One entity by URI: labels, classes, Greek proper names, external links, and every assertion about it - claims where it is subject or object, reified relation statements, each with certainty, attribution, transmission chain and D.L. citation.
 * @summary Entity detail with its assertions
 */
export const GetEntityQueryParams = zod.object({
  "uri": zod.coerce.string().describe('Entity URI as it appears in the dataset')
})

export const GetEntityResponse = zod.object({
  "uri": zod.string(),
  "label": zod.string(),
  "kinds": zod.array(zod.string()).describe('All ontology classes of the entity, qnames'),
  "grcName": zod.string().optional(),
  "book": zod.number().optional(),
  "chapter": zod.string().optional(),
  "schoolUri": zod.string().optional(),
  "schoolLabel": zod.string().optional(),
  "founderOf": zod.string().optional(),
  "roles": zod.array(zod.string()).optional(),
  "properNames": zod.array(zod.object({
  "uri": zod.string(),
  "form": zod.string(),
  "lang": zod.string()
})),
  "sameAs": zod.array(zod.object({
  "uri": zod.string(),
  "label": zod.string().optional()
})),
  "seeAlso": zod.array(zod.object({
  "uri": zod.string(),
  "label": zod.string().optional()
})),
  "doctrines": zod.array(zod.object({
  "uri": zod.string(),
  "label": zod.string().optional()
})).optional().describe('Principal doctrines, for school entities'),
  "assertions": zod.array(zod.object({
  "uri": zod.string().describe('Claim URI, or a synthetic statement identifier for reified relations'),
  "kind": zod.enum(['claim', 'relation']),
  "subjectUri": zod.string(),
  "subjectLabel": zod.string(),
  "predicateUri": zod.string(),
  "predicateLabel": zod.string().describe('rdfs:label of the predicate from the ontology TBox in the store'),
  "objectUri": zod.string().optional(),
  "objectLabel": zod.string().optional(),
  "objectValue": zod.string().optional().describe('Literal object value, when the assertion\'s object is a literal'),
  "objectLang": zod.string().optional(),
  "certainty": zod.string().describe('asserted, reported, disputed or conjectured (from lo:certainty)'),
  "accordingTo": zod.array(zod.object({
  "uri": zod.string(),
  "label": zod.string().optional()
})).optional().describe('Authorities D.L. names for the assertion'),
  "assertedInWork": zod.object({
  "uri": zod.string(),
  "label": zod.string().optional()
}).optional(),
  "chain": zod.array(zod.object({
  "authorityUri": zod.string(),
  "authorityLabel": zod.string(),
  "order": zod.number().describe('Position in the transmission chain, 1 = D.L.\'s immediate source')
})).optional().describe('Transmission chain, outermost authority first'),
  "conflictsWith": zod.array(zod.object({
  "uri": zod.string(),
  "summary": zod.string().optional().describe('Verbalized subject-predicate-object of the conflicting claim')
})).optional(),
  "citation": zod.string(),
  "ref": zod.string(),
  "sectionId": zod.string().optional(),
  "grc": zod.string().optional().describe('Verbatim Greek excerpt carried by the claim, when curated'),
  "note": zod.string().optional()
})).describe('Assertions whose subject is this entity'),
  "mentions": zod.array(zod.object({
  "uri": zod.string().describe('Claim URI, or a synthetic statement identifier for reified relations'),
  "kind": zod.enum(['claim', 'relation']),
  "subjectUri": zod.string(),
  "subjectLabel": zod.string(),
  "predicateUri": zod.string(),
  "predicateLabel": zod.string().describe('rdfs:label of the predicate from the ontology TBox in the store'),
  "objectUri": zod.string().optional(),
  "objectLabel": zod.string().optional(),
  "objectValue": zod.string().optional().describe('Literal object value, when the assertion\'s object is a literal'),
  "objectLang": zod.string().optional(),
  "certainty": zod.string().describe('asserted, reported, disputed or conjectured (from lo:certainty)'),
  "accordingTo": zod.array(zod.object({
  "uri": zod.string(),
  "label": zod.string().optional()
})).optional().describe('Authorities D.L. names for the assertion'),
  "assertedInWork": zod.object({
  "uri": zod.string(),
  "label": zod.string().optional()
}).optional(),
  "chain": zod.array(zod.object({
  "authorityUri": zod.string(),
  "authorityLabel": zod.string(),
  "order": zod.number().describe('Position in the transmission chain, 1 = D.L.\'s immediate source')
})).optional().describe('Transmission chain, outermost authority first'),
  "conflictsWith": zod.array(zod.object({
  "uri": zod.string(),
  "summary": zod.string().optional().describe('Verbalized subject-predicate-object of the conflicting claim')
})).optional(),
  "citation": zod.string(),
  "ref": zod.string(),
  "sectionId": zod.string().optional(),
  "grc": zod.string().optional().describe('Verbatim Greek excerpt carried by the claim, when curated'),
  "note": zod.string().optional()
})).describe('Assertions whose object is this entity'),
  "relations": zod.array(zod.object({
  "from": zod.string().describe('Label of the subject philosopher'),
  "to": zod.string(),
  "fromUri": zod.string(),
  "toUri": zod.string(),
  "type": zod.enum(['teacherOf', 'influenced', 'spouseOf']),
  "predicateUri": zod.string(),
  "ref": zod.string().describe('D.L. reference (book.section, Hicks numbering)'),
  "citation": zod.string().describe('Full bibliographic citation literal from the statement'),
  "certainty": zod.string().describe('\"asserted\" when the store also holds the direct triple the statement reifies; \"reported\" when the relation exists only as a reification'),
  "attribution": zod.string().describe('Named authorities (lo:accordingTo) when the dataset records them, otherwise Diogenes Laertius himself'),
  "sectionId": zod.string().optional().describe('Corpus section id the citation resolves to, when unambiguous')
})).describe('Derived relation edges touching this entity'),
  "annotatedSections": zod.array(zod.object({
  "sectionId": zod.string(),
  "citation": zod.string(),
  "lifeOf": zod.string().optional(),
  "count": zod.number().describe('Stored annotations of this entity in the section')
}))
})


/**
 * Every lo:Passage node of the dataset in reading order, with citation, Life attribution, English availability, and stored annotation counts. Filterable by book.
 * @summary List passages
 */
export const ListPassagesQueryParams = zod.object({
  "book": zod.coerce.number().optional()
})

export const ListPassagesResponse = zod.object({
  "sections": zod.array(zod.object({
  "id": zod.string(),
  "citation": zod.string(),
  "book": zod.number(),
  "chapter": zod.string(),
  "section": zod.string(),
  "lifeOf": zod.string().optional(),
  "lifeOfUri": zod.string().optional(),
  "hasEnglish": zod.boolean(),
  "annotationCount": zod.number(),
  "assertionCount": zod.number().describe('Assertions whose citation resolves to this section')
}))
})


/**
 * One passage by section id: the stored Greek and English text literals, the stand-off annotation layer (exact quote, offsets, language, tagged entity), and the assertions cited to this section. No runtime tagging is involved; highlights come from the dataset.
 * @summary Passage detail with stored annotations
 */
export const GetPassageParams = zod.object({
  "id": zod.coerce.string().describe('Section id (book.chapter.section, e.g. 2.5.21)')
})

export const GetPassageResponse = zod.object({
  "id": zod.string(),
  "citation": zod.string(),
  "urn": zod.string(),
  "book": zod.number(),
  "chapter": zod.string(),
  "section": zod.string(),
  "lifeOf": zod.string().optional(),
  "lifeOfUri": zod.string().optional(),
  "greekText": zod.string().describe('The stored lo:greekText literal'),
  "englishText": zod.string().nullish().describe('The stored lo:englishText literal, when the dataset has one'),
  "annotations": zod.array(zod.object({
  "annotationUri": zod.string(),
  "start": zod.number().describe('UTF-16 offset into the stored greekText (grc) or englishText (en)'),
  "end": zod.number(),
  "lang": zod.enum(['grc', 'en']),
  "exact": zod.string().describe('The oa:exact quote stored in the TextQuoteSelector'),
  "entityUri": zod.string(),
  "entityLabel": zod.string().optional(),
  "entityKind": zod.string().optional(),
  "nameUri": zod.string().optional().describe('otv:ProperName body, when the annotation realizes a name'),
  "conceptUris": zod.array(zod.string()).optional().describe('otv:Concept bodies a term annotation denotes')
})),
  "assertions": zod.array(zod.object({
  "uri": zod.string().describe('Claim URI, or a synthetic statement identifier for reified relations'),
  "kind": zod.enum(['claim', 'relation']),
  "subjectUri": zod.string(),
  "subjectLabel": zod.string(),
  "predicateUri": zod.string(),
  "predicateLabel": zod.string().describe('rdfs:label of the predicate from the ontology TBox in the store'),
  "objectUri": zod.string().optional(),
  "objectLabel": zod.string().optional(),
  "objectValue": zod.string().optional().describe('Literal object value, when the assertion\'s object is a literal'),
  "objectLang": zod.string().optional(),
  "certainty": zod.string().describe('asserted, reported, disputed or conjectured (from lo:certainty)'),
  "accordingTo": zod.array(zod.object({
  "uri": zod.string(),
  "label": zod.string().optional()
})).optional().describe('Authorities D.L. names for the assertion'),
  "assertedInWork": zod.object({
  "uri": zod.string(),
  "label": zod.string().optional()
}).optional(),
  "chain": zod.array(zod.object({
  "authorityUri": zod.string(),
  "authorityLabel": zod.string(),
  "order": zod.number().describe('Position in the transmission chain, 1 = D.L.\'s immediate source')
})).optional().describe('Transmission chain, outermost authority first'),
  "conflictsWith": zod.array(zod.object({
  "uri": zod.string(),
  "summary": zod.string().optional().describe('Verbalized subject-predicate-object of the conflicting claim')
})).optional(),
  "citation": zod.string(),
  "ref": zod.string(),
  "sectionId": zod.string().optional(),
  "grc": zod.string().optional().describe('Verbatim Greek excerpt carried by the claim, when curated'),
  "note": zod.string().optional()
})).describe('Assertions whose D.L. citation resolves to this section'),
  "prevId": zod.string().optional(),
  "nextId": zod.string().optional()
})


/**
 * Hybrid retrieval (BM25 and dense embeddings, both indexed from the dataset's own text literals) selects passages; the stored annotation layer of those passages names the entities involved; and the answer lines are the assertions about those entities whose citations resolve into the retrieved passages. Every line carries the assertion URI, its certainty and attribution, and the D.L. citation.
 * @summary Ask a question, answered by cited assertions
 */

export const askOntologyBodyTopKDefault = 8;
export const askOntologyBodyTopKMax = 25;



export const AskOntologyBody = zod.object({
  "question": zod.string().min(1),
  "topK": zod.number().min(1).max(askOntologyBodyTopKMax).default(askOntologyBodyTopKDefault).describe('Number of passages to retrieve')
})

export const AskOntologyResponse = zod.object({
  "question": zod.string(),
  "mode": zod.enum(['hybrid', 'sparse']).describe('Whether dense retrieval participated'),
  "lines": zod.array(zod.object({
  "text": zod.string().describe('Verbalized assertion, subject - predicate - object'),
  "assertion": zod.object({
  "uri": zod.string().describe('Claim URI, or a synthetic statement identifier for reified relations'),
  "kind": zod.enum(['claim', 'relation']),
  "subjectUri": zod.string(),
  "subjectLabel": zod.string(),
  "predicateUri": zod.string(),
  "predicateLabel": zod.string().describe('rdfs:label of the predicate from the ontology TBox in the store'),
  "objectUri": zod.string().optional(),
  "objectLabel": zod.string().optional(),
  "objectValue": zod.string().optional().describe('Literal object value, when the assertion\'s object is a literal'),
  "objectLang": zod.string().optional(),
  "certainty": zod.string().describe('asserted, reported, disputed or conjectured (from lo:certainty)'),
  "accordingTo": zod.array(zod.object({
  "uri": zod.string(),
  "label": zod.string().optional()
})).optional().describe('Authorities D.L. names for the assertion'),
  "assertedInWork": zod.object({
  "uri": zod.string(),
  "label": zod.string().optional()
}).optional(),
  "chain": zod.array(zod.object({
  "authorityUri": zod.string(),
  "authorityLabel": zod.string(),
  "order": zod.number().describe('Position in the transmission chain, 1 = D.L.\'s immediate source')
})).optional().describe('Transmission chain, outermost authority first'),
  "conflictsWith": zod.array(zod.object({
  "uri": zod.string(),
  "summary": zod.string().optional().describe('Verbalized subject-predicate-object of the conflicting claim')
})).optional(),
  "citation": zod.string(),
  "ref": zod.string(),
  "sectionId": zod.string().optional(),
  "grc": zod.string().optional().describe('Verbatim Greek excerpt carried by the claim, when curated'),
  "note": zod.string().optional()
}),
  "passageRank": zod.number().optional().describe('Rank of the retrieved passage that grounded this line')
})),
  "passages": zod.array(zod.object({
  "sectionId": zod.string(),
  "citation": zod.string(),
  "rank": zod.number(),
  "score": zod.number().describe('Fused retrieval score (reciprocal rank fusion)'),
  "lifeOf": zod.string().optional(),
  "snippet": zod.string().describe('Short excerpt of the stored English (or Greek) text'),
  "snippetLang": zod.enum(['grc', 'en']).optional(),
  "annotationCount": zod.number()
})),
  "entities": zod.array(zod.object({
  "uri": zod.string(),
  "label": zod.string().optional()
})).describe('Entities named by the retrieved passages\' annotations that grounded the lines'),
  "notice": zod.string().optional().describe('Degradation notice, e.g. dense index unavailable')
})


/**
 * Executes a SPARQL 1.1 query against the in-memory store that feeds every other endpoint. SELECT and ASK return bindings; CONSTRUCT and DESCRIBE return Turtle. Updates are rejected.
 * @summary Run a read-only SPARQL query
 */
export const runSparqlBodyQueryMax = 20000;



export const RunSparqlBody = zod.object({
  "query": zod.string().min(1).max(runSparqlBodyQueryMax)
})

export const RunSparqlResponse = zod.object({
  "form": zod.enum(['select', 'ask', 'construct', 'describe']),
  "columns": zod.array(zod.string()).optional(),
  "rows": zod.array(zod.object({
  "cells": zod.array(zod.object({
  "bound": zod.boolean(),
  "termType": zod.enum(['uri', 'literal', 'bnode']).optional(),
  "value": zod.string().optional(),
  "lang": zod.string().optional(),
  "datatype": zod.string().optional()
}))
})).optional(),
  "boolean": zod.boolean().optional().describe('ASK result'),
  "turtle": zod.string().optional().describe('CONSTRUCT \/ DESCRIBE result serialized as Turtle'),
  "rowCount": zod.number(),
  "elapsedMs": zod.number()
})


/**
 * Example SPARQL queries demonstrating the assertion ontology - the same queries the server itself uses for its derivations, plus smaller didactic ones.
 * @summary Curated example queries
 */
export const ListSparqlExamplesResponse = zod.object({
  "examples": zod.array(zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "description": zod.string(),
  "query": zod.string()
}))
})


