/**
 * Curated doxography from Book 10 of Diogenes Laertius' Lives, cited to
 * Hicks section ids (book.section). See doxai.ts for the model and curation
 * rules. Source-internal: every `en` is a verbatim excerpt of its cited
 * section.
 */
import type { Doxa } from "../doxai";

export const BOOK10_DOXAI: Doxa[] = [
  // ----------------------------------------------------------- Epicurus (Canon)
  {
    id: "epicurus-canon-criterion-of-truth",
    philosopher: "Epicurus",
    domain: "epistemology",
    gloss:
      "The standards of truth are the sensations, the preconceptions and the feelings.",
    grc: "κριτήρια τῆς ἀληθείας εἶναι τὰς αἰσθήσεις καὶ προλήψεις καὶ τὰ πάθη",
    en: "Epicurus affirms that our sensations and preconceptions and our feelings are the standards of truth",
    ref: "10.31",
    certainty: "asserted",
    note: "D.L. cites Epicurus' work The Canon for this division of the criterion.",
  },
  {
    id: "epicurus-preconception-prolepsis",
    philosopher: "Epicurus",
    domain: "epistemology",
    gloss:
      "A preconception (prolepsis) is a universal idea, stored from repeated perception, that underlies every name.",
    grc: "Τὴν δὲ πρόληψιν λέγουσιν οἱονεὶ κατάληψιν ἢ δόξαν ὀρθὴν ἢ ἔννοιαν ἢ καθολικὴν νόησιν ἐναποκειμένην",
    en: "By preconception they mean a sort of apprehension or a right opinion or notion, or universal idea stored in the mind",
    ref: "10.33",
    certainty: "asserted",
  },
  {
    id: "epicurus-two-feelings-pleasure-pain",
    philosopher: "Epicurus",
    domain: "pleasure",
    gloss:
      "There are two feelings, pleasure and pain, by which choice and avoidance are decided.",
    grc: "Πάθη δὲ λέγουσιν εἶναι δύο, ἡδονὴν καὶ ἀλγηδόνα, ἱστάμενα περὶ πᾶν ζῷον, καὶ τὴν μὲν οἰκεῖον, τὴν δὲ ἀλλότριον· διʼ ὧν κρίνεσθαι τὰς αἱρέσεις καὶ φυγάς.",
    en: "They affirm that there are two states of feeling, pleasure and pain, which arise in every animate being, and that the one is favourable and the other hostile to that being, and by their means choice and avoidance are determined",
    ref: "10.34",
    certainty: "asserted",
  },
  // ------------------------------------------------- Epicurus (Letter to Menoeceus)
  {
    id: "epicurus-gods-not-as-many-believe",
    philosopher: "Epicurus",
    domain: "gods",
    gloss:
      "The gods truly exist and are known, but not as the multitude imagine them.",
    grc: "θεοὶ μὲν γάρ εἰσιν. ἐναργὴς δέ ἐστιν αὐτῶν ἡ γνῶσις",
    en: "For verily there are gods, and the knowledge of them is manifest; but they are not such as the multitude believe",
    ref: "10.123",
    certainty: "asserted",
  },
  {
    id: "epicurus-death-nothing-to-us",
    philosopher: "Epicurus",
    domain: "death",
    gloss:
      "Death is nothing to us, since all good and evil lie in sensation and death is its privation.",
    grc: "μηδὲν πρὸς ἡμᾶς εἶναι τὸν θάνατον· ἐπεὶ πᾶν ἀγαθὸν καὶ κακὸν ἐν αἰσθήσει· στέρησις δέ ἐστιν αἰσθήσεως ὁ θάνατος.",
    en: "death is nothing to us, for good and evil imply sentience, and death is the privation of all sentience",
    ref: "10.124",
    doctrine:
      "Death is nothing to us, for good and evil imply sentience and death is the privation of all sentience",
    certainty: "asserted",
  },
  {
    id: "epicurus-death-when-we-are-death-is-not",
    philosopher: "Epicurus",
    domain: "death",
    gloss:
      "Death never coincides with us: while we live it is absent, and when it comes we no longer are.",
    grc: "τὸ φρικωδέστατον οὖν τῶν κακῶν ὁ θάνατος οὐθὲν πρὸς ἡμᾶς, ἐπειδή περ ὅταν μὲν ἡμεῖς ὦμεν, ὁ θάνατος οὐ πάρεστιν· ὅταν δʼ ὁ θάνατος παρῇ, τόθʼ ἡμεῖς οὐκ ἐσμέν.",
    en: "Death, therefore, the most awful of evils, is nothing to us, seeing that, when we are, death is not come, and, when death is come, we are not",
    ref: "10.125",
    certainty: "asserted",
  },
  {
    id: "epicurus-desires-natural-necessary",
    philosopher: "Epicurus",
    domain: "ethics",
    gloss:
      "Desires are natural or groundless; and natural ones are either necessary or merely natural.",
    grc: "τῶν ἐπιθυμιῶν αἱ μέν εἰσι φυσικαί, αἱ δὲ κεναί. καὶ τῶν φυσικῶν αἱ μὲν ἀναγκαῖαι, αἱ δὲ φυσικαὶ μόνον",
    en: "of desires some are natural, others are groundless; and that of the natural some are necessary as well as natural, and some natural only",
    ref: "10.127",
    certainty: "asserted",
  },
  {
    id: "epicurus-pleasure-end-not-profligate",
    philosopher: "Epicurus",
    domain: "pleasure",
    gloss:
      "Pleasure as the end means not the profligate's pleasures but freedom from bodily pain and mental disturbance.",
    grc: "Ὅταν οὖν λέγωμεν ἡδονὴν τέλος ὑπάρχειν, οὐ τὰς τῶν ἀσώτων ἡδονὰς καὶ τὰς ἐν ἀπολαύσει κειμένας λέγομεν, ὥς τινες ἀγνοοῦντες καὶ οὐχ ὁμολογοῦντες ἢ κακῶς ἐκδεχόμενοι νομίζουσιν, ἀλλὰ τὸ μήτε ἀλγεῖν κατὰ σῶμα μήτε ταράττεσθαι κατὰ ψυχήν.",
    en: "When we say, then, that pleasure is the end and aim, we do not mean the pleasures of the prodigal or the pleasures of sensuality, as we are understood to do by some through ignorance, prejudice, or wilful misrepresentation. By pleasure we mean the absence of pain in the body and of trouble in the soul.",
    ref: "10.131",
    doctrine: "Pleasure is the end and aim",
    certainty: "asserted",
  },
  {
    id: "epicurus-prudence-greatest-good",
    philosopher: "Epicurus",
    domain: "ethics",
    gloss:
      "Prudence is the greatest good, more precious than philosophy, and the root of all the other virtues.",
    grc: "τούτων δὲ πάντων ἀρχὴ καὶ τὸ μέγιστον ἀγαθὸν φρόνησις· διὸ καὶ φιλοσοφίας τιμιώτερον ὑπάρχει φρόνησις, ἐξ ἧς αἱ λοιπαὶ πᾶσαι πεφύκασιν ἀρεταί",
    en: "Of all this the beginning and the greatest good is prudence. Wherefore prudence is a more precious thing even than philosophy; from it spring all the other virtues",
    ref: "10.132",
    doctrine:
      "Prudence (phronesis) is the greatest good and the source of all the other virtues, more precious even than philosophy",
    certainty: "asserted",
  },
  {
    id: "epicurus-necessity-chance-agency",
    philosopher: "Epicurus",
    domain: "fate",
    gloss:
      "He rejects sovereign destiny: some things happen of necessity, some by chance, and some through our own agency.",
    en: "Destiny, which some introduce as sovereign over all things, he laughs to scorn, affirming rather that some things happen of necessity, others by chance, others through our own agency",
    ref: "10.133",
    certainty: "asserted",
  },
  // ---------------------------------------- Epicurus (D.L.'s summary; vs Cyrenaics)
  {
    id: "epicurus-katastematic-kinetic-pleasure",
    philosopher: "Epicurus",
    domain: "pleasure",
    gloss:
      "Against the Cyrenaics, he counts pleasure of rest as well as pleasure of motion, of mind as well as body.",
    grc: "Διαφέρεται δὲ πρὸς τοὺς Κυρηναϊκοὺς περὶ τῆς ἡδονῆς· οἱ μὲν γὰρ τὴν καταστηματικὴν οὐκ ἐγκρίνουσι, μόνην δὲ τὴν ἐν κινήσει· ὁ δὲ ἀμφοτέραν",
    en: "He differs from the Cyrenaics with regard to pleasure. They do not include under the term the pleasure which is a state of rest, but only that which consists in motion. Epicurus admits both",
    ref: "10.136",
    doctrine:
      "Pleasure is of two kinds: that which is a state of rest (peace of mind, freedom from pain) and that which consists in motion (joy and delight)",
    certainty: "asserted",
  },
  {
    id: "epicurus-mental-pleasures-greater",
    philosopher: "Epicurus",
    domain: "pleasure",
    gloss:
      "Mental pleasures (and pains) outweigh bodily ones, since the mind spans past, present and future.",
    grc: "οὕτως οὖν καὶ μείζονας ἡδονὰς εἶναι τὰς τῆς ψυχῆς.",
    en: "he holds mental pleasures to be greater than those of the body",
    ref: "10.137",
    certainty: "asserted",
  },
  {
    id: "epicurus-virtue-chosen-for-pleasure",
    philosopher: "Epicurus",
    domain: "ethics",
    gloss:
      "The virtues are chosen for the sake of pleasure, not for their own sake, as medicine is taken for health.",
    grc: "Διὰ δὲ τὴν ἡδονὴν καὶ τὰς ἀρετὰς αἱρεῖσθαι, οὐ διʼ αὑτάς, ὥσπερ τὴν ἰατρικὴν διὰ τὴν ὑγίειαν",
    en: "And we choose the virtues too on account of pleasure and not for their own sake, as we take medicine for the sake of health",
    ref: "10.138",
    certainty: "asserted",
  },
  // ---------------------------------------- Epicurus (Principal Doctrines / Kyriai Doxai)
  {
    id: "epicurus-blessed-being-untroubled",
    philosopher: "Epicurus",
    domain: "gods",
    gloss:
      "The blessed and immortal being has no troubles and causes none, and so knows neither anger nor favour.",
    grc: "Τὸ μακάριον καὶ ἄφθαρτον οὔτε αὐτὸ πράγματα ἔχει οὔτε ἄλλῳ παρέχει, ὥστε οὔτε ὀργαῖς οὔτε χάρισι συνέχεται",
    en: "A blessed and eternal being has no trouble himself and brings no trouble upon any other being; hence he is exempt from movements of anger and partiality",
    ref: "10.139",
    doctrine:
      "The gods are living beings immortal and blessed, exempt from trouble, anger and partiality; they neither trouble themselves nor others",
    certainty: "asserted",
    note: "Principal Doctrine 1 (Kyria Doxa I).",
  },
  {
    id: "epicurus-limit-of-pleasure-removal-of-pain",
    philosopher: "Epicurus",
    domain: "pleasure",
    gloss:
      "Pleasure reaches its ceiling once all pain has been removed; it cannot be increased beyond that.",
    grc: "Ὅρος τοῦ μεγέθους τῶν ἡδονῶν ἡ παντὸς τοῦ ἀλγοῦντος ὑπεξαίρεσις.",
    en: "The magnitude of pleasure reaches its limit in the removal of all pain",
    ref: "10.139",
    doctrine: "The magnitude of pleasure reaches its limit in the removal of all pain",
    certainty: "asserted",
    note: "Principal Doctrine 3 (Kyria Doxa III).",
  },
  {
    id: "epicurus-natural-justice-compact",
    philosopher: "Epicurus",
    domain: "politics",
    gloss:
      "Natural justice is a compact of mutual expediency, to keep men from harming or being harmed.",
    grc: "Τὸ τῆς φύσεως δίκαιόν ἐστι σύμβολον τοῦ συμφέροντος εἰς τὸ μὴ βλάπτειν ἀλλήλους μηδὲ βλάπτεσθαι.",
    en: "Natural justice is a symbol or expression of expediency, to prevent one man from harming or being harmed by another",
    ref: "10.150",
    doctrine:
      "Natural justice is a compact of expediency, to prevent one man from harming or being harmed by another; there is no absolute justice",
    certainty: "asserted",
    note: "Principal Doctrine 31 (Kyria Doxa XXXI).",
  },
  {
    id: "epicurus-friendship-greatest-blessing",
    philosopher: "Epicurus",
    domain: "ethics",
    gloss:
      "Of all that wisdom provides for lifelong happiness, the acquisition of friends is by far the greatest.",
    grc: "Ὧν ἡ σοφία παρασκευάζεται εἰς τὴν τοῦ ὅλου βίου μακαριότητα, πολὺ μέγιστόν ἐστιν ἡ τῆς φιλίας κτῆσις.",
    en: "Of all the means which are procured by wisdom to ensure happiness throughout the whole of life, by far the most important is the acquisition of friends",
    ref: "10.148",
    doctrine:
      "Of all the means to ensure happiness throughout life, by far the most important is the acquisition of friends",
    certainty: "asserted",
    note: "Principal Doctrine 27 (Kyria Doxa XXVII).",
  },
  {
    id: "epicurus-nothing-from-nothing",
    philosopher: "Epicurus",
    domain: "first-principles",
    gloss: "Nothing comes into being out of the non-existent.",
    grc: "οὐδὲν γίνεται ἐκ τοῦ μὴ ὄντος",
    en: "nothing comes into being out of what is non-existent",
    ref: "10.38",
    certainty: "asserted",
  },
  {
    id: "epicurus-sensations-are-the-criterion",
    philosopher: "Epicurus",
    domain: "epistemology",
    gloss: "The senses and feelings are the standards to which all inquiry must be referred.",
    grc: "τὰς αἰσθήσεις δεῖ πάντως τηρεῖν καὶ ἁπλῶς τὰς παρούσας ἐπιβολὰς εἴτε διανοίας εἴθʼ ὅτου δήποτε τῶν κριτηρίων",
    en: "we must by all means stick to our sensations, that is, simply to the present impressions whether of the mind or of any criterion whatever, and similarly to our actual feelings",
    ref: "10.38",
    certainty: "asserted",
  },
  {
    id: "epicurus-sum-of-things-unchanging",
    philosopher: "Epicurus",
    domain: "physics",
    gloss: "The totality of things is eternal and unchanging, for there is nothing outside it into which it could change.",
    grc: "τὸ πᾶν ἀεὶ τοιοῦτον ἦν οἷον νῦν ἐστι, καὶ ἀεὶ τοιοῦτον ἔσται",
    en: "the sum total of things was always such as it is now, and such it will ever remain. For there is nothing into which it can change",
    ref: "10.39",
    certainty: "asserted",
  },
  {
    id: "epicurus-bodies-and-void",
    philosopher: "Epicurus",
    domain: "first-principles",
    gloss: "The whole of being is composed of bodies and void.",
    grc: "τὸ πᾶν ἐστι σώματα καὶ κενόν",
    en: "the whole of being consists of bodies and space",
    ref: "10.39",
    doctrine: "The whole of being consists of bodies and space (void)",
    certainty: "asserted",
  },
  {
    id: "epicurus-void-enables-motion",
    philosopher: "Epicurus",
    domain: "physics",
    gloss: "Without void bodies would have nowhere to be and no way to move.",
    grc: "εἰ δὲ μὴ ἦν ὃ κενὸν καὶ χώραν καὶ ἀναφῆ φύσιν ὀνομάζομεν, οὐκ ἂν εἶχε τὰ σώματα ὅπου ἦν οὐδὲ διʼ οὗ ἐκινεῖτο",
    en: "if there were no space (which we call also void and place and intangible nature), bodies would have nothing in which to be and through which to move",
    ref: "10.40",
    certainty: "asserted",
  },
  {
    id: "epicurus-atoms-first-beginnings",
    philosopher: "Epicurus",
    domain: "first-principles",
    gloss: "The ultimate constituents are indivisible, unchangeable corporeal atoms.",
    grc: "τὰς ἀρχὰς ἀτόμους ἀναγκαῖον εἶναι σωμάτων φύσεις",
    en: "the first beginnings must be indivisible, corporeal entities",
    ref: "10.41",
    doctrine: "The first beginnings are indivisible, unchangeable corporeal entities (atoms)",
    certainty: "asserted",
  },
  {
    id: "epicurus-sum-of-things-infinite",
    philosopher: "Epicurus",
    domain: "cosmology",
    gloss: "The universe is infinite, unlimited alike in the number of atoms and the extent of the void.",
    grc: "τῷ πλήθει τῶν σωμάτων ἄπειρόν ἐστι τὸ πᾶν καὶ τῷ μεγέθει τοῦ κενοῦ",
    en: "the sum of things is unlimited both by reason of the multitude of the atoms and the extent of the void",
    ref: "10.41",
    doctrine: "The sum of things is infinite, unlimited both by the multitude of atoms and the extent of the void",
    certainty: "asserted",
  },
  {
    id: "epicurus-atoms-vary-in-shape",
    philosopher: "Epicurus",
    domain: "physics",
    gloss: "Atoms differ in an indefinite variety of shapes, accounting for the variety of things.",
    grc: "ἀπερίληπτά ἐστι ταῖς διαφοραῖς τῶν σχημάτων",
    en: "vary indefinitely in their shapes; for so many varieties of things as we see could never have arisen out of a recurrence of a definite number of the same shapes",
    ref: "10.42",
    certainty: "asserted",
  },
  {
    id: "epicurus-atoms-in-perpetual-motion",
    philosopher: "Epicurus",
    domain: "physics",
    gloss: "The atoms move ceaselessly for all eternity.",
    grc: "Κινοῦνταί τε συνεχῶς αἱ ἄτομοι",
    en: "The atoms are in continual motion through all eternity",
    ref: "10.43",
    certainty: "asserted",
  },
  {
    id: "epicurus-atoms-shape-size-weight",
    philosopher: "Epicurus",
    domain: "physics",
    gloss: "Atoms have no qualities of observable things save shape, weight, and size.",
    grc: "τὰς ἀτόμους νομιστέον μηδεμίαν ποιότητα τῶν φαινομένων προσφέρεσθαι πλὴν σχήματος καὶ βάρους καὶ μεγέθους",
    en: "the atoms in fact possess none of the qualities belonging to things which come under our observation, except shape, weight, and size",
    ref: "10.54",
    certainty: "asserted",
  },
  {
    id: "epicurus-infinite-worlds",
    philosopher: "Epicurus",
    domain: "cosmology",
    gloss: "There are infinitely many worlds, some like ours and some unlike.",
    grc: "κόσμοι ἄπειροί εἰσιν, οἵ θʼ ὅμοιοι τούτῳ καὶ ἀνόμοιοι",
    en: "there is an infinite number of worlds, some like this world, others unlike it",
    ref: "10.45",
    certainty: "asserted",
  },
  {
    id: "epicurus-eidola-images",
    philosopher: "Epicurus",
    domain: "physics",
    gloss: "Thin films (eidola) shaped like solid bodies stream off them and are the images we perceive.",
    grc: "τύποι ὁμοιοσχήμονες τοῖς στερεμνίοις εἰσί, λεπτότησιν ἀπέχοντες μακρὰν τῶν φαινομένων",
    en: "there are outlines or films, which are of the same shape as solid bodies, but of a thinness far exceeding that of any object that we see",
    ref: "10.46",
    certainty: "asserted",
  },
  {
    id: "epicurus-soul-fine-textured-body",
    philosopher: "Epicurus",
    domain: "soul",
    gloss: "The soul is a body of fine particles dispersed through the whole frame, resembling breath mixed with heat.",
    grc: "ἡ ψυχὴ σῶμά ἐστι λεπτομερὲς παρʼ ὅλον τὸ ἄθροισμα παρεσπαρμένον, προσεμφερέστατον δὲ πνεύματι θερμοῦ τινα κρᾶσιν ἔχοντι",
    en: "the soul is a corporeal thing, composed of fine particles, dispersed all over the frame, most nearly resembling wind with an admixture of heat",
    ref: "10.63",
    certainty: "asserted",
  },
  {
    id: "epicurus-soul-scattered-at-death",
    philosopher: "Epicurus",
    domain: "death",
    gloss: "When the body dissolves the soul is scattered and loses its powers, motions, and sentience.",
    grc: "λυομένου τοῦ ὅλου ἀθροίσματος ἡ ψυχὴ διασπείρεται καὶ οὐκέτι ἔχει τὰς αὐτὰς δυνάμεις οὐδὲ κινεῖται, ὥσπερ οὐδʼ αἴσθησιν κέκτηται",
    en: "when the whole frame is broken up, the soul is scattered and has no longer the same powers as before, nor the same motions; hence it does not possess sentience either",
    ref: "10.65",
    certainty: "asserted",
  },
  {
    id: "epicurus-celestial-not-gods-work",
    philosopher: "Epicurus",
    domain: "gods",
    gloss: "Celestial motions occur by natural causes, not by the command of any blessed, immortal being.",
    grc: "ἐν τοῖς μετεώροις φορὰν καὶ τροπὴν καὶ ἔκλειψιν καὶ ἀνατολὴν καὶ δύσιν καὶ τὰ σύστοιχα τούτοις μήτε λειτουργοῦντός τινος νομίζειν δεῖ γενέσθαι",
    en: "we are bound to believe that in the sky revolutions, solstices, eclipses, risings and settings, and the like, take place without the ministration or command, either now or in the future, of any being who at the same time enjoys perfect bliss along with immortality",
    ref: "10.76",
    certainty: "asserted",
  },
  {
    id: "epicurus-multiple-explanations",
    philosopher: "Epicurus",
    domain: "epistemology",
    gloss: "Celestial phenomena admit of several explanations, all consistent with sensation - no single account need be forced.",
    grc: "ταῦτά γε πλεοναχὴν ἔχει καὶ τῆς γενέσεως αἰτίαν καὶ τῆς οὐσίας ταῖς αἰσθήσεσι σύμφωνον κατηγορίαν",
    en: "these at any rate admit of manifold causes for their occurrence and manifold accounts, none of them contradictory of sensation",
    ref: "10.86",
    certainty: "asserted",
  },
  {
    id: "epicurus-sun-size-as-it-appears",
    philosopher: "Epicurus",
    domain: "cosmology",
    gloss: "The sun and stars are, relative to us, just as large as they appear to sense.",
    grc: "Τὸ δὲ μέγεθος ἡλίου τε καὶ τῶν λοιπῶν ἄστρων κατὰ μὲν τὸ πρὸς ἡμᾶς τηλικοῦτόν ἐστιν ἡλίκον φαίνεται",
    en: "The size of the sun and the remaining stars relatively to us is just as great as it appears",
    ref: "10.91",
    certainty: "asserted",
  },
];
