/**
 * Curated doxography from Book 9 of Diogenes Laertius' Lives, cited to
 * Hicks section ids (book.section). See doxai.ts for the model and curation
 * rules. Source-internal: every `en` is a verbatim excerpt of its cited
 * section.
 */
import type { Doxa } from "../doxai";

export const BOOK9_DOXAI: Doxa[] = [
  // ---------------------------------------------------------------- Heraclitus
  {
    id: "heraclitus-all-from-fire",
    philosopher: "Heraclitus",
    domain: "first-principles",
    gloss: "Fire is the primary substance: all things arise from it and are resolved back into it.",
    grc: "ἐκ πυρὸς τὰ πάντα συνεστάναι καὶ εἰς τοῦτο ἀναλύεσθαι",
    en: "All things are composed of fire, and into fire they are again resolved",
    ref: "9.7",
    doctrine: "All things are composed of fire and into fire are again resolved",
    certainty: "asserted",
  },
  {
    id: "heraclitus-flux-opposites",
    philosopher: "Heraclitus",
    domain: "physics",
    gloss: "All things come to be through the strife of opposites, and the whole is in perpetual flux.",
    grc: "γίνεσθαί τε πάντα κατʼ ἐναντιότητα καὶ ῥεῖν τὰ ὅλα ποταμοῦ δίκην",
    en: "All things come into being by conflict of opposites, and the sum of things flows like a stream",
    ref: "9.8",
    doctrine: "All that is flows like a stream and comes into being by conflict of opposites",
    certainty: "asserted",
  },
  {
    id: "heraclitus-periodic-conflagration",
    philosopher: "Heraclitus",
    domain: "cosmology",
    gloss: "The one world is alternately born from fire and resolved back into fire in fixed cycles for ever, as destiny determines.",
    grc: "γεννᾶσθαί τε αὐτὸν ἐκ πυρὸς καὶ πάλιν ἐκπυροῦσθαι κατά τινας περιόδους ἐναλλὰξ τὸν σύμπαντα αἰῶνα· τοῦτο δὲ γίνεσθαι καθʼ εἱμαρμένην",
    en: "it is alternately born from fire and again resolved into fire in fixed cycles to all eternity, and this is determined by destiny",
    ref: "9.8",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Xenophanes
  {
    id: "xenophanes-god-one-spherical",
    philosopher: "Xenophanes",
    domain: "gods",
    gloss: "God is a single spherical being, wholly unlike man, all perception and thought, and eternal.",
    grc: "οὐσίαν θεοῦ σφαιροειδῆ, μηδὲν ὅμοιον ἔχουσαν ἀνθρώπῳ· ὅλον δὲ ὁρᾶν καὶ ὅλον ἀκούειν, μὴ μέντοι ἀναπνεῖν· σύμπαντά τε εἶναι νοῦν καὶ φρόνησιν καὶ ἀΐδιον",
    en: "The substance of God is spherical, in no way resembling man. He is all eye and all ear, but does not breathe; he is the totality of mind and thought, and is eternal",
    ref: "9.19",
    doctrine: "The substance of God is spherical, in no way resembling man; all eye and all ear, eternal",
    certainty: "asserted",
  },
  {
    id: "xenophanes-perishable-and-soul-breath",
    philosopher: "Xenophanes",
    domain: "physics",
    gloss: "Whatever comes into being must perish, and the soul is breath.",
    grc: "πᾶν τὸ γινόμενον φθαρτόν ἐστι καὶ ἡ ψυχὴ πνεῦμα",
    en: "everything which comes into being is doomed to perish, and that the soul is breath",
    ref: "9.19",
    doctrine: "Everything which comes into being is doomed to perish, and the soul is breath",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Parmenides
  {
    id: "parmenides-two-philosophies",
    philosopher: "Parmenides",
    domain: "logic",
    gloss: "Philosophy has two parts: the way of truth and the way of opinion.",
    grc: "δισσήν τε ἔφη τὴν φιλοσοφίαν, τὴν μὲν κατʼ ἀλήθειαν, τὴν δὲ κατὰ δόξαν",
    en: "He divided his philosophy into two parts dealing the one with truth, the other with opinion",
    ref: "9.22",
    doctrine: "Philosophy is divided into two parts, dealing the one with truth, the other with opinion",
    certainty: "asserted",
  },
  {
    id: "parmenides-reason-standard",
    philosopher: "Parmenides",
    domain: "epistemology",
    gloss: "Reason is the criterion of truth; the senses are inexact.",
    grc: "κριτήριον δὲ τὸν λόγον εἶπε· τάς τε αἰσθήσεις μὴ ἀκριβεῖς ὑπάρχειν",
    en: "He made reason the standard and pronounced sensations to be inexact",
    ref: "9.22",
    doctrine: "Reason is the standard; sensations are inexact",
    certainty: "asserted",
  },
  // ------------------------------------------------------------------ Melissus
  {
    id: "melissus-one-unlimited-being",
    philosopher: "Melissus",
    domain: "first-principles",
    gloss: "The universe is one, unlimited, unchanging, immovable and full; motion is only apparent.",
    grc: "τὸ πᾶν ἄπειρον εἶναι καὶ ἀναλλοίωτον καὶ ἀκίνητον καὶ ἓν ὅμοιον ἑαυτῷ καὶ πλῆρες· κίνησίν τε μὴ εἶναι, δοκεῖν δʼ εἶναι",
    en: "the universe was unlimited, unchangeable and immovable, and was one, uniform and full of matter. There was no real, but only apparent, motion",
    ref: "9.24",
    doctrine: "The universe is unlimited, unchangeable, immovable, one, uniform and full of matter; motion is only apparent",
    certainty: "asserted",
  },
  {
    id: "melissus-no-knowledge-of-gods",
    philosopher: "Melissus",
    domain: "gods",
    gloss: "We should make no assertions about the gods, since knowledge of them is impossible.",
    grc: "περὶ θεῶν ἔλεγε μὴ δεῖν ἀποφαίνεσθαι· μὴ γὰρ εἶναι γνῶσιν αὐτῶν",
    en: "we ought not to make any statements about the gods, for it was impossible to have knowledge of them",
    ref: "9.24",
    doctrine: "We ought not to make any statements about the gods, for it is impossible to have knowledge of them",
    certainty: "asserted",
  },
  // -------------------------------------------------------------- Zeno of Elea
  {
    id: "zeno-elea-worlds-no-void",
    philosopher: "Zeno of Elea",
    domain: "physics",
    gloss: "There are worlds, but no empty space (void) exists.",
    grc: "κόσμους εἶναι κενόν τε μὴ εἶναι",
    en: "There are worlds, but there is no empty space",
    ref: "9.29",
    doctrine: "There are worlds, but there is no empty space",
    certainty: "asserted",
  },
  // ----------------------------------------------------------------- Leucippus
  {
    id: "leucippus-worlds-from-atoms-void",
    philosopher: "Leucippus",
    domain: "cosmology",
    gloss: "Worlds form when atoms fall into the void and become entangled with one another.",
    grc: "τούς τε κόσμους γίνεσθαι σωμάτων εἰς τὸ κενὸν ἐμπιπτόντων καὶ ἀλλήλοις περιπλεκομένων",
    en: "The worlds are formed when atoms fall into the void and are entangled with one another",
    ref: "9.30",
    doctrine: "Atoms and the void are first principles; the worlds are formed when atoms fall into the void and entangle in a vortex",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Democritus
  {
    id: "democritus-atoms-and-void",
    philosopher: "Democritus",
    domain: "first-principles",
    gloss: "Atoms and empty space are the first principles; everything else exists only by convention.",
    grc: "ἀρχὰς εἶναι τῶν ὅλων ἀτόμους καὶ κενόν, τὰ δʼ ἄλλα πάντα νενομίσθαι",
    en: "The first principles of the universe are atoms and empty space; everything else is merely thought to exist",
    ref: "9.44",
    doctrine: "The first principles of the universe are atoms and empty space; everything else is merely thought to exist",
    certainty: "asserted",
  },
  {
    id: "democritus-unlimited-worlds",
    philosopher: "Democritus",
    domain: "cosmology",
    gloss: "The worlds are unlimited in number, subject to coming-to-be and perishing.",
    grc: "ἀπείρους τε εἶναι κόσμους καὶ γενητοὺς καὶ φθαρτούς",
    en: "The worlds are unlimited; they come into being and perish",
    ref: "9.44",
    certainty: "asserted",
  },
  {
    id: "democritus-cheerfulness-the-end",
    philosopher: "Democritus",
    domain: "ethics",
    gloss: "The end (telos) is cheerfulness - a calm, steady state of the soul, not bodily pleasure.",
    grc: "τέλος δʼ εἶναι τὴν εὐθυμίαν, οὐ τὴν αὐτὴν οὖσαν τῇ ἡδονῇ",
    en: "The end of action is tranquillity, which is not identical with pleasure, as some by a false interpretation have understood, but a state in which the soul continues calm and strong, undisturbed by any fear or superstition or any other emotion",
    ref: "9.45",
    doctrine: "The end of action is tranquillity, a state in which the soul continues calm and strong, undisturbed by fear or superstition",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Protagoras
  {
    id: "protagoras-man-the-measure",
    philosopher: "Protagoras",
    domain: "epistemology",
    gloss: "Man is the measure of all things - of what is, that it is; of what is not, that it is not.",
    grc: "πάντων χρημάτων μέτρον ἄνθρωπος, τῶν μὲν ὄντων ὡς ἔστιν, τῶν δὲ οὐκ ὄντων ὡς οὐκ ἔστιν",
    en: "Man is the measure of all things, of things that are that they are, and of things that are not that they are not",
    ref: "9.51",
    doctrine: "Man is the measure of all things, of things that are that they are, and of things that are not that they are not",
    certainty: "asserted",
  },
  {
    id: "protagoras-two-opposed-accounts",
    philosopher: "Protagoras",
    domain: "logic",
    gloss: "On every matter there are two mutually opposed accounts.",
    grc: "δύο λόγους εἶναι περὶ παντὸς πράγματος ἀντικειμένους ἀλλήλοις",
    en: "there are two sides to every question, opposed to each other",
    ref: "9.51",
    doctrine: "There are two sides to every question, opposed to each other",
    certainty: "asserted",
  },
  {
    id: "pyrrho-acatalepsy-epoche",
    philosopher: "Pyrrho",
    domain: "epistemology",
    gloss: "He introduced the form of acatalepsy (agnosticism) and suspension of judgement.",
    grc: "τὸ τῆς ἀκαταληψίας καὶ ἐποχῆς εἶδος εἰσαγαγών",
    en: "taking the form of agnosticism and suspension of judgement",
    ref: "9.61",
    certainty: "reported",
    accordingTo: "Ascanius of Abdera",
  },
  {
    id: "pyrrho-ou-mallon",
    philosopher: "Pyrrho",
    domain: "epistemology",
    gloss: "Nothing is really existent; custom governs action, and no thing is any more this than that.",
    grc: "νόμῳ δὲ καὶ ἔθει πάντα τοὺς ἀνθρώπους πράττειν· οὐ γὰρ μᾶλλον τόδε ἢ τόδε εἶναι ἕκαστον",
    en: "he held that there is nothing really existent, but custom and convention govern human action; for no single thing is in itself any more this than that",
    ref: "9.61",
    certainty: "asserted",
  },
  {
    id: "pyrrho-nothing-honourable-just",
    philosopher: "Pyrrho",
    domain: "ethics",
    gloss: "He denied that anything is by nature honourable or dishonourable, just or unjust.",
    grc: "οὐδὲν γὰρ ἔφασκεν οὔτε καλὸν οὔτʼ αἰσχρὸν οὔτε δίκαιον οὔτʼ ἄδικον",
    en: "He denied that anything was honourable or dishonourable, just or unjust.",
    ref: "9.61",
    certainty: "asserted",
  },
  {
    id: "pyrrho-isostheneia",
    philosopher: "Pyrrho",
    domain: "epistemology",
    gloss: "When opposed arguments carry equal weight, ignorance of the truth necessarily follows.",
    grc: "τῶν μὲν γὰρ πραγμάτων διαφωνούντων, τῶν δὲ λόγων ἰσοσθενούντων ἀγνωσία τῆς ἀληθείας ἐπακολουθεῖ",
    en: "when facts disagree, but the contradictory statements have exactly the same weight, ignorance of the truth is the necessary consequence",
    ref: "9.76",
    certainty: "asserted",
  },
  {
    id: "pyrrho-ten-modes",
    philosopher: "Pyrrho",
    domain: "epistemology",
    gloss: "The perplexities that force suspension are ordered under ten modes of variation.",
    grc: "ἦσαν κατὰ δέκα τρόπους, καθʼ οὓς τὰ ὑποκείμενα παραλλάττοντα ἐφαίνετο",
    en: "these perplexities they distinguished under ten different modes in which the subjects in question appeared to vary",
    ref: "9.79",
    certainty: "asserted",
  },
  {
    id: "pyrrho-deny-proof-and-criterion",
    philosopher: "Pyrrho",
    domain: "logic",
    gloss: "They abolished demonstration, criterion, sign, cause, motion, learning, becoming and natural good and evil.",
    grc: "Ἀνῄρουν δʼ οὗτοι καὶ πᾶσαν ἀπόδειξιν καὶ κριτήριον καὶ σημεῖον καὶ αἴτιον καὶ κίνησιν καὶ μάθησιν καὶ γένεσιν καὶ τὸ φύσει τι εἶναι ἀγαθὸν ἢ κακόν",
    en: "They would deny all demonstration, criterion, sign, cause, motion, the process of learning, coming into being, or that there is anything good or bad by nature.",
    ref: "9.90",
    certainty: "asserted",
  },
  {
    id: "pyrrho-criterion-unknowable",
    philosopher: "Pyrrho",
    domain: "epistemology",
    gloss: "Because the criterion cannot be established without circularity, it and truth alike are unknowable.",
    grc: "ἄγνωστον οὖν ἐστι τὸ κριτήριον καὶ διὰ τοῦτο ἡ ἀλήθεια",
    en: "Hence the criterion is unknowable, and consequently truth also.",
    ref: "9.95",
    certainty: "asserted",
  },
  {
    id: "pyrrho-no-good-bad-by-nature",
    philosopher: "Pyrrho",
    domain: "ethics",
    gloss: "There is no good or bad by nature, since nothing is good or bad for all alike; the natural good is unknowable.",
    grc: "Φύσει τε μὴ εἶναι ἀγαθὸν ἢ κακόν",
    en: "There is nothing good or bad by nature",
    ref: "9.101",
    certainty: "asserted",
  },
  {
    id: "pyrrho-suspend-on-non-evident",
    philosopher: "Pyrrho",
    domain: "epistemology",
    gloss: "They suspend judgement about non-evident things and confine knowledge to their own impressions.",
    grc: "περὶ τούτων ἐπέχομεν ὡς ἀδήλων, μόνα δὲ τὰ πάθη γινώσκομεν",
    en: "we suspend our judgement because they are not certain, and confine knowledge to our impressions",
    ref: "9.103",
    certainty: "asserted",
  },
  {
    id: "pyrrho-appearance-criterion",
    philosopher: "Pyrrho",
    domain: "epistemology",
    gloss: "The apparent is the Sceptic's criterion - they follow phenomena alone.",
    grc: "ἔστιν οὖν κριτήριον κατὰ τοὺς σκεπτικοὺς τὸ φαινόμενον",
    en: "the apparent is the Sceptic's criterion",
    ref: "9.106",
    certainty: "reported",
    note: "D.L.: 'as indeed Aenesidemus says; and so does Epicurus.'",
  },
  {
    id: "timon-telos-epoche-ataraxia",
    philosopher: "Timon",
    domain: "ethics",
    gloss: "The end is suspension of judgement, upon which tranquillity follows like a shadow.",
    grc: "τέλος δὲ οἱ σκεπτικοί φασι τὴν ἐποχήν, ᾗ σκιᾶς τρόπον ἐπακολουθεῖ ἡ ἀταραξία",
    en: "The end to be realized they hold to be suspension of judgement, which brings with it tranquillity like its shadow",
    ref: "9.107",
    certainty: "reported",
    crossAttributed: true,
    note: "D.L. credits the telos to Timon and Aenesidemus jointly, inside Pyrrho's life.",
  },
  {
    id: "pyrrho-suspend-in-inquiry-not-life",
    philosopher: "Pyrrho",
    domain: "ethics",
    gloss: "The Sceptic suspends judgement in the search for truth, but follows habit and custom in practical life.",
    grc: "περὶ τῶν δογματικῶν ζητήσεων ἐπέχειν, οὐ περὶ τῶν βιωτικῶν καὶ τηρητικῶν",
    en: "he will be able so to live as to suspend his judgement in cases where it is a question of arriving at the truth, but not in matters of life and the taking of precautions",
    ref: "9.108",
    certainty: "asserted",
  },
];
