/**
 * Curated doxography from Book 7 of Diogenes Laertius' Lives, cited to
 * Hicks section ids (book.section). See doxai.ts for the model and curation
 * rules. Source-internal: every `en` is a verbatim excerpt of its cited
 * section.
 */
import type { Doxa } from "../doxai";

export const BOOK7_DOXAI: Doxa[] = [
  // ============================================================ Stoic ethics
  // The doctrinal summary in Zeno's life (7.84-131). Owner is Zeno of
  // Citium; where D.L. credits Chrysippus or Cleanthes by name for a
  // DISTINCT tenet, the holder is set and crossAttributed flagged.
  {
    id: "zeno-citium-first-impulse-self-preservation",
    philosopher: "Zeno of Citium",
    domain: "ethics",
    gloss:
      "An animal's first impulse is not to pleasure but to self-preservation, nature endearing it to itself from birth (oikeiosis).",
    grc: "Τὴν δὲ πρώτην ὁρμήν φασι τὸ ζῷον ἴσχειν ἐπὶ τὸ τηρεῖν ἑαυτό, οἰκειούσης αὑτῷ τῆς φύσεως ἀπʼ ἀρχῆς",
    en: "An animal’s first impulse, say the Stoics, is to selfpreservation, because nature from the outset endears it to itself",
    ref: "7.85",
    doctrine:
      "An animal's first impulse is to self-preservation, nature endearing it to itself from the outset",
    certainty: "reported",
    accordingTo: "Chrysippus",
  },
  {
    id: "zeno-citium-telos-agreement-nature",
    philosopher: "Zeno of Citium",
    domain: "ethics",
    gloss:
      "Zeno first fixed the end (telos) as life in agreement with nature, which is the same as a virtuous life.",
    grc: "Διόπερ πρῶτος ὁ Ζήνων ἐν τῷ Περὶ ἀνθρώπου φύσεως τέλος εἶπε τὸ ὁμολογουμένως τῇ φύσει ζῆν, ὅπερ ἐστὶ κατʼ ἀρετὴν ζῆν",
    en: "Zeno was the first (in his treatise On the Nature of Man ) to designate as the end life in agreement with nature (or living agreeably to nature), which is the same as a virtuous life",
    ref: "7.87",
    doctrine: "Life in agreement with nature is the end",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-only-good-is-beautiful",
    philosopher: "Zeno of Citium",
    domain: "ethics",
    gloss:
      "Only the morally beautiful is good: virtue and what shares in virtue exhaust the class of goods.",
    grc: "Λέγουσι δὲ μόνον τὸ καλὸν ἀγαθὸν εἶναι",
    en: "only the morally beautiful is good",
    ref: "7.101",
    certainty: "reported",
    note: "D.L. cites Hecato (On Goods, bk. iii) and Chrysippus (On the Morally Beautiful).",
  },
  {
    id: "zeno-citium-goods-evils-indifferents",
    philosopher: "Zeno of Citium",
    domain: "ethics",
    gloss:
      "Between goods (the virtues) and evils (the vices) lie the indifferents - life, health, wealth and the rest - which neither benefit nor harm.",
    grc: "οὐδέτερα δὲ ὅσα μήτʼ ὠφελεῖ μήτε βλάπτει, οἷον ζωή, ὑγίεια, ἡδονή, κάλλος, ἰσχύς, πλοῦτος, εὐδοξία, εὐγένεια",
    en: "Neutral (neither good nor evil, that is) are all those things which neither benefit nor harm a man: such as life, health, pleasure, beauty, strength, wealth, fair fame and noble birth",
    ref: "7.102",
    certainty: "reported",
  },
  {
    id: "zeno-citium-preferred-rejected-indifferents",
    philosopher: "Zeno of Citium",
    domain: "ethics",
    gloss:
      "Among indifferents, those having value are 'preferred' (proegmena), those having disvalue 'rejected' (apoproegmena).",
    grc: "Τῶν ἀδιαφόρων τὰ μὲν λέγουσι προηγμένα, τὰ δὲ ἀποπροηγμένα· προηγμένα μὲν τὰ ἔχοντα ἀξίαν, ἀποπροηγμένα δὲ τὰ ἀπαξίαν ἔχοντα",
    en: "Of things indifferent, as they express it, some are preferred, others rejected. Such as have value, they say, are preferred, while such as have negative, instead of positive, value are rejected.",
    ref: "7.105",
    certainty: "reported",
  },
  {
    id: "zeno-citium-passion-irrational-movement",
    philosopher: "Zeno of Citium",
    domain: "ethics",
    gloss:
      "Passion (pathos) is an irrational and unnatural movement of the soul, or an impulse in excess.",
    grc: "ἔστι δὲ αὐτὸ τὸ πάθος κατὰ Ζήνωνα ἡ ἄλογος καὶ παρὰ φύσιν ψυχῆς κίνησις ἢ ὁρμὴ πλεονάζουσα",
    en: "Passion, or emotion, is defined by Zeno as an irrational and unnatural movement in the soul, or again as impulse in excess.",
    ref: "7.110",
    doctrine:
      "Passion is an irrational and unnatural movement in the soul, or impulse in excess",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-wise-man-passionless",
    philosopher: "Zeno of Citium",
    domain: "ethics",
    gloss:
      "The wise man is passionless (apathes), because he is not liable to fall into such infirmity.",
    grc: "Φασὶ δὲ καὶ ἀπαθῆ εἶναι τὸν σοφόν, διὰ τὸ ἀνέμπτωτον εἶναι",
    en: "Now they say that the wise man is passionless, because he is not prone to fall into such infirmity.",
    ref: "7.117",
    doctrine: "The wise man is passionless, not prone to fall into infirmity",
    certainty: "reported",
  },
  {
    id: "zeno-citium-wise-man-takes-part-in-politics",
    philosopher: "Zeno of Citium",
    domain: "politics",
    gloss:
      "The wise man will take part in politics, unless something hinders, so as to check vice and foster virtue.",
    grc: "Πολιτεύσεσθαί φασι τὸν σοφὸν ἂν μή τι κωλύῃ",
    en: "the Stoics say that the wise man will take part in politics, if nothing hinders him",
    ref: "7.121",
    certainty: "reported",
    accordingTo: "Chrysippus",
  },
  {
    id: "zeno-citium-wise-man-alone-free",
    philosopher: "Zeno of Citium",
    domain: "ethics",
    gloss:
      "The wise man alone is free and the bad are slaves, freedom being the power of independent action.",
    grc: "μόνον τʼ ἐλεύθερον, τοὺς δὲ φαύλους δούλους· εἶναι γὰρ τὴν ἐλευθερίαν ἐξουσίαν αὐτοπραγίας, τὴν δὲ δουλείαν στέρησιν αὐτοπραγίας",
    en: "They declare that he alone is free and bad men are slaves, freedom being power of independent action, whereas slavery is privation of the same",
    ref: "7.121",
    certainty: "reported",
  },
  {
    id: "zeno-citium-virtue-sufficient-happiness",
    philosopher: "Zeno of Citium",
    domain: "ethics",
    gloss:
      "Virtue is in itself sufficient to ensure well-being (happiness).",
    grc: "αὐτάρκη τʼ εἶναι αὐτὴν πρὸς εὐδαιμονίαν, καθά φησι Ζήνων καὶ Χρύσιππος ἐν τῷ πρώτῳ Περὶ ἀρετῶν καὶ Ἑκάτων ἐν τῷ δευτέρῳ Περὶ ἀγαθῶν",
    en: "they hold that it is in itself sufficient to ensure well-being: thus Zeno, and Chrysippus in the first book of his treatise On Virtues",
    ref: "7.127",
    doctrine: "Virtue is in itself sufficient to ensure well-being",
    certainty: "reported",
  },
  // ---------------------------------------------------- Chrysippus (in Zeno)
  {
    id: "chrysippus-nature-universal-and-human",
    philosopher: "Chrysippus",
    domain: "ethics",
    gloss:
      "For Chrysippus the nature we must live in accord with is both universal nature and, more particularly, the nature of man.",
    grc: "Φύσιν δὲ Χρύσιππος μὲν ἐξακούει, ᾗ ἀκολούθως δεῖ ζῆν, τήν τε κοινὴν καὶ ἰδίως τὴν ἀνθρωπίνην",
    en: "By the nature with which our life ought to be in accord, Chrysippus understands both universal nature and more particularly the nature of man",
    ref: "7.89",
    doctrine:
      "The nature with which life should accord is both universal nature and the nature of man",
    certainty: "asserted",
    crossAttributed: true,
  },
  {
    id: "chrysippus-emotions-are-judgements",
    philosopher: "Chrysippus",
    domain: "ethics",
    gloss:
      "The emotions are judgements - e.g. avarice is the supposition that money is a good.",
    grc: "δοκεῖ δʼ αὐτοῖς τὰ πάθη κρίσεις εἶναι, καθά φησι Χρύσιππος ἐν τῷ Περὶ παθῶν",
    en: "They hold the emotions to be judgements, as is stated by Chrysippus in his treatise On the Passions",
    ref: "7.111",
    doctrine: "The emotions are judgements",
    certainty: "reported",
    crossAttributed: true,
  },
  {
    id: "chrysippus-virtue-can-be-lost",
    philosopher: "Chrysippus",
    domain: "ethics",
    gloss:
      "Chrysippus held that virtue can be lost, in consequence of drunkenness or melancholy.",
    grc: "τὴν ἀρετὴν Χρύσιππος μὲν ἀποβλητήν",
    en: "Chrysippus holds that virtue can be lost",
    ref: "7.127",
    doctrine: "Virtue can be lost, in consequence of drunkenness or melancholy",
    certainty: "asserted",
    crossAttributed: true,
  },
  // ----------------------------------------------------- Cleanthes (in Zeno)
  {
    id: "cleanthes-nature-universe-alone",
    philosopher: "Cleanthes",
    domain: "ethics",
    gloss:
      "Cleanthes takes only the nature of the universe as the standard to follow, not the nature of the individual.",
    grc: "ὁ δὲ Κλεάνθης τὴν κοινὴν μόνην ἐκδέχεται φύσιν, ᾗ ἀκολουθεῖν δεῖ, οὐκέτι δὲ καὶ τὴν ἐπὶ μέρους",
    en: "whereas Cleanthes takes the nature of the universe alone as that which should be followed, without adding the nature of the individual",
    ref: "7.89",
    doctrine:
      "The nature to be followed as the end is the nature of the universe alone, not the nature of the individual",
    certainty: "asserted",
    crossAttributed: true,
  },
  {
    id: "cleanthes-virtue-cannot-be-lost",
    philosopher: "Cleanthes",
    domain: "ethics",
    gloss:
      "Against Chrysippus, Cleanthes held virtue to be inalienable, owing to the certainty of our mental apprehension.",
    grc: "ὁ δʼ ἀναπόβλητον διὰ βεβαίους καταλήψεις",
    en: "the latter takes it to be inalienable owing to the certainty of our mental apprehension",
    ref: "7.127",
    doctrine: "Virtue cannot be lost, owing to the certainty of our mental apprehension",
    certainty: "asserted",
    crossAttributed: true,
  },
  // -------------------------------------------------- Dissenting (heterodox) Stoics
  {
    id: "ariston-chios-unity-of-virtue",
    philosopher: "Ariston of Chios",
    domain: "ethics",
    gloss:
      "Ariston recognized neither a plurality of virtues nor one virtue under many names, but virtue as a single disposition in a relative mode.",
    grc: "ἀρετάς τʼ οὔτε πολλὰς εἰσῆγεν, ὡς ὁ Ζήνων, οὔτε μίαν πολλοῖς ὀνόμασι καλουμένην, ὡς οἱ Μεγαρικοί, ἀλλὰ κατὰ τὸ πρός τί πως ἔχειν",
    en: "He would not admit a plurality of virtues with Zeno, nor again with the Megarians one single virtue called by many names; but he treated virtue in accordance with the category of relative modes",
    ref: "7.161",
    certainty: "asserted",
  },
  {
    id: "herillus-telos-knowledge",
    philosopher: "Herillus",
    domain: "ethics",
    gloss:
      "Herillus made the end Knowledge - to live always by making the scientific life the standard in all things.",
    grc: "Ἥριλλος δʼ ὁ Καρχηδόνιος τέλος εἶπε τὴν ἐπιστήμην, ὅπερ ἐστὶ ζῆν ἀεὶ πάντʼ ἀναφέροντα πρὸς τὸ μετʼ ἐπιστήμης ζῆν καὶ μὴ τῇ ἀγνοίᾳ διαβεβλημένον",
    en: "Herillus of Carthage declared the end of action to be Knowledge, that is, so to live always as to make the scientific life the standard in all things and not to be misled by ignorance",
    ref: "7.165",
    doctrine:
      "The end of action is Knowledge: to live always so as to make the scientific life the standard in all things",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-three-part-division",
    philosopher: "Zeno of Citium",
    domain: "logic",
    gloss: "Philosophy divides into three parts: physics, ethics, and logic.",
    grc: "Τριμερῆ φασὶν εἶναι τὸν κατὰ φιλοσοφίαν λόγον· εἶναι γὰρ αὐτοῦ τὸ μέν τι φυσικόν, τὸ δὲ ἠθικόν, τὸ δὲ λογικόν.",
    en: "Philosophic doctrine, say the Stoics, falls into three parts: one physical, another ethical, and the third logical",
    ref: "7.39",
    doctrine: "Philosophic doctrine falls into three parts: physical, ethical, and logical",
    certainty: "asserted",
    note: "D.L.: Zeno of Citium was the first to make this division in his Exposition of Doctrine.",
  },
  {
    id: "cleanthes-six-part-division",
    philosopher: "Cleanthes",
    domain: "logic",
    gloss: "Cleanthes divides philosophy into six parts, not three.",
    grc: "ὁ δὲ Κλεάνθης ἓξ μέρη φησί, διαλεκτικόν, ῥητορικόν, ἠθικόν, πολιτικόν, φυσικόν, θεολογικόν.",
    en: "Cleanthes makes not three, but six parts, Dialectic, Rhetoric, Ethics, Politics, Physics, Theology",
    ref: "7.41",
    doctrine: "Philosophy has six parts: Dialectic, Rhetoric, Ethics, Politics, Physics, Theology",
    certainty: "reported",
    crossAttributed: true,
  },
  {
    id: "zeno-citium-presentation-imprint",
    philosopher: "Zeno of Citium",
    domain: "epistemology",
    gloss: "A presentation (phantasia) is an imprint made on the soul.",
    grc: "Τὴν δὲ φαντασίαν εἶναι τύπωσιν ἐν ψυχῇ",
    en: "A presentation (or mental impression) is an imprint on the soul: the name having been appropriately borrowed from the imprint made by the seal upon the wax",
    ref: "7.45",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-apprehending-presentation",
    philosopher: "Zeno of Citium",
    domain: "epistemology",
    gloss: "The apprehending presentation, proceeding from a real object, is the test of reality.",
    grc: "καταληπτικὴν μέν, ἣν κριτήριον εἶναι τῶν πραγμάτων φασί, τὴν γινομένην ἀπὸ ὑπάρχοντος κατʼ αὐτὸ τὸ ὑπάρχον ἐναπεσφραγισμένην καὶ ἐναπομεμαγμένην",
    en: "The former, which they take to be the test of reality, is defined as that which proceeds from a real object, agrees with that object itself, and has been imprinted seal-fashion and stamped upon the mind",
    ref: "7.46",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-criterion-of-truth",
    philosopher: "Zeno of Citium",
    domain: "epistemology",
    gloss: "The standard of truth is the apprehending presentation, which comes from a real object.",
    grc: "Κριτήριον δὲ τῆς ἀληθείας φασὶ τυγχάνειν τὴν καταληπτικὴν φαντασίαν, τουτέστι τὴν ἀπὸ ὑπάρχοντος",
    en: "The standard of truth they declare to be the apprehending presentation, i.e. that which comes from a real object",
    ref: "7.54",
    doctrine: "The standard of truth is the apprehending presentation, that which proceeds from a real object and is stamped seal-fashion on the mind",
    certainty: "reported",
    accordingTo: "Chrysippus",
    note: "D.L. also names Antipater and Apollodorus for this criterion.",
  },
  {
    id: "zeno-citium-two-principles",
    philosopher: "Zeno of Citium",
    domain: "first-principles",
    gloss: "Two principles: the active (reason/God) and the passive (unqualified matter).",
    grc: "Δοκεῖ δʼ αὐτοῖς ἀρχὰς εἶναι τῶν ὅλων δύο, τὸ ποιοῦν καὶ τὸ πάσχον.",
    en: "They hold that there are two principles in the universe, the active principle and the passive",
    ref: "7.134",
    doctrine: "There are two principles in the universe: the active (reason, i.e. God) and the passive (substance without quality, i.e. matter)",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-god-reason-fate-zeus",
    philosopher: "Zeno of Citium",
    domain: "gods",
    gloss: "God is identical with Reason, Fate, and Zeus, under many names.",
    grc: "Ἕν τʼ εἶναι θεὸν καὶ νοῦν καὶ εἱμαρμένην καὶ Δία· πολλάς τʼ ἑτέρας ὀνομασίας προσονομάζεσθαι.",
    en: "God is one and the same with Reason, Fate, and Zeus; he is also called by many other names",
    ref: "7.135",
    doctrine: "God is one and the same with Reason, Fate, and Zeus, the everlasting artificer of all things",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-four-elements",
    philosopher: "Zeno of Citium",
    domain: "physics",
    gloss: "God first generated the four elements: fire, water, air, earth.",
    grc: "εἶτʼ ἀπογεννᾶν πρῶτον τὰ τέσσαρα στοιχεῖα, πῦρ, ὕδωρ, ἀέρα, γῆν.",
    en: "he created first of all the four elements, fire, water, air, earth",
    ref: "7.136",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-world-providence",
    philosopher: "Zeno of Citium",
    domain: "gods",
    gloss: "The cosmos is governed by reason and providence.",
    grc: "Τὸν δὴ κόσμον διοικεῖσθαι κατὰ νοῦν καὶ πρόνοιαν",
    en: "The world, in their view, is ordered by reason and providence",
    ref: "7.138",
    doctrine: "The world is ordered by reason and providence",
    certainty: "reported",
    note: "D.L. cites Chrysippus On Providence bk 5 and Posidonius On the Gods bk 3.",
  },
  {
    id: "zeno-citium-world-living-being",
    philosopher: "Zeno of Citium",
    domain: "cosmology",
    gloss: "The whole world is a living, ensouled, rational being ruled by aether.",
    grc: "τὸν ὅλον κόσμον ζῷον ὄντα καὶ ἔμψυχον καὶ λογικόν, ἔχειν ἡγεμονικὸν μὲν τὸν αἰθέρα",
    en: "the whole world is a living being, endowed with soul and reason, and having aether for its ruling principle",
    ref: "7.139",
    certainty: "reported",
    accordingTo: "Antipater of Tyre",
  },
  {
    id: "cleanthes-sun-ruling-power",
    philosopher: "Cleanthes",
    domain: "cosmology",
    gloss: "Cleanthes makes the sun, not the heaven, the ruling power of the world.",
    grc: "Κλεάνθης δὲ τὸν ἥλιον.",
    en: "Cleanthes that the sun, is the ruling power of the world",
    ref: "7.139",
    doctrine: "The sun is the ruling power of the world",
    certainty: "reported",
    crossAttributed: true,
    note: "Against Chrysippus and Posidonius, who make the heaven the ruling power.",
  },
  {
    id: "zeno-citium-world-finite-spherical",
    philosopher: "Zeno of Citium",
    domain: "cosmology",
    gloss: "The world is one, finite, and spherical, with infinite void outside it.",
    grc: "Ἕνα τὸν κόσμον εἶναι καὶ τοῦτον πεπερασμένον, σχῆμʼ ἔχοντα σφαιροειδές",
    en: "The world, they say, is one and finite, having a spherical shape",
    ref: "7.140",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-god-not-anthropomorphic",
    philosopher: "Zeno of Citium",
    domain: "gods",
    gloss: "The deity takes providential care of the world and is not of human shape.",
    grc: "προνοητικὸν κόσμου τε καὶ τῶν ἐν κόσμῳ· μὴ εἶναι μέντοι ἀνθρωπόμορφον.",
    en: "taking providential care of the world and all that therein is, but he is not of human shape",
    ref: "7.147",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-fate-chain-of-causation",
    philosopher: "Zeno of Citium",
    domain: "fate",
    gloss: "Fate is an endless chain of causation by which the world proceeds.",
    grc: "ἔστι δʼ εἱμαρμένη αἰτία τῶν ὄντων εἰρομένη ἢ λόγος καθʼ ὃν ὁ κόσμος διεξάγεται.",
    en: "Fate is defined as an endless chain of causation, whereby things are, or as the reason or formula by which the world goes on",
    ref: "7.149",
    doctrine: "All things happen by fate or destiny, an endless chain of causation",
    certainty: "reported",
    note: "Maintained by Chrysippus, Posidonius, Zeno, and Boethus.",
  },
  {
    id: "zeno-citium-nature-creative-fire",
    philosopher: "Zeno of Citium",
    domain: "physics",
    gloss: "Nature is an artistically working fire, a creative, fashioning breath.",
    grc: "τὴν μὲν φύσιν εἶναι πῦρ τεχνικόν, ὁδῷ βαδίζον εἰς γένεσιν, ὅπερ ἐστὶ πνεῦμα πυροειδὲς καὶ τεχνοειδές",
    en: "Nature in their view is an artistically working fire, going on its way to create; which is equivalent to a fiery, creative, or fashioning breath",
    ref: "7.156",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-soul-warm-breath",
    philosopher: "Zeno of Citium",
    domain: "soul",
    gloss: "The soul is a warm breath, by which we live and move.",
    grc: "πνεῦμα ἔνθερμον εἶναι τὴν ψυχήν· τούτῳ γὰρ ἡμᾶς εἶναι ἔμπνους καὶ ὑπὸ τούτου κινεῖσθαι.",
    en: "define the soul as a warm breath; for by this we become animate and this enables us to move",
    ref: "7.157",
    doctrine: "The soul is a warm breath, by which we become animate and can move",
    certainty: "asserted",
    note: "So Zeno of Citium and Antipater in their treatises De anima, and Posidonius.",
  },
  {
    id: "chrysippus-souls-of-wise-survive",
    philosopher: "Chrysippus",
    domain: "soul",
    gloss: "Only the souls of the wise survive until the general conflagration.",
    grc: "Χρύσιππος δὲ τὰς τῶν σοφῶν μόνον.",
    en: "Chrysippus says that only the souls of the wise do so",
    ref: "7.157",
    doctrine: "Only the souls of the wise survive until the general conflagration",
    certainty: "reported",
    crossAttributed: true,
    note: "Against Cleanthes, who holds that all souls survive until the conflagration.",
  },
  // ============================================================ Heterodox Stoics
  // The three dissenters D.L. treats after the school summary (7.160-167):
  // Ariston of Chios, Herillus, Dionysius the Renegade.
  {
    id: "ariston-chios-telos-indifference",
    philosopher: "Ariston of Chios",
    domain: "ethics",
    gloss:
      "The end is a life of perfect indifference to everything between virtue and vice, admitting no gradations among indifferent things.",
    grc: "τέλος ἔφησεν εἶναι τὸ ἀδιαφόρως ἔχοντα ζῆν πρὸς τὰ μεταξὺ ἀρετῆς καὶ κακίας μηδʼ ἡντινοῦν ἐν αὐτοῖς παραλλαγὴν ἀπολείποντα, ἀλλʼ ἐπίσης ἐπὶ πάντων ἔχοντα",
    en: "declared the end of action to be a life of perfect indifference to everything which is neither virtue nor vice; recognizing no distinction whatever in things indifferent, but treating them all alike",
    ref: "7.160",
    doctrine:
      "The end of action is a life of perfect indifference to everything which is neither virtue nor vice",
    certainty: "asserted",
  },
  {
    id: "ariston-chios-ethics-alone-concerns-us",
    philosopher: "Ariston of Chios",
    domain: "logic",
    gloss:
      "Logic and Physics should be discarded - Physics is beyond us, Logic is nothing to us; only Ethics concerns us.",
    grc: "τόν τε φυσικὸν τόπον καὶ τὸν λογικὸν ἀνῄρει, λέγων τὸν μὲν εἶναι ὑπὲρ ἡμᾶς, τὸν δʼ οὐδὲν πρὸς ἡμᾶς, μόνον δὲ τὸν ἠθικὸν εἶναι πρὸς ἡμᾶς.",
    en: "He wished to discard both Logic and Physics, saying that Physics was beyond our reach and Logic did not concern us: all that did concern us was Ethics.",
    ref: "7.160",
    certainty: "asserted",
  },
  {
    id: "herillus-knowledge-habit-of-mind",
    philosopher: "Herillus",
    domain: "epistemology",
    gloss:
      "Knowledge is a habit of mind in the acceptance of presentations that cannot be upset by argument.",
    grc: "εἶναι δὲ τὴν ἐπιστήμην ἕξιν ἐν φαντασιῶν προσδέξει ἀνυπόπτωτον ὑπὸ λόγου",
    en: "Knowledge he defined as a habit of mind, not to be upset by argument, in the acceptance of presentations",
    ref: "7.165",
    certainty: "asserted",
  },
  {
    id: "herillus-end-in-chief-subordinate",
    philosopher: "Herillus",
    domain: "ethics",
    gloss:
      "The end-in-chief differs from the subordinate end: even the unwise may aim at the latter, only the wise at the true end.",
    grc: "διαφέρειν δὲ τέλος καὶ ὑποτελίδα· τῆς μὲν γὰρ καὶ τοὺς μὴ σοφοὺς στοχάζεσθαι, τοῦ δὲ μόνον τὸν σοφόν.",
    en: "He made a distinction between end-in-chief and subordinate end: even the unwise may aim at the latter, but only the wise seek the true end of life.",
    ref: "7.165",
    certainty: "asserted",
  },
  {
    id: "dionysius-renegade-telos-pleasure",
    philosopher: "Dionysius the Renegade",
    domain: "pleasure",
    gloss: "Pleasure is the end of action.",
    grc: "τέλος εἶπε τὴν ἡδονὴν",
    en: "declared that pleasure was the end of action",
    ref: "7.166",
    certainty: "asserted",
    note: "Adopted after an attack of ophthalmia left him unable to call pain indifferent; D.L. counts him with Ariston and Herillus among the heterodox Stoics.",
  },
];
