/**
 * Curated sayings & apophthegms from Book 2 of Diogenes Laertius' Lives
 * (Socratics), cited to Hicks section ids (book.section). See sayings.ts for
 * the model and curation rules. Source-internal: every `en` is a verbatim
 * excerpt of its cited section.
 */
import type { Saying } from "../sayings";

export const BOOK2_SAYINGS: Saying[] = [
  // -------------------------------------------------------------- Anaximander
  {
    id: "anaximander-improve-singing",
    philosopher: "Anaximander",
    topic: "wit",
    gloss: "When the boys laughed at his singing: then to please the boys he must improve it.",
    grc: "βέλτιον οὖν ἡμῖν ᾀστέον διὰ τὰ παιδάρια.",
    en: "Then to please the boys I must improve my singing.",
    ref: "2.2",
    certainty: "reported",
    note: "D.L.: 'There is a story that...'",
  },
  // ---------------------------------------------------------------- Anaxagoras
  {
    id: "anaxagoras-look-after-it",
    philosopher: "Anaxagoras",
    topic: "wealth",
    gloss: "Accused by his relations of neglecting the patrimony he gave up to them: why then do you not look after it?",
    grc: "τί οὖν, ἔφη, οὐχ ὑμεῖς ἐπιμελεῖσθε;",
    en: "Why then do you not look after it?",
    ref: "2.7",
    certainty: "asserted",
  },
  {
    id: "anaxagoras-fatherland-sky",
    philosopher: "Anaxagoras",
    topic: "wisdom",
    gloss: "Asked if he had no concern for his native land, he pointed to the sky: he was greatly concerned with his fatherland.",
    grc: "εὐφήμει, ἔφη, ἐμοὶ γὰρ καὶ σφόδρα μέλει τῆς πατρίδος, δείξας τὸν οὐρανόν.",
    en: "Gently, he replied, I am greatly concerned with my fatherland, and pointed to the sky.",
    ref: "2.7",
    certainty: "asserted",
  },
  {
    id: "anaxagoras-hills-become-sea",
    philosopher: "Anaxagoras",
    topic: "wisdom",
    gloss: "Asked if the hills at Lampsacus would ever become sea: yes, it only needs time.",
    grc: "ἐάν γε ὁ χρόνος μὴ ἐπιλίπῃ.",
    en: "Yes, it only needs time.",
    ref: "2.10",
    certainty: "reported",
    note: "D.L.: 'φασὶν εἰπεῖν' - 'they say he replied.'",
  },
  {
    id: "anaxagoras-born-to-study",
    philosopher: "Anaxagoras",
    topic: "wisdom",
    gloss: "Asked to what end he had been born: to study sun and moon and heavens.",
    grc: "εἰς θεωρίαν, ἔφη, ἡλίου καὶ σελήνης καὶ οὐρανοῦ.",
    en: "To study sun and moon and heavens.",
    ref: "2.10",
    certainty: "asserted",
  },
  {
    id: "anaxagoras-they-miss-mine",
    philosopher: "Anaxagoras",
    topic: "wit",
    gloss: "Asked if he missed the society of the Athenians: not I, but they miss mine.",
    grc: "οὐ μὲν οὖν, ἔφη, ἀλλʼ ἐκεῖνοι ἐμοῦ.",
    en: "Not I, but they miss mine.",
    ref: "2.10",
    certainty: "asserted",
  },
  {
    id: "anaxagoras-mausolus-tomb",
    philosopher: "Anaxagoras",
    topic: "wealth",
    gloss: "Seeing the tomb of Mausolus: a costly tomb is an image of an estate turned into stone.",
    grc: "τάφος πολυτελὴς λελιθωμένης ἐστὶν οὐσίας εἴδωλον.",
    en: "A costly tomb is an image of an estate turned into stone.",
    ref: "2.10",
    certainty: "asserted",
  },
  {
    id: "anaxagoras-descent-to-hades",
    philosopher: "Anaxagoras",
    topic: "death",
    gloss: "To one who complained of dying in a foreign land: the descent to Hades is the same from every place.",
    grc: "πανταχόθεν, ἔφη, ὁμοία ἐστὶν ἡ εἰς ᾅδου κατάβασις.",
    en: "The descent to Hades is much the same from whatever place we start.",
    ref: "2.11",
    certainty: "asserted",
  },
  {
    id: "anaxagoras-nature-condemned",
    philosopher: "Anaxagoras",
    topic: "death",
    gloss: "On hearing of his death sentence: nature long ago condemned both his judges and himself.",
    grc: "κἀκείνων κἀμοῦ πάλαι ἡ φύσις κατεψηφίσατο",
    en: "Long ago nature condemned both my judges and myself to death",
    ref: "2.13",
    certainty: "asserted",
    note: "The same retort is told of Socrates at 2.35, where D.L. adds 'some ascribe this to Anaxagoras.'",
  },
  {
    id: "anaxagoras-children-born-to-die",
    philosopher: "Anaxagoras",
    topic: "death",
    gloss: "On the news of his sons' death: he knew that his children were born to die.",
    grc: "ᾔδειν αὐτοὺς θνητοὺς γεννήσας",
    en: "I knew that my children were born to die.",
    ref: "2.13",
    certainty: "disputed",
    alsoAttributedTo: "Solon",
    note: "D.L.: 'Some, however, tell this story of Solon, and others of Xenophon.'",
  },
  {
    id: "anaxagoras-holiday-for-boys",
    philosopher: "Anaxagoras",
    topic: "death",
    gloss: "Asked by the magistrates of Lampsacus what they could do for him, he asked that the boys be given an annual holiday in the month of his death.",
    grc: "φάναι, τοὺς παῖδας ἐν ᾧ ἂν ἀποθάνῃ μηνὶ κατʼ ἔτος παίζειν συγχωρεῖν.",
    en: "he replied that he would like them to grant an annual holiday to the boys in the month in which he died",
    ref: "2.14",
    certainty: "asserted",
  },
  // ------------------------------------------------------------------ Socrates
  {
    id: "socrates-donkey-kick",
    philosopher: "Socrates",
    topic: "wit",
    gloss: "Kicked and asked why he took it so quietly: should he have taken the law of a donkey that kicked him?",
    grc: "εἰ δέ με ὄνος ἐλάκτισε, δίκην ἂν αὐτῷ ἐλάγχανον;",
    en: "Should I have taken the law of a donkey, supposing that he had kicked me?",
    ref: "2.21",
    certainty: "reported",
    accordingTo: "Demetrius of Byzantium",
  },
  {
    id: "socrates-delian-diver",
    philosopher: "Socrates",
    topic: "wisdom",
    gloss: "On Heraclitus' treatise, which Euripides gave him: excellent where understood, but it needs a Delian diver to get to the bottom of it.",
    grc: "ἃ μὲν συνῆκα, γενναῖα· οἶμαι δὲ καὶ ἃ μὴ συνῆκα· πλὴν Δηλίου γέ τινος δεῖται κολυμβητοῦ.",
    en: "The part I understand is excellent, and so too is, I dare say, the part I do not understand; but it needs a Delian diver to get to the bottom of it.",
    ref: "2.22",
    to: "Euripides",
    certainty: "reported",
    note: "D.L.: 'They relate that Euripides gave him the treatise of Heraclitus...'",
  },
  {
    id: "socrates-whole-hide",
    philosopher: "Socrates",
    topic: "self-sufficiency",
    gloss: "Declining the building site Alcibiades offered: like accepting a whole hide when he only wanted shoes.",
    grc: "καὶ εἰ ὑποδημάτων ἔδει, καὶ βύρσαν μοι ἐδίδους, ἵνʼ ἐμαυτῷ ὑποδήματα ποιησαίμην, καταγέλαστος ἂν ἦν λαβών.",
    en: "Suppose, then, I wanted shoes and you offered me a whole hide to make a pair with, would it not be ridiculous in me to take it?",
    ref: "2.24",
    to: "Alcibiades",
    certainty: "reported",
    accordingTo: "Pamphila",
  },
  {
    id: "socrates-do-without",
    philosopher: "Socrates",
    topic: "self-sufficiency",
    gloss: "Before the market stalls, he reflected how many things he needed nothing of.",
    grc: "πόσων ἐγὼ χρείαν οὐκ ἔχω.",
    en: "How many things I can do without!",
    ref: "2.25",
    certainty: "asserted",
  },
  {
    id: "socrates-sheep-friends",
    philosopher: "Socrates",
    topic: "friendship",
    gloss: "Strange that a man can count his sheep precisely but cannot name his friends or say how many he has.",
    grc: "θαυμαστὸν πρόβατα μὲν ἕκαστον εἰπεῖν ἂν ῥᾳδίως ὅσα ἔχει, φίλους δʼ οὐκ ἂν ὀνομάσαι ὁπόσους κέκτηται· οὕτως ὀλιγώρως ἔχειν περὶ αὐτούς.",
    en: "it was strange that, if you asked a man how many sheep he had, he could easily tell you the precise number; whereas he could not name his friends or say how many he had, so slight was the value he set upon them",
    ref: "2.30",
    certainty: "asserted",
  },
  {
    id: "socrates-euclides-sophists",
    philosopher: "Socrates",
    topic: "speech",
    gloss: "Seeing Euclides keen on eristic arguments: he would get on with sophists, but with men not at all.",
    grc: "ὦ Εὐκλείδη, ἔφη, σοφισταῖς μὲν δυνήσῃ χρῆσθαι, ἀνθρώποις δὲ οὐδαμῶς.",
    en: "You will be able to get on with sophists, Euclides, but with men not at all.",
    ref: "2.30",
    to: "Euclides",
    certainty: "asserted",
  },
  {
    id: "socrates-one-good-knowledge",
    philosopher: "Socrates",
    topic: "wisdom",
    gloss: "There is only one good, knowledge, and one evil, ignorance.",
    grc: "ἓν μόνον ἀγαθὸν εἶναι, τὴν ἐπιστήμην, καὶ ἓν μόνον κακόν, τὴν ἀμαθίαν· πλοῦτον δὲ καὶ εὐγένειαν οὐδὲν σεμνὸν ἔχειν· πᾶν δὲ τοὐναντίον κακόν.",
    en: "There is, he said, only one good, that is, knowledge, and only one evil, that is, ignorance; wealth and good birth bring their possessor no dignity, but on the contrary evil.",
    ref: "2.31",
    certainty: "asserted",
  },
  {
    id: "socrates-thracian-mother",
    philosopher: "Socrates",
    topic: "wit",
    gloss: "Told that Antisthenes' mother was a Thracian: did you expect so noble a man to have been born of two Athenian parents?",
    grc: "σὺ δʼ ᾤου, ἔφη, οὕτως ἂν γενναῖον ἐκ δυοῖν Ἀθηναίων γενέσθαι;",
    en: "Nay, did you expect a man so noble to have been born of two Athenian parents?",
    ref: "2.31",
    certainty: "asserted",
  },
  {
    id: "socrates-know-nothing",
    philosopher: "Socrates",
    topic: "wisdom",
    gloss: "He knew nothing except the fact of his own ignorance.",
    grc: "εἰδέναι μὲν μηδὲν πλὴν αὐτὸ τοῦτο [εἰδέναι].",
    en: "he knew nothing except just the fact of his ignorance",
    ref: "2.32",
    certainty: "asserted",
  },
  {
    id: "socrates-nothing-to-excess",
    philosopher: "Socrates",
    topic: "virtue",
    gloss: "Asked what a young man's virtue was, he answered: doing nothing to excess.",
    grc: "ἐρωτηθείς, τίς ἀρετὴ νέου, τὸ μηδὲν ἄγαν, εἶπεν.",
    en: "being once asked in what consisted the virtue of a young man, he said, In doing nothing to excess",
    ref: "2.32",
    certainty: "asserted",
  },
  {
    id: "socrates-marry-or-not",
    philosopher: "Socrates",
    topic: "wit",
    gloss: "Asked whether to marry, he said you will regret it either way.",
    grc: "ἐρωτηθεὶς πότερον γῆμαι ἢ μή, ἔφη, ὃ ἂν αὐτῶν ποιήσῃς, μεταγνώσῃ.",
    en: "Some one asked him whether he should marry or not, and received the reply, Whichever you do you will repent it.",
    ref: "2.33",
    certainty: "asserted",
  },
  {
    id: "socrates-statues-vs-selves",
    philosopher: "Socrates",
    topic: "virtue",
    gloss: "Sculptors take pains that marble should resemble a man, but none that they themselves not turn out mere blocks.",
    grc: "θαυμάζειν τῶν τὰς λιθίνας εἰκόνας κατασκευαζομένων τοῦ μὲν λίθου προνοεῖν ὅπως ὁμοιότατος ἔσται, αὑτῶν δʼ ἀμελεῖν, ὡς μὴ ὁμοίους τῷ λίθῳ φαίνεσθαι.",
    en: "He used to express his astonishment that the sculptors of marble statues should take pains to make the block of marble into a perfect likeness of a man, and should take no pains about themselves lest they should turn out mere blocks, not men.",
    ref: "2.33",
    certainty: "asserted",
  },
  {
    id: "socrates-eat-to-live",
    philosopher: "Socrates",
    topic: "self-sufficiency",
    gloss: "Others live to eat; he ate to live.",
    grc: "τοὺς μὲν ἄλλους ἀνθρώπους ζῆν ἵνʼ ἐσθίοιεν· αὐτὸς δὲ ἐσθίειν ἵνα ζῴη.",
    en: "He would say that the rest of the world lived to eat, while he himself ate to live.",
    ref: "2.34",
    certainty: "asserted",
  },
  {
    id: "socrates-xanthippe-dinner",
    philosopher: "Socrates",
    topic: "self-sufficiency",
    gloss: "When Xanthippe was ashamed of the dinner set before rich guests: if they are reasonable they will put up with it.",
    grc: "θάρρει· εἰ μὲν γὰρ εἶεν μέτριοι, συμπεριενεχθεῖεν ἄν· εἰ δὲ φαῦλοι, ἡμῖν αὐτῶν οὐδὲν μελήσει.",
    en: "Never mind, said he, for if they are reasonable they will put up with it, and if they are good for nothing, we shall not trouble ourselves about them.",
    ref: "2.34",
    to: "Xanthippe",
    certainty: "asserted",
  },
  {
    id: "socrates-aeschines-gift",
    philosopher: "Socrates",
    topic: "friendship",
    gloss: "When the poor Aeschines offered him himself: do you not see that you are offering me the greatest gift of all?",
    grc: "ἆρʼ οὖν, εἶπεν, οὐκ αἰσθάνῃ τὰ μέγιστά μοι διδούς;",
    en: "Nay, do you not see that you are offering me the greatest gift of all?",
    ref: "2.34",
    to: "Aeschines",
    certainty: "asserted",
  },
  {
    id: "socrates-thirty-overlooked",
    philosopher: "Socrates",
    topic: "politics",
    gloss: "To one who complained of being overlooked when the Thirty rose to power: you are not sorry for that, are you?",
    grc: "ἆρα, ἔφη, μήτι σοι μεταμέλει;",
    en: "You are not sorry for that, are you?",
    ref: "2.34",
    certainty: "asserted",
  },
  {
    id: "socrates-condemned-by-nature",
    philosopher: "Socrates",
    topic: "death",
    gloss: "Told the Athenians had condemned him to death, he replied that nature had condemned them.",
    grc: "πρὸς τὸν εἰπόντα, θάνατόν σου κατέγνωσαν Ἀθηναῖοι, κἀκείνων, εἶπεν, ἡ φύσις.",
    en: "To one who said, You are condemned by the Athenians to die, he made answer, So are they, by nature.",
    ref: "2.35",
    certainty: "disputed",
    alsoAttributedTo: "Anaxagoras",
    note: "D.L.: 'But some ascribe this to Anaxagoras.'",
  },
  {
    id: "socrates-suffer-justly",
    philosopher: "Socrates",
    topic: "death",
    gloss: "When his wife protested that he was dying unjustly, he asked if she would prefer him to die justly.",
    grc: "τῆς γυναικὸς εἰπούσης, ἀδίκως ἀποθνήσκεις, σὺ δέ, ἔφη, δικαίως ἐβούλου;",
    en: "When his wife said, You suffer unjustly, he retorted, Why, would you have me suffer justly?",
    ref: "2.35",
    certainty: "asserted",
  },
  {
    id: "socrates-third-day",
    philosopher: "Socrates",
    topic: "death",
    gloss: "After dreaming of Homer's line on reaching Phthia, he told Aeschines he would die in three days.",
    grc: "πρὸς Αἰσχίνην ἔφη, εἰς τρίτην ἀποθανοῦμαι.",
    en: "he told Aeschines, On the third day I shall die.",
    ref: "2.35",
    to: "Aeschines",
    certainty: "asserted",
  },
  {
    id: "socrates-garment-to-die-in",
    philosopher: "Socrates",
    topic: "death",
    gloss: "Offered a beautiful garment to die in, he asked why his own was good enough to live in but not to die in.",
    grc: "τί δέ, ἔφη, τὸ ἐμὸν ἱμάτιον ἐμβιῶναι μὲν ἐπιτήδειον, ἐναποθανεῖν δὲ οὐχί;",
    en: "What, said he, is my own good enough to live in but not to die in?",
    ref: "2.35",
    to: "Apollodorus",
    certainty: "asserted",
  },
  {
    id: "socrates-never-learnt-to-speak-well",
    philosopher: "Socrates",
    topic: "speech",
    gloss: "Told that someone spoke ill of him: true, for he never learnt to speak well.",
    grc: "πρὸς τὸν εἰπόντα, κακῶς ὁ δεῖνά σε λέγει, καλῶς γάρ, ἔφη, λέγειν οὐκ ἔμαθε.",
    en: "When he was told that So-and-so spoke ill of him, he replied, True, for he has never learnt to speak well.",
    ref: "2.35",
    certainty: "asserted",
  },
  {
    id: "socrates-comic-poets",
    philosopher: "Socrates",
    topic: "wit",
    gloss: "We should not mind being mocked by comedians: just criticism improves us, unjust does not touch us.",
    grc: "ἔλεγε δὲ τοῖς κωμικοῖς δεῖν ἐπίτηδες ἑαυτὸν διδόναι· εἰ μὲν γάρ τι τῶν προσόντων λέξειαν, διορθώσονται· εἰ δʼ οὔ, οὐδὲν πρὸς ἡμᾶς.",
    en: "We ought not to object, he used to say, to be subjects for the Comic poets, for if they satirize our faults they will do us good, and if not they do not touch us.",
    ref: "2.36",
    certainty: "asserted",
  },
  {
    id: "socrates-vanity-through-cloak",
    philosopher: "Socrates",
    topic: "fame",
    gloss: "When Antisthenes turned his cloak to show the tear, Socrates saw his vanity through it.",
    grc: "ὁρῶ σου, ἔφη, διὰ τοῦ τρίβωνος τὴν κενοδοξίαν.",
    en: "I see, said he, your vanity through your cloak.",
    ref: "2.36",
    to: "Antisthenes",
    certainty: "asserted",
  },
  {
    id: "socrates-two-to-quarrel",
    philosopher: "Socrates",
    topic: "wit",
    gloss: "Asked if a certain man was not offensive: no, for it takes two to make a quarrel.",
    grc: "πρὸς τὸν εἰπόντα, οὐ σοὶ λοιδορεῖται ὁ δεῖνα; οὐχί, ἔφη· ἐμοὶ γὰρ οὐ πρόσεστι ταῦτα.",
    en: "To one who said, Don’t you find so-and-so very offensive? his reply was, No, for it takes two to make a quarrel.",
    ref: "2.36",
    certainty: "asserted",
  },
  {
    id: "socrates-thunder-and-rain",
    philosopher: "Socrates",
    topic: "wit",
    gloss: "When Xanthippe scolded and then drenched him: did I not say her thunder would end in rain?",
    grc: "οὐκ ἔλεγον, εἶπεν, ὅτι Ξανθίππη βροντῶσα καὶ ὕδωρ ποιήσει;",
    en: "Did I not say that Xanthippe’s thunder would end in rain?",
    ref: "2.36",
    certainty: "asserted",
  },
  {
    id: "socrates-windlass",
    philosopher: "Socrates",
    topic: "wit",
    gloss: "To Alcibiades on Xanthippe's scolding: he was as used to it as to the rattle of a windlass.",
    grc: "ἀλλʼ ἔγωγʼ, ἔφη, συνείθισμαι, καθαπερεὶ καὶ τροχιλίας ἀκούων συνεχές.",
    en: "Nay, I have got used to it, said he, as to the continued rattle of a windlass. And you do not mind the cackle of geese.",
    ref: "2.36",
    to: "Alcibiades",
    certainty: "asserted",
  },
  {
    id: "socrates-mother-of-my-children",
    philosopher: "Socrates",
    topic: "wit",
    gloss: "When Alcibiades said his geese at least gave him eggs: and Xanthippe is the mother of my children.",
    grc: "κἀμοί, φησί, Ξανθίππη παιδία γεννᾷ.",
    en: "And Xanthippe, said Socrates, is the mother of my children.",
    ref: "2.37",
    to: "Alcibiades",
    certainty: "asserted",
  },
  {
    id: "socrates-sparring-match",
    philosopher: "Socrates",
    topic: "wit",
    gloss: "Advised to hit back when Xanthippe tore off his coat in the market-place, he refused to make a public sparring match of it.",
    grc: "νὴ Δίʼ, εἶπεν, ἵνʼ ἡμῶν πυκτευόντων ἕκαστος ὑμῶν λέγῃ, εὖ Σώκρατες, εὖ Ξανθίππη.",
    en: "Yes, by Zeus, said he, in order that while we are sparring each of you may join in with Go it, Socrates! Well done, Xanthippe!",
    ref: "2.37",
    certainty: "asserted",
  },
  {
    id: "socrates-spirited-horses",
    philosopher: "Socrates",
    topic: "education",
    gloss: "He lived with a shrew as horsemen train on spirited horses: mastering Xanthippe, he could adapt to all mankind.",
    grc: "ἀλλʼ ὡς ἐκεῖνοι, φησί, τούτων κρατήσαντες ῥᾳδίως τῶν ἄλλων περιγίνονται, οὕτω κἀγὼ Ξανθίππῃ χρώμενος τοῖς ἄλλοις ἀνθρώποις συμπεριενεχθήσομαι.",
    en: "so I in the society of Xanthippe shall learn to adapt myself to the rest of the world.",
    ref: "2.37",
    certainty: "asserted",
  },
  {
    id: "socrates-lysias-speech",
    philosopher: "Socrates",
    topic: "speech",
    gloss: "He read the defence Lysias wrote for him and found it a fine speech, but not suitable to him.",
    grc: "καλὸς μὲν ὁ λόγος, ὦ Λυσία, οὐ μὴν ἁρμόττων γʼ ἐμοί.",
    en: "A fine speech, Lysias; it is not, however, suitable to me.",
    ref: "2.40",
    to: "Lysias",
    certainty: "asserted",
  },
  {
    id: "socrates-fine-raiment",
    philosopher: "Socrates",
    topic: "speech",
    gloss: "When Lysias asked how a fine speech could fail to suit him: just as fine raiment and fine shoes would not.",
    grc: "οὐ γὰρ καὶ ἱμάτια καλὰ καὶ ὑποδήματα εἴη ἂν ἐμοὶ ἀνάρμοστα;",
    en: "Well, he replied, would not fine raiment and fine shoes be just as unsuitable to me?",
    ref: "2.41",
    to: "Lysias",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Aristippus
  {
    id: "aristippus-partridge",
    philosopher: "Aristippus",
    topic: "wealth",
    gloss: "Censured for buying a partridge at fifty drachmae, he said the sum meant nothing to him.",
    grc: "σὺ δʼ οὐκ ἄν, εἶπεν, ὀβολοῦ τοῦτον ἐπρίω; ἐπινεύσαντος δέ, τοσοῦτον, ἔφη, ἐμοὶ δύνανται αἱ πεντήκοντα δραχμαί.",
    en: "Would not you have given an obol for it? and, being answered in the affirmative, rejoined, Fifty drachmae are no more to me.",
    ref: "2.66",
    certainty: "asserted",
  },
  {
    id: "aristippus-at-ease-anywhere",
    philosopher: "Aristippus",
    topic: "self-sufficiency",
    gloss: "What he gained from philosophy: the ability to be at ease in any company.",
    grc: "ἐρωτηθεὶς τί αὐτῷ περιγέγονεν ἐκ φιλοσοφίας, ἔφη, τὸ δύνασθαι πᾶσι θαρρούντως ὁμιλεῖν.",
    en: "Being asked what he had gained from philosophy, he replied, The ability to feel at ease in any society.",
    ref: "2.68",
    certainty: "asserted",
  },
  {
    id: "aristippus-lais",
    philosopher: "Aristippus",
    topic: "pleasure",
    gloss: "He possessed Lais without being possessed: mastery of pleasures, not abstinence, is best.",
    grc: "ἔχω [Λαΐδα], ἀλλʼ οὐκ ἔχομαι· ἐπεὶ τὸ κρατεῖν καὶ μὴ ἡττᾶσθαι ἡδονῶν ἄριστον, οὐ τὸ μὴ χρῆσθαι.",
    en: "I have Lais, not she me; and it is not abstinence from pleasures that is best, but mastery over them without ever being worsted.",
    ref: "2.75",
    certainty: "asserted",
  },
  {
    id: "aristippus-throw-off-load",
    philosopher: "Aristippus",
    topic: "wealth",
    gloss: "When his slave staggered under the money, he told him to pour away all he could not carry.",
    grc: "ἀπόχεε, ἔφη, τὸ πλέον καὶ ὅσον δύνασαι βάσταζε.",
    en: "Pour away the greater part, and carry no more than you can manage.",
    ref: "2.77",
    certainty: "reported",
    accordingTo: "Bion",
  },
  {
    id: "aristippus-earthenware-standard",
    philosopher: "Aristippus",
    topic: "wisdom",
    gloss: "Men test pottery by its ring but have no standard by which to test a life.",
    grc: "τὰ σκεύη μὲν ἐν ταῖς ἀγορασίαις κομπούντων, τοὺς δὲ βίους εἰκῆ δοκιμαζόντων",
    en: "in purchasing earthenware they made trial whether it rang true, but had no regular standard by which to judge life",
    ref: "2.78",
    certainty: "disputed",
    alsoAttributedTo: "Diogenes of Sinope",
    note: "D.L.: 'Others attribute this remark to Diogenes.'",
  },
  {
    id: "aristippus-paris-three-courtesans",
    philosopher: "Aristippus",
    topic: "pleasure",
    gloss: "Told by Dionysius to choose one of three courtesans, he carried off all three: Paris paid dearly for preferring one.",
    grc: "οὐδὲ τῷ Πάριδι συνήνεγκε μίαν προκρῖναι",
    en: "Paris paid dearly for giving the preference to one out of three.",
    ref: "2.67",
    certainty: "asserted",
    note: "D.L. adds ('φασίν') that he let all three go at the porch.",
  },
  {
    id: "aristippus-gudgeon-and-blenny",
    philosopher: "Aristippus",
    topic: "wit",
    gloss: "Reproached for bearing Dionysius' spittle: fishermen endure sea-water for a gudgeon; should I not endure negus to take a blenny?",
    grc: "εἶτα οἱ μὲν ἁλιεῖς, εἶπεν, ὑπομένουσι ῥαίνεσθαι τῇ θαλάττῃ, ἵνα κωβιὸν θηράσωσιν· ἐγὼ δὲ μὴ ἀνάσχωμαι κράματι ῥανθῆναι, ἵνα βλέννοι λάβω;",
    en: "If the fishermen let themselves be drenched with sea-water in order to catch a gudgeon, ought I not to endure to be wetted with negus in order to take a blenny?",
    ref: "2.67",
    certainty: "asserted",
  },
  {
    id: "aristippus-washing-vegetables",
    philosopher: "Aristippus",
    topic: "wit",
    gloss: "To Diogenes, who jeered that a diet of vegetables would free him from courting kings: if you knew how to associate with men, you would not be washing vegetables.",
    grc: "καὶ σύ, εἶπεν, εἴπερ ᾔδεις ἀνθρώποις ὁμιλεῖν, οὐκ ἂν λάχανα ἔπλυνες.",
    en: "And if you knew how to associate with men, you would not be washing vegetables.",
    ref: "2.68",
    to: "Diogenes of Sinope",
    certainty: "asserted",
  },
  {
    id: "aristippus-at-festivals-of-gods",
    philosopher: "Aristippus",
    topic: "pleasure",
    gloss: "Reproached for extravagance: if it were wrong, it would not be in vogue at the festivals of the gods.",
    grc: "εἰ τοῦτʼ, ἔφη, φαῦλον ἦν, οὐκ ἂν ἐν ταῖς τῶν θεῶν ἑορταῖς ἐγίνετο.",
    en: "If it were wrong to be extravagant, it would not be in vogue at the festivals of the gods.",
    ref: "2.68",
    certainty: "asserted",
  },
  {
    id: "aristippus-laws-repealed",
    philosopher: "Aristippus",
    topic: "virtue",
    gloss: "Asked what advantage philosophers have: should all laws be repealed, we shall go on living as we do now.",
    grc: "ἐὰν πάντες οἱ νόμοι ἀναιρεθῶσιν, ὁμοίως βιωσόμεθα.",
    en: "Should all laws be repealed, we shall go on living as we do now.",
    ref: "2.68",
    certainty: "asserted",
  },
  {
    id: "aristippus-who-knows-their-needs",
    philosopher: "Aristippus",
    topic: "wisdom",
    gloss: "Why philosophers go to rich men's houses and not the reverse: the one know what they need, the other do not.",
    grc: "ὅτι οἱ μὲν ἴσασιν ὧν δέονται, οἱ δʼ οὐκ ἴσασιν.",
    en: "the one know what they need while the other do not",
    ref: "2.69",
    to: "Dionysius",
    certainty: "asserted",
  },
  {
    id: "aristippus-dionysius-more-extravagant",
    philosopher: "Aristippus",
    topic: "pleasure",
    gloss: "Reproached by Plato for extravagance - is Dionysius a good man? Yet he lives more extravagantly: nothing hinders living extravagantly and well.",
    grc: "καὶ μήν, ἔφη, ζῇ ἐμοῦ πολυτελέστερον· ὥστʼ οὐδὲν κωλύει καὶ πολυτελῶς καὶ καλῶς ζῆν.",
    en: "And yet, said he, he lives more extravagantly than I do. So that there is nothing to hinder a man living extravagantly and well.",
    ref: "2.69",
    to: "Plato",
    certainty: "asserted",
  },
  {
    id: "aristippus-trained-horses",
    philosopher: "Aristippus",
    topic: "education",
    gloss: "How the educated differ from the uneducated: as trained horses differ from untrained.",
    grc: "ᾧπερ οἱ δεδαμασμένοι ἵπποι τῶν ἀδαμάστων.",
    en: "Exactly as horses that have been trained differ from untrained horses.",
    ref: "2.69",
    certainty: "asserted",
  },
  {
    id: "aristippus-unable-to-go-out",
    philosopher: "Aristippus",
    topic: "pleasure",
    gloss: "When a lad blushed on entering a courtesan's house with him: it is not going in that is dangerous, but being unable to go out.",
    grc: "οὐ τὸ εἰσελθεῖν, ἔφη, χαλεπόν, ἀλλὰ τὸ μὴ δύνασθαι ἐξελθεῖν.",
    en: "It is not going in that is dangerous, but being unable to go out.",
    ref: "2.69",
    certainty: "asserted",
  },
  {
    id: "aristippus-riddle-knot",
    philosopher: "Aristippus",
    topic: "wit",
    gloss: "Asked to untie a knotty problem: why untie it, you simpleton, when it causes trouble enough tied?",
    grc: "τί, ὦ μάταιε, ἔφη, λῦσαι θέλεις, ὃ καὶ δεδεμένον ἡμῖν πράγματα παρέχει;",
    en: "Why, you simpleton, said he, do you want it untied, seeing that it causes trouble enough as it is?",
    ref: "2.70",
    certainty: "asserted",
  },
  {
    id: "aristippus-beggar-vs-uneducated",
    philosopher: "Aristippus",
    topic: "education",
    gloss: "Better a beggar than uneducated: the one needs money, the other needs to be humanized.",
    grc: "ἄμεινον ἔφη ἐπαίτην ἢ ἀπαίδευτον εἶναι· οἱ μὲν γὰρ χρημάτων, οἱ δʼ ἀνθρωπισμοῦ δέονται.",
    en: "It is better, he said, to be a beggar than to be uneducated; the one needs money, the others need to be humanized.",
    ref: "2.70",
    certainty: "asserted",
  },
  {
    id: "aristippus-privilege-not-to-listen",
    philosopher: "Aristippus",
    topic: "speech",
    gloss: "Pursued by a reviler asking why he ran away: yours is the privilege of foul language, mine of not listening.",
    grc: "ὅτι, φησί, τοῦ μὲν κακῶς λέγειν σὺ τὴν ἐξουσίαν ἔχεις, τοῦ δὲ μὴ ἀκούειν ἐγώ.",
    en: "Because, said he, as it is your privilege to use foul language, so it is my privilege not to listen.",
    ref: "2.70",
    certainty: "asserted",
  },
  {
    id: "aristippus-physicians-at-sick-doors",
    philosopher: "Aristippus",
    topic: "wisdom",
    gloss: "Philosophers at rich men's doors are like physicians attending the sick - no one would rather be sick than a physician.",
    grc: "καὶ γὰρ καὶ οἱ ἰατροί. φησί, παρὰ ταῖς τῶν νοσούντων· ἀλλʼ οὐ παρὰ τοῦτό τις ἂν ἕλοιτο νοσεῖν ἢ ἰατρεύειν.",
    en: "So, too, physicians are in attendance on those who are sick, but no one for that reason would prefer being sick to being a physician.",
    ref: "2.70",
    certainty: "asserted",
  },
  {
    id: "aristippus-not-same-souls",
    philosopher: "Aristippus",
    topic: "death",
    gloss: "Mocked for fearing a storm at sea while plain men stayed calm: the lives at stake are not comparable.",
    grc: "οὐ γὰρ περὶ ὁμοίας, ἔφη, ψυχῆς ἀγωνιῶμεν ἑκάτεροι.",
    en: "The lives at stake in the two cases are not comparable.",
    ref: "2.71",
    certainty: "asserted",
  },
  {
    id: "aristippus-useful-reading",
    philosopher: "Aristippus",
    topic: "education",
    gloss: "To one who boasted of wide learning: not wide reading but useful reading tends to excellence.",
    grc: "οὕτως οὐδὲ οἱ πολλὰ ἀλλʼ οἱ χρήσιμα ἀναγινώσκοντές εἰσι σπουδαῖοι.",
    en: "so too it is not wide reading but useful reading that tends to excellence",
    ref: "2.71",
    certainty: "asserted",
  },
  {
    id: "aristippus-advocate-true-words",
    philosopher: "Aristippus",
    topic: "wit",
    gloss: "Asked by the advocate who won his case what good Socrates had done him: this much - that what you said of me was true.",
    grc: "ἔφη, τοῦτο, τοὺς λόγους, οὓς εἶπας ὑπὲρ ἐμοῦ, ἀληθεῖς εἶναι.",
    en: "Thus much, was the reply, that what you said of me in your speech was true.",
    ref: "2.71",
    certainty: "asserted",
  },
  {
    id: "aristippus-stone-upon-stone",
    philosopher: "Aristippus",
    topic: "education",
    gloss: "How his son would profit from education: at least in the theatre he will not sit like a stone upon stone.",
    grc: "ἐν γοῦν τῷ θεάτρῳ οὐ καθεδεῖται λίθος ἐπὶ λίθῳ",
    en: "If nothing more than this, at all events, when in the theatre he will not sit down like a stone upon stone.",
    ref: "2.72",
    certainty: "asserted",
  },
  {
    id: "aristippus-buy-and-have-two",
    philosopher: "Aristippus",
    topic: "education",
    gloss: "To the father who balked at a fee of 500 drachmae, saying he could buy a slave for that: then do so, and you will have two.",
    grc: "πρίω, ἔφη, καὶ ἕξεις δύο.",
    en: "Then do so, was the reply, and you will have two.",
    ref: "2.72",
    certainty: "asserted",
  },
  {
    id: "aristippus-hire-a-cook",
    philosopher: "Aristippus",
    topic: "wit",
    gloss: "Reproached for employing a rhetorician to conduct his case: when I give a dinner, I hire a cook.",
    grc: "καὶ γάρ, ἔφη, ὅταν δεῖπνον ἔχω, μάγειρον μισθοῦμαι.",
    en: "Well, if I give a dinner, I hire a cook.",
    ref: "2.72",
    certainty: "asserted",
  },
  {
    id: "aristippus-what-to-say-when",
    philosopher: "Aristippus",
    topic: "speech",
    gloss: "Compelled by Dionysius to enunciate philosophy: ludicrous that you learn from me what to say, yet instruct me when to say it.",
    grc: "γελοῖον, ἔφη, εἰ τὸ λέγειν μὲν παρʼ ἐμοῦ μανθάνεις, τὸ δὲ πότε δεῖ λέγειν σύ με διδάσκεις.",
    en: "It would be ludicrous, he said, that you should learn from me what to say, and yet instruct me when to say it.",
    ref: "2.73",
    to: "Dionysius",
    certainty: "asserted",
  },
  {
    id: "aristippus-last-place-distinction",
    philosopher: "Aristippus",
    topic: "wit",
    gloss: "Demoted by the offended Dionysius to the end of the table: you must have wished to confer distinction on the last place.",
    grc: "ἐνδοξότερον, φάναι, τὸν τόπον ἠθέλησας ποιῆσαι.",
    en: "You must have wished to confer distinction on the last place.",
    ref: "2.73",
    to: "Dionysius",
    certainty: "reported",
    note: "D.L.: 'At this, they say, Dionysius was offended...'",
  },
  {
    id: "aristippus-dolphin",
    philosopher: "Aristippus",
    topic: "wit",
    gloss: "To one who boasted of his diving: are you not ashamed to brag of what a dolphin can do?",
    grc: "οὐκ αἰσχύνῃ, εἶπεν, ἐπὶ δελφῖνος ἔργοις ἀλαζονευόμενος;",
    en: "Are you not ashamed, said he, to brag of that which a dolphin can do?",
    ref: "2.73",
    certainty: "asserted",
  },
  {
    id: "aristippus-strip-them-both",
    philosopher: "Aristippus",
    topic: "wisdom",
    gloss: "The difference between the wise man and the unwise: strip them both and send them among strangers, and you will know.",
    grc: "εἰς ἀγνῶτας τοὺς δύο γυμνοὺς ἀπόστειλον, καὶ εἴσῃ.",
    en: "Strip them both, said he, and send them among strangers and you will know.",
    ref: "2.73",
    certainty: "asserted",
  },
  {
    id: "aristippus-so-can-a-mule",
    philosopher: "Aristippus",
    topic: "wit",
    gloss: "To one who boasted he could drink a great deal without getting drunk: so can a mule.",
    grc: "τοῦτο καὶ ἡμίονος, φησί.",
    en: "And so can a mule.",
    ref: "2.73",
    certainty: "asserted",
  },
  {
    id: "aristippus-house-and-ship",
    philosopher: "Aristippus",
    topic: "pleasure",
    gloss: "Against the reproach of living with a courtesan - a house or ship is no worse for previous occupants: it makes no difference whether she has lived with many or with nobody.",
    grc: "οὐδʼ ἄρα γυναικί, ἔφη, συνεῖναι ᾗ πολλοὶ κέχρηνται ἢ μηδείς.",
    en: "Then it makes no difference, said he, whether the woman you live with has lived with many or with nobody.",
    ref: "2.74",
    certainty: "asserted",
  },
  {
    id: "aristippus-fees-like-socrates",
    philosopher: "Aristippus",
    topic: "wealth",
    gloss: "Accused of taking fees though a pupil of Socrates: Socrates too accepted corn and wine - but he had the foremost Athenians for stewards, I only my slave Eutychides.",
    grc: "καὶ μάλα, εἶπε· καὶ γὰρ Σωκράτης, πεμπόντων αὐτῷ τινων καὶ σῖτον καὶ οἶνον, ὀλίγα λαμβάνων τὰ λοιπὰ ἀπέπεμπεν· εἶχε γὰρ ταμίας τοὺς πρώτους Ἀθηναίων, ἐγὼ δʼ Εὐτυχίδην ἀργυρώνητον.",
    en: "Most certainly I do, for Socrates, too, when certain people sent him corn and wine, used to take a little and return all the rest; and he had the foremost men in Athens for his stewards, whereas mine is my slave Eutychides.",
    ref: "2.74",
    certainty: "asserted",
  },
  {
    id: "aristippus-you-love-money",
    philosopher: "Aristippus",
    topic: "pleasure",
    gloss: "Wouldn't you have bought this for three obols? Then I am no longer a lover of pleasure - you are a lover of money.",
    grc: "οὐκέτι τοίνυν, ἔφη, φιλήδονος ἐγώ, ἀλλὰ σὺ φιλάργυρος.",
    en: "Very well, then, said Aristippus, I am no longer a lover of pleasure, it is you who are a lover of money.",
    ref: "2.75",
    certainty: "asserted",
  },
  {
    id: "aristippus-no-fitter-place",
    philosopher: "Aristippus",
    topic: "wit",
    gloss: "Having spat in the face of Simus, who showed off costly tesselated pavements: I could not find any place more suitable.",
    grc: "οὐκ εἶχον, εἶπε, τόπον ἐπιτηδειότερον.",
    en: "I could not find any place more suitable.",
    ref: "2.75",
    certainty: "asserted",
  },
  {
    id: "aristippus-die-like-socrates",
    philosopher: "Aristippus",
    topic: "death",
    gloss: "Asked how Socrates died: as I would wish to die myself.",
    grc: "ὡς ἂν ἐγὼ εὐξαίμην.",
    en: "As I would wish to die myself.",
    ref: "2.76",
    certainty: "asserted",
  },
  {
    id: "aristippus-blame-the-cost",
    philosopher: "Aristippus",
    topic: "pleasure",
    gloss: "Polyxenus reproached his ladies and expensive fare, then accepted a dinner invitation: you appear to blame the cost, not the entertainment.",
    grc: "τί οὖν, ἔφη, ἐμέμφου; ἔοικας γὰρ οὐ τὴν ὀψωνίαν ἀλλὰ τὸ ἀνάλωμα αἰτιᾶσθαι.",
    en: "Why, then, did you find fault? For you appear to blame the cost and not the entertainment.",
    ref: "2.77",
    certainty: "asserted",
  },
  {
    id: "aristippus-money-or-aristippus",
    philosopher: "Aristippus",
    topic: "wealth",
    gloss: "Having dropped his gold into the sea when pirates seized the ship: better the money perish on account of Aristippus than Aristippus on account of the money.",
    grc: "ἄμεινον ταῦτα διʼ Ἀρίστιππον ἢ διὰ ταῦτα Ἀρίστιππον ἀπολέσθαι.",
    en: "it was better for the money to perish on account of Aristippus than for Aristippus to perish on account of the money",
    ref: "2.77",
    certainty: "reported",
    note: "D.L.: 'Another version of the story attributes to him the further remark...'",
  },
  {
    id: "aristippus-impart-and-obtain",
    philosopher: "Aristippus",
    topic: "wisdom",
    gloss: "Asked by Dionysius what he had come for: to impart what he had and obtain what he had not.",
    grc: "ἔφη ἐπὶ τῷ μεταδώσειν ὧν ἔχοι, καὶ μεταλήψεσθαι ὧν μὴ ἔχοι.",
    en: "it was to impart what he had and obtain what he had not",
    ref: "2.77",
    to: "Dionysius",
    certainty: "asserted",
  },
  {
    id: "aristippus-wisdom-socrates-money-you",
    philosopher: "Aristippus",
    topic: "wealth",
    gloss: "Why he had come to Dionysius: when I needed wisdom I went to Socrates; now that I need money I come to you.",
    grc: "ὁπότε μὲν σοφίας ἐδεόμην, ἧκον παρὰ τὸν Σωκράτην· νῦν δὲ χρημάτων δεόμενος παρὰ σὲ ἥκω.",
    en: "When I needed wisdom, I went to Socrates; now that I am in need of money, I come to you.",
    ref: "2.78",
    to: "Dionysius",
    certainty: "reported",
    note: "D.L.: 'But some make his answer to have been...' - a rival version of the reply at 2.77.",
  },
  {
    id: "aristippus-ears-in-his-feet",
    philosopher: "Aristippus",
    topic: "wit",
    gloss: "Jeered at for falling at Dionysius' feet when begging a favour for a friend: the fault lies with Dionysius, who has his ears in his feet.",
    grc: "οὐκ ἐγώ, φησίν, αἴτιος, ἀλλὰ Διονύσιος ὁ ἐν τοῖς ποσὶ τὰς ἀκοὰς ἔχων.",
    en: "It is not I who am to blame, but Dionysius who has his ears in his feet.",
    ref: "2.79",
    certainty: "asserted",
  },
  {
    id: "aristippus-converse-with-artaphernes",
    philosopher: "Aristippus",
    topic: "fortune",
    gloss: "Taken prisoner by the satrap Artaphernes and asked if he could be cheerful: when should I be more cheerful than now, about to converse with Artaphernes?",
    grc: "πότε γάρ, εἶπεν, ὦ μάταιε, θαρρήσαιμι ἀν μᾶλλον ἢ νῦν, ὅτε μέλλω Ἀρταφέρνῃ διαλέξεσθαι;",
    en: "for when should I be more cheerful than now that I am about to converse with Artaphernes?",
    ref: "2.79",
    certainty: "asserted",
  },
  {
    id: "aristippus-suitors-of-penelope",
    philosopher: "Aristippus",
    topic: "education",
    gloss: "Those educated in everything but philosophy are like Penelope's suitors: they win the handmaidens but not the mistress.",
    grc: "τοὺς τῶν ἐγκυκλίων παιδευμάτων μετασχόντας, φιλοσοφίας δὲ ἀπολειφθέντας ὁμοίους ἔλεγεν εἶναι τοῖς τῆς Πηνελόπης μνηστῆρσι",
    en: "Those who went through the ordinary curriculum, but in their studies stopped short at philosophy, he used to compare to the suitors of Penelope.",
    ref: "2.79",
    certainty: "asserted",
    note: "D.L. adds at 2.80 that 'a similar remark is ascribed to Ariston' (Odysseus in the under-world never saw the queen herself).",
  },
  {
    id: "aristippus-useful-when-grown",
    philosopher: "Aristippus",
    topic: "education",
    gloss: "What handsome boys ought to learn: the things that will be useful to them when they are grown up.",
    grc: "οἷς ἄνδρες γενόμενοι χρήσονται.",
    en: "Those which will be useful to them when they are grown up.",
    ref: "2.80",
    certainty: "asserted",
  },
  {
    id: "aristippus-education-and-recreation",
    philosopher: "Aristippus",
    topic: "wit",
    gloss: "Censured for leaving Socrates for Dionysius: I came to Socrates for education, to Dionysius for recreation.",
    grc: "ἀλλὰ πρὸς Σωκράτην μέν, εἶπεν, ἦλθον παιδείας ἕνεκεν, πρὸς δὲ Διονύσιον παιδιᾶς.",
    en: "Yes, but I came to Socrates for education and to Dionysius for recreation.",
    ref: "2.80",
    certainty: "asserted",
  },
  {
    id: "aristippus-where-you-got-so-little",
    philosopher: "Aristippus",
    topic: "wealth",
    gloss: "Asked by Socrates where he got so much money from teaching: where you got so little.",
    grc: "ὅθεν σοι τὰ ὀλίγα.",
    en: "Where you got so little.",
    ref: "2.80",
    to: "Socrates",
    certainty: "asserted",
  },
  {
    id: "aristippus-coarse-rushes",
    philosopher: "Aristippus",
    topic: "wit",
    gloss: "To a courtesan claiming to be with child by him: you are no more sure than if you had run through coarse rushes and named the one that pricked you.",
    grc: "οὐ μᾶλλον, ἔφη, γινώσκεις ἢ εἰ διʼ ὁλοσχοίνων ἰοῦσα ἔφασκες ὑπὸ τοῦδε κεκεντῆσθαι.",
    en: "You are no more sure of this than if, after running through coarse rushes, you were to say you had been pricked by one in particular.",
    ref: "2.81",
    certainty: "asserted",
  },
  {
    id: "aristippus-phlegm-and-vermin",
    philosopher: "Aristippus",
    topic: "wit",
    gloss: "Accused of exposing his son as if not his own: phlegm and vermin too are of our own begetting, yet being useless we cast them as far away as possible.",
    grc: "καὶ τὸ φλέγμα, φησί, καὶ τοὺς φθεῖρας ἐξ ἡμῶν ἴσμεν γεννωμένους, ἀλλʼ ἀχρεῖα ὄντα ὡς πορρωτάτω ῥιπτοῦμεν.",
    en: "Phlegm, too, and vermin we know to be of our own begetting, but for all that, because they are useless, we cast them as far from us as possible.",
    ref: "2.81",
    certainty: "asserted",
  },
  {
    id: "aristippus-money-plato-books",
    philosopher: "Aristippus",
    topic: "wealth",
    gloss: "Twitted for taking money from Dionysius while Plato carried off a book: I want money, Plato wants books.",
    grc: "ἐγω μὲν γάρ, εἶπεν, ἀργυρίων, Πλάτων δὲ βιβλίων ἐστὶν ἐνδεής.",
    en: "Well, I want money, Plato wants books.",
    ref: "2.81",
    certainty: "asserted",
  },
  {
    id: "aristippus-why-refuted",
    philosopher: "Aristippus",
    topic: "wit",
    gloss: "Asked why he let himself be refuted by Dionysius: for the same reason as the others refute him.",
    grc: "οὗ ἕνεκα, φησίν, οἱ ἄλλοι ἐλέγχουσιν.",
    en: "For the same reason, said he, as the others refute him.",
    ref: "2.81",
    certainty: "asserted",
  },
  {
    id: "aristippus-pay-then-discuss",
    philosopher: "Aristippus",
    topic: "wealth",
    gloss: "Dionysius countered his request for money with 'the wise man is never in want': pay first, then let us discuss - you see that I was not found wanting.",
    grc: "δός, εἶπε, καὶ περὶ τούτου ζητῶμεν. δόντος δέ, ὁρᾷς, ἔφη, ὅτι οὐκ ἠπόρηκα;",
    en: "Pay! Pay! and then let us discuss the question; and when he was paid, Now you see, do you not, said he, that I was not found wanting?",
    ref: "2.82",
    to: "Dionysius",
    certainty: "asserted",
  },
  {
    id: "aristippus-no-slave-if-free",
    philosopher: "Aristippus",
    topic: "politics",
    gloss: "Correcting the verse Dionysius quoted at him ('whoso goes to a prince's court becomes his slave'): no slave is he, if a free man he come.",
    grc: "οὐκ ἔστι δοῦλος, ἂν ἐλεύθερος μόλῃ.",
    en: "If a free man he come, no slave is he.",
    ref: "2.82",
    to: "Dionysius",
    certainty: "disputed",
    alsoAttributedTo: "Plato",
    accordingTo: "Diocles",
    note: "D.L.: 'This is stated by Diocles in his work On the Lives of Philosophers; other writers refer the anecdotes to Plato.'",
  },
  {
    id: "aristippus-reconcile-over-wine",
    philosopher: "Aristippus",
    topic: "friendship",
    gloss: "After a quarrel with Aeschines: shall we not make it up, or will you wait for someone to reconcile us over the wine-bowl?",
    grc: "οὐ διαλλαχθησόμεθα, οὐ παυσόμεθα, εἶπε, ληροῦντες, ἀλλʼ ἀναμενεῖς ἕως ἂν ἐπὶ τῆς κύλικος ἡμᾶς διαλλάξῃ τις;",
    en: "Are we not to make it up and desist from vapouring, or will you wait for some one to reconcile us over the wine-bowl?",
    ref: "2.82",
    to: "Aeschines",
    certainty: "asserted",
  },
  {
    id: "aristippus-first-approaches",
    philosopher: "Aristippus",
    topic: "friendship",
    gloss: "Sealing the reconciliation with Aeschines: remember that, though I am your senior, I made the first approaches.",
    grc: "μνημόνευε τοίνυν, εἶπεν ὁ Ἀρίστιππος, ὅτι σοι πρότερος πρεσβύτερος ὢν προσῆλθον.",
    en: "Then remember, Aristippus went on, that, though I am your senior, I made the first approaches.",
    ref: "2.83",
    to: "Aeschines",
    certainty: "asserted",
  },
  {
    id: "stilpo-jackdaw",
    philosopher: "Stilpo",
    topic: "wit",
    gloss: "Having trapped Theodorus into conceding 'you are god' by his own logic: but, you rascal, at this rate you would allow yourself to be a jackdaw and ten thousand other things.",
    grc: "ἀλλʼ, ὦ μόχθηρε, τῷ λόγῳ τούτῳ καὶ κολοιὸς ἂν ὁμολογήσειας εἶναι καὶ ἄλλα μυρία.",
    en: "But, you rascal, at this rate you would allow yourself to be a jackdaw and ten thousand other things.",
    ref: "2.100",
    to: "Theodorus",
    certainty: "asserted",
    crossAttributed: true,
    note: "Spoken by Stilpo in the life of Aristippus (the Theodorus excursus).",
  },
  {
    id: "aeschines-you-begin-friendship",
    philosopher: "Aeschines",
    topic: "friendship",
    gloss: "Accepting Aristippus' reconciliation: you are a much better man than I - the quarrel was of my beginning, the friendship of yours.",
    grc: "εὖγε, νὴ τὴν Ἥραν, εὐλόγως εἶπας, ἐπεὶ πολλῷ μου βελτίων ὑπάρχεις· ἐγὼ μὲν γὰρ ἔχθρας, σὺ δὲ φιλίας ἄρχεις.",
    en: "Well done, by Hera, you are quite right; you are a much better man than I am. For the quarrel was of my beginning, you make the first move to friendship.",
    ref: "2.83",
    to: "Aristippus",
    certainty: "asserted",
    crossAttributed: true,
    note: "Spoken by Aeschines in the life of Aristippus.",
  },
  {
    id: "socrates-prytaneum",
    philosopher: "Socrates",
    topic: "politics",
    gloss: "Asked to propose his own penalty at his trial: considering his services, maintenance in the Prytaneum at the public expense.",
    grc: "ἕνεκα μέν, εἶπε, τῶν ἐμοὶ διαπεπραγμένων τιμῶμαι τὴν δίκην τῆς ἐν πρυτανείῳ σιτήσεως.",
    en: "Considering my services, I assess the penalty at maintenance in the Prytaneum at the public expense.",
    ref: "2.42",
    certainty: "asserted",
  },
  {
    id: "socrates-follow-me-and-learn",
    philosopher: "Socrates",
    topic: "education",
    gloss: "Barring young Xenophon's way with his stick, he asked where men become good and honourable - then: follow me, and learn.",
    grc: "ἕπου τοίνυν, φάναι, καὶ μάνθανε.",
    en: "Then follow me, said Socrates, and learn.",
    ref: "2.48",
    to: "Xenophon",
    certainty: "reported",
    crossAttributed: true,
    note: "Spoken by Socrates in the life of Xenophon; D.L.: 'The story goes that Socrates met him in a narrow passage...'",
  },
  {
    id: "xenophon-mortal-son",
    philosopher: "Xenophon",
    topic: "death",
    gloss: "Told mid-sacrifice that his son Gryllus had fallen at Mantinea: he knew his son was mortal.",
    grc: "ᾔδειν θνητὸν γεγεννηκώς.",
    en: "I knew my son was mortal.",
    ref: "2.55",
    certainty: "reported",
    note: "D.L.: 'Some say that he did not even shed tears, but exclaimed...' - the same consolation is told of Anaxagoras at 2.13.",
  },
  {
    id: "socrates-sausage-makers-son",
    philosopher: "Socrates",
    topic: "friendship",
    gloss: "On the tireless Aeschines, who never left his side: only the sausage-maker's son knows how to honour me.",
    grc: "μόνος ἡμᾶς οἶδε τιμᾶν ὁ τοῦ ἀλλαντοποιοῦ.",
    en: "Only the sausage-maker’s son knows how to honour me.",
    ref: "2.60",
    certainty: "asserted",
    crossAttributed: true,
    note: "Spoken by Socrates in the life of Aeschines.",
  },
  {
    id: "socrates-borrow-from-yourself",
    philosopher: "Socrates",
    topic: "self-sufficiency",
    gloss: "Seeing Aeschines pinched by poverty: borrow from yourself by reducing your rations.",
    grc: "παρʼ ἑαυτοῦ δανείζεσθαι τῶν σιτίων ὑφαιροῦντα.",
    en: "Socrates, seeing how he was pinched by poverty, advised him to borrow from himself by reducing his rations.",
    ref: "2.62",
    to: "Aeschines",
    certainty: "reported",
    crossAttributed: true,
    note: "Spoken by Socrates in the life of Aeschines; D.L.: 'They say...'",
  },
  {
    id: "aristippus-you-thief",
    philosopher: "Aristippus",
    topic: "wit",
    gloss: "As Aeschines read a dialogue of doubtful authorship at Megara: where did you get that, you thief?",
    grc: "πόθεν σοι, λῃστά, ταῦτα;",
    en: "Where did you get that, you thief?",
    ref: "2.62",
    to: "Aeschines",
    certainty: "reported",
    crossAttributed: true,
    note: "Spoken by Aristippus in the life of Aeschines; D.L.: 'φασι σκῶψαι' - Aristippus suspected the dialogues were really Socrates' own.",
  },
  // -------------------------------------------------------------------- Stilpo
  {
    id: "stilpo-no-honour-to-her",
    philosopher: "Stilpo",
    topic: "fame",
    gloss: "Told his profligate daughter was a disgrace to him: no more than he was an honour to her.",
    grc: "οὐ μᾶλλον, εἶπεν, ἢ ἐγὼ ταύτην κοσμῶ.",
    en: "Not so, any more than I am an honour to her.",
    ref: "2.114",
    certainty: "asserted",
  },
  {
    id: "stilpo-lost-nothing",
    philosopher: "Stilpo",
    topic: "self-sufficiency",
    gloss: "After the sack of Megara he denied losing anything of his own: no one had carried off his learning.",
    grc: "ἔφη μηδὲν τῶν οἰκείων ἀπολωλεκέναι· παιδείαν γὰρ μηδένα ἐξενηνοχέναι, τόν τε λόγον ἔχειν καὶ τὴν ἐπιστήμην.",
    en: "Stilpo denied that he had lost anything which really belonged to him, for no one had taken away his learning, while he still had his eloquence and knowledge.",
    ref: "2.115",
    certainty: "asserted",
  },
  {
    id: "stilpo-athena-not-a-god",
    philosopher: "Stilpo",
    topic: "religion",
    gloss: "His argument on Phidias' Athena: she is by Phidias, not by Zeus, therefore not a god - which brought him before the Areopagus.",
    grc: "ἆρά γε ἡ τοῦ Διὸς Ἀθηνᾶ θεός ἐστι; φήσαντος δέ, ναί, αὕτη δέ γε, εἶπεν, οὐκ ἔστι Διός, ἀλλὰ Φειδίου· συγχωρουμένου δέ, οὐκ ἄρα, εἶπε, θεός ἐστιν.",
    en: "Is it not Athena the daughter of Zeus who is a goddess? And when the other said Yes, he went on, But this at least is not by Zeus but by Phidias, and, this being granted, he concluded, This then is not a god.",
    ref: "2.116",
    certainty: "reported",
    note: "D.L.: 'There is a story that he once used the following argument.'",
  },
  {
    id: "stilpo-not-in-the-street",
    philosopher: "Stilpo",
    topic: "religion",
    gloss: "When Crates asked in public whether the gods delight in prayers, he deferred the question to when they were alone.",
    grc: "περὶ τούτων μὴ ἐρώτα, ἀνόητε, ἐν ὁδῷ, ἀλλὰ μόνον.",
    en: "Don’t put such a question in the street, simpleton, but when we are alone!",
    ref: "2.117",
    to: "Crates",
    certainty: "reported",
    note: "D.L.: 'he is said to have replied.'",
  },
  {
    id: "stilpo-anything-but-what-you-ought",
    philosopher: "Stilpo",
    topic: "wit",
    gloss: "When Crates answered a question with an insult instead: he knew Crates would utter anything rather than what he ought.",
    grc: "ᾔδειν, ἔφη, ὡς πάντα μᾶλλον φθέγξῃ ἢ ἃ δεῖ.",
    en: "I knew, said Stilpo, that you would utter anything rather than what you ought.",
    ref: "2.117",
    to: "Crates",
    certainty: "asserted",
  },
  {
    id: "stilpo-fig-in-advance",
    philosopher: "Stilpo",
    topic: "wit",
    gloss: "He ate the fig Crates held out with a question: Crates lost not just the fig but the question it was payment for.",
    grc: "οὐ μόνον, ἔφη, ἀλλὰ καὶ τὸ ἐρώτημα, οὗ ἦν ἀρραβὼν ἡ ἰσχάς.",
    en: "Not only that but your question as well, for which the fig was payment in advance.",
    ref: "2.118",
    to: "Crates",
    certainty: "reported",
  },
  {
    id: "stilpo-new-coat",
    philosopher: "Stilpo",
    topic: "wit",
    gloss: "Seeing Crates shrivelled with cold: you seem to want a new coat - punning on wanting a new mind as well.",
    grc: "ὦ Κράτης, εἶπε, δοκεῖς μοι χρείαν ἔχειν ἱματίου καινοῦ.",
    en: "You seem to me, Crates, to want a new coat,",
    ref: "2.118",
    to: "Crates",
    certainty: "asserted",
  },
  {
    id: "stilpo-genuine-man",
    philosopher: "Stilpo",
    topic: "fame",
    gloss: "Told the Athenians stared at him as at some strange creature: no, as at a genuine man.",
    grc: "οὐ μὲν οὖν, εἰπεῖν, ἀλλʼ ὡς ἄνθρωπον ἀληθινόν.",
    en: "No, indeed, said he, but as if I were a genuine man.",
    ref: "2.119",
    certainty: "reported",
    note: "D.L.: 'It is said that at Athens he so attracted the public...'",
  },
  {
    id: "stilpo-argument-remains",
    philosopher: "Stilpo",
    topic: "wit",
    gloss: "Hurrying off mid-argument to buy fish: the argument will remain, but the fish will soon be sold.",
    grc: "οὐκ ἔγωγε, ἔφη, ἀλλὰ τὸν μὲν λόγον ἔχω, σὲ δὲ καταλείπω· ὁ μὲν γὰρ λόγος περιμενεῖ, τὸ δʼ ὄψον πεπράσεται.",
    en: "Not I. I keep the argument though I am leaving you; for the argument will remain, but the fish will soon be sold.",
    ref: "2.119",
    to: "Crates",
    certainty: "reported",
    note: "D.L.: 'The story goes...'",
  },
  // --------------------------------------------------------------------- Simon
  {
    id: "simon-free-speech",
    philosopher: "Simon",
    topic: "speech",
    gloss: "When Pericles promised to support him if he would come to him: he would not part with his free speech for money.",
    grc: "οὐκ ἂν ἔφη τὴν παρρησίαν ἀποδόσθαι.",
    en: "I will not part with my free speech for money.",
    ref: "2.123",
    to: "Pericles",
    certainty: "asserted",
  },
  // ----------------------------------------------------- Menedemus of Eretria
  {
    id: "menedemus-cabbage-radish",
    philosopher: "Menedemus of Eretria",
    topic: "wit",
    gloss: "To an adulterer giving himself airs: radish has as good a flavour as cabbage.",
    grc: "ἀγνοεῖς, ἔφη, ὅτι οὐ μόνον κράμβη χυλὸν ἔχει χρηστόν, ἀλλὰ καὶ ῥαφανίς;",
    en: "Do you not know that, if cabbage has a good flavour, so for that matter has radish?",
    ref: "2.128",
    certainty: "asserted",
  },
  {
    id: "menedemus-look-behind-you",
    philosopher: "Menedemus of Eretria",
    topic: "wit",
    gloss: "Hearing a very noisy youth: see what there is behind you.",
    grc: "σκέψαι, ἔφη, μή τι ὄπισθεν ἔχων λέληθας.",
    en: "See what there is behind you.",
    ref: "2.128",
    certainty: "asserted",
  },
  {
    id: "menedemus-son-of-a-king",
    philosopher: "Menedemus of Eretria",
    topic: "politics",
    gloss: "When Antigonus asked whether he should go to a drinking-rout, he sent back only the reminder that he was a king's son.",
    grc: "σιωπήσας τἄλλα μόνον ἐκέλευσεν ἀπαγγεῖλαι ὅτι βασιλέως υἱός ἐστι.",
    en: "he sent a message to say no more than this, that he was the son of a king",
    ref: "2.128",
    to: "Antigonus",
    certainty: "asserted",
  },
  {
    id: "menedemus-mind-your-farm",
    philosopher: "Menedemus of Eretria",
    topic: "wit",
    gloss: "To a stupid fellow rambling on, who admitted he had a farm and cattle: go and look after them.",
    grc: "πορεύου τοίνυν, ἔφη, κἀκείνων ἐπιμελοῦ, μὴ συμβῇ σοι καὶ ταῦτα καταφθεῖραι καὶ κομψὸν ἰδιώτην ἀποβαλεῖν.",
    en: "Then go and look after them, lest it should happen that they are ruined and a clever farmer thrown away.",
    ref: "2.128",
    certainty: "asserted",
  },
  {
    id: "menedemus-good-man-marries",
    philosopher: "Menedemus of Eretria",
    topic: "virtue",
    gloss: "Asked if the good man ever married: do you think me good? Then know that I am married.",
    grc: "πότερον ἐγώ σοι σπουδαῖος δοκῶ ἢ οὔ; φήσαντος δʼ εἶναι, ἐγὼ τοίνυν, εἶπε, γεγάμηκα.",
    en: "Do you think me good or not? The reply being in the affirmative, he said, Well, I am married.",
    ref: "2.128",
    certainty: "asserted",
  },
  {
    id: "menedemus-more-than-a-hundred",
    philosopher: "Menedemus of Eretria",
    topic: "wit",
    gloss: "Of one who affirmed that there were many good things, he asked whether he thought there were more than a hundred.",
    grc: "πρὸς δὲ τὸν εἰπόντα πολλὰ τὰ ἀγαθὰ ἐπύθετο πόσα τὸν ἀριθμὸν καὶ εἰ νομίζοι πλείω τῶν ἑκατόν.",
    en: "Of one who affirmed that there were many good things, he inquired how many, and whether he thought there were more than a hundred.",
    ref: "2.129",
    certainty: "asserted",
  },
  {
    id: "menedemus-daily-feast",
    philosopher: "Menedemus of Eretria",
    topic: "politics",
    gloss: "At Nicocreon's monthly feast: if gathering such men is good, it should happen every day; if not, it is superfluous now.",
    grc: "εἰ καλὸν ἦν ἡ τῶν τοιούτων ἀνδρῶν συναγωγή, καθʼ ἑκάστην ἡμέραν ἔδει γίνεσθαι τὴν ἑορτήν· εἰ δʼ οὔ, περιττῶς καὶ νῦν.",
    en: "if the gathering of such men was a good thing, the feast ought to have been held every day; if not, then it was superfluous even on the present occasion",
    ref: "2.129",
    certainty: "reported",
    note: "D.L.: 'we are told that Menedemus said...' - the frank speech that nearly cost him his life in Cyprus.",
  },
  {
    id: "menedemus-stilpo-gentleman",
    philosopher: "Menedemus of Eretria",
    topic: "virtue",
    gloss: "Questioned about Stilpo, whom he admired, he answered only that he was a gentleman.",
    grc: "καί ποτε ἐρωτηθεὶς περὶ αὐτοῦ ἄλλο μὲν οὐδὲν εἶπε πλὴν ὅτι ἐλευθέριος.",
    en: "when he was questioned about him, he made no other answer than that he was a gentleman",
    ref: "2.134",
    certainty: "asserted",
  },
  {
    id: "menedemus-confer-benefits",
    philosopher: "Menedemus of Eretria",
    topic: "wisdom",
    gloss: "His favourite eristic argument: benefiting differs from the good, therefore to confer benefits is not good.",
    grc: "τὸ ἕτερον τοῦ ἑτέρου ἕτερόν ἐστι; ναί. ἕτερον δέ ἐστι τὸ ὠφελεῖν τοῦ ἀγαθοῦ; ναί. οὐκ ἄρα τὸ ὠφελεῖν ἀγαθόν ἐστιν.",
    en: "Is the one of two things different from the other? Yes. And is conferring benefits different from the good? Yes. Then to confer benefits is not good.",
    ref: "2.134",
    certainty: "asserted",
  },
  {
    id: "menedemus-not-beating-father",
    philosopher: "Menedemus of Eretria",
    topic: "wit",
    gloss: "To Alexinus' trick question whether he had left off beating his father: I was not beating him and have not left off.",
    grc: "ἀλλʼ οὔτʼ ἔτυπτον, φάναι, οὔτε πέπαυμαι.",
    en: "Why, I was not beating him and have not left off",
    ref: "2.135",
    to: "Alexinus",
    certainty: "reported",
    accordingTo: "Heraclides",
  },
  {
    id: "menedemus-stop-at-threshold",
    philosopher: "Menedemus of Eretria",
    topic: "speech",
    gloss: "When Alexinus insisted on a plain yes or no: absurd to follow your rules when I can stop you on the threshold.",
    grc: "γελοῖον, εἶπε, τοῖς ὑμετέροις νόμοις ἀκολουθεῖν, ἐξὸν ἐν πύλαις ἀντιβῆναι.",
    en: "It would be absurd, he said, for me to conform to your rules when I can stop you on the threshold.",
    ref: "2.135",
    to: "Alexinus",
    certainty: "reported",
    accordingTo: "Heraclides",
  },
  {
    id: "menedemus-slaying-the-slain",
    philosopher: "Menedemus of Eretria",
    topic: "wit",
    gloss: "When Bion persistently ran down the soothsayers: he was slaying the slain.",
    grc: "νεκροὺς αὐτὸν ἐπισφάττειν ἔλεγε.",
    en: "Menedemus said he was slaying the slain.",
    ref: "2.135",
    certainty: "asserted",
  },
  {
    id: "menedemus-want-right-things",
    philosopher: "Menedemus of Eretria",
    topic: "wisdom",
    gloss: "Hearing that the greatest good is getting all you want: a far greater good is to want the right things.",
    grc: "πολὺ δὲ μεῖζον τὸ ἐπιθυμεῖν ὧν δεῖ.",
    en: "To want the right things is a far greater good.",
    ref: "2.136",
    certainty: "asserted",
  },
  {
    id: "menedemus-asclepiades-door",
    philosopher: "Menedemus of Eretria",
    topic: "friendship",
    gloss: "Admitting the late Asclepiades' favourite to a party: even under the earth, Asclepiades opens the door for him.",
    grc: "εἰπὼν ὅτι Ἀσκληπιάδης αὐτῷ καὶ κατὰ γῆς ὢν τὰς θύρας ἀνοίγει.",
    en: "even now, when under the earth, Asclepiades opened the door for him",
    ref: "2.138",
    certainty: "asserted",
  },
  {
    id: "menedemus-persaeus-worst-of-men",
    philosopher: "Menedemus of Eretria",
    topic: "wit",
    gloss: "Refuting Persaeus over the wine: such a philosopher, but as a man the worst of all alive or to be born.",
    grc: "φιλόσοφος μὲν [τοι] τοιοῦτος, ἀνὴρ δὲ καὶ τῶν ὄντων καὶ τῶν γενησομένων κάκιστος.",
    en: "Such he is as a philosopher but, as a man, the worst of all that are alive or to be born hereafter.",
    ref: "2.144",
    to: "Persaeus",
    certainty: "asserted",
    note: "Persaeus was thought to have blocked Antigonus' restoration of the Eretrian democracy for Menedemus' sake.",
  },
];
