/**
 * Curated sayings & apophthegms from Book 1 of Diogenes Laertius' Lives
 * (the Seven Sages), cited to Hicks section ids (book.section). See sayings.ts
 * for the model and curation rules. Source-internal: every `en` is a verbatim
 * excerpt of its cited section.
 */
import type { Saying } from "../sayings";

export const BOOK1_SAYINGS: Saying[] = [
  // -------------------------------------------------------------------- Thales
  {
    id: "thales-most-ancient-god",
    philosopher: "Thales",
    topic: "religion",
    gloss: "Of all things the most ancient is God, for he alone is uncreated.",
    grc: "πρεσβύτατον τῶν ὄντων θεός· ἀγένητον γάρ.",
    en: "Of all things that are, the most ancient is God, for he is uncreated.",
    ref: "1.35",
    certainty: "asserted",
  },
  {
    id: "thales-life-death",
    philosopher: "Thales",
    topic: "death",
    gloss:
      "He held life and death no different; asked why then he did not die, he said: for that very reason.",
    grc: "οὐδὲν ἔφη τὸν θάνατον διαφέρειν τοῦ ζῆν. σὺ οὖν, ἔφη τις, διὰ τί οὐκ ἀποθνήσκεις; ὅτι, ἔφη, οὐδὲν διαφέρει.",
    en: "He held there was no difference between life and death. Why then, said one, do you not die? Because, said he, there is no difference.",
    ref: "1.35",
    certainty: "asserted",
  },
  {
    id: "thales-what-is-difficult",
    philosopher: "Thales",
    topic: "wisdom",
    gloss: "Asked what is difficult, he answered: to know oneself.",
    grc: "ἐρωτηθεὶς τί δύσκολον, ἔφη, τὸ ἑαυτὸν γνῶναι",
    en: "Being asked what is difficult, he replied, To know oneself.",
    ref: "1.36",
    certainty: "asserted",
  },
  {
    id: "thales-know-thyself",
    philosopher: "Thales",
    topic: "wisdom",
    gloss:
      "The Delphic maxim 'Know thyself' was credited to him, though others assign it elsewhere.",
    grc: "Τούτου ἐστὶν τὸ Γνῶθι σαυτόν",
    en: "To him belongs the proverb Know thyself",
    ref: "1.40",
    certainty: "disputed",
    alsoAttributedTo: "Chilon",
    note: "D.L.: Antisthenes attributes it to Phemonoë, 'though admitting that it was appropriated by Chilon.'",
  },
  {
    id: "thales-loved-children",
    philosopher: "Thales",
    topic: "wit",
    gloss: "Asked why he had no children of his own: because he loved children.",
    grc: "ἐρωτηθέντα διὰ τί οὐ τεκνοποιεῖ, διὰ φιλοτεκνίαν εἰπεῖν.",
    en: "when he was asked why he had no children of his own he replied because he loved children",
    ref: "1.26",
    certainty: "asserted",
  },
  {
    id: "thales-too-soon-too-late",
    philosopher: "Thales",
    topic: "wit",
    gloss:
      "Pressed by his mother to marry, he said it was too soon; later in life, that it was too late.",
    grc: "τῆς μητρὸς ἀναγκαζούσης αὐτὸν γῆμαι, [νὴ Δία], ἔλεγεν, οὐδέπω καιρός. εἶτα, ἐπειδὴ παρήβησεν ἐγκειμένης, εἰπεῖν, οὐκέτι καιρός.",
    en: "when his mother tried to force him to marry, he replied it was too soon, and when she pressed him again later in life, he replied that it was too late",
    ref: "1.26",
    certainty: "reported",
  },
  {
    id: "thales-three-blessings",
    philosopher: "Thales",
    topic: "fortune",
    gloss:
      "He thanked Fortune for three blessings: to be born human and not brute, man and not woman, Greek and not barbarian.",
    grc: "τριῶν τούτων ἕνεκα χάριν ἔχειν τῇ Τύχῃ· πρῶτον μὲν ὅτι ἄνθρωπος ἐγενόμην καὶ οὐ θηρίον, εἶτα ὅτι ἀνὴρ καὶ οὐ γυνή, τρίτον ὅτι Ἕλλην καὶ οὐ βάρβαρος.",
    en: "there were three blessings for which he was grateful to Fortune: first, that I was born a human being and not one of the brutes; next, that I was born a man and not a woman; thirdly, a Greek and not a barbarian",
    ref: "1.33",
    certainty: "disputed",
    accordingTo: "Hermippus",
    alsoAttributedTo: "Socrates",
    note: "D.L.: 'Hermippus in his Lives refers to Thales the story which is told by some of Socrates.'",
  },
  {
    id: "thales-beautiful-universe",
    philosopher: "Thales",
    topic: "religion",
    gloss: "The most beautiful thing is the universe, for it is God's workmanship.",
    grc: "κάλλιστον κόσμος· ποίημα γὰρ θεοῦ.",
    en: "The most beautiful is the universe, for it is God’s workmanship.",
    ref: "1.35",
    certainty: "asserted",
  },
  {
    id: "thales-greatest-space",
    philosopher: "Thales",
    topic: "wisdom",
    gloss: "The greatest thing is space, for it holds all things.",
    grc: "μέγιστον τόπος· ἅπαντα γὰρ χωρεῖ.",
    en: "The greatest is space, for it holds all things.",
    ref: "1.35",
    certainty: "asserted",
  },
  {
    id: "thales-swiftest-mind",
    philosopher: "Thales",
    topic: "wisdom",
    gloss: "The swiftest thing is mind, for it speeds everywhere.",
    grc: "τάχιστον νοῦς· διὰ παντὸς γὰρ τρέχει.",
    en: "The swiftest is mind, for it speeds everywhere.",
    ref: "1.35",
    certainty: "asserted",
  },
  {
    id: "thales-strongest-necessity",
    philosopher: "Thales",
    topic: "wisdom",
    gloss: "The strongest thing is necessity, for it masters all.",
    grc: "ἰσχυρότατον ἀνάγκη· κρατεῖ γὰρ πάντων.",
    en: "The strongest, necessity, for it masters all.",
    ref: "1.35",
    certainty: "asserted",
  },
  {
    id: "thales-wisest-time",
    philosopher: "Thales",
    topic: "wisdom",
    gloss: "The wisest thing is time, for it brings everything to light.",
    grc: "σοφώτατον χρόνος· ἀνευρίσκει γὰρ πάντα.",
    en: "The wisest, time, for it brings everything to light.",
    ref: "1.35",
    certainty: "asserted",
  },
  {
    id: "thales-night-older",
    philosopher: "Thales",
    topic: "wit",
    gloss: "Which is older, day or night? Night - by one day.",
    grc: "πρὸς τὸν πυθόμενον τί πρότερον γεγόνοι, νὺξ ἢ ἡμέρα, ἡ νύξ, ἔφη, μιᾷ ἡμέρᾳ πρότερον.",
    en: "To the question which is older, day or night, he replied: Night is the older by one day.",
    ref: "1.36",
    certainty: "asserted",
  },
  {
    id: "thales-evil-thought",
    philosopher: "Thales",
    topic: "religion",
    gloss:
      "Can a man hide an evil deed from the gods? No - nor yet an evil thought.",
    grc: "ἠρώτησέ τις αὐτὸν εἰ λήθοι θεοὺς ἄνθρωπος ἀδικῶν· ἀλλʼ οὐδὲ διανοούμενος, ἔφη.",
    en: "Some one asked him whether a man could hide an evil deed from the gods: No, he replied, nor yet an evil thought.",
    ref: "1.36",
    certainty: "asserted",
  },
  {
    id: "thales-perjury-adultery",
    philosopher: "Thales",
    topic: "virtue",
    gloss:
      "To the adulterer asking whether to deny the charge on oath: perjury is no worse than adultery.",
    grc: "πρὸς τὸν μοιχὸν ἐρόμενον εἰ ὀμόσειε μὴ μεμοιχευκέναι, οὐ χεῖρον, ἔφη, μοιχείας ἐπιορκία.",
    en: "To the adulterer who inquired if he should deny the charge upon oath he replied that perjury was no worse than adultery.",
    ref: "1.36",
    certainty: "asserted",
  },
  {
    id: "thales-easy-advice",
    philosopher: "Thales",
    topic: "wit",
    gloss: "What is easy? To give advice to another.",
    grc: "τί δὲ εὔκολον, τὸ ἄλλῳ ὑποθέσθαι",
    en: "What is easy? To give advice to another.",
    ref: "1.36",
    certainty: "asserted",
  },
  {
    id: "thales-pleasant-success",
    philosopher: "Thales",
    topic: "pleasure",
    gloss: "What is most pleasant? Success.",
    grc: "τί ἥδιστον, τὸ ἐπιτυγχάνειν",
    en: "What is most pleasant? Success.",
    ref: "1.36",
    certainty: "asserted",
  },
  {
    id: "thales-the-divine",
    philosopher: "Thales",
    topic: "religion",
    gloss: "The divine is that which has neither beginning nor end.",
    grc: "τί τὸ θεῖον, τὸ μήτε ἀρχὴν ἔχον μήτε τελευτήν.",
    en: "What is the divine? That which has neither beginning nor end.",
    ref: "1.36",
    certainty: "asserted",
  },
  {
    id: "thales-aged-tyrant",
    philosopher: "Thales",
    topic: "wit",
    gloss: "The strangest thing he had ever seen: an aged tyrant.",
    grc: "τί δὲ καινὸν εἴη τεθεαμένος ἔφη· γέροντα τύραννον.",
    en: "To the question what was the strangest thing he had ever seen, his answer was, An aged tyrant.",
    ref: "1.36",
    certainty: "asserted",
  },
  {
    id: "thales-adversity-enemies",
    philosopher: "Thales",
    topic: "fortune",
    gloss:
      "How best to bear adversity: by seeing one's enemies in worse plight.",
    grc: "πῶς ἄν τις ἀτυχίαν ῥᾷστα φέροι, εἰ τοὺς ἐχθροὺς χεῖρον πράσσοντας βλέποι",
    en: "How can one best bear adversity? If he should see his enemies in worse plight.",
    ref: "1.36",
    certainty: "asserted",
  },
  {
    id: "thales-blame-others",
    philosopher: "Thales",
    topic: "virtue",
    gloss:
      "The best and most righteous life: refrain from doing what we blame in others.",
    grc: "πῶς ἂν ἄριστα καὶ δικαιότατα βιώσαιμεν, ἐὰν ἃ τοῖς ἄλλοις ἐπιτιμῶμεν, αὐτοὶ μὴ δρῶμεν",
    en: "How shall we lead the best and most righteous life? By refraining from doing what we blame in others.",
    ref: "1.36",
    certainty: "asserted",
  },
  {
    id: "thales-happy-man",
    philosopher: "Thales",
    topic: "fortune",
    gloss:
      "The happy man has a healthy body, a resourceful mind, and a docile nature.",
    grc: "τίς εὐδαίμων, ὁ τὸ μὲν σῶμα ὑγιής, τὴν δὲ ψυχὴν εὔπορος, τὴν δὲ φύσιν εὐπαίδευτος.",
    en: "What man is happy? He who has a healthy body, a resourceful mind and a docile nature.",
    ref: "1.37",
    certainty: "asserted",
  },
  {
    id: "thales-remember-friends",
    philosopher: "Thales",
    topic: "friendship",
    gloss: "Remember friends, whether present or absent.",
    grc: "φίλων παρόντων καὶ ἀπόντων μεμνῆσθαί φησι",
    en: "He tells us to remember friends, whether present or absent",
    ref: "1.37",
    certainty: "asserted",
  },
  {
    id: "thales-beautiful-character",
    philosopher: "Thales",
    topic: "virtue",
    gloss:
      "Do not pride yourself on outward appearance; study to be beautiful in character.",
    grc: "μὴ τὴν ὄψιν καλλωπίζεσθαι, ἀλλὰ τοῖς ἐπιτηδεύμασιν εἶναι καλόν.",
    en: "not to pride ourselves upon outward appearance, but to study to be beautiful in character",
    ref: "1.37",
    certainty: "asserted",
  },
  {
    id: "thales-ill-gotten-gains",
    philosopher: "Thales",
    topic: "wealth",
    gloss: "Shun ill-gotten gains.",
    grc: "μὴ πλούτει, φησί, κακῶς",
    en: "Shun ill-gotten gains, he says.",
    ref: "1.37",
    certainty: "asserted",
  },
  {
    id: "thales-parents-children",
    philosopher: "Thales",
    topic: "virtue",
    gloss:
      "Whatever you provide for your parents, expect the same from your children.",
    grc: "οὓς ἂν ἐράνους εἰσενέγκῃς, φησί, τοῖς γονεῦσιν, τοὺς αὐτοὺς προσδέχου καὶ παρὰ τῶν τέκνων.",
    en: "Whatever provision thou hast made for thy parents, the same must thou expect from thy children.",
    ref: "1.37",
    certainty: "asserted",
  },
  // --------------------------------------------------------------------- Solon
  {
    id: "solon-laws-spiderwebs",
    philosopher: "Solon",
    topic: "politics",
    gloss:
      "Laws are like spiders' webs: they hold the weak but the powerful break through.",
    grc: "τοὺς δὲ νόμους τοῖς ἀραχνίοις ὁμοίους· καὶ γὰρ ἐκεῖνα, ἐὰν μὲν ἐμπέσῃ τι κοῦφον καὶ ἀσθενές, στέγειν· ἐὰν δὲ μεῖζον, διακόψαν οἴχεσθαι.",
    en: "He compared laws to spiders' webs, which stand firm when any light and yielding object falls upon them, while a larger thing breaks through them and makes off.",
    ref: "1.58",
    certainty: "asserted",
  },
  {
    id: "solon-speech-mirror",
    philosopher: "Solon",
    topic: "speech",
    gloss: "Speech is the mirror of action.",
    grc: "τὸν μὲν λόγον εἴδωλον εἶναι τῶν ἔργων",
    en: "Speech is the mirror of action",
    ref: "1.58",
    certainty: "asserted",
  },
  {
    id: "solon-weep-no-avail",
    philosopher: "Solon",
    topic: "death",
    gloss:
      "Weeping for his dead son and told it availed nothing, he said that was the very reason he wept.",
    grc: "διʼ αὐτὸ δὲ τοῦτο δακρύω, ὅτι οὐδὲν ἀνύτω.",
    en: "That is why I weep, because it is of no avail.",
    ref: "1.63",
    certainty: "reported",
    accordingTo: "Dioscurides",
  },
  {
    id: "solon-nothing-too-much",
    philosopher: "Solon",
    topic: "virtue",
    gloss: "'Nothing too much' - the maxim of measure, also claimed for Chilon.",
    grc: "Μηδὲν ἄγαν.",
    en: "he was the author of the apophthegm Nothing too much",
    ref: "1.63",
    certainty: "disputed",
    alsoAttributedTo: "Chilon",
    note: "The same maxim is elsewhere ascribed to Chilon (1.41).",
  },
  {
    id: "solon-croesus-happy",
    philosopher: "Solon",
    topic: "fortune",
    gloss:
      "Asked by Croesus whom he considered happy, he named Tellus of Athens, Cleobis and Biton.",
    grc: "ἐρωτηθεὶς ὑπʼ αὐτοῦ, τίς σοι δοκεῖ εὐδαίμων; Τέλλος, ἔφη, Ἀθηναῖος καὶ Κλέοβις καὶ Βίτων καὶ τὰ θρυλούμενα.",
    en: "There Croesus put the question, Whom do you consider happy? and Solon replied, Tellus of Athens, and Cleobis and Biton, and went on in words too familiar to be quoted here.",
    ref: "1.50",
    certainty: "asserted",
  },
  {
    id: "solon-cocks-peacocks",
    philosopher: "Solon",
    topic: "wit",
    gloss:
      "Croesus enthroned in splendour asked if he had seen anything more beautiful: yes - cocks, pheasants and peacocks, whose colours are nature's own.",
    grc: "ὁ δέ ἀλεκτρυόνας, εἶπε, καὶ φασιανοὺς καὶ ταώς· φυσικῷ γὰρ ἄνθει κεκόσμηνται καὶ μυρίῳ καλλίονι.",
    en: "Yes, was the reply, cocks and pheasants and peacocks; for they shine in nature’s colours, which are ten thousand times more beautiful.",
    ref: "1.51",
    certainty: "reported",
  },
  {
    id: "solon-seventy-years",
    philosopher: "Solon",
    topic: "death",
    gloss: "Seventy years are the term of man's life.",
    grc: "Σόλων δὲ ὅρον ἀνθρωπίνου βίου φησὶν ἔτη ἑβδομήκοντα.",
    en: "one of his sayings is that 70 years are the term of man’s life",
    ref: "1.55",
    certainty: "asserted",
  },
  {
    id: "solon-strongest-king",
    philosopher: "Solon",
    topic: "politics",
    gloss: "The strongest and most capable is king.",
    grc: "βασιλέα δὲ τὸν ἰσχυρότατον τῇ δυνάμει.",
    en: "the strongest and most capable is king",
    ref: "1.58",
    certainty: "asserted",
  },
  {
    id: "solon-secrecy-seal",
    philosopher: "Solon",
    topic: "speech",
    gloss: "Secrecy is the seal of speech, and occasion the seal of secrecy.",
    grc: "ἔφασκέ τε σφραγίζεσθαι τὸν μὲν λόγον σιγῇ, τὴν δὲ σιγὴν καιρῷ.",
    en: "Secrecy he called the seal of speech, and occasion the seal of secrecy.",
    ref: "1.58",
    certainty: "asserted",
  },
  {
    id: "solon-tyrant-pebbles",
    philosopher: "Solon",
    topic: "politics",
    gloss:
      "Courtiers of tyrants are like calculation pebbles: now they stand for much, now for little.",
    grc: "ἔλεγε δὲ τοὺς παρὰ τοῖς τυράννοις δυναμένους παραπλησίους εἶναι ταῖς ψήφοις ταῖς ἐπὶ τῶν λογισμῶν.",
    en: "He used to say that those who had influence with tyrants were like the pebbles employed in calculations; for, as each of the pebbles represented now a large and now a small number, so the tyrants would treat each one of those about them at one time as great and famous, at another as of no account.",
    ref: "1.59",
    certainty: "asserted",
  },
  {
    id: "solon-parricide-law",
    philosopher: "Solon",
    topic: "politics",
    gloss:
      "Asked why he made no law against parricide: he hoped it was unnecessary.",
    grc: "ἐρωτηθεὶς διὰ τί κατὰ πατροκτόνου νόμον οὐκ ἔθηκε, διὰ τὸ ἀπελπίσαι, ἔφη.",
    en: "On being asked why he had not framed any law against parricide, he replied that he hoped it was unnecessary.",
    ref: "1.59",
    certainty: "asserted",
  },
  {
    id: "solon-crime-resentment",
    philosopher: "Solon",
    topic: "politics",
    gloss:
      "Crime is best diminished when it stirs as much resentment in those unharmed as in its victims.",
    grc: "πῶς τε ἥκιστʼ ἂν ἀδικοῖεν οἱ ἄνθρωποι, εἰ ὁμοίως, ἔφη, ἄχθοιντο τοῖς ἀδικουμένοις οἱ μὴ ἀδικούμενοι.",
    en: "Asked how crime could most effectually be diminished, he replied, If it caused as much resentment in those who are not its victims as in those who are",
    ref: "1.59",
    certainty: "asserted",
  },
  {
    id: "solon-wealth-satiety",
    philosopher: "Solon",
    topic: "wealth",
    gloss: "Wealth breeds satiety, satiety outrage.",
    grc: "καὶ τὸν μὲν κόρον ὑπὸ τοῦ πλούτου γεννᾶσθαι, τὴν δὲ ὕβριν ὑπὸ τοῦ κόρου.",
    en: "Wealth breeds satiety, satiety outrage.",
    ref: "1.59",
    certainty: "asserted",
  },
  {
    id: "solon-acting-tragedies",
    philosopher: "Solon",
    topic: "wit",
    gloss:
      "When Pisistratus appeared with self-inflicted wounds: 'This comes from acting tragedies.'",
    grc: "Πεισίστρατος ἑαυτὸν κατέτρωσεν, ἐκεῖθεν ἔφη ταῦτα φῦναι.",
    en: "When therefore Pisistratus appeared with self-inflicted wounds, Solon said, This comes from acting tragedies.",
    ref: "1.60",
    certainty: "asserted",
  },
  {
    id: "solon-counsel-precepts",
    philosopher: "Solon",
    topic: "virtue",
    gloss:
      "His counsel to men: trust character above oaths, never lie, pursue worthy aims, keep friends once made, learn to obey before commanding, advise what is best not what is most pleasing, follow reason, shun bad company, honour the gods and reverence parents.",
    grc: "καλοκἀγαθίαν ὅρκου πιστοτέραν ἔχε. μὴ ψεύδου. τὰ σπουδαῖα μελέτα. φίλους μὴ ταχὺ κτῶ· οὓς δʼ ἂν κτήσῃ μὴ ἀποδοκίμαζε. ἄρχε πρῶτον μαθὼν ἄρχεσθαι. συμβούλευε μὴ τὰ ἥδιστα, ἀλλὰ τὰ ἄριστα. νοῦν ἡγεμόνα ποιοῦ. μὴ κακοῖς ὁμίλει. θεοὺς τίμα, γονέας αἰδοῦ.",
    en: "Put more trust in nobility of character than in an oath. Never tell a lie. Pursue worthy aims. Do not be rash to make friends and, when once they are made, do not drop them. Learn to obey before you command. In giving advice seek to help, not to please, your friend. Be led by reason. Shun evil company. Honour the gods, reverence parents.",
    ref: "1.60",
    certainty: "reported",
    accordingTo: "Apollodorus",
    note: "D.L.: 'His counsel to men in general is stated by Apollodorus in his work on the Philosophic Sects as follows.'",
  },
  // -------------------------------------------------------------------- Chilon
  {
    id: "chilon-give-pledge",
    philosopher: "Chilon",
    topic: "wisdom",
    gloss: "'Give a pledge, and suffer for it' - a warning against rash suretyship.",
    grc: "ἐγγύα, πάρα δʼ ἄτα.",
    en: "Give a pledge, and suffer for it.",
    ref: "1.73",
    certainty: "asserted",
  },
  {
    id: "chilon-educated-good-hope",
    philosopher: "Chilon",
    topic: "education",
    gloss: "The difference between the educated and the uneducated: good hope.",
    grc: "ἐρωτηθεὶς τίνι διαφέρουσιν οἱ πεπαιδευμένοι τῶν ἀπαιδεύτων, ἔφη, ἐλπίσιν ἀγαθαῖς.",
    en: "Being asked wherein lies the difference between the educated and the uneducated, Chilon answered, In good hope.",
    ref: "1.69",
    certainty: "asserted",
  },
  {
    id: "chilon-submit-injustice",
    philosopher: "Chilon",
    topic: "wit",
    gloss:
      "To his brother, sore at not being made ephor: the difference is that I can bear injustice and you cannot.",
    grc: "ἐγὼ μὲν γὰρ ἐπίσταμαι, εἶπεν, ἀδικεῖσθαι, σὺ δὲ οὔ.",
    en: "I know how to submit to injustice and you do not.",
    ref: "1.68",
    certainty: "asserted",
  },
  {
    id: "chilon-excellence-foresight",
    philosopher: "Chilon",
    topic: "wisdom",
    gloss:
      "The excellence of a man is to divine the future so far as reason can grasp it.",
    grc: "ἔφασκε πρόνοιαν περὶ τοῦ μέλλοντος λογισμῷ καταληπτὴν εἶναι ἀνδρὸς ἀρετήν.",
    en: "he declared that the excellence of a man is to divine the future so far as it can be grasped by reason",
    ref: "1.68",
    certainty: "asserted",
  },
  {
    id: "chilon-what-is-hard",
    philosopher: "Chilon",
    topic: "wisdom",
    gloss:
      "What is hard: to keep a secret, to employ leisure well, to bear an injury.",
    grc: "τί δύσκολον, τὸ τὰ ἀπόρρητα σιωπῆσαι, καὶ σχολὴν εὖ διαθέσθαι, καὶ ἀδικούμενον [δύνασθαι] φέρειν.",
    en: "What is hard? To keep a secret, to employ leisure well, to be able to bear an injury.",
    ref: "1.69",
    certainty: "asserted",
  },
  {
    id: "chilon-control-tongue",
    philosopher: "Chilon",
    topic: "speech",
    gloss: "Control the tongue, especially at a banquet.",
    grc: "γλώττης κρατεῖν, καὶ μάλιστα ἐν συμποσίῳ.",
    en: "To control the tongue, especially at a banquet.",
    ref: "1.69",
    certainty: "asserted",
  },
  {
    id: "chilon-threats-womanish",
    philosopher: "Chilon",
    topic: "speech",
    gloss: "Do not use threats to anyone; that is womanish.",
    grc: "μὴ ἀπειλεῖν μηδενί· γυναικῶδες γάρ.",
    en: "Do not use threats to any one; for that is womanish.",
    ref: "1.70",
    certainty: "asserted",
  },
  {
    id: "chilon-visit-friends-adversity",
    philosopher: "Chilon",
    topic: "friendship",
    gloss:
      "Be more ready to visit friends in adversity than in prosperity.",
    grc: "ταχύτερον ἐπὶ τὰς ἀτυχίας τῶν φίλων ἢ ἐπὶ τὰς εὐτυχίας πορεύεσθαι.",
    en: "Be more ready to visit friends in adversity than in prosperity.",
    ref: "1.70",
    certainty: "asserted",
  },
  {
    id: "chilon-speak-no-ill-dead",
    philosopher: "Chilon",
    topic: "speech",
    gloss: "Speak no evil of the dead.",
    grc: "τὸν τεθνηκότα μὴ κακολογεῖν.",
    en: "De mortuis nil nisi bonum.",
    ref: "1.70",
    certainty: "asserted",
    note: "Hicks renders the Greek ('do not speak ill of the dead') with the Latin proverb.",
  },
  {
    id: "chilon-loss-dishonest-gain",
    philosopher: "Chilon",
    topic: "wealth",
    gloss:
      "Prefer a loss to a dishonest gain: the one pains once, the other forever.",
    grc: "ζημίαν αἱρεῖσθαι μᾶλλον ἢ κέρδος αἰσχρόν· ἡ μὲν γὰρ ἅπαξ ἐλύπησε, τὸ δὲ διὰ παντός.",
    en: "Prefer a loss to a dishonest gain: the one brings pain at the moment, the other for all time.",
    ref: "1.70",
    certainty: "asserted",
  },
  {
    id: "chilon-strong-merciful",
    philosopher: "Chilon",
    topic: "virtue",
    gloss:
      "When strong, be merciful, so your neighbours respect rather than fear you.",
    grc: "ἰσχυρὸν ὄντα πρᾷον εἶναι, ὅπως οἱ πλησίον αἰδῶνται μᾶλλον ἢ φοβῶνται.",
    en: "When strong, be merciful, if you would have the respect, not the fear, of your neighbours.",
    ref: "1.70",
    certainty: "asserted",
  },
  {
    id: "chilon-tongue-thought",
    philosopher: "Chilon",
    topic: "speech",
    gloss: "Let not your tongue outrun your thought.",
    grc: "τὴν γλῶτταν μὴ προτρέχειν τοῦ νοῦ.",
    en: "Let not your tongue outrun your thought.",
    ref: "1.70",
    certainty: "asserted",
  },
  {
    id: "chilon-no-broken-law",
    philosopher: "Chilon",
    topic: "virtue",
    gloss:
      "In old age he said he was not aware of ever having broken the law - but was unsure on one point, a friend's lawsuit.",
    grc: "φασὶ δʼ αὐτόν ποτε γηραιὸν ἤδη ὄντα εἰπεῖν, ὡς οὐδὲν συνειδείη ἄνομον ἑαυτῷ ἐν τῷ βίῳ· διστάζειν δὲ περὶ ἑνός.",
    en: "He is reported to have said in his old age that he was not aware of having ever broken the law throughout his life; but on one point he was not quite clear.",
    ref: "1.71",
    certainty: "reported",
  },
  {
    id: "chilon-cythera",
    philosopher: "Chilon",
    topic: "politics",
    gloss:
      "Of the island Cythera off Laconia: would it had never been placed there, or had sunk into the sea.",
    grc: "εἴθε, ἔφη, μὴ ἐγεγόνει, ἢ γενομένη κατεβυθίσθη.",
    en: "Would it had never been placed there, or else had been sunk in the depths of the sea.",
    ref: "1.71",
    certainty: "asserted",
  },
  // ------------------------------------------------------------------ Pittacus
  {
    id: "pittacus-hard-to-be-good",
    philosopher: "Pittacus",
    topic: "virtue",
    gloss: "'It is hard to be good' - the maxim Plato debates in the Protagoras.",
    grc: "χαλεπὸν ἐσθλὸν ἔμμεναι",
    en: "It is hard to be good",
    ref: "1.76",
    certainty: "asserted",
  },
  {
    id: "pittacus-office-shows-man",
    philosopher: "Pittacus",
    topic: "politics",
    gloss: "Office shows the man.",
    grc: "ἀρχὴ ἄνδρα δείκνυσιν.",
    en: "Office shows the man.",
    ref: "1.77",
    certainty: "asserted",
  },
  {
    id: "pittacus-know-opportunity",
    philosopher: "Pittacus",
    topic: "wisdom",
    gloss: "'Know thine opportunity' - seize the right moment.",
    grc: "καιρὸν γνῶθι.",
    en: "Know thine opportunity.",
    ref: "1.79",
    certainty: "asserted",
  },
  {
    id: "pittacus-mercy-vengeance",
    philosopher: "Pittacus",
    topic: "virtue",
    gloss: "'Mercy is better than vengeance' - said on freeing a captured foe.",
    grc: "συγγνώμη τιμωρίας κρείσσων.",
    en: "Mercy is better than vengeance.",
    ref: "1.76",
    certainty: "reported",
    accordingTo: "Heraclitus",
    note: "Pamphila gives the saying instead as 'It is better to pardon now than to repent later,' spoken over his son's murderer.",
  },
  {
    id: "pittacus-half-more-whole",
    philosopher: "Pittacus",
    topic: "self-sufficiency",
    gloss:
      "Granted land, he cut off a small portion and pronounced the half to be more than the whole.",
    grc: "Σωσικράτης δέ φησιν ὅτι ὀλίγον ἀποτεμόμενος ἔφη τὸ ἥμισυ τοῦ παντὸς πλεῖον εἶναι.",
    en: "Sosicrates relates that he cut off a small portion for himself and pronounced the half to be more than the whole.",
    ref: "1.75",
    certainty: "reported",
    accordingTo: "Sosicrates",
  },
  {
    id: "pittacus-twice-as-much",
    philosopher: "Pittacus",
    topic: "self-sufficiency",
    gloss:
      "He declined Croesus' money, saying he already had twice as much as he wanted.",
    grc: "ἀλλὰ καὶ Κροίσου διδόντος χρήματα οὐκ ἐδέξατο, εἰπὼν ἔχειν ὧν ἐβούλετο διπλάσια",
    en: "he declined an offer of money made him by Croesus, saying that he had twice as much as he wanted",
    ref: "1.75",
    certainty: "asserted",
  },
  {
    id: "pittacus-gods-necessity",
    philosopher: "Pittacus",
    topic: "religion",
    gloss: "Even the gods do not fight against necessity.",
    grc: "ἀνάγκᾳ δʼ οὐδὲ θεοὶ μάχονται.",
    en: "Even the gods do not fight against necessity.",
    ref: "1.77",
    certainty: "asserted",
  },
  {
    id: "pittacus-work-in-hand",
    philosopher: "Pittacus",
    topic: "wisdom",
    gloss: "The best thing: to do well the work in hand.",
    grc: "ἐρωτηθεὶς δέ ποτε τί ἄριστον, τὸ παρὸν εὖ ποιεῖν.",
    en: "Once, when asked what is the best thing, he replied, To do well the work in hand.",
    ref: "1.77",
    certainty: "asserted",
  },
  {
    id: "pittacus-rule-shifting-wood",
    philosopher: "Pittacus",
    topic: "politics",
    gloss:
      "Asked by Croesus what is the best rule: the rule of the shifting wood - meaning the law.",
    grc: "καὶ ὑπὸ Κροίσου τίς ἀρχὴ μεγίστη, ἡ τοῦ ποικίλου, ἔφη, ξύλου, σημαίνων τὸν νόμον.",
    en: "And, when Croesus inquired what is the best rule, he answered, The rule of the shifting wood, by which he meant the law.",
    ref: "1.77",
    certainty: "asserted",
  },
  {
    id: "pittacus-bloodless-victories",
    philosopher: "Pittacus",
    topic: "politics",
    gloss: "Win bloodless victories.",
    grc: "ἔλεγε δὲ καὶ τὰς νίκας ἄνευ αἵματος ποιεῖσθαι.",
    en: "He also urged men to win bloodless victories.",
    ref: "1.77",
    certainty: "asserted",
  },
  {
    id: "pittacus-seek-too-carefully",
    philosopher: "Pittacus",
    topic: "wit",
    gloss:
      "On the search for a good man: if you seek too carefully, you will never find him.",
    grc: "ἔφη δὲ καὶ πρὸς τὸν Φωκαϊκὸν φάσκοντα δεῖν ζητεῖν ἄνθρωπον σπουδαῖον, ἂν λίαν, ἔφη, ζητῇς, οὐχ εὑρήσεις.",
    en: "When the Phocaean said that we must search for a good man, Pittacus rejoined, If you seek too carefully, you will never find him.",
    ref: "1.77",
    certainty: "asserted",
  },
  {
    id: "pittacus-trusty-earth",
    philosopher: "Pittacus",
    topic: "wisdom",
    gloss:
      "What is agreeable? Time. Obscure? The future. Trustworthy? The earth. Untrustworthy? The sea.",
    grc: "καὶ πρὸς τοὺς πυνθανομένους τί εὐχάριστον, χρόνος, ἔφη· ἀφανές, τὸ μέλλον · πιστόν, γῆ · ἄπιστον, θάλασσα.",
    en: "He answered various inquiries thus: What is agreeable? Time. Obscure? The future. Trustworthy? The earth. Untrustworthy? The sea.",
    ref: "1.77",
    certainty: "asserted",
  },
  {
    id: "pittacus-prudent-provide",
    philosopher: "Pittacus",
    topic: "wisdom",
    gloss:
      "Prudent men provide against difficulties before they arise; courageous men deal with them when they have arisen.",
    grc: "ἔλεγέ τε συνετῶν ἀνδρῶν, πρὶν γενέσθαι τὰ δυσχερῆ, προνοῆσαι ὅπως μὴ γένηται",
    en: "It is the part of prudent men, he said, before difficulties arise, to provide against their arising",
    ref: "1.77",
    certainty: "asserted",
    note: "The sentence continues into 1.78: 'and of courageous men to deal with them when they have arisen.'",
  },
  {
    id: "pittacus-dont-announce-plans",
    philosopher: "Pittacus",
    topic: "speech",
    gloss:
      "Do not announce your plans beforehand; if they fail, you will be laughed at.",
    grc: "ὃ μέλλεις πράττειν, μὴ πρόλεγε· ἀποτυχὼν γὰρ γελασθήσῃ.",
    en: "Do not announce your plans beforehand; for, if they fail, you will be laughed at.",
    ref: "1.78",
    certainty: "asserted",
  },
  {
    id: "pittacus-no-reproach-misfortune",
    philosopher: "Pittacus",
    topic: "fortune",
    gloss:
      "Never reproach anyone with a misfortune, for fear of Nemesis.",
    grc: "ἀτυχίαν μὴ ὀνειδίζειν, νέμεσιν αἰδούμενον.",
    en: "Never reproach any one with a misfortune, for fear of Nemesis.",
    ref: "1.78",
    certainty: "asserted",
  },
  {
    id: "pittacus-no-ill-friend-enemy",
    philosopher: "Pittacus",
    topic: "speech",
    gloss: "Speak no ill of a friend, nor even of an enemy.",
    grc: "φίλον μὴ λέγειν κακῶς, ἀλλὰ μηδὲ ἐχθρόν.",
    en: "Speak no ill of a friend, nor even of an enemy.",
    ref: "1.78",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------------- Bias
  {
    id: "bias-most-men-bad",
    philosopher: "Bias",
    topic: "wisdom",
    gloss: "'Most men are bad' (οἱ πλεῖστοι κακοί) - his signature apophthegm.",
    grc: "οἱ πλεῖστοι κακοί.",
    en: "Most men are bad.",
    ref: "1.88",
    certainty: "asserted",
  },
  {
    id: "bias-what-is-sweet-hope",
    philosopher: "Bias",
    topic: "fortune",
    gloss: "Asked what is sweet to men, he answered: hope.",
    grc: "Ἐρωτηθεὶς τί γλυκὺ ἀνθρώποις, ἐλπίς, ἔφη.",
    en: "Being asked What is sweet to men, he answered, Hope.",
    ref: "1.87",
    certainty: "asserted",
  },
  {
    id: "bias-love-friends",
    philosopher: "Bias",
    topic: "friendship",
    gloss: "Love your friends as if you might one day hate them.",
    grc: "φιλεῖν ὡς μισήσοντας",
    en: "to love their friends as if they would some day hate them",
    ref: "1.87",
    certainty: "asserted",
  },
  {
    id: "bias-ship-impious",
    philosopher: "Bias",
    topic: "religion",
    gloss:
      "In a storm among impious men crying to the gods, he told them to hush lest the gods notice them aboard.",
    grc: "σιγᾶτε, ἔφη, μὴ αἴσθωνται ὑμᾶς ἐνθάδε πλέοντας.",
    en: "Peace! said he, lest they hear and become aware that you are here in the ship.",
    ref: "1.86",
    certainty: "asserted",
  },
  {
    id: "bias-alyattes-onions",
    philosopher: "Bias",
    topic: "wit",
    gloss:
      "Invited to Alyattes' court after outwitting his siege: tell Alyattes to make his diet of onions - that is, to weep.",
    grc: "ἐγὼ δέ, φησίν, Ἀλυάττῃ κελεύω κρόμμυα ἐσθίειν, [ἴσον τῷ κλαίειν].",
    en: "Tell Alyattes, from me, to make his diet of onions, that is, to weep.",
    ref: "1.83",
    certainty: "reported",
  },
  {
    id: "bias-strength-nature",
    philosopher: "Bias",
    topic: "speech",
    gloss:
      "Bodily strength is nature's work; to speak for one's country's interests is the gift of soul and reason.",
    grc: "καὶ τὸ μὲν ἰσχυρὸν γενέσθαι τῆς φύσεως ἔργον· τὸ δὲ λέγειν δύνασθαι τὰ συμφέροντα τῇ πατρίδι ψυχῆς ἴδιον καὶ φρονήσεως.",
    en: "The growth of strength in man is nature’s work; but to set forth in speech the interests of one’s country is the gift of soul and reason.",
    ref: "1.86",
    certainty: "asserted",
  },
  {
    id: "bias-unfortunate-bear",
    philosopher: "Bias",
    topic: "fortune",
    gloss: "He who cannot bear misfortune is truly unfortunate.",
    grc: "ἔλεγε δὲ ἀτυχῆ εἶναι τὸν ἀτυχίαν μὴ φέροντα",
    en: "he who could not bear misfortune was truly unfortunate",
    ref: "1.86",
    certainty: "asserted",
  },
  {
    id: "bias-disease-soul",
    philosopher: "Bias",
    topic: "wisdom",
    gloss:
      "It is a disease of the soul to be enamoured of things impossible of attainment.",
    grc: "καὶ νόσον ψυχῆς τὸ τῶν ἀδυνάτων ἐρᾶν",
    en: "it is a disease of the soul to be enamoured of things impossible of attainment",
    ref: "1.86",
    certainty: "asserted",
  },
  {
    id: "bias-what-difficult-change",
    philosopher: "Bias",
    topic: "fortune",
    gloss:
      "What is difficult: nobly to endure a change for the worse.",
    grc: "ἐρωτηθεὶς τί δυσχερές, τὴν ἐπὶ τὸ χεῖρον, ἔφη, μεταβολὴν εὐγενῶς ἐνεγκεῖν.",
    en: "Being asked what is difficult, he replied, Nobly to endure a change for the worse.",
    ref: "1.86",
    certainty: "asserted",
  },
  {
    id: "bias-piety-silence",
    philosopher: "Bias",
    topic: "religion",
    gloss:
      "Asked by an impious man to define piety, he kept silent: 'because you are asking questions about what does not concern you.'",
    grc: "ἐρωτηθεὶς ὑπὸ ἀσεβοῦς ἀνθρώπου τί ποτέ ἐστιν εὐσέβεια, ἐσίγα. τοῦ δὲ τὴν αἰτίαν τῆς σιγῆς πυθομένου, σιωπῶ, ἔφη, ὅτι περὶ τῶν οὐδέν σοι προσηκόντων πυνθάνῃ.",
    en: "When an impious man asked him to define piety, he was silent; and when the other inquired the reason, I am silent, he replied, because you are asking questions about what does not concern you.",
    ref: "1.86",
    certainty: "asserted",
  },
  {
    id: "bias-enemies-dispute",
    philosopher: "Bias",
    topic: "friendship",
    gloss:
      "Better to judge a dispute between enemies than between friends: one enemy will become a friend, but one friend an enemy.",
    grc: "ἥδιον ἔλεγε δικάζειν μεταξὺ ἐχθρῶν ἢ φίλων· τῶν μὲν γὰρ φίλων πάντως ἐχθρὸν ἔσεσθαι τὸν ἕτερον, τῶν δὲ ἐχθρῶν τὸν ἕτερον φίλον.",
    en: "He said he would rather decide a dispute between two of his enemies than between two of his friends; for in the latter case he would be certain to make one of his friends his enemy, but in the former case he would make one of his enemies his friend.",
    ref: "1.87",
    certainty: "asserted",
  },
  {
    id: "bias-making-money",
    philosopher: "Bias",
    topic: "wealth",
    gloss:
      "What occupation gives most pleasure? Making money.",
    grc: "ἐρωτηθεὶς τί ποιῶν ἄνθρωπος τέρπεται, ἔφη, κερδαίνων.",
    en: "Asked what occupation gives a man most pleasure, he replied, Making money.",
    ref: "1.87",
    certainty: "asserted",
  },
  {
    id: "bias-measure-life",
    philosopher: "Bias",
    topic: "wisdom",
    gloss:
      "Measure life as if you had both a short and a long time to live.",
    grc: "ἔλεγέ τε τὸν βίον οὕτω μετρεῖν ὡς καὶ πολὺν καὶ ὀλίγον χρόνον βιωσομένους",
    en: "He advised men to measure life as if they had both a short and a long time to live",
    ref: "1.87",
    certainty: "asserted",
  },
  {
    id: "bias-slow-enterprise",
    philosopher: "Bias",
    topic: "wisdom",
    gloss:
      "Be slow to set about an enterprise, but persevere steadfastly once it is undertaken.",
    grc: "βραδέως ἐγχείρει τοῖς πραττομένοις· ὃ δʼ ἂν ἕλῃ, βεβαίως τηρῶν διάμενε.",
    en: "Be slow to set about an enterprise, but persevere in it steadfastly when once it is undertaken.",
    ref: "1.87",
    certainty: "asserted",
  },
  {
    id: "bias-persuasion-not-force",
    philosopher: "Bias",
    topic: "speech",
    gloss: "Gain your point by persuasion, not by force.",
    grc: "πείσας λαβέ, μὴ βιασάμενος.",
    en: "Gain your point by persuasion, not by force.",
    ref: "1.88",
    certainty: "asserted",
  },
  {
    id: "bias-wisdom-provision",
    philosopher: "Bias",
    topic: "wisdom",
    gloss:
      "Make wisdom your provision for the journey from youth to old age - a surer support than all other possessions.",
    grc: "ἐφόδιον ἀπὸ νεότητος εἰς γῆρας ἀναλάμβανε σοφίαν· βεβαιότερον γὰρ τοῦτο τῶν ἄλλων κτημάτων.",
    en: "Make wisdom your provision for the journey from youth to old age; for it is a more certain support than all other possessions.",
    ref: "1.88",
    certainty: "asserted",
  },
  // ----------------------------------------------------------------- Cleobulus
  {
    id: "cleobulus-educate-daughters",
    philosopher: "Cleobulus",
    topic: "education",
    gloss:
      "Daughters should be given in marriage maidens in years but women in wisdom - girls need educating too.",
    grc: "δεῖν συνοικίζειν τὰς θυγατέρας, παρθένους μὲν τὴν ἡλικίαν, τὸ δὲ φρονεῖν γυναῖκας",
    en: "we ought to give our daughters to their husbands maidens in years but women in wisdom",
    ref: "1.91",
    certainty: "asserted",
  },
  {
    id: "cleobulus-service-friend-enemy",
    philosopher: "Cleobulus",
    topic: "friendship",
    gloss:
      "Do a friend a service to bind him closer, an enemy to make a friend of him.",
    grc: "τὸν φίλον δεῖν εὐεργετεῖν, ὅπως μᾶλλον ᾖ φίλος· τὸν δὲ ἐχθρὸν φίλον ποιεῖν.",
    en: "we should render a service to a friend to bind him closer to us, and to an enemy in order to make a friend of him",
    ref: "1.91",
    certainty: "asserted",
  },
  {
    id: "cleobulus-listeners",
    philosopher: "Cleobulus",
    topic: "speech",
    gloss: "Be a listener rather than a talker.",
    grc: "φιλήκοον εἶναι μᾶλλον ἢ φιλόλαλον",
    en: "to be listeners rather than talkers",
    ref: "1.92",
    certainty: "asserted",
  },
  {
    id: "cleobulus-leave-house-inquire",
    philosopher: "Cleobulus",
    topic: "wisdom",
    gloss:
      "On leaving the house, ask what you mean to do; on returning, ask what you have effected.",
    grc: "καὶ ὅταν τις ἐξίῃ τῆς οἰκίας, ζητείτω πρότερον τί μέλλει πράσσειν· καὶ ὅταν εἰσέλθῃ πάλιν, ζητείτω τί ἔπραξε.",
    en: "When anyone leaves his house, let him first inquire what he means to do; and on his return let him ask himself what he has effected.",
    ref: "1.92",
    certainty: "asserted",
  },
  {
    id: "cleobulus-master-pleasure",
    philosopher: "Cleobulus",
    topic: "pleasure",
    gloss: "Do not be overcome by pleasure.",
    grc: "ἡδονῆς κρατεῖν",
    en: "not to be overcome by pleasure",
    ref: "1.92",
    certainty: "asserted",
  },
  {
    id: "cleobulus-marry-equals",
    philosopher: "Cleobulus",
    topic: "wisdom",
    gloss:
      "Mate with one of your own rank: marry above you and her kinsfolk become your masters.",
    grc: "γαμεῖν ἐκ τῶν ὁμοίων",
    en: "Mate with one of your own rank; for if you take a wife who is superior to you, her kinsfolk will become your masters.",
    ref: "1.92",
    certainty: "asserted",
    note: "The Greek sentence runs over the section boundary into 1.93 ('δεσπότας κτήσῃ τοὺς συγγενέας'); only the opening clause falls in 1.92.",
  },
  {
    id: "cleobulus-arrogant-prosperity",
    philosopher: "Cleobulus",
    topic: "fortune",
    gloss:
      "Do not be arrogant in prosperity; if you fall into poverty, do not humble yourself.",
    grc: "εὐτυχῶν μὴ ἴσθι ὑπερήφανος· ἀπορήσας μὴ ταπεινοῦ.",
    en: "Do not be arrogant in prosperity; if you fall into poverty, do not humble yourself.",
    ref: "1.93",
    certainty: "asserted",
  },
  {
    id: "cleobulus-bear-fortune",
    philosopher: "Cleobulus",
    topic: "fortune",
    gloss: "Know how to bear the changes of fortune with nobility.",
    grc: "τὰς μεταβολὰς τῆς τύχης γενναίως ἐπίστασο φέρειν.",
    en: "Know how to bear the changes of fortune with nobility.",
    ref: "1.93",
    certainty: "asserted",
  },
  {
    id: "cleobulus-moderation-best",
    philosopher: "Cleobulus",
    topic: "virtue",
    gloss: "His apophthegm: Moderation is best.",
    grc: "Ἀπεφθέγξατο· μέτρον ἄριστον.",
    en: "His apophthegm was: Moderation is best.",
    ref: "1.93",
    certainty: "asserted",
  },
  // ----------------------------------------------------------------- Periander
  {
    id: "periander-practice",
    philosopher: "Periander",
    topic: "wisdom",
    gloss: "'Practice makes perfect' (μελέτη τὸ πᾶν) - his apophthegm.",
    grc: "Μελέτη τὸ πᾶν.",
    en: "Practice makes perfect.",
    ref: "1.99",
    certainty: "asserted",
  },
  {
    id: "periander-loyalty-bodyguard",
    philosopher: "Periander",
    topic: "politics",
    gloss:
      "Tyrants who would be safe should guard themselves with loyalty, not arms.",
    grc: "τοὺς μέλλοντας ἀσφαλῶς τυραννήσειν τῇ εὐνοίᾳ δορυφορεῖσθαι, καὶ μὴ τοῖς ὅπλοις.",
    en: "those tyrants who intend to be safe should make loyalty their bodyguard, not arms",
    ref: "1.97",
    certainty: "asserted",
  },
  {
    id: "periander-honours-immortal",
    philosopher: "Periander",
    topic: "fame",
    gloss: "Pleasures are transient, honours immortal.",
    grc: "αἱ μὲν ἡδοναὶ φθαρταί, αἱ δὲ τιμαὶ ἀθάνατοι",
    en: "Pleasures are transient, honours are immortal.",
    ref: "1.97",
    certainty: "asserted",
  },
  {
    id: "periander-never-for-money",
    philosopher: "Periander",
    topic: "wealth",
    gloss:
      "Never do anything for money; leave gain to trades pursued for gain.",
    grc: "Τούτου ἐστὶ καὶ τὸ Μηδὲν χρημάτων ἕνεκα πράττειν· δεῖν γὰρ τὰ κερδαντὰ κερδαίνειν.",
    en: "To him belongs the maxim: Never do anything for money; leave gain to trades pursued for gain.",
    ref: "1.97",
    certainty: "asserted",
  },
  {
    id: "periander-why-tyrant",
    philosopher: "Periander",
    topic: "politics",
    gloss:
      "Why remain tyrant? Because it is as dangerous to retire voluntarily as to be dispossessed.",
    grc: "καί ποτε ἐρωτηθεὶς διὰ τί τυραννεῖ, ἔφη, ὅτι καὶ τὸ ἑκουσίως ἀποστῆναι καὶ τὸ ἀφαιρεθῆναι κίνδυνον φέρει.",
    en: "When some one asked him why he was tyrant, he replied, Because it is as dangerous to retire voluntarily as to be dispossessed.",
    ref: "1.97",
    certainty: "asserted",
  },
  {
    id: "periander-rest-beautiful",
    philosopher: "Periander",
    topic: "wisdom",
    gloss: "Rest is beautiful.",
    grc: "καλὸν ἡσυχία",
    en: "Rest is beautiful.",
    ref: "1.97",
    certainty: "asserted",
  },
  {
    id: "periander-gain-ignoble",
    philosopher: "Periander",
    topic: "wealth",
    gloss: "Gain is ignoble.",
    grc: "κέρδος αἰσχρόν",
    en: "Gain is ignoble.",
    ref: "1.97",
    certainty: "asserted",
  },
  {
    id: "periander-democracy-better",
    philosopher: "Periander",
    topic: "politics",
    gloss: "Democracy is better than tyranny.",
    grc: "δημοκρατία κρεῖττον τυραννίδος",
    en: "Democracy is better than tyranny.",
    ref: "1.97",
    certainty: "asserted",
  },
  {
    id: "periander-moderate-prosperity",
    philosopher: "Periander",
    topic: "fortune",
    gloss: "Be moderate in prosperity, prudent in adversity.",
    grc: "εὐτυχῶν μὲν μέτριος ἴσθι, δυστυχῶν δὲ φρόνιμος",
    en: "Be moderate in prosperity, prudent in adversity.",
    ref: "1.98",
    certainty: "asserted",
  },
  {
    id: "periander-same-to-friends",
    philosopher: "Periander",
    topic: "friendship",
    gloss:
      "Be the same to your friends in prosperity and in adversity.",
    grc: "φίλοις εὐτυχοῦσι καὶ ἀτυχοῦσιν ὁ αὐτὸς ἴσθι",
    en: "Be the same to your friends whether they are in prosperity or in adversity.",
    ref: "1.98",
    certainty: "asserted",
  },
  {
    id: "periander-agreement-stick",
    philosopher: "Periander",
    topic: "virtue",
    gloss: "Whatever agreement you make, stick to it.",
    grc: "ὃ ἂν ὁμολογήσῃς, διατήρει",
    en: "Whatever agreement you make, stick to it.",
    ref: "1.98",
    certainty: "asserted",
  },
  {
    id: "periander-betray-no-secret",
    philosopher: "Periander",
    topic: "speech",
    gloss: "Betray no secret.",
    grc: "λόγων ἀπορρήτων ἐκφορὰν μὴ ποιοῦ",
    en: "Betray no secret.",
    ref: "1.98",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Anacharsis
  {
    id: "anacharsis-reputation-envy",
    philosopher: "Anacharsis",
    topic: "fame",
    gloss:
      "Struck by his brother's arrow: my reputation carried me safe through Greece, but the envy it excited at home has been my ruin.",
    grc: "εἰπὼν διὰ μὲν τὸν λόγον ἐκ τῆς Ἑλλάδος σωθῆναι, διὰ δὲ τὸν φθόνον ἐν τῇ οἰκείᾳ ἀπολέσθαι.",
    en: "My reputation carried me safe through Greece, but the envy it excited at home has been my ruin.",
    ref: "1.102",
    certainty: "asserted",
    note: "D.L. adds that 'in some accounts it is said that he was slain while performing Greek rites.'",
  },
  {
    id: "anacharsis-vine-three-grapes",
    philosopher: "Anacharsis",
    topic: "pleasure",
    gloss:
      "The vine bears three kinds of grapes: pleasure, intoxication, and disgust.",
    grc: "Οὗτος τὴν ἄμπελον εἶπε τρεῖς φέρειν βότρυς· τὸν πρῶτον ἡδονῆς· τὸν δεύτερον μέθης· τὸν τρίτον ἀνδίας.",
    en: "It was a saying of his that the vine bore three kinds of grapes: the first of pleasure, the next of intoxication, and the third of disgust.",
    ref: "1.103",
    certainty: "asserted",
  },
  {
    id: "anacharsis-experts-judges",
    philosopher: "Anacharsis",
    topic: "wit",
    gloss:
      "He wondered why in Greece experts contend in the games and non-experts award the prizes.",
    grc: "θαυμάζειν δὲ ἔφη πῶς παρὰ τοῖς Ἕλλησιν ἀγωνίζονται μὲν οἱ τεχνῖται, κρίνουσι δὲ οἱ μὴ τεχνῖται.",
    en: "He said he wondered why in Greece experts contend in the games and non-experts award the prizes.",
    ref: "1.103",
    certainty: "asserted",
  },
  {
    id: "anacharsis-avoid-toper",
    philosopher: "Anacharsis",
    topic: "pleasure",
    gloss:
      "How to avoid becoming a toper: keep before your eyes the disgraceful exhibition made by the drunkard.",
    grc: "ἐρωτηθεὶς πῶς οὐκ ἂν γένοιτό τις φιλοπότης, εἰ πρὸ ὀφθαλμῶν, εἶπεν, ἔχοι τὰς τῶν μεθυόντων ἀσχημοσύνας.",
    en: "Being asked how one could avoid becoming a toper, he answered, By keeping before your eyes the disgraceful exhibition made by the drunkard.",
    ref: "1.103",
    certainty: "asserted",
  },
  {
    id: "anacharsis-athletes-bruising",
    philosopher: "Anacharsis",
    topic: "wit",
    gloss:
      "He was surprised that Greek lawgivers punish outrage yet honour athletes for bruising one another.",
    grc: "θαυμάζειν τε ἔλεγε πῶς οἱ Ἕλληνες νομοθετοῦντες κατὰ τῶν ὑβριζόντων, τοὺς ἀθλητὰς τιμῶσιν ἐπὶ τῷ τύπτειν ἀλλήλους.",
    en: "he expressed surprise that the Greek lawgivers should impose penalties on wanton outrage, while they honour athletes for bruising one another",
    ref: "1.103",
    certainty: "asserted",
  },
  {
    id: "anacharsis-four-fingers-death",
    philosopher: "Anacharsis",
    topic: "death",
    gloss:
      "Learning the ship's side was four fingers thick: the passengers are just so far from death.",
    grc: "μαθὼν τέτταρας δακτύλους εἶναι τὸ πάχος τῆς νεώς, τοσοῦτον ἔφη τοῦ θανάτου τοὺς πλέοντας ἀπέχειν.",
    en: "After ascertaining that the ship’s side was four fingers’ breadth in thickness, he remarked that the passengers were just so far from death.",
    ref: "1.103",
    certainty: "asserted",
  },
  {
    id: "anacharsis-oil-madness",
    philosopher: "Anacharsis",
    topic: "wit",
    gloss:
      "Oil is a drug producing madness - athletes anointed with it are maddened against each other.",
    grc: "Τὸ ἔλαιον μανίας φάρμακον ἔλεγε διὰ τὸ ἀλειφομένους τοὺς ἀθλητὰς ἐπιμαίνεσθαι ἀλλήλοις.",
    en: "Oil he called a drug which produced madness, because the athletes when they anoint themselves with it are maddened against each other.",
    ref: "1.104",
    certainty: "asserted",
  },
  {
    id: "anacharsis-falsehood-retail",
    philosopher: "Anacharsis",
    topic: "speech",
    gloss:
      "How is it the Greeks prohibit falsehood, yet obviously tell falsehoods in retail trade?",
    grc: "πῶς, ἔλεγεν, ἀπαγορεύοντες τὸ ψεύδεσθαι ἐν ταῖς καπηλείαις φανερῶς ψεύδονται;",
    en: "How is it, he asked, that the Greeks prohibit falsehood and yet obviously tell falsehoods in retail trade?",
    ref: "1.104",
    certainty: "asserted",
  },
  {
    id: "anacharsis-bridle-speech",
    philosopher: "Anacharsis",
    topic: "speech",
    gloss:
      "The inscription on his statues: bridle speech, gluttony, and sensuality.",
    grc: "ἐπιγράφεται δὲ αὐτοῦ ταῖς εἰκόσι· γλώσσης, γαστρός, αἰδοίων κρατεῖν.",
    en: "The inscription on his statues is: Bridle speech, gluttony, and sensuality.",
    ref: "1.104",
    certainty: "asserted",
  },
  {
    id: "anacharsis-flutes-vines",
    philosopher: "Anacharsis",
    topic: "wit",
    gloss: "Are there flutes in Scythia? No - nor yet vines.",
    grc: "ἐρωτηθεὶς εἰ εἰσὶν ἐν Σκύθαις αὐλοί, εἶπεν, ἀλλʼ οὐδὲ ἄμπελοι.",
    en: "Being asked if there were flutes in Scythia, he replied, No, nor yet vines.",
    ref: "1.104",
    certainty: "asserted",
  },
  {
    id: "anacharsis-safest-ships",
    philosopher: "Anacharsis",
    topic: "wit",
    gloss: "The safest vessels: those which have been hauled ashore.",
    grc: "ἐρωτηθεὶς τίνα τῶν πλοίων εἰσὶν ἀσφαλέστερα, ἔφη, τὰ νενεωλκημένα.",
    en: "To the question what vessels were the safest his reply was, Those which have been hauled ashore.",
    ref: "1.104",
    certainty: "asserted",
  },
  {
    id: "anacharsis-smoke-mountains",
    philosopher: "Anacharsis",
    topic: "wit",
    gloss:
      "The strangest thing in Greece: they leave the smoke on the mountains and convey the fuel into the city.",
    grc: "καὶ τοῦτο ἔφη θαυμασιώτατον ἑωρακέναι παρὰ τοῖς Ἕλλησιν, ὅτι τὸν μὲν καπνὸν ἐν τοῖς ὄρεσι καταλείπουσι, τὰ δὲ ξύλα εἰς τὴν πόλιν κομίζουσιν.",
    en: "And he declared the strangest thing he had seen in Greece to be that they leave the smoke on the mountains and convey the fuel into the city.",
    ref: "1.104",
    certainty: "asserted",
  },
  {
    id: "anacharsis-living-or-dead",
    philosopher: "Anacharsis",
    topic: "death",
    gloss:
      "Which are more, the living or the dead? In which category do you place those at sea?",
    grc: "ἐρωτηθεὶς πότεροι πλείους εἰσίν, οἱ ζῶντες ἢ οἱ νεκροί, ἔφη, τοὺς οὖν πλέοντας ποῦ τίθης;",
    en: "When some one inquired which were more in number, the living or the dead, he rejoined, In which category, then, do you place those who are on the seas?",
    ref: "1.104",
    certainty: "asserted",
  },
  {
    id: "anacharsis-scythian-disgrace",
    philosopher: "Anacharsis",
    topic: "wit",
    gloss:
      "Reproached as a Scythian: granted my country is a disgrace to me, you are a disgrace to your country.",
    grc: "ὀνειδιζόμενος ὑπὸ Ἀττικοῦ ὅτι Σκύθης ἐστίν, ἔφη, ἀλλʼ ἐμοῦ μὲν ὄνειδος ἡ πατρίς, σὺ δὲ τῆς πατρίδος.",
    en: "When some Athenian reproached him with being a Scythian, he replied, Well, granted that my country is a disgrace to me, you are a disgrace to your country.",
    ref: "1.104",
    certainty: "asserted",
  },
  {
    id: "anacharsis-tongue-good-bad",
    philosopher: "Anacharsis",
    topic: "speech",
    gloss:
      "What among men is both good and bad? The tongue.",
    grc: "ἐρωτηθεὶς τί ἐστιν ἐν ἀνθρώποις ἀγαθόν τε καὶ φαῦλον, ἔφη, γλῶσσα.",
    en: "To the question, What among men is both good and bad? his answer was The tongue.",
    ref: "1.105",
    certainty: "asserted",
  },
  {
    id: "anacharsis-one-friend-worth",
    philosopher: "Anacharsis",
    topic: "friendship",
    gloss:
      "Better one friend of great worth than many friends worth nothing at all.",
    grc: "κρεῖττον ἔλεγεν ἕνα φίλον ἔχειν πολλοῦ ἄξιον ἢ πολλοὺς μηδενὸς ἀξίους.",
    en: "He said it was better to have one friend of great worth than many friends worth nothing at all.",
    ref: "1.105",
    certainty: "asserted",
  },
  {
    id: "anacharsis-market-deceive",
    philosopher: "Anacharsis",
    topic: "wealth",
    gloss:
      "The market: a place set apart where men may deceive and overreach one another.",
    grc: "τὴν ἀγορὰν ὡρισμένον ἔφη τόπον εἰς τὸ ἀλλήλους ἀπατᾶν καὶ πλεονεκτεῖν.",
    en: "He defined the market as a place set apart where men may deceive and overreach one another.",
    ref: "1.105",
    certainty: "asserted",
  },
  {
    id: "anacharsis-boy-wine-water",
    philosopher: "Anacharsis",
    topic: "wit",
    gloss:
      "To a boy insulting him over the wine: if you cannot carry your liquor young, you will carry water when old.",
    grc: "ὑπὸ μειρακίου παρὰ πότον ὑβρισθεὶς ἔφη, μειράκιον, ἐὰν νέος ὢν τὸν οἶνον οὐ φέρῃς, γέρων γενόμενος ὕδωρ οἴσεις.",
    en: "When insulted by a boy over the wine he said, If you cannot carry your liquor when you are young, boy, you will be a water carrier when you are old.",
    ref: "1.105",
    certainty: "asserted",
  },
  // --------------------------------------------------------------------- Myson
  {
    id: "myson-plough-repair",
    philosopher: "Myson",
    topic: "wit",
    gloss:
      "Found fitting a share to a plough in summer - 'this is not the season for the plough' - he replied it was just the time to repair it.",
    grc: "καὶ μάλα, εἶπεν, ὥστε ἐπισκευάζειν.",
    en: "It is just the time to repair it, was the reply.",
    ref: "1.106",
    certainty: "reported",
    to: "Anacharsis",
    note: "D.L. introduces the anecdote with λέγεται ('we are told'); Anacharsis had sought Myson out after the Pythian oracle named him wiser.",
  },
  {
    id: "myson-laughing-alone",
    philosopher: "Myson",
    topic: "wit",
    gloss:
      "Seen laughing to himself in a lonely spot and asked why he laughed with no one near: 'That is just the reason.'",
    grc: "ὀφθῆναι γοῦν ἐν Λακεδαίμονι μόνον ἐπʼ ἐρημίας γελῶντα· ἄφνω δέ τινος ἐπιστάντος καὶ πυθομένου διὰ τί μηδενὸς παρόντος γελᾷ, φάναι, διʼ αὐτὸ τοῦτο.",
    en: "he was seen in Lacedaemon laughing to himself in a lonely spot; and when some one suddenly appeared and asked him why he laughed when no one was near, he replied, That is just the reason",
    ref: "1.108",
    certainty: "reported",
    accordingTo: "Aristoxenus",
  },
  {
    id: "myson-facts-not-arguments",
    philosopher: "Myson",
    topic: "wisdom",
    gloss:
      "Investigate arguments by the light of facts, not facts by the light of arguments - facts are not put together to fit arguments.",
    grc: "Ἔφασκε δὲ μὴ ἐκ τῶν λόγων τὰ πράγματα, ἀλλʼ ἐκ τῶν πραγμάτων τοὺς λόγους ζητεῖν· οὐ γὰρ ἕνεκα τῶν λόγων τὰ πράγματα συντελεῖσθαι, ἀλλʼ ἕνεκα τῶν πραγμάτων τοὺς λόγους.",
    en: "He used to say we should not investigate facts by the light of arguments, but arguments by the light of facts; for the facts were not put together to fit the arguments, but the arguments to fit the facts.",
    ref: "1.108",
    certainty: "asserted",
  },
];
