/**
 * Curated sayings & apophthegms from Book 7 of Diogenes Laertius' Lives
 * (the Stoics), cited to Hicks section ids (book.section). See sayings.ts for
 * the model and curation rules. Source-internal: every `en` is a verbatim
 * excerpt of its cited section.
 */
import type { Saying } from "../sayings";

export const BOOK7_SAYINGS: Saying[] = [
  // ----------------------------------------------------------- Zeno of Citium
  {
    id: "zeno-citium-shipwreck",
    philosopher: "Zeno of Citium",
    topic: "fortune",
    gloss: "Ruined by shipwreck, he said the wreck had made his fortune by driving him to philosophy.",
    grc: "νῦν εὐπλόηκα, ὅτε νεναυάγηκα.",
    en: "I made a prosperous voyage when I suffered shipwreck.",
    ref: "7.4",
    certainty: "reported",
  },
  {
    id: "zeno-citium-two-ears-one-mouth",
    philosopher: "Zeno of Citium",
    topic: "speech",
    gloss: "We have two ears and one mouth so as to listen more and speak less.",
    grc: "διὰ τοῦτο, εἶπε, δύο ὦτα ἔχομεν, στόμα δὲ ἕν, ἵνα πλείονα μὲν ἀκούωμεν, ἥττονα δὲ λέγωμεν.",
    en: "The reason why we have two ears and only one mouth is that we may listen the more and talk the less.",
    ref: "7.23",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-friend-second-self",
    philosopher: "Zeno of Citium",
    topic: "friendship",
    gloss: "Asked what a friend is, he answered: a second self.",
    grc: "ἐρωτηθεὶς τίς ἐστι φίλος, ἄλλος, ἔφη, ἐγώ.",
    en: "To the question Who is a friend? his answer was, A second self",
    ref: "7.23",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-seize-by-ears",
    philosopher: "Zeno of Citium",
    topic: "wisdom",
    gloss: "Dragged by his cloak from Stilpo, he said a philosopher is seized only by persuading his ears.",
    grc: "ὦ Κράτης, λαβὴ φιλοσόφων ἐστὶν ἐπιδέξιος ἡ διὰ τῶν ὤτων· πείσας οὖν ἕλκε τούτων· εἰ δέ με βιάζῃ, τὸ μὲν σῶμα παρὰ σοὶ ἔσται, ἡ δὲ ψυχὴ παρὰ Στίλπωνι.",
    en: "The right way to seize a philosopher, Crates, is by the ears: persuade me then and drag me off by them; but, if you use violence, my body will be with you, but my mind with Stilpo.",
    ref: "7.24",
    to: "Crates of Thebes",
    certainty: "reported",
    accordingTo: "Apollonius of Tyre",
  },
  {
    id: "zeno-citium-arrogance",
    philosopher: "Zeno of Citium",
    topic: "virtue",
    gloss: "Nothing is more unbecoming than arrogance, above all in the young.",
    grc: "πάντων ἔλεγεν ἀπρεπέστερον εἶναι τὸν τῦφον, καὶ μάλιστα ἐπὶ τῶν νέων.",
    en: "Nothing, he declared, was more unbecoming than arrogance, especially in the young.",
    ref: "7.22",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-well-being-little",
    philosopher: "Zeno of Citium",
    topic: "virtue",
    gloss: "Well-being is built up little by little, and is no little thing.",
    grc: "τὸ εὖ γίνεσθαι μὲν παρὰ μικρόν, οὐ μὴν μικρὸν εἶναι.",
    en: "Well-being is attained by little and little, and nevertheless it is no little thing itself.",
    ref: "7.26",
    certainty: "disputed",
    alsoAttributedTo: "Socrates",
    note: "D.L.: 'Others attribute this to Socrates.'",
  },
  {
    id: "zeno-citium-mud-mirror",
    philosopher: "Zeno of Citium",
    topic: "wit",
    gloss: "Watching a miser pick his way across a watercourse: he rightly looks askance at the mud, for he cannot see his face in it.",
    grc: "δικαίως, εἶπεν, ὑφορᾷ τὸν πηλόν· οὐ γὰρ ἔστιν ἐν αὐτῷ κατοπτρίσασθαι.",
    en: "With good reason, quoth Zeno, he looks askance at the mud, for he can’t see his face in it.",
    ref: "7.17",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-cynic-impudence",
    philosopher: "Zeno of Citium",
    topic: "wit",
    gloss: "Refusing oil to a begging Cynic, he bade him consider which of the two was the more impudent.",
    grc: "ἀπελθόντα μέντοι ἐκέλευσε σκέψασθαι ὁπότερος εἰη ἀναιδέστερος.",
    en: "However, as the man went away, Zeno bade him consider which of the two was the more impudent.",
    ref: "7.17",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-inflammation-repose",
    philosopher: "Zeno of Citium",
    topic: "virtue",
    gloss: "Rising from beside a youth he loved, he told Cleanthes: the best cure for inflammation is repose.",
    grc: "ἔφη καὶ τῶν ἰατρῶν ἀκούω τῶν ἀγαθῶν, κράτιστον εἶναι φάρμακον πρὸς τὰ φλεγμαίνοντα ἡσυχίαν.",
    en: "Good physicians tell us, said he, that the best cure for inflammation is repose.",
    ref: "7.17",
    to: "Cleanthes",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-neighbour-knee",
    philosopher: "Zeno of Citium",
    topic: "wit",
    gloss: "Nudging with his knee a guest who had kicked the man below him: how do you think your neighbour liked what you did to him?",
    grc: "τί οὖν 〈ἔφη〉 οἴει τὸν ὑποκάτω σου πάσχειν ὑπὸ σοῦ;",
    en: "How do you think your neighbour liked what you did to him?",
    ref: "7.17",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-schoolmasters-boys",
    philosopher: "Zeno of Citium",
    topic: "wit",
    gloss: "To a lover of boys: like schoolmasters, such men lose their common sense by spending all their time with boys.",
    grc: "πρὸς δὲ τὸν φιλόπαιδα οὔτε τοὺς διδασκάλους ἔφη φρένας ἔχειν, ἀεὶ διατρίβοντας ἐν παιδαρίοις, οὔτʼ ἐκείνους.",
    en: "Just as schoolmasters lose their common-sense by spending all their time with boys, so it is with people like you.",
    ref: "7.18",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-alexander-coinage",
    philosopher: "Zeno of Citium",
    topic: "speech",
    gloss: "Over-polished expressions are like Alexander's coinage: beautiful and well-rounded, but none the better for it.",
    grc: "ἔφασκε δὲ τοὺς μὲν τῶν ἀσολοίκων λόγους καὶ ἀπηρτισμένους ὁμοίους εἶναι τῷ ἀργυρίῳ τῷ Ἀλεξανδρίνῳ· εὐοφθάλμους μὲν καὶ περιγεγραμμένους καθὰ καὶ τὸ νόμισμα, οὐδὲν δὲ διὰ ταῦτα βελτίονας.",
    en: "He used to say that the very exact expressions used by those who avoided solecisms were like the coins struck by Alexander: they were beautiful in appearance and well-rounded like the coins, but none the better on that account.",
    ref: "7.18",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-ariston-begotten-drunk",
    philosopher: "Zeno of Citium",
    topic: "wit",
    gloss: "To his headstrong pupil Ariston, discoursing at length without inspiration: your father must have been drunk when he begat you.",
    grc: "ἀδύνατον, εἰπεῖν, εἰ μή σε ὁ πατὴρ μεθύων ἐγέννησεν",
    en: "Your father, said he, must have been drunk when he begat you.",
    ref: "7.18",
    to: "Ariston of Chios",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-gourmand-fish",
    philosopher: "Zeno of Citium",
    topic: "wit",
    gloss: "Seizing the whole fish before a greedy table companion: what must those who live with you feel every day, if you cannot bear my gourmandise once?",
    grc: "τί οὖν, ἔφη, τοὺς συμβιωτὰς οἴει πάσχειν καθʼ ἡμέραν, εἰ σὺ μίαν μὴ δύνασαι ἐνεγκεῖν τὴν ἐμὴν ὀψοφαγίαν;",
    en: "What do you suppose, said he, those who live with you feel every day, if you cannot put up with my gourmandise in this single instance?",
    ref: "7.19",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-youth-mirror",
    philosopher: "Zeno of Citium",
    topic: "education",
    gloss: "He led an over-curious youth to a mirror and asked whether such questions became anyone who looked like that.",
    grc: "προσήγαγε πρὸς κάτοπτρον καὶ ἐκέλευσεν ἐμβλέψαι· ἔπειτʼ ἠρώτησεν εἰ δοκεῖ αὐτῷ ἁρμόττοντα εἶναι 〈τῇ〉 ὄψει τοιαύτῃ ζητήματα.",
    en: "Zeno led him to a mirror, and bade him look in it; after which he inquired if he thought it became anyone who looked like that to ask such questions.",
    ref: "7.19",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-antisthenes-good-things",
    philosopher: "Zeno of Citium",
    topic: "virtue",
    gloss: "To a critic of Antisthenes: are you not ashamed to pick out his faults and suppress his good things?",
    grc: "εἶτʼ οὐκ αἰσχύνῃ, ἔφη, εἰ μέν τι κακὸν ἦν εἰρημένον [ὑπʼ Ἀντισθένους], τοῦτʼ ἐκλεγόμενος καὶ μνημονεύων, εἰ δέ τι καλόν, οὐδʼ ἐπιβαλλόμενος κατέχειν;",
    en: "Then are you not ashamed, quoth he, to pick out and mention anything wrong said by Antisthenes, while you suppress his good things without giving them a thought?",
    ref: "7.19",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-syllables-clipped",
    philosopher: "Zeno of Citium",
    topic: "speech",
    gloss: "Told the philosophers' chain-arguments seemed curt: quite right - the very syllables ought to be clipped if possible.",
    grc: "λέγεις, εἶπε, τἀληθῆ· δεῖ μέντοι καὶ τὰς συλλαβὰς αὐτῶν βραχείας εἶναι, εἰ δυνατόν.",
    en: "You are quite right; indeed, the very syllables ought, if possible, to be clipped.",
    ref: "7.20",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-actors-voice",
    philosopher: "Zeno of Citium",
    topic: "speech",
    gloss: "In conversation be earnest like actors - loud voice and great strength - but do not stretch the mouth wide like a chatterbox.",
    grc: "δεῖν δʼ ἔφη τόνῳ διαλεγόμενον ὥσπερ τοὺς ὑποκριτὰς τὴν μὲν φωνὴν καὶ τὴν δύναμιν μεγάλην ἔχειν, τὸ μέντοι στόμα μὴ διέλκειν· ὃ ποιεῖν τοὺς πολλὰ μὲν λαλοῦντας, ἀδύνατα δέ.",
    en: "He said that when conversing we ought to be earnest and, like actors, we should have a loud voice and great strength; but we ought not to open the mouth too wide, which is what your senseless chatterbox does.",
    ref: "7.20",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-telling-periods",
    philosopher: "Zeno of Citium",
    topic: "speech",
    gloss: "Good speech should leave the hearer no leisure even to take notes - absorbed in the discourse itself, not pausing to admire it.",
    grc: "τοῖς εὖ λεγομένοις οὐκ ἔφη δεῖν καταλείπεσθαι τόπον ὥσπερ τοῖς ἀγαθοῖς τεχνίταις εἰς τὸ θεάσασθαι, τοὐναντίον δὲ τὸν ἀκούοντα οὕτω πρὸς τοῖς λεγομένοις γίνεσθαι ὥστε μὴ λαμβάνειν χρόνον εἰς τὴν ἐπισημείωσιν.",
    en: "Telling periods, he said, unlike the works of good craftsmen, should need no pause for the contemplation of their excellences; on the contrary, the hearer should be so absorbed in the discourse itself as to have no leisure even to take notes.",
    ref: "7.20",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-ears-into-tongue",
    philosopher: "Zeno of Citium",
    topic: "speech",
    gloss: "To a young man who talked a good deal: your ears have slid down and merged in your tongue.",
    grc: "τὰ ὦτά σου εἰς τὴν γλῶτταν συνερρύηκεν.",
    en: "Your ears have slid down and merged in your tongue.",
    ref: "7.21",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-hapless-fair-youths",
    philosopher: "Zeno of Citium",
    topic: "wit",
    gloss: "To the fair youth who held that the wise man would not fall in love: then who is more hapless than you fair youths?",
    grc: "οὐδέν, ἔφη, ὑμῶν ἀθλιώτερον ἔσεσθαι τῶν καλῶν.",
    en: "Then who can be more hapless than you fair youths?",
    ref: "7.21",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-philosophers-mostly-unwise",
    philosopher: "Zeno of Citium",
    topic: "wisdom",
    gloss: "Even of philosophers the greater number are in most things unwise, and about small and casual things quite ignorant.",
    grc: "ἔλεγε δὲ καὶ τῶν φιλοσόφων τοὺς πλείστους τὰ μὲν πολλὰ ἀσόφους εἶναι, τὰ δὲ μικρὰ καὶ τυχηρὰ ἀμαθεῖς.",
    en: "He used to say that even of philosophers the greater number were in most things unwise, while about small and casual things they were quite ignorant.",
    ref: "7.21",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-saucy-youth",
    philosopher: "Zeno of Citium",
    topic: "wit",
    gloss: "To a youth talking saucily: I would rather not tell you what I am thinking, my lad.",
    grc: "οὐκ ἂν εἴποιμι, ἔφη, μειράκιον, ἃ ἐπέρχεταί μοι.",
    en: "I would rather not tell you what I am thinking, my lad.",
    ref: "7.21",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-mind-not-words",
    philosopher: "Zeno of Citium",
    topic: "education",
    gloss: "Remember not the words and expressions but exercise the mind in profiting by what is heard, not tasting it like a well-cooked dish.",
    grc: "μὴ τὰς φωνὰς καὶ τὰς λέξεις ἀπομνημονεύειν, ἀλλὰ περὶ τὴν διάθεσιν τῆς χρείας τὸν νοῦν ἀσχολεῖσθαι, μὴ ὥσπερ ἕψησίν τινα ἢ σκευασίαν ἀναλαμβάνοντας.",
    en: "He used also to say that it was not the words and expressions that we ought to remember, but we should exercise our mind in disposing to advantage of what we hear, instead of, as it were, tasting a well-cooked dish or well-dressed meal.",
    ref: "7.22",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-conceit-and-time",
    philosopher: "Zeno of Citium",
    topic: "education",
    gloss: "Nothing is so fatal to mastering the sciences as conceit, and nothing do we need so much as time.",
    grc: "Ἔλεγε δὲ μηδὲν εἶναι τῆς οἰήσεως ἀλλοτριώτερον πρὸς κατάληψιν τῶν ἐπιστημῶν, μηδενός θʼ ἡμᾶς οὕτως εἶναι ἐνδεεῖς ὡς χρόνου.",
    en: "if we want to master the sciences there is nothing so fatal as conceit, and again there is nothing we stand so much in need of as time.",
    ref: "7.23",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-fated-to-be-beaten",
    philosopher: "Zeno of Citium",
    topic: "wit",
    gloss: "To the slave who pleaded it was his fate to steal: yes, and to be beaten too.",
    grc: "δοῦλον ἐπὶ κλοπῇ, φασίν, ἐμαστίγου· τοῦ δʼ εἰπόντος, εἵμαρτό μοι κλέψαι, ἔφη, καὶ δαρῆναι.",
    en: "when the latter pleaded that it was his fate to steal, Yes, and to be beaten too, said Zeno.",
    ref: "7.23",
    certainty: "reported",
  },
  {
    id: "zeno-citium-beauty-flower-chastity",
    philosopher: "Zeno of Citium",
    topic: "virtue",
    gloss: "Beauty he called the flower of chastity - or, by other accounts, chastity the flower of beauty.",
    grc: "τὸ κάλλος εἶπε τῆς σωφροσύνης ἄνθος εἶναι· οἱ δὲ τοῦ κάλλους τὴν σωφροσύνην.",
    en: "Beauty he called the flower of chastity, while according to others it was chastity which he called the flower of beauty.",
    ref: "7.23",
    certainty: "asserted",
    note: "D.L. records both wordings: others said he called chastity the flower of beauty.",
  },
  {
    id: "zeno-citium-imprints-of-anger",
    philosopher: "Zeno of Citium",
    topic: "virtue",
    gloss: "Seeing an acquaintance's slave marked with weals: I see the imprints of your anger.",
    grc: "ὁρῶ σου, ἔφη, τοῦ θυμοῦ τὰ ἴχνη",
    en: "I see, said he, the imprints of your anger.",
    ref: "7.23",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-smells-of-woman",
    philosopher: "Zeno of Citium",
    topic: "wit",
    gloss: "To one drenched with unguent: who is this who smells of woman?",
    grc: "τίς ἐστιν, ἔφη, ὁ γυναικὸς ὄζων;",
    en: "Who is this, quoth he, who smells of woman?",
    ref: "7.23",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-mistrust-dionysius",
    philosopher: "Zeno of Citium",
    topic: "education",
    gloss: "Asked by Dionysius the Renegade why he alone was never corrected: because I mistrust you.",
    grc: "Διονυσίου δὲ τοῦ Μεταθεμένου εἰπόντος αὐτῷ διὰ τί αὐτὸν μόνον οὐ διορθοῖ, ἔφη, οὐ γάρ σοι πιστεύω.",
    en: "When Dionysius the Renegade asked, Why am I the only pupil you do not correct? the reply was, Because I mistrust you.",
    ref: "7.23",
    to: "Dionysius the Renegade",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-hold-his-tongue",
    philosopher: "Zeno of Citium",
    topic: "speech",
    gloss: "Silent at a banquet, he told Ptolemy's envoys to report to the king that there was one present who knew how to hold his tongue.",
    grc: "ἔφη οὖν τῷ ἐγκαλέσαντι ἀπαγγεῖλαι πρὸς τὸν βασιλέα ὅτι παρῆν τις σιωπᾶν ἐπιστάμενος",
    en: "he bade his critic carry word to the king that there was one present who knew how to hold his tongue.",
    ref: "7.24",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-abuse-envoy",
    philosopher: "Zeno of Citium",
    topic: "wit",
    gloss: "Asked how he felt about abuse: as an envoy feels who is dismissed without an answer.",
    grc: "ἐρωτηθεὶς πῶς ἔχει πρὸς λοιδορίαν, καθάπερ, εἶπεν, εἰ πρεσβευτὴς ἀναπόκριτος ἀποστέλλοιτο.",
    en: "On being asked how he felt about abuse, he replied, As an envoy feels who is dismissed without an answer.",
    ref: "7.24",
    certainty: "asserted",
  },
  {
    id: "zeno-citium-lupins-soaked",
    philosopher: "Zeno of Citium",
    topic: "wit",
    gloss: "Asked why he, though austere, relaxed over wine: lupins too are bitter, but when soaked become sweet.",
    grc: "καὶ οἱ θέρμοι πικροὶ ὄντες βρεχόμενοι γλυκαίνονται.",
    en: "Lupins too are bitter, but when they are soaked become sweet.",
    ref: "7.26",
    certainty: "reported",
  },
  {
    id: "zeno-citium-trip-feet-not-tongue",
    philosopher: "Zeno of Citium",
    topic: "speech",
    gloss: "Better to trip with the feet than with the tongue.",
    grc: "κρεῖττον εἶναι τοῖς ποσὶν ὀλισθεῖν ἢ τῇ γλώττῃ.",
    en: "Better to trip with the feet than with the tongue.",
    ref: "7.26",
    certainty: "asserted",
  },
  // ---------------------------------------------------------- Ariston of Chios
  {
    id: "ariston-chios-spiders-webs",
    philosopher: "Ariston of Chios",
    topic: "wisdom",
    gloss: "Dialectical reasonings are like spiders' webs: seemingly artistic workmanship, but of no use.",
    grc: "Ἐοικέναι δὲ τοὺς διαλεκτικοὺς λόγους τοῖς ἀραχνίοις, ἃ καίτοι δοκοῦντα τεχνικόν τι ἐμφαίνειν, ἄχρηστά ἐστιν.",
    en: "Dialectical reasonings, he said, are like spiders’ webs, which, though they seem to display some artistic workmanship, are yet of no use.",
    ref: "7.161",
    certainty: "asserted",
  },
  {
    id: "ariston-chios-who-blinded-you",
    philosopher: "Ariston of Chios",
    topic: "wit",
    gloss: "To the Academic sceptic who denied seeing his neighbour: who can have blinded you? who robbed you of luminous eyesight?",
    grc: "ἆρʼ οὐδὲ τὸν πλησίον σου καθήμενον ὁρᾷς; εἶπεν· ἀρνησαμένου δέ, τίς δέ σʼ ἐτύφλωσεν (ἔφη), τίς ἀφείλετο λαμπάδος αὐγάς;",
    en: "Do you not even see your neighbour sitting by you? and when the other answered No, he rejoined, Who can have blinded you? who robbed you of luminous eyesight?",
    ref: "7.163",
    certainty: "asserted",
  },
  // ----------------------------------------------------------------- Cleanthes
  {
    id: "cleanthes-maintain-second-cleanthes",
    philosopher: "Cleanthes",
    topic: "self-sufficiency",
    gloss: "Producing his hard-earned coin: Cleanthes could maintain a second Cleanthes, while those with means live at others' expense.",
    grc: "Κλεάνθης μὲν καὶ ἄλλον Κλεάνθην δύναιτʼ ἂν τρέφειν, εἰ βούλοιτο· οἱ δʼ ἔχοντες ὅθεν τραφήσονται παρʼ ἑτέρων ἐπιζητοῦσι τἀπιτήδεια, καίπερ ἀνειμένως φιλοσοφοῦντες.",
    en: "Cleanthes could even maintain a second Cleanthes, if he liked, whereas those who possess the means to keep themselves yet seek to live at the expense of others, and that too though they have plenty of time to spare from their studies.",
    ref: "7.170",
    certainty: "asserted",
  },
  {
    id: "cleanthes-carry-zenos-load",
    philosopher: "Cleanthes",
    topic: "virtue",
    gloss: "Called the ass by his fellow pupils, he accepted it: he alone was strong enough to carry the load of Zeno.",
    grc: "λέγων αὐτὸς μόνος δύνασθαι βαστάζειν τὸ Ζήνωνος φορτίον.",
    en: "telling them that he alone was strong enough to carry the load of Zeno.",
    ref: "7.170",
    certainty: "asserted",
  },
  {
    id: "cleanthes-cowardice-seldom-wrong",
    philosopher: "Cleanthes",
    topic: "wit",
    gloss: "Reproached with cowardice: that is why I so seldom go wrong.",
    grc: "καί ποτʼ ὀνειδιζόμενος ὡς δειλός, διὰ τοῦτο, εἶπεν, ὀλίγα ἁμαρτάνω.",
    en: "Once when he was reproached with cowardice, he replied, That is why I so seldom go wrong.",
    ref: "7.171",
    certainty: "asserted",
  },
  {
    id: "cleanthes-digging-barren-ground",
    philosopher: "Cleanthes",
    topic: "wealth",
    gloss: "Preferring his life to the rich man's: while they play at ball, he digs hard and barren ground.",
    grc: "προκρίνων δὲ τὸν ἑαυτοῦ βίον τοῦ τῶν πλουσίων ἔλεγεν, ἐν ᾧ σφαιρίζουσιν ἐκεῖνοι γῆν σκληρὰν καὶ ἄκαρπον αὐτὸς ἐργάζεσθαι σκάπτων.",
    en: "when extolling his own manner of life above that of the wealthy, he used to say that, while they were playing at ball, he was at work digging hard and barren ground.",
    ref: "7.171",
    certainty: "asserted",
  },
  {
    id: "cleanthes-old-man-no-wits",
    philosopher: "Cleanthes",
    topic: "wit",
    gloss: "Caught scolding himself and asked by Ariston whom he was scolding: an old man with grey hairs and no wits.",
    grc: "πρεσβύτῃ, φησί, πολιὰς μὲν ἔχοντι, νοῦν δὲ μή.",
    en: "he, laughing, said, An old man with grey hairs and no wits.",
    ref: "7.171",
    to: "Ariston of Chios",
    certainty: "asserted",
  },
  {
    id: "cleanthes-arcesilaus-deeds",
    philosopher: "Cleanthes",
    topic: "virtue",
    gloss: "Defending Arcesilaus: if by his words he does away with duty, he maintains it at all events by his deeds.",
    grc: "παῦσαι, ἔφη, καὶ μὴ ψέγε· εἰ γὰρ καὶ λόγῳ τὸ καθῆκον ἀναιρεῖ, τοῖς γοῦν ἔργοις αὐτὸ τιθεῖ.",
    en: "No more of this; do not censure him. For if by his words he does away with duty, he maintains it at all events by his deeds.",
    ref: "7.171",
    certainty: "asserted",
  },
  {
    id: "cleanthes-flattery-theory-practice",
    philosopher: "Cleanthes",
    topic: "wit",
    gloss: "When Arcesilaus said he was not to be won by flattery: true - but my flattery is alleging that your theory contradicts your practice.",
    grc: "ναί, ἔφη, σὲ κολακεύω φάμενος ἄλλα μὲν λέγειν, ἕτερα δὲ ποιεῖν.",
    en: "True, but my flattery consists in alleging that your theory is incompatible with your practice.",
    ref: "7.171",
    to: "Arcesilaus",
    certainty: "asserted",
  },
  {
    id: "cleanthes-electra-silence",
    philosopher: "Cleanthes",
    topic: "education",
    gloss: "Asked what lesson to give a son, he quoted the Electra: silence, silence, light be thy step.",
    grc: "τὸ τῆς Ἠλέκτρας, ἔφη, σῖγα, σῖγα, λεπτὸν ἴχνος.",
    en: "Cleanthes in reply quoted words from the Electra : Silence, silence, light be thy step.",
    ref: "7.172",
    certainty: "asserted",
  },
  {
    id: "cleanthes-lacedaemonian-toil",
    philosopher: "Cleanthes",
    topic: "virtue",
    gloss: "Overjoyed at a Spartan who called toil a good thing, he quoted Homer: thou art of gentle blood, dear child.",
    grc: "Λάκωνός τινος εἰπόντος ὅτι ὁ πόνος ἀγαθόν, διαχυθείς φησιν, αἵματός εἰς ἀγαθοῖο, φίλον τέκος.",
    en: "A Lacedaemonian having declared that toil was a good thing, he was overjoyed and said, Thou art of gentle blood, dear child.",
    ref: "7.172",
    certainty: "asserted",
  },
  {
    id: "cleanthes-see-that-you-see",
    philosopher: "Cleanthes",
    topic: "wit",
    gloss: "To a youth who nodded that he could see: why, then, don't I see that you see?",
    grc: "διὰ τί οὖν, εἶπεν, ἐγὼ οὐκ αἰσθάνομαι ὅτι αἰσθάνῃ;",
    en: "he went on, Why, then, don’t I see that you see?",
    ref: "7.172",
    certainty: "asserted",
  },
  {
    id: "cleanthes-dionysus-heracles-abuse",
    philosopher: "Cleanthes",
    topic: "virtue",
    gloss: "Accepting the poet Sositheus' apology: if Dionysus and Heracles bear the poets' ridicule without anger, he cannot mind casual abuse.",
    grc: "εἰπὼν ἄτοπον εἶναι τὸν μὲν Διόνυσον καὶ τὸν Ἡρακλέα φλυαρουμένους ὑπὸ τῶν ποιητῶν μὴ ὀργίζεσθαι, αὐτὸν δʼ ἐπὶ τῇ τυχούσῃ βλασφημίᾳ δυσχεραίνειν.",
    en: "he accepted the apology, saying that, when Dionysus and Heracles were ridiculed by the poets without getting angry, it would be absurd for him to be annoyed at casual abuse.",
    ref: "7.173",
    certainty: "asserted",
  },
  {
    id: "cleanthes-peripatetics-lyres",
    philosopher: "Cleanthes",
    topic: "wit",
    gloss: "The Peripatetics are like lyres: they give forth sweet sounds but never hear themselves.",
    grc: "ἔλεγε δὲ καὶ τοὺς ἐκ τοῦ περιπάτου ὅμοιόν τι πάσχειν ταῖς λύραις, αἳ καλῶς φθεγξάμεναι αὑτῶν οὐκ ἀκούουσι.",
    en: "He used to say that the Peripatetics were in the same case as lyres which, although they give forth sweet sounds, never hear themselves.",
    ref: "7.173",
    certainty: "asserted",
  },
  {
    id: "cleanthes-sneeze-effeminate",
    philosopher: "Cleanthes",
    topic: "wit",
    gloss: "Perplexed by the country rake brought to test physiognomy, he seized on the man's sneeze: I have it - he is effeminate.",
    grc: "ἔχω, εἶπεν, αὐτόν, ὁ Κλεάνθης, μαλακός ἐστι.",
    en: "I have it, cried Cleanthes, he is effeminate.",
    ref: "7.173",
    certainty: "reported",
  },
  {
    id: "cleanthes-talking-to-himself",
    philosopher: "Cleanthes",
    topic: "wit",
    gloss: "To the solitary man talking to himself: you are not talking to a bad man.",
    grc: "πρὸς δὲ τὸν μονήρη καὶ ἑαυτῷ λαλοῦντα, οὐ φαύλῳ, ἔφη, ἀνθρώπῳ λαλεῖς.",
    en: "To the solitary man who talked to himself he remarked, You are not talking to a bad man.",
    ref: "7.174",
    certainty: "asserted",
  },
  {
    id: "cleanthes-content-to-wait",
    philosopher: "Cleanthes",
    topic: "death",
    gloss: "Twitted on his old age: he too is ready to depart, but finding himself in good health, still writing and reading, he is content to wait.",
    grc: "Κἀγώ, ἔφη, ἀπιέναι βούλομαι· ὅταν δὲ πανταχόθεν ἐμαυτὸν ὑγιαίνοντα περινοῶ καὶ γράφοντα καὶ ἀναγινώσκοντα, πάλιν μένω.",
    en: "I too am ready to depart; but when again I consider that I am in all points in good health and that I can still write and read, I am content to wait.",
    ref: "7.174",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Chrysippus
  {
    id: "chrysippus-doctrines-proofs",
    philosopher: "Chrysippus",
    topic: "education",
    gloss: "He often told Cleanthes that all he wanted was the doctrines: he would find the proofs for himself.",
    grc: "πολλάκις ἔλεγε μόνης τῆς τῶν δογμάτων διδασκαλίας χρῄζειν, τὰς δὲ ἀποδείξεις αὐτὸς εὑρήσειν.",
    en: "all he wanted was to be told what the doctrines were; he would find out the proofs for himself.",
    ref: "7.179",
    to: "Cleanthes",
    certainty: "asserted",
  },
  {
    id: "chrysippus-followed-multitude",
    philosopher: "Chrysippus",
    topic: "wisdom",
    gloss: "Reproached for not going with the crowd to hear Ariston: had I followed the multitude, I should not have studied philosophy.",
    grc: "εἰ τοῖς πολλοῖς, εἶπε προσεῖχον, οὐκ ἂν ἐφιλοσόφησα.",
    en: "If I had followed the multitude, I should not have studied philosophy.",
    ref: "7.182",
    certainty: "asserted",
  },
  {
    id: "chrysippus-quibbles-to-juniors",
    philosopher: "Chrysippus",
    topic: "wit",
    gloss: "To a dialectician plying the aged Cleanthes with sophisms: cease distracting your elder - propound such quibbles to us juniors.",
    grc: "πέπαυσο, εἶπε, περιέλκων τὸν πρεσβύτην ἀπὸ τῶν πραγματικωτέρων, ἡμῖν δὲ τὰ τοιαῦτα πρότεινε τοῖς νέοις.",
    en: "Cease to distract your elder from matters of importance; propound such quibbles to us juniors.",
    ref: "7.182",
    certainty: "asserted",
  },
  {
    id: "chrysippus-entrust-your-son",
    philosopher: "Chrysippus",
    topic: "education",
    gloss: "Asked to whom a son should be entrusted: to me - had he thought anyone better than himself, he would be studying with him.",
    grc: "ἐμοί· καὶ γὰρ εἰ ὑπελάμβανον εἶναί τινʼ ἐμοῦ βελτίονα, παρʼ αὐτῷ ἂν ἐγὼ ἐφιλοσόφουν.",
    en: "To me: for, if I had dreamt of there being anyone better than myself, I should myself be studying with him.",
    ref: "7.183",
    certainty: "asserted",
  },
  {
    id: "chrysippus-ass-drink-wine",
    philosopher: "Chrysippus",
    topic: "wit",
    gloss: "After an ass ate his figs, the jest said to have killed him with laughter: now give the ass pure wine to wash them down.",
    grc: "εἰπόντα τῇ γραῒ διδόναι ἄκρατον ἐπιρροφῆσαι τῷ ὄνῳ",
    en: "he cried out to the old woman, Now give the ass a drink of pure wine to wash down the figs.",
    ref: "7.185",
    certainty: "reported",
  },
];
