/**
 * Curated sayings & apophthegms from Book 5 of Diogenes Laertius' Lives
 * (the Peripatetics: Aristotle, Theophrastus, ...), cited to Hicks section
 * ids (book.section). See sayings.ts for the model and curation rules.
 */
import type { Saying } from "../sayings";

export const BOOK5_SAYINGS: Saying[] = [
  // ----------------------------------------------------------------- Aristotle
  {
    id: "aristotle-liars-not-believed",
    philosopher: "Aristotle",
    topic: "speech",
    gloss:
      "What do liars gain? That when they speak the truth they are not believed.",
    grc: "ἐρωτηθεὶς τί περιγίνεται κέρδος τοῖς ψευδομένοις, ὅταν, ἔφη, λέγωσιν ἀληθῆ, μὴ πιστεύεσθαι.",
    en: "To the question, What do people gain by telling lies? his answer was, Just this, that when they speak the truth they are not believed.",
    ref: "5.17",
    certainty: "asserted",
  },
  {
    id: "aristotle-pitied-the-man",
    philosopher: "Aristotle",
    topic: "virtue",
    gloss:
      "Reproached for giving alms to a bad man: it was the man and not his character that I pitied.",
    grc: "οὐ τὸν τρόπον, εἶπεν, ἀλλὰ τὸν ἄνθρωπον ἠλέησα.",
    en: "It was the man and not his character that I pitied.",
    ref: "5.17",
    certainty: "asserted",
  },
  {
    id: "aristotle-roots-of-education",
    philosopher: "Aristotle",
    topic: "education",
    gloss: "The roots of education are bitter, but the fruit is sweet.",
    grc: "Τῆς παιδείας ἔφη τὰς μὲν ῥίζας εἶναι πικράς, τὸν δὲ καρπὸν γλυκύν.",
    en: "The roots of education, he said, are bitter, but the fruit is sweet.",
    ref: "5.18",
    certainty: "asserted",
  },
  {
    id: "aristotle-gratitude-grows-old",
    philosopher: "Aristotle",
    topic: "friendship",
    gloss: "What soon grows old? Gratitude.",
    grc: "ἐρωτηθεὶς τί γηράσκει ταχύ, χάρις, ἔφη.",
    en: "Being asked, What is it that soon grows old? he answered, Gratitude.",
    ref: "5.18",
    certainty: "asserted",
  },
  {
    id: "aristotle-hope-waking-dream",
    philosopher: "Aristotle",
    topic: "fortune",
    gloss: "Asked to define hope: it is a waking dream.",
    grc: "ἐρωτηθεὶς τί ἐστιν ἐλπίς, ἐγρηγορότος, εἶπεν, ἐνύπνιον.",
    en: "He was asked to define hope, and he replied, It is a waking dream.",
    ref: "5.18",
    certainty: "asserted",
  },
  {
    id: "aristotle-beauty-introduction",
    philosopher: "Aristotle",
    topic: "fame",
    gloss:
      "Beauty is a greater recommendation than any letter of introduction - though some give the definition to Diogenes.",
    grc: "τὸ κάλλος παντὸς ἔλεγεν ἐπιστολίου συστατικώτερον.",
    en: "Beauty he declared to be a greater recommendation than any letter of introduction.",
    ref: "5.18",
    certainty: "disputed",
    alsoAttributedTo: "Diogenes",
    note: "D.L. immediately adds: 'Others attribute this definition to Diogenes' (5.19).",
  },
  {
    id: "aristotle-educated-living-dead",
    philosopher: "Aristotle",
    topic: "education",
    gloss:
      "The educated differ from the uneducated as much as the living from the dead.",
    grc: "ἐρωτηθεὶς τίνι διαφέρουσιν οἱ πεπαιδευμένοι τῶν ἀπαιδεύτων, ὅσῳ, εἶπεν, οἱ ζῶντες τῶν τεθνεώτων.",
    en: "Being asked how the educated differ from the uneducated, As much, he said, as the living from the dead.",
    ref: "5.19",
    certainty: "asserted",
  },
  {
    id: "aristotle-education-ornament-refuge",
    philosopher: "Aristotle",
    topic: "education",
    gloss:
      "Education is an ornament in prosperity and a refuge in adversity.",
    grc: "τὴν παιδείαν ἔλεγεν ἐν μὲν ταῖς εὐτυχίαις εἶναι κόσμον, ἐν δὲ ταῖς ἀτυχίαις καταφυγήν.",
    en: "He used to declare education to be an ornament in prosperity and a refuge in adversity.",
    ref: "5.19",
    certainty: "asserted",
  },
  {
    id: "aristotle-friend-single-soul",
    philosopher: "Aristotle",
    topic: "friendship",
    gloss: "What is a friend? A single soul dwelling in two bodies.",
    grc: "ἐρωτηθεὶς τί ἐστι φίλος, ἔφη, μία ψυχὴ δύο σώμασιν ἐνοικοῦσα.",
    en: "To the query, What is a friend? his reply was, A single soul dwelling in two bodies.",
    ref: "5.20",
    certainty: "asserted",
  },
  {
    id: "aristotle-philosophy-without-orders",
    philosopher: "Aristotle",
    topic: "virtue",
    gloss:
      "What philosophy gained him: doing unbidden what others do only for fear of the law.",
    grc: "ἐρωτηθεὶς τί ποτʼ αὐτῷ περιγέγονεν ἐκ φιλοσοφίας, ἔφη, τὸ ἀνεπιτάκτως ποιεῖν ἅ τινες διὰ τὸν ἀπὸ τῶν νόμων φόβον ποιοῦσιν.",
    en: "When asked what advantage he had ever gained from philosophy, he replied, This, that I do without being ordered what some are constrained to do by their fear of the law.",
    ref: "5.20",
    certainty: "asserted",
  },
  {
    id: "aristotle-friends-no-friend",
    philosopher: "Aristotle",
    topic: "friendship",
    gloss: "He who has friends can have no true friend.",
    grc: "ᾧ φίλοι, οὐδεὶς φίλος",
    en: "He who has friends can have no true friend.",
    ref: "5.21",
    certainty: "reported",
    accordingTo: "Favorinus",
    note: "Favorinus (Memorabilia, book 2) gives it as one of his habitual sayings; D.L. adds it is found in the seventh book of the Ethics.",
  },
  {
    id: "aristotle-soul-light-mathematics",
    philosopher: "Aristotle",
    topic: "education",
    gloss: "As sight takes in light from the surrounding air, so does the soul from mathematics.",
    grc: "ὡς ἡ μὲν ὅρασις ἀπὸ τοῦ περιέχοντος [ἀέρος] λαμβάνει τὸ φῶς, ἡ δὲ ψυχὴ ἀπὸ τῶν μαθημάτων.",
    en: "As sight takes in light from the surrounding air, so does the soul from mathematics.",
    ref: "5.17",
    certainty: "asserted",
  },
  {
    id: "aristotle-athenians-wheat-laws",
    philosopher: "Aristotle",
    topic: "politics",
    gloss: "The Athenians discovered wheat and laws - but used only the wheat.",
    grc: "τοὺς Ἀθηναίους ἔφασκεν εὑρηκέναι πυροὺς καὶ νόμους· ἀλλὰ πυροῖς μὲν χρῆσθαι, νόμοις δὲ μή.",
    en: "the Athenians were the discoverers of wheat and of laws; but, though they used wheat, they had no use for laws.",
    ref: "5.17",
    certainty: "asserted",
  },
  {
    id: "aristotle-diogenes-figs",
    philosopher: "Aristotle",
    topic: "wit",
    gloss: "Taking Diogenes' proffered figs to spoil the prepared jest - Diogenes lost his figs and his jest into the bargain; and next time, lifting them aloft like a baby: great is Diogenes.",
    grc: "λαβὼν ἔφη Διογένην μετὰ τῆς χρείας καὶ τὴν ἰσχάδα ἀπολωλεκέναι· πάλιν τε διδόντος λαβὼν καὶ μετεωρίσας ὡς τὰ παιδία εἰπών τε μέγας Διογένης, ἀπέδωκεν αὐτῷ.",
    en: "so he took them and said Diogenes had lost his figs and his jest into the bargain. And on another occasion he took them when they were offered, lifted them up aloft, as you do babies, and returned them with the exclamation, Great is Diogenes.",
    ref: "5.18",
    certainty: "asserted",
  },
  {
    id: "aristotle-three-things-education",
    philosopher: "Aristotle",
    topic: "education",
    gloss: "Three things are indispensable for education: natural endowment, study, and constant practice.",
    grc: "τριῶν ἔφη δεῖν παιδείᾳ, φύσεως, μαθήσεως, ἀσκήσεως.",
    en: "Three things he declared to be indispensable for education: natural endowment, study, and constant practice.",
    ref: "5.18",
    certainty: "asserted",
  },
  {
    id: "aristotle-scourge-me-absent",
    philosopher: "Aristotle",
    topic: "wit",
    gloss: "Hearing that someone abused him: he may even scourge me, so it be in my absence.",
    grc: "ἀκούσας ὑπό τινος λοιδορεῖσθαι, ἀπόντα με, ἔφη, καὶ μαστιγούτω.",
    en: "He may even scourge me so it be in my absence.",
    ref: "5.18",
    certainty: "asserted",
  },
  {
    id: "aristotle-teachers-more-honour",
    philosopher: "Aristotle",
    topic: "education",
    gloss: "Teachers deserve more honour than parents: the one gives bare life, the other the good life.",
    grc: "τῶν γονέων τοὺς παιδεύσαντας ἐντιμοτέρους εἶναι τῶν μόνον γεννησάντων· τοὺς μὲν γὰρ τὸ ζῆν, τοὺς δὲ τὸ καλῶς ζῆν παρασχέσθαι.",
    en: "Teachers who educated children deserved, he said, more honour than parents who merely gave them birth; for bare life is furnished by the one, the other ensures a good life.",
    ref: "5.19",
    certainty: "asserted",
  },
  {
    id: "aristotle-worthy-great-country",
    philosopher: "Aristotle",
    topic: "fame",
    gloss: "To one boasting of his great city: consider rather who is worthy of a great country.",
    grc: "οὐ τοῦτο, ἔφη, δεῖ σκοπεῖν, ἀλλʼ ὅστις μεγάλης πατρίδος ἄξιός ἐστιν.",
    en: "That is not the point to consider, but who it is that is worthy of a great country.",
    ref: "5.19",
    certainty: "asserted",
  },
  {
    id: "aristotle-thrifty-extravagant",
    philosopher: "Aristotle",
    topic: "wealth",
    gloss: "Mankind divides into the thrifty, who live as if for ever, and the extravagant, who live as if to die tomorrow.",
    grc: "τῶν ἀνθρώπων ἔλεγε τοὺς μὲν οὕτω φείδεσθαι ὡς ἀεὶ ζησομένους, τοὺς δὲ οὕτως ἀναλίσκειν ὡς αὐτίκα τεθνηξομένους.",
    en: "Mankind, he used to say, were divided into those who were as thrifty as if they would live for ever, and those who were as extravagant as if they were going to die the next day.",
    ref: "5.20",
    certainty: "asserted",
  },
  {
    id: "aristotle-blind-mans-question",
    philosopher: "Aristotle",
    topic: "wit",
    gloss: "Asked why we spend much time with the beautiful: that is a blind man's question.",
    grc: "πρὸς τὸν πυθόμενον διὰ τί τοῖς καλοῖς πολὺν χρόνον ὁμιλοῦμεν, τυφλοῦ, ἔφη, τὸ ἐρώτημα.",
    en: "That, he said, is a blind man’s question.",
    ref: "5.20",
    certainty: "asserted",
  },
  {
    id: "aristotle-students-progress",
    philosopher: "Aristotle",
    topic: "education",
    gloss: "Students progress by pressing hard on those in front, not waiting for those behind.",
    grc: "ἐὰν τοὺς προέχοντας διώκοντες τοὺς ὑστεροῦντας μὴ ἀναμένωσι.",
    en: "By pressing hard on those in front and not waiting for those behind.",
    ref: "5.20",
    certainty: "asserted",
  },
  {
    id: "aristotle-not-attending-chatterbox",
    philosopher: "Aristotle",
    topic: "wit",
    gloss: "To the chatterbox asking if he had bored him to death: no, indeed - I was not attending to you.",
    grc: "μὰ Δίʼ, εἶπεν· οὐ γάρ σοι προσεῖχον.",
    en: "No, indeed; for I was not attending to you.",
    ref: "5.20",
    certainty: "asserted",
  },
  {
    id: "aristotle-assisted-humanity",
    philosopher: "Aristotle",
    topic: "virtue",
    gloss: "Variant of the alms story: it was not the man that I assisted, but humanity.",
    grc: "οὐ τῷ ἀνθρώπῳ, φησίν, ἔδωκα, ἀλλὰ τῷ ἀνθρωπίνῳ.",
    en: "It was not the man, said he, that I assisted, but humanity.",
    ref: "5.21",
    certainty: "reported",
    note: "D.L.: 'for the story is also told in this form' - a variant of the alms anecdote at 5.17.",
  },
  {
    id: "aristotle-friends-as-we-wish",
    philosopher: "Aristotle",
    topic: "friendship",
    gloss: "How to behave to friends: as we should wish them to behave to us.",
    grc: "ἐρωτηθεὶς πῶς ἂν τοῖς φίλοις προσφεροίμεθα, ἔφη, ὡς ἂν εὐξαίμεθα αὐτοὺς ἡμῖν προσφέρεσθαι.",
    en: "As we should wish them to behave to us.",
    ref: "5.21",
    certainty: "asserted",
  },
  {
    id: "aristotle-justice-virtue-soul",
    philosopher: "Aristotle",
    topic: "virtue",
    gloss: "Justice is a virtue of soul which distributes according to merit.",
    grc: "τὴν δικαιοσύνην ἔφη ἀρετὴν ψυχῆς διανεμητικὴν τοῦ κατʼ ἀξίαν.",
    en: "Justice he defined as a virtue of soul which distributes according to merit.",
    ref: "5.21",
    certainty: "asserted",
  },
  {
    id: "aristotle-education-old-age",
    philosopher: "Aristotle",
    topic: "education",
    gloss: "Education is the best provision for old age.",
    grc: "κάλλιστον ἐφόδιον τῷ γήρᾳ τὴν παιδείαν ἔλεγε.",
    en: "Education he declared to be the best provision for old age.",
    ref: "5.21",
    certainty: "asserted",
  },
  // -------------------------------------------------------------- Theophrastus
  {
    id: "theophrastus-unbridled-horse",
    philosopher: "Theophrastus",
    topic: "speech",
    gloss:
      "An unbridled horse ought to be trusted sooner than a badly-arranged discourse.",
    grc: "θᾶττον ἔφη πιστεύειν δεῖν ἵππῳ ἀχαλίνῳ ἢ λόγῳ ἀσυντάκτῳ.",
    en: "An unbridled horse, he said, ought to be trusted sooner than a badly-arranged discourse.",
    ref: "5.39",
    certainty: "asserted",
  },
  {
    id: "theophrastus-silent-banquet",
    philosopher: "Theophrastus",
    topic: "wit",
    gloss:
      "To one silent at a banquet: a wise course for an ignoramus, but in an educated man sheer folly.",
    grc: "πρὸς δὲ τὸν ἐν τῷ συμποσίῳ σιωπῶντα τὸ ὅλον ἔφη, εἰ μὲν ἀμαθὴς εἶ, φρονίμως ποιεῖς, εἰ δὲ πεπαίδευσαι, ἀφρόνως.",
    en: "To some one who never opened his lips at a banquet he remarked: Yours is a wise course for an ignoramus, but in an educated man it is sheer folly.",
    ref: "5.40",
    certainty: "asserted",
  },
  {
    id: "theophrastus-time-costliest",
    philosopher: "Theophrastus",
    topic: "wisdom",
    gloss: "In our expenditure, the item that costs most is time.",
    grc: "συνεχές τε ἔλεγε πολυτελὲς ἀνάλωμα εἶναι τὸν χρόνον.",
    en: "He used constantly to say that in our expenditure the item that costs most is time.",
    ref: "5.40",
    certainty: "asserted",
  },
  {
    id: "theophrastus-pleasures-seeming",
    philosopher: "Theophrastus",
    topic: "pleasure",
    gloss:
      "His last message: many of the pleasures which life boasts are but in the seeming.",
    grc: "ἐπισκήπτειν μὲν ἔχειν οὐδέν, πλὴν ὅτι πολλὰ τῶν ἡδέων ὁ βίος διὰ τὴν δόξαν καταλαζονεύεται.",
    en: "Nothing else but this, that many of the pleasures which life boasts are but in the seeming.",
    ref: "5.40",
    certainty: "reported",
    note: "D.L.: 'It is said that his disciples asked him if he had any last message for them.'",
  },
  // ---------------------------------------------------------------------- Lyco
  {
    id: "lyco-modesty-spur-bridle",
    philosopher: "Lyco",
    topic: "education",
    gloss:
      "Modesty and love of honour are as necessary an equipment for boys as spur and bridle for horses.",
    grc: "ἔφασκε γὰρ δεῖν παρεζεῦχθαι τοῖς παισὶ τὴν αἰδῶ καὶ φιλοτιμίαν ὡς τοῖς ἵπποις μύωπα καὶ χαλινόν.",
    en: "he used to say that modesty and love of honour were as necessary an equipment for boys as spur and bridle for horses",
    ref: "5.65",
    certainty: "asserted",
  },
  {
    id: "lyco-garland-olympia",
    philosopher: "Lyco",
    topic: "fame",
    gloss:
      "Many go in search of the garland of the market-place; few or none seek the crown at Olympia.",
    grc: "ἐπὶ μὲν τὸν ἐν τῇ ἀγορᾷ στέφανον πολλοὺς ἀπιέναι, ἐπὶ δὲ τὸν Ὀλυμπίασιν ἢ ὀλίγους ἢ οὐδένα.",
    en: "Many go in search of the garland of the market-place; few or none seek the crown at Olympia.",
    ref: "5.66",
    certainty: "asserted",
  },
  // ----------------------------------------------------- Demetrius of Phalerum
  {
    id: "demetrius-statues-merits",
    philosopher: "Demetrius of Phalerum",
    topic: "fame",
    gloss:
      "Hearing the Athenians had destroyed his statues: that they may do, but not the merits which caused them to be erected.",
    grc: "ἀλλʼ οὐ τὴν ἀρετήν, ἔφη, διʼ ἣν ἐκείνας ἀνέστησαν.",
    en: "When he heard that the Athenians had destroyed his statues, That they may do, said he, but the merits which caused them to be erected they cannot destroy.",
    ref: "5.82",
    certainty: "asserted",
  },
  {
    id: "demetrius-plutus-fortune-blind",
    philosopher: "Demetrius of Phalerum",
    topic: "fortune",
    gloss: "Not only is Plutus blind, but his guide, Fortune, as well.",
    grc: "οὐ μόνον τὸν πλοῦτον ἔφη τυφλόν, ἀλλὰ καὶ τὴν ὁδηγοῦσαν αὐτὸν τύχην.",
    en: "he said that not only was Plutus blind, but his guide, Fortune, as well",
    ref: "5.82",
    certainty: "asserted",
  },
  {
    id: "demetrius-eyebrows-darken-life",
    philosopher: "Demetrius of Phalerum",
    topic: "wit",
    gloss:
      "The eyebrows are but a small part of the face, yet they can darken the whole of life by their scorn.",
    grc: "ἔλεγε μικρὸν μὲν εἶναι μέρος τὰς ὀφρῦς, ὅλῳ δʼ ἐπισκοτῆσαι τῷ βίῳ δύνασθαι.",
    en: "He used to say that the eyebrows formed but a small part of the face, and yet they can darken the whole of life by the scorn they express.",
    ref: "5.82",
    certainty: "asserted",
  },
  {
    id: "demetrius-friends-prosperity-adversity",
    philosopher: "Demetrius of Phalerum",
    topic: "friendship",
    gloss:
      "In prosperity friends do not leave you unless desired; in adversity they stay away of their own accord.",
    grc: "τοὺς φίλους ἐπὶ μὲν τὰ ἀγαθὰ παρακαλουμένους ἀπιέναι, ἐπὶ δὲ τὰς συμφορὰς αὐτομάτους.",
    en: "In prosperity friends do not leave you unless desired, whereas in adversity they stay away of their own accord.",
    ref: "5.83",
    certainty: "asserted",
  },
  {
    id: "demetrius-steel-eloquence",
    philosopher: "Demetrius of Phalerum",
    topic: "politics",
    gloss: "All that steel achieves in war, eloquence wins in politics.",
    grc: "ὅσον ἐν πολέμῳ δύνασθαι σίδηρον, τοσοῦτον ἐν πολιτείᾳ ἰσχύειν λόγον.",
    en: "that all that steel could achieve in war was won in politics by eloquence.",
    ref: "5.82",
    certainty: "asserted",
  },
  {
    id: "demetrius-four-square-hermes",
    philosopher: "Demetrius of Phalerum",
    topic: "wit",
    gloss: "Seeing a young dandy: there is a four-square Hermes for you, with trailing robe, belly, beard and all.",
    grc: "ἰδών ποτε νεανίσκον ἄσωτον, ἰδού, ἔφη, τετράγωνος Ἑρμῆς ἔχων σύρμα, κοιλίαν, αἰδοῖον, πώγωνα.",
    en: "There, quoth he, is a four-square Hermes for you, with trailing robe, belly, beard and all.",
    ref: "5.82",
    certainty: "asserted",
  },
  {
    id: "demetrius-haughty-stature",
    philosopher: "Demetrius of Phalerum",
    topic: "virtue",
    gloss: "Of the haughty: cut down their tall stature but leave their spirit unimpaired.",
    grc: "τῶν τετυφωμένων ἀνδρῶν ἔφη τὸ μὲν ὕψος δεῖν περιαιρεῖν, τὸ δὲ φρόνημα καταλείπειν.",
    en: "When men are haughty and arrogant, he declared we should cut down their tall stature and leave them their spirit unimpaired.",
    ref: "5.82",
    certainty: "asserted",
  },
  {
    id: "demetrius-honour-parents-selves",
    philosopher: "Demetrius of Phalerum",
    topic: "education",
    gloss: "The young should honour their parents at home, out of doors everyone they meet, and in solitude themselves.",
    grc: "τοὺς νέους ἔφη δεῖν ἐπὶ μὲν τῆς οἰκίας τοὺς γονέας αἰδεῖσθαι, ἐν δὲ ταῖς ὁδοῖς τοὺς ἀπαντῶντας, ἐν δὲ ταῖς ἐρημίαις ἑαυτούς.",
    en: "Children should honour their parents at home, out-of-doors everyone they meet, and in solitude themselves.",
    ref: "5.82",
    certainty: "asserted",
  },
];
