/**
 * Curated sayings & apophthegms from Book 4 of Diogenes Laertius' Lives
 * (the Academy: Speusippus, Xenocrates, Arcesilaus, Bion, ...), cited to
 * Hicks section ids (book.section). See sayings.ts for the model and rules.
 */
import type { Saying } from "../sayings";

export const BOOK4_SAYINGS: Saying[] = [
  // ---------------------------------------------------- Plato (in Xenocrates)
  {
    id: "plato-spur-bridle",
    philosopher: "Plato",
    topic: "education",
    gloss:
      "Comparing his pupils Xenocrates and Aristotle: the one needed a spur, the other a bridle.",
    grc: "τῷ μὲν μύωπος δεῖ, τῷ δὲ χαλινοῦ.",
    en: "The one needed a spur, the other a bridle.",
    ref: "4.6",
    certainty: "asserted",
    crossAttributed: true,
    note: "Spoken by Plato, recorded in the life of Xenocrates.",
  },
  {
    id: "plato-sacrifice-graces",
    philosopher: "Plato",
    topic: "wit",
    gloss:
      "To the grave, unbending Xenocrates he would say continually: sacrifice to the Graces.",
    grc: "Ξενόκρατες, θῦε ταῖς Χάρισι.",
    en: "Xenocrates, sacrifice to the Graces.",
    ref: "4.6",
    to: "Xenocrates",
    certainty: "asserted",
    crossAttributed: true,
    note: "Spoken by Plato, recorded in the life of Xenocrates.",
  },
  // ---------------------------------------------------------------- Xenocrates
  {
    id: "xenocrates-alexander-money",
    philosopher: "Xenocrates",
    topic: "wealth",
    gloss:
      "Returning most of Alexander's money: the king's needs were greater, for he had more people to keep.",
    grc: "τρισχιλίας Ἀττικὰς ἀφελὼν τὸ λοιπὸν ἀπέπεμψεν, εἰπὼν ἐκείνῳ πλειόνων δεῖν πλείονας τρέφοντι.",
    en: "when Alexander sent him a large sum of money, he took three thousand Attic drachmas and sent back the rest to Alexander, whose needs, he said, were greater than his own, because he had a greater number of people to keep",
    ref: "4.8",
    certainty: "asserted",
  },
  {
    id: "xenocrates-philip-bribe",
    philosopher: "Xenocrates",
    topic: "politics",
    gloss:
      "To the Athenians, on the embassy to Philip: Philip knew the others could be bought, but never him.",
    grc: "τοὺς μὲν γὰρ ᾔδει δωροδοκήσαντας ὁ Φίλιππος, ἐμὲ δὲ μηδενὶ λόγῳ ὑπαξόμενοσ",
    en: "Philip knew that the others had accepted his bribes, but that he would never win me over",
    ref: "4.9",
    to: "the Athenians",
    certainty: "asserted",
  },
  {
    id: "xenocrates-suppliant-sparrow",
    philosopher: "Xenocrates",
    topic: "virtue",
    gloss:
      "Sheltering a sparrow chased by a hawk: a suppliant must not be betrayed.",
    grc: "καταψήσας μεθῆκεν, εἰπὼν τὸν ἱκέτην δεῖν μὴ ἐκδιδόναι.",
    en: "When a little sparrow was pursued by a hawk and rushed into his bosom, he stroked it and let it go, declaring that a suppliant must not be betrayed.",
    ref: "4.10",
    certainty: "asserted",
  },
  {
    id: "xenocrates-tragedy-comedy",
    philosopher: "Xenocrates",
    topic: "wit",
    gloss:
      "Bantered by Bion, he refused to answer: tragedy does not deign to answer the banter of comedy.",
    grc: "μηδὲ γὰρ τὴν τραγῳδίαν ὑπὸ τῆς κωμῳδίας σκωπτομένην ἀποκρίσεως ἀξιοῦν.",
    en: "For neither, said he, does tragedy deign to answer the banter of comedy.",
    ref: "4.10",
    to: "Bion",
    certainty: "asserted",
  },
  {
    id: "xenocrates-nothing-to-lay-hold-of",
    philosopher: "Xenocrates",
    topic: "education",
    gloss:
      "To one untrained in music, geometry, and astronomy who wished to attend his lectures: you offer philosophy nothing to lay hold of.",
    grc: "πορεύου, ἔφη· λαβὰς γὰρ οὐκ ἔχεις φιλοσοφίας.",
    en: "Go your ways, for you offer philosophy nothing to lay hold of.",
    ref: "4.10",
    certainty: "asserted",
  },
  // -------------------------------------------------------------------- Polemo
  {
    id: "polemo-facts-not-speculations",
    philosopher: "Polemo",
    topic: "wisdom",
    gloss:
      "Exercise yourself with facts, not with mere logical speculations - like practising harmony, not just learning the handbook.",
    grc: "ἔφασκε δὲ ὁ Πολέμων δεῖν ἐν τοῖς πράγμασι γυμνάζεσθαι καὶ μὴ ἐν τοῖς διαλεκτικοῖς θεωρήμασι, καθάπερ ἁρμονικόν τι τέχνιον καταπιόντα καὶ μὴ μελετήσαντα, ὡς κατὰ μὲν τὴν ἐρώτησιν θαυμάζεσθαι, κατὰ δὲ τὴν διάθεσιν ἑαυτοῖς μάχεσθαι.",
    en: "Polemo used to say that we should exercise ourselves with facts and not with mere logical speculations, which leave us, like a man who has got by heart some paltry handbook on harmony but never practised, able, indeed, to win admiration for skill in asking questions, but utterly at variance with ourselves in the ordering of our lives.",
    ref: "4.18",
    certainty: "asserted",
  },
  // ------------------------------------------------------------------- Crantor
  {
    id: "crantor-tragedy-everyday-language",
    philosopher: "Crantor",
    topic: "speech",
    gloss:
      "It is hard at once to write tragedy and to stir the emotions in the language of everyday life.",
    grc: "λέγων ἐργῶδες εἶναι ἐν τῷ κυρίῳ τραγικῶς ἅμα καὶ συμπαθῶς γράψαι.",
    en: "it is hard, he said, at once to write tragedy and to stir the emotions in the language of everyday life",
    ref: "4.26",
    certainty: "asserted",
  },
  // ---------------------------------------------------------------- Arcesilaus
  {
    id: "arcesilaus-geometry-agape",
    philosopher: "Arcesilaus",
    topic: "wit",
    gloss:
      "Of the sluggard geometer Hipponicus: geometry must have flown into his mouth while it was agape.",
    grc: "εἰπὼν τὴν γεωμετρίαν αὐτοῦ χάσκοντος εἰς τὸ στόμα ἐμπτῆναι.",
    en: "Geometry, he said, must have flown into his mouth while it was agape.",
    ref: "4.32",
    certainty: "asserted",
  },
  {
    id: "arcesilaus-time-for-all-things",
    philosopher: "Arcesilaus",
    topic: "wisdom",
    gloss:
      "Pressed to debate over the wine: the peculiar province of philosophy is to know that there is a time for all things.",
    grc: "ἀλλʼ αὐτὸ τοῦτο μάλιστα φιλοσοφίας ἴδιον, τὸ τὸν καιρὸν ἑκάστων ἐπίστασθαι.",
    en: "The peculiar province of philosophy is just this, to know that there is a time for all things.",
    ref: "4.42",
    certainty: "asserted",
  },
  {
    id: "arcesilaus-eunuchs-epicureans",
    philosopher: "Arcesilaus",
    topic: "wit",
    gloss:
      "Why converts go over to Epicurus but never come back: men may become eunuchs, but a eunuch never becomes a man.",
    grc: "ἐκ μὲν γὰρ ἀνδρῶν γάλλοι γίνονται, ἐκ δὲ γάλλων ἄνδρες οὐ γίνονται.",
    en: "Because men may become eunuchs, but a eunuch never becomes a man, was his answer.",
    ref: "4.43",
    certainty: "asserted",
  },
  {
    id: "arcesilaus-knuckle-bone",
    philosopher: "Arcesilaus",
    topic: "wit",
    gloss: "Of a young man talking more boldly than was becoming: will no one beat him at a game of knuckle-bone?",
    grc: "οὐ λήψεταί τις, ἔφη, τοῦτον ἀστραγάλῳ;",
    en: "Will no one beat him at a game of knuckle-bone?",
    ref: "4.34",
    certainty: "asserted",
  },
  {
    id: "arcesilaus-six-and-ten-inches",
    philosopher: "Arcesilaus",
    topic: "wit",
    gloss: "To one of immodest life who denied that one thing seemed greater than another: then six inches and ten inches are all the same to you?",
    grc: "ἠρώτησεν εἰ οὐδὲ τὸ δεκαδάκτυλον τοῦ ἑξαδακτύλου.",
    en: "Then six inches and ten inches are all the same to you?",
    ref: "4.34",
    certainty: "asserted",
  },
  {
    id: "arcesilaus-handsome-hemon",
    philosopher: "Arcesilaus",
    topic: "wit",
    gloss: "To Hemon of Chios, an ugly man who fancied himself handsome and denied the wise man will fall in love: what, not with one so handsome as you and so handsomely dressed?",
    grc: "ἔφη, πότερον οὐδʼ ἐὰν οὕτω καλὸς ᾖ τις ὥσπερ σὺ οὐδʼ ἐὰν οὕτω καλὰ ἱμάτια ἔχῃ;",
    en: "What, not with one so handsome as you and so handsomely dressed?",
    ref: "4.34",
    certainty: "asserted",
    to: "Hemon of Chios",
  },
  {
    id: "arcesilaus-sons-of-slaves",
    philosopher: "Arcesilaus",
    topic: "speech",
    gloss: "Against a troublesome talker of no family he cited the line: right ill to live with are the sons of slaves.",
    grc: "ἀκόλασθʼ ὁμιλεῖν γίγνεται δούλων τέκνα.",
    en: "Right ill to live with are the sons of slaves.",
    ref: "4.35",
    certainty: "asserted",
    note: "A verse quotation deployed as a retort; D.L. says he 'cited the line'.",
  },
  {
    id: "arcesilaus-nurse-scold",
    philosopher: "Arcesilaus",
    topic: "wit",
    gloss: "Of one who talked much nonsense: he could not have had even a nurse to scold him.",
    grc: "οὐδὲ τίτθης αὐτὸν χαλεπῆς τετυχηκέναι ἔφη·",
    en: "he could not have had even a nurse to scold him",
    ref: "4.35",
    certainty: "asserted",
  },
  // ----------------------------------------------------------------------- Bion
  {
    id: "bion-soft-cheese-hook",
    philosopher: "Bion",
    topic: "wit",
    gloss:
      "Reproached for not paying court to a youth: you can't get hold of a soft cheese with a hook.",
    grc: "οὐχ οἷόντε, εἶπεν, ἁπαλὸν τυρὸν ἀγκίστρῳ ἐπισπᾶσθαι.",
    en: "You can't get hold of a soft cheese with a hook.",
    ref: "4.47",
    certainty: "asserted",
  },
  {
    id: "bion-anxiety-ambition",
    philosopher: "Bion",
    topic: "fortune",
    gloss:
      "Who suffers most from anxiety? He who is ambitious of the greatest prosperity.",
    grc: "ἐρωτηθείς ποτε τίς μᾶλλον ἀγωνιᾷ, ἔφη, ὁ τὰ μέγιστα βουλόμενος εὐημερεῖν.",
    en: "Being once asked who suffers most from anxiety, he replied, He who is ambitious of the greatest prosperity.",
    ref: "4.48",
    certainty: "asserted",
  },
  {
    id: "bion-marriage-dilemma",
    philosopher: "Bion",
    topic: "wit",
    gloss:
      "On whether to marry: an ugly wife will be your bane; a beautiful one you will not keep to yourself.",
    grc: "ἐὰν μὲν γήμῃς αἰσχράν, ἕξεις ποινήν· ἂν δὲ καλήν, ἕξεις κοινήν.",
    en: "If the wife you marry be ugly, she will be your bane; if beautiful, you will not keep her to yourself.",
    ref: "4.48",
    certainty: "reported",
    note: "D.L. flags the attribution: 'for this story is also told of Bion.'",
  },
  {
    id: "bion-old-age-harbour",
    philosopher: "Bion",
    topic: "fortune",
    gloss: "Old age is the harbour of all ills: they all take refuge there.",
    grc: "τὸ γῆρας ἔλεγεν ὅρμον εἶναι τῶν κακῶν· εἰς αὐτὸ γοῦν πάντα καταφεύγειν.",
    en: "He called old age the harbour of all ills; at least they all take refuge there.",
    ref: "4.48",
    certainty: "asserted",
  },
  {
    id: "bion-road-to-hades",
    philosopher: "Bion",
    topic: "death",
    gloss:
      "The road to Hades is easy to travel - men pass away with their eyes shut.",
    grc: "εὔκολον ἔφασκε τὴν εἰς ᾅδου ὁδόν· καταμύοντας γοῦν ἀπιέναι.",
    en: "The road to Hades, he used to say, was easy to travel; at any rate men passed away with their eyes shut.",
    ref: "4.49",
    certainty: "asserted",
  },
  {
    id: "bion-pirates-discovered",
    philosopher: "Bion",
    topic: "wit",
    gloss:
      "Among pirates, when his bad company said 'We are lost if we are discovered': and I too, unless I am discovered.",
    grc: "ἐγὼ δέ γε, φησίν, ἐὰν μὴ γνωσθῶ.",
    en: "And I too, he replied, unless I am discovered.",
    ref: "4.50",
    certainty: "asserted",
  },
  {
    id: "bion-fortune-acquired-him",
    philosopher: "Bion",
    topic: "wealth",
    gloss:
      "Of a wealthy miser: he has not acquired a fortune; the fortune has acquired him.",
    grc: "οὐχ οὗτος, ἔφη, τὴν οὐσίαν κέκτηται, ἀλλʼ ἡ οὐσία τοῦτον.",
    en: "He has not acquired a fortune; the fortune has acquired him.",
    ref: "4.50",
    certainty: "asserted",
  },
  {
    id: "bion-prudence-sight",
    philosopher: "Bion",
    topic: "virtue",
    gloss:
      "Prudence excels the other virtues as much as sight excels the other senses.",
    grc: "τοσοῦτον διαφέρειν τὴν φρόνησιν τῶν ἄλλων ἀρετῶν, ὅσον τὴν ὅρασιν τῶν ἄλλων αἰσθήσεων.",
    en: "Prudence, he said, excels the other virtues as much as sight excels the other senses.",
    ref: "4.51",
    certainty: "asserted",
  },
  {
    id: "bion-judge-me-by-myself",
    philosopher: "Bion",
    topic: "self-sufficiency",
    gloss: "Closing his frank autobiography to Antigonus: it is high time Persaeus and Philonides left off recounting it - judge me by myself.",
    grc: "ὥστε παυσάσθωσαν Περσαῖός τε καὶ Φιλωνίδης ἱστοροῦντες αὐτά· σκόπει δέ με ἐξ ἐμαυτοῦ.",
    en: "It is high time, then, that Persaeus and Philonides left off recounting it. Judge me by myself.",
    ref: "4.47",
    certainty: "asserted",
    to: "Antigonus",
    toRef: "4.46",
  },
  {
    id: "bion-renown-beauty-wealth",
    philosopher: "Bion",
    topic: "fame",
    gloss: "Renown is the mother of virtues; beauty another's good; wealth the sinews of success.",
    grc: "τὴν δόξαν 〈ἀρ〉ετῶν μητέρα εἶναι· τὸ κάλλος ἀλλότριον ἀγαθόν· τὸν πλοῦτον νεῦρα πραγμάτων.",
    en: "Renown he called the mother of virtues; beauty another’s good; wealth the sinews of success.",
    ref: "4.48",
    certainty: "asserted",
  },
  {
    id: "bion-swallowed-your-land",
    philosopher: "Bion",
    topic: "wit",
    gloss: "To one who had devoured his patrimony: the earth swallowed Amphiaraus, but you have swallowed your land.",
    grc: "τὸν μὲν Ἀμφιάραον, ἔφη, ἡ γῆ κατέπιε, σὺ δὲ τὴν γῆν.",
    en: "The earth swallowed Amphiaraus, but you have swallowed your land.",
    ref: "4.48",
    certainty: "asserted",
  },
  {
    id: "bion-bear-an-ill",
    philosopher: "Bion",
    topic: "virtue",
    gloss: "To be unable to bear an ill is itself a great ill.",
    grc: "μέγα κακὸν τὸ μὴ δύνασθαι φέρειν κακόν.",
    en: "To be unable to bear an ill is itself a great ill.",
    ref: "4.48",
    certainty: "asserted",
  },
  {
    id: "bion-grant-favours",
    philosopher: "Bion",
    topic: "pleasure",
    gloss: "He repeatedly said that granting favours is preferable to enjoying the favours of others, which ruins body and soul.",
    grc: "ἔλεγε δὲ συνεχὲς ὅτι αἱρετώτερόν ἐστι τὴν ὥραν ἄλλῳ χαρίζεσθαι ἢ ἀλλοτρίας ἀποδρέπεσθαι· καὶ γὰρ εἰς σῶμα βλάπτεσθαι καὶ εἰς ψυχήν.",
    en: "He used repeatedly to say that to grant favours to another was preferable to enjoying the favours of others. For the latter means ruin to both body and soul.",
    ref: "4.49",
    certainty: "asserted",
  },
  {
    id: "bion-wheat-barley",
    philosopher: "Bion",
    topic: "wit",
    gloss: "Teaching philosophy at Rhodes while the Athenians practised rhetoric - how can I sell barley when what I brought to market is wheat?",
    grc: "πρὸς οὖν τὸν αἰτιασάμενον ἔφη, πυροὺς ἐκόμισα καὶ κριθὰς πιπράσκω;",
    en: "How can I sell barley when what I brought to market is wheat?",
    ref: "4.49",
    certainty: "asserted",
  },
  {
    id: "bion-vessels-hades",
    philosopher: "Bion",
    topic: "death",
    gloss: "Those in Hades would be more severely punished if their water-vessels were whole instead of pierced with holes.",
    grc: "Ἔλεγε δὲ τοὺς ἐν ᾅδου μᾶλλον ἂν κολάζεσθαι εἰ ὁλοκλήροις καὶ μὴ τετρημένοις ἀγγείοις ὑδροφόρουν.",
    en: "He used to say that those in Hades would be more severely punished if the vessels in which they drew water were whole instead of being pierced with holes.",
    ref: "4.50",
    certainty: "asserted",
  },
  {
    id: "bion-plead-stay-away",
    philosopher: "Bion",
    topic: "wit",
    gloss: "To an importunate talker wanting his help: I will satisfy your demand, if you will only get others to plead your cause and stay away yourself.",
    grc: "τὸ ἱκανόν σοι ποιήσω, φησίν, ἐὰν παρακλήτους πέμψῃς καὶ αὐτὸς μὴ ἔλθῃς.",
    en: "I will satisfy your demand, if you will only get others to plead your cause and stay away yourself.",
    ref: "4.50",
    certainty: "asserted",
  },
  {
    id: "bion-conceit-hindrance",
    philosopher: "Bion",
    topic: "wisdom",
    gloss: "Conceit is a hindrance to progress.",
    grc: "τὴν οἴησιν ἔλεγε προκοπῆς ἐγκοπήν.",
    en: "Conceit he styled a hindrance to progress.",
    ref: "4.50",
    certainty: "asserted",
  },
  {
    id: "bion-misers-property",
    philosopher: "Bion",
    topic: "wealth",
    gloss: "Misers take care of property as if it were their own, but benefit from it no more than if it belonged to others.",
    grc: "ἔλεγε τοὺς μικρολόγους τῶν μὲν ὑπαρχόντων ὡς ἰδίων ἐπιμελεῖσθαι, ὡς δʼ ἐξ ἀλλοτρίων μηδὲν ὠφελεῖσθαι.",
    en: "Misers, he said, took care of property as if it belonged to them, but derived no more benefit from it than if it belonged to others.",
    ref: "4.50",
    certainty: "asserted",
  },
  {
    id: "bion-reproach-old-age",
    philosopher: "Bion",
    topic: "wisdom",
    gloss: "We ought not to heap reproaches on old age, seeing that we all hope to reach it.",
    grc: "μὴ δεῖν ἔφασκεν ὀνειδίζειν τὸ γῆρας, εἰς ὅ, ἔφη, πάντες εὐχόμεθα ἐλθεῖν.",
    en: "He used to say that we ought not to heap reproaches on old age, seeing that, as he said, we all hope to reach it.",
    ref: "4.51",
    certainty: "asserted",
  },
  {
    id: "bion-slanderer-grave-face",
    philosopher: "Bion",
    topic: "wit",
    gloss: "To a slanderer showing a grave face: I don't know whether you have met with ill luck, or your neighbour with good.",
    grc: "οὐκ οἶδα, ἔφη, πότερον σοὶ κακὸν γέγονεν ἢ ἄλλῳ ἀγαθόν.",
    en: "I don’t know whether you have met with ill luck, or your neighbour with good.",
    ref: "4.51",
    certainty: "asserted",
  },
  {
    id: "bion-low-birth-free-speech",
    philosopher: "Bion",
    topic: "speech",
    gloss: "Low birth makes a bad partner for free speech: it cows a man, however bold his heart.",
    grc: "τὴν δυσγένειαν πονηρὸν ἔλεγεν εἶναι σύνοικον τῇ παρρησίᾳ· δουλοῖ γὰρ ἄνδρα, κἂν θρασύσπλαγχνός τις ᾖ.",
    en: "low birth made a bad partner for free speech, for— It cows a man, however bold his heart.",
    ref: "4.51",
    certainty: "asserted",
  },
  {
    id: "bion-watch-friends",
    philosopher: "Bion",
    topic: "friendship",
    gloss: "Watch your friends and see what manner of men they are, so as not to be thought to associate with the bad or to decline the friendship of the good.",
    grc: "τοὺς φίλους ὁποῖοι ἂν ὦσι συντηρεῖν, ἵνα μὴ δοκοίημεν πονηροῖς κεχρῆσθαι ἢ χρηστοὺς παρῃτῆσθαι.",
    en: "We ought, he remarked, to watch our friends and see what manner of men they are, in order that we may not be thought to associate with the bad or to decline the friendship of the good.",
    ref: "4.51",
    certainty: "asserted",
  },
  // ------------------------------------------------------------------- Lacydes
  {
    id: "lacydes-statues-distance",
    philosopher: "Lacydes",
    topic: "wit",
    gloss:
      "Sent for by King Attalus, he remarked that statues are best seen from a distance.",
    grc: "τὰς εἰκόνας πόρρωθεν δεῖν θεωρεῖσθαι.",
    en: "When Attalus sent for him, he is said to have remarked that statues are best seen from a distance.",
    ref: "4.60",
    certainty: "reported",
  },
  {
    id: "lacydes-geometry-late",
    philosopher: "Lacydes",
    topic: "education",
    gloss:
      "Studying geometry late and asked 'Is this a proper time?': nay, is it not even yet the proper time?",
    grc: "εἶτα μηδὲ νῦν;",
    en: "To which he replied, Nay, is it not even yet the proper time?",
    ref: "4.60",
    certainty: "asserted",
  },
  // ----------------------------------------------------------------- Carneades
  {
    id: "carneades-without-chrysippus",
    philosopher: "Carneades",
    topic: "education",
    gloss:
      "Of the Stoic he built his career refuting: without Chrysippus where should I have been?",
    grc: "εἰ μὴ γὰρ ἦν Χρύσιππος, οὐκ ἂν ἦν ἐγώ.",
    en: "Without Chrysippus where should I have been?",
    ref: "4.62",
    certainty: "asserted",
  },
  {
    id: "carneades-voice-regulator",
    philosopher: "Carneades",
    topic: "wit",
    gloss:
      "Asked by the gymnasiarch not to shout so loud: then give me something by which to regulate my voice.",
    grc: "καὶ δὸς μέτρον φωνῆς.",
    en: "To which he replied, Then give me something by which to regulate my voice.",
    ref: "4.63",
    certainty: "asserted",
  },
  {
    id: "carneades-nature-destroys",
    philosopher: "Carneades",
    topic: "death",
    gloss:
      "Facing death he would often repeat: Nature which framed this whole will also destroy it.",
    grc: "ἡ συστήσασα φύσις καὶ διαλύσει.",
    en: "Nature which framed this whole will also destroy it.",
    ref: "4.64",
    certainty: "asserted",
  },
];
