/**
 * Curated sayings & apophthegms from Book 6 of Diogenes Laertius' Lives
 * (the Cynics), cited to Hicks section ids (book.section). See sayings.ts
 * for the model and curation rules. Source-internal: every `en` is a
 * verbatim excerpt of its cited section.
 */
import type { Saying } from "../sayings";

export const BOOK6_SAYINGS: Saying[] = [
  // -------------------------------------------------------- Diogenes of Sinope
  {
    id: "diogenes-sinope-lamp",
    philosopher: "Diogenes of Sinope",
    topic: "virtue",
    gloss: "Carried a lit lamp in daylight, 'looking for a man' (an honest human being).",
    grc: "λύχνον μεθʼ ἡμέραν ἅψας περιῄει λέγων ἄνθρωπον ζητῶ.",
    en: "He lit a lamp in broad daylight and said, as he went about, I am looking for a man.",
    ref: "6.41",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-alexander-light",
    philosopher: "Diogenes of Sinope",
    topic: "self-sufficiency",
    gloss: "Offered any boon by Alexander, he asked only that the king stop blocking his sun.",
    grc: "αἴτησόν με ὃ θέλεις. καὶ ὅς, ἀποσκότησόν μου, φησί.",
    en: "Alexander came and stood over him and said, Ask of me any boon you like. To which he replied, Stand out of my light.",
    ref: "6.38",
    to: "Alexander",
    certainty: "asserted",
  },
  {
    // Spoken by Plato (in Diogenes' life), not Diogenes - cross-attributed.
    id: "plato-socrates-gone-mad",
    philosopher: "Plato",
    topic: "wit",
    gloss: "Plato's famous verdict on Diogenes: 'A Socrates gone mad.'",
    grc: "Ἐρωτηθεὶς ὑπό τινος, ποῖός τίς σοι Διογένης δοκεῖ ; Σωκράτης, εἶπε, μαινόμενος.",
    en: "What sort of a man do you consider Diogenes to be? A Socrates gone mad, said he.",
    ref: "6.54",
    certainty: "asserted",
    crossAttributed: true,
  },
  {
    id: "diogenes-sinope-child-cup",
    philosopher: "Diogenes of Sinope",
    topic: "self-sufficiency",
    gloss: "Seeing a child drink from its hands, he threw away his cup as superfluous.",
    grc: "Θεασάμενός ποτε παιδίον ταῖς χερσὶ πῖνον ἐξέρριψε τῆς πήρας τὴν κοτύλην, εἰπών, παιδίον με νενίκηκεν εὐτελείᾳ.",
    en: "observing a child drinking out of his hands, he cast away the cup from his wallet with the words, A child has beaten me in plainness of living.",
    ref: "6.37",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-platos-man",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Mocked Plato's definition of man by producing a plucked fowl.",
    grc: "τίλας ἀλεκτρυόνα εἰσήνεγκεν αὐτὸν εἰς τὴν σχολὴν καί φησιν, οὗτός ἐστιν ὁ Πλάτωνος ἄνθρωπος.",
    en: "Diogenes plucked a fowl and brought it into the lecture-room with the words, Here is Plato’s man.",
    ref: "6.40",
    certainty: "asserted",
    note: "Answering Plato's definition of Man as a featherless biped.",
  },
  {
    id: "diogenes-sinope-trample-vainglory",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Trod on Plato's fine carpets to trample his vanity.",
    grc: "πατῶ τὴν Πλάτωνος κενοσπουδίαν",
    en: "Diogenes trampled upon his carpets and said, I trample upon Plato’s vainglory.",
    ref: "6.26",
    to: "Plato",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-govern-men",
    philosopher: "Diogenes of Sinope",
    topic: "self-sufficiency",
    gloss: "Put up for sale, he said his trade was governing men, and sought a master to buy.",
    grc: "ἀπεκρίνατο, ἀνδρῶν ἄρχειν · καὶ πρὸς τὸν κήρυκα, κήρυσσε, ἔφη, εἴ τις ἐθέλει δεσπότην αὑτῷ πρίασθαι.",
    en: "He replied, Govern men. And he told the crier to give notice in case anybody wanted to purchase a master for himself.",
    ref: "6.29",
    certainty: "reported",
    accordingTo: "Menippus",
  },
  {
    id: "diogenes-sinope-love-of-money",
    philosopher: "Diogenes of Sinope",
    topic: "wealth",
    gloss: "Called the love of money the mother-city of all evils.",
    grc: "τὴν φιλαργυρίαν εἶπε μητρόπολιν πάντων τῶν κακῶν.",
    en: "The love of money he declared to be mother-city of all evils.",
    ref: "6.50",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-good-men-images",
    philosopher: "Diogenes of Sinope",
    topic: "virtue",
    gloss: "Good men are images of the gods; love is the business of the idle.",
    grc: "Τοὺς ἀγαθοὺς ἄνδρας θεῶν εἰκόνας εἶναι· τὸν ἔρωτα σχολαζόντων ἀσχολίαν.",
    en: "Good men he called images of the gods, and love the business of the idle.",
    ref: "6.51",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-exile-philosopher",
    philosopher: "Diogenes of Sinope",
    topic: "fortune",
    gloss: "Reproached with exile, he answered that exile made him a philosopher.",
    grc: "ἀλλὰ τούτου γʼ ἕνεκεν, εἶπεν, ὦ κακόδαιμον, ἐφιλοσόφησα.",
    en: "When some one reproached him with his exile, his reply was, Nay, it was through that, you miserable fellow, that I came to be a philosopher.",
    ref: "6.49",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-reason-or-halter",
    philosopher: "Diogenes of Sinope",
    topic: "wisdom",
    gloss: "For living we need either right reason or a halter (a noose).",
    grc: "συνεχές τε ἔλεγεν εἰς τὸν βίον παρεσκευάσθαι δεῖν λόγον ἢ βρόχον.",
    en: "He would continually say that for the conduct of life we need right reason or a halter.",
    ref: "6.24",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-open-hands",
    philosopher: "Diogenes of Sinope",
    topic: "friendship",
    gloss: "We should reach out to friends with open hands, not closed fists.",
    grc: "ἔλεγε δὲ καὶ δεῖν τὰς χεῖρας ἐπὶ τοὺς φίλους ἐκτείνειν μὴ συγκεκαμμένοις τοῖς δακτύλοις.",
    en: "we ought to stretch out our hands to our friends with the fingers open and not closed.",
    ref: "6.29",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-athenians-lodging",
    philosopher: "Diogenes of Sinope",
    topic: "self-sufficiency",
    gloss: "Pointing to the public porticoes, he said the Athenians had built him homes.",
    grc: "τοὺς Ἀθηναίους ἔφασκε, δεικνὺς τὴν τοῦ Διὸς στοὰν καὶ τὸ Πομπεῖον, αὐτῷ κατεσκευακέναι ἐνδιαιτᾶσθαι.",
    en: "he would say, pointing to the portico of Zeus and the Hall of Processions, that the Athenians had provided him with places to live in.",
    ref: "6.22",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-time-to-marry",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "The right time to marry: for the young not yet, for the old never.",
    grc: "ἐρωτηθεὶς ποίῳ καιρῷ δεῖ γαμεῖν, ἔφη, τοὺς μὲν νέους μηδέπω, τοὺς δὲ πρεσβυτέρους μηδεπώποτε.",
    en: "Being asked what was the right time to marry, Diogenes replied, For a young man not yet: for an old man never at all.",
    ref: "6.54",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-time-for-lunch",
    philosopher: "Diogenes of Sinope",
    topic: "wealth",
    gloss: "The proper time for lunch: for the rich whenever they wish, for the poor whenever they can.",
    grc: "πρὸς τὸν πυθόμενον ποίᾳ ὥρᾳ δεῖ ἀριστᾶν, εἰ μὲν πλούσιος, ἔφη, ὅταν θέλῃ· εἰ δὲ πένης, ὅταν ἔχῃ.",
    en: "To one who asked what was the proper time for lunch, he said, If a rich man, when you will; if a poor man, when you can.",
    ref: "6.40",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-spy-greed",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Captured after Chaeronea and asked who he was, he called himself a spy on Philip's greed.",
    grc: "ἐρωτηθεὶς ὅστις εἴη, ἀπεκρίνατο, κατάσκοπος τῆς σῆς ἀπληστίας",
    en: "being asked who he was, replied, A spy upon your insatiable greed.",
    ref: "6.43",
    to: "Philip",
    certainty: "reported",
    accordingTo: "Dionysius the Stoic",
  },
  // ------------------------- Diogenes of Sinope (expansion, 6.21–6.47)
  {
    id: "diogenes-sinope-strike-no-wood",
    philosopher: "Diogenes of Sinope",
    topic: "education",
    gloss: "Offered his head to Antisthenes' raised staff: no wood is hard enough to drive me away.",
    grc: "παῖε, εἶπεν· οὐ γὰρ εὑρήσεις οὕτω σκληρὸν ξύλον ᾧ με ἀπείρξεις ἕως ἄν τι φαίνῃ λέγων.",
    en: "Strike, for you will find no wood hard enough to keep me away from you, so long as I think you’ve something to say.",
    ref: "6.21",
    to: "Antisthenes",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-school-bile",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Punned Euclides' school (σχολή) into bile (χολή) and Plato's lectures (διατριβή) into waste of time (κατατριβή).",
    grc: "καὶ τὴν μὲν Εὐκλείδου σχολὴν ἔλεγε χολήν, τὴν δὲ Πλάτωνος διατριβὴν κατατριβήν",
    en: "The school of Euclides he called bilious, and Plato’s lectures waste of time, the performances at the Dionysia great peep-shows for fools, and the demagogues the mob’s lacqueys.",
    ref: "6.24",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-man-wisest-silliest",
    philosopher: "Diogenes of Sinope",
    topic: "wisdom",
    gloss: "Man is the most intelligent of animals beside physicians and pilots, the silliest beside diviners and the conceited rich.",
    grc: "ὅτε μὲν ἴδοι κυβερνήτας ἐν τῷ βίῳ καὶ ἰατροὺς καὶ φιλοσόφους, συνετώτατον εἶναι τῶν ζῴων νομίζειν τὸν ἄνθρωπον· ὅτε δὲ πάλιν ὀνειροκρίτας καὶ μάντεις καὶ τοὺς προσέχοντας τούτοις ἢ τοὺς ἐπὶ δόξῃ καὶ πλούτῳ πεφυσημένους, οὐδὲν ματαιότερον νομίζειν ἀνθρώπου.",
    en: "when he saw physicians, philosophers and pilots at their work, he deemed man the most intelligent of all animals; but when again he saw interpreters of dreams and diviners and those who attended to them, or those who were puffed up with conceit of wealth, he thought no animal more silly.",
    ref: "6.24",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-syracuse-olives",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Needled Plato over his Sicilian voyages: did Attica grow no olives?",
    grc: "τί οὖν ἔδει πλεῖν εἰς Συρακούσας; ἢ τότε ἡ Ἀττικὴ οὐκ ἔφερεν ἐλάας;",
    en: "Why then, said Diogenes, did you need to go to Syracuse? Was it that Attica at that time did not grow olives?",
    ref: "6.25",
    to: "Plato",
    certainty: "asserted",
    alsoAttributedTo: "Aristippus",
    note: "Favorinus in his Miscellaneous History attributes the retort to Aristippus.",
  },
  {
    id: "diogenes-sinope-share-not-eat",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Offered Plato a share of his figs: 'I said you might share them, not that you might eat them all up.'",
    grc: "ἔφη, μετασχεῖν εἶπον, οὐ καταφαγεῖν.",
    en: "I said you might share them, not that you might eat them all up.",
    ref: "6.25",
    to: "Plato",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-two-and-two-twenty",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Sent a whole jar of wine when asking for a little: you neither give as asked nor answer as questioned.",
    grc: "σύ, φησίν, ἐὰν ἐρωτηθῇς δύο καὶ δύο πόσα ἐστίν, Εἴκοσιν ἀποκρινῇ; οὕτως οὔτε πρὸς τὰ αἰτούμενα δίδως οὔτε πρὸς τὰ ἐρωτώμενʼ ἀποκρίνῃ.",
    en: "If some one asks you how many two and two are, will you answer, Twenty? So, it seems, you neither give as you are asked nor answer as you are questioned.",
    ref: "6.26",
    to: "Plato",
    certainty: "asserted",
  },
  {
    // Spoken by Plato (in Diogenes' life) - cross-attributed.
    id: "plato-pride-of-another-sort",
    philosopher: "Plato",
    topic: "wit",
    gloss: "Plato's retort to Diogenes trampling his carpets: how much pride you expose by seeming not to be proud.",
    grc: "ὅσον, ὦ Διόγενες, τοῦ τύφου διαφαίνεις, δοκῶν μὴ τετυφῶσθαι.",
    en: "How much pride you expose to view, Diogenes, by seeming not to be proud.",
    ref: "6.26",
    to: "Diogenes",
    certainty: "asserted",
    crossAttributed: true,
  },
  {
    id: "diogenes-sinope-good-boys-lacedaemon",
    philosopher: "Diogenes of Sinope",
    topic: "virtue",
    gloss: "Where in Greece he saw good men: good men nowhere, but good boys at Lacedaemon.",
    grc: "ἄνδρας μέν, εἶπεν, οὐδαμοῦ, παῖδας δʼ ἐν Λακεδαίμονι.",
    en: "Good men nowhere, but good boys at Lacedaemon.",
    ref: "6.27",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-digging-kicking",
    philosopher: "Diogenes of Sinope",
    topic: "virtue",
    gloss: "Men compete in digging and kicking, but no one strives to become a good man.",
    grc: "ἔλεγέ τε περὶ μὲν τοῦ παρορύττειν καὶ λακτίζειν ἀγωνίζεσθαι τοὺς ἀνθρώπους, περὶ δὲ καλοκἀγαθίας μηδένα.",
    en: "He would say that men strive in digging and kicking to outdo one another, but no one strives to become a good man and true.",
    ref: "6.27",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-grammarians-odysseus",
    philosopher: "Diogenes of Sinope",
    topic: "education",
    gloss: "Grammarians hunt the ills of Odysseus while ignorant of their own.",
    grc: "τούς τε γραμματικοὺς ἐθαύμαζε τὰ μὲν τοῦ Ὀδυσσέως κακὰ ἀναζητοῦντας, τὰ δʼ ἴδια ἀγνοοῦντας.",
    en: "he would wonder that the grammarians should investigate the ills of Odysseus, while they were ignorant of their own.",
    ref: "6.27",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-sacrifice-health",
    philosopher: "Diogenes of Sinope",
    topic: "religion",
    gloss: "Men sacrifice to the gods for health, then feast against health in the very sacrifice.",
    grc: "ἐκίνει δʼ αὐτὸν καὶ τὸ θύειν μὲν τοῖς θεοῖς ὑπὲρ ὑγιείας, ἐν αὐτῇ δὲ τῇ θυσίᾳ κατὰ τῆς ὑγιείας δειπνεῖν.",
    en: "He was moved to anger that men should sacrifice to the gods to ensure health and in the midst of the sacrifice should feast to the detriment of health.",
    ref: "6.28",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-fishes-purchasers",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Forbidden to sit down while on sale: fishes find purchasers in whatever position they lie.",
    grc: "οὐδέν, ἔφη, διαφέρει· καὶ γὰρ τοὺς ἰχθῦς ὅπως ἂν κέοιντο πιπράσκεσθαι.",
    en: "It makes no difference, said he, for in whatever position fishes lie, they still find purchasers.",
    ref: "6.29",
    certainty: "reported",
    accordingTo: "Menippus",
  },
  {
    id: "diogenes-sinope-jar-rings-true",
    philosopher: "Diogenes of Sinope",
    topic: "wisdom",
    gloss: "We test a jar by its ring before buying, but judge a man by his looks alone.",
    grc: "θαυμάζειν τʼ ἔφη εἰ χύτραν μὲν καὶ λοπάδα ὠνούμενοι κομποῦμεν· ἄνθρωπον δὲ μόνῃ τῇ ὄψει ἀρκούμεθα.",
    en: "he said he marvelled that before we buy a jar or dish we try whether it rings true, but if it is a man are content merely to look at him.",
    ref: "6.30",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-obey-your-slave",
    philosopher: "Diogenes of Sinope",
    topic: "wisdom",
    gloss: "Told his purchaser Xeniades to obey him, as one obeys an enslaved physician or steersman.",
    grc: "δεῖν πείθεσθαι αὐτῷ, εἰ καὶ δοῦλος εἴη· καὶ γὰρ εἰ ἰατρὸς ἢ κυβερνήτης ἦν δοῦλος, πεισθῆναι ἂν αὐτῷ.",
    en: "You must obey me, although I am a slave; for, if a physician or a steersman were in slavery, he would be obeyed.",
    ref: "6.30",
    to: "Xeniades",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-buried-on-face",
    philosopher: "Diogenes of Sinope",
    topic: "death",
    gloss: "Asked how he wished to be buried: on my face - for down will soon be turned to up.",
    grc: "πυνθανομένου τοῦ Ξενιάδου πῶς αὐτὸν θάψειεν, ἔφη, ἐπὶ πρόσωπον",
    en: "There Xeniades once asked him how he wished to be buried. To which he replied, On my face.",
    ref: "6.31",
    to: "Xeniades",
    certainty: "reported",
    accordingTo: "Eubulus",
    note: "The reason follows in 6.32: 'after a little time down will be converted into up', on Macedon's rise.",
  },
  {
    id: "diogenes-sinope-men-not-scoundrels",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Called for men, then beat off the crowd with his stick: 'It was men I called for, not scoundrels.'",
    grc: "ἀνθρώπους ἐκάλεσα, οὐ καθάρματα",
    en: "It was men I called for, not scoundrels.",
    ref: "6.32",
    certainty: "reported",
    accordingTo: "Hecato",
  },
  {
    id: "diogenes-sinope-meaner-receptacle",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Warned not to spit in a magnificent house, he spat in his host's face - the meanest receptacle he could find.",
    grc: "εἰς τὴν ὄψιν αὐτοῦ ἔπτυσεν, εἰπὼν χείρονα τόπον μὴ εὑρηκέναι.",
    en: "having cleared his throat he discharged the phlegm into the man’s face, being unable, he said, to find a meaner receptacle.",
    ref: "6.32",
    certainty: "asserted",
    alsoAttributedTo: "Aristippus",
  },
  {
    id: "diogenes-sinope-disabled-wallet",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "The truly disabled are not the deaf or blind but those without a wallet (πήρα).",
    grc: "Ἀναπήρους ἔλεγεν οὐ τοὺς κωφοὺς καὶ τυφλούς, ἀλλὰ τοὺς μὴ ἔχοντας πήραν.",
    en: "ought to be applied not to the deaf or blind, but to those who have no wallet",
    ref: "6.33",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-defeat-men-slaves",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "To a boastful Pythian victor: 'I defeat men, you defeat slaves.'",
    grc: "ἐγὼ μὲν οὖν, εἶπεν, ἄνδρας, σὺ δʼ ἀνδράποδα.",
    en: "Nay, I defeat men, you defeat slaves.",
    ref: "6.33",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-stadium-goal",
    philosopher: "Diogenes of Sinope",
    topic: "death",
    gloss: "Told to rest in old age: should a runner slacken near the goal rather than put on speed?",
    grc: "τί δέ, ἔφη, εἰ δόλιχον ἔτρεχον, πρὸς τῷ τέλει ἔδει με ἀνεῖναι καὶ μὴ μᾶλλον ἐπιτεῖναι;",
    en: "What? he replied, if I were running in the stadium, ought I to slacken my pace when approaching the goal? ought I not rather to put on speed?",
    ref: "6.34",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-inside-tavern",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "To Demosthenes retreating deeper into an inn: all the more you will be inside the tavern.",
    grc: "τοσούτῳ μᾶλλον, ἔφη, ἔσῃ ἐν τῷ πανδοκείῳ.",
    en: "All the more you will be inside the tavern.",
    ref: "6.34",
    to: "Demosthenes",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-demagogue-athens",
    philosopher: "Diogenes of Sinope",
    topic: "politics",
    gloss: "Pointed strangers to Demosthenes with his middle finger: there goes the demagogue of Athens.",
    grc: "τὸν μέσον δάκτυλον ἐκτείνας, οὗτος ὑμῖν, ἔφη, ἐστὶν ὁ Ἀθηναίων δημαγωγός.",
    en: "he stretched out his middle finger and said, There goes the demagogue of Athens.",
    ref: "6.34",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-finger-madness",
    philosopher: "Diogenes of Sinope",
    topic: "wisdom",
    gloss: "Most people are so nearly mad that a finger makes all the difference.",
    grc: "τοὺς πλείστους ἔλεγε παρὰ δάκτυλον μαίνεσθαι· ἐὰν οὖν τις τὸν μέσον προτείνας πορεύηται, δόξει τῳ μαίνεσθαι, ἐὰν δὲ τὸν λιχανόν, οὐκέτι.",
    en: "Most people, he would say, are so nearly mad that a finger makes all the difference.",
    ref: "6.35",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-statue-barley",
    philosopher: "Diogenes of Sinope",
    topic: "wealth",
    gloss: "Valuable things sell for nothing and vice versa: a statue fetches 3000 drachmas, a quart of barley-flour two coppers.",
    grc: "τὰ πολλοῦ ἄξια τοῦ μηδενὸς ἔλεγε πιπράσκεσθαι καὶ ἔμπαλιν· ἀνδριάντα γοῦν τρισχιλίων πιπράσκεσθαι, χοίνικα δʼ ἀλφίτων δύο χαλκῶν.",
    en: "Very valuable things, said he, were bartered for things of no value, and vice versa.",
    ref: "6.35",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-tunny-friendship",
    philosopher: "Diogenes of Sinope",
    topic: "friendship",
    gloss: "A would-be pupil threw away the tunny he was given to carry: 'The friendship between you and me was broken by a tunny.'",
    grc: "τὴν σὴν καὶ ἐμὴν φιλίαν σαπέρδης διέλυσε.",
    en: "The friendship between you and me was broken by a tunny.",
    ref: "6.36",
    certainty: "asserted",
    note: "Diocles' version has a half-obol cheese instead of the tunny.",
  },
  {
    id: "diogenes-sinope-all-things-of-wise",
    philosopher: "Diogenes of Sinope",
    topic: "self-sufficiency",
    gloss: "All things belong to the gods; the wise are the gods' friends; friends hold all in common - so all things belong to the wise.",
    grc: "τῶν θεῶν ἐστι πάντα· φίλοι δὲ οἱ σοφοὶ τοῖς θεοῖς· κοινὰ δὲ τὰ τῶν φίλων. πάντʼ ἄρα ἐστὶ τῶν σοφῶν.",
    en: "All things belong to the gods. The wise are friends of the gods, and friends hold things in common. Therefore all things belong to the wise.",
    ref: "6.37",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-god-behind-you",
    philosopher: "Diogenes of Sinope",
    topic: "religion",
    gloss: "To a woman prostrate before the gods in an ungraceful attitude: a god may be standing behind you, for all things are full of his presence.",
    grc: "οὐκ εὐλαβῇ, ὦ γύναι, μή ποτε θεοῦ ὄπισθεν ἑστῶτοσ—πάντα γάρ ἐστιν αὐτοῦ πλήρη—ἀσχημονήσῃς;",
    en: "Are you not afraid, my good woman, that a god may be standing behind you?—for all things are full of his presence—and you may be put to shame?",
    ref: "6.37",
    certainty: "reported",
    accordingTo: "Zoïlus of Perga",
  },
  {
    id: "diogenes-sinope-oppose-courage",
    philosopher: "Diogenes of Sinope",
    topic: "fortune",
    gloss: "To fortune he opposed courage, to convention nature, to passion reason.",
    grc: "ἔφασκε δʼ ἀντιτιθέναι τύχῃ μὲν θάρσος, νόμῳ δὲ φύσιν, πάθει δὲ λόγον.",
    en: "he claimed that to fortune he could oppose courage, to convention nature, to passion reason.",
    ref: "6.38",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-land-in-sight",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "When a long reader neared the blank end of his roll: cheer up, men - land in sight.",
    grc: "θαρρεῖτε, ἔφη, ἄνδρες· γῆν ὁρῶ.",
    en: "Cheer up, my men, cried Diogenes; there’s land in sight.",
    ref: "6.38",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-horns",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Against the 'horns' syllogism he simply touched his forehead: 'I for my part don't see any.'",
    grc: "πρὸς τὸν συλλογισάμενον ὅτι κέρατα ἔχει, ἁψάμενος τοῦ μετώπου, ἐγὼ μέν, ἔφη, οὐχ ὁρῶ.",
    en: "To one who by argument had proved conclusively that he had horns, he said, touching his forehead, Well, I for my part don’t see any.",
    ref: "6.38",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-days-from-sky",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "To a lecturer on celestial phenomena: how many days were you in coming from the sky?",
    grc: "ποσταῖος, ἔφη, πάρει ἀπὸ τοῦ οὐρανοῦ;",
    en: "How many days, asked Diogenes, were you in coming from the sky?",
    ref: "6.39",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-initiated-mire",
    philosopher: "Diogenes of Sinope",
    topic: "religion",
    gloss: "Refused initiation: ludicrous that Agesilaus and Epaminondas dwell in the mire while initiated nobodies live in the Isles of the Blest.",
    grc: "γελοῖον, ἔφη, εἰ Ἀγησίλαος μὲν καὶ Ἐπαμεινώνδας ἐν τῷ βορβόρῳ διάξουσιν, εὐτελεῖς δέ τινες μεμυημένοι ἐν ταῖς μακάρων νήσοις ἔσονται.",
    en: "It would be ludicrous, quoth he, if Agesilaus and Epaminondas are to dwell in the mire, while certain folk of no account will live in the Isles of the Blest because they have been initiated.",
    ref: "6.39",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-dog-comes-back",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Styled a dog by Plato: quite true, for I come back again and again to those who have sold me.",
    grc: "ναί, ἔφη· ἐγὼ γὰρ ἐπανῆλθον ἐπὶ τοὺς πεπρακότας.",
    en: "Quite true, he said, for I come back again and again to those who have sold me.",
    ref: "6.40",
    to: "Plato",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-megarian-ram",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Seeing Megarian sheep jacketed while the children went bare: better to be a Megarian's ram than his son.",
    grc: "ἔφη, λυσιτελέστερόν ἐστι Μεγαρέως κριὸν εἶναι ἢ υἱόν.",
    en: "It’s better, said he, to be a Megarian’s ram than his son.",
    ref: "6.41",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-forgot-helmet",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Struck by a fist: 'how came I to forget to put on a helmet when I walked out?'",
    grc: "Ἡράκλεις, ἔφη, οἷόν με χρῆμʼ ἐλάνθανε τὸ μετὰ περικεφαλαίας περιπατεῖν.",
    en: "Heracles, said he, how came I to forget to put on a helmet when I walked out?",
    ref: "6.41",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-3000-blows",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Paid Meidias back his own words with boxing-gauntlets: 'There are 3000 blows to your credit.'",
    grc: "τῇ ἑξῆς πυκτικοὺς λαβὼν ἱμάντας καὶ καταλοήσας αὐτὸν ἔφη, τρισχίλιαί σοι κεῖνται ἐπὶ τῇ τραπέζῃ.",
    en: "the next day he took a pair of boxing-gauntlets, gave him a thrashing and said, There are 3000 blows to your credit.",
    ref: "6.42",
    to: "Meidias",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-god-forsaken-wretch",
    philosopher: "Diogenes of Sinope",
    topic: "religion",
    gloss: "Asked if he believed in the gods: how not, when I see a god-forsaken wretch like you?",
    grc: "πῶς δέ, εἶπεν, οὐ νομίζω, ὅπου καὶ σὲ θεοῖς ἐχθρὸν ὑπολαμβάνω;",
    en: "How can I help believing in them, said he, when I see a god-forsaken wretch like you?",
    ref: "6.42",
    certainty: "asserted",
    alsoAttributedTo: "Theodorus",
  },
  {
    id: "diogenes-sinope-sprinklings",
    philosopher: "Diogenes of Sinope",
    topic: "religion",
    gloss: "Ritual sprinklings can no more wash away errors of conduct than mistakes in grammar.",
    grc: "ὦ κακόδαιμον, οὐκ ἐπίστασαι ὅτι ὥσπερ τῶν ἐν γραμματικῇ ἁμαρτημάτων περιρραινόμενος οὐκ ἂν ἀπαλλαγείης, οὕτως οὐδὲ τῶν ἐν τῷ βίῳ;",
    en: "Unhappy man, don’t you know that you can no more get rid of errors of conduct by sprinklings than you can of mistakes in grammar?",
    ref: "6.42",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-prayers-seeming-goods",
    philosopher: "Diogenes of Sinope",
    topic: "religion",
    gloss: "Men pray for what seems good to them, not for what is truly good.",
    grc: "ἐνεκάλει τοῖς ἀνθρώποις περὶ τῆς εὐχῆς, αἰτεῖσθαι λέγων αὐτοὺς ἀγαθὰ τὰ αὐτοῖς δοκοῦντα καὶ οὐ τὰ κατʼ ἀλήθειαν.",
    en: "He would rebuke men in general with regard to their prayers, declaring that they asked for those things which seemed to them to be good, not for such as are truly good.",
    ref: "6.42",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-graceless",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "On Alexander's letter to Antipater carried by one Athlios: graceless son of graceless sire to graceless wight by graceless squire.",
    grc: "ἄθλιος παρʼ ἀθλίου διʼ ἀθλίου πρὸς ἄθλιον.",
    en: "Graceless son of graceless sire to graceless wight by graceless squire.",
    ref: "6.44",
    certainty: "asserted",
    note: "A pun on the courier's name Athlios ('wretched').",
  },
  {
    id: "diogenes-sinope-beetle-tarantula",
    philosopher: "Diogenes of Sinope",
    topic: "death",
    gloss: "Threatened with death by Perdiccas: nothing wonderful - a beetle or a tarantula would do the same.",
    grc: "ἔφη, οὐδὲν μέγα· καὶ γὰρ κάνθαρος καὶ φαλάγγιον τοῦτʼ ἂν πράξειεν·",
    en: "That’s nothing wonderful, quoth he, for a beetle or a tarantula would do the same.",
    ref: "6.44",
    to: "Perdiccas",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-wipe-your-nose",
    philosopher: "Diogenes of Sinope",
    topic: "pleasure",
    gloss: "To a man whose servant put on his shoes: full felicity will come when he wipes your nose too - once you have lost the use of your hands.",
    grc: "οὔπω, εἶπε, μακάριος εἶ, ἂν μή σε καὶ ἀπομύξῃ· τοῦτο δʼ ἔσται πηρωθέντι σοι τὰς χεῖρας.",
    en: "You have not attained to full felicity, unless he wipes your nose as well; and that will come, when you have lost the use of your hands.",
    ref: "6.44",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-great-thieves",
    philosopher: "Diogenes of Sinope",
    topic: "politics",
    gloss: "Watching temple officials lead off a bowl-thief: the great thieves are leading away the little thief.",
    grc: "ἔφη, οἱ μεγάλοι κλέπται τὸν μικρὸν ἀπάγουσι.",
    en: "The great thieves are leading away the little thief.",
    ref: "6.45",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-lions-skin",
    philosopher: "Diogenes of Sinope",
    topic: "virtue",
    gloss: "To one proud of wearing a lion's skin: stop dishonouring the habiliments of courage.",
    grc: "παῦσαι, ἔφη, τὰ τῆς ἀρετῆς στρώματα καταισχύνων.",
    en: "Leave off dishonouring the habiliments of courage.",
    ref: "6.45",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-callisthenes-ill-fortune",
    philosopher: "Diogenes of Sinope",
    topic: "self-sufficiency",
    gloss: "Callisthenes' splendour in Alexander's suite is ill fortune: he breakfasts and dines when Alexander thinks fit.",
    grc: "κακοδαίμων μὲν οὖν ἐστιν, εἶπεν, ὃς καὶ ἀριστᾷ καὶ δειπνεῖ ὅταν Ἀλεξάνδρῳ δόξῃ.",
    en: "Not so, said Diogenes, but rather ill fortune; for he breakfasts and dines when Alexander thinks fit.",
    ref: "6.45",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-alms-repayment",
    philosopher: "Diogenes of Sinope",
    topic: "friendship",
    gloss: "Short of money, he asked friends not for alms but for repayment of his due.",
    grc: "Χρημάτων δεόμενος ἀπαιτεῖν ἔλεγε τοὺς φίλους, οὐκ αἰτεῖν.",
    en: "Being short of money, he told his friends that he applied to them not for alms, but for repayment of his due.",
    ref: "6.46",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-golden-fleece",
    philosopher: "Diogenes of Sinope",
    topic: "wealth",
    gloss: "An ignorant rich man is a sheep with the golden fleece.",
    grc: "τὸν ἀμαθῆ πλούσιον πρόβατον εἶπε χρυσόμαλλον.",
    en: "An ignorant rich man he used to call the sheep with the golden fleece.",
    ref: "6.47",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-dirty-bath",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Of a dirty public bath: when people have bathed here, where do they go to get clean?",
    grc: "οἱ ἐνθάδε, ἔφη, λουσάμενοι ποῦ λοῦνται;",
    en: "When people have bathed here, where are they to go to get clean?",
    ref: "6.47",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-stout-musician",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Alone praised a stout musician: being so big, he sings to his lute and does not turn brigand.",
    grc: "ἔφη, ὅτι τηλικοῦτος ὢν κιθαρῳδεῖ καὶ οὐ λῃστεύει.",
    en: "Because being so big, he yet sings to his lute and does not turn brigand.",
    ref: "6.47",
    certainty: "asserted",
  },
  // ------------------------- Diogenes of Sinope (expansion, 6.48–6.61)
  {
    id: "diogenes-sinope-chanticleer",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Hailed the deserted musician as chanticleer: your song makes every one get up.",
    grc: "ὅτι, ἔφη, ᾅδων πάντας ἐγείρεις.",
    en: "Because your song makes every one get up.",
    ref: "6.48",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-sneeze-left",
    philosopher: "Diogenes of Sinope",
    topic: "religion",
    gloss: "To a superstitious man threatening a blow: with one sneeze from the left I will make you tremble.",
    grc: "ἐγὼ δέ γε, εἶπε, πταρὼν ἐξ ἀριστερῶν τρέμειν σε ποιήσω.",
    en: "And I, said Diogenes, by a sneeze from the left will make you tremble.",
    ref: "6.48",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-painted-figs",
    philosopher: "Diogenes of Sinope",
    topic: "education",
    gloss: "To Hegesias asking for his writings: you don't choose painted figs over real ones, yet pass over true training for written rules.",
    grc: "μάταιος, ἔφη, τυγχάνεις, ὦ Ἡγησία, ὃς ἰσχάδας μὲν γραπτὰς οὐχ αἱρῇ, ἀλλὰ τὰς ἀληθινάς· ἄσκησιν δὲ παριδὼν τὴν ἀληθινὴν ἐπὶ τὴν γεγραμμένην ὁρμᾷς.",
    en: "You are a simpleton, Hegesias; you do not choose painted figs, but real ones; and yet you pass over the true training and would apply yourself to written rules.",
    ref: "6.48",
    to: "Hegesias",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-home-staying",
    philosopher: "Diogenes of Sinope",
    topic: "fortune",
    gloss: "The Sinopeans sentenced him to exile - 'And I them to home-staying.'",
    grc: "ἐγὼ δέ γε, εἶπεν, ἐκείνων μονήν.",
    en: "And I them, said he, to home-staying.",
    ref: "6.49",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-athletes-pork",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Why athletes are stupid: they are built up of pork and beef.",
    grc: "ἔφη, ὅτι κρέασιν ὑείοις καὶ βοείοις ἀνῳκοδόμηνται.",
    en: "Because they are built up of pork and beef.",
    ref: "6.49",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-begging-statue",
    philosopher: "Diogenes of Sinope",
    topic: "self-sufficiency",
    gloss: "Begged alms of a statue to get practice in being refused.",
    grc: "μελετῶ, εἶπεν, ἀποτυγχάνειν.",
    en: "To get practice in being refused.",
    ref: "6.49",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-harmodius-bronze",
    philosopher: "Diogenes of Sinope",
    topic: "politics",
    gloss: "Asked by a tyrant what bronze is best for a statue: that of which Harmodius and Aristogiton were moulded.",
    grc: "ἔφη, ἀφʼ οὗ Ἁρμόδιος καὶ Ἀριστογείτων ἐχαλκεύθησαν.",
    en: "That of which Harmodius and Aristogiton were moulded.",
    ref: "6.50",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-dionysius-purses",
    philosopher: "Diogenes of Sinope",
    topic: "friendship",
    gloss: "How Dionysius treats his friends: like purses - hung up while full, thrown away when empty.",
    grc: "ἔφη, ὡς θυλάκοις, τοὺς μὲν πλήρεις κρημνῶν, τοὺς δὲ κενοὺς ῥίπτων.",
    en: "Like purses, he replied; so long as they are full, he hangs them up, and, when they are empty, he throws them away.",
    ref: "6.50",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-after-war-alliance",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Under a newlywed's door-inscription barring evil, he wrote: 'After war, alliance.'",
    grc: "ἐπέγραψε· μετὰ τὸν πόλεμον ἡ συμμαχία.",
    en: "After war, alliance.",
    ref: "6.50",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-breakfast-dinner",
    philosopher: "Diogenes of Sinope",
    topic: "wealth",
    gloss: "To a spendthrift eating olives in a tavern: had you breakfasted so, you would not so be dining.",
    grc: "εἰ οὕτως ἠρίστας, οὐκ ἂν οὕτως ἐδείπνεις.",
    en: "If you had breakfasted in this fashion, you would not so be dining.",
    ref: "6.50",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-old-man-destitute",
    philosopher: "Diogenes of Sinope",
    topic: "fortune",
    gloss: "What is wretched in life: an old man destitute.",
    grc: "ἐρωτηθεὶς τί ἄθλιον ἐν βίῳ, ἔφη, γέρων ἄπορος.",
    en: "To the question what is wretched in life he replied, An old man destitute.",
    ref: "6.51",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-sycophant-flatterer",
    philosopher: "Diogenes of Sinope",
    topic: "speech",
    gloss: "The worst bite: among wild beasts the sycophant's, among tame ones the flatterer's.",
    grc: "ἔφη, τῶν μὲν ἀγρίων συκοφάντης, τῶν δὲ ἡμέρων κόλαξ.",
    en: "Of those that are wild a sycophant’s; of those that are tame a flatterer’s.",
    ref: "6.51",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-honeyed-halter",
    philosopher: "Diogenes of Sinope",
    topic: "speech",
    gloss: "Ingratiating speech is honey used to choke you.",
    grc: "τὸν πρὸς χάριν λόγον ἔφη μελιτίνην ἀγχόνην εἶναι.",
    en: "Ingratiating speech he compared to honey used to choke you.",
    ref: "6.51",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-stomach-charybdis",
    philosopher: "Diogenes of Sinope",
    topic: "pleasure",
    gloss: "The stomach is livelihood's Charybdis.",
    grc: "τὴν γαστέρα Χάρυβδιν ἔλεγε τοῦ βίου.",
    en: "The stomach he called livelihood’s Charybdis.",
    ref: "6.51",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-gold-pale",
    philosopher: "Diogenes of Sinope",
    topic: "wealth",
    gloss: "Why gold is pale: it has so many thieves plotting against it.",
    grc: "ἔφη, ὅτι πολλοὺς ἔχει τοὺς ἐπιβουλεύοντας.",
    en: "Because it has so many thieves plotting against it.",
    ref: "6.51",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-tablehood-cuphood",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Against Plato's Ideas: table and cup I see, but tablehood and cuphood nowise.",
    grc: "ἐγώ, εἶπεν, ὦ Πλάτων, τράπεζαν μὲν καὶ κύαθον ὁρῶ· τραπεζότητα δὲ καὶ κυαθότητα οὐδαμῶς·",
    en: "Table and cup I see; but your tablehood and cuphood, Plato, I can nowise see.",
    ref: "6.53",
    to: "Plato",
    certainty: "asserted",
  },
  {
    // Spoken by Plato (in Diogenes' life) - cross-attributed.
    id: "plato-eyes-not-understanding",
    philosopher: "Plato",
    topic: "wit",
    gloss: "Plato's answer on the Ideas: you have the eyes to see table and cup, but not the understanding for tablehood and cuphood.",
    grc: "κατὰ λόγον, ἔφη· οἷς μὲν γὰρ κύαθος καὶ τράπεζα θεωρεῖται, ὀφθαλμοὺς ἔχεις· ᾧ δὲ τραπεζότης καὶ κυαθότης βλέπεται, νοῦν οὐκ ἔχεις.",
    en: "That’s readily accounted for, said Plato, for you have the eyes to see the visible table and cup; but not the understanding by which ideal tablehood and cuphood are discerned.",
    ref: "6.53",
    certainty: "asserted",
    crossAttributed: true,
  },
  {
    id: "diogenes-sinope-blush-virtue",
    philosopher: "Diogenes of Sinope",
    topic: "virtue",
    gloss: "To a blushing youth: courage - that is the hue of virtue.",
    grc: "θάρρει, ἔφη· τοιοῦτόν ἐστι τῆς ἀρετῆς τὸ χρῶμα.",
    en: "Courage, quoth he, that is the hue of virtue.",
    ref: "6.54",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-wine-others-pay",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "The wine he found pleasant to drink: that for which other people pay.",
    grc: "ἐρωτηθεὶς ποῖον οἶνον ἡδέως πίνει, ἔφη, τὸν ἀλλότριον.",
    en: "To the question what wine he found pleasant to drink, he replied, That for which other people pay.",
    ref: "6.54",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-not-laughed-down",
    philosopher: "Diogenes of Sinope",
    topic: "fame",
    gloss: "Told that many laughed at him: 'But I am not laughed down.'",
    grc: "ἀλλʼ ἐγώ, ἔφη, οὐ καταγελῶμαι.",
    en: "But I am not laughed down.",
    ref: "6.54",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-living-ill",
    philosopher: "Diogenes of Sinope",
    topic: "wisdom",
    gloss: "Life is not an evil - living ill is.",
    grc: "οὐ τὸ ζῆν, εἶπεν, ἀλλὰ τὸ κακῶς ζῆν.",
    en: "Not life itself, but living ill.",
    ref: "6.55",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-manes",
    philosopher: "Diogenes of Sinope",
    topic: "self-sufficiency",
    gloss: "Refused to chase his runaway slave: absurd if Manes lives without Diogenes, but Diogenes cannot without Manes.",
    grc: "γελοῖον, ἔφη, εἰ Μάνης μὲν χωρὶς Διογένους ζῇ, Διογένης δὲ χωρὶς Μάνου οὐ δυνήσεται.",
    en: "It would be absurd, if Manes can live without Diogenes, but Diogenes cannot get on without Manes.",
    ref: "6.55",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-beggars-philosophers",
    philosopher: "Diogenes of Sinope",
    topic: "wisdom",
    gloss: "People give to beggars, not philosophers: they expect they may be lame or blind one day, but never philosophers.",
    grc: "ἔφη, ὅτι χωλοὶ μὲν καὶ τυφλοὶ γενέσθαι ἐλπίζουσι, φιλοσοφῆσαι δʼ οὐδέποτε.",
    en: "Because they think they may one day be lame or blind, but never expect that they will turn to philosophy.",
    ref: "6.56",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-food-not-funeral",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "To a slow miser: it's for food that I'm asking, not for funeral expenses.",
    grc: "ἄνθρωπε, εἶπεν, εἰς τροφήν σε αἰτῶ, οὐκ εἰς ταφήν.",
    en: "My friend, it’s for food that I’m asking, not for funeral expenses.",
    ref: "6.56",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-such-as-you",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Reproached with having falsified the currency: such as you are now, I once was; such as I am now, you will never be.",
    grc: "ἦν ποτε χρόνος ἐκεῖνος ὅτʼ ἤμην ἐγὼ τοιοῦτος ὁποῖος σὺ νῦν· ὁποῖος δʼ ἐγὼ νῦν, σὺ οὐδέποτε.",
    en: "That was the time when I was such as you are now; but such as I am now, you will never be.",
    ref: "6.56",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-myndus-gates",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Finding Myndus' gates large and the city small: bar your gates, lest the city run away.",
    grc: "ἄνδρες Μύνδιοι, ἔφη, κλείσατε τὰς πύλας, μὴ ἡ πόλις ὑμῶν ἐξέλθῃ.",
    en: "Men of Myndus, bar your gates, lest the city should run away.",
    ref: "6.57",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-salt-at-athens",
    philosopher: "Diogenes of Sinope",
    topic: "self-sufficiency",
    gloss: "Declined Craterus' hospitality: better a few grains of salt at Athens than sumptuous fare at his table.",
    grc: "ἀλλὰ βούλομαι, ἔφη, ἐν Ἀθήναις ἅλα λείχειν ἢ παρὰ Κρατέρῳ τῆς πολυτελοῦς τραπέζης ἀπολαύειν.",
    en: "I would rather live on a few grains of salt at Athens than enjoy sumptuous fare at Craterus’s table.",
    ref: "6.57",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-anaximenes-fish",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Drew off Anaximenes' audience with a salt fish: an obol's worth of salt fish has broken up his lecture-class.",
    grc: "τὴν Ἀναξιμένους, ἔφη, διάλεξιν ὀβολοῦ τάριχος διαλέλυκεν.",
    en: "An obol’s worth of salt fish has broken up Anaximenes’ lecture-class.",
    ref: "6.57",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-market-hungry",
    philosopher: "Diogenes of Sinope",
    topic: "self-sufficiency",
    gloss: "Reproached for eating in the market-place: it was in the market-place that I felt hungry.",
    grc: "ἐν ἀγορᾷ γάρ, ἔφη, καὶ ἐπείνησα.",
    en: "Well, it was in the market-place, he said, that I felt hungry.",
    ref: "6.58",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-washing-lettuces",
    philosopher: "Diogenes of Sinope",
    topic: "self-sufficiency",
    gloss: "To Plato's 'had you paid court to Dionysius, you wouldn't be washing lettuces': had you washed lettuces, you wouldn't have paid court to Dionysius.",
    grc: "καὶ σὺ εἰ λάχανα ἔπλυνες, οὐκ ἂν Διονύσιον ἐθεράπευες.",
    en: "If you had washed lettuces, you wouldn’t have paid court to Dionysius.",
    ref: "6.58",
    to: "Plato",
    certainty: "reported",
    note: "D.L. introduces the exchange with 'some authors affirm that the following also belongs to him'.",
  },
  {
    id: "diogenes-sinope-philosophy-beauty",
    philosopher: "Diogenes of Sinope",
    topic: "wisdom",
    gloss: "Seeing a youth studying philosophy: well done, Philosophy, that thou divertest admirers of bodily charms to the beauty of the soul.",
    grc: "εὖγε, εἶπεν, ὅτι τοὺς τοῦ σώματος ἐραστὰς ἐπὶ τὸ τῆς ψυχῆς κάλλος μετάγεις.",
    en: "Well done, Philosophy, that thou divertest admirers of bodily charms to the real beauty of the soul.",
    ref: "6.58",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-samothrace-offerings",
    philosopher: "Diogenes of Sinope",
    topic: "religion",
    gloss: "On the votive offerings of the saved at Samothrace: there would be far more if those who were not saved had set up offerings.",
    grc: "ἔφη, πολλῷ ἂν ἦν πλείω εἰ καὶ οἱ μὴ σωθέντες ἀνετίθεσαν·",
    en: "There would have been far more, if those who were not saved had set up offerings.",
    ref: "6.59",
    certainty: "asserted",
    alsoAttributedTo: "Diagoras of Melos",
  },
  {
    id: "diogenes-sinope-mens-to-womens",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Returning from Sparta to Athens, asked whither and whence: from the men's apartments to the women's.",
    grc: "ἐκ τῆς ἀνδρωνίτιδος, εἶπεν, εἰς τὴν γυναικωνῖτιν.",
    en: "From the men’s apartments to the women’s.",
    ref: "6.59",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-crowd-few-men",
    philosopher: "Diogenes of Sinope",
    topic: "wisdom",
    gloss: "Of the crowd at Olympia: a great crowd, but few who could be called men.",
    grc: "πολὺς μέν, εἶπεν, ὁ ὄχλος, ὀλίγοι δʼ οἱ ἄνθρωποι.",
    en: "Yes, he said, a great crowd, but few who could be called men.",
    ref: "6.60",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-alexander-cynic",
    philosopher: "Diogenes of Sinope",
    topic: "self-sufficiency",
    gloss: "To 'I am Alexander the great king' - 'And I am Diogenes the Cynic.'",
    grc: "κἀγώ, φησί, Διογένης ὁ κύων.",
    en: "And I, said he, am Diogenes the Cynic.",
    ref: "6.60",
    to: "Alexander",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-hound-fawn",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Why he is called a hound: I fawn on givers, yelp at refusers, and set my teeth in rascals.",
    grc: "ἔφη, τοὺς μὲν διδόντας σαίνων, τοὺς δὲ μὴ διδόντας ὑλακτῶν, τοὺς δὲ πονηροὺς δάκνων.",
    en: "I fawn on those who give me anything, I yelp at those who refuse, and I set my teeth in rascals.",
    ref: "6.60",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-you-are-dogs",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "To bystanders crying 'dog' at his breakfast: it is you who are dogs, standing round to watch me eat.",
    grc: "ὑμεῖς, εἶπεν, ἐστὲ κύνες, οἵ με ἀριστῶντα περιεστήκατε.",
    en: "It is you who are dogs, cried he, when you stand round and watch me at my breakfast.",
    ref: "6.61",
    certainty: "asserted",
  },
  // ------------------------- Diogenes of Sinope (expansion, 6.62–6.69)
  {
    id: "diogenes-sinope-gift-or-loan",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Asked to return a cloak: if it was a gift, I possess it; if a loan, I am using it.",
    grc: "εἰ μὲν ἐχαρίσω, ἔχω· εἰ δʼ ἔχρησας, χρῶμαι.",
    en: "If it was a gift, replied Diogenes, I possess it; while, if it was a loan, I am using it.",
    ref: "6.62",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-hit-your-father",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "To a courtesan's child throwing stones at a crowd: take care you don't hit your father.",
    grc: "πρόσεχε, ἔφη, μὴ τὸν πατέρα πλήξῃς.",
    en: "Take care you don’t hit your father.",
    ref: "6.62",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-blade-handle",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Of a dagger received from an admirer: a pretty blade with an ugly handle.",
    grc: "ἡ μὲν μάχαιρα, ἔφη, καλή, ἡ δὲ λαβὴ αἰσχρά·",
    en: "A pretty blade with an ugly handle.",
    ref: "6.62",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-prepared-for-fortune",
    philosopher: "Diogenes of Sinope",
    topic: "fortune",
    gloss: "What he gained from philosophy: to be prepared for every fortune.",
    grc: "ἔφη, εἰ καὶ μηδὲν ἄλλο, τὸ γοῦν πρὸς πᾶσαν τύχην παρεσκευάσθαι.",
    en: "This at least, if nothing else—to be prepared for every fortune.",
    ref: "6.63",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-citizen-of-world",
    philosopher: "Diogenes of Sinope",
    topic: "politics",
    gloss: "Asked where he came from: 'I am a citizen of the world' (κοσμοπολίτης).",
    grc: "ἐρωτηθεὶς πόθεν εἴη, κοσμοπολίτης, ἔφη.",
    en: "Asked where he came from, he said, I am a citizen of the world.",
    ref: "6.63",
    certainty: "asserted",
    note: "The first recorded use of the word 'cosmopolitan'.",
  },
  {
    id: "diogenes-sinope-sacrifice-what-manner",
    philosopher: "Diogenes of Sinope",
    topic: "religion",
    gloss: "To parents sacrificing for a son to be born: do you not sacrifice for what manner of man he shall turn out to be?",
    grc: "ἔφη, περὶ δὲ τοῦ ποδαπὸς ἐκβῇ οὐ θύετε;",
    en: "But, said he, do you not sacrifice to ensure what manner of man he shall turn out to be?",
    ref: "6.63",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-sarapis",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "When Athens voted Alexander the title Dionysus: me too you might make Sarapis.",
    grc: "κἀμέ, ἔφη, Σάραπιν ποιήσατε.",
    en: "Me too you might make Sarapis.",
    ref: "6.63",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-sun-cesspools",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Reproached for going into dirty places: the sun too visits cesspools without being defiled.",
    grc: "καὶ γὰρ ὁ ἥλιος, ἔφη, εἰς τοὺς ἀποπάτους, ἀλλʼ οὐ μιαίνεται.",
    en: "his reply was that the sun too visits cesspools without being defiled.",
    ref: "6.63",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-pretender-wisdom",
    philosopher: "Diogenes of Sinope",
    topic: "wisdom",
    gloss: "Told he philosophized without knowledge: even pretending to wisdom is itself philosophy.",
    grc: "ἔφη, εἰ καὶ προσποιοῦμαι σοφίαν, καὶ τοῦτο φιλοσοφεῖν ἐστι.",
    en: "Even if I am but a pretender to wisdom, that in itself is philosophy.",
    ref: "6.64",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-what-need-of-me",
    philosopher: "Diogenes of Sinope",
    topic: "education",
    gloss: "Of a boy praised as gifted and of excellent character: what need then has he of me?",
    grc: "τί οὖν, εἶπεν, ἐμοῦ χρῄζει;",
    en: "What need then, said he, has he of me?",
    ref: "6.64",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-harp",
    philosopher: "Diogenes of Sinope",
    topic: "speech",
    gloss: "Those who say admirable things but fail to do them are like a harp: it has neither hearing nor perception.",
    grc: "τοὺς λέγοντας μὲν τὰ σπουδαῖα, μὴ ποιοῦντας δέ, ἔλεγε μηδὲν διαφέρειν κιθάρας· καὶ γὰρ ταύτην μήτʼ ἀκούειν μήτʼ αἰσθάνεσθαι.",
    en: "Those who say admirable things, but fail to do them, he compared to a harp; for the harp, like them, he said, has neither hearing nor perception.",
    ref: "6.64",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-against-the-stream",
    philosopher: "Diogenes of Sinope",
    topic: "self-sufficiency",
    gloss: "Entering the theatre against the crowd coming out: this is what I practise doing all my life.",
    grc: "τοῦτο, ἔφη, ἐν παντὶ τῷ βίῳ ἐπιτηδεύω ποιεῖν.",
    en: "This, he said, is what I practise doing all my life.",
    ref: "6.64",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-harmonize-soul",
    philosopher: "Diogenes of Sinope",
    topic: "virtue",
    gloss: "To a fool tuning a psaltery: ashamed to tune the wood while failing to harmonize your soul with life?",
    grc: "οὐκ αἰσχύνῃ, ἔφη, τοὺς μὲν φθόγγους τῷ ξύλῳ προσαρμόττων, τὴν δὲ ψυχὴν εἰς τὸν βίον μὴ ἁρμόττων;",
    en: "Are you not ashamed, said he, to give this wood concordant sounds, while you fail to harmonize your soul with life?",
    ref: "6.65",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-why-then-live",
    philosopher: "Diogenes of Sinope",
    topic: "wisdom",
    gloss: "To one claiming to be ill adapted for philosophy: why then do you live, if you do not care to live well?",
    grc: "τί οὖν, ἔφη, ζῇς, εἰ τοῦ καλῶς ζῆν μὴ μέλει σοι;",
    en: "Why then do you live, if you do not care to live well?",
    ref: "6.65",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-despise-father",
    philosopher: "Diogenes of Sinope",
    topic: "virtue",
    gloss: "To one who despised his father: ashamed to despise him to whom you owe your pride?",
    grc: "οὐκ αἰσχύνῃ, ἔφη, καταφρονῶν τούτου διʼ ὃν μέγα φρονεῖς;",
    en: "Are you not ashamed, he said, to despise him to whom you owe it that you can so pride yourself?",
    ref: "6.65",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-lead-dagger",
    philosopher: "Diogenes of Sinope",
    topic: "speech",
    gloss: "To a handsome youth chattering unseemly: ashamed to draw a dagger of lead from an ivory scabbard?",
    grc: "οὐκ αἰσχύνῃ, ἔφη, ἐξ ἐλεφαντίνου κολεοῦ μολυβδίνην ἕλκων μάχαιραν;",
    en: "Are you not ashamed, he said, to draw a dagger of lead from an ivory scabbard?",
    ref: "6.65",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-barber-shop",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Reproached with drinking in a tavern: I also get my hair cut in a barber's shop.",
    grc: "καὶ γὰρ ἐν κουρείῳ, φησί, κείρομαι.",
    en: "Well, said he, I also get my hair cut in a barber’s shop.",
    ref: "6.66",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-gods-gifts",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Reproached with accepting a cloak from Antipater, he answered with Homer: the gods' choice gifts are nowise to be spurned.",
    grc: "ἔφη, οὔτοι ἀπόβλητʼ ἐστὶ θεῶν ἐρικυδέα δῶρα.",
    en: "The gods’ choice gifts are nowise to be spurned.",
    ref: "6.66",
    certainty: "asserted",
    note: "Quoting Iliad 3.65.",
  },
  {
    id: "diogenes-sinope-perfumed-hair",
    philosopher: "Diogenes of Sinope",
    topic: "virtue",
    gloss: "To one with perfumed hair: beware lest the sweet scent on your head cause an ill odour in your life.",
    grc: "βλέπε, εἶπε, μὴ ἡ τῆς κεφαλῆς σου εὐωδία δυσωδίαν σου τῷ βίῳ παράσχῃ.",
    en: "Beware lest the sweet scent on your head cause an ill odour in your life.",
    ref: "6.66",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-lusts-masters",
    philosopher: "Diogenes of Sinope",
    topic: "pleasure",
    gloss: "Bad men obey their lusts as servants obey their masters.",
    grc: "τοὺς μὲν οἰκέτας ἔφη τοῖς δεσπόταις, τοὺς δὲ φαύλους ταῖς ἐπιθυμίαις δουλεύειν.",
    en: "He said that bad men obey their lusts as servants obey their masters.",
    ref: "6.66",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-knees-of-gods",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Why he asked a spendthrift for a mina instead of an obol: whether I shall ever get anything from you again lies on the knees of the gods.",
    grc: "ὅτι, εἶπε, παρὰ μὲν τῶν ἄλλων πάλιν ἐλπίζω λαβεῖν, παρὰ δὲ σοῦ θεῶν ἐν γούνασι κεῖται εἰ πάλιν λήψομαι.",
    en: "Because, said Diogenes, I expect to receive from others again, but whether I shall ever get anything from you again lies on the knees of the gods.",
    ref: "6.67",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-plato-begs-too",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "Reproached with begging when Plato did not: he begs too, but holds his head down close, that none may hear.",
    grc: "κἀκεῖνος, εἶπεν, αἰτεῖ, ἀλλʼ ἄγχι σχὼν κεφαλήν, ἵνα μὴ πευθοίαθʼ οἱ ἄλλοι.",
    en: "Oh yes, says he, he does, but when he does so— He holds his head down close, that none may hear.",
    ref: "6.67",
    certainty: "asserted",
    note: "The hexameter is adapted from Odyssey 1.157.",
  },
  {
    id: "diogenes-sinope-death-not-evil",
    philosopher: "Diogenes of Sinope",
    topic: "death",
    gloss: "Death cannot be an evil: in its presence we are not aware of it.",
    grc: "πῶς, εἶπε, κακός, οὗ παρόντος οὐκ αἰσθανόμεθα;",
    en: "How can it be evil, when in its presence we are not aware of it?",
    ref: "6.68",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-afraid-of-good",
    philosopher: "Diogenes of Sinope",
    topic: "virtue",
    gloss: "Alexander asked 'are you not afraid of me?' - if you are a good thing, who is afraid of the good?",
    grc: "τίς οὖν, εἶπε, τὸ ἀγαθὸν φοβεῖται;",
    en: "Who then, said Diogenes, is afraid of the good?",
    ref: "6.68",
    to: "Alexander",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-education-grace",
    philosopher: "Diogenes of Sinope",
    topic: "education",
    gloss: "Education is a controlling grace to the young, consolation to the old, wealth to the poor, ornament to the rich.",
    grc: "τὴν παιδείαν εἶπε τοῖς μὲν νέοις σωφροσύνην, τοῖς δὲ πρεσβυτέροις παραμυθίαν, τοῖς δὲ πένησι πλοῦτον, τοῖς δὲ πλουσίοις κόσμον εἶναι.",
    en: "Education, according to him, is a controlling grace to the young, consolation to the old, wealth to the poor, and ornament to the rich.",
    ref: "6.68",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-oculist-pupil",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "On the rake Didymon treating a girl's eye: beware lest the oculist, curing the eye, ruin the pupil.",
    grc: "ὅρα, φησί, μὴ τὸν ὀφθαλμὸν τῆς παρθένου θεραπεύων τὴν κόρην φθείρῃς.",
    en: "Beware, says Diogenes, lest the oculist instead of curing the eye should ruin the pupil.",
    ref: "6.68",
    certainty: "asserted",
    note: "The pun works in both languages: κόρη is both 'girl' and 'pupil of the eye'.",
  },
  {
    id: "diogenes-sinope-friends-enemies",
    philosopher: "Diogenes of Sinope",
    topic: "friendship",
    gloss: "To one whose friends were plotting against him: what is to be done, if you must treat friends and enemies alike?",
    grc: "καὶ τί δεῖ πράττειν, ἔφη, εἰ δεήσει τοῖς φίλοις καὶ τοῖς ἐχθροῖς ὁμοίως χρῆσθαι;",
    en: "What is to be done then, if you have to treat friends and enemies alike?",
    ref: "6.68",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-freedom-of-speech",
    philosopher: "Diogenes of Sinope",
    topic: "speech",
    gloss: "The most beautiful thing in the world: freedom of speech (παρρησία).",
    grc: "Ἐρωτηθεὶς τί κάλλιστον ἐν ἀνθρώποις, ἔφη, παρρησία.",
    en: "Being asked what was the most beautiful thing in the world, he replied, Freedom of speech.",
    ref: "6.69",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-muses-pupils",
    philosopher: "Diogenes of Sinope",
    topic: "wit",
    gloss: "In a school with many statues of the Muses but few pupils: by the help of the gods, schoolmaster, you have plenty of pupils.",
    grc: "σὺν θεοῖς, ἔφη, διδάσκαλε, πολλοὺς μαθητὰς ἔχεις.",
    en: "By the help of the gods, said he, schoolmaster, you have plenty of pupils.",
    ref: "6.69",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-ruling-men",
    philosopher: "Diogenes of Sinope",
    topic: "self-sufficiency",
    gloss: "Sold as a slave and asked his proficiency - 'In ruling men' - then pointed at Xeniades: sell me to this man; he needs a master.",
    grc: "ἔφη, τούτῳ με πώλει· οὗτος δεσπότου χρῄζει.",
    en: "Sell me to this man; he needs a master.",
    ref: "6.74",
    certainty: "asserted",
  },
  {
    id: "diogenes-sinope-lions-not-slaves",
    philosopher: "Diogenes of Sinope",
    topic: "self-sufficiency",
    gloss: "Called the friends who wanted to ransom him simpletons: lions are not the slaves of those who feed them - those who feed them are at the mercy of the lions.",
    grc: "οὐδὲ γὰρ τοὺς λέοντας δούλους εἶναι τῶν τρεφόντων, ἀλλὰ τοὺς τρέφοντας τῶν λεόντων.",
    en: "lions are not the slaves of those who feed them, but rather those who feed them are at the mercy of the lions: for fear is the mark of the slave, whereas wild beasts make men afraid of them.",
    ref: "6.75",
    certainty: "reported",
    accordingTo: "Cleomenes",
  },
  // ------------------------- Crates, Metrocles, Hipparchia
  {
    id: "crates-thebes-quart-of-lupins",
    philosopher: "Crates of Thebes",
    topic: "self-sufficiency",
    gloss: "What he gained from philosophy: a quart of lupins and to care for no one.",
    grc: "θέρμων τε χοῖνιξ καὶ τὸ μηδενὸς μέλειν.",
    en: "A quart of lupins and to care for no one.",
    ref: "6.86",
    certainty: "asserted",
  },
  {
    id: "crates-thebes-pomegranate-flaws",
    philosopher: "Crates of Thebes",
    topic: "wisdom",
    gloss: "Impossible to find anybody wholly free from flaws: as in a pomegranate, one of the seeds is always going bad.",
    grc: "ἔλεγέ τʼ ἀδύνατον εἶναι ἀδιάπτωτον εὑρεῖν, ἀλλʼ ὥσπερ ἐν ῥοιᾷ καὶ σαπρόν τινα κόκκον εἶναι.",
    en: "It was, he used to say, impossible to find anybody wholly free from flaws; but, just as in a pomegranate, one of the seeds is always going bad.",
    ref: "6.89",
    certainty: "asserted",
  },
  {
    id: "crates-thebes-hip-joints",
    philosopher: "Crates of Thebes",
    topic: "wit",
    gloss: "Grasping the gymnasiarch's hips while pleading a case: are not these hip-joints yours as much as your knees?",
    grc: "τί γάρ; οὐχὶ καὶ ταῦτα σά ἐστι καθάπερ καὶ τὰ γόνατα;",
    en: "What, are not these hip-joints yours as much as your knees?",
    ref: "6.89",
    certainty: "reported",
    accordingTo: "Favorinus",
  },
  {
    id: "crates-thebes-nicodromus-handiwork",
    philosopher: "Crates of Thebes",
    topic: "wit",
    gloss: "Struck in the face by the musician Nicodromus, he wore a plaster on his forehead inscribed 'Nicodromus's handiwork.'",
    grc: "προσθεὶς οὖν πιττάκιον τῷ μετώπῳ ἐπέγραψε, Νικόδρομος ἐποίει.",
    en: "Nicodromus’s handiwork.",
    ref: "6.89",
    certainty: "asserted",
  },
  {
    id: "crates-thebes-springs-bread",
    philosopher: "Crates of Thebes",
    topic: "self-sufficiency",
    gloss: "Reproached Demetrius of Phalerum for sending bread and wine: oh that the springs yielded bread as well as water!",
    grc: "εἴθε γὰρ αἱ κρῆναι καὶ ἄρτους ἔφερον.",
    en: "Oh that the springs yielded bread as well as water!",
    ref: "6.90",
    to: "Demetrius of Phalerum",
    certainty: "asserted",
  },
  {
    id: "crates-thebes-theophrastus-muslin",
    philosopher: "Crates of Thebes",
    topic: "wit",
    gloss: "To the police-inspectors who faulted his muslin: I'll show you that Theophrastus also wears muslin - and led them to the barber's.",
    grc: "ἔφη, καὶ Θεόφραστον ὑμῖν δείξω σινδόνα περιβεβλημένον·",
    en: "I’ll show you that Theophrastus also wears muslin.",
    ref: "6.90",
    certainty: "asserted",
  },
  {
    id: "crates-thebes-take-heart",
    philosopher: "Crates of Thebes",
    topic: "self-sufficiency",
    gloss: "Laughed at during his exercises, he would say, raising his hands: take heart, Crates, for it is for the good of your eyes and the rest of your body.",
    grc: "θάρρει, Κράτης, ὑπὲρ ὀφθαλμῶν καὶ τοῦ λοιποῦ σώματος·",
    en: "Take heart, Crates, for it is for the good of your eyes and of the rest of your body.",
    ref: "6.91",
    certainty: "asserted",
  },
  {
    id: "crates-thebes-generals-donkey-drivers",
    philosopher: "Crates of Thebes",
    topic: "politics",
    gloss: "We should study philosophy to the point of seeing in generals nothing but donkey-drivers.",
    grc: "ἔλεγε δὲ μέχρι τούτου δεῖν φιλοσοφεῖν, μέχρι ἂν δόξωσιν οἱ στρατηγοὶ εἶναι ὀνηλάται.",
    en: "He used to say that we should study philosophy to the point of seeing in generals nothing but donkey-drivers.",
    ref: "6.92",
    certainty: "asserted",
  },
  {
    id: "crates-thebes-calves-among-wolves",
    philosopher: "Crates of Thebes",
    topic: "friendship",
    gloss: "Those who live with flatterers are as defenceless as calves among wolves: neither has any protector, only plotters.",
    grc: "ἐρήμους ἔλεγε τοὺς μετὰ κολάκων ὄντας ὥσπερ τοὺς μόσχους ἐπειδὰν μετὰ λύκων ὦσιν·",
    en: "Those who live with flatterers he declared to be as defenceless as calves in the midst of wolves; for neither these nor those have any to protect them, but only such as plot against them.",
    ref: "6.92",
    certainty: "asserted",
  },
  {
    id: "crates-thebes-another-alexander",
    philosopher: "Crates of Thebes",
    topic: "politics",
    gloss: "Asked by Alexander whether he wanted Thebes rebuilt: why should it be? Perhaps another Alexander will destroy it again.",
    grc: "ἔφη, καὶ τί δεῖ; πάλιν γὰρ ἴσως Ἀλέξανδρος ἄλλος αὐτὴν κατασκάψει.",
    en: "Why should it be? Perhaps another Alexander will destroy it again.",
    ref: "6.93",
    to: "Alexander",
    certainty: "asserted",
  },
  {
    id: "crates-thebes-ignominy-poverty",
    philosopher: "Crates of Thebes",
    topic: "fortune",
    gloss: "Declared Ignominy and Poverty his country - one Fortune could never take captive.",
    grc: "ἔχειν δὲ πατρίδα ἀδοξίαν καὶ πενίαν ἀνάλωτα τῇ τύχῃ",
    en: "Ignominy and Poverty he declared to be his country, which Fortune could never take captive.",
    ref: "6.93",
    certainty: "asserted",
  },
  {
    // Spoken by Crates in Hipparchia's life (6.96).
    id: "crates-thebes-bridegroom",
    philosopher: "Crates of Thebes",
    topic: "self-sufficiency",
    gloss: "Stripped before Hipparchia's face: this is the bridegroom, here are his possessions - you will be no helpmeet of mine unless you share my pursuits.",
    grc: "ὁ μὲν νυμφίος οὗτος, ἡ δὲ κτῆσις αὕτη",
    en: "This is the bridegroom, here are his possessions; make your choice accordingly; for you will be no helpmeet of mine, unless you share my pursuits.",
    ref: "6.96",
    certainty: "asserted",
    crossAttributed: true,
  },
  {
    id: "metrocles-money-or-time",
    philosopher: "Metrocles",
    topic: "education",
    gloss: "Things divide into what money can buy, like a house, and what only time and trouble procure, like education.",
    grc: "οὗτος ἔλεγε τῶν πραγμάτων τὰ μὲν ἀργυρίου ὠνητὰ εἶναι, οἷον οἰκίαν· τὰ δὲ χρόνου καὶ ἐπιμελείας, ὡς παιδείαν.",
    en: "He divided things into such as are procurable for money, like a house, and such as can be procured by time and trouble, like education.",
    ref: "6.95",
    certainty: "asserted",
  },
  {
    id: "metrocles-wealth-harmful",
    philosopher: "Metrocles",
    topic: "wealth",
    gloss: "Wealth is harmful, unless we put it to a worthy use.",
    grc: "τὸν πλοῦτον βλαβερόν, εἰ μή τις ἀξίως αὐτῷ χρῷτο.",
    en: "Wealth, he said, is harmful, unless we put it to a worthy use.",
    ref: "6.95",
    certainty: "asserted",
  },
  {
    id: "hipparchia-loom-education",
    philosopher: "Hipparchia",
    topic: "education",
    gloss: "To Theodorus's jibe about quitting the loom: do you suppose I was ill advised, if instead of wasting time on the loom I spent it in education?",
    grc: "ἐγώ, φησίν, εἰμί, Θεόδωρε· ἀλλὰ μὴ κακῶς σοι δοκῶ βεβουλεῦσθαι περὶ αὑτῆς, εἰ, τὸν χρόνον ὃν ἔμελλον ἱστοῖς προσαναλώσειν, τοῦτον εἰς παιδείαν κατεχρησάμην;",
    en: "It is I, Theodorus,—but do you suppose that I have been ill advised about myself, if instead of wasting further time upon the loom I spent it in education?",
    ref: "6.98",
    to: "Theodorus",
    certainty: "asserted",
  },
  // ------------------------------------------------------------------ Antisthenes
  {
    id: "antisthenes-mad-not-pleasure",
    philosopher: "Antisthenes",
    topic: "pleasure",
    gloss: "'I'd rather be mad than feel pleasure' - the Cynic's scorn of pleasure.",
    grc: "μανείην μᾶλλον ἢ ἡσθείην",
    en: "I'd rather be mad than feel pleasure",
    ref: "6.3",
    certainty: "asserted",
  },
  {
    id: "antisthenes-royal-privilege",
    philosopher: "Antisthenes",
    topic: "fame",
    gloss: "Told Plato abused him: it is a king's privilege to do good and be ill spoken of.",
    grc: "βασιλικόν, ἔφη, καλῶς ποιοῦντα κακῶς ἀκούειν.",
    en: "It is a royal privilege to do good and be ill spoken of.",
    ref: "6.3",
    certainty: "asserted",
  },
  {
    id: "antisthenes-crows-flatterers",
    philosopher: "Antisthenes",
    topic: "friendship",
    gloss: "Better to fall in with crows than flatterers: the one devour you dead, the other alive.",
    grc: "κρεῖττον ἔλεγε, καθά φησιν Ἑκάτων ἐν ταῖς Χρείαις, εἰς κόρακας ἢ εἰς κόλακας ἐμπεσεῖν· οἱ μὲν γὰρ νεκρούς, οἱ δὲ ζῶντας ἐσθίουσιν.",
    en: "it is better to fall in with crows than with flatterers; for in the one case you are devoured when dead, in the other case while alive.",
    ref: "6.4",
    certainty: "reported",
    accordingTo: "Hecato",
  },
  {
    id: "antisthenes-converse-myself",
    philosopher: "Antisthenes",
    topic: "self-sufficiency",
    gloss: "What philosophy gained him: the ability to hold converse with himself.",
    grc: "ἐρωτηθεὶς τί αὐτῷ περιγέγονεν ἐκ φιλοσοφίας, ἔφη, τὸ δύνασθαι ἑαυτῷ ὁμιλεῖν.",
    en: "The ability to hold converse with myself.",
    ref: "6.6",
    certainty: "asserted",
  },
  {
    id: "antisthenes-unlearn",
    philosopher: "Antisthenes",
    topic: "education",
    gloss: "The most necessary learning: how to get rid of having anything to unlearn.",
    grc: "ἐρωτηθεὶς τί τῶν μαθημάτων ἀναγκαιότατον, τὸ περιαιρεῖν, ἔφη, τὸ ἀπομανθάνειν.",
    en: "How to get rid of having anything to unlearn.",
    ref: "6.7",
    certainty: "asserted",
  },
  {
    id: "antisthenes-virtue-weapon",
    philosopher: "Antisthenes",
    topic: "virtue",
    gloss: "Virtue is a weapon that cannot be taken away.",
    grc: "ἀναφαίρετον ὅπλον ἡ ἀρετή",
    en: "Virtue is a weapon that cannot be taken away.",
    ref: "6.12",
    certainty: "reported",
    accordingTo: "Diocles",
  },
  {
    id: "antisthenes-enemies-mistakes",
    philosopher: "Antisthenes",
    topic: "wisdom",
    gloss: "Attend to your enemies: they are the first to discover your faults.",
    grc: "προσέχειν τοῖς ἐχθροῖς· πρῶτοι γὰρ τῶν ἁμαρτημάτων αἰσθάνονται.",
    en: "Pay attention to your enemies, for they are the first to discover your mistakes.",
    ref: "6.12",
    certainty: "reported",
    accordingTo: "Diocles",
  },
  // ------------------------------------------- Antisthenes (expansion, 6.1–6.13)
  {
    id: "antisthenes-mother-of-gods",
    philosopher: "Antisthenes",
    topic: "wit",
    gloss: "Taunted with his non-Attic blood: the mother of the gods too is a Phrygian.",
    grc: "καὶ ἡ μήτηρ τῶν θεῶν Φρυγία ἐστίν",
    en: "The mother of the gods too is a Phrygian.",
    ref: "6.1",
    certainty: "asserted",
  },
  {
    id: "antisthenes-snails-locusts",
    philosopher: "Antisthenes",
    topic: "wit",
    gloss: "Athenian pride in being sprung from the soil makes them no better born than snails.",
    grc: "ἔλεγε μηδὲν εἶναι κοχλιῶν καὶ ἀττελέβων εὐγενεστέρους.",
    en: "this did not make them any better born than snails or wingless locusts.",
    ref: "6.1",
    certainty: "asserted",
  },
  {
    id: "antisthenes-new-book-new-pen",
    philosopher: "Antisthenes",
    topic: "education",
    gloss: "Told a prospective pupil to come with a new book, pen and tablets - punning on the need for mind (καινοῦ / καὶ νοῦ).",
    grc: "βιβλιαρίου καινοῦ καὶ γραφείου καινοῦ καὶ πινακιδίου καινοῦ, τὸν νοῦν παρεμφαίνων.",
    en: "Come with a new book, a new pen, and new tablets, if you have a mind to",
    ref: "6.3",
    certainty: "asserted",
  },
  {
    id: "antisthenes-what-wife",
    philosopher: "Antisthenes",
    topic: "wit",
    gloss: "On what sort of wife to marry: beautiful, you'll share her; ugly, you'll pay for it.",
    grc: "ἂν μὲν καλήν, ἕξεις κοινήν, ἂν δὲ αἰσχράν, ἕξεις ποινήν.",
    en: "If she's beautiful, you'll not have her to yourself; if she's ugly, you'll pay for it dearly.",
    ref: "6.3",
    certainty: "asserted",
  },
  {
    id: "antisthenes-orphic-why-not-die",
    philosopher: "Antisthenes",
    topic: "religion",
    gloss: "To the Orphic priest promising blessings in Hades: why then don't you die?",
    grc: "τί οὖν, ἔφη, οὐκ ἀποθνήσκεις;",
    en: "Why then, said he, don't you die?",
    ref: "6.4",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wrestlers",
    philosopher: "Antisthenes",
    topic: "wit",
    gloss: "Reproached that his parents were not both free-born: nor were they both wrestlers, yet I am one.",
    grc: "οὐδὲ γὰρ ἐκ δύο, ἔφη, παλαιστικῶν, ἀλλὰ παλαιστικός εἰμι.",
    en: "Nor were they both wrestlers, quoth he, but yet I am a wrestler.",
    ref: "6.4",
    certainty: "asserted",
  },
  {
    id: "antisthenes-silver-rod",
    philosopher: "Antisthenes",
    topic: "education",
    gloss: "Why he had few disciples: he ejects them with a silver rod.",
    grc: "ὅτι ἀργυρέᾳ αὐτοὺς ἐκβάλλω ῥάβδῳ.",
    en: "Because I use a silver rod to eject them.",
    ref: "6.4",
    certainty: "asserted",
  },
  {
    id: "antisthenes-bitter-physicians",
    philosopher: "Antisthenes",
    topic: "education",
    gloss: "Why so bitter in reproving pupils: physicians are just the same with patients.",
    grc: "καὶ οἱ ἰατροί, φησί, τοῖς κάμνουσιν.",
    en: "Physicians are just the same with their patients.",
    ref: "6.4",
    certainty: "asserted",
  },
  {
    id: "antisthenes-adulterer-obol",
    philosopher: "Antisthenes",
    topic: "wit",
    gloss: "Seeing an adulterer fleeing for his life: what peril he might have escaped for an obol.",
    grc: "ὦ δυστυχής, εἶπε, πηλίκον κίνδυνον ὀβολοῦ διαφυγεῖν ἴσχυες.",
    en: "Poor wretch, what peril you might have escaped at the price of an obol.",
    ref: "6.4",
    certainty: "asserted",
  },
  {
    id: "antisthenes-die-happy",
    philosopher: "Antisthenes",
    topic: "death",
    gloss: "The height of human bliss: to die happy.",
    grc: "Ἐρωτηθεὶς τί μακαριώτατον ἐν ἀνθρώποις, ἔφη, τὸ εὐτυχοῦντα ἀποθανεῖν.",
    en: "Being asked what was the height of human bliss, he replied, To die happy.",
    ref: "6.5",
    certainty: "asserted",
  },
  {
    id: "antisthenes-notes-on-mind",
    philosopher: "Antisthenes",
    topic: "education",
    gloss: "To a friend who lost his notes: inscribe them on the mind, not on paper.",
    grc: "ἔδει γάρ, ἔφη, ἐν τῇ ψυχῇ αὐτὰ καὶ μὴ ἐν τοῖς χαρτίοις καταγράφειν.",
    en: "You should have inscribed them, said he, on your mind instead of on paper.",
    ref: "6.5",
    certainty: "asserted",
  },
  {
    id: "antisthenes-envy-rust",
    philosopher: "Antisthenes",
    topic: "virtue",
    gloss: "As rust eats iron, the envious are consumed by their own passion.",
    grc: "ὥσπερ ὑπὸ τοῦ ἰοῦ τὸν σίδηρον, οὕτως ἔλεγε τοὺς φθονεροὺς ὑπὸ τοῦ ἰδίου ἤθους κατεσθίεσθαι.",
    en: "As iron is eaten away by rust, so, said he, the envious are consumed by their own passion.",
    ref: "6.5",
    certainty: "asserted",
  },
  {
    id: "antisthenes-immortality-piety",
    philosopher: "Antisthenes",
    topic: "religion",
    gloss: "Those who would be immortal must live piously and justly.",
    grc: "τοὺς βουλομένους ἀθανάτους εἶναι ἔφη δεῖν εὐσεβῶς καὶ δικαίως ζῆν.",
    en: "Those who would fain be immortal must, he declared, live piously and justly.",
    ref: "6.5",
    certainty: "asserted",
  },
  {
    id: "antisthenes-states-doomed",
    philosopher: "Antisthenes",
    topic: "politics",
    gloss: "States are doomed when they cannot tell good men from bad.",
    grc: "τότʼ ἔφη τὰς πόλεις ἀπόλλυσθαι, ὅταν μὴ δύνωνται τοὺς φαύλους ἀπὸ τῶν σπουδαίων διακρίνειν.",
    en: "States, said he, are doomed when they are unable to distinguish good men from bad.",
    ref: "6.5",
    certainty: "asserted",
  },
  {
    id: "antisthenes-applause-rascals",
    philosopher: "Antisthenes",
    topic: "fame",
    gloss: "Applauded by rascals: 'I am horribly afraid I have done something wrong.'",
    grc: "ἀγωνιῶ μή τι κακὸν εἴργασμαι.",
    en: "I am horribly afraid I have done something wrong.",
    ref: "6.5",
    certainty: "asserted",
  },
  {
    id: "antisthenes-brothers-fortress",
    philosopher: "Antisthenes",
    topic: "friendship",
    gloss: "The common life of brothers in agreement is stronger than any fortress.",
    grc: "Ὁμονοούντων ἀδελφῶν συμβίωσιν παντὸς ἔφη τείχους ἰσχυροτέραν εἶναι.",
    en: "When brothers agree, no fortress is so strong as their common life, he said.",
    ref: "6.6",
    certainty: "asserted",
  },
  {
    id: "antisthenes-shipwreck-outfit",
    philosopher: "Antisthenes",
    topic: "wisdom",
    gloss: "The right provisions for a voyage are those that swim with you from a shipwreck.",
    grc: "τοιαῦτʼ ἔφη δεῖν ποιεῖσθαι ἐφόδια ἃ καὶ ναυαγήσαντι συγκολυμβήσει.",
    en: "The right outfit for a voyage, he said, is such as, even if you are shipwrecked, will go through the water with you.",
    ref: "6.6",
    certainty: "asserted",
  },
  {
    id: "antisthenes-physicians-no-fever",
    philosopher: "Antisthenes",
    topic: "virtue",
    gloss: "Censured for keeping bad company: physicians attend patients without catching the fever.",
    grc: "καὶ οἱ ἰατροί, φησί, μετὰ τῶν νοσούντων εἰσίν, ἀλλʼ οὐ πυρέττουσιν.",
    en: "Well, physicians are in attendance on their patients without getting the fever themselves.",
    ref: "6.6",
    certainty: "asserted",
  },
  {
    id: "antisthenes-darnel-politics",
    philosopher: "Antisthenes",
    topic: "politics",
    gloss: "We weed darnel from corn and the unfit from war, but not evil men from the state.",
    grc: "ἄτοπον ἔφη τοῦ μὲν σίτου τὰς αἴρας ἐκλέγειν καὶ ἐν τῷ πολέμῳ τοὺς ἀχρείους, ἐν δὲ πολιτείᾳ τοὺς πονηροὺς μὴ παραιτεῖσθαι.",
    en: "It is strange, said he, that we weed out the darnel from the corn and the unfit in war, but do not excuse evil men from the service of the state.",
    ref: "6.6",
    certainty: "asserted",
  },
  {
    id: "antisthenes-song-pipe",
    philosopher: "Antisthenes",
    topic: "wit",
    gloss: "Called on for a song over the wine: then you must accompany me on the pipe.",
    grc: "σὺ δέ μοι, φησίν, αὔλησον.",
    en: "Then you must accompany me on the pipe.",
    ref: "6.6",
    certainty: "asserted",
  },
  {
    id: "antisthenes-fold-cloak-double",
    philosopher: "Antisthenes",
    topic: "self-sufficiency",
    gloss: "When Diogenes begged a coat, he bade him fold his cloak double instead.",
    grc: "Διογένει χιτῶνα αἰτοῦντι πτύξαι προσέταξε θοιμάτιον.",
    en: "When Diogenes begged a coat of him, he bade him fold his cloak around him double.",
    ref: "6.6",
    to: "Diogenes",
    certainty: "asserted",
  },
  {
    id: "antisthenes-slander-stones",
    philosopher: "Antisthenes",
    topic: "speech",
    gloss: "Endure slander more courageously than a pelting with stones.",
    grc: "παρεκελεύετό τε κακῶς ἀκούοντας καρτερεῖν μᾶλλον ἢ εἰ λίθοις τις βάλλοιτο.",
    en: "he advised that when men are slandered, they should endure it more courageously than if they were pelted with stones.",
    ref: "6.7",
    certainty: "asserted",
  },
  {
    id: "antisthenes-plato-steed",
    philosopher: "Antisthenes",
    topic: "wit",
    gloss: "Teased the horse-praising Plato: you would have made just such a proud, showy steed.",
    grc: "ἐδόκεις μοι καὶ σὺ ἵππος ἂν εἶναι λαμπρυντής",
    en: "It seems to me that you would have made just such a proud, showy steed.",
    ref: "6.7",
    to: "Plato",
    certainty: "asserted",
  },
  {
    id: "antisthenes-bile-not-pride",
    philosopher: "Antisthenes",
    topic: "wit",
    gloss: "At the sick Plato's basin: 'The bile I see, but not the pride.'",
    grc: "χολὴν μὲν ὁρῶ ἐνταῦθα, τῦφον δὲ οὐχ ὁρῶ.",
    en: "The bile I see, but not the pride.",
    ref: "6.7",
    to: "Plato",
    certainty: "asserted",
  },
  {
    id: "antisthenes-elected-generals",
    philosopher: "Antisthenes",
    topic: "politics",
    gloss: "Urged voting asses to be horses: your generals too are merely elected, not trained.",
    grc: "ἀλλὰ μὴν καὶ στρατηγοί, φησί, φαίνονται παρʼ ὑμῖν μηδὲν μαθόντες, μόνον δὲ χειροτονηθέντες.",
    en: "But yet generals are found among you who had had no training, but were merely elected.",
    ref: "6.8",
    certainty: "asserted",
  },
  {
    id: "antisthenes-praise-what-wrong",
    philosopher: "Antisthenes",
    topic: "fame",
    gloss: "Told that many men praised him: why, what wrong have I done?",
    grc: "τί γάρ, ἔφη, κακὸν πεποίηκα;",
    en: "Why, what wrong have I done? was his rejoinder.",
    ref: "6.8",
    certainty: "asserted",
  },
  {
    // Spoken by Socrates (in Antisthenes' life) - cross-attributed.
    id: "socrates-fame-through-cloak",
    philosopher: "Socrates",
    topic: "fame",
    gloss: "Seeing Antisthenes parade the torn part of his cloak: 'I spy your love of fame peeping through your cloak.'",
    grc: "ὁρῶ σου διὰ τοῦ τρίβωνος τὴν φιλοδοξίαν.",
    en: "I spy your love of fame peeping through your cloak.",
    ref: "6.8",
    certainty: "asserted",
    crossAttributed: true,
  },
  {
    id: "antisthenes-learn-faults",
    philosopher: "Antisthenes",
    topic: "virtue",
    gloss: "How to become good and noble: learn from those who know that your faults are to be avoided.",
    grc: "εἰ τὰ κακὰ ἃ ἔχεις ὅτι φευκτά ἐστι μάθοις παρὰ τὼν εἰδότων.",
    en: "You must learn from those who know that the faults you have are to be avoided.",
    ref: "6.8",
    certainty: "reported",
    accordingTo: "Phanias",
  },
  {
    id: "antisthenes-luxury-enemies",
    philosopher: "Antisthenes",
    topic: "pleasure",
    gloss: "To one extolling luxury: may the sons of your enemies live in luxury.",
    grc: "ἐχθρῶν παῖδες, ἔφη, τρυφήσειαν.",
    en: "May the sons of your enemies live in luxury.",
    ref: "6.8",
    certainty: "asserted",
  },
  {
    id: "antisthenes-bronze-beauty",
    philosopher: "Antisthenes",
    topic: "fame",
    gloss: "To the youth posing as a model: ashamed to delight in the same quality as an inanimate bronze?",
    grc: "οὐκ αἰσχύνῃ οὖν, ἔφη, τὰ ὅμοια γεγηθὼς ἀψύχῳ;",
    en: "Then, said he, are you not ashamed of delighting in the very same quality as an inanimate object?",
    ref: "6.9",
    certainty: "asserted",
  },
  {
    id: "antisthenes-salt-fish",
    philosopher: "Antisthenes",
    topic: "wit",
    gloss: "Charged flour to the account of a youth who kept promising payment when his salt-fish boat came in.",
    grc: "ὁ νεανίσκος, ἔφη, δώσει ἐὰν τὸ πλοῖον αὐτοῦ τῶν ταρίχων ἀφίκηται.",
    en: "The young man will pay, said he, when his boatload of salt fish arrives.",
    ref: "6.9",
    certainty: "asserted",
  },
  {
    id: "antisthenes-wisdom-stronghold",
    philosopher: "Antisthenes",
    topic: "wisdom",
    gloss: "Wisdom is the surest stronghold; walls of defence must be built in our own impregnable reasonings.",
    grc: "Τεῖχος ἀσφαλέστατον φρόνησιν· μήτε γὰρ καταρρεῖν μήτε προδίδοσθαι. τείχη κατασκευαστέον ἐν τοῖς αὑτῶν ἀναλώτοις λογισμοῖς.",
    en: "Wisdom is a most sure stronghold which never crumbles away nor is betrayed. Walls of defence must be constructed in our own impregnable reasonings.",
    ref: "6.13",
    certainty: "asserted",
  },
  {
    id: "antisthenes-good-men-fighting",
    philosopher: "Antisthenes",
    topic: "virtue",
    gloss: "Better with a handful of good men against all the bad than with hosts of bad against the good.",
    grc: "κρεῖττόν ἐστι μετʼ ὀλίγων ἀγαθῶν πρὸς ἅπαντας τοὺς κακοὺς ἢ μετὰ πολλῶν κακῶν πρὸς ὀλίγους ἀγαθοὺς μάχεσθαι.",
    en: "It is better to be with a handful of good men fighting against all the bad, than with hosts of bad men against a handful of good men.",
    ref: "6.12",
    certainty: "reported",
    accordingTo: "Diocles",
  },
  {
    id: "antisthenes-virtue-same-women",
    philosopher: "Antisthenes",
    topic: "virtue",
    gloss: "Virtue is the same for women as for men.",
    grc: "ἀνδρὸς καὶ γυναικὸς ἡ αὐτὴ ἀρετή",
    en: "Virtue is the same for women as for men.",
    ref: "6.12",
    certainty: "reported",
    accordingTo: "Diocles",
  },
];
